qiskit/_quantumprogram.py

minor bug when checking for timeout

fixing timeout bug when timeout is not a multiple of wait time

---

test/python/test_apps.py
test/python/test_jsonoutput.py
test/python/test_local_simulator.py
test/python/test_qasm_python_simulator.py
test/python/test_qi.py
test/python/test_quantumprogram.py
test/python/test_unitary_python_simulator.py

fix profiling after recent changes
"make profile" was broken when the Results object was introduced.
ran "make profile" with error. Verified PDF plot generated.

fix bug in profiling

---

test/python/test_apps.py
test/python/test_jsonoutput.py
test/python/test_local_simulator.py
test/python/test_qasm_python_simulator.py
test/python/test_qi.py
test/python/test_quantumprogram.py
test/python/test_unitary_python_simulator.py

Left some test logging in output. Removed.
Many of the test modules were logging "this is a test" which is probably obvious.

clean logging output

---

Make.bat
README.rst

Solves #29 
A new Make.bat script file has been created to support all the Makefile targets in Windows:
```
Make.bat run
Make.bat test
Make.bat profile
Make.bat doc
Make.bat clean
```
All targets have been executed locally.
There are problems with 'doc' target, because it invokes another Make.bat script file already present in the /doc sub-directory, that is malfunctioning. We will fix it in another issue.

Issue 29 - New Make.bat script to support operating with Windows

---

tools/apps/optimization.py

Energy eval without writing H

---

test/python/test_quantumprogram.py

* Fixes local tests in: test_quantumprogram.py 
* Little clean up and refactor
Local tests were failing because QE_TOKEN was not being properly set.
Locally: make test

Fixes local tests in: test_quantumprogram.py

---

test/python/test_quantumprogram.py

Tests were being skipped for non-pull request builds which was not intended.
make test generated one error with test_execute_one_circuit_real_online which seems unrelated to this change.

fix skip test logic

---

tools/apps/optimization.py

Better use of resources in computing energy for exact states
Significantly improves computing times for exact diagonal Hamiltonians

Faster exact energy calculation

---

setup.py
test/python/test_apps.py
test/python/test_qi.py

* Distributable packages include new tools location into qiskit
* Fixed corresponding tests
Locally: make test
Travis tests passed in my fork.

Pip release: 0.3.4

---

examples/jupyter/quantum_state_tomography_bell_states.ipynb

added the tools import fix to jupyter example, according to issue #57

inserted qiskit folder to tools import

---

test/python/qasm/example_fail.qasm
test/python/test_qasm_parser.py

A couple of simple tests to cover this part of the code.
It only adds:
- The file with the code of the tests.
- Another mock file to write a failing test.
Code good practices.
It´s a test so it doesn´t affect to any other part of the code.
- [ x ] New feature (non-breaking change which adds functionality)
- [ x ] My code follows the code style of this project.
- [ x ] I have read the **CONTRIBUTING** document.
- [ x ] I have added tests to cover my changes.
- [ x ] All new and existing tests passed.

First tests for the parser.

---

qiskit/_quantumprogram.py
test/python/test_quantumprogram.py

Updates IBMQuantumExperience imports because of last version changes

---

qiskit/_openquantumcompiler.py

This code was used for debugging but is not needed

remove debugging code for forks

---

.gitignore
qiskit/qasm/_qasmparser.py

Fixes Issue #69 by forcing Yacc to use the temporary dir to create the auto-generated file: parsetab.py 
make test

Issue 69 - Create parsetab.py autogenerated file in a temporary dir

---

.travis.yml
test/python/_random_circuit_generator.py

Add python 3.5 to the travis config file, so the CI runs two separate jobs (one on each Python version environment).
Further automated testing support.

Add Python 3.5 to travis.yml

---

README.md

Typo in the README ('superpesition' => 'superposition')

Fixed doc typo

---

README.md
examples/python/rippleadd-async.py
qiskit/__init__.py
qiskit/_jobprocessor.py
qiskit/_quantumjob.py
qiskit/_result.py
qiskit/_resulterror.py
test/python/test_job_processor.py
test/python/test_quantumprogram.py

This is an improvement for better error management when there's a problem with a job in the backend.
Now, if there's an exception caused by an erroneous result sent by the backend, the corresponding exception is embedded into the result object so the user can differentiate between various exceptions in her code.
A refactoring of some related classes has been made to improve readability. 
We had to change some tests.
All tests passed locally and remotely (Travis)
- [] New feature (non-breaking change which adds functionality)

Better error handling with backends

---

README.md

Fix link, style example, add PyPi badge on README

---

qiskit/tools/qcvv/fitters.py

Fix spelling and add grid to plot
measurement misspelled in the fitter. Looks better with grid.

update coherence fitter 

---

qiskit/tools/qcvv/fitters.py

Added an rb fit function and plot.
Future consideration for RB.
- [x ] New feature (non-breaking change which adds functionality)

Added some rb fits

---

qiskit/tools/apps/optimization.py

Fixed a bug due to a wrong line breaking after linting

Optimization bug line breaking

---

CODE_OF_CONDUCT.md

Code of Conduct!

---

qiskit/_jobprocessor.py
qiskit/_qiskiterror.py
qiskit/_quantumprogram.py
qiskit/_resulterror.py
qiskit/qasm/_qasmparser.py

Fix a number of linting and PEP8 issues:
* revise docstrings (parameters, return types, raises)
* indenting errors
* unused imports
* other misc. fixes
Get closer to the goal of having an usable `make lint` pass, in particular for `QuantumProgram`, now that there are not so many PR open that might lead to conflicts.
`make test`

Linting and style fixes in several files

---

qiskit/_util.py

Make "_check_ibmqe_version()" be more robust when checking the version
available of IBMQuantumExperience:
* try to use `__version__` (not available until the next release of
IBMQuantumExperience 1.8.14).
* support environments where IBMQuantumExperience is not installed but
it is available (for example, placed on a reachable PYTHONPATH).
Be more flexible and avoid emitting the warning if the user has the dependency available, but not installed via `pip`. 
`make test` plus simulating the conditions for the new changes (ie. IBMQuantumExperience on the PYTHONPATH instead of installed as a package).

Allow local IBMQuantumExperience packages on _check_ibmqe_version

---

qiskit/_result.py

Spelling mistake correction

---

appveyor.yml
qiskit/_util.py

Add CI integration with appveyor, using two jobs (Python 3.5 and 3.6)
and display of individual tests running the suite via pytest and
exporting to xml instead of running unittest. The build is setup to use
anaconda instead of plain pip due to scipy not being able to build
directly in Windows if installed via pip.
Allow automated testing in Windows.

Add appveyor integration

---

README.md

DOC: README.md: Jupyter notebooks are

---

qiskit/qasm/_qasmparser.py

This change addresses issue #190 
This has been tested against the example submitted in the issue and make test.
make test returned errors because Quantum Experience is currently down for maintenance. The number of errors was the same as performing the tests in the master branch. I do not include new tests.

Precedence issue 190

---

README.md
doc/example_real_backend.rst
doc/install.rst

Documentation update for the IBM Q features.

Add documentation for set_api with IBM Q features

---

DEVELOPMENT_CYCLE.md

Fix typos in DEVELOPMENT_CYCLE.md
less typos better reading 🤗
Proof reading

Fix typos in DEVELOPMENT_CYCLE.md

---

qiskit/_quantumprogram.py
setup.py

[WIP] Small tweaks for IBM Q and upcoming release

---

appveyor.yml

Disable appveyor, as it is causing some issues since the latest 4.4.0
conda release.

Temporarily disable appveyor due to conda 4.4.0

---

qiskit/_quantumprogram.py

Revise the handling of the CredentialsError exception raised by the
API during `set_api`, in order to make the output less verbose by just
showing the last Exception instead of the full chained list. For the
rest of Exceptions, the original behaviour is preserved.

Revise the handling of the 401 license Exception

---

qiskit/tools/qi/qi.py
test/python/test_qi.py

Added some additional features to qi module and improved some older functions:
- partial trace more efficient if input is a state vector
- Added several entropy and mutual information functions
- Added functions for generating random density matrices
- fixed a couple of bugs with chop function, and for list inputs of state vectors
Unit tests pass on Python 3.6
- [] Breaking change (fix or feature that would cause existing functionality to change)
- [] I have updated the documentation accordingly.

Adding some quantum information functions to qi module

---

qiskit/extensions/quantum_initializer/_initializer.py
test/python/test_initializer.py

Tests InitializeGate's functionality with Sympy
Adds one more test case to `test/python/test_initializer.py`
Complex numbers are currently not converted into symbolic form (in `qiskit/_instruction.py`). This is an attempt to check possible bugs due to this.

one more initializer test case

---

README.md
doc/dev_introduction.rst
doc/example_real_backend.rst
doc/index.rst
doc/install.rst
qiskit/_quantumprogram.py
qiskit/extensions/__init__.py

* Fix the sphinx warnings when building the documentation.
* Round of small fixes (spelling, word wrapping, typos, comments).
* Revise the informatio about installing in Mac OS (thanks to comment by Hanhee) and pointers to the wiki.

Documentation fixes and changes

---

requirements.txt
setup.py
test/python/test_apps.py

Revise the dependencies in order to:
* drop `requests`, as it is not needed directly by the SDK
* for several packages, test that the most recent *major* versions of
them work with QISKit, and adjust the comparators accordingly.
* fix a test that was failing due to the precision.

Revise dependencies, allow more recent versions

---

appveyor.yml

Re-enable the AppVeyor CI, as the conflicts with the version were
hopefully solved after bumping the scipy dependency and others.

Reintroduce AppVeyor integration

---

.travis.yml
qiskit/tools/qi/qi.py

flake8 points out three undefined names

Three undefined names

---

doc/install.rst

Clarify the installation instructions at the autodoc, emphasizing that
PIP install and git install are alternatives and not consecutive
steps.

Revise Sphinx installation instructions

---

qiskit/dagcircuit/_dagcircuit.py
qiskit/unroll/_dagbackend.py

Several small improvements for mapper developers

A few improvements for mapper

---

Makefile
test/python/test_apps.py
test/python/test_basebackend.py
test/python/test_extensions_standard.py
test/python/test_job_processor.py
test/python/test_local_qiskit_simulator.py
test/python/test_projectq_cpp_simulator.py
test/python/test_qasm_python_simulator.py
test/python/test_quantumprogram.py
test/python/test_unitary_python_simulator.py

Minor fixes for the tests:
* use subtests in several places, for easier identification of the
failing assertions in loops.
* style, variable names, and typo fixes.
* add cleanup of the files generated by the tests to the `make clean`
target.

Test fixes: subtests, names, make clean

---

pypi.sh
qiskit/__init__.py
qiskit/backends/_qiskit_cpp_simulator.py
setup.py
src/cpp-simulator/README.md
src/cpp-simulator/src/Makefile
src/cpp-simulator/src/backends/ideal_backend.hpp
src/cpp-simulator/src/backends/noise_models.hpp
src/cpp-simulator/src/utilities/types.hpp
src/cpp-simulator/test/inputs/reset_error.json
src/cpp-simulator/test/refs/reset_error.ref

@chriseclectic has fixed an issue with the C++ Simulator that required a new release version.
I have taken this opportunity to introduce some changes in the way we create distributable packages to allow us compile with certain flags without changing the Makefile back and forth every time we release.

Stable 0.4.7 fix cpp sim

---

qiskit/backends/_qiskit_cpp_simulator.py

Fixes issue #271 for error in the `__parse_noise_params` function in `_qiskit_cpp_backend.py`

Fixes issue #271

---

.pylintrc
Makefile
qiskit/tools/apps/fermion.py
qiskit/tools/apps/optimization.py
qiskit/tools/file_io.py
qiskit/tools/qcvv/fitters.py
qiskit/tools/qcvv/tomography.py
qiskit/tools/qi/pauli.py
qiskit/tools/qi/qi.py
qiskit/tools/visualization.py

Convert `qiskit.tools` to real Python modules by adding` __init__.py`,
adding lint and style fixes in the process.
Enable style and lint Travis check for qiskit.tools.
The directories on `qiskit.tools` were not "real modules" due to the lack of `__init__.py` files on them, which made them not fall in line with the rest of the codebase and slight issues with the overall tooling (for example, they were not picked up by the linter for that reason). With this change and the style/docstring fixes, they are now the same as the rest of the codebase in that regard.

Make qiskit.tools modules, with linting

---

CONTRIBUTING.rst

Small changes to `CONTRIBUTING.rst`:
* fix some typos
* move the "Documentation" (Sphinx) section to the end, adding a missing newline before a codeblock, and a link to the rendered docs
* change the nesting level of some entries 
* minor rewording and wrapping of long lines
Be able to close #100, as #274 introduced a rewrite and clearer instructions on the issue -> PR flow, with only minor tweaks missing.

Tweaks and fixes for CONTRIBUTING.rst

---

qiskit/tools/apps/optimization.py

fixed X <-> Z indexing in eval_hamiltonian with one shot and pauli list
representation for the operator

bug fix in pauli addressing

---

qiskit/qasm/_qasm.py
qiskit/qasm/_qasmlexer.py
qiskit/qasm/_qasmparser.py
test/python/test_qasm_parser.py

Setting `lex.input` data at `__mklexer__` instead of `push`.

Issue #264: `__mklexer__` was not setting data.

---

qiskit/qasm/_qasm.py

It seems we overlooked the opening of a file after the changes in #306, that resulted in a warning about unclosed files during tests and execution.

Fix unclosed file during QASM parsing

---

qiskit/tools/qi/pauli.py

add a method in Pauli class to generate sparse matrix and revise the to_matrix method.

to_matrix and to_spmatrix methods for Pauli class

---

README.md
examples/python/basic_optimize.py
examples/python/ghz.py
examples/python/hello_quantum.py
examples/python/initialize.py
examples/python/qft.py
examples/python/rippleadd-async.py
examples/python/rippleadd.py
examples/python/sympy_backends.py
examples/python/teleport.py

This is a cleanup of some of the examples and the README given the recent issues (#344, #354, Slack messages).
- The `hello_quantum` example in the README is now more concise, and uses the QISKit interfaces better (instead of using QuantumProgram for everything).
- Increased timeout to 300 for the `hello_quantum` example. 
- Removed the relative imports in all examples, and replaced with a note.
- General cleanup of README.

Clean up examples and README

---

.travis.yml
cmake/code-qa.cmake

* Fix the travis stage that performs the linting, making it fail if the
`make style` target fails instead of ignoring it silently.
* Fix the execution of the deploy stages for the jobs that are the
result of a PR against stable. Now the stages are only executed in the
job associated to the push.
* Revise the cmake QA-related targets, making them optional by default
and emitting warnings instead of errors if the dependencies are not
present.
Paving the way for better CI support for the upcoming release.

Travis and cmake improvements

---

qiskit/extensions/qiskit_simulator/noise.py

Fix typo in docstring of noise method.
Changed "locla_qiskit_simulator" to "local_qiskit_simulator".
To support grammar consistency.
Small change in docstring.

Fix typo in docstring of noise method

---

CONTRIBUTORS.md
README.md
doc/conf.py
doc/index.rst

Following up on the recent changes for the documentation and the `README.md` in particular and after a conversation with @jaygambetta, this PR reorganizes a bit the "Authors" section on the main `README.md` by moving the list of contributors to its own separate file. The goal is to make that list able to scale better, being able to both preserve attribution to the contributors and keep the mainlist readable.

Reorganize the contributors information

---

qiskit/extensions/standard/barrier.py
qiskit/extensions/standard/ccx.py
qiskit/extensions/standard/ch.py
qiskit/extensions/standard/crz.py
qiskit/extensions/standard/cswap.py
qiskit/extensions/standard/cu1.py
qiskit/extensions/standard/cu3.py
qiskit/extensions/standard/cx.py
qiskit/extensions/standard/cy.py
qiskit/extensions/standard/cz.py
qiskit/extensions/standard/h.py
qiskit/extensions/standard/iden.py
qiskit/extensions/standard/rx.py
qiskit/extensions/standard/ry.py
qiskit/extensions/standard/rz.py
qiskit/extensions/standard/s.py
qiskit/extensions/standard/swap.py
qiskit/extensions/standard/t.py
qiskit/extensions/standard/u0.py
qiskit/extensions/standard/u1.py
qiskit/extensions/standard/u2.py
qiskit/extensions/standard/u3.py
qiskit/extensions/standard/x.py
qiskit/extensions/standard/y.py
qiskit/extensions/standard/z.py
qiskit/tools/visualization.py
test/python/test_visualization.py

- Fixed drawing of cu1 & cu3. Together with PR #333, this means any circuit containing 
`id, u0, u1, u2, u3, x, y, z, h, s, sdg, t, tdg, rx, ry, rz, cx, cy, cz, ch, crz, cu1, cu3, swap, ccx, measure, c_if` can be plotted.
- Beamer overlay removed from plots (fixes #335)
- Fixed trimming issue with very small circuits (fixes #335)
- Improved error messages when plotting fails, suggesting possible fixes (fixes #334)
- Fixed subscript indexing of classical bits greater than 9
- Made classical register optional in the circuit
- Fixed font issue (contributed by @nelimeee)
- Unified gate signatures and a bug fix in rx, ry, rz (fixes #352)
- Fixed bug drawing more than 2 cswap and ccx gates
- Automatically discover the best image scaling, based on column widths, while not exceeding hard limits …

Improved circuit visualization

---

README.md
examples/python/hello_quantum.py
examples/python/using_qiskit_core_level_0.py
examples/python/using_qiskit_core_level_1.py

fixing up the backend in the example

---

qiskit/backends/_backendutils.py
test/python/test_backends.py
test/python/test_quantumprogram.py

the backend config dictionary and qiskit handling of it got out of sync.
Need to update pypi
resolves #416 
resolves #417

hotfix: basisGates

---

qiskit/dagcircuit/_dagcircuit.py
qiskit/extensions/standard/cswap.py
qiskit/extensions/standard/header.py
qiskit/qasm/libs/qelib1.inc
qiskit/tools/visualization.py
test/python/test_extensions_standard.py
test/python/test_qasm_parser.py
test/python/test_quantumprogram.py

Resolves #398.
Changes include:
1- fix row spacing for corner cases (circuits 1 & 2 below)
2- add cswap to the standard extensions (it wasn't already), and draw a Fredkin gate picture (circuit 3 below)
3- add ability to draw reset (circuit 4 below)
4- fixed conditional gates at the beginning of circuits, as well as conditionals for 2/3 qubit gates (circuits 4 below)
5- made cz, crz, cu1 drawing symmetric (the latter 2 add extra `e^ilambda` label) (circuit 5 below)
6- add initial state labels to both quantum and classical bits
cz
For cu1 and crz, the angle labels have to go in a new "column". Right now i do this:
but is it better to be this, at the risk of some overlap? 
For bigger cases it's better and more compact:
Also should it be e^ilambda, or just lambda? Considering for example for …

Circuit drawing improvement

---

requirements.txt
setup.py.in

Bump the dependency on `IBMQuantumExperience` to the latest version.

Bump IBMQuantumExperience dependency to 1.9

---

CMakeLists.txt
qiskit/__init__.py
qiskit/_openquantumcompiler.py
test/python/test_util.py

* Fixed a bug with legacy code affecting Developer Challenge
* Disabled util_tests temporarily

pip release: 0.4.15

---

qiskit/_openquantumcompiler.py

Resolves #444 
We brought the `_openquantumcompiler.py` file back temporarily to preserve backwards compatibility, especially for the "developer challenge" contest. It is only there temporarily, and will be removed soon. This is just to fix a bug in that file in the meantime.

Fix issue #444: feed list instead of str to JsonBackend()

---

test/python/test_simulator_interfaces.py

Comparing counts from two simulators rather than one simulator vs. ground truth is naturally more error prone, hence higher tolerance needed.

increase tolerance of cross simulation tests

---

qiskit/mapper/_compiling.py

Fixes Issue #445.
The function `np.linalg.det` returns a `np.float64` dtype, that cannot be negative when doing negative fractional powers as a result of strict typecasting rules.  This Pull replaces the `np.linalg` calls with those of `scipy.linalg` that return a simple `float` and can be up casted to `complex`.
Fixes #445.

BUG: Fix Issue 445

---

examples/python/hello_quantum.py
examples/python/using_qiskit_core_level_0.py
examples/python/using_qiskit_core_level_1.py
qiskit/__init__.py

fixing the examples
running the examples

Fixing the examples in python

---

README.md
doc/_templates/better-apidoc/package.rst
doc/example_real_backend.rst
doc/index.rst
doc/install.rst
doc/ja/example_real_backend.rst
doc/quickstart.rst
doc/releases.rst
qiskit/_quantumprogram.py
qiskit/backends/local/statevector_simulator_sympy.py
qiskit/backends/local/unitary_simulator_sympy.py
requirements.txt

Small tweaks in preparation for the release:
This PR should be merged once the rest of the 0.5 PRs are completed - I'll be rechecking the warnings and rebasing accordingly.

Documentation tweaks and release notes for 0.5

---

qiskit/_compiler.py
test/python/test_compiler.py

Picks a better initial layout for register to physical qubits if none is given.
This is a stopgap fix, as the values should be cached as they need only be computed once.
Multiple issues with swap mapper, as reported in #469.
Seems to solve all mapper issues.

Fix Issue #469, Mapper error

---

test/python/test_compiler.py

Fixing test_mapping_correction parameters

---

test/python/test_localjob.py

Make the `TestLocalJob:test_run_async()` wait for the jobs to be
completed, marking it as a slow_test as a result, as otherwise it might
have affect subsequent tests due to filling up the executor queue with
the jobs running in the background even after the test was finished.
Hopefully it will take care of the latest round of issues on the CIs, as in:
https://travis-ci.org/QISKit/qiskit-sdk-py/jobs/380776638

Fix potentially blocking local job test

---

qiskit/backends/ibmq/ibmqjob.py
test/python/test_ibmqjob.py

This change verifies that job cancellation works with hubs. In addition the test suite has been updated to work with hubs.
add test for job cancellation

job cancellation improvements for hubs

---

qiskit/_compiler.py

The compiler random number seed was hard-coded to 13.
The seed should not be fixed.
- [X ] My code follows the code style of this project.
- [X ] All new and existing tests passed.

Fix compiler seed hardcoded to 13

---

CONTRIBUTORS.md

fix link to .github/CONTRIBUTING.rst

---

qiskit/_compiler.py
qiskit/_gate.py
test/python/test_compiler.py

PR #527 tried to make the compiler not change a circuit that already maps correctly to the backend topology, but part of the code was wrong (specifically, in the way Gate._qubit_coupling was defined).This PR fixes that, and adds a test for the original intent of #527.

Fix: Gate._qubit_coupling

---

CHANGELOG.rst
requirements.txt
setup.py.in

Bump IBMQuantumExperience dependency to 1.9.6

---

test/python/_mockutils.py
test/python/test_wrapper.py

Fix a failing test, as mentioned by Ali at https://github.com/QISKit/qiskit-terra/pull/602#issuecomment-401256826, by playing a bit with the `DummyProvider`.

Fix test_register_backend_name_conflicts

---

.travis.yml
requirements.txt

Fix #615 
Checking Python3.7 compatibility

Python3.7 compatibility

---

CHANGELOG.rst

Update the changelog after the 0.5.6 release.

Post 0.5.6 changelog

---

README.md

The Links to Sections previously had a failing link. Added the License section with a link to the license and the link to the contribution guidelines.
that is all.

Update Readme to add back the License section

---

test/python/test_registration.py

Fix the mocking functions in test_registration.py, as they were not
performing mocking over multiple files nor the default environment
variables.

Fix mocks in test_registration.py

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/BUG_REPORT.md

Update `(Python SDK)` to `Terra` in GitHub templates
Now it's more consistent with the new naming and with the Qiskit Aqua repository.

Update (Python SDK) to Terra in GitHub templates

---

qiskit/schemas/result_schema.json

Fix #814 
Quick fix for a problem @ewinston found.

Removed example from result field from schema because it was out of date (fixes #814)

---

qiskit/tools/apps/optimization.py
qiskit/transpiler/_transpilererror.py
test/python/test_load_qasm.py

Fix #827.
Found 2 other files that needed fixing in addition to the above.

fix license in 3 files

---

test/python/_test_options.py
test/python/common.py

- type in docstring fixed
- logging instead of printing
- unset var does no create an empty option
Fixes #840

No printing to stdout during testing

---

qiskit/schemas/examples/qobj_openpulse_example.json
qiskit/schemas/qobj_schema.json

To address https://github.com/Qiskit/qiskit-terra/issues/841. Had to add three gates to the qobj schema (`u0`,`rzz`,`cswap`)

Updated qobj schema with qelib1

---

appveyor.yml
requirements-dev.txt
requirements.txt
setup.py.in

Small adjustments to the dependencies after #528 (include `jsonschema` as a general dependency, not dev-specific dependency), and other tweaks.

Fix dependencies: add jsonschema, remove vcrpy

---

test/cassettes/test_double_submit_fails
test/cassettes/test_execute_one_circuit_simulator_online
test/cassettes/test_execute_several_circuits_simulator_online
test/cassettes/test_get_backend_name
test/cassettes/test_get_jobs_filter_counts
test/cassettes/test_get_jobs_filter_date
test/cassettes/test_get_jobs_filter_job_status
test/cassettes/test_get_jobs_from_backend
test/cassettes/test_job_id
test/cassettes/test_online_qasm_simulator_two_registers
test/cassettes/test_qasm
test/cassettes/test_remote_backend_calibration
test/cassettes/test_remote_backend_parameters
test/cassettes/test_retrieve_job
test/cassettes/test_retrieve_job_error
test/cassettes/test_run_simulator

Two are failing because of non-deterministic tests.

Updating casettes

---

qiskit/tools/visualization/__init__.py

import plot_bloch_vector at init

---

qiskit/tools/visualization/bloch.py

Fix the labelling issue on the Bloch sphere.
A bug in the labels of the Bloch sphere.

Fix bloch labels

---

qiskit/backends/ibmq/ibmqbackend.py
qiskit/backends/ibmq/ibmqjob.py
qiskit/qobj/_qobj.py
qiskit/result/_result.py
requirements.txt
setup.py.in
test/python/test_ibmqjob.py
test/python/test_ibmqjob_states.py

Fix #754
Fix #829 
This PR submits qobj formatted data to ibmq backends instead of qasm if the backend identifies that it excepts this format.

submit qobj 1.0.0 to ibmq backends. 

---

qiskit/tools/visualization/_counts_visualization.py

Fix #896
This commit adds support for the 3 missing option fields: height,
width, and sort from iplot_histogram (using online js) to
plot_histogram (using matplotlib).
This difference between the 2 histogram plot options was pointed out in review for #866.

Add missing support for missing option fields to plot_histogram

---

qiskit/tools/visualization/_state_visualization.py
qiskit/tools/visualization/interactive/_iplot_state.py

Fixes #907 by automatically converting a statevector to a density matrix when calling `plot_state`.
This PR also adds basic error handling to check that the input (after conversion to a density matrix) is a square matrix, and is an n-qubit state.

Add statevector support and basic error checking to plot_state

---

qiskit/tools/visualization/_counts_visualization.py

Passing `options={'number_to_keep': int}` was failing because the value was not actually being used anywhere.  This fixes it.

Fix number to keep in plot_histogram

---

requirements.txt
setup.py.in
test/python/test_qcvv_fitters.py
test/python/test_visualization.py
test/python/test_visualization_output.py

This removes the restriction on Matplotlib 3.0.
Fixes #922

Remove mpl-3 restriction

---

.github/ISSUE_TEMPLATE.md

Spelling in the issue template. Issue  #932

fixing issue template

---

test/python/test_wrapper.py

Fix master tests, as they are failing due to the tests not being updated after #979.

Fix master failing due to registration test

---

qiskit/tools/visualization/_circuit_visualization.py

Fix #931 
set
```compress=True```
in qx_color_scheme()

matplotlib drawer - modify default styles heet

---

test/python/ibmq/test_ibmq_qasm_simulator.py
test/python/ibmq/test_ibmq_qobj.py
test/python/test_remote_simulator.py

Update remote simulator tests so that they are both running and passing.

Remote Simulator Tests Update

---

qiskit/wrapper/_wrapper.py
test/python/aer/test_extensions_simulator.py
test/python/test_circuit.py
test/python/test_compiler.py

clean up warnings from tests

---

CHANGELOG.rst
doc/example_real_backend.rst
doc/quickstart.rst
doc/releases.rst
qiskit/_schema_validation.py
qiskit/transpiler/_parallel.py
qiskit/wrapper/_wrapper.py

Fixes #966 .
WIP, as this is likely to be the "wrapping up" PR for the 0.6 release - will be updated as the others are merged, and conflicts to be solved in this PR.

Finalize 0.6

---

README.md
doc/install.rst

small mistakes to readme

---

doc/conf.py
doc/dev_introduction.rst
doc/example_real_backend.rst
doc/index.rst
doc/install.rst
doc/qiskit.rst
doc/quickstart.rst
doc/releases.rst
doc/theme/theme.conf

Minor corrections to the docs.  Mostly fixed out-of-date information, and made clear how to use `enable_account` with `Qconfig`.  Also made color scheme align with qiskit.org.

Updates to the 0.6 documentation

---

test/python/test_dagcircuit.py

Fix #382 
Fixes the source of confusion in the test (refer to https://github.com/Qiskit/qiskit-terra/issues/382#issuecomment-427258909)

Clarify dagcircuit test

---

qiskit/backends/ibmq/ibmqprovider.py

Modifies docstrings (`enable_account` and `save_account`)for accuracy in `IBMQProvider`.
Fixes (#1050)

Updated ibmq provider documentation (fixes #1050)

---

qiskit/dagcircuit/_dagcircuit.py
qiskit/tools/visualization/__init__.py
qiskit/tools/visualization/_dag_visualization.py
requirements.txt
test/python/test_dagcircuit.py

Adding a DAG visualizer for easing debugging transpilation process.

Adding DAG visualizer

---

tox.ini

This commit adds support for using tox by adding a tox.ini. This makes
it very simple for users and contributors to run tests and style checks
locally by just using the `tox` command. This is also a common tool for
python projects, as many (if not most) other python project uses it.
Fixes #1012

Add tox.ini to start using tox

---

CHANGELOG.rst
qiskit/tools/visualization/_state_visualization.py

This commit adds a new filename kwarg to the plot_bloch_vector function.
When set this will save the bloch sphere visualization to the specified
file instead of calling show() on it. This enables people to generate
bloch sphere visualizations with non-GUI matplotlib backends.
Fixes #1095

Add filename kwarg to plot_bloch_vector()

---

CHANGELOG.rst
qiskit/backends/ibmq/credentials/credentials.py

Update the comparison for premium credentials, allowing case-insensitive URLs.

Use case insensitive URLs when matching premium

---

qiskit/tools/qi/pauli.py

improve the sgn_prod in pauli

---

CHANGELOG.rst
qiskit/__init__.py
qiskit/wrapper/__init__.py
qiskit/wrapper/_wrapper.py
test/python/aer/test_simulator_interfaces.py
test/python/aer/test_statevector_simulator.py
test/python/test_file_io.py
test/python/test_initializer.py
test/python/test_mapper.py
test/python/test_qobj.py
test/python/test_result.py
test/python/test_skip_transpiler.py
test/python/test_tomography.py
test/python/test_transpiler.py
test/python/test_wrapper.py

This is the fist step in doing #1083. 
Issues i still have is cleaning up the test_results and test_wrapper
Next is the splitting up the transpile.compile and then making dagtocircuits. Then doing parallel.

Removing old wrapper commands

---

src/qasm-simulator-cpp/README.md

Updates the C++ simulator readme for how to compute coherent error matrices for X90 and CX gates, and to use the new backend providers for 0.6.
This is related to recent comment by @gxchan3 in closed issue #623

update simulator readme for coherent errors

---

qiskit/backends/aer/_simulatortools.py
qiskit/backends/aer/qasm_simulator_py.py
qiskit/mapper/_mapping.py
qiskit/qasm/_qasmparser.py
qiskit/tools/visualization/_circuit_visualization.py
qiskit/tools/visualization/_error.py
qiskit/tools/visualization/_latex.py
qiskit/tools/visualization/_matplotlib.py
qiskit/tools/visualization/_state_visualization.py
qiskit/tools/visualization/_text.py
qiskit/tools/visualization/interactive/_iplot_qsphere.py
qiskit/unrollers/_jsonbackend.py

Aims to replace all assert statements (excluding in tests) with conditional statement/exceptions as per [#225](https://github.com/Qiskit/qiskit-terra/issues/225)
I've initially replaced the asserts in the mapper module. Created a WIP PR to make sure I'm on right lines, with the assert replacements as well as with PR procedure.

Remove asserts from codebase

---

test/python/circuit/test_circuit_load_from_qasm.py
test/python/circuit/test_circuit_operations.py
test/python/circuit/test_circuit_qasm.py
test/python/circuit/test_circuit_registers.py

As discussed with @ajavadia. I divided the circuit test up into three and put them in the circuits folder.

Dividing up circuits test

---

qiskit/tools/qi/pauli.py

My bad, I forget to remove a print statement for debug in PR #1166

remove debug print statement

---

qiskit/tools/visualization/_state_visualization.py
qiskit/tools/visualization/interactive/_iplot_blochsphere.py

Fixing pauli singles

---

requirements.txt

Update networkx requirement to latest stable minor, `>= 2.2`.

Update networkx to most recent stable minor version (#1264).

---

.github/CODE_OF_CONDUCT.rst
README.md

simplifying the readme 
making the code of conduct rst and will add to documentation

Simplifying the readme

---

CHANGELOG.rst

This commit adds several missing items to the changelog that are
important to note in the release notes for 0.7.

Update the changelog

---

examples/python/load_qasm.py

load qasm exampe

---

CHANGELOG.rst
qiskit/_quantumcircuit.py
qiskit/dagcircuit/_dagcircuit.py
qiskit/transpiler/_transpiler.py
test/python/test_dagcircuit.py

circuit.properties()

---

doc/ko/README.md

This is the updated version of the Korean translation of README.md for Terra.  I updated the content to be consistent with the recent update in English version and  re-wrote the text to sound more colloquial.

Korean translation for Terra README.md 

---

qiskit/tools/visualization/__init__.py

This commit fixes a small issue in the visualization module when we do
the connectivity check to see if we can reach the hosted JS library for
the interactive plots. We called the _has_connection() function which
opens a socket and checks if we can establish a connection. However, we
were calling this function incorrectly and passing in the protocol
"https://" when the function just wants the hostname and port. This
commit fixes the call to pass the expect arguments.
Fixes #1335

Fix _has_connection() call in visualization module

---

examples/python/teleport.py
qiskit/result/result.py
test/python/aer/test_qasm_simulator_py.py

Follow on from #1360 and part of #830 
Renamed get_data and provided more information in the documentation

Renaming get_data to data

---

qiskit/dagcircuit/_dagcircuit.py
test/python/test_dagcircuit.py

For better testing, we need to do equivalence checks in DAGs.
Fixes #1364

__eq__ in DAG

---

test/python/test_dagcircuit.py

PR #1366 was merged before CI finished running and it had a small
whitespace failure. This commit corrects the oversight to make
everything pass again.

Fix lint failure in test_dagcircuit.py

---

test/python/test_dagcircuit.py

A DAG equivalence test for testing two dags that are the same in topology.

More testing for DAG equivalence

---

doc/_templates/drawer.html
doc/_templates/globaltoc.html
doc/conf.py
doc/theme/static/theme.css
doc/theme/static/themeExt.js

Update documentacion TOC

---

qiskit/tools/_compiler.py

For the upcoming aer release we need the ability to have a configurable backend

Adding kwargs for backend

---

CHANGELOG.rst
qiskit/_quantumcircuit.py
qiskit/dagcircuit/_dagcircuit.py
qiskit/mapper/_mapping.py
qiskit/tools/_compiler.py
qiskit/transpiler/_transpiler.py
qiskit/unrollers/_dagbackend.py
qiskit/unrollers/_dagunroller.py
qiskit/unrollers/_jsonbackend.py
test/python/test_transpiler.py
test/python/tools/test_compiler.py

Dags2circuit

---

qiskit/qobj/_qobj.py

Fixes #1424 
The serialization function for QobjItems was not recursively serializing numpy arrays.

Recursively serialize numpy array in as_dict

---

qiskit/tools/qcvv/tomography.py

Allows specifying different preparation qubits to measurement qubits in process tomography.
Closes #1432 
changes `tomography_set` and `process_tomography_set` to have optional `prep_qubits` kwarg for preparation qubits. If it is left as default (`None`), it will use `prep_qubits=meas_qubits`.
Maintain backwards compatibility with old version and defaults to preparation qubits being the same as measurement qubits.

Allow different prep and meas qubits in process tomography

---

CHANGELOG.rst
qiskit/mapper/_coupling.py
qiskit/mapper/_layout.py
qiskit/transpiler/_transpiler.py
qiskit/transpiler/passes/__init__.py
qiskit/transpiler/passes/mapping/lookahead_mapper.py
test/python/test_layout.py
test/python/test_mapper_coupling.py
test/python/test_transpiler.py

Closes #1140. Adds tree-search swap mapper as a transpiler pass.

Add lookahead swap mapper as pass to the transpiler.

---

qiskit/backends/ibmq/ibmqjob.py

#1483 made a small mistake in parsing the header of jobs. It should parse the new field first, then fall back on the old.

small bug in header check

---

qiskit/transpiler/_transpiler.py

The user should be able to use the transpiler by just supplying a circuit and a pass_manager. The `backend` arg is just meant to be a shorthand for things like `coupling_map` and `basis_gates` (for now).

make backend arg optional in transpile

---

qiskit/backends/builtinsimulators/simulatorsprovider.py

Fixing warning

---

README.md
doc/install.rst

This mentions VC++ runtime as a dependency for Windows in the readme and installation instruction.
Fixes #1183

mention vc++ runtime as dependency

---

qiskit/transpiler/passes/optimize_1q_gates.py

issue raised by @maikatakita.
some tiny euler angles should be chopped to 0 during compilation.

chop small values in optimize_1q_gates

---

CHANGELOG.rst
doc/release_history.rst

This change starts the process of preparing the documentation for the
0.7 release. It adds detailed release notes and updates and cleans up
somethings in the changelog.
Fixes #1370

Update the changelog and add release notes for 0.7

---

qiskit/tools/monitor/job_monitor.py

The `job_monitor` now uses the text checker, rather than a ipywidget, when running in blocking mode in a notebook.

job_monitor uses text in notebook

---

README.md

Now that the meta-package is called `qiskit`, and this package is called `qiskit-terra`, the pypi shield in the README needs to be updated to point to the correct package.

update pypi shield address

---

README.md

Making the readme format similar between Qiskit, Qiskit terra and Qiskit aer

---

qiskit/circuit/quantumcircuit.py

A minor fix in a comment

---

.github/CONTRIBUTING.rst

Merge `stable` into `master`, aiming to avoid extra changes. The only file actually changed is `CONTRIBUTING.rst`.

Resync documentation changes into master

---

.github/CONTRIBUTING.rst
README.md

Fixed typos and made consistent with the other elements

---

CHANGELOG.rst
qiskit/circuit/quantumcircuit.py

Removed circuit.add

---

qiskit/tools/visualization/_counts_visualization.py

This fixes a bunch of zeros popping up when the `number_to_keep` arg is used in `plot_histogram`:

Fix plot_histogram with number_to_keep

---

qiskit/extensions/standard/h.py

remove typo in hadamard gate

---

qiskit/tools/visualization/_matplotlib.py

This commit updates some internal variable names and removes out of date
comments. When we refactored the visualizers to use the dag/circuit
directly instad of unrolling into json these were leftover. While the
code worked it didn't reflect how things were actually working anymore.
To minimize code churn before the release these cleanups were left until
after the 0.7 release.
Fixes #1452

Update _matplolib code to be more consistent

---

requirements.txt

`marshmallow.warnings` used in qiskit/_util.py was introduced after 2.16.3.

bump marshmallow version requirement to 2.17.0

---

qiskit/providers/models/backendconfiguration.py

Closes #1719. Remove validation of `open_pulse` backend configuration flag.

Removed validation of open_pulse backend configuration parameters.

---

requirements-dev.txt

Small follow-up to https://github.com/Qiskit/qiskit-terra/pull/1672

Remove unused Sphinx dependency from requirements-dev

---

qiskit/circuit/quantumcircuit.py
test/python/circuit/test_circuit_operations.py

Fixes #1688 
Added in a method to QuantumCircuit that copies the circuit, and a test for it.

Added in a copy method to QuantumCircuit

---

qiskit/providers/models/__init__.py
qiskit/providers/models/pulsedefaults.py
qiskit/schemas/default_pulse_configuration_schema.json
qiskit/schemas/examples/default_pulse_configuration_example.json
test/python/test_schemas.py

Add the schema and models for `PulseDefaults` , in preparation for the new endpoint. Please note:
* the model is not in use yet - the only place where it is invoked is during `test_schema`, for checking against the example.
* the spec has been modified (`default_pulse_configuration_schema.json` modified, along with the sample file), fixing the type of `params` after conversation with @taalexander.

Add model for pulse "defaults"

---

README.md

The example script creating a bell state under the Creating your First
Quantum Program in Qiskit Terra section has an example of the output
after outlining the script. However, the output in that section was out
of date and doesn't actually reflect what the output dictionary from
get_counts() looks like. This just fixes that line so the output matches
the current output.

Make a small tweak to readme

---

qiskit/dagcircuit/_dagcircuit.py
qiskit/mapper/_mapping.py
qiskit/transpiler/passes/decompose.py
qiskit/transpiler/passes/mapping/barrier_before_final_measurements.py
qiskit/transpiler/passes/mapping/basic_swap.py
qiskit/transpiler/passes/mapping/check_map.py
qiskit/transpiler/passes/mapping/cx_direction.py
qiskit/transpiler/passes/mapping/lookahead_swap.py
qiskit/transpiler/passes/mapping/stochastic_swap.py
qiskit/transpiler/passes/mapping/unroller.py
qiskit/transpiler/passes/unroll_3q_or_more.py
test/python/test_dagcircuit.py
test/python/test_mapper.py
test/python/transpiler/test_decompose.py
test/python/transpiler/test_stochastic_swap.py
test/python/transpiler/test_unroll_3q_or_more.py
test/python/transpiler/test_unroller.py

Removing the calls to deprecated methods after #1773 .
Sorry for the noise in CI.

 remove deprecation warnings after PR#1773

---

Make.bat
Makefile

Follow-up to #1752 (which fixes #1676).
Removes the `make doc` target, revising the `make clean` target in the process.

Remove "make doc" target

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
README.md

Update the README travis badge for checking against `travis-ci.com`.

Update the badge for travis-ci.com

---

README.md

wrong stack exchange link

---

tools/report_ci_failure.py

Fix the name of the repository and fix the report URL for Travis.

Fixing reporting URL for Travis

---

qiskit/dagcircuit/_dagcircuit.py
test/python/test_mapper.py

@atilag noticed that #1806 is breaking one of Aer tests. One of them, Grover algorithm. Indeed, that PR needs to be reverted (and a test is added).

Revert #1806

---

qiskit/transpiler/passes/unroller.py

doc changes in unroll pass

---

CHANGELOG.rst
qiskit/quantum_info/states/_states.py
qiskit/tools/qi/qi.py
requirements.txt
test/python/quantum_info/test_states.py

Fixes #829 
Also made random_state work for any dimension not just 2**num
Follow on PR needs to move this to quantum_info #1143

Adding random unitary

---

qiskit/extensions/standard/u1.py
qiskit/extensions/standard/u2.py

update decomposition rules for u1 and u2

u1,u2 in terms of u3

---

qiskit/dagcircuit/_dagcircuit.py
test/python/transpiler/test_optimize_1q_gates.py

It seems that there is an off-by-one error en `collect_runs`.

off-by-one in dag.collect_runs

---

appveyor.yml

Installing PyGithub in the Appveyor environment

---

CHANGELOG.rst
qiskit/tools/qcvv/__init__.py

deprecate qcvv package

---

CHANGELOG.rst
qiskit/circuit/instruction.py

Reverts Qiskit/qiskit-terra#1900

Revert "Fix instruction inheritance issues"

---

README.md

Just a few spelling and grammar fixes in the README.
N/A

Spelling & grammar fixes in README

---

CHANGELOG.rst
qiskit/extensions/standard/rzz.py

fix rzz definition bug

---

qiskit/converters/dag_to_circuit.py

The current method relies on monkey-patched gate methods which are not extensible to custom (user-defined) gates. I fix that here.

generalize dag_to_circuit for custom instructions

---

README.md

Closes #1891 
Updated Aer references to BasicAer in file README.md

Updated Aer references to BasicAer in README.md

---

qiskit/qobj/models/__init__.py

Add init to qiskit.qobj.models

---

qiskit/qobj/models/__init__.py
qiskit/qobj/models/pulse.py
qiskit/qobj/models/qasm.py

Optimize import order of Qobj models

---

CHANGELOG.rst
qiskit/mapper/layout.py
qiskit/tools/compiler.py
qiskit/transpiler/transpiler.py
test/python/compiler/test_compiler.py
test/python/test_layout.py

Allow for list of ints as layout

---

qiskit/extensions/standard/s.py

fix sdg definition

---

CHANGELOG.rst
qiskit/result/models.py
qiskit/schemas/result_schema.json

Added `meas_level` as a possible option in the result schema.
Closes #1925.

Add meas_level to result schema

---

qiskit/quantum_info/__init__.py

import unitary like other stuff are imported in quantum_info

import unitary in quantum_info package

---

qiskit/extensions/quantum_initializer/initializer.py
test/python/circuit/test_initializer.py

fix initializer internal names to always produce equivalent definition

---

qiskit/transpiler/passes/__init__.py
qiskit/transpiler/passes/remove_reset_in_zero_state.py
test/python/transpiler/test_remove_reset_in_zero_state.py

RemoveResetInZeroState pass

---

qiskit/circuit/quantumcircuit.py
test/python/circuit/test_circuit_properties.py

Fix quantumcircuit.size for (instr,qargs,cargs) format of self.data.

---

examples/python/commutation_relation.py
examples/python/ghz.py
examples/python/hello_quantum.py
examples/python/initialize.py
examples/python/qft.py
examples/python/teleport.py

Should fix #2189, I got a slightly different but related error when I ran the sample code which is now fixed. 
Updated the examples so that they all now run successfully and tidied up some of the print statements and code to improve clarity.

Tidy up examples

---

CHANGELOG.rst

This commit updates the changelog to include updates for recent
changes/improvements made to the disassembler/qobj_to_circuits. The
changelog wasn't updated during the PRs that made these change, this
just corrects that oversight.

Update changelog for recent disassembler changes

---

qiskit/visualization/matplotlib.py

Fixes #2227 
The params of the instruction were changing type as the original list was being modified. Fixed by creating a new list and modifying that instead.

Fixed issue with params changing type with mpl drawer

---

qiskit/visualization/text.py
test/python/visualization/test_circuit_text_drawer.py

Fixes #2234 
Unitary gate should not print the parameters when text-drawed.

text drawing unitary gates

---

CHANGELOG.rst
qiskit/circuit/quantumcircuit.py
qiskit/extensions/unitary.py
qiskit/quantum_info/random/utils.py
test/python/quantum_info/test_synthesis.py

This adds the ability to decompose a 2x2 unitary into a U3 with standard Euler angles.

1q unitary decomposition

---

qiskit/visualization/matplotlib.py

Fixed the heights of the boxes, so instead of appearing as they do in #2233 they now look like

Updated logic to fix mpl box sizes

---

examples/python/commutation_relation.py
examples/python/initialize.py
examples/python/using_qiskit_terra_level_1.py
examples/python/using_qiskit_terra_level_2.py

This is @jaygambetta 's PR from before with minor tweaks. No idea why that one closed.

Examples update

---

CHANGELOG.rst
qiskit/providers/models/backendconfiguration.py
qiskit/schemas/backend_configuration_schema.json

The schema validation for backend config was set too tightly and it was
rejecting valid responses from the backend API. This potentially causes
issues when running against the api. This commit addresses this by
changing the schema validation to ensure that we properly validate the
response received by the backends and no longer reject valid responses
moving forward.

Relax schema validation on backendconfiguration

---

qiskit/assembler/assemble_schedules.py

This is a bug where the schedule_los were making their way into the qobj config, which are then not serializable.

assemble lo bug fix

---

CHANGELOG.rst

This commit updates the changelog on master to include the intermediate
0.7.x stable releases and also marks the 0.8 release. This should be the
last commit on master prior to the the 0.8 release.

Update changelog to prepare for 0.8 release

---

qiskit/transpiler/transpile_circuit.py

fix 2339: run level 0 optimization level

---

qiskit/transpiler/transpile_circuit.py

Fixes #2339
(cherry picked from commit da8fe358597167d61618e34f6273f17089ceb78a)
Backported from #2370

[Stable] fix level 0 check 

---

qiskit/transpiler/preset_passmanagers/level2.py
qiskit/transpiler/preset_passmanagers/level3.py

This PR sets the swapper with the seed_transpiler, which was ignored
in level 2 and 3.
(cherry picked from commit 76e28ea821a90a8c6a6f654ff408282b8607af95)
Backported from: #2361

[Stable] Preset passmanager should honor seed_transpiler

---

qiskit/assembler/disassemble.py
qiskit/circuit/quantumcircuit.py
qiskit/pulse/schedule.py
qiskit/transpiler/__init__.py

As a small follow-up to #2365 (thanks Lev!), address some pylint ignores.

Address more pylint ignores

---

qiskit/assembler/assemble_schedules.py
qiskit/circuit/quantumcircuit.py
qiskit/compiler/assemble.py
qiskit/compiler/transpile.py
qiskit/dagcircuit/dagcircuit.py
qiskit/pulse/timeslots.py
qiskit/tools/events/progressbar.py
qiskit/transpiler/layout.py
qiskit/transpiler/passes/mapping/barrier_before_final_measurements.py
qiskit/transpiler/passes/mapping/enlarge_with_ancilla.py
qiskit/validation/fields/custom.py
qiskit/visualization/matplotlib.py

We don't support py2 so may as well simplify.

Remove python2-isms

---

test/python/pulse/__init__.py
test/python/pulse/test_channels.py
test/python/pulse/test_cmd_def.py
test/python/pulse/test_commands.py
test/python/pulse/test_continuous_pulses.py
test/python/pulse/test_discrete_pulses.py
test/python/pulse/test_experiment_configurations.py
test/python/pulse/test_samplers.py
test/python/pulse/test_schedule.py
test/python/pulse/test_timeslots.py
test/python/quantum_info/operators/channel/__init__.py
test/python/quantum_info/operators/channel/channel_test_case.py
test/python/quantum_info/operators/channel/test_adjoint.py
test/python/quantum_info/operators/channel/test_chi.py
test/python/quantum_info/operators/channel/test_choi.py
test/python/quantum_info/operators/channel/test_evolve.py
test/python/quantum_info/operators/channel/test_kraus.py
test/python/quantum_info/operators/channel/test_linearops.py
test/python/quantum_info/operators/channel/test_ptm.py
test/python/quantum_info/operators/channel/test_stinespring.py
test/python/quantum_info/operators/channel/test_superop.py
test/python/quantum_info/operators/channel/test_tensor_compose.py
test/python/quantum_info/operators/channel/test_transformations.py
test/python/quantum_info/operators/test_operator.py
test/python/quantum_info/test_synthesis.py

* test/python/pulse
* test/python/quantum_info
#2423 , #2232

Update license header in several modules, 4

---

qiskit/circuit/bit.py
qiskit/visualization/matplotlib.py

removing deprecated bit access in visualization/matplotlib.py

---

qiskit/assembler/assemble_schedules.py
test/python/compiler/test_assembler.py

Fixes #2404
Previously, if a user created a pulse schedule with two different pulses of the same name and assembled the schedule into a Qobj, the first pulse would be played for both instructions. Now, the name conflict is resolved.* The first pulse remains named pulse.name, and later pulses are named f"{pulse.name}-{hash(pulse.samples.tostring())}"
\* Except when >2 pulses share the same name, the pulses are long enough that their str repr is abbreviated, and the abbreviated samples (usually the first and last few) are the same. I'd love recommendations for fixing this! Do we have qubit and time info? Then we can be sure we wouldn't have more conflicts (can't play two pulses at the same time on the same channel)
Backport of #2431.

[Stable] Bug fix sample pulse name conflict in qobj assembly (#2431)

---

qiskit/transpiler/passes/mapping/stochastic_swap.py
test/python/transpiler/test_stochastic_swap.py

Fixes #1723 -- Stochastic swap was modifying the layout provided to it in certain circumstances, which led to unpredictable behavior.

remove layout modification from stochastic swap

---

qiskit/circuit/classicalregister.py
qiskit/circuit/quantumcircuit.py
qiskit/circuit/quantumregister.py
qiskit/transpiler/layout.py

This PR reverts #2474, fixing #2496 and it's an alternative to #2499

reverts PR #2474

---

qiskit/test/mock.py
test/python/transpiler/test_preset_passmanagers.py

* Fixes issue #2446 
* Tests added

Mocking of fake backends with several optimization levels

---

qiskit/transpiler/passes/mapping/stochastic_swap.py
test/python/transpiler/test_stochastic_swap.py

Fixes #1723
Stochastic swap was modifying the layout provided to it in certain circumstances, which led to unpredictable behavior. 
Backport of #2463 to stable

[Stable] remove layout modification from stochastic swap

---

constraints.txt
requirements-dev.txt

After the cleanups in #2465, #2374 and others, we can finally update to the 2.3 version of `pylint`.

Update pylint to 2.3

---

CHANGELOG.rst

This commit adds a changelog for all the fixes we've landed on the
stable branch so far for the pending 0.8.1 release.

[Stable] Add missing changelog items for fixes in 0.8.1

---

qiskit/pulse/cmd_def.py
test/python/pulse/test_cmd_def.py

Fix CmdDef unittest

---

qiskit/transpiler/preset_passmanagers/level0.py
test/python/transpiler/test_preset_passmanagers.py

[Stable] optimization_level=0 without coupling map

---

qiskit/providers/__init__.py
qiskit/providers/basebackend.py
qiskit/providers/basejob.py
qiskit/providers/baseprovider.py
qiskit/providers/exceptions.py
qiskit/providers/jobstatus.py
qiskit/providers/providerutils.py

Round of small updates to the docstrings and the exceptions of the `qiskit.providers` module, aiming for increasing a bit the readability on the generated docs without changing functionality.

Docstring and style tweaks for qiskit.providers

---

examples/python/circuit_draw.py
examples/python/commutation_relation.py
examples/python/ghz.py
examples/python/hello_quantum.py
examples/python/initialize.py
examples/python/load_qasm.py
examples/python/qft.py
examples/python/rippleadd.py
examples/python/using_qiskit_terra_level_0.py
examples/python/using_qiskit_terra_level_1.py
examples/python/using_qiskit_terra_level_2.py

removed registers, circuit.draw in prints etc

Examples updated to use simplified inputs

---

qiskit/circuit/quantumcircuit.py

removed the deprecated circuit._attach

Removed deprecated circuit._attach

---

README.md

fixing broken links

---

qiskit/tools/jupyter/backend_monitor.py

One more fix for backend monitor

---

qiskit/tools/jupyter/backend_monitor.py

Fixed:
- Issue with new single qubit ordering from backends.
- Correctly displays LaTeX Hamiltonian (if any).
- Adjusts size of coupling map bounding box to prevent clipping.

More backend monitor updates

---

qiskit/tools/jupyter/backend_overview.py

Adds avg cx and avg meas errors to the overview widget

Update backend overview

---

qiskit/tools/monitor/backend_overview.py

Fixes for updated backend properties.

Fix cmd line backend monitor

---

qiskit/tools/jupyter/backend_monitor.py
qiskit/tools/monitor/backend_overview.py

This PR contains a series of backports for 5 fixes in the backend
monitors to make them work with updates made to the IBMQ backends.
These are needed moving forward to have the backend monitors continue
working with the backends.
This is a backport of #2606, #2611, #2624, #2630, and #2632.

[Stable] Backport backend monitor fixes

---

CHANGELOG.md

Add 0.8.1 and 0.8.2 to CHANGELOG

---

CONTRIBUTING.md

Updates the CLA section and the testing option table from `CONTRIBUTING.md`, as they are displaying some formatting artifacts.

CONTRIBUTING.Md: update test table and CLA

---

qiskit/transpiler/passes/mapping/noise_adaptive_layout.py

fix log 0 error in noise adaptive layout

---

qiskit/transpiler/passes/mapping/noise_adaptive_layout.py

(cherry picked from commit 2151cb92497836577d9610d28d78dade1b566f24)
Backported from #2656

[Stable] Fix log 0 error in noise adaptive layout

---

.travis.yml
test/randomized/test_transpiler_equivalence.py

Test PR to look at the feasibility of running asv benchmarks for PR branches in travis. Looking to find out if the variability of other tenants on the host hardware of the travis VM will wash out any meaningful information in the benchmark comparison.

Run benchmarks in CI, resolve hypothesis errors

---

.github/CODEOWNERS

This adds @lcapelluto as a Github codeowner.

Add Lauren as codeowner

---

qiskit/quantum_info/synthesis/two_qubit_decompose.py

Fix NumPy dot array alignment in KAK

---

qiskit/visualization/pulse/matplotlib.py

Add specified channels to channel builder

---

qiskit/pulse/commands/command.py
qiskit/pulse/commands/pulse_decorators.py
test/python/pulse/test_commands.py

Allow for np.integer as pulse duration

---

qiskit/tools/qi/qi.py
test/python/test_qi.py

remove deprecated qi functions

remove deprecated qi functions

---

qiskit/providers/baseprovider.py
qiskit/providers/providerutils.py
qiskit/validation/fields/polymorphic.py
qiskit/validation/jsonschema/schema_validation.py

Small update to docstrings that contained `**kwargs` and `*args` in a not fully conformant google-style docstrings, which caused some minor annoyances in sphinx and ides.

Update kwargs and args docstring

---

CONTRIBUTING.md

Update some lines with `{.title-ref}` that were still remaining after the automatic conversion.

Update CONTRIBUTING.md minor glitches

---

qiskit/tools/monitor/backend_overview.py

Replace usage of IBMQ as a provider of backends in backend_overview.py. Without this change, backend_overview throws a deprecation warning.
Fixes #2827

update backend_overview.py with provider changes

---

examples/python/ibmq/ghz.py
examples/python/ibmq/hello_quantum.py
examples/python/ibmq/qft.py
examples/python/ibmq/using_qiskit_terra_level_0.py
examples/python/ibmq/using_qiskit_terra_level_1.py
examples/python/ibmq/using_qiskit_terra_level_2.py
test/python/test_examples.py

Update the examples and the test in order to use the API v2 and the new-style provider objects introduced in 0.3.

Update examples for IBMQProvider 0.3 and api v2

---

CHANGELOG.md
qiskit/providers/models/backendconfiguration.py
qiskit/test/mock.py

config coupling map required by marshmallow

---

docs/README.md

docs have moved out of Terra and to the meta package: https://github.com/Qiskit/qiskit

remove docs folder

---

qiskit/circuit/gate.py
qiskit/compiler/assemble.py
qiskit/compiler/transpile.py
qiskit/dagcircuit/dagnode.py
qiskit/qobj/converters/pulse_instruction.py
qiskit/transpiler/layout.py
qiskit/transpiler/passes/collect_2q_blocks.py

Tweaks to docstrings, trying to fix some lines that generated sphinx warnings and visual artifacts in the rendered `.html` pages when building the documentation.

Misc updates to docstrings for sphinx warnings

---

qiskit/compiler/assemble.py
qiskit/execute.py

Fix typo in comments.

---

test/randomized/test_transpiler_equivalence.py

Limit angles in randomize tests to +/- 10 pi.

---

azure-pipelines.yml

Add style and lint checks to azure so that we can unblock merging PRs.

Add style and lint check to azure pipelines.

---

CHANGELOG.md
qiskit/circuit/quantumcircuit.py
test/python/circuit/test_circuit_properties.py

Ordered count_ops

---

CHANGELOG.md
qiskit/transpiler/preset_passmanagers/level1.py
test/python/compiler/test_transpiler.py
test/python/transpiler/test_preset_passmanagers.py

Fixes #2845 
Alternative to PR #2852

Use DenseLayout in optimization level 1

---

qiskit/tools/jupyter/watcher_monitor.py

faster job status checking in job watcher

---

CHANGELOG.md
qiskit/pulse/schedule.py
qiskit/pulse/timeslots.py
qiskit/pulse/utils.py
test/python/pulse/test_schedule.py
test/python/pulse/test_timeslots.py

slight modification to https://github.com/Qiskit/qiskit-terra/pull/2870

Issue 2848 improve schedule performance

---

qiskit/pulse/channels/pulse_channel_spec.py
qiskit/pulse/channels/qubit.py
qiskit/pulse/channels/system_topology.py
qiskit/qobj/converters/lo_config.py

Was causing deprecation warning to always print!!!! 🚑 
Remove `pulse_channels` imports in other modules

FIXUP from 3094

---

qiskit/transpiler/transpile_circuit.py
test/python/compiler/test_transpiler.py

Do not unroll an Rx,Ry,Rxx circuit to U3,CX because of measure.

---

qiskit/transpiler/passes/mapping/noise_adaptive_layout.py

Partial fix for #3124 
Currently the algorithm crashes when no layout can be determined. This PR adds error messages that show which CNOT/qubit could not be placed. In addition, some field variable names were improved.

Added error messages to NoiseAdaptiveLayout and did some refactoring

---

qiskit/transpiler/passes/ms_basis_decomposer.py
releasenotes/notes/initial-ion-trap-support-33686980aa9ec3ae.yaml

Adds release notes for ion trap branch and addresses remaining code review comments from #3214 .

Add release notes for ion trap merge.

---

qiskit/visualization/latex.py

the latex drawer is currently emitting some deprecation warnings.

fix tuple->Bit deprecation warning in latex drawer

---

.github/auto-merge.yml

Reading the documentation for the auto-merge bot [1] it is necessary to
set the minimum number of approvals needed to trigger the bot into
action. In addition to this the setting for the number of requested
changes to block auto merging is set to any. So if a code owner blocks
leaves a changes requested review it will block auto merging.
[1] https://github.com/bobvanderlinden/probot-auto-merge/blob/master/README.md#configuration

Update config file for auto-merge bot

---

qiskit/visualization/gate_map.py

Fixes #2945 
It was assumed that the returned bits were in order when in fact they need not be.

Fix plot_circuit_layout (#2945)

---

releasenotes/notes/3281-parameterized-circuits-raise-exception-at-optimization_level-c6e25be56b1f5eb8.yaml

Add missing release notes for #3281.

---

azure-pipelines.yml

This commit fixes several issues that cropped up during the release jobs
for the 0.10.0 release. All the jobs failed at release time and did not
upload anything to pypi (if they even successfully ran). This commit
fixes all the issues identified so far during that process.
(cherry picked from commit e0e6da5b293807fa1a264e1b29b33fb6188d010e)
Backported from #3275

[Stable] Fix broken release wheel jobs

---

qiskit/transpiler/passes/collect_2q_blocks.py
qiskit/transpiler/passes/commutation_analysis.py
releasenotes/notes/3281-parameterized-circuits-raise-exception-at-optimization_level-c6e25be56b1f5eb8.yaml
test/python/circuit/test_parameters.py

Stable PR of #3288 (bugfix) and #3340 (release note) to resolve #3281 .

[Stable] Collect2qBlocks, CommutationAnalysis to ignore parameterized gates.

---

qiskit/transpiler/passes/mapping/enlarge_with_ancilla.py
qiskit/transpiler/passes/mapping/full_ancilla_allocation.py
test/python/transpiler/test_enlarge_with_ancilla_pass.py
test/python/visualization/references/pass_manager_standard.dot
test/python/visualization/references/pass_manager_style.dot
test/python/visualization/test_pass_manager_drawer.py

[This](https://github.com/Qiskit/qiskit-terra/pull/3321#discussion_r339325604) is a context for this PR.

FullAncillaAllocation and EnlargeWithAncilla do not allow initial_layout at construction time

---

test/python/visualization/test_visualization.py

I think this is the last issue to close #205!
The test is very shallow, which is a different issue: https://github.com/Qiskit/qiskit-terra/issues/3364.

no more random in test_visualization

---

qiskit/transpiler/passes/barrier_before_final_measurements.py
qiskit/transpiler/passes/collect_2q_blocks.py
qiskit/transpiler/passes/commutation_analysis.py
qiskit/transpiler/passes/commutative_cancellation.py
qiskit/transpiler/passes/consolidate_blocks.py
qiskit/transpiler/passes/count_ops.py
qiskit/transpiler/passes/count_ops_longest_path.py
qiskit/transpiler/passes/cx_cancellation.py
qiskit/transpiler/passes/dag_fixed_point.py
qiskit/transpiler/passes/dag_longest_path.py
qiskit/transpiler/passes/decompose.py
qiskit/transpiler/passes/depth.py
qiskit/transpiler/passes/fixed_point.py
qiskit/transpiler/passes/merge_adjacent_barriers.py
qiskit/transpiler/passes/ms_basis_decomposer.py

Update the docstrings of roughly half of the `qiskit.transpiler.passes`, following the rationale and convention from #3332.

Docstrings updates for qiskit.transpiler.passes.[a-m]

---

qiskit/test/mock/fake_johannesburg.py

Fake Johannesburg device (20 qubit)

---

qiskit/providers/models/backendconfiguration.py
test/python/providers/test_backendconfiguration.py

Fixes #3369 and #3444 
Remove dt warnings, which are annoying because they would be unavoidable (even in correct code). Allow dt to be set.

Remove warning about units of dt

---

qiskit/transpiler/passes/count_ops.py
qiskit/transpiler/passes/count_ops_longest_path.py
qiskit/transpiler/passes/num_qubits.py
qiskit/transpiler/passes/num_tensor_factors.py
qiskit/transpiler/passes/optimize_1q_gates.py
qiskit/transpiler/passes/optimize_swap_before_measure.py
qiskit/transpiler/passes/remove_diagonal_gates_before_measure.py
qiskit/transpiler/passes/remove_final_measurements.py
qiskit/transpiler/passes/remove_reset_in_zero_state.py
qiskit/transpiler/passes/resource_estimation.py
qiskit/transpiler/passes/size.py
qiskit/transpiler/passes/unroll_3q_or_more.py
qiskit/transpiler/passes/unroller.py
qiskit/transpiler/passes/width.py

Update the docstrings of the last half of the `qiskit.transpiler.passes`, following the rationale and convention from #3332 and completing #3382.

Docstrings updates for qiskit.transpiler.passes.[n-z]

---

qiskit/providers/models/backendconfiguration.py

Fix control qubit channel bug in pulse backend configuration

---

releasenotes/notes/fix-bug-in-align_acquires-b0736bf9d520967f.yaml

Add release notes for #3307.

---

qiskit/providers/models/backendconfiguration.py

Closes #3579. One time dt/dtm warning for the recent conversion of units to seconds from nanoseconds.

One time dt/dtm unit conversion warning

---

qiskit/execute.py

Reverts Qiskit/qiskit-terra#3622

Revert "Allow giving jobs names via execute for IBMQ devices"

---

.github/ISSUE_TEMPLATE/ENHANCEMENT_REQUEST.md
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md

In #3560 the issue templates were updated to include the tags. However
the tags for enhancement and feature request contain a ':' in them. This
confuses the yaml parser because ':' is a reserved character. To address
this issue, this commit adds quotes around the tags so the yaml parser
can process the issue templates and add them back to the list of
options.

Add missing quotes to issue templates

---

releasenotes/notes/0.11/3281-parameterized-circuits-raise-exception-at-optimization_level-c6e25be56b1f5eb8.yaml
releasenotes/notes/0.11/deprecation_0.9-0163a90875b53832.yaml
releasenotes/notes/0.11/job_queue_position_None-da3e6c2a203bc795.yaml
releasenotes/notes/0.11/remove_implicit_conversion_snapshot_label-f3082561ede0bed5.yaml
releasenotes/notes/0.9/changes-on-upgrade-6fcd573269a8ebc5.yaml
releasenotes/notes/0.9/new-features-0.9-159645f977a139f7.yaml

fix typo in release notes

---

qiskit/circuit/add_control.py
qiskit/circuit/controlledgate.py
qiskit/circuit/gate.py
qiskit/circuit/parameterexpression.py
qiskit/circuit/quantumcircuit.py
qiskit/qobj/models/pulse.py
qiskit/quantum_info/analysis/make_observable.py
qiskit/quantum_info/operators/base_operator.py
qiskit/quantum_info/operators/channel/superop.py
qiskit/quantum_info/states/quantum_state.py
qiskit/quantum_info/synthesis/local_invariance.py
qiskit/quantum_info/synthesis/one_qubit_decompose.py
qiskit/quantum_info/synthesis/weyl.py
qiskit/visualization/counts_visualization.py

Fix typos in python files under `qiskit/circuit, qobj, quantum_info, and visualization` directories

fix typo under qiskit/circuit, qobj, quantum_info, and visualization

---

qiskit/quantum_info/synthesis/two_qubit_decompose.py

Reverts Qiskit/qiskit-terra#3585
Recent PRs are failing due to this merge.

Revert "remove randomness from two_qubit_decompose"

---

test/python/circuit/test_instruction_repeat.py
test/python/compiler/test_disassembler.py
test/python/compiler/test_transpiler.py
test/python/notebooks/test_pbar_status.ipynb
test/python/providers/test_backendproperties.py
test/python/pulse/test_schedule.py
test/python/pulse/test_timeslots.py
test/python/quantum_info/test_analyzation.py
test/python/quantum_info/test_quaternions.py
test/python/quantum_info/test_synthesis.py
test/python/quantum_info/test_weyl.py
test/python/test_dagcircuit.py
test/python/transpiler/test_barrier_before_final_measurements.py
test/python/transpiler/test_consolidate_blocks.py
test/python/transpiler/test_cx_direction.py
test/python/transpiler/test_pass_scheduler.py
test/python/transpiler/test_passmanager.py
test/python/transpiler/test_preset_passmanagers.py

Fix typos in python files under `test` directory

fix typo under

---

qiskit/pulse/reschedule.py
test/python/scheduler/test_basic_scheduler.py

Thank you @nkanazawa1989 for catching this!

Update deprecated call to cmd_qubits in the rescheduler

---

CONTRIBUTING.md
Make.bat
qiskit/extensions/quantum_initializer/isometry.py
qiskit/extensions/quantum_initializer/ucg.py
qiskit/extensions/quantum_initializer/ucrot.py
qiskit/extensions/standard/multi_control_toffoli_gate.py
qiskit/providers/basicaer/basicaertools.py
qiskit/providers/models/backendproperties.py
qiskit/pulse/instruction_schedule_map.py
qiskit/pulse/reschedule.py
qiskit/pulse/schedule.py
qiskit/result/utils.py
qiskit/schemas/default_pulse_configuration_schema.json
qiskit/schemas/qobj_schema.json
qiskit/schemas/result_schema.json
qiskit/tools/jupyter/backend_monitor.py
qiskit/transpiler/passes/layout/dense_layout.py
qiskit/transpiler/passes/optimization/commutative_cancellation.py
qiskit/transpiler/passes/optimization/crosstalk_adaptive_schedule.py
qiskit/transpiler/passes/routing/cython/stochastic_swap/swap_trial.pyx
qiskit/transpiler/passes/routing/cython/stochastic_swap/utils.pyx
qiskit/transpiler/passes/routing/stochastic_swap.py
releasenotes/notes/0.9/new-features-0.9-159645f977a139f7.yaml
releasenotes/notes/crosstalk-adaptive-scheduling-2e08f213053c8f17.yaml
tools/subunit_to_junit.py

Fix typos in python files under `qiskit` and other directories

Fix typo under qiskit directory

---

qiskit/compiler/assemble.py

Seems like this can be removed, now.

Remove outdated code from when backend defaults wasn't done

---

qiskit/pulse/commands/parametric_pulses.py

Thank you @1ucian0 for pointing this out.

Swap pass for NotImplementedError in Parametric Pulses

---

.github/CODEOWNERS

Add Lauren Capelluto to the codeowners list for 'assembler/'

---

qiskit/validation/fields/custom.py

Adds the ability to deserialize from a dictionary containing actual complex numbers 
Closes #3746

Fixed deserialization logic in Complex number definition

---

qiskit/circuit/parametertable.py

add repr method for ParameterTable

---

MANIFEST.in

Add an entry to the `MANIFEST.in` so the `LICENSE.txt` file is included
in the .tar.gz source distribution.

Include license in sdist

---

.travis.yml

Our travis config file was using some deprecated syntax which is no
longer supported on travis. This commit goes through and cleans things
up to make sure the config is compliant with travis's syntax and enable
running jobs again.

Cleanup travis config file

---

docs/apidocs/qiskit.rst

This PR fixes the heading of the landing page of API docs. (might look a bit odd after https://github.com/Qiskit/qiskit/pull/551 is merged)

Update the heading of the landing API docs page

---

qiskit/pulse/__init__.py
qiskit/pulse/commands/__init__.py

Closes #3859 
Added a hidden autosummary which will generate the stub file. _([more info](https://github.com/Qiskit/qiskit-terra/issues/3859#issuecomment-588390866))_

Fix the broken hyperlink in Pulse API docs

---

.mergify.yml
.travis.yml
azure-pipelines.yml

According to the trigger docs for azure [1] not specifying a pr field in
the config should have an implicit pr trigger on all branches.
However, this default PR trigger has stopped working. This commit adds a
manual pr trigger field in an attempt to workaround this issue. It has
been reported that manually adding the PR trigger will resolve the
issue. [2]
[1] https://docs.microsoft.com/en-us/azure/devops/pipelines/build/triggers?view=azure-devops&tabs=yaml#pr-triggers
[2] https://developercommunity.visualstudio.com/comments/949243/view.html

Add explicit PR trigger to azure pipelines

---

test/python/quantum_info/test_states.py

This PR checks (and silences) the `DeprecationWarning`s in `test/python/quantum_info/test_states.py`

self.assertWarns(DeprecationWarning) in quantum_info/test_states.py

---

qiskit/transpiler/passes/routing/lookahead_swap.py
releasenotes/notes/lookahead-swap-choose-depth-width-c265b261cb82b76d.yaml
test/python/transpiler/test_lookahead_swap.py

making these two attributes settable rather than hardcoded

set depth/width for LookaheadSwap pass

---

azure-pipelines.yml

The new pip depsolver is coming this summer. [1] Until it's ready
this starts running pip check as part of our CI test jobs to make
sure we're not somehow installing conflicting package versions. We
shouldn't be, but if we are better to know and start
preparing/fixing it now.
[1] https://pyfound.blogspot.com/2020/03/new-pip-resolver-to-roll-out-this-year.html

Add pip check to CI jobs

---

qiskit/quantum_info/states/quantum_state.py
releasenotes/notes/state-sample-counts-9710a22dfcb01ed6.yaml
test/python/quantum_info/states/test_densitymatrix.py
test/python/quantum_info/states/test_statevector.py

* Remove sample_measure function
* Adds separate sample_counts, sample_measure functions
* changes order of args so shots is first an no longer a kwarg.

Rename sample_measure to sample_counts and sample_memory

---

qiskit/circuit/quantumcircuit.py
test/python/circuit/test_circuit_operations.py

fix measure all

---

qiskit/circuit/library/arithmetic/functional_pauli_rotations.py
qiskit/circuit/library/arithmetic/integer_comparator.py
qiskit/circuit/library/arithmetic/linear_pauli_rotations.py
qiskit/circuit/library/arithmetic/piecewise_linear_pauli_rotations.py
qiskit/circuit/library/arithmetic/polynomial_pauli_rotations.py
qiskit/circuit/library/arithmetic/weighted_adder.py
qiskit/circuit/library/fourier_checking.py
qiskit/circuit/library/quantum_volume.py

Add missing pyling ignore to circuit library.

---

qiskit/circuit/library/generalized_gates/diagonal.py

In #4186 which recently merged a lint failure was introduced. The PR was
merged before CI finished which would have caught this. This commit
corrects the oversight and unblocks development.

Fix lint failure in diagonal gate

---

qiskit/visualization/matplotlib.py

display labels in custom instructions in mpl drawer

---

qiskit/schemas/qobj_schema.json

Added Delay to the qobj schema to support "delay" instructions

Support delay in specification

---

qiskit/circuit/quantumcircuit.py

Reverting change in https://github.com/Qiskit/qiskit-terra/pull/4207 due to Aqua and Aer breakage.

Change `QuantumCircuit` append back to accept `to_instruction()`

---

qiskit/tools/jupyter/library.py

Update fields and work around limitations in Sphinx handling of ipywidgets output type.  Also add scrolling for overflow of qasm, as the code does not wrap in sphinx.

Updates to library widget

---

qiskit/circuit/library/quantum_volume.py

adding published reference to volume circuit

---

qiskit/tools/jupyter/library.py

changing name to openqasm and circuit properties

---

qiskit/circuit/quantumcircuit.py
releasenotes/notes/circuit-compose-c320c4057cd2bb8f.yaml
test/python/circuit/test_compose.py

it now allows composing instructions too

Circuit compose() is compatible with append()

---

azure-pipelines.yml

As a followup to #4342 the auto cancellation is still not working.
Searching for this issue yielded scipy/scipy#11295 and it's fix
scipy/scipy#11301. This commit duplicates that for the terra config in
the hopes of making auto cancellation work again.

Modify job conditions to enable auto cancellation

---

qiskit/extensions/quantum_initializer/isometry.py
qiskit/providers/models/backendconfiguration.py
requirements-dev.txt

New update in pycodestyle raises new pylint issues.

pycodestyle 2.6.0

---

qiskit/circuit/controlledgate.py
releasenotes/notes/4573-Open-ControlledGates-not-marked-equivalent-729bc971c897ede3.yaml
test/python/circuit/test_controlled_gate.py

Set register name for definition of ControlledGates with ctrl_state.

---

qiskit/quantum_info/synthesis/one_qubit_decompose.py

fix u3 decomposition doc

---

qiskit/circuit/library/generalized_gates/gms.py

Missed `quant-ph`. Also remove trailing `=`.

Fix broken link in GMS docs

---

qiskit/assembler/assemble_schedules.py
qiskit/pulse/library/sample_pulse.py

This PR makes `SamplePulse` inherit from `Waveform` as `Waveform` is the new name for this object.

Make SamplePulse inherit from Waveform

---

README.md

Added the valid Slack invite link.
The valid Slack link (https://qiskit.slack.com/join/shared_invite/zt-fybmq791-hYRopcSH6YetxycNPXgv~A#/) has been added in README.md.

Valid Slack community link

---

qiskit/pulse/instructions/instruction.py
qiskit/pulse/library/continuous.py
qiskit/pulse/library/discrete.py
qiskit/pulse/library/parametric_pulses.py
qiskit/pulse/library/pulse.py
qiskit/pulse/library/waveform.py
qiskit/pulse/schedule.py
qiskit/visualization/pulse/matplotlib.py
qiskit/visualization/pulse_visualization.py
releasenotes/notes/remove-deprecated-pulse-code-9ec2dba175058c5f.yaml
test/python/pulse/test_continuous_pulses.py
test/python/pulse/test_discrete_pulses.py
test/python/pulse/test_schedule.py
test/python/visualization/test_pulse_visualization_output.py

- `union` schedule method
- drawing `scaling` arg
- library `period` arg

Remove deprecated code from pulse

---

CONTRIBUTING.md
README.md

Two misspelled words were edited

minor_spelling_mistakes

---

qiskit/circuit/library/standard_gates/u2.py
qiskit/circuit/library/standard_gates/u3.py

Fixes #4749 with instructions following the `cmd_def` information for `ibmq_armonk`. Adds details.

Fixes 4749 with backend default instructions

---

qiskit/assembler/assemble_schedules.py
test/python/compiler/test_assembler.py

Closes #4523. Allows a single instruction to be assembled.

Allow a single instruction to be assembled

---

qiskit/schemas/backend_configuration_schema.json

Bump configuration schema

---

releasenotes/notes/0.15/0.15.0-release-c7d85921f85f0b4d.yaml
releasenotes/notes/0.15/level0_RemoveResetInZeroState-942c0fb19cb6c087.yaml

Spelling issues found in https://github.com/Qiskit/qiskit/pull/998/

Spelling in release note 0.15

---

README.md

Update example in README.md to use transpiler.

---

qiskit/circuit/quantumcircuit.py
test/python/circuit/test_circuit_properties.py

Fixing a bug from my previous Pulse gates: User API PR #4859 and adding tests for them

Fix bug from #4859: Pulse gates calibrations 

---

qiskit/pulse/transforms.py
releasenotes/notes/pulse-schedule-recursion-bugfix-1bf1b7d919cf1a0c.yaml

This fix, readds the bugfix #4789, that was lost due to a bad conflict resolution in #4755.

Fix pulse transforms recursion bug fix that was lost in merge conflict

---

qiskit/dagcircuit/dagcircuit.py
releasenotes/notes/dagcircuit-compose-fix-multiple-creg-7f3478401a874fbb.yaml
test/python/dagcircuit/test_compose.py

Fix DAGCircuit.compose condition map when handling multiple cregs.

---

setup.py

The email in `setup.py` (displayed in PyPI) doesn't actually exist. This PR updates it with the correct email.

Update email in setup

---

qiskit/compiler/assemble.py
test/python/compiler/test_assembler.py

Enable zero rep delay

---

qiskit/test/mock/fake_backend.py

Fixes #4635 
* Used warnings flag of NoiseModel in qiskit aer.

setting warnings=False for NoiseModel of FakeBackend

---

qiskit/result/result.py
releasenotes/notes/3207-Results-object-should-inform-user-if-multiple-results-of-same-name-5757be483b0979c3.yaml
test/python/result/test_result.py

Result object to warn when fetching by name is ambiguous.

---

qiskit/visualization/pulse/matplotlib.py

Fixes a bug with the visualization of a frequency change.

Fix issue with frequency change visualization.

---

qiskit/pulse/channels.py

add `np.integer` for channel operand type check.
this is a patch for #5250

small patch for #5250

---

.github/CODEOWNERS

Recently I added two tools (timeline drawer #5122 and v2 pulse drawer #5101) to the visualization module.
I need maintain these codes.

Add myself to codeowner of visualization module

---

qiskit/compiler/transpile.py

The behavior in the issue https://github.com/Qiskit/qiskit-terra/issues/5409 was changed in #5495. However, I forgot to update the `transpile` docstring to reflect that change.

update doc after 5495

---

MANIFEST.in
setup.py

Fixes #1586
Update setup.py to utilize requirements.txt for installation-required dependencies. This reduces the chance of hard-to-debug errors if requirements and setup don't match

Update setup.py: REQUIREMENTS

---

qiskit/algorithms/optimizers/spsa.py

resolves https://github.com/Qiskit/qiskit-aqua/issues/1491

fix "RuntimeError: dictionary changed size during iteration"

---

qiskit/pulse/builder.py

Fix misspellings/unclear documentation in ``./qiskit/pulse/builder.py``
Only docstrings changed, no code changes.

Pulse builder interface: fix spelling

---

qiskit/circuit/quantumcircuit.py
test/python/circuit/library/test_blueprintcircuit.py
test/python/circuit/test_circuit_qasm.py

Raise if attempting to convert parameterized circuit to qasm.

---

qiskit/algorithms/minimum_eigen_solvers/numpy_minimum_eigen_solver.py
qiskit/opflow/primitive_ops/pauli_op.py

Fix deprecation msg on NumPyMinimumEigensolver and opflow

---

qiskit/algorithms/optimizers/aqgd.py
qiskit/opflow/gradients/derivative_base.py
test/python/algorithms/test_optimizer_aqgd.py

resolves https://github.com/Qiskit/qiskit-terra/issues/5650
1) custom gradient_fn enabled in **aqgd**
2) gradient_wrapper optimised in derivative_base
3) unit tests for **aqgd** using custom gradient_fn

Fix gradient use of the AQGD optimizer

---

qiskit/quantum_info/operators/channel/quantum_channel.py

resolves https://github.com/Qiskit/qiskit-terra/issues/5610
using `np.linalg.eigvalsh` to verify trace-preserving property

trace-preserving property for QuantumChannel verified more precisely

---

test/python/algorithms/test_qaoa.py

Fix https://dev.azure.com/qiskit-ci/qiskit-terra/_build/results?buildId=24547&view=logs&jobId=6d8ff735-f981-52fa-2234-caef37f9a56b&j=3956a1e0-82bc-50b0-1442-e87b8e13252f&t=4d4946a8-bdaf-51d1-e5e9-413bd0078b90

Fix seed in QAOA test

---

test/python/tools/monitor/test_job_monitor.py

Stop from `TestJobMonitor` from writing to stdout

Suppress stdout from TestJobMonitor

---

qiskit/assembler/assemble_circuits.py
qiskit/converters/circuit_to_gate.py
qiskit/converters/circuit_to_instruction.py
qiskit/quantum_info/operators/channel/superop.py
qiskit/quantum_info/operators/operator.py
qiskit/quantum_info/operators/symplectic/clifford_circuits.py
qiskit/quantum_info/states/densitymatrix.py
qiskit/scheduler/lowering.py
qiskit/transpiler/instruction_durations.py
qiskit/transpiler/passes/scheduling/alap.py
qiskit/transpiler/passes/scheduling/asap.py
releasenotes/notes/deprecate-instructionduration-get-with-qubit-instance-64a9a428bb3bdbbd.yaml
test/python/circuit/library/test_grover_operator.py
test/python/circuit/test_hamiltonian_gate.py
test/python/circuit/test_unitary.py

Following #5498 , updates converters, quantum_info, assembler, circuit library and scheduler to support optional registers, and to prefer inspecting bits over registers where possible.
~on-hold until #5498 merges.~
Commits in this PR (without #5498 and #5486 ): https://github.com/Qiskit/qiskit-terra/pull/5504/files/18c95db0f2daef7fe52674ca1ec7fb5e7f1eae3e..5c5ac703ff05a25bdea6ae57346440d15d45033f

Converters, quantum_info, assembler, scheduler and circuit library updates for optional registers.

---

qiskit/circuit/quantumcircuit.py
releasenotes/notes/issue-5939-calibrations-34c4ddf684595105.yaml
test/python/circuit/test_calibrations.py

Fixes #5939 
Added the required code in `combine` method of `QuantumCircuit` and a test to check that the calibrations are carried over.

Added LHS circuit calibrations with + operator

---

tools/report_ci_failure.py

With the use of mergify to auto backport PRs for us, a new branch is
created by the mergify bot account and a PR opened from that branch
against the stable branch. This model however is breaking the
assumptions made by the report_ci_failure.py script which assumes it is
only ever invoked from push event because normally pull requests don't
have credentials to report back to github. This is not the case for
pull requests from a branch, only pull requests from a fork. As branches
on a repo can be trusted since only users (or in this case bots) that
are trusted can create a branch they also have access to secrets and
therefore have credentials. This was causing the QacoBot account to open
issues everytime CI failed on a mergify backport PR which is not the
expected or desired behavior. This …

Fix QacoBot issue creation on backport PR CI failures

---

qiskit/quantum_info/operators/operator.py
releasenotes/notes/reverse_qargs-f2f3c9a3e1c3aaa0.yaml
test/python/quantum_info/operators/test_operator.py

Add `reverse_qargs` method to `Operator`.

Add reverse_qargs to Operator

---

qiskit/circuit/quantumcircuit.py
test/python/circuit/test_circuit_properties.py

Fix QuantumCircuit.copy not deepcopying metadata.

---

qiskit/utils/quantum_instance.py

update quantum instance to handle shots from `BackendV1` correctly.

fix quantum instance shot handling

---

.mergify.yml

To attempt to increase CI throughput, updates mergify configuration to only update one approved PR at a time.
See https://docs.mergify.io/actions/merge.html#merge .

Mergify to only update one approved PR at a time.

---

qiskit/extensions/quantum_initializer/initializer.py

Fix spelling in circuit.initializer docstring

---

qiskit/algorithms/algorithm_result.py

Improve AlgorithmResult string representation and combine

---

docs/apidocs/qiskit.algorithms.optimizers.nlopts.rst
docs/apidocs/qiskit.algorithms.optimizers.rst
qiskit/algorithms/__init__.py
qiskit/algorithms/optimizers/spsa.py

Optimizers package is missing in the docs.

Add algorithms.optimizers to docs

---

qiskit/algorithms/amplitude_estimators/mlae.py
test/python/algorithms/test_amplitude_estimators.py

Fix a couple of things for mlae.py and test_amplitude_estimators.py
Fix a typo in mlae.py
Remove a duplicated line in mlae.py
Fix a bug in test_amplitude_estimators.py (the circuits list has one element, while it should have three or six elements).

Fix a couple of things for mlae

---

qiskit/transpiler/passes/basis/basis_translator.py

Addresses #6156 by caching some internal transformations in the `BasisTranslator`. 
Local benchmark numbers:
```
$ asv continuous --python 3.6 --no-only-changed --bench '(time_compile_from_large_qasm|RandomizedBenchmarking|QuantumVolume)' master 6156-performance-regression-from-disabling-sympy-evaluate
All benchmarks:
before           after         ratio
[2ecf45d9]       [417f4510]
<master>         <6156-performance-regression-from-disabling-sympy-evaluate>
3.53±0.2s          5.98±1s    ~1.70  quantum_volume.QuantumVolumeBenchmark.time_ibmq_backend_transpile(14, 'synthesis')
5.67±0.1s        8.68±0.1s    ~1.53  randomized_benchmarking.RandomizedBenchmarkingBenchmark.time_ibmq_backend_transpile([[0, 1]])
2.05±0.1s        3.06±0.4s    ~1.49 …
```

BasisTranslator to cache bound target DAG.

---

CONTRIBUTING.md

This commit expands step 2 on updating documentation in the
CONTRIBUTING.md file's checklist for opening a PR. This was previously
missing an explanation about needing to update the `autosummary`
directives if a new class, function, or module is added otherwise it
won't be included in the documentation builds. In addition to fixing
this oversight a link is added to the contributing documentation's
section on the documentation structure to provide more details on how to
add/where to add new objects to the documentation build.

Add more details on documentation to the PR checklist

---

qiskit/providers/models/backendconfiguration.py
releasenotes/notes/control-channels-config-8928d33de782d777.yaml

Exposes the control channels of the backend configuration to the user.
This is done by introducing a new property `control_channels` that returns `_control_channels`.

Issue 6326

---

qiskit/algorithms/optimizers/nlopts/nloptimizer.py

Fix aqua link in nlopt

---

qiskit/circuit/library/n_local/qaoa_ansatz.py

Fix this pylint error.
https://dev.azure.com/qiskit-ci/qiskit-terra/_build/results?buildId=27937&view=logs&jobId=7684b0c9-af38-5400-184f-6880bd8a4dd7&j=7684b0c9-af38-5400-184f-6880bd8a4dd7&t=9d95188b-4e59-58d8-f7c4-3f1fbd4209ad
Note: Looking at the recent CI results, this fails with some uncertainty, and I don't know the conditions.

Remove unused import in circuit/library/n_local/qaoa_ansatz.py 

---

test/python/algorithms/optimizers/test_optimizer_aqgd.py
test/python/algorithms/test_measure_error_mitigation.py
test/python/algorithms/test_vqe.py

Fix aer backend deprecate msgs in algorithm unit tests

---

qiskit/circuit/library/boolean_logic/inner_product.py

update inner product documentation

---

qiskit/algorithms/linear_solvers/hhl.py

Fix HHL isinstance Failure

---

qiskit/pulse/builder.py

fixes #6538 
Updated the pulse documentation of method control_channels.

fixed issue 6538 by updating the documentation

---

qiskit/utils/measurement_error_mitigation.py
qiskit/utils/quantum_instance.py
releasenotes/notes/TensoredMeasFitter-d327f0e2d736efdd.yaml
test/python/algorithms/test_measure_error_mitigation.py

Add Support to TensoredMeasFitter in QuantumInstance

---

qiskit/transpiler/passes/layout/sabre_layout.py
qiskit/transpiler/passes/routing/sabre_swap.py

This PR should fix the performance regression that happened because of #6498. 
I basically remove an unnecessary `deepcopy` and rewrite the `_score_heuristic`.
It also fixes a small bug on SabreLayout.

Fix sabre regressions

---

test/python/circuit/test_controlled_gate.py

Removing the TODO entry that was waiting for #3304, introduced in #4076

Removing pending TODO blocked by #3304

---

qiskit/pulse/utils.py
test/python/pulse/test_parameter_manager.py

Fix parameter formatting logic

---

qiskit/visualization/qcstyle.py

these cliffords were not colored consistently with the others.

sx and sxdg colored as cliffords in mpl

---

qiskit/transpiler/passes/optimization/collect_2q_blocks.py
test/python/transpiler/test_collect_2q_blocks.py

Re-applies #6534 so that the intermittent CI failures reported in #6686 can be investigated.
Resolves #6694.
This commit is a cherry-pick of https://github.com/Qiskit/qiskit-terra/commit/3bb72d340fcf9552d4a6bd54b675399578c726db .

Reapply "Performance improvement for Collect2qBlocks (#6534)"

---

.mailmap

Consolidate my emails into only my IBM one, because GitHub insists on associating merges and suggestions made in the web interface with my personal one unless I swap to using my work one as my primary email site-wide.
I suppose it doesn't matter _too_ much because squashing commits destroys signatures, but still.

Add Jake to mailmap

---

qiskit/visualization/bloch.py
qiskit/visualization/counts_visualization.py
qiskit/visualization/gate_map.py
qiskit/visualization/matplotlib.py
qiskit/visualization/pulse_v2/plotters/matplotlib.py
qiskit/visualization/pulse_visualization.py
qiskit/visualization/state_visualization.py
qiskit/visualization/timeline/plotters/matplotlib.py
qiskit/visualization/utils.py
releasenotes/notes/fix-duplicate-mpl-drawer-ipykernel6-c64d9178e31ab9fe.yaml

The latest major version of ipykernel swapped the matplotlib backend to
the new `matplotlib_inline` separate dependency, which registers itself
with a different backend name.
Fix #6889.

Fix mpl circuit drawing duplication in ipykernel 6

---

qiskit/compiler/assembler.py
qiskit/providers/models/backendconfiguration.py

assemble ignores backend option#6902
Fixes #6902 
Edited the docstring

Fix issue#6902

---

qiskit/circuit/quantumcircuit.py

Resolve performance regression in `QuantumCircuit.depth()`.

---

qiskit/algorithms/optimizers/qnspsa.py

This class inherits from `SPSA`, which has a note about setting `qiskit.utils.algorithm_globals.random_seed` for reproducible behaviour, however this wasn't visible on the `QNSPSA` documentation page.  This commit just copies the same note up. 
Fix #7069

Add note on reproducibility to QNSPSA

---

test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py

- Replace PauliTable with PauliList or str except `test_pauli_table_init`
- Use np.testing

Refactor the unit tests of SparsePauliOp

---

qiskit/opflow/__init__.py

I've tried to match the style of the language used in the rest of the
documentation for this.
Fix #7176 (with Qiskit/qiskit-tutorials#1251).

Add note on operator precedence to opflow docs

---

qiskit/algorithms/amplitude_amplifiers/grover.py

Correction of the grammatical error in the docstring.

Fix typo in ``Grover`` docstring

---

README.md

Just updated the link to the "installing from source" section in [qiskit.org](qiskit.org) website.
Based on the link in:
https://qiskit.org/documentation/contributing_to_qiskit.html#getting-started,
and the label here:
https://github.com/Qiskit/qiskit/blob/6cdb5c1a69f7464be4db26fa0b859c5a21548dda/docs/contributing_to_qiskit.rst#L627-L633

Update the "installing from source" link in README

---

qiskit/transpiler/coupling.py

Correct typos in CouplingMap constructors

CouplingMap: fix docstrings

---

azure-pipelines.yml
qiskit/synthesis/evolution/lie_trotter.py
qiskit/synthesis/evolution/matrix_synthesis.py
qiskit/synthesis/evolution/suzuki_trotter.py
requirements-dev.txt
setup.py

This is temporary to get CI running again, while we prepare a proper
fix for the latest version.
Temporary to get CI running again.  See #7272, but this isn't a proper fix of it yet.

Pin matplotlib <3.5 and remove unused imports

---

qiskit/visualization/utils.py

Most ControlFlowOps have at least one param of type QuantumCircuit
which qiskit.visualization.utils.get_param_str will attempt to
stringify and display as an instruction parameter. This largely
doesn't work, since the circuit's string will contain newlines, so
instead draw ControlFlowOps with only their name.
Example:
```
qc = qk.QuantumCircuit(2, 1)
cbit = qc.clbits[0]
with qc.if_test((cbit, True)) as else_:
qc.x(0)
with else_:
qc.x(1)
qc.barrier()
with qc.while_loop((cbit, True)):
qc.cx(0,1)
qc.barrier()
with qc.for_loop(Parameter('p'), range(10)) as p:
qc.rz(p, [0, 1])
```
Before (text):
```
»
q_0: »
»
q_1: »
»
c: »
»
«     ┌─────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────┐»
«q_0: ┤1 …
```

Omit QuantumCircuit as a parameter when drawing ControlFlowOps.

---

qiskit/test/base.py
requirements-dev.txt
test/ipynb/mpl_tester.ipynb
test/python/notebooks/test_backend_tools.ipynb
test/python/notebooks/test_pbar_status.ipynb

Nothing has changed in the majority of files, but recent versions of `black` now support formatting Jupyter notebooks with the `jupyter` extra installed.
There's a nice `--experimental-string-processing` option which maybe something we want to consider adding into the `tox -eblack` run (but not requiring it in the full check); it'd have saved @levbishop a bunch of time a short while ago.
If we accept it, probably no need to bother adding this PR to the ignored commits file in the repo root, since the changes are incredibly minimal.

Bump black to the latest version

---

qiskit/algorithms/__init__.py
qiskit/opflow/operator_globals.py
qiskit/opflow/primitive_ops/pauli_sum_op.py
qiskit/quantum_info/operators/measures.py

I have fixed a few typos in comments and strings, and updated one outdated reference to `qiskit.chemistry`.

Fix a few typos in comments and strings

---

qiskit/visualization/state_visualization.py

fix #7420 Alternate example for plot_bloch_multivector
Added example for not entangled state.

Alternate example for plot_bloch_multivector

---

qiskit/algorithms/__init__.py
qiskit/algorithms/amplitude_amplifiers/amplitude_amplifier.py
qiskit/algorithms/amplitude_estimators/amplitude_estimator.py
releasenotes/notes/fix-algorithms-7f1b969e5b2447f9.yaml

`qiskit.algorithms.amplitude_estimators.AmplitudeEstimator` now inherits from `ABC`.
`qiskit.algorithms.amplitude_amplifiers.AmplitudeAmplifier` is now included in ``qiskit/algorithms/__init__.py`` file.
Closes: #7751

AmplitudeEstimator/Amplifier minor refactoring and docs.

---

qiskit/circuit/library/standard_gates/xx_plus_yy.py
releasenotes/notes/add-xy-gate-e3ac32084273136a.yaml

I missed updating the release note in #7786 . Also, I fixed an error in a docstring.
@Cryoris

fix XXPlusYYGate documentation and release note

---

qiskit/extensions/unitary.py

The pull request fixes issue https://github.com/https://github.com/Qiskit/qiskit-terra/issues/7206. I have added the suggested code chunk to the class description.

Example for creating quantum circuit from unitary matrix

---

test/randomized/test_transpiler_equivalence.py

After merging #7980, it looks like rule probabilities need
to be adjusted a bit for us to get useful test cases to
run. Currently, Hypothesis spends most of the test cycles
adding registers rather than useful gates, and often skips
running the equivalent transpile rule altogether since it
seemingly runs out of steps.
This commit limits the number of classical and quantum
registers to 3 each (arbitrary) to increase the chances
of gate generation and invocation of the equivalent
transpile rule.
The number of examples has also been increased from 25
to 200, which should vastly improve the coverage of
this test (it seems to exercise more useful circuits per run),
at the expense of a longer runtime.

Tweak probabilities in random equivalence test

---

qiskit/result/distributions/quasi.py

This fixes a typo.  I've been sitting on this for several weeks and have not noticed any other typos in that time, so am finally submitting it as a PR.

Fix typo: [qasi -> quasi]-probability

---

qiskit/providers/backend.py

Grammar and syntax cleanup in comment to `def run`
Trivial but neat.

Fix grammar in `Backend` documentation

---

qiskit/primitives/base_estimator.py
qiskit/primitives/base_sampler.py
qiskit/primitives/estimator.py
qiskit/primitives/estimator_result.py
qiskit/primitives/sampler.py
qiskit/primitives/sampler_result.py
qiskit/primitives/utils.py
qiskit/transpiler/passes/synthesis/unitary_synthesis.py
releasenotes/notes/primitive-interface-408b91ed338a5bc4.yaml
test/python/primitives/test_estimator.py
test/python/primitives/test_sampler.py

This PR enhances Primitives (Sampler and Estimator) and provide a more flexible interface.
This comes from the discussion #8035.
The major difference is that the previous PR provided a function to extend the interface, but this one does so by default.
As discussed offline, this PR is API breaking but only for internals.
If needed, I will add a DeprecationWarning, please point it out in the review comments.
TODO:

Enhance Primitives' interface

---

qiskit/quantum_info/operators/symplectic/pauli.py

Two things 
- equation does not show up (this hasn't been fixed)
- the code doesn't render

enables the code example

---

qiskit/extensions/quantum_initializer/initializer.py

Fixed docstring in `Initialize`

---

requirements-dev.txt

https://github.com/sphinx-doc/sphinx/issues/10701 is fixed

Remove upper cap on Sphinx version (undoes #8392)

---

qiskit/primitives/base_estimator.py
qiskit/primitives/base_sampler.py

This is my mistake. These are deprecated from next release (0.22).

Fix deprecation messages in BaseSampler/BaseEstimator

---

test/randomized/test_transpiler_equivalence.py

Hypothesis sometimes fails to shrink tests or provide a proper
reproducer because there is also randomisation in the transpiler.  This
now outputs a `seed_transpiler` value as part of the draw, which should
fix the output completely.  The draw configuration is re-organised into
a `kwargs` dictionary because the argument list was getting unwieldy.

Generate transpiler seed in randomised testing

---

qiskit/visualization/__init__.py

Prevent extraneous file generated by docs build

---

releasenotes/notes/add-fidelity-interface-primitives-dc543d079ecaa8dd.yaml
releasenotes/notes/add-gradients-with-primitives-561cf9cf75a7ccb8.yaml

Fix release notes code block format

---

test/python/algorithms/minimum_eigensolvers/test_adapt_vqe.py

This replaces the flaky AdaptVQE cyclicity termination test with a test for the internal cyclicity detection method. This test simply cannot be flaky.
Closes #8806

fix: rewrite AdaptVQE cyclicity test

---

.github/CODEOWNERS
qiskit_bot.yaml

I recently don't follow the development of visualization module except for pulse and timeline. I'll remove myself from the visualization code owner not to confuse the developers.

Remove nkanazawa1989 from code owner

---

qiskit/transpiler/preset_passmanagers/plugin.py

A few small tweaks to the staged pass manager documentation I thought might be worthwhile after following it to integrate `qiskit-toqm` in PR https://github.com/qiskit-toqm/qiskit-toqm/pull/30.

Doc fix-ups for staged pass manager plugin

---

qiskit/circuit/library/standard_gates/dcx.py

This updates an incorrect docstring in DCXGate. 
Fix https://github.com/Qiskit/qiskit-terra/issues/8990

Fix DCXGate's QASM docstring #8990

---

README.md

Two of the code blocks modified in #8686 are currently missing language information, so don't get highlighted correctly.

Add misssing language from README codeblocks

---

qiskit/algorithms/optimizers/__init__.py
qiskit/algorithms/optimizers/nlopts/__init__.py
qiskit/utils/optionals.py

Update NLopt install instructions

---

qiskit/circuit/quantumcircuit.py
releasenotes/notes/circuit-from-instructions-832b43bfd2bfd921.yaml
test/python/circuit/test_circuit_operations.py

add QuantumCircuit.from_instructions

---

qiskit/algorithms/gradients/lin_comb_estimator_gradient.py
releasenotes/notes/fix-complex-gradient-sign-25f153b5a53ae259.yaml
test/python/algorithms/gradients/test_estimator_gradient.py

This PR fixes the bug below and adds relevant unit tests.
Closes: #9112

Fixed sign bug in docs in LinCombEstimatorGradient.

---

qiskit/utils/optionals.py

Since gh-9035 this documentation has been out-of-date.  This updates it to give the correct information.

Update `HAS_NETWORKX` documentation

---

test/python/algorithms/optimizers/test_optimizer_aqgd.py
test/python/algorithms/test_shor.py

Fix slow unit tests

---

qiskit/qpy/__init__.py

This commit adds a missing top level description of what QPY is to the module docs for QPY. The existing documentation provides a good overview of how to use qpy and a very detailed guide to the format specification, but it does not actually say what QPY is up front. This commit fixes that gap and also adds an example for saving multiple circuits in a single file.

Add top level summary to QPY module docs

---

qiskit/result/counts.py

Inspired by https://quantumcomputing.stackexchange.com/q/27530/1859, some small clarifications in `Counts`.

some small issues in Counts documentation 

---

.github/CODEOWNERS

Adds @ElePT to the ``qiskit/algorithms`` code owners. Elena has rewritten a substantial part of the algorithms with the primitives and knows the codebase and it's interaction with the applications, plus the integration with the primtives and Qiskit Runtime, very well.

Add ElePT as ``qiskit/algorithms`` code owner

---

requirements-dev.txt

Relax ipywidgets in requirements-dev.txt
Follow-up #9364

Relax ipywidgets (follow-up #9364)

---

qiskit/circuit/library/arithmetic/polynomial_pauli_rotations.py
qiskit/transpiler/passes/routing/sabre_swap.py
qiskit/transpiler/passmanager.py

I fixed a few docstring typos that I noticed.

Fix some typos in the docstrings

---

docs/apidocs/circuit_library.rst
docs/apidocs/terra.rst
docs/index.rst
qiskit/circuit/__init__.py

I read the contributing guidelines.
I moved the circuit_library to be within API Reference regarding issue #9462.  In addition, regarding issue https://github.com/Qiskit/qiskit/issues/1644  Removed Circuit Library from (sidebar) being at the same level as API Reference. 
Close #9462

Add circuit library to Terra API Reference list

---

releasenotes/notes/0.23/prepare-0.23.0-release-0d954c91143cf9a4.yaml

https://github.com/Qiskit/qiskit/pull/1662#pullrequestreview-1288166312

Fix Python 3.7 support removal date (wrong year)

---

qiskit/quantum_info/synthesis/xx_decompose/decomposer.py

I ran into this line during a PR review and found it needlessly confusing.

rewrite needlessly confusing line

---

qiskit/circuit/library/standard_gates/z.py

fixes:
- |
Fixes a mistake (missing i) in the documentation for ZGate. Refer to
`#9588 <https://github.com/Qiskit/qiskit-terra/issues/9588>` for more
details.

ZGate note in documentation fixed

---

test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py

@t-imamichi found these tests are ignored since there are no prefixes `test`.
This PR enables ignored tests.

Enable ignored tests in SparsePauliOp

---

qiskit/visualization/counts_visualization.py

"legendL" should be "legend". Also use f-string rather than percent formatting.

Fix typo in docstring

---

README.md

Update slack invite link to https://qisk.it/join-slack

---

qiskit/circuit/library/standard_gates/ecr.py
releasenotes/notes/add-inverse-ecr-e03720252a0c9c1e.yaml

The ECRGate() is self inverse, so this PR adds an inverse method to the ECRGate().

Add inverse method to ECRGate

---

qiskit_bot.yaml

I (Eric) don't watch the whole repo, but would like to be able to help review Rust changes.

Tag Eric in Rust changes

---

.azure/test-linux.yml
.azure/tutorials-linux.yml
requirements-dev.txt

Reverts https://github.com/Qiskit/qiskit-terra/pull/9477, now that we've solved both root causes via https://github.com/Qiskit/qiskit-terra/pull/9758 and https://github.com/Qiskit/qiskit-terra/pull/9754.

Remove tweedledum from requirements-dev.txt

---

qiskit/algorithms/time_evolvers/variational/var_qite.py
qiskit/algorithms/time_evolvers/variational/var_qrte.py

Fixes outdated code snippets in variational time evolvers docstrings, as raised in https://github.com/Qiskit/qiskit-terra/issues/9859. Adds an example with auxiliary operators for completion.
Closes https://github.com/Qiskit/qiskit-terra/issues/9859

Fix examples in `VarQITE` and `VarQRTE` docstrings

---

qiskit/quantum_info/operators/symplectic/base_pauli.py
qiskit/quantum_info/operators/symplectic/pauli_list.py

Fixes a copy/paste typo in `PauliList.insert` docstring

Fix a typo in `PauliList.insert` docstring

---

tox.ini

See https://github.com/Qiskit/qiskit/pull/1690 for the motivation and details.

Add `docs-clean` command to Tox

---

qiskit_bot.yaml

In #9835 Manoel was removed from codeowners. This removes him from the bot yaml file and for `algorithms` replaces him by @ElePT

Update bot yaml

---

requirements-dev.txt

We try to avoid breaking changes with the Sphinx theme and keep it as stable as possible. 
Still, it's more stable for us to only upgrade to new minor releases when we want to. That allows us to better make clear the new theme will render how we want.
This aligns with the change to the metapackage in https://github.com/Qiskit/qiskit-metapackage/pull/1715.
The docs team will be in charge of upgrading the theme version.

Pin Sphinx theme to minor release

---

qiskit/qasm3/__init__.py

This is a part of documentation that wasn't clear from #9916, but is important to flag for users.
Suggested from https://github.com/Qiskit/qiskit-terra/pull/9928#discussion_r1170575102.

Add note on support window for experimental OQ3

---

requirements-dev.txt

See https://github.com/Qiskit/qiskit_sphinx_theme/releases/tag/1.11.0 for the detailed changelog.
Some highlights:
* Fixed IBM fonts not loading
* Left sidebar can have expandable sections
* Left sidebar shows the previous versions as an expandable section now, unexpanded by default
* Page table of contents on the right stays fixed when scrolling

Upgrade Sphinx theme to 1.11

---

requirements-dev.txt

This week, we want to use the new subsection feature for the 0.24 release notes. So, we can use a VCS requirement until they do a formal release.
This is a dev-only requirement, so it's safe to use VCS.

Upgrade Reno for subsection support

---

qiskit/circuit/library/generalized_gates/rv.py
qiskit/circuit/library/n_local/excitation_preserving.py
qiskit/circuit/library/standard_gates/global_phase.py
qiskit/circuit/library/standard_gates/p.py
qiskit/circuit/library/standard_gates/r.py
qiskit/circuit/library/standard_gates/rx.py
qiskit/circuit/library/standard_gates/ry.py
qiskit/circuit/library/standard_gates/rz.py
qiskit/circuit/library/standard_gates/u1.py
qiskit/circuit/library/standard_gates/y.py

- Fix typos in the documentation of gates
- Resolve #6750
- I closed #10139 and reopened this due to messy commit history.

Fix typo in documentation

---

docs/migration_guides/qi_migration.rst

Update typo in `qi_migration.rst`

---

examples/python/initialize.py
pyproject.toml
qiskit/pulse/macros.py
qiskit/qobj/converters/pulse_instruction.py
qiskit/transpiler/coupling.py
qiskit/transpiler/passes/layout/disjoint_utils.py
test/python/pulse/test_block.py

Turn on `enable flake8-comprehensions` (C4) and use it (with --fix) to make a few nice simplifications.

Ruff enable flake8-comprehensions (C4)

---

qiskit_bot.yaml

With Junye moving away from the docs effort (congratulations!), he's no longer a suitable contact for people whose PRs touch the documentation.
@HuangJunye: I'd understood from our talk that you'd want your tag removed from this.  Let me know if you want it to stay, though, and we can just close this PR.

Remove Junye from Qiskit Bot notifications

---

docs/apidocs/passmanager.rst
docs/apidocs/terra.rst
qiskit/passmanager/__init__.py
qiskit/passmanager/base_pass.py
qiskit/passmanager/exceptions.py
qiskit/passmanager/flow_controllers.py
qiskit/passmanager/passmanager.py
qiskit/passmanager/passrunner.py
qiskit/passmanager/propertyset.py
qiskit/transpiler/__init__.py
qiskit/transpiler/basepasses.py
qiskit/transpiler/exceptions.py
qiskit/transpiler/passmanager.py
qiskit/transpiler/runningpassmanager.py
releasenotes/notes/add-passmanager-module-3ae30cff52cb83f1.yaml

Now that 0.45 development is open on main we can restore #10124. This reverts Qiskit/qiskit-terra#10454

Revert "Revert "Pass manager refactoring: add passmanager module (#10124)""

---

test/python/compiler/test_transpiler.py

These tests are the culmination of all the `Expr` work; there was no clean point to add them until all the moving pieces were in place.
Fix #10234.

Add transpiler integration tests for `Expr` nodes

---

README.md

Updated the readme to reflect partial funding from the C2QA NQI center.

Add C2QA attribution to README

---

qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py

Fix an error message at Sparse PauliOp.

Fix error message at class SparsePauliOp
