Qiskit/qiskit

CODEOWNERS
README.rst
doc/conf.py

minor changes do documentation.

more minor doc changes

---

qiskit/_quantumcircuit.py
qiskit/_quantumprogram.py
qiskit/extensions/standard/ch.py
qiskit/extensions/standard/crz.py
qiskit/extensions/standard/cu1.py
qiskit/extensions/standard/cu3.py
qiskit/extensions/standard/cx.py
qiskit/extensions/standard/cy.py
qiskit/extensions/standard/cz.py
test/python/test_quantumprogram.py

- Fixed measure and control gates to work on registers of qubits.
- Added magic methods to combine Result objects.
- `circuit.measure(qr, cr)` now will apply measure operations between all qubits in a quantum register and all bits in a classical register. If registers are not the same size it will raise an exception. Eg if both a size 2 it will return qasm `measure qr[0]->cr[0]; measure qr[1]->cr[1];`
- `circuit.cx(qr1, qr2)` will apply CNOT gates between each qubit in register `qr1` to each qubit in register `qr2`. If registers are not the same size it will raise an exception. Eg. if both a size 2 it will return qasm `cx(qr1[0], qr2[0]); cx(qr1[1], qr2[1]);`. The same change was made for `cz, cy, ch, crz, cu1, cu3`.
- Results may be combined using `+` and `+=`. Combining results with `+` …

Combine results, apply controlled gates and measure to whole registers

---

test/python/test_qi.py
tools/qi/qi.py

- Fixed errors with concurrence and state_fidelity in tools.qi
- Added unit tests for tools.qi functions
- The `state_fidelity` function was returning `NaN` for pure state density matrices due to issues with `scipy.linalg.sqrtm`. I fixed this by adding a function `funm_svd` similar to the build in `scipy.linalg.funm` that applies a scalar function to the singular values of a matrix. The matrix square root for positive-semidefinite matrices is then computed using this function.
- The `concurrence` function was returning negative values for some states which should have zero concurrence (for example the maximally mixed two qubit state). This has been fixed.
- Fixed concurrence and purity to work for array_like input states (such as lists) by converting the input to a ndarray.
- Added `raise …

Added tests and fixed bugs in tools.qi

---

Makefile

This addresses an issue with installation of setuptools during initial 'make env'.
'make env' also tries to deal more gracefully with previous run of the target. Also, 'pip install' was removed from 'make test' since 'make env' now handles that.
started new conda environment to test 'make env'.

fixes issue #17

---

pypi.sh
requires.txt
setup.py

* Added setup.py script for creating a Pure Wheels distributed package.
* Added a helper script for uploading distributable packages to PyPi.
Locally: make test

Pip support

---

qiskit/_quantumprogram.py
test/python/test_quantumprogram.py

The SDK will throw a ConnectionError exception if there's a problem with the Internet connection, so the user can act accordingly.
Example:
```python
try:
self.quantum_program.set_api(TOKEN, URL)
except ConnectionError as ex:
self.offline = True
except CredentialsError as ex:
self.ask_for_credentials()
...
```
A new test has been added to ensure that set_api() method throws a ConnectionError when there's
no connection to the API servers.

Issue 49 - Better offline support

---

qiskit/_quantumprogram.py

We want to rethrow this exception so app developers can capture it.
There's a specific test: test_simulator_online_size()

Rethrow IBMQuantumExperience RegisterSizeError exception

---

qiskit/_jobprocessor.py
test/python/test_job_processor.py

* JobProcessor constructor will throw if no valid backend is found
in any of the jobs.
* Some import refactoring
Added a new test in test_job_pocessor.py: test_backend_not_found.
All tests pass locally and in Travis.

Issue 80 - Fix non-valid backend

---

tools
tools/random_qasm_generator.py

This tool will print on the standard output a QASM program which instructions
were generated randomly and are equally weighted between U3 and CX. 
The program is valid from the point of view of QASM syntax but it has no valid logic. 
The main purpose of this tool is to help in benchmarking and testing Quantum simulators.
Usage example:
Create a QASM circuit file called circuit.qasm with ~100 operations 
(CX and U3 gates), 16 Qubits, and a seed of 169
`./random_qasm_generator.py -s 169 -d 100 -q 16 > circuit.qasm`
**I'm using this PR to reuse /tools directory. The old one was not useful anymore since
pip integration**
This tool could be useful for testing and/or benchmarking simulators.

Add a new tool to generate random QASM circuits

---

qiskit/qasm/_node/__init__.py
qiskit/qasm/_node/_binaryop.py
qiskit/qasm/_node/_binaryoperator.py
qiskit/qasm/_node/_if.py
qiskit/qasm/_node/_indexedid.py
qiskit/qasm/_node/_magic.py
qiskit/qasm/_node/_prefix.py
qiskit/qasm/_node/_unaryoperator.py
qiskit/qasm/_qasmlexer.py
qiskit/qasm/_qasmparser.py
qiskit/unroll/_unroller.py
test/python/qasm/example_if.qasm
test/python/test_qasm_parser.py

Fixes for #62 and related issues:
* ensure that the following Nodes have children which are always a subclass of `Node`:
* `IndexedId` (as noted in https://github.com/QISKit/qiskit-sdk-py/issues/62#issuecomment-328586459)
* `BinOp` and `Prefix` (as noted in https://github.com/QISKit/qiskit-sdk-py/issues/62#issue-256569802). This involved introducing new nodes (`BinaryOperator` and `UnaryOperator`) to represent the children nodes.
* `Magic` (discovered during testing).
* additionally fix the `^` operator, as it seems it produced a syntax error on the current version of the lexer as it was not considered a valid literal.
The operators are still considered plain `literal`s by the lexer - I'm not sure if it would be arguably cleaner to [consider them proper …

Issue #62: make AST nodes always Node subclasses

---

qiskit/_jobprocessor.py
qiskit/_quantumprogram.py
qiskit/mapper/_compiling.py

The function _run_internal in qiskit/_quantumprogram.py is not passing on the wait and timeout parameters to the jobprocessor. This PR fixes this issue.
Moreover, the documentation about the wait and timeout parameters for the functions run, run_async, run_batch, run_batch_async is a bit confusing. This PR also changes this.
Clarifying the use of wait and timeout parameters.
The existing tests pass.

Fixing the documentation and use of wait and timeout parameters in _quantumprogram

---

.pylintrc
Makefile
qiskit/backends/_qasmsimulator.py
qiskit/backends/_simulatortools.py
qiskit/dagcircuit/_dagcircuit.py
qiskit/mapper/_compiling.py
qiskit/mapper/_coupling.py
qiskit/mapper/_mapping.py
qiskit/qasm/_qasmlexer.py
qiskit/unroll/_unrollerbackend.py
test/python/test_apps.py
test/python/test_basebackend.py
test/python/test_job_processor.py
test/python/test_jsonoutput.py
test/python/test_local_qasm_cpp_simulator.py
test/python/test_qasm_parser.py
test/python/test_qasm_python_simulator.py
test/python/test_qi.py
test/python/test_quantumprogram.py
test/python/test_unitary_python_simulator.py

Make the default linter configuration less strict, reducing the number
of false positives and the usefulness of the existing output with a
combination of:
* ignoring specific files entirely (such as the parser or the standard
extension individual files)
* ignore specific warnings on some files (such as "invalid-name" on
files that use variables mapped to mathematic algorithms)
* disable specific tags globaly (in particular, "no-self-use")
Also make the linter more strict when it comes to docstrings via the
"pylint.extensions.docparams" plugin.
In numbers, this would make the number of warnings from ~1700 to ~800 - which is still a sizable number but hopefully making the number of false positives and the significance of the warnings higher, and pave the way for making #90 easier to tackle. …

Relax the default linter checks

---

doc/dev_introduction.rst
qiskit/_jobprocessor.py
qiskit/_logging.py
qiskit/_openquantumcompiler.py
qiskit/_quantumprogram.py
qiskit/backends/_qasm_cpp_simulator.py
qiskit/backends/_qasmsimulator.py
qiskit/backends/_unitarysimulator.py
qiskit/mapper/_mapping.py
test/python/test_job_processor.py
test/python/test_quantumprogram.py

* add `QuantumProgram.enable_logs()` and `disable_logs()` as the single point of entry for setting/unsetting the verbosity of the output, replacing the different `verbose` and `silent` parameters.
* add a `qiskit._logging` module that contains two convenience functions for setting up the loggers (format, handlers) to be used by the SDK, defaulting to sensible values.
* replace `print()` with `logger.info()` (or `logger.debug()` on the mapper)
Not included in this PR:
* replacement of `verbose/silent` and `print` in `qiskit.tools` (might be well suited for a follow-up first contribution PR)
* fine grained decision about what current output should be `INFO/WARNING/DEBUG`
* allowing the user to override the logging format (might be better tackled along with a bigger scope PR that introduces …

Issue #88: use standard logging instead of print

---

qiskit/qasm/_qasmlexer.py

Revise the lexer to prevent that the identifiers that start with a reserved word are interpreted as other types of token instead of identifiers, following the [guideline on the Ply documentation](http://www.dabeaz.com/ply/ply.html) (Section 4.3).
Fix issue #82, which is a bit more general than initially reported - the parser mistakenly interprets identifiers that begin with a "reserved word" such as:
```
qreg qregister[2];
barrier ifthisisabarrier;
```
as if they were a token + an identifier (`qreg`:QREG `ister`:ID, `if`:IF `thisisabarrier`:ID), causing the syntax to be invalid. 
`make test`, plus also `make test` at the `QISKit/openqasm` repository to validate with the full list of examples.

Fix ids starting with reserved word tokenizing #82

---

qiskit/extensions/standard/iden.py

Fixed typo with identity circuit extension.
The `reapply` method called `id` instead of `iden`. This bug only showed up if you tried to combine circuits containing an identity gate. Eg:
```Python
from qiskit import QuantumProgram
qp = QuantumProgram()
qr = qp.create_quantum_register('qr', 1)
circ1 = qp.create_circuit('circ1', [qr], [])
circ2 = qp.create_circuit('circ2', [qr], [])
circ1.h(qr)
circ2.iden(qr)
circ1 + circ2
>>> AttributeError: 'QuantumCircuit' object has no attribute 'id'
```
Tests pass

fixed typo in iden.py

---

qiskit/tools/apps/optimization.py

removing passing silent option to Q_program.execute
silent option has been removed from _quantumprogram previously
tested by running optimization notebook from qiskit-tutorial

removing silent parameter from Q_program.execute

---

qiskit/_result.py
qiskit/tools/file_io.py
test/python/test_quantumprogram.py

Added functionality to the Result class to save/load the qobj and result to a JSON file. 
The save creates a new dictionary that combines qobj,result and a user-defined metadata dictionary. This is then saved to a JSON file. There is a function which can create a time-stamped filename. Because the 'local_unitary_simulator' backend creates a result dictionary with complex numpy arrays I added some hidden functions to the Result class to convert those into lists. 
Currently there is no way to save results. This is needed functionality for running experiments where we need to keep a detailed record of past results and for analyzing results at a later date.
I saved and loaded Results from the different backends.  
Code will look something like this (where qpresult is the result output from an …

Added a save/load feature to Result

---

qiskit/_result.py

Add an extra check before raising the contents of `Result._result['result']` for erroneous results, as it is not guaranteed that they will contain an Exception in all cases.
This was caught by a user and reported on [Quantum Experience](https://quantumexperience.ng.bluemix.net/qx/community/question?questionId=b628cacd77cab777ca51c48b01a37415).
It might be a better option to ensure that in **all** cases where `Result._is_error()` is `True`, `self._result['result']` contains an `Exception`. This would involve tweaking `_wait_for_job()`, making sure that it fulfills that condition - I have not implemented the fix using that approach as it seems a design decision rather than a minor fix.
`make test`

Fix raising on non-exception in Result.get_data()

---

qiskit/_quantumprogram.py
test/python/test_quantumprogram.py

Add a method to `QuantumProgram` to reconfigure an already compiled qobj to change parameters that are not dependent on compilation (e.g. shots, backend, config...)
The compilation step (`QuantumProgram.compile()`) takes a finite amount of time and it is not necessary to recompile if we just need to change certain configuration options. Technically the user could just change the qobj dictionary, but this abstraction will ensure less code is broken if there are future changes to the qobj structure as these would just need to be fixed in this method. 
Added a unit test.
- [ x] New feature (non-breaking change which adds functionality)

Added a reconfigure qobj method to quantum program

---

qiskit/qasm/_qasm.py
qiskit/qasm/_qasmparser.py

* Yacc temporary files are generated in random temporary
directories, allowing multiple users to use QISKit in the same
machine.
* QasmParser is now a context manager.
This PR fixes issue 137.
$ make test

Issue 137 - QASM parser problems with multiuser environments

---

qiskit/tools/qcvv/tomography.py
qiskit/tools/visualization.py

Fix for an indentation error in code.
As above.
@diego-plan9 @ChristopheVuillot I am very sorry but an indentation error somehow got into our code. This pull request provides a fix for it.  
We have downloaded the revised code to a fresh location from GitHub and testing locally.

Wigner function functionality: Fixed an error

---

.pylintrc
.travis.yml
qiskit/dagcircuit/_dagcircuit.py
qiskit/mapper/_compiling.py
qiskit/mapper/_mapping.py

Confirms the need for #146 
flake8 testing of https://github.com/QISKit/qiskit-sdk-py on Python 3.6.3
$ __flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics__
```
./qiskit/dagcircuit/_dagcircuit.py:570:49: F821 undefined name 'n'
nd = input_circuit.multi_graph.node[n]
^
./qiskit/tools/visualization.py:463:70: E999 SyntaxError: EOL while scanning string literal
"""Plot the equal angle slice spin Wigner function of an arbitrary
^
./qiskit/tools/qcvv/tomography.py:805:17: E999 IndentationError: expected an indented block
W[wpt] = W[wpt]+(x[i]/shots)*parity[i]
^
2     E999 IndentationError: expected an indented block
1     F821 undefined name 'n'
3
```
Add flake8 to the testing to find syntax errors and undefined names.  Revisits #8 
We want highly reliable software …

Use pylint to look for issues on every pull request

---

qiskit/tools/apps/fermion.py
qiskit/tools/qi/pauli.py
test/python/test_qi.py

This allows for direct comparison of pauli operators and is much faster than conversion to text as used previously. 
in qiskit.tools.qi.pauli I added the two overloading operators to the Pauli class for == and !=
in qiskit.tools.apps.fermion I changed the textual comparison that was used to a direct one
Some code in the chemistry examples uses a comparison 'if pauli1.to_label() == pauli2.to_label().'
With the proposed change the comparison is just 'if pauli1 == pauli2'. The direct comparison is 15x faster than the conversion to strings and thus significantly speeds up several codes.
pa = Pauli([0,0,1,1,1],[1,0,1,0,0])
pb = Pauli([0,0,1,1,1],[1,0,1,0,0])
pc = Pauli([0,0,1,1,1],[1,0,1,0,1])
if pa == pb:
print('the first two are equal')
if pa != pc:
print('the second two are not equal')
and …

Overloading of comparison operator for pauli operator class. 

---

qiskit/_quantumprogram.py
test/python/test_quantumprogram.py

* Propagate timeout (and other) parameters to QuantumJob constructor
* Test created to test timeouts
Fixes #168 
Locally tested.
A new tests has been introduced: test_quantumprogram.py: test_timeout()

Issue 168 - Jobs timeouts are wrongly managed

---

Qconfig.py.default
README.md
doc/install.rst
qiskit/_quantumprogram.py
requirements.txt
test/python/test_ai_ibmq.py
test/python/test_api_ibmq.py

Changes related for supporting IBM Q features while preserving compatibility:
* Update `QuantumProgram.set_api()` so it accepts `hub`, `group`, `project` as optional parameters.
* Add a new `QuantumProgram.set_api_hubs_config()` for modifying those parameters during a run.
* Revise the `Qconfig.py.default` file, adding the new parameters and clarifying the instructions.
* Revise the documentation, copying the `Qconfig` information to the main `README.md` and updating the instructions.
* Add tests (currently only not-skipped if a valid Qconfig is found, still not on the CI)
Support the new IBM Q features.

Add support for IBM Q hubs, groups and projects

---

qiskit/_quantumprogram.py
test/python/test_quantumprogram.py

New routines destroy_* that pair with all the create_* routines
The codebase contains routines for creating quantum registers, classical registers, and circuits, but there is no way to destroy them. Since a new register or circuit cannot be created with the same name, this restricts the reuse of a quantum program, resulting in either an ever-growing quantum program with more registers and circuits, or constantly recreating the quantum program object
I have been running stress tests, which include 6 hour runs using a single quantum program object, constantly reusing the same named quantum and classical registers and circuits, creating and destroying them each pass.

Add destroy routines for registers and circuits

---

Makefile
doc/dev_introduction.rst
test/python/common.py
test/python/test_quantumprogram.py

It looks like the logfiles generated by the test suite are unnecessary (comment here if I'm wrong). Logs can be useful in very specific situations, such as writing new tests or checking when one of them is failing. This PR makes them show up "on demand", with a env var called `LOG_LEVEL`:
`env LOG_LEVEL="INFO" python -m unittest test/python/test_apps.py`
If you wan to run the full test suite:
`make test_verbose`
By default, the tests only print CRITICAL issues. They should be rare and, when show up, should not be ignored.
The output now is cleaner, so you can focus on things that are really important.

[test suite] No more logs in file. Logs on stderr on demand.

---

qiskit/mapper/_mapping.py

When an operator is removed in the function optimize_1q_gates an operator u3 is created without necessity and harms the next iterations. For instance with the following code based on #159 
from qiskit import QuantumProgram
import Qconfig
import pickle
import sympy as sp
qp = QuantumProgram()
qp.set_api(Qconfig.APItoken, Qconfig.config["url"])
qr = qp.create_quantum_register('qr',2)
cr = qp.create_classical_register('cr',2)
qc = qp.create_circuit('Bell',[qr],[cr])
qc.h(qr[1])
qc.h(qr[1])
qc.h(qr[1])
qc.cx(qr[1], qr[0])
qc.cx(qr[1], qr[0])
qc.cx(qr[1], qr[0])
qc.measure(qr[0], cr[0])
qc.measure(qr[1], cr[1])
backend = 'ibmqx4'
try:
f = open(backend,'rb')
cmap = pickle.load(backend)
except:
cmap = qp.get_backend_configuration(backend)['coupling_map']
qobj = qp.compile(["Bell"], …

mapper issue

---

qiskit/_quantumprogram.py

Some devices would return a basis of the form 'SU2+CNOT'.
If there are no commas in basis string it will be replaced
with u1,u2,u3,cx.id and a warning will be logged.
Without this change the unroller just uses U and CX gates when it encounters this unrecognized basis specification. When all remote backends adopt the new basis specification this code can probably be elimintated, however, in the future it may be better for the unroller to throw an exception if it encounters such an error.

catch deprecated basis specification

---

doc/example_real_backend.rst
qiskit/_openquantumcompiler.py
qiskit/_quantumprogram.py
qiskit/backends/_qeremote.py
test/python/test_quantumprogram.py

* QuantumProgram::compile() now accepts an 'hpc' parameter with
the format:
{ "multi_shot_optimization": Boolean,
"omp_num_threads": Numeric }
* hpc parameter is mandatory for the new backend but it's not
allowed for the rest of the backends.
* Tests added for checking parameter format correctness.
Run all tests locally: make test
Added two new tests: test_hpc_parameter_is_correct and test_hpc_parameter_is_incorrect

Added support for ibmqx_hpc_qasm_simulator backend:

---

qiskit/tools/qcvv/tomography.py
test/python/test_tomography.py

Improves tomography tools module to allow:
- More detailed document strings
- Default SIC-POVM based initial state for process tomography.
- Custom input and measurement bases
- Unifying state and process tomography functions by using a dict of experimental configurations
- Basic unit tests
Current implementation of process tomography is suboptimal in the number of prepared initial states.
Unit tests added in test_tomography.py test module
Wrapper functions were added to maintain backwards compatibility with old tomography.py though these should be phased out.
- [] My change requires a change to the documentation.
- [] I have updated the documentation accordingly.

Tomography module improvement

---

examples/python/basic_optimize.py
examples/python/initialize.py
qiskit/__init__.py
qiskit/_instruction.py
qiskit/extensions/quantum_initializer/__init__.py
qiskit/extensions/quantum_initializer/_initializer.py
test/python/test_initializer.py

The main contribution is a new class Initializer that implements the (complex amplitude) initialization of a flexible collection of qubit registers (assuming the qubits are in the zero state).
The class implements a recursive initialization algorithm including optimizations from "Synthesis of Quantum Logic Circuits" Shende, Bullock, Markov https://arxiv.org/abs/quant-ph/0406176v5
Additionally implements some extra optimizations: remove zero rotations and double cnots.
Incorporated changes from Diego and Ali.
The current SDK does not allow for arbitrary multi-qubit initialization.
Two python demo examples included.
Ali created 10 test cases.
No other code is affected because ONLY new functionality is added in the form of a new class that inherits from the CompositeGate class.

New CompositeGate Class for Arbitrary Multi-Qubit Initialization (take 2)

---

qiskit/tools/qcvv/tomography.py
test/python/test_tomography.py

This patch fixes the following errors in the `qcvv.tomography` module and unit tests:
1. Issue #236
2. An error in fitting process tomography data due to input qubits being reversed
3. An error in the unit test testing 2-qubit process tomography
The second error was due to the qubit order being reversed when converting measurement counts to a process tomography data dictionary. This resulted in the reconstructed process matrix differing from the true input by a permutation of the qubits. There was also an error in the unit test that prevented this issue from being detected there.
@diego-plan9 @atilag this patch should be merged into stable ASAP (though after someone else verifies there aren't more bugs!).

Fix bug with process tomography reversing qubit preparation order

---

CONTRIBUTING.rst

Link currently points at https://github.com/QISKit/qiskit-sdk-py/blob/master/www.sphinx-doc.org
I've also removed a (single) unnecessary piece of whitespace.
https://github.com/QISKit/qiskit-sdk-py/issues/100
Link now works in my fork :+1:

Fix sphinx-doc.org link mistaken by github as a relative link

---

qiskit/tools/qcvv/tomography.py

I think the projector in the documentation in line 88 was mislabeled with a Z instead of X.

Z -> X in name of projector in line 88

---

qiskit/__init__.py
qiskit/backends/_qiskit_cpp_simulator.py
setup.py
src/cpp-simulator/src/Makefile

* Bumped version to: 0.4.5
New Cpp Simulator can't be build automatically from the repo, but we are working on it. 
In the meantime, I did a Windows build by myself and distributed to some contributors who needed it.
With these changes, they can put the executable and all DLL dependencies in `C:\Users\<user>\Anaconda3\Lib\site-packages\qiskit\backends\` and the SDK will recognize it and be able to execute it.
make test passed all tests.
I did a simple Qiskit example program that uses the 'local_qiskit_simulator' on Windows, and it worked.

* Added support for Windows cpp simulator

---

README.md
doc/example_real_backend.rst
doc/install.rst
doc/ja/example_real_backend.rst
doc/ja/quickstart.rst
doc/quickstart.rst

Remove the "linenos" sphinx directive, in order to allow some code blocks (in particular the examples) when browsing the .rst files from the GitHub interface. Point the documentation link on the README to the landing page docs.
Thanks to David Bowen for pointing it out.

Fix display of code-blocks on .rst pages

---

cmake/defaults.cmake
cmake/python-build.cmake
setup.py.in
src/qiskit-simulator/CMakeLists.txt

* The command: pyhton setup.py bdist_wheel/sdist, now copies the
executables to qiskit/backends/, so platforms without wheels
package support have a chance to run the c++ simulator
* Improved some in-file CMake documentation
Tested manually, as we don't have automated tests for these procedures.
These changes don't affect the code, they are related to the build system.

Fix static linking of the C++ Simulator

---

qiskit/tools/qi/qi.py
test/python/test_qi.py
test/python/test_tomography.py

Change the definition of `state_fidelity` to be consistent with IBM quantum group research papers. #278 
The new definition is that:
- Pure states: F(|a>, |b>) = |<a|b>|^2.
- Mixed states: F(rho1, rho2) = Tr[sqrt(sqrt(rho1).rho2.sqrt(rho1))] ^ 2

updated state_fidelity convention

---

test/python/test_quantumprogram.py

The test `test.python.test_quantumprogram.test_simulator_online_size` generates a warning from `IBMQuantumExperience`. It can be cleaned (and checked) with `assertLog`.
I recently learnt about `assertLog`. It allows to clean the output of the tests and, on top of that, make sure that is generated and with the "right" message.
`make test`

test_simulator_online_size with assertLog

---

qiskit/dagcircuit/_dagcircuit.py
qiskit/mapper/_mapping.py

The parser creates symbolic objects from the parameters. However, when the dag was created, they used to be saved as strings for avoiding incompatibilities issues. This created a situation that, when the dag parameters need to be used, they are sympified. You can imagine, tons of overhead. This PR fixes this. We have better tests than we used to have in the past. The improvement in the mapper performance is noticeable.
`make test`

Sympy in dag

---

setup.py.in

Fix a problem that prevented the installation of the package to succeed
if there was a problem when building the simulator during
`QiskitSimulatorBuild`. The `try`...`except` block could fail leaving
the current working directory modified, as seen in #292: now it is
more robust and ensures the change is undone in case of any failure.

Fix installation issue with simulator compilation

---

.travis.yml
CMakeLists.txt
CONTRIBUTING.rst
cmake/code-qa.cmake
cmake/defaults.cmake
cmake/tests.cmake
doc/dev_introduction.rst
requirements-dev.txt
requirements.txt
setup.py.in
test/python/common.py
test/python/test_job_processor.py
test/python/test_quantumprogram.py
test/python/test_visualization.py
tools/ghpages_documentation_deploy.sh

* Revise the travis configuration for using `cmake` for the several
targets, and use "stages" instead of parallel jobs:
* define three stages that are executed if the previous one suceeds:
1. "linter and pure python test": executes the linter and a test
without compiling the binaries, with the idea of providing quick
feedback for PRs.
2. "test": launch the test, including the compilation of binaries,
under GNU/Linux Python 3.6 and 3.6; and osx Python 3.6.
3. "deploy doc and pypi": for the stable branch, deploy the docs
to the landing page, and when using a specific commit message,
build the GNU/Linux and osx wheels, uploading them to test.pypi.
* use yaml anchors and definitions to avoid repeating code (and
working around travis limitations).
* Modify the `cmake``configuration to …

Revise travis configuration (cmake+stages+deploy)

---

requirements.txt
setup.py.in

Bump the required version of `IBMQuantumExperience` version to `1.8.28`, as it
includes a fix for the latest errors with hpc and ibmqx2 backends.
This needs to be included in the next stable release - in the meantime, please use `pip install -U qiskit` to automatically update the dependencies to their latest versions.

Bump IBMQuantumExperience dependency version

---

qiskit/tools/visualization.py
setup.py.in

The circuit drawing had a couple of bugs which are fixed here.
@atilag after the merge, can you please bump the release to 4.11 so that this can be used in the tutorials?
`u1`,`u2`,`u3` were just drawn as U, even if the basis kept u1,u2,u3.
`measure` was doing a NOT instead of copy onto the cbit, in contrast to the quantum experience convention.
`swap` was not working at all.
some standard library gates were missing, such as `ch`, `crz`, etc. 
Now all gates are drawn.

Fixed circuit drawing

---

qiskit/qasm/__init__.py
qiskit/unroll/_dagbackend.py

Some very minor docstring improvements that I had sitting around.
* Added reference to unroll package from qasm.
* Added code example to DAGBackend.
The usage of the qasm package is not obvious from the docstrings.
I ran `make doc` and checked the docs.

Clarified usage of qasm package in docstrings.

---

qiskit/__init__.py

Check Python version in __init__ as done by NumPy and SciPy for equivalent checks.
Do Python version check at import, as opposed to a manual assert (as done in the tutorials).
Having a manual assert in the tutorials is silly.  Checks in tutorials can be removed after commit.
I ran it.

Do Python version check in init

---

qiskit/_quantumprogram.py
test/python/test_identifiers.py

@ajavadia noticed that the unnamed registers look ugly when `plot_circuit` is called:
He convinced me that `infix` can be used as identifier when it is available. The result looks nicer:

nicer default names for unnamed registers

---

qiskit/_quantumprogram.py
qiskit/extensions/standard/barrier.py
qiskit/mapper/_coupling.py
qiskit/mapper/_mapping.py
test/python/test_mapper.py
test/python/test_quantumprogram.py

The issue described in #342 is fixed (mapper bug alters already conforming circuits, and inserts operation after measurement).
This PR also resolves several other bug reports about mapper behavior:
- https://github.com/QISKit/qiskit-tutorial/issues/102
- https://github.com/QISKit/qiskit-tutorial/issues/88
- https://quantumexperience.ng.bluemix.net/qx/community/question?questionId=caf79b2243698650d38bf27321ac5991
- https://quantumexperience.ng.bluemix.net/qx/community/question?questionId=fd6d4e1c2e4a45963b4a93a87ad840dd
The default layout, if none is provided, is a layout of circuit qubit _i_ to device qubit _i_. This is reasonable since many users will hand optimize circuits and create already-conforming gates, or would like to map qubits to exact same qubits on the device.
If compilation …

Fix mapper issue #342

---

qiskit/_util.py
requirements.txt
setup.py.in
test/python/common.py

* Bump `IBMQuantumExperience` dependency to 1.8.29, as it fixes a bug
and will be required by the next sdk release.
* Fix the `_check_ibmqe_version()`, as after #286 there where cases
where the `requirement.txt` file was not present, resulting in the
wrong warning. Now uses a simple approach: the check is only performed
if installed via pip, assuming in the rest of the cases the user is
responsible for updating the dependencies (ie. `pip install -U`).
* Revise `_AssertNoLogsContext` in order to produce more informative
failure messages.

Bump API version, fix check, _AssertNoLogsContext

---

README.md

The example in README doesn't compile by copy and paste due to line break.
- Python doesn't compile due to line break.
- I've corrected typos and punctuation.
- Improved rendering due to invalid markdown syntax.

Improves markdown formatting and Python compiling issue

---

.travis.yml

Temporarily disable the osx build on Travis, as they are having a
backlog that might take some time to recover:
https://www.traviscistatus.com/incidents/qkqy13yk55q9

Disable travis osx builds temporarily

---

qiskit/_quantumprogram.py
test/python/test_api_ibmq.py

Fix #367 by revising the tests. Additionally, adds an extra check at `QuantumProgram.set_api()` for not passing the parameters to the API if all of them are `None` (as, even if it is to be deprecated soon, it should help avoid confusion). We should have a similar measure in `IBMQuantumExperience` directly - 
@ajavadia or @jaygambetta : can you test the changes manually with your `Qconfig`s? Following up on Ali's comment in the issue, the tests are not performed in travis as we don't have the environment variables for them set.
Fix the `test_api_ibmq.py` tests:
* adjust them to the new style for using the API directly instead of
going through QuantumProgram.
* revise tests that were failing due to assertions no longer valid, and
relaxed the assertions in a couple of cases.
* remove the …

Fix hub tests, add safety against empty hubs

---

test/python/common.py
test/python/test_identifiers.py
test/python/test_local_qiskit_simulator.py
test/python/test_mapper.py
test/python/test_projectq_cpp_simulator.py
test/python/test_qasm_python_simulator.py
test/python/test_quantumprogram.py

- Added a `assertDictAlmostEqual` function to `QiskitTestCase` for assessing if two numerical dictionaries are approximately equal. Function was based on `assertAlmostEqual` function from unittest.TestCase`.
- Updated tests which relied on a fixed seed when comparing the outcome of circuits with random measurement outcomes to use this function so that the tests shouldn't fail if any changes are made to RNG implementation.
Tests that compare a counts dictionary which includes measurement sampling error to a target using a fixed seed are not portable to different test systems. This PR allows for approximate comparison of two counts dictionaries within an allowed threshold to account for sampling statistics.
Updated tests to use new function, all current tests pass.

Updated tests that compare random counts outcomes

---

README.md
doc/ko/README.md
doc/zh/README.md
qiskit/_quantumprogram.py

* Copy the example and the authors sections on the main README.md to the translations, to synchronize them with the latest changes by #357 and  #359.
* Revise some docstrings that were raising some warnings during the generation of the sphinx docs. There are still some warnings left at `qiskit/backends/_qiskit_cpp_simulator.py`, but they have been left untouched as they might cause some conflicts with #351 (another pass will be done after that PR is merged).
Improve documentation consistency.
`make doc`

Sync example and authors for translated README, docstrings

---

test/python/test_mapper.py

Seems like one test case was missed in #380 when we updated tests to allow tolerance intervals instead of exact comparisons.
This PR covers that.

use assertDictAlmostEqual in test_mapper

---

qiskit/_quantumcircuit.py
test/python/test_quantumprogram.py

This patch modifies the `QuantumCircuit.combine` and `QuantumCircuit.extend` functions (and hence `+`, and `+=` operators) to allow combing circuits with common and/or distinct quantum and classical registers.
```python
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit
qr1 = QuantumRegister('q1', 2)
cr1 = ClassicalRegister('c1', 2)
qr2 = QuantumRegister('q2', 2)
cr2 = ClassicalRegister('c2', 2)
qc1 = QuantumCircuit(qr1, cr1)
qc1.h(qr1)
qc2 = QuantumCircuit(qr2, cr2)
qc2.x(qr2)
circ = qc1 + qc2
circ.cx(qr1, qr2)
circ.measure(qr1, cr1)
circ.measure(qr2, cr2)
```
In this case the resulting qasm equivalents will be
```
OPENQASM 2.0;
include "qelib1.inc";
qreg q1[2];
creg c1[2];
h q1[0];
h q1[1];
OPENQASM 2.0;
include "qelib1.inc";
qreg q2[2];
creg c2[2];
x q2[0];
x q2[1]; …
```

Allow combining circuits with different unique registers

---

qiskit/_jobprocessor.py

Fixes #391 
Stops `JobProcessor` from modifying input qobj to `QuantumProgram.run`.
See issue #391 
All tests pass

Stop JobProcessor from modifying input qobj

---

qiskit/_compiler.py
qiskit/_jobprocessor.py
qiskit/_quantumjob.py
qiskit/_quantumprogram.py
qiskit/_result.py
qiskit/backends/ibmq/ibmqbackend.py
test/performance/vqe.py
test/python/qobj/cpp_conditionals.json
test/python/qobj/cpp_measure_opt.json
test/python/qobj/cpp_reset.json
test/python/qobj/cpp_save_load.json
test/python/qobj/cpp_single_qubit_gates.json
test/python/qobj/cpp_two_qubit_gates.json
test/python/test_compiler.py
test/python/test_job_processor.py
test/python/test_local_qasm_simulator_cpp.py
test/python/test_projectq_cpp_simulator.py
test/python/test_qasm_python_simulator.py
test/python/test_qasm_sympy_simulator.py
test/python/test_unitary_python_simulator.py
test/python/test_unitary_sympy_simulator.py

I realized that the previous PR merge broke our c++ simulator and Project Q simulators. It was because our c++ simulator tests were flawed (they were actually using the Python backend!), and the ProjectQ simulator was not installed on Travis.
The problem was with the Qobj dictionary created. The value for the`backend` field was a `Backend` instance, but this is not valid JSON and those simulators that expect and decode JSON will throw errors. I made this point to the backend string, but included a copy of the instance in the QuantumJob wrapper. Going forward, this will be part of the Qobj object.

Serializable Qobj + Pass cpp/projectq simulator tests

---

qiskit/_openquantumcompiler.py
qiskit/_quantumprogram.py

Reintroduce the discovery of remote backends during `QuantumProgram.set_api()`, as noted in https://github.com/QISKit/qiskit-tutorial/issues/136, as it seems it has been removed inadvertently, and without it the user would need to manually call `available_backends()` to populate the list before being able to use a remote backend.

Reintroduce remote discovery during qp.set_api() and openquantumcompiler.dag2json()

---

qiskit/_quantumprogram.py

In PR #347 we introduced an automatic compiler barrier insertion to avoid measurement reordering. The backends do not handle redundant barriers well, however, and some experiments were throwing errors. This is a temporary fix of the issue, until we:
1- fix barriers in the backends
2- use the dag information to insert barriers once and once only

remove extra barriers temporarily from compile

---

qiskit/_compiler.py
qiskit/_openquantumcompiler.py
test/python/test_quantumprogram.py

So we have to fix some stuff on `stable` to release a new version, we couldn't make it through `master` because it has strongly changed these days, so we pushed against `stable` and released a new pypi package version (0.4.13).
Now we are merging back these changes into `master`.
Some of these changes don't apply to `master` so I cherry-picked the significant ones and made some changes to adapt them.
@ajavadia Your changes were introduced in the old `QuantumProgram.compile()` method, that has strongly changed in current `master`. I guess that we need to fix this in our `_compiler.compile()` , right?

Resyncing master stable

---

qiskit/dagcircuit/_dagcircuit.py
qiskit/mapper/_mapping.py

* DAGCircuit.layers changed to yield a generator
* DAGCircuit.serial_layers changed to yield a generator
* Mapper has been adjust to consume generators instead of lists for
layers
The layers function in DAGCircuit was eager, producing a full list of layers on its call. This is not necessary. It has been changed to lazily emit values instead.
Where a result was appended to the output list now instead a value is emitted through `yield` resulting in a generator.
For writing my own mapper I would like to request the first layer of the DAGCircuit, but calling `layers()` constructs the complete list. This wastes resources and is actually blocking for large DAGCircuits (think 10s of thousands of instructions).
I ran `make test` with `SKIP_ONLINE_TESTS=1` and passed all tests. I found all usages …

DAGCircuit layer functions yield generators

---

requirements-dev.txt

Running `make pypi_package` fails with `error: invalid command 'bdist_wheel'` if the `wheel` package is not installed.

Adding `wheel` package to dev dependencies.

---

test/python/_dummybackend.py

The test suite on the master branch is currently failing, due to a small issue with filtering.
The failing test is `test_reordering`, and the underlying cause is that `available_backends({'simulator': False})` is returning `ibmqx2, ibmqx4, ibmqx5, local_dummy_simulator`. Clearly, the last one should not be there, since it is a simulator. The reason it shows up is that `filter` is not implemented for the dummy provider. This PR addresses that.
(The above test does not fail when run individually. Only when run with other tests, the local_dummy_backend persists in the `wrapper.available_backends()`).
This is a temporary fix until #410 properly addresses the filtering mechanism.

dummy provider filter

---

qiskit/_quantumprogram.py
qiskit/backends/local/qasm_simulator_cpp.py
test/python/qobj/cpp_conditionals.json
test/python/qobj/cpp_measure_opt_flag.json
test/python/qobj/cpp_reset.json
test/python/qobj/cpp_save_load.json
test/python/qobj/cpp_single_qubit_gates.json
test/python/qobj/cpp_two_qubit_gates.json
test/python/test_qasm_simulator_py.py

1. Updates tests and  fixes #441, by ensuring tests do not output a lot of DeprecationWarnings
2. Updates the DeprecationWarning messages in quantumprogram.py to the latest SDK usage convention.

Fix deprecation warnings

---

test/python/test_ibmqjob.py
test/python/test_localjob.py
test/python/test_reordering.py

* Fix `test_cancel()` issue, as in some environments the Jobs might have
been to fast and not be able to be cancelled, causing the test to fail.
Fix `test_run_async()`, waiting for the jobs to finish and checking for
the results, as a similar situation might apply (the jobs being run
too fast and being completed by the time the assertion was reached,
which was only checking for `RUNNING`).
* Adjust tests to avoid unavailable backends (such as "ibmqx2") be used
during the tests by making sure that the device picked up by the tests
is `available`.

Fix test_localjob.py and slowtests

---

CMakeLists.txt
qiskit/__init__.py

* No code changes this time. There was problem with the MacOS Wheel
package. We cannot overwrite a Wheel package on PyPi without
bumping up software version number.

pip release: 0.5.1

---

requirements-dev.txt

Temporarily pin the `pylint` dependency to 1.8, as 1.9 was released
recently and is raising an error when using the `docparams` extension:
https://travis-ci.org/QISKit/qiskit-sdk-py/jobs/379390357
Possibly related to https://github.com/PyCQA/pylint/issues/2102

Pin pylint version to 1.8

---

qiskit/_compiler.py
qiskit/_quantumprogram.py
qiskit/backends/ibmq/ibmqbackend.py
qiskit/backends/ibmq/ibmqjob.py
qiskit/backends/ibmq/ibmqprovider.py
qiskit/wrapper/defaultqiskitprovider.py
test/python/test_api_ibmq.py
test/python/test_backends.py
test/python/test_ibmqjob.py
test/python/test_quantumprogram.py
test/python/test_simulator_interfaces.py

* ibmqx_qasm_simulator and ibmqx_hpc_qasm_simulator have been merged
into ibmq_qasm_simulator, so we have to updates tests and code.
* hpc parameter is not enforced anymore, as there are no 'hpc'
specific backends, and the rest of the backends ignore this param
in case someone sends it to them by mistake.

Adapting to new online simulator names.

---

test/performance/state_tomography.py

Fixes #475 
Updates compiler performance test `state_tomography.py` to use `local_statevector_simulator` backend to get the state vector of the prep circuit.

Fix #475 update state_tomography.py to use local_statevector_simulator

---

qiskit/_compiler.py
test/python/test_compiler.py

There was an indexing error in the case when multiple qregs where in a circuit.
Fixes Issue #492.
Tested on original code where error showed up, and added unit test.

Fix mapping error for multiple qregs raised in #492

---

examples/python/load_qasm.py
qiskit/__init__.py
qiskit/_quantumprogram.py
qiskit/wrapper/__init__.py
qiskit/wrapper/_wrapper.py
test/python/test_load_qasm.py

This PR adds a few conveniences to the wrapper:
- ability to load a qasm string/file, and get a corresponding QuantumCircuit object. This function existed in QuantumProgram, and here we move further towards deprecating it.
- Passes the default quantum experience url to the _wrapper.register method, to make it easier to register just by your token.

adding `load_qasm` and default `url` to wrapper

---

cmake/defaults.cmake
src/qasm-simulator-cpp/CMakeLists.txt

As the code it was generating was not 100% compatible with all CPUs of the same
architecture. The loss of performance is negligible.
There are reports of CPP simulator not working on certain CPUs.
It works in one of the problematic machines.

Remove -march=native from compiler flags

---

src/qasm-simulator-cpp/src/engines/vector_engine.hpp
test/python/qobj/cpp_measure_opt.json
test/python/test_qasm_simulator_cpp.py

Thanks to Guy Szweigman and Mohammad Heeb, who noticed that the C++ simulator does not always display correct density matrix and probabilities vector. 
This happens in the presence of an optimization, which applies to no-noise circuits where all measurements are located at the end. The optimization replaces the shots by a single shot + sampling. However in the calculation of the density matrix and probabilities vector there is a normalization by the number of shots. This results in a density matrix whose trace is 1/(number of shots), and a probabilities vector whose sum is 1/(number of shots).
I fixed the number of shots when the optimization is applied.
Independently of this pull request, it should be revised whether it is correct to normalize by total_shots. Looks like there is an …

Bug fix in the C++ simulator: density matrix and probabilities are sometimes erroneous

---

.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/ENHANCEMENT_REQUEST.md
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md

Update issue templates. Following the #473.

Update issue templates

---

.github/CONTRIBUTING.rst
.travis.yml
README.md
doc/index.rst
doc/install.rst
doc/ja/install.rst
doc/ja/qiskit.rst
doc/ko/README.md
doc/qiskit.rst
doc/zh/README.md
qiskit/backends/local/qasm_simulator_cpp.py
qiskit/backends/local/qasm_simulator_py.py
qiskit/backends/local/statevector_simulator_cpp.py
qiskit/backends/local/statevector_simulator_py.py
qiskit/backends/local/statevector_simulator_sympy.py
qiskit/backends/local/unitary_simulator_py.py
qiskit/backends/local/unitary_simulator_sympy.py
setup.py.in
src/qasm-simulator-cpp/README.md
src/qasm-simulator-cpp/build_dependencies.sh
test/python/_dummybackend.py
test/python/qasm/math_domain_error.qasm
test/python/qasm/overoptimization.qasm
test/python/test_mapper.py
test/python/test_quantumprogram.py

Rename all references to `qiskit-sdk-py` to the new repository name,
`QISKit/qiskit-core`, including a handful of instances where the
`IBM/qiskit-sdk-py` form was used.
Fixes #467

Rename repository to 'qiskit-core'

---

qiskit/tools/visualization.py

The filename of the generated `.png` file is specified only relative and not found under windows.

fix issue with filename location on windows

---

.github/ISSUE_TEMPLATE.md
.github/ISSUE_TEMPLATE/BUG_REPORT.md
.github/ISSUE_TEMPLATE/ENHANCEMENT_REQUEST.md
.github/ISSUE_TEMPLATE/FEATURE_REQUEST.md
.github/PULL_REQUEST_TEMPLATE.md

Update pull request and issue templates. Following the #473.

Update pull request and issue templates

---

qiskit/tools/visualization.py

PR #543 fixed an issue with filenames on Windows by adding absolute paths. But it broke circuit_drawer functionality on Mac/Linux. This PR fixes that. The absolute paths are still preserved.
The underlying issue was that when doing conversion from `pdf` to `png`, the output file location was not explicitly set. This is now explicit, avoiding inconsistencies between platforms.

fix circuit_drawer for linux/mac

---

CHANGELOG.rst
qiskit/_compiler.py
qiskit/_gate.py
qiskit/_instruction.py
qiskit/_quantumprogram.py
qiskit/wrapper/_wrapper.py
test/python/test_skip_transpiler.py

When a circuit already satisfies the coupling_map on the backend, the swap_mapper should not insert any swaps. This means passing an `initial_layout` of `q[i]->q[i]`.
PR #478 optimizes the initial layout, but that creates unexpected behavior when the coupling map is already satisfied. Here, I only apply the optimization of #478 if swaps are indeed needed.
The other thing that this PR does is a slight name change: `skip_translation` -> `skip_transpiler`, to get ready for the transpiler PR.
Issue was raised here:
https://quantumexperience.ng.bluemix.net/qx/community/question?questionId=5b0d17f943fb6e0038a623bf

Preserve i->i initial layout when coupling_map satisfied

---

doc/example_real_backend.rst

The variable `job` in the statement `job.result()` has not been declared previously. 
Fixed changing `job` variable to `job_exp` as required in the issue #570 
-

Fixing undefined variable in docs related to getting results from real chips (backends)

---

qiskit/_compiler.py

in pr #562 a basis string constant was defined which seems like could be avoided.

remove defining basis in compile.

---

CHANGELOG.rst
qiskit/extensions/quantum_initializer/_initializer.py

Fixes a bug in the arbitrary-state initializer gate that affected its inversion.
Fixes #572.
Fixes #507.
`InitializeGate` inherits from `CompositeGate`, which has an `inverse_flag` property to signal that it has been inverted (this property is useful, for instance, in reapplying the gate to some circuit).
Our initialize gate has been implemented based on https://arxiv.org/abs/quant-ph/0406176v5. The implementation details are that it begins from the desired state, and evolves it to the zero state. The final initializer gate is thus the inverse of this process. 
This means that a call to `inverse()` is made during the implementation, which inadvertently sets the `inverse_flag` property of the gate. Here, we unset this flag.
This PR also undoes the change made in #534. That change had fixed …

Fix initializer gate inversion

---

qiskit/backends/ibmq/ibmqbackend.py

Fix the handling of calibration parameters during
`IBMQBackend.parameters()` in order to have the same behaviour both
in QX and in client.

Fix calibration parameters parsing

---

qiskit/backends/ibmq/ibmqjob.py
test/python/_mockutils.py
test/python/test_ibmqjob_states.py
test/python/test_quantumprogram.py

The test suite does not require a network connection. It fakes the QJOB object and the API behaviour.
This commit partially refactors the `IBMQJob#status()` method to avoid raising exceptions while reading a property.
Current tests behave as integration tests so, in case of failure, it is not guaranteed the problem arises from IBMJob-related abstractions malfunctioning.

Adding test suite for testing IBMQJob in isolation.

---

qiskit/dagcircuit/_dagcircuit.py
qiskit/mapper/_mapping.py
test/python/test_dagcircuit.py

The get_named_nodes of DAGCircuit was unnecessarily sorting the graph nodes in topological order.
I have removed the sorting and replaced it with a list generator.
I noticed that a decent amount of time was spent in the get_named_nodes function and noticed that it was sorting the multi_graph for no apparent reason. That's why I rewrote it.
I added a simple test case and tested all offline tests locally.

Get named nodes removed unnecessary sorting

---

CHANGELOG.rst
qiskit/_quantumprogram.py
qiskit/_util.py
qiskit/backends/basebackend.py
qiskit/backends/ibmq/ibmqbackend.py
qiskit/wrapper/_wrapper.py
qiskit/wrapper/defaultqiskitprovider.py
test/python/test_backends.py
test/python/test_filter_backends.py
test/python/test_ibmqjob.py
test/python/test_quantumprogram.py

Replace the backend status key `available` with `operational` at the
SDK level. A temporarily (and hacky) subclass of `UserDict` is used
for showing the users a `DeprecationWarning` when accessing the old key.
Fixes #599 (albeit via a workaround).

Replace backend "available" with "operational"

---

.travis.yml

Fix the travis python version to 3.6.5 using `pyenv`, as the current
runs use Python 3.7 which seems to cause some issues in some of the
dependencies.
The latest travis osx runs (since ~yesterday) are picking Python 3.7, which seem to be a source of issues.

Use fixed Python version on travis osx

---

CHANGELOG.rst
CONTRIBUTORS.md
qiskit/mapper/_mapping.py
qiskit/mapper/_quaternion.py
test/python/test_mapper.py
test/python/test_quaternions.py

This fixes the errors in the `qiskit.mapper._mapping.yzy_to_zyz` Euler angle mapping by switching to quaternions.  
The previous routine was failing for several instances.  I believe the code itself had some math errors that made the transformations invalid rather than we were running into issues with the use of Euler angles themselves.  Regardless, this is an implementation that computes the `yzy` rotation using quaternions, and returns the `zyz` from the generated rotation matrix.  The routine checks the validity of the transformation by computing the quaternions in both `yzy` and `zyz` and checks to see if the abs inner product is close to one.  Additional sanity tests are also implemented.
The failed examples in #607 now generate results.
Fixes #520, Fixes #607.

Use quaternions in yzy to zyz transformation

---

test/python/test_quantumprogram.py

`test/python/test_quantumprogram.py::TestQuantumProgram::test_load` was silently broken yesterday, as Sympy 1.2 was released and it seems the length of the QASM was changed as a result. This PR workarounds the expected length, in the hopes of evaluating more carefully the compatibility as a whole in the future.

Fix test failing for sympy 1.2

---

CHANGELOG.rst
qiskit/backends/ibmq/ibmqjob.py
requirements.txt
setup.py.in
test/python/test_ibmqjob_states.py

Use the recently included `api.get_status_job()` for checking the
status of an online job, as it is more performant than the existing
`api.get_job()`. Bump IBMQuantumExperience dependency.

Use get_status_job() in IBMQJob, bump 1.9.8

---

.travis.yml
qiskit/backends/ibmq/ibmqjob.py
qiskit/backends/jobstatus.py
test/python/test_ibmqjob_states.py

In order to avoid wasting bandwidth, IBM QE now provides a `get_status_job()` method. Only if the status is final, the `IBMQJob` instance will query for more info. Checking whether a state was final or not was incorrectly implemented.
Fortunately, the current implementation does not retrieve any additional data aside from the status (double check if this is an error).
The patch also adds a test to ensure that final states do indeed perform a query for getting the details (although we should check if this is something needed for `ERROR_*` status).

Fixes final states for `get_status_job()` support

---

appveyor.yml

Fix #643 
Removes Miniconda and uses `venv` directly as virtual environment.

Adding Python 3.7 to appveyor matrix.

---

test/python/test_quantumprogram.py

While working on #234, I'm setting the `QE_URL` to things like `http://127.0.0.1:5000/<test_name>/api`. The test `test.python.test_quantumprogram.TestQuantumProgram.test_config_scripts_file` checks a regexp that is a bit too restrictive in this new setting. This PR is a bit more generic and works in both cases.

A more generic re expression

---

qiskit/backends/ibmq/ibmqbackend.py
qiskit/backends/ibmq/ibmqprovider.py
qiskit/transpiler/_transpiler.py
test/python/test_quantumprogram.py

This is a temporary hack to show updated device display names when inquiring `backend.status`, until such names are updated in the API itself.
*Motivation*: we want to remove `ibmqx2`, `ibmqx4` and `ibmqx5` in favor of new, more descriptive names.
A previous PR (#566 ) created aliases that allowed the wrapper to work with both old names and new names (e.g. when calling `execute()`).

update device display names in `backend.status`

---

qiskit/wrapper/defaultqiskitprovider.py
test/python/test_wrapper.py

An exception is too strict here, and can cause some issues when working in a notebook env.  Here, a warning is generated instead.

Make double registration a warning not exception

---

CHANGELOG.rst
qiskit/backends/local/qasm_simulator_py.py
qiskit/backends/local/statevector_simulator_cpp.py
qiskit/backends/local/statevector_simulator_py.py
qiskit/qobj/_converter.py
qiskit/qobj/_qobj.py
qiskit/transpiler/_transpiler.py
qiskit/unroll/_jsonbackend.py
test/python/test_qasm_simulator_py.py
test/python/test_qobj.py
test/python/test_unitary_simulator_py.py

Update the Qobj classes and the codebase for adjusting to the 1.0.0
schema:
* 'snapshot' operation name is '#snapshot' in the json
* add `qobj.schema_version` field, defaulting to `1.0.0`
* replace `qobj.register_slots` with `qobj.memory_slots`
* add `memory` attribute to the `measure` instruction.
Update the codebase for accounting for the changes:
* update `qasm_simulator_py` for accepting `#snapshot`
* update the qobj converter to convert `#snapshot` to `snapshot`
* update `JsonBackend` to append the `#` to `snapshot` at that level.

Update Qobj to the 1.0.0 schema

---

qiskit/backends/local/statevector_simulator_cpp.py
qiskit/backends/local/statevector_simulator_py.py
qiskit/qobj/__init__.py
test/python/_mockutils.py
test/python/test_ibmqjob_states.py
test/python/test_localjob.py
test/python/test_qasm_simulator_cpp.py
test/python/test_qobj.py

See #652 
There are two use-cases that seem legit to me:
1. The one for loading from a file.
Although it would make sense to rename it to `from_json`.
2. The one for loading from the result of the `Unroller#execute()`.
Although I think that the method should return a `QobjExperiment` instance.
@diego-plan9 what do you think?

Removing unnecessary uses of `from_dict` method.

---

CHANGELOG.rst
qiskit/backends/local/qasm_simulator_py.py
qiskit/backends/local/statevector_simulator_cpp.py
qiskit/backends/local/statevector_simulator_py.py
qiskit/qobj/_converter.py
qiskit/qobj/_qobj.py
qiskit/transpiler/_transpiler.py
qiskit/unroll/_jsonbackend.py
test/python/_mockutils.py
test/python/qobj/cpp_conditionals.json
test/python/qobj/cpp_measure_opt.json
test/python/qobj/cpp_measure_opt_flag.json
test/python/qobj/cpp_reset.json
test/python/qobj/cpp_save_load.json
test/python/qobj/cpp_single_qubit_gates.json
test/python/qobj/cpp_two_qubit_gates.json
test/python/test_qasm_simulator_cpp.py
test/python/test_qasm_simulator_py.py
test/python/test_qobj.py
test/python/test_unitary_simulator_py.py

Update the `Qobj` classes and codebase for the new schema changes:
* `qobj.id` -> `qobj.qobj_id`
* `#snapshot` -> `snapshot`
Include changes in the Qobj classes, simulators, and tests.
Following #703

Update Qobj to the latest schema changes

---

qiskit/extensions/quantum_initializer/_initializer.py

`qiskit.extensions._quantum_initializer._initializer` had a depreciation warning from the use of `np.matrix`.  Here, I replaced the code with a cleaner implementation using only `np.array`.

Fix depreciation warning from use of np.matrix

---

CHANGELOG.rst
requirements.txt
test/python/common.py
test/python/test_ibmqjob.py
test/python/test_ibmqjob_states.py
test/python/test_simulator_interfaces.py

Fix #687
Uses `ibmqx4` to test the jobs can be cancelled.

Testing non commercial backends accepts cancellation.

---

qiskit/transpiler/_transpiler.py
test/python/test_quantumprogram.py

Add `qobj.config.n_qubits` and `qobj.experiment.config.n_qubits`
during `transpile()`. This field is not part of the `qobj_schema`, but
needed for the online simulator at the moment.

Add `n_qubits` to qobj.config and qobj.exp.config

---

qiskit/backends/ibmq/ibmqbackend.py
qiskit/backends/ibmq/ibmqjob.py
test/python/test_ibmqjob_states.py
test/python/test_quantumprogram.py

Fix #780
One related to the simplification of the Job API. It is now raising JobTimeoutError instead of TimeoutError and we forgot to update a reference. It also evidentiates an inconsistency in the way we treat exceptions.
The other was related to a new update in the IBMQuantumExperience library. Now some server errors raise an ApiError that was not captured before.

Tests revealed a couple of bugs in the codebase.

---

CHANGELOG.rst
qiskit/tools/visualization/_circuit_visualization.py

Fix #767
This commit adds a new kwarg parameter to the latex drawer
reverse_qubits which gives users an option to reverse the order qubits
are displayed. Currently the bit order increases downward with the q_0
bit being displayed at the top. When the reverse_qubit option is set to
True the order is reversed and q_N is at the top and the order
decreases.
Related to #693

Add option to reverse qubit order in latex drawer

---

qiskit/mapper/_coupling.py
test/python/test_mapper__coupling.py

This commit adds test coverage for the qiskit.mapper.__coupling. During
the testing some unhandled edge cases were found in the module, this
commit also fixes those at the same time.
Fixes #770

Add tests for qiskit.mapper._coupling module

---

test/python/test_quantumprogram.py

Fixes #791 
This PR improves the way that the timeout in `test_simulator_online_size` is checked.
There are two key changes in this PR. The first one is adding `timeout=float_info.min` as an argument of `q_program.execute`. This will warranty that a timeout is triggered. The second change is the simplification of the program since there is no need to send a big program to trigger the timeout.
The checking time is reduced from:
```
test_simulator_online_size (test.python.test_quantumprogram.TestQuantumProgram)
Test test_simulator_online_size. ... ok
----------------------------------------------------------------------
Ran 1 test in 60.914s
```
to
```
test_simulator_online_size (test.python.test_quantumprogram.TestQuantumProgram)
Test test_simulator_online_size. ... ok …
```

Remove the test `test_simulator_online_size`

---

doc/dev_introduction.rst

Fixes #796 . Now the table looks like this:

fix for the table

---

test/python/_test_options.py

Fixes #798 
Checks if the flag is empty before raising an error about it. Not setting any option should not be considered an error.

checks if flag is not empty before erroring

---

qiskit/schemas/backend_configuration_schema.json
qiskit/schemas/examples/backend_configuration_openpulse_example.json

I believe the vars and osc definitions were accidentally added to the example.
Fix #787. Moved schema definition from example to the schema. Updated example with empty `vars` and `osc` field.

Updated  property Backend Configuration schema and example to reflect spec.

---

qiskit/tools/qcvv/tomography.py
test/python/test_tomography.py

Removes dependency on QuantumProgram from the tomography module.
Removed depreciated interface wrapper from qiskit 0.3.
The function `create_tomography_circuits` now takes as input a quantum circuit object instead of a quantum program and a circuit name string: 
`create_tomography_circuits(qp, name, ...)` ---> `create_tomography_circuits(circuit, ...)`
`build_wigner_circuits(qp, name, ...)` ---> `build_wigner_circuits(circuit, ...)`
It returns a list of quantum circuit objects that may be executed, rather than needing to extract the circuits from a quantum program.
Tests have been updated to new format and pass.
The tutorials for state tomography, process tomography, and wigner tomography will need updating.
```python
from qiskit import execute, QuantumCircuit, QuantumRegister, …
```

removed quantum program from tomography module

---

CHANGELOG.rst
qiskit/tools/visualization/__init__.py
qiskit/tools/visualization/_counts_visualization.py
qiskit/tools/visualization/_error.py
qiskit/tools/visualization/interactive/_iplot_histogram.py

This commit fixes the inconsistencies between the 2 histogram plot
functions iplot_histogram (for an interactive js plot) and
plot_histogram (for a matplotlib generated plot). Both functions perform
the same function just using different tools. To make them
interchangeable this commit addresses the differences between the 2 and
makes the interface the same between the 2. However, because of
backwards compat concerns with plot_histogram (which has been present in
several releases already) there is a some duplication of number_to_keep
kwarg and the options dict. This deprecates the number_to_keep parameter
so users can migrate off of it and then we can remove it from both
plot_histogram and iplot_histogram.
With the interfaces to both functions being the same this commit also
updates the …

Conform iplot_histogram and plot_histogram

---

qiskit/__init__.py
qiskit/backends/__init__.py
qiskit/wrapper/defaultqiskitprovider.py
test/python/_test_options.py

See #699.
Changes needed for reintroducing the sympy, projectq and jku backends as addons for 0.6. The implementation is based on the upcoming packaging structure and actually serve as the first tentative step - this PR:
* makes `qiskit.backends` "extensible"
* adds the providers to the `DefaultQISKitProvider` set if they are available (as the assumption is that they are official addons maintained by the Qiskit team)
and will be accompanied by PRs on each backend repositories that rename their modules.
After this PR, the only related change left in this repository will be to add them to the dependency list - this will need to be done probably closer to the release  (as the packages will need to be in pip, a bit of a chicken-and-egg style).

Reintroduce the external addons through namespaces

---

.travis.yml
qiskit/__init__.py
qiskit/tools/visualization/_circuit_visualization.py

From an usability point of view, it should be easier to use the `circuit_drawer` and `plot_histogram` functions.  Especially given that they are used in the very first intro notebook.
This PR makes the `circuit_drawer` and `plot_histogram` functions available at import.

Import commonly used visualizations by default

---

CHANGELOG.rst
qiskit/wrapper/__init__.py
qiskit/wrapper/_wrapper.py
test/python/test_wrapper.py

This commit adds a new function to convert a qobj to a list of quantum
circuit objects. Right now it only works with qobj that have the qasm
embedded in the header. If the qobj input doesn't have the qasm in the
header it will just return None.
Fixes #823

Add function that converts a qobj to QuantumCircuit

---

qiskit/__init__.py

Fix an issue with the addon reintegration at #699  caused during #874, as the expansion is not performed in the right order due to the introduction of an extra code block.
Moving forward, we should really think deeply the need for making functions available in the top-level namespace via imports, as the modularization of `terra` is still not ideal and `qiskit/__init__.py` is central to the project and modifications have a number of non-trivial implications - and we should also keep an eye on the upcoming uber-qiskit reorganization.

Fix main __init__ py instruction order

---

qiskit/__init__.py
qiskit/tools/visualization/_circuit_visualization.py

Fixes #889 
Fixes #889 by changing the imports in `qiskit.tools.visualization._circuit_visualization.py`.  Also moved the import in the `__init__.py`, although this is not strictly necessary once the  correct imports are done.

Fix import of visualization tools

---

qiskit/wrapper/jupyter/jupyter_magics.py

As pointed out by @ajavadia, the Jupyter job status magic could have an undefined variable when using a simulator that reports done before the magic enters its loop.  This fixes that error.

Fix bug in Jupyter status magic

---

CHANGELOG.rst
qiskit/_util.py
qiskit/tools/visualization/__init__.py
requirements.txt

Fix #895
As pointed out by @chriseclectic , loading qiskit with no internet connection results in a `ConnectionError` because the interactive visualizations max out the number of attempts to look for the needed host url.  Here we replace the previous check with on that gracefully exits if no connection can be established.

Properly check if connection can be established for importing interactive visualizations

---

qiskit/__init__.py

Fix #904  
Fixes issue where aqua GUI interface crashes for default OSX matplotlib backend.

Remove top level visualization imports

---

qiskit/backends/local/_simulatortools.py
qiskit/backends/local/unitary_simulator_py.py
test/python/test_unitary_simulator_py.py

Fix #894
This PR changes the local unitary simulator to use the Numpy.einsum function. This removes the need to enlarge single and two qubit gates to full 2^N x 2^N matrices, and greatly speeds up performance for larger circuits.
An example of runtime for a random circuit of 100 gates on my laptop (Macbook pro 3.1 GHz i7, 16 GB Ram):
Timing results for new implementation are:
```
2 qubit circuit, 100 gates, time taken: 0.073 s
3 qubit circuit, 100 gates, time taken: 0.072 s
4 qubit circuit, 100 gates, time taken: 0.071 s
5 qubit circuit, 100 gates, time taken: 0.075 s
6 qubit circuit, 100 gates, time taken: 0.087 s
7 qubit circuit, 100 gates, time taken: 0.08 s
8 qubit circuit, 100 gates, time taken: 0.11 s
9 qubit circuit, 100 gates, time taken: 0.352 s
10 qubit circuit, 100 gates, time …
```

Speedup python local_unitary_simulator by using Numpy.einsum

---

requirements.txt

Fix #920 
New matplotlib 3.0 version breaks backwards compatibility by raising
an ImportError when Python is not installed as a framework in MacOS X.
This PR pins Matplotlib to versions under 3.0 since it is the fastest
way to ensure we are not introducing breaking changes in visualization
tools given the proximity of the new release.

Pinning to matplotlib < 3 to avoid incompatibility issues.

---

CHANGELOG.rst
examples/python/using_qiskit_core_level_1.py
qiskit/__init__.py
qiskit/_register.py
qiskit/_util.py
qiskit/backends/basebackend.py
qiskit/backends/ibmq/ibmqbackend.py
qiskit/backends/local/qasm_simulator_py.py
qiskit/schemas/backend_status_schema.json
qiskit/schemas/examples/backend_status_example.json
qiskit/wrapper/__init__.py
qiskit/wrapper/_wrapper.py
test/python/test_backends.py

Fix #778 
One major inconsistency between the defined spec/schemas and the current qiskit API is the methods `backend.calibration` and `backend.parameters`. The data returned from these should just be combined and returned via `backend.properties`.
The API doesn't have this endpoint yet, so this is a temporary hack in Qiskit to make the API consistent for 0.6 Should fix (along with a bunch of other FIXMEs) when the API finally gets updated.
The PR also does the following cleanups:
- Fixes a bug in the status schema that did not report backend name and version, like other backend calls.
- Fully remove some deprecated stuff (and messages) from `_register.py` and `qasm_simulator_py`

Replace backend.calibration & backend.parameters with backend.properties

---

qiskit/transpiler/__init__.py
qiskit/transpiler/_parallel.py
test/python/test_parallel.py

After moving all the parallel tools to the `transpiler` the env var flag was not being set at init, and therefore using `parallel_map` directly would not use multiple processes.  This fixes that.

Fix setting parallel flag at init

---

qiskit/tools/visualization/_counts_visualization.py

The options `width` and `height` in `plot_histogram` were passed to `figsize` in the wrong order.  This fixes that.

Fix reversed width and height options in plot_histogram

---

qiskit/tools/visualization/_circuit_visualization.py

This commit fixes an issue on drawing the barrier centering for all
qubits covered by a barrier when there is a measure after a gate. When
there is a gate followed immediately by a measure in the next column we
need to adjust the horizontal offset for the barrier because the box for
a measure is wider. However, prior to this commit we weren't accounting
for the downward span of the barrier being drawn, just the qubit/row
where the \barrier LaTeX call was made. This commit fixes the issue by
searching all the qubits/rows in the column before a measure and looking
for a \barrier. If a barrier is found and it's span covers the qubit/row
with the measure then we adjust the horizontal offset of that \barrier
command.
Fixes #940

Fix barrier centering before measure on all qubits

---

CHANGELOG.rst
qiskit/tools/visualization/_circuit_visualization.py

This commit adds a note about the latex drawer supporting barriers now,
it also highlights that you need to have the latest version of the latex
qcircuit package installed to use it.
Related to #934

Add latex barrier drawing to changelog

---

qiskit/tools/visualization/__init__.py
qiskit/tools/visualization/_dag_visualization.py
requirements.txt

Fix #956 
A dag visualizer is important for developing transpiler passes. This PR introduces that. 
This is to be merged into the `transpiler` branch (i.e. not for 0.6). So no CHANGELOG here.
```python
from qiskit import QuantumRegister, ClassicalRegister, QuantumCircuit
from qiskit.tools.visualization import circuit_drawer
q = QuantumRegister(3)
c = ClassicalRegister(3)
circ = QuantumCircuit(q, c)
circ.h(q[0])
circ.cx(q[0], q[1])
circ.cx(q[0], q[1])
circ.u1(0.2, q[0])
circ.u2(0.2, 0.4, q[0])
circ.iden(q[0])
circ.ccx(q[0], q[1], q[2])
circuit_drawer(circ)
```
```python
from qiskit.transpiler._transpiler import _circuits_2_dags
from qiskit.tools.visualization import dag_drawer
dag = _circuits_2_dags([circ])[0]
dag_drawer(dag)
```
This adds a new dependency (`nxpd` package). This is simply …

Add dag_drawer() visualizer

---

qiskit/backends/ibmq/credentials/_configrc.py
qiskit/backends/ibmq/ibmqprovider.py
test/python/test_registration.py

This commit adds a function to remove all accounts from the ibmqprovider
and optionally the qiskitrc. Previously there was only a function to
remove a single which got a bit tedious if you wanted to flush
everything. This fixes that by giving a single point to delete all
accounts.
Fixes #958

Add remove_all_accounts() function to the ibmqprovider

---

qiskit/backends/ibmq/ibmqjob.py

There was a depreciation warning when grabbing results from a ibmq job.  This fixes that.

Fix depreciation warning when getting results from ibmqjob

---

CHANGELOG.rst
qiskit/backends/ibmq/ibmqprovider.py

Fix #959 
Fix #961
Example:
`IBMQ.load_accounts()`  # load all saved credentials
`IBMQ.load_accounts(hub=None)`  # load public credentials only
`IBMQ.load_accounts(hub='ibm-q-internal)`   # load private credentials only

add filters to load_accounts

---

qiskit/wrapper/jupyter/jupyter_magics.py

Previously there was a delay of length `interval` in the `qiskit_job_status` magic before it output to screen if the job status was not done.  This fixes that.

Immediately set job magic status value

---

test/python/test_remote_simulator.py

Quick fix for the `master` tests, as it seems that due the high pace of the weekend, they are not passing since #950:
https://travis-ci.org/Qiskit/qiskit-terra/builds/435083330?utm_source=github_status&utm_medium=notification
This changes `test_remote_simulator.py` setup(), as it was instantiating a provider manually with the previous syntax, resulting in a failure - and it was hard to catch as these tests are only run when pushing to master, and require the specific environment variables to access the device.

Fix test_remote_simulator usage of providers

---

qiskit/backends/ibmq/ibmqprovider.py
test/python/test_registration.py
test/python/test_wrapper.py

Emit warning instead of raise exception when trying to add the same account twice (to disk or to session). It will just skip without doing anything (because it's not really an error).
fixes #961

warning instead of error for double loading

---

examples/python/using_qiskit_terra_level_1.py
qiskit/qobj/_converter.py
qiskit/qobj/_qobj.py

The qobj converter was not expanding the types to native python types when doing conversion to old qobj format. This PR fixes that.
The context is that jobs compiled for IBMQ backends resulted in JSON decoding error when being run on Aer `qasm_simulator`.
An immediate consequence is that `example/using_qiskit_level_1.py` can now be run (i.e. compile once run twice).

expand qobj types for previous version too

---

qiskit/tools/qcvv/tomography.py

Silent linter warnings in `qiskit/tools/qcvv/tomography.py` (the real credit is  @1ucian0 's!). Please note that these warnings are actually not shown when running under some configurations, and hint towards depending on the order `pylint` reads and parses the files or a similar issue, which in turn might be a symptom of other issue with the tomography module that should be investigated further.

Fix intermittent linter warning in qcvv.tomography

---

qiskit/dagcircuit/_dagcircuit.py

Use `OrderedDict`s for `DAGCircuit.qregs` and `DAGCircuit.cregs` in
order to ensure that they are traversed always in the same order (which
should be the order of creation).
This is an attempt to fix the problem we have been experiencing in `master` recently, and intermittently in local tests:
```
1: ======================================================================
1: FAIL: test_online_qasm_simulator_two_registers (python.ibmq.test_ibmq_qasm_simulator.TestIbmqQasmSimulator)
1: Test online_qasm_simulator_two_registers.
1: ----------------------------------------------------------------------
1: Traceback (most recent call last):
1:   File "/home/travis/build/Qiskit/qiskit-terra/test/python/common.py", line 373, in _wrapper
1:     return decorated_func(self, *args, **kwargs)
1:   File …
```

Guarantee order of registers in DAGCircuit

---

CHANGELOG.rst
README.md
doc/install.rst
doc/releases.rst
examples/python/ghz.py
examples/python/hello_quantum.py
examples/python/qft.py
examples/python/using_qiskit_terra_level_0.py
examples/python/using_qiskit_terra_level_1.py
examples/python/using_qiskit_terra_level_2.py
qiskit/backends/ibmq/ibmqprovider.py
qiskit/wrapper/_wrapper.py
test/python/aer/test_simulator_interfaces.py
test/python/ibmq/test_ibmq_qasm_simulator.py
test/python/ibmq/test_ibmq_qobj.py
test/python/ibmq/test_ibmqjob.py
test/python/ibmq/test_registration.py
test/python/test_backend_name_resolution.py
test/python/test_backends.py
test/python/test_compiler.py
test/python/test_filter_backends.py
test/python/test_reordering.py
test/python/test_result.py

**PR #1000!**
Fixes #980 
Fixes #1001 
The IBMQ account adminstration has been changed a bit. Here is how it works now.
```python
enable_account(token, url) # add to current session
disable_accounts(**kwargs)  #remove from current session
save_account(token, url) #save to disk
delete_accounts(**kwargs) #delete from disk
load_accounts(**kwargs) #load into session
active_accounts() # list all accounts active in this session
stored_accounts() # list all accounts saved to disk
```
Example usage:
```python
from qiskit import *
import Qconfig
import QconfigCore
IBMQ.delete_accounts()
IBMQ.stored_accounts()
IBMQ.enable_account(Qconfig.APItoken, Qconfig.config['url'])
IBMQ.active_accounts()
IBMQ.backends()
IBMQ.disable_accounts(token=Qconfig.APItoken, url=Qconfig.config['url'])
import Qconfig …
```

rework IBMQ account adminstration

---

test/python/ibmq/test_registration.py

Test is bad proxy info raises proxyerror in the API.  This means we correctly pass the `proxies` dict to the API.  Note that this test takes a while because the API does not check if a connection can be established before trying the max number of times.

Add proxy pass through test

---

qiskit/dagcircuit/_dagcircuit.py
test/python/test_dagcircuit.py

Fix #749 
In my profiling the `DAGCircuit.layers()` function came forward as the main culprit to my runtime, at about 90% of the total run time.  60% of the total time is spent in a the function `_add_wire` which is of course a bit silly considering the trivial thing it does. Turns out that DAGCircuit constructs a full copy of itself besides the gates, which turns out to be very slow. Instead of making a full copy it now returns a shallow copy.
The layers function now constructs a shallow copy of DAGCircuit and modifies it such that it only contains the nodes of the current layer. That being: All input and output nodes disregarding whether they are used or not, and exactly one layer of op_nodes.
On a relatively small circuit containing a 1000 gates my runtime goes from 22 minutes on the …

DAGCircuit layers uses a shallow copy

---

CHANGELOG.rst
qiskit/tools/visualization/_circuit_visualization.py

If there is a barrier right before a ccnot in a circuit it requires a
modified horizontal offset for the barrier because of the spacing
between the elements. This commit fixes this by modifying offset when
drawing a ccnot if there is a barrier on overlapping rows in the
circuit.

Fix horizontal barrier offset before ccnot

---

CHANGELOG.rst
qiskit/tools/visualization/_circuit_visualization.py

As part of the cleanup of the circuit visualization module we really
only need one entrypoint to draw a circuit. So instead of having 5
separate methods that all do the same thing with different mechanisms or
options this commit condenses that all into the single circuit_drawer()
method. 2 new kwarg flags are added to specify the output technique used
and whether we should open the visualization in a new window after
generating it. For backwards compatibility the old public methods still
exist but are deprecated (which emits the proper warning) and can be
removed after we include the warnings in a release and an appropriate
period of time passes.
Fixes #1048
Fixes #1049

Unify circuit drawer methods

---

qiskit/tools/visualization/_circuit_visualization.py

The python backend name was a bit ambigious as to what it was. We only
used this originally because matplotlib was too long. This changes the
backend name to be mpl (the canonical short name for matplotlib) to
better describe what the backend is.
Fixes #1076

Rename python circuit_drawer() backend to mpl

---

CHANGELOG.rst
qiskit/backends/ibmq/ibmqbackend.py
qiskit/backends/ibmq/ibmqjob.py
requirements.txt
setup.py

Fix #1065 
Make use of new functionality in the API (bumped to 2.0.4) in order to fetch only "informational" fields of a job during 
```
backend.jobs()
backend.retrieve_job()
```
which in turn avoids fetching the results until the user explicitly calls
```
job.result()
```
(alleviating the problem of inadvertently deleting them).
Additionally, reduce a bit the number of API calls made by those methods, as in some cases it is no longer needed to call `.status()` internally during instantiation.
@jaygambetta : note  #1065 was initially asking for a new method - with this PR the fix is a bit different: the user is free to use the list of `Job`s directly and pick from any attribute of them (so in practice, hopefully you have all the metadata needed, and decent guarantees that the jobs will …

Avoid consuming results during `.retrieve_job()` and `.jobs()`

---

qiskit/_quantumcircuit.py

The default circuit name is the circuit prefix with an integer which
increments every time a new circuit is created. However this circuit
count starts at 1 instead of 0 because we were incrementing this before
referencing the value in the circuit object constructor. This commit
fixes the issue by moving this to after we pull the value for the
default name. This will make the default name counts consistent with
standard indexing in python.
Fixes #1078

Start circuit count at zero

---

qiskit/tools/visualization/_circuit_visualization.py

This commit fixes an issue when drawing a circuit using the latex*
output methods and reversebits is enabled. The barriers were not using
the reversed bit order so it was drawing on the LSB instead of the MSB
(or vice versa) as the start of the barrier when reversed. This meant we
were incorrectly starting to draw the downward span at the bottom instead
of the top. To fix this we just reverse the bit order if reversebits is
set before we start drawing the barrier.
Fixes #1099

Respect reversed bit order for drawing barriers in latex

---

CHANGELOG.rst
qiskit/tools/visualization/_dag_visualization.py

The dag visualizations require that graphviz be installed to function
because they leverage pydot via nxpd. However this was not documented or
noted in the docstring or release notes. This commit updates those
accordingly to document this.
Fixes #1093

Add documentation for graphviz external requirement

---

qiskit/tools/visualization/_circuit_visualization.py
qiskit/tools/visualization/_qcstyle.py

This commit adds support to the latex circuit drawers (output 'latex'
and 'latex_source') for respecting the plotbarrier style config setting.
However, to maintain backwards compatibility for the latex drawer the
default style has to change from false to true.
Partially addresses #1099

Respect plotbarrier style setting for latex circuit drawers

---

qiskit/backends/aer/statevector_simulator.py
qiskit/backends/aer/statevector_simulator_py.py
test/python/test_result.py

This commit fixes an issue when using the statevector simulators where
accessing the backend_name attribute of a results object would return a
bound method instead of the actual string for the backend name. This was
caused by the statevector simulators were overloading the backend_name
property of its parent classes with a pointer to the name() method. If
this was necessary it should have overloaded the value and called name()
instead of setting the method as backend_name. However this isn't even
necessary because backend_name is assigned automatically already. So
this commit just removes the unnecessary overloads.
Fixes #1116

Stop overloading backend_name in statevector simluators

---

qiskit/tools/visualization/_circuit_visualization.py

The style input dict for better or worse is our interface to adjust how
the latex and mpl backends draw circuits. However we never actually
included any documentation on the different parameters for the dict.
This commit fixes the oversight and adds documentation explaining in
detail how to use the kwarg, which keys are accepted in the input dict,
and the function of each value.

Add documentation on the style input parameter

---

doc/install.rst

This commit fixes a small issue in the install docs pointing to the
incorrect location to download the anaconda python distribution. This
corrects the link which was either a typo or has changed since the link
was first added.
Fixes #1123

Fix incorrect conda download link in install docs

---

src/qasm-simulator-cpp/README.md

This commit fixes a small typo in the readme for the cpp qasm simulator.
The doc refers to the 'depends' make target. However the actual target
name is 'depend' (no 's').
Fixes #1122

Fix a small typo in cpp qasm simulator README

---

qiskit/backends/aer/statevector_simulator.py
qiskit/backends/aer/statevector_simulator_py.py

Partial fix for #1112 
This PR follows [the hack introduced in #807](https://github.com/Qiskit/qiskit-terra/blob/02200d2cdbbc5057062c35f9002463db7795cdf0/qiskit/unroll/_dagunroller.py#L198) to make snapshot instructions pass the schema. 
Here I add the same hack to 2 other places where snapshots are used.
This will make the bug in #1112 go away, but the problem is deeper, having to do with the relationship between statevector_simulator and qasm_simulator in general, and removing places where qobj is hacked. I will thus keep that issue open.

fix snapshot insertion so qobj doesnt break when running statevector sim

---

CHANGELOG.rst
qiskit/tools/visualization/_circuit_visualization.py

This commit deprecates the basis argument to the circuit_drawer()
function. This has always been out of scope for a tool to just visualize
the circuit, if you need to adjust the basis gates used to construct the
circuit that should be done outside the visualization layer. But, with
the discussion of removing the dependence on calling transpile() from
the circuit_drawer (see #1129) this becomes the first step to some
larger cleanups.

Deprecate basis kwarg on circuit_drawer() function

---

qiskit/_quantumcircuit.py
qiskit/unrollers/_circuitbackend.py
qiskit/wrapper/_wrapper.py
test/python/test_circuit.py

This commit adds 2 new static methods to the QuantumCircuit class to
enable constructing a QuantumCircuit from a QASM string or file. This
gives users to option of building a QuantumCircuit object with a qasm
file simply by calling:
circuit = QuantumCircuit.from_qasm_file(path)
or
circuit = QuantumCircuit.from_qasm_str(qasm_str)
As part of this change the circuitbackend imports for Unroller() had to
be updated to be module imports. This was to avoid having a circular
import with the _quantumcircuit module (now that _quantumcircuit
leverages uses it).
Fixes #971

Add constructor methods to build QuantumCircuits from QASM

---

CHANGELOG.rst
qiskit/backends/aer/aerjob.py

AerJobs are local Jobs, backed by Python's concurrent `Futures`. We were not dealing correctly with an
undocumented Future state: `PENDING`, that happens when a Job is enqueued (in an internal `Executor` queue) and waiting for some worker to take it and run it.
Fixes #1203 and unblocks #975

Fixing AerJob::status() method to deal with Python's Future

---

doc/_templates/layout.html

Small follow-up to #1133, fixing the links to the different languages of the sphinx documentation, to avoid 404s when the release is made.

Fix links to languages in sphinx docs

---

CHANGELOG.rst
qiskit/quantum_info/states/_states.py

The `random_state` function from `qiskit.quanutm_info.states` starts by generating a random array on the interval (0,1]. This PR is fixes cases where values > 1 were actually being generated which caused the function to return `numpy.nan`.
Fixes #1247

Fix random_state from returning nan

---

qiskit/tools/visualization/_circuit_visualization.py

Fix #1253 
Replace `os.errno` with `errno` for compatibility with Python 3.7,
adding a round of removal of pylint disables in the process.

Replace os.errno with errno, linting

---

qiskit/backends/models/__init__.py
qiskit/backends/models/backendconfiguration.py
qiskit/backends/models/backendproperties.py
qiskit/backends/models/backendstatus.py
qiskit/backends/models/jobstatus.py
qiskit/validation/base.py
qiskit/validation/fields.py
qiskit/validation/result.py
qiskit/validation/validate.py
test/python/test_schemas.py
test/python/test_validation.py

Follow-up to #1249, adding models and schemas for:
* BackendConfiguration
* BackendProperties
* BackendStatus
* JobStatus
* Results
along with the utilities needed for supporting their functionality (Fields, Validators, and tweaks and fixes for the base models).The models however have been tested against the existing `qiskit/schemas/examples` files by modifying the `test_schema.py` file.
By having these files in place, the rest of the work (updating the components needed for each schema, adjusting the simulators for conforming to it, working with results, etc) can hopefully be split more easily.
Please note that the objects are not in use yet - will be tackled in subsequent PRS. Also, the location of some files and classes is still not set in stone (in particular, …

Add models and schema for backend objects and Results

---

qiskit/backends/aer/_simulatortools.py
qiskit/backends/aer/qasm_simulator_py.py

The `_index1` and `_index2` functions appear to now be used as static methods of `QasmSimulatorPy` in `qasm_simulator_py.py` so their definitions in `_simulartools.py` are never used and should be removed.
In addition there is a minor typo in the docstring of `_index2` which can be corrected.
Fixes #1171

Remove duplicated code from QasmSimulatorPy

---

qiskit/tools/qcvv/fitters.py
qiskit/tools/visualization/__init__.py
qiskit/tools/visualization/_circuit_visualization.py
qiskit/tools/visualization/_matplotlib.py
requirements-dev.txt
requirements.txt
test/python/test_circuit_text_drawer.py
test/python/test_qcvv_fitters.py
test/python/test_visualization.py
test/python/test_visualization_output.py

Fixes #1275
As discussed #911, this PR makes matplotlib optional:
- `import qiskit` does not import matplotlib.
- The module `qiskit.tools.visualization` has a  `HAS_MATPLOTLIB` constant to query if matplotlib is installed. Test using matplot lib should check for this to skip or not.
- When a function that requires matplotlib is called and matplotlib is not installed (or python is not running as a framework in osx) a `ImportError` exception is raised with instructions to pip install matplotlib. Because this only happens when effective use occurs, more tests can be executed without matplotlib now.
- The use of `VALID_MATPLOTLIB` in the tests was removed.
- The line `matplotlib>=2.1` was moved from `requirements.txt` to `requirements-dev.txt`
Example without matplotlib:
```
>>> from …
```

runtime matplotlib import

---

CHANGELOG.rst
qiskit/backends/baseprovider.py
test/python/_mockutils.py

Complete the deprecation of `available_backends()` - which actually resulted in a tiny PR as the real functionality was removed during #1131.
In the process, a duplicated section of the changelog was removed (and no line added for this PR, as it was already present).
Labelling this PR as `specs`, as it carries out the action mentioned in  https://github.com/Qiskit/qiskit-terra/issues/1047#issuecomment-435461710

Fully deprecate `BaseProvider.available backends()`

---

doc/install.rst
setup.py

This commit adds a setuptools extras [1] entry for optionally installing
matplotlib. This enables users to just run:
'pip install qiskt[visualization]' and instlal qiskit and the
visualization dependencies in one command. Right now this is only
matplotlib, but it will likely also include nxpd too in the near future.
[1] https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

Add setuptools extras for installing matplotlib

---

CHANGELOG.rst
qiskit/backends/basebackend.py
qiskit/backends/ibmq/__init__.py
qiskit/backends/ibmq/api/ibmqconnector.py
qiskit/backends/ibmq/ibmqbackend.py
qiskit/backends/providerutils.py
test/python/ibmq/test_ibmq_connector.py
test/python/ibmq/test_ibmq_qobj.py
test/python/test_backends.py

Related issues:
#996 - `backend_status_schema.json` checkbox
#1175 - fixes for `connector.backend_status()`
Update the Base (used by Aer) and IBMQBackend `.status()` method in order to return instances of `BackendStatus`. This includes moving the `IBMQBackend.status()` property mangling one layer deeper, to `IBMQConnector.backend_status()`, making use of the original fixes of the unpublished branch "feature/qiskit_requirement" of `qiskit-api-py` (commit f55c5d9) along with additional fixes for the rest of the fields in the schema.
`test/python/test_backends.py` has also been adjusted in order to iterate through the backends, checking their `.status()`.

Update backend.status() to use BackendStatus

---

CHANGELOG.rst
qiskit/backends/basebackend.py
qiskit/backends/ibmq/api/ibmqconnector.py
qiskit/backends/ibmq/ibmqbackend.py
test/python/ibmq/test_ibmq_connector.py
test/python/test_backends.py

Remove the `.calibration()` and `.parameters()` methods (that were marked as deprecated in 0.6) from:
* BaseBackend
* IBMQBackend
* related methods from IBMQConnector
This includes adding `IBMQConnector.backend_properties()` method, based on the original code of the unpublished branch "feature/qiskit_requirement" of `qiskit-api-py` (commit 3791601) with some additional tweaks.
For testing, the most relevant test is `test/python/test_backends.py::TestBackends::test_remote_backend_properties` (which as usual will not be run until merging) - running it manually against QX and IBMQ seemed to work.
Please note that this PR does **not** deal with the schema for the `backend_properties` - which currently seems to be quite a way off from the expected one (to be addressed in subsequent PRs).

Remove .parameters() and .calibration() (now .properties())

---

qiskit/unrollers/_jsonbackend.py
test/python/common.py
test/python/ibmq/test_ibmq_qasm_simulator.py
test/python/test_wrapper.py

Reverts Qiskit/qiskit-terra#1309 (via the github interface button - let's see how it goes, seems to be creating a branch in the main repo).
As #1309 was a temporary solution for trying to find a bug finally fixed by #1314 (hopefully), I'm creating the revert PR in the hopes of being able to introduce the underlying feature (easy access to logs and extra-information from travis and CIs) later in a more controlled way, as part of the post-0.7 CI revamp.

Revert "Add debug logging to occasionally failing tests"

---

qiskit/tools/visualization/_utils.py
test/python/test_visualization.py

The _get_instructions() helper function was operating a level too low,
it should take a circuit in and return the iterators needed for drawing
the circuit. Each of the drawer backends deal with a circuit and
converting to a dag prior to getting the instructions adds unnecessary
complexity to the circuit_drawers. We also can isolate handling that in
one place in the helper function so if/when we change our relationship
between dags and circuits we have a single place to fix.

Switch _get_instructions() function to use a circuit

---

qiskit/tools/visualization/_matplotlib.py

This commit converts the matplotlib drawer to use the
_utils.get_instructions() function instead of using the transpiler. This
allows us to remove our dependency on the transpiler for circuit
visualization and also makes our bit ordering consistent with the
documented ordering.
Fixes #1272

Convert mpl drawer to use _utils.get_instructions()

---

test/python/ibmq/test_ibmq_qobj.py

Update the name of the simulator used by `test_ibmq_qobj` during the setup phase, in order to make `master` pass after #1303 .

Fix test_ibmq_qobj simulator usage

---

qiskit/tools/visualization/_latex.py
qiskit/tools/visualization/_matplotlib.py

The patches that switched the circuit drawers away from using the
transpiler and switching to the circuit/dag changed the format we were
passing conditionals to the drawers. Instead of getting a bitmask and a
value we now get the register name and the value. Additionally the field
in the instruction changed from 'conditional' to 'condition', and
defaults to None instead of not being present. However none of these
changes were reflected in the migration patches #1278 and #1276. This
commit corrects the behavior for conditionals by updated the checks and
just generating the bitmask for conditionals.
Fixes #1318

Fix conditional drawing in latex and mpl

---

.pylintrc
CHANGELOG.rst
qiskit/backends/aer/qasm_simulator.py
qiskit/backends/aer/qasm_simulator_py.py
qiskit/backends/aer/statevector_simulator.py
qiskit/backends/aer/statevector_simulator_py.py
qiskit/backends/aer/unitary_simulator_py.py
qiskit/backends/basebackend.py
qiskit/backends/ibmq/api/ibmqconnector.py
qiskit/backends/ibmq/ibmqbackend.py
qiskit/backends/models/backendproperties.py
test/python/_mockutils.py
test/python/test_backends.py

Related issues:
#996 - backend_properties_schema.json checkbox
In a similar spirit to #1301 and #1323, update `backend.properties()` (base, aer, and ibmq) in order to return instances of `BackendProperties` that conform to the schemas instead of dicts.
For the local simulators, their properties have been composed trying to achieve minimal working ones, using placeholders - as the specs does not allow empty Properties. In particular, `qubits` and `gates` require at lease one element: they should be set to proper values in a follow-up PR.
For `IBMQBackend`, the changes involved moving the parsing and processing of the properties to the IBMQConnector, freeing up the layer above from those modifications. Please note that the processing included is meant to be temporary, and takes into account …

Update backend.properties() to use BackendProperties

---

qiskit/result/result.py

With changes to the Result object the return formatting for the
Result.data() (previously Result.get_data()) method has changed. This
commit updates the docstring to better explain the new format and how it
differs from the get_XXX() functions which do processing of the data.
Fixes #1374

Update docstring for Result.data()

---

qiskit/backends/ibmq/api/ibmqconnector.py
qiskit/backends/ibmq/ibmqsingleprovider.py

Fix the value of "configuration.conditional" for devices that use the
old endpoints and do not provide a default value.
Add safety block for configurations that cannot be parsed.

Fix "conditional" for devices using old endpoints

---

CHANGELOG.rst
qiskit/result/result.py
test/python/aer/test_extensions_simulator.py
test/python/aer/test_qasm_simulator.py
test/python/aer/test_simulator_interfaces.py
test/python/circuit/test_circuit_operations.py
test/python/test_dagcircuit.py

In this pull request we are removing from results get_snapshot. The snapshots are still possible using results.data(circuit)[‘snapshot’] and if we need a method for making this simpler we will add this to analyzation and it can be configured to the snapshots the users wants.

Removing snapshots

---

CHANGELOG.rst
qiskit/result/result.py

This commit just makes some small tweaks to the changelog entry for the
removal of Result.get_snapshot() and the docstring for Result.data()
(which is the alternative to getting snapshots post removal). Hopefully
this will make it a bit clearer moving forward on how to access
snapshots in a result object.

Update docs around Result.get_snapshot removal

---

qiskit/result/result.py

Adding a rounding feature to the get_commands in results. I am tired of seeing numbers at 17 decimals when it is zero.

Adding a round feature

---

qiskit/backends/models/backendconfiguration.py

Update the `BackendConfiguration` model to adhere to the schemas,
disallowing `-1` for `n_qubits`.
This is a small fix  that makes that model be consistent with the change introduced in #1327 - which now can be added safely since #1369 landed.

Update configuration.n_qubits model, disallow -1

---

CHANGELOG.rst
qiskit/backends/aer/qasm_simulator.py
qiskit/backends/aer/qasm_simulator_py.py
qiskit/backends/aer/statevector_simulator.py
qiskit/backends/aer/statevector_simulator_py.py
qiskit/backends/aer/unitary_simulator_py.py
qiskit/backends/basebackend.py
qiskit/backends/ibmq/ibmqbackend.py
test/python/test_backends.py

As per conversations, update the `backend.properties()` methods for local and remote
simulators, so they return `None`, adjusting the `BaseBackend` method
accordingly.
Addresses partly #1332.

Update backend.properties to None for simulators

---

qiskit/tools/qi/qi.py
test/python/tools/visualization/test_visualization.py

Remove some `DeprecationWarnings` when running the test suite. There are still some of them that are expected:
`test/python/test_result.py`: two warnings due to using result addition, to be removed when the deprecation is completed.
`test/python/ibmq/test_registration.py`: one warning when using duplicate credentials (expected, as the test is actually checking for that feature).

Remove some DeprecationWarnings in test suite

---

qiskit/validation/base.py
test/python/converters/__init__.py
test/python/converters/test_qobj_2_circuits.py

Move the `to_dict()` and `from_dict()` methods directly to the
`BaseModel` instead of appending them at decoration time, for ease of
usage and aiding discovery.
Adjust the converter tests as a followup to #1410, caught while testing.

Make to_dict and from_dict more discoverable, adjust converter tests

---

qiskit/backends/models/backendproperties.py
qiskit/schemas/backend_properties_schema.json

Use `integer` instead of `number` in the schema for BackendProperties
(`BackendProperties.gates[x].qubits`).

Use integers in properties.gates.qubits

---

CHANGELOG.rst
qiskit/backends/aer/qasm_simulator_py.py
qiskit/converters/circuits_to_qobj.py
qiskit/result/result.py
qiskit/tools/_compiler.py
test/python/aer/test_qasm_simulator.py
test/python/aer/test_qasm_simulator_py.py

Fixes #1063
This PR supports reading per-shot measurements, in a new field of the result.data called memory. This information is accessible via result.get_memory().
The Aer.QasmSimulator() and Aer.QasmSimulatorPy() do this in #1373. The devices are being modified separately to do this. However, backends may continue to just return counts, if they choose.

result.get_memory()

---

qiskit/converters/qobj_to_circuits.py
test/python/converters/test_qobj_2_circuits.py

This commit adds support to the helper function in
qiskit.tools.qobj_to_circuits for creating circuits from a qobj without
compiled qasm in the header. It does this by looping over the Qobj
object to run the operations needed to construct the circuit objects
directly instead of just parsing qasm.
Fixes #1407

Add support to qobj_to_circuits for qobj without qasm

---

qiskit/converters/qobj_to_circuits.py
test/python/converters/test_qobj_2_circuits.py

Since moving the qobj_to_circuit() function from parsing the qasm in the
header any qobj with a simulator instruction hasn't worked. This is
because the function naively assumed that any instruction in the qobj
wouldn't have parameters defined that were not used by the QuantumCircuit
method. So it would always pass the list of all parameters, qargs, and
cargs assuming that to always be correct. However for the simulator
instructions snapshot, save, load, and noise the QuantumCircuit
instruction methods for those only want the slot (or switch for noise),
but the qobj has a qargs defined. This commit fixes this by special
casing the simulator instructions and only using the parameters required
by the instruction methods.

Fix simulator instruction handling for qobj_to_circuit()

---

qiskit/validation/fields/containers.py
qiskit/validation/fields/polymorphic.py

When running on Python 3.7 importing things from 'collections.abc' via
just 'collections' raises a deprecation warning because it'll be
removed in python 3.8. This commit fixes this by updating the imports
to not use the alias.

Fix deprecation warnings for abc on Python 3.7

---

qiskit/backends/aer/aerprovider.py
qiskit/backends/ibmq/ibmqprovider.py
test/python/test_backend_name_resolution.py

Move the `deprecated_backend_names` and `aliased_backend_names` to
private.
Part of #1046.

Move aliased and deprecated functions to private

---

qiskit/tools/visualization/_matplotlib.py

When we migrated to using the dag the labels for bits in mpl drawings
were broken because we started passing around a Register object instead
of just a string. This commit fixes the issue by pulling the actual
string label for the register instead of an object.
Fixes #1449

Fix label when drawing registers in mpl

---

qiskit/backends/ibmq/api/ibmqconnector.py

Currently when we encounter an error response we log a message (or raise
an exception) saying we hit a failure response code. In that message it
contains the full url which potentially includes the access token. This
is a potential security issue because we don't want to log the token
accidentally somewhere. While there is a ttl on that token and it's
going to expire, there is still a chance someone could use that
information to gain access to the system. This commit addresses this
potential issue by stripping any query info from the logged url and
also only logging the relative api path relative to the actions being
invoked. This is all that should be needed to understand and
report/debug a failure encountered while making requests to the api.
This is a mirror of …

Sanitize url in error and warnings

---

qiskit/dagcircuit/_dagcircuit.py
qiskit/mapper/_mapping.py
test/python/test_mapper.py
test/python/test_reordering.py
test/python/tools/test_compiler.py
test/python/transpiler/test_basic_mapper.py

Attempts to address failing tests in #1426 by increasing size of identity_wire_map to the number of physical qubits in the device.

Increase mapper identity_wire_map size to coupling.size() (#1426).

---

qiskit/backends/ibmq/ibmqbackend.py
qiskit/backends/ibmq/ibmqjob.py
test/python/ibmq/test_ibmqjob.py

Fix #1372 
This PR fixes the root cause for master failing allowing users to retrieve their jobs prior to 0.7. It also displays a deprecation warning encouraging the user to save the results from old jobs or resend with the latest version.

Restoring header fields in _reorder_bits

---

qiskit/transpiler/passes/mapping/basic_mapper.py
qiskit/transpiler/passes/mapping/direction_mapper.py
qiskit/transpiler/passes/mapping/unroller.py

Without `__init__.py` file, Python does not consider this directory a package and it is not packaged when setup.py is ran, resulting in an error when trying to use this Qiskit package.

Added empty __init__.py to transpiler/passes/mapping

---

qiskit/backends/builtinsimulators/_simulatortools.py
qiskit/backends/builtinsimulators/qasm_simulator.py
qiskit/backends/builtinsimulators/statevector_simulator.py
qiskit/backends/builtinsimulators/unitary_simulator.py
test/python/circuit/test_circuit_operations.py
test/python/simulators/test_qasm_simulator_py.py
test/python/tools/test_compiler.py

Updates Terra python simulators to match qiskit-aer C++ simulators for basic usage and options.
Improves speed of `QasmSimulatorPy` and `StatevectorSimulatorPy` by switching to using Numpy Einsum and adding measure sampling to QasmSimulatorPy
* update `QasmSimulatorPy` to use `numpy.einsum`
* add measurement sampling to `QasmSimulatorPy`. Enabled by setting`"allows_measure_sampling": True` in qobj experiment config, or it can do a basic check that a circuit contains no resets, and no gates after the first measure.
* implements `StatevectorSimulatorPy` without snapshot hack
* removes snapshots from python simulators
* allows measure, reset, conditionals in single shot statevector simulator
* if circuit contains no creg `QasmSimulatorPy` returns empty count dictionary
* if circuit contains …

Update python simulators to match qiskit-aer simulator

---

qiskit/__init__.py
setup.py

Partially solves #1490 by:
* Trying to make `Aer` available in the `qiskit` root package.
* Changing the name of the package to `qiskit-terra`.
* Changing the description to align it with the repository description of the Terra element.
* Adding the Aer element as a feature dependency.

Trying to import Aer provider and adding the Aer element as a feature

---

Makefile
doc/theme/static/themeExt.js
qiskit/circuit/measure.py
qiskit/circuit/quantumcircuit.py
qiskit/mapper/_layout.py
qiskit/providers/builtinsimulators/qasm_simulator.py
qiskit/providers/builtinsimulators/simulatorsjob.py
qiskit/providers/builtinsimulators/statevector_simulator.py
qiskit/providers/builtinsimulators/unitary_simulator.py
qiskit/providers/ibmq/ibmqbackend.py
qiskit/providers/ibmq/ibmqjob.py
qiskit/quantum_info/operators/_measures.py
qiskit/quantum_info/states/_measures.py
qiskit/transpiler/_passmanager.py
qiskit/transpiler/passes/decompose.py
qiskit/transpiler/passes/mapping/cx_direction.py
qiskit/transpiler/passes/mapping/unroller.py
qiskit/validation/fields/polymorphic.py
qiskit/validation/validate.py

* Remove most of the sphinx warnings produced during `make doc`, which involves tweaking a bunch of docstrings, as part of the release dance.
* Fix a rendering issue with the TOC, where some sections where not shown with the right name.
* More importantly, **include `qiskit.tools` in the documentation.** Previously it was not included as it was a non-essential package, but now it has grown in scope and includes relevant functionality (ie. compiler, events, visualization). Please note that the warnings for `qiskit.tools` have *not* been fixed.
Ideally we should followup with cleaning the warnings for `qiskit.tools` and indentation fixes for the changelog and release notes (not included to avoid conflicts with the work in #1456 )

Sphinx docstring cleanup, and include qiskit.tools

---

qiskit/tools/jupyter/jupyter_magics.py
qiskit/tools/monitor/job_monitor.py

For long device queues, it is possible to check the status of a job more times than is allowed on the IBM network.  Here, the job status check interval is made adaptive, where the interval between checks is determined by queue position.

ENH: Adaptive job status check interval

---

CHANGELOG.rst
qiskit/qiskiterror.py

In #1600, `qiskit.qiskiterror` (the module) was renamed to `qiskit.exceptions` - and it seems we have dependencies using that import directly (as opposed to importing from qiskit - sorry aer guys! :grin: ).
This PR restores the module, making it a soft import of the real `qiskit.exceptions` module, along with a note in the CHANGELOG.

Restore qiskit.qiskiterror

---

CHANGELOG.rst
qiskit/providers/builtinsimulators/qasm_simulator.py
test/python/tools/test_compiler.py

Fixes #1583 
A bug in the BasicAer qasm_simulator caused measurement sampling to behave incorrectly when more qubits existed than being measured.
This fix also allows us to use BasicAer in the one remaining test in `test_compiler`. So now the only tests using the legacy_simulator are the ones living in `test/python/old_aer_integration_test`. So we just need to move those out of Terra and then #1621 can be closed.

fix BasicAer sampling bug

---

qiskit/_util.py

Add a warnings filter for ignoring `ChangedInMarshmallow3Warning`,
renaming the util function in the process.
Mashmallow 3 release seems to be relatively close, but it is technically still in beta (with release candidates) and 2.17.0 introduced some extra warnings that in practice are a bit noisy in our current usage. This PR disables them, giving us less verbosity during that window.

Silence ChangedInMarshmallow3Warning warnings

---

.travis.yml

Currently the osx jobs are failing trying upgrade the pyenv version to the latest (which is needed to install the python versions we test in CI). According to the travis docs the best way to use homebrew on osx jobs is to rely on the travis addon instead of doing it manually in the install scripts. This commit makes this change so we install the latest version of pyenv (and the python 3.7 dependencies) via the addon instead of out of band. This fixes the failure and makes sure we have the latest versions of the homebrew package installed as needed.

Switch to travis addon for homebrew on osx jobs

---

CHANGELOG.rst
qiskit/transpiler/_transpiler.py
test/python/test_mapper.py

Remove the use of the deprecated `format` kwarg used in the `transpile_dag` function.

Remove `transpile_dag()`'s `format` kwarg

---

setup.py

Since #1644 we've removed all the C++ code from the terra repository.
That commit updated the setup.py and build process to not assume we're
compiling code to build the simulators. However we missed a lot of
parameters imports and other code in the setup.py which are not needed
or don't apply anymore now that terra is just python code. This commit
cleans that all up so we minimize what we include in the setup.py.

Clean up unused code in setup.py

---

CHANGELOG.rst
qiskit/tools/visualization/__init__.py
qiskit/tools/visualization/_dag_visualization.py
qiskit/tools/visualization/_gate_map.py

I'm adding `dag_drawer` and `gate_map` to import from `qiskit.tools.visualization`. These were apparently omitted in order to keep dependencies light. But this should only be a problem at the point of use, not import. Right now we have a situation where some things are imported and some things are not, creating an inconsistent API.
This commit makes everything consistent (we have functions that raise dependency errors at the point of use (e.g. plot_histogram), but are still imported).
All the dependencies that were optional (nxpd, matplotlib) will remain optional.

gate_map and dag_drawer available, but raise at point of use

---

qiskit/tools/visualization/_matplotlib.py

In #1651 the register labels were updated to reflect their actual value.
However, in that change a single usage of the old label was missed and
remained. This was in the code path when there was a conditional in the
circuit. This commit corrects the oversight and updates the last
remnant of the old label name.

Fix register label in mpl conditional drawing

---

CHANGELOG.rst
qiskit/quantum_info/operators/pauli.py

Remove Pauli v, w, and pauli_group() case arg as int

Remove Pauli v, w, and pauli_group() case arg as int

---

CHANGELOG.rst
appveyor.yml
qiskit/__init__.py
qiskit/exceptions.py
qiskit/qiskiterror.py
qiskit/tools/jupyter/_backend_monitor.py
qiskit/tools/monitor/backend_overview.py
qiskit/tools/visualization/_circuit_visualization.py
qiskit/tools/visualization/_gate_map.py
test/python/notebooks/test_backend_tools.ipynb
test/python/test_qcvv_fitters.py

Related to #1646.
(Hopefully) Complete the round of deprecations for 0.7, by removing `QISKitError` (ie. the one with the old capitalization). In the process, a handful of old references were updated in `tools` and `tests`, and also took the chance to unify the convention used for some `TODO`s, relying on the git history instead.

Remove QISKitError (old capitalization)

---

CHANGELOG.rst
qiskit/transpiler/_transpiler.py
qiskit/transpiler/passes/mapping/barrier_before_final_measurements.py
test/python/test_mapper.py
test/python/transpiler/test_add_barrier_before_measuremets.py

Update the default transpile pipeline to add a barrier prior to the last round of measurements for both devices and simulators. Fixes #1591.

Include BarrierBeforeFinalMeasurements in default transpile pipeline

---

CHANGELOG.rst
qiskit/converters/circuits_to_qobj.py
qiskit/qobj/_converter.py
qiskit/test/mock.py
test/python/converters/test_qobj_to_circuits.py
test/python/qobj/test_qobj_identifiers.py

Fixes #1633 
Remove `compiled_circuit_qasm` from the Qobj header, since all the
backends support Qobj and it was part of the pre-Qobj transition.

Remove compiled_circuit_qasm from Qobj header

---

qiskit/dagcircuit/_dagcircuit.py
qiskit/transpiler/passes/mapping/barrier_before_final_measurements.py
test/python/transpiler/test_add_barrier_before_measuremets.py
test/python/transpiler/test_lookahead_swap.py

Fixes #1709 by including barriers as ops to be re-inserted in the DAG after the new barrier. Also, removes the existing logic to consolidate barriers (this can be re-added, but probably as a separate pass).

Update BarrierBeforeFinalMeasures to preserve existing barriers

---

qiskit/transpiler/passes/mapping/stochastic_swap.py
test/python/transpiler/test_stochastic_swap.py

Fixes #1573. StochasticSwap had been in some cases appending swap gates based on the layout of logical qubits at the time of the swap rather than the initial layout, generating circuits incompatible with the provided coupling map.

Fix StochasticSwap mapper emitting 2q gates outside coupling map

---

test/python/test_tomography.py

This commit removes some old skips from the tomography tests that were
added during the brief period when we were returning hex values in
get_counts prior to the 0.7 release. Since we're back to returning
binary strings we can safely remove these skips because the tests should
pass again.

Remove old skips for hex return format

---

CHANGELOG.rst
qiskit/quantum_info/__init__.py
qiskit/quantum_info/states/_states.py
qiskit/tools/qi/qi.py
test/python/quantum_info/test_states.py

The purity function in ``qiskit.tools.qi.qi`` has been moved to ``qiskit.quantum_information`` as per #1219
Issue #1219 calls for the ``qiskit.tools.qi.qi.purity`` to be moved into the new ``quantum_information`` namespace as well as the addition of a "real test" for this function. I have implemented this change and written a few tests for the purity function. The old purity function in ``qiskit.tools.qi.qi`` now calls the new function and issues a deprecation warning.

Move purity function to quantum_information namespace

---

qiskit/mapper/_coupling.py
qiskit/transpiler/passes/mapping/stochastic_swap.py

- Coupling map distance is now numpy array.
- All random scalings in Stochastic mapper are computed at once (50x+ faster).

Update coupling distance and computing of random scalings in Stochastic mapper

---

qiskit/tools/visualization/_text.py
test/python/tools/visualization/test_circuit_text_drawer.py

Fixes #1733
The following circuit is text drew like this:
```
q = QuantumRegister(2)
qc = QuantumCircuit(q);
qc.rzz(0, q[0], q[1])
```
```
┌────────┐
q0_0: |0>┤        ├
│ Rzz(0) │
q0_1: |0>┤        ├
└────────┘
```

Adding support for 2-or-moreQ gates in the text drawer 

---

qiskit/transpiler/passes/mapping/stochastic_swap.py

It is 4x faster to undo a swap than it is to copy a `Layout` so only do so when needed.  For the 20x5 QV test this brings the time down from 30 -> 22 sec.

Only copy Layout when needed

---

tox.ini

Specifiy basepython in tox testenv
For versions of Linux that have both python2 and python3 installed,
tox will use python2 if not specified. This prevents tox targets like
lint from running as the version of pylint is only available for
python3.
This sets basepython for all testenvs to make this work.

specify basepython in tox testenv

---

qiskit/converters/dag_to_circuit.py
test/python/circuit/test_circuit_load_from_qasm.py

Fixes #1753 by using the lexicographical topological sort to order the gates. Added in a test to cover this.

Correct order of instructions when loading OpenQASM

---

qiskit/providers/models/pulsedefaults.py
test/python/test_schemas.py

Follow up to #1757 
Fix the model for `PulseDefaults`, where the type of `params` was set
to a list instead of a single value.
Update `test_schema` to raise an error instead of logging.

Fix pulse defaults params, update schema test

---

qiskit/dagcircuit/_dagcircuit.py

In the spirit of #1346, this PR deprecates the methods that have a prefix `get_`.

Remove get_ prefix in DAGCircuit methods

---

qiskit/mapper/_layout.py
qiskit/transpiler/passes/mapping/basic_swap.py
test/python/test_layout.py

The layout object is going to be used as a way to define which part of the coupling map is going to be used for the mappers in general, and the swappers in particular.
This means, if you are using physical qubit 2, they assumption should not be that physical qubits 0 and 1 are available. This PR fixes that and, by that, simplifies the object structure.

Layout object simplification

---

qiskit/transpiler/_transpiler.py

I'm not an expert here, but it seems that there an advantage in getting rid the pointer to circuit after `_transpilation()` converts it to DAG, specially when there are several instances of `_transpilation()` running in parallel.
For a set of 1000 circuits generated with Randomized Benchmarking from Ignis, compile takes slightly less in my machine:
```
133.00766 segs # without the patch
109.01785 segs # with the patch
```

a small optimization in parallel compilation cases

---

qiskit/qobj/qobj.py

On some backends Gate parameters get mapped to list of [re, im]. This fix properly tests sympy objects for whether this is needed.

fixes Instruction params getting nested list for reals

---

qiskit/tools/visualization/_counts_visualization.py

When we were plotting multiple executions in the histogram plot the
xtick (and label) were being put on the position of the first bar.
However this goes contrary to expectations since the tick is normally
expected in the center of the group of bars for that particular result.
This commit adjusts this by apply an offset to the xtick position to
always keep in centered in the group.
Fixes #1812

Center histogram labels with multiple executions

---

test/python/transpiler/test_mappers.py

Because the meta test for swappers checks against a fixed ground truth, they need to be seeded.

Meta testing should set seed_mapper for the mappers

---

.pylintrc
CHANGELOG.rst
qiskit/test/__init__.py
qiskit/test/providers/__init__.py
qiskit/test/providers/backend.py
qiskit/test/providers/provider.py
qiskit/test/reference_circuits.py
test/python/basicaer/test_basicaer_backends.py
test/python/basicaer/test_basicaer_integration.py
test/python/basicaer/test_basicaer_qobj_headers.py
test/python/basicaer/test_multi_registers_convention.py
test/python/basicaer/test_qasm_simulator.py
test/python/basicaer/test_statevector_simulator.py
test/python/basicaer/test_unitary_simulator.py

Continuing #1616, add a mini-framework (as in, two specializations of `QiskitTestCase`: `ProviderTestCase` and `BackendTestCase`) containing a minimal amount of tests for providers and backends, in order to have a "canonical" set of tests that a provider implementer can use (by inheriting and customizing), for both our and theirs convenience - `basicaer` has been used as the guinea pig for the changes.
For the moment, the tests included have been kept as minimal as possible - this PR is intended to set the basics in place, and later fine-tune the specific tests and circuits as needed.

Add qiskit.test facilities for providers and backends

---

qiskit/qobj/qobj.py

A simple `Qobj` representation.
A qobj is now printed like this:
```
Qobj<2 qubits, 10 circuits, 1024 shots>
```
vs
```
Qobj(config=QobjConfig(max_credits=10, memory_slots=2, n_qubits=2, shots=1024), experiments=[QobjExperiment(config=QobjExperimentConfig(memory_slots=2, n_qubits=2), header=QobjExperimentHeader(clbit_labels=[['c0', 0], ['c0', 1]], creg_sizes=[['c0', 2]], memory_slots=2, n_qubits=2, name='circuit0', qreg_sizes=[['q0', 2]], qubit_labels=[['q0', 0], ['q0', 1]]), instructions=[QobjInstruction(name='h', qubits=[0]), QobjInstruction(name='cx', qubits=[0, 1]), QobjInstruction(name='barrier', qubits=[0, 1]), QobjInstruction(memory=[1], name='measure', qubits=[1]), QobjInstruction(memory=[0], name='measure', qubits=[0])]), QobjExperiment(config=QobjExperimentConfig(memory_slots=2, …
```

Simple Qobj repr

---

qiskit/tools/visualization/_state_visualization.py

The plot_state_city() function had code to handle when the bars in a
component of the graph were all the same. It assumed these values were
all zero and to make the flat bar of 0 height in the z at the bottom of
the graph it would adjust the limits to be 0 to 1+10^-9. However, this
condition was erronously being applied to all conditions when the bars
were all of the same height even if not zero. This would have the
undesired effect of changing the limits to be X to X+10^-9, which was
not desired behavior. This caused matplotlib to render the bars from
what appeared to be an offset from the axes. This commit corrects this
incorrect behavior by changing the checks to differentiate between bars
of equal nonzero height and equal zero height. The zero case is treated
the same, but in the case …

Fix city plots where bars are equal and not zero

---

.travis.yml
constraints.txt
tox.ini

This commit adds a constraints file so we're always running pylint and
astroid at known working version. The 2 are requirements are very coupled
and small changes in one often requires an update in the other.
Unfortunately new versions of pylint often change or add rules which
makes running it unpinned not a good decision. To ensure a consistent
environment for running pylint this commit leverages pip constraints to
make sure we always install the same version of astroid and pylint.

Add constraints to pin pylint to known working version

---

qiskit/circuit/quantumcircuit.py

justify existed as part of `circuit_drawer()`, but not `circuit.draw()`.
i added it.

add justify to circuit.draw() signature

---

test/python/tools/test_compiler.py

When `transpile` fails in `test_mapping_correction` and `test_mapping_multi_qreg`, it is not possible to see the traceback because a try-catch masquerades an error into a fail.

Two tests have a try-except that masquerades an error into a fail

---

qiskit/tools/visualization/_latex.py

For whatever reason the latex circuit drawer was not able to handle the
identity gate. If it encountered one it would just leave a gap in the
circuit were it was expected. This commit fixes this oversight and adds
the identity gate to the list of single box gates. It will draw it as
"Id" in a single box.
Partially-fixes issue #1870

Add support for identity gate to latex drawer

---

CHANGELOG.rst
qiskit/quantum_info/analyzation/average.py
qiskit/quantum_info/analyzation/make_observable.py
test/python/quantum_info/test_analyzation.py

As per discussion in #1322 I have altered the ``average_data`` function to accept an observable given as a sorted list.
When passed a list or matrix as an observable, ``average_data`` will now call ``make_dict_observable`` to convert into dictionary format. The function then continues as before.  This address the feature request in #1322 and has accompanying tests.

Changed average_data to accept observable input in matrix form 

---

qiskit/tools/visualization/_matplotlib.py

If an empty quantum circuit is passed into the draw function with the
mpl output specified it will stack trace. This is because internally the
mpl drawer assumes there will be always registers and operations that it
can iterate over. This commit fixes that so passing in an empty quantum
circuit is no longer fatal. It will return a blank white image, which is
consistent with the behavior of the latex and text output types.
Fixes #1845

Handle empty output in mpl circuit drawer

---

qiskit/circuit/gate.py

When unrolling a gate without a decomposition rule we raises:
```
NotImplementedError: ('No decomposition rules defined for ', 'U')
```
and the error should be
```
NotImplementedError: No decomposition rules defined for U
```
This PR fixes that.

Typo in error message

---

.gitignore

The `stochastic_swap` pass creates the following cpp files:
```
qiskit/transpiler/passes/mapping/cython/stochastic_swap/utils.cpp
qiskit/transpiler/passes/mapping/cython/stochastic_swap/_swap_trial.cpp
```
This PR ignores the files as well as any other `cpp` file in the subfolders of `cython` under the `passes` folder.

gitignoring cpp files created in cython folders under the passes folder

---

CHANGELOG.rst
qiskit/circuit/instruction.py

Fixes #1892 
Modified the way in which type-checking is done in `instruction.py` to allow `QuantumRegister` and `ClassicalRegister` to be inherited from.
Type-equality checking is brittle and should be avoided except in the case where inheritance is to be disregarded for a class. That appears to be the case for neither `QuantumRegister` nor `ClassicalRegister`.

Fix instruction inheritance issues

---

test/python/test_dagcircuit.py

After #1897, many `multi_graph` access in `test_dagcircuit` can be replaced with the new method `dag.node()`

use dag.node() in test_dagcircuit

---

qiskit/dagcircuit/_dagcircuit.py
qiskit/transpiler/passes/mapping/lookahead_swap.py
qiskit/transpiler/passes/optimize_1q_gates.py
test/python/transpiler/test_lookahead_swap.py

This PR removes the direct access to `dag.multi_graph.nodes` by extending the DAG API with `nodes()`.

DAG.nodes() to remove dag.multi_graph.nodes()

---

CHANGELOG.rst
qiskit/dagcircuit/_dagcircuit.py
test/python/transpiler/test_optimize_1q_gates.py

Fixes #1871 Fixes #1820 
`dag.collect_runs()` should only collect runs of gates that are non-conditional, otherwise the optimizations that are based on them won't work.

Fix DAGCircuit.collect_runs()

---

qiskit/qobj/models.py
qiskit/validation/fields/__init__.py
qiskit/validation/fields/custom.py
test/python/aer_provider_integration_test/test_extensions_simulator.py
test/python/aer_provider_integration_test/test_qasm_simulator.py

Fix #1951
Add a new validation field to handle the different types that can be used in `instruction.parameters`, that were causing serialization issues, using it instead of `Raw()`, re-enabling the tests xfailed in 1909.
The root cause was that the Qobj ended up containing objects that could not be serialized by the default `json` serializer (numpy and sympy constructs) - if other fields are loosely defined in other parts of the spec, we should look into it further and extend this custom field, ensure that the producers of `Qobj` guarantee that the types used are known and serializable, or actually consider being more restrictive in the specs.

Fix qobj.experiment.instructions.parameters serialization

---

qiskit/tools/visualization/_text.py

@ajavadia noticed that, after https://github.com/Qiskit/qiskit-terra/pull/1962, the text drawer "modifies" the `qargs` of gates in the circuit.
Indeed, that's happen because I'm doing a pop of a varialble `bits`, that is a pointer to the gate's `[q|c]args`: https://github.com/Qiskit/qiskit-terra/pull/1962/files#diff-600b5035095fd43ac99cc06b82d2b902R893
This PR makes sure that the array `bit` gets a fresh pointer before juggling with it.

text drawer "modifies" the circuit

---

qiskit/validation/fields/custom.py
test/python/validation/test_custom_fields.py

Fix #1966
Extend `InstructionParameter`, adding support for containers (`list` and `numpy.ndarray`), along with polishing the class a bit and adding some some tests. 
As mentioned in previous issues, at some point we should really try to explore a more "specialized" approach for the instructions (as in, for the standard ones, define some subclasses that narrow down the parameters and other attributes a bit more, instead of relying on generic types). This is currently blocked by the comments at https://github.com/Qiskit/qiskit-terra/issues/1047#issuecomment-441718590.

Extend InstructionParameter for containers

---

qiskit/tools/visualization/_matplotlib.py

The `MatplotlibDrawer` would never show gate parameters due to a typo in the `params` attribute detection.
`matplotlib_ref.png` in the visualization tests will need updating. The image output of matplotlib on my (macOS) machine seems to differ slightly from where the file was last generated, however, and the respective tests aren't run by default anyway, so I left it for now.

MatplotlibDrawer: Fix gate parameter display

---

qiskit/providers/basicaer/qasm_simulator.py
qiskit/providers/basicaer/statevector_simulator.py
qiskit/providers/basicaer/unitary_simulator.py
qiskit/providers/models/backendconfiguration.py
qiskit/transpiler/transpiler.py

`transpile` now works correctly for simulators with `coupling_map` as required by the qiskit spec.  `BasicAer` simulators now have `coupling_map` attributes in their configuration files
This PR is required for https://github.com/Qiskit/qiskit-aer/pull/93 to pass as well.

Support `None` for simulator backend coupling_map

---

qiskit/circuit/instruction.py
qiskit/transpiler/passes/optimize_1q_gates.py
test/python/transpiler/test_optimize_1q_gates.py

Partially fixes #1989 (the `test.python.transpiler.test_optimize_1q_gates.TestOptimize1qGates.test_optimize_h_gates_pass_manager` case)
The `sympy.py` value needs to match the float version of pi:
```
> sympy.pi == 3.141592653589793                                                                
False
> float(sympy.pi) == float(3.141592653589793)                                                  
True
```
The second element of this patch is that the instruction `snapshot` creates params with symbols (i.e. `[1.00000000000000, statevector]`, so literal comparison (as before) is needed too.

compare Instructions params

---

qiskit/transpiler/passes/optimize_1q_gates.py
test/python/transpiler/test_optimize_1q_gates.py

Fixes #2004
In PR #2000, I changed the strategy of `optimize_1q_gates`, because the way that was altering the nodes in place was incorrect. Sadly, that fixes introduced #2004. This PR is going back to the change-in-place strategy (kinda, it replace one of the nodes in the run with a DAG that contain a single node with the optimization) while doing it correctly.

Optimize1qGates change node "in-place"

---

qiskit/transpiler/basepasses.py
test/python/transpiler/_dummy_passes.py
test/python/transpiler/test_generic_pass.py
test/python/transpiler/test_pass_scheduler.py

Fixes https://github.com/Qiskit/qiskit-terra/issues/1769
This PR removes the pass instance cache that was creating obscure and hard to trace bugs. It's replaced by the usual `__hash__` and `__eq__` approach.

Removing pass instance cache

---

qiskit/dagcircuit/_dagcircuit.py
qiskit/transpiler/passes/mapping/barrier_before_final_measurements.py

Fixes #1997 
Updates `apply_operation_front()` and `apply_operation_back()` to return `DAGNode`s instead of `node_id`s so that the returned value can then be used later on without getting a deprecation warning.

Updated apply_operation_front/back to return DAGNodes

---

qiskit/quantum_info/__init__.py
qiskit/quantum_info/operators/channel/__init__.py
qiskit/quantum_info/operators/channel/basechannel.py
qiskit/quantum_info/operators/channel/chi.py
qiskit/quantum_info/operators/channel/choi.py
qiskit/quantum_info/operators/channel/kraus.py
qiskit/quantum_info/operators/channel/ptm.py
qiskit/quantum_info/operators/channel/stinespring.py
qiskit/quantum_info/operators/channel/superop.py
qiskit/quantum_info/operators/channel/transformations.py
qiskit/quantum_info/operators/channel/unitary.py
qiskit/quantum_info/operators/channel/unitarychannel.py
qiskit/quantum_info/operators/predicates.py
test/python/quantum_info/channel/__init__.py
test/python/quantum_info/channel/base.py
test/python/quantum_info/channel/test_adjoint.py
test/python/quantum_info/channel/test_chi.py
test/python/quantum_info/channel/test_choi.py
test/python/quantum_info/channel/test_evolve.py
test/python/quantum_info/channel/test_kraus.py
test/python/quantum_info/channel/test_linearops.py
test/python/quantum_info/channel/test_ptm.py
test/python/quantum_info/channel/test_stinespring.py
test/python/quantum_info/channel/test_superop.py
test/python/quantum_info/channel/test_tensor_compose.py
test/python/quantum_info/channel/test_transformations.py
test/python/quantum_info/channel/test_unitarychannel.py

Closes #1193 
Adds quantum channel package to `quantum_info`. This package contains classes for representing quantum channels (CPTP maps, and also general Non-CPTP operator maps) and is essentially an implementation of the paper: 
*Tensor networks and graphical calculus for open quantum systems*
Wood, Biamonte, Cory, Quant. Inf. Comp. 15, 0579-0811 (2015)
Open access: [arXiv: arXiv:1111.6950v3](https://arxiv.org/abs/1111.6950)
* Contains classes for channel representations: 
* `Choi`: Choi-Jamiolkowski process matrix
* `SuperOp`: Linear superoperator
* `Chi`: Pauli-basis Chi matrix
* `PTM`: Pauli transfer-matrix superoperator
* `Kraus`:  Kraus / operator-sum operators
* `Stinespring`: Stinespring / system-environment insometry
* `UnitaryChannel`: single-matrix Kraus representation (not …

Quantum channels

---

qiskit/circuit/quantumcircuit.py

Checking if https://github.com/Qiskit/qiskit-terra/issues/876 and https://github.com/Qiskit/qiskit-terra/issues/1807 were still valid, I realize that nobody is updating nor reading this structure. It seems that `QuantumCircuit.definitions` is a residue from the past. This PR removes it.  
Closes #876 
Closes #1807

QuantumCircuit.definitions is not used anymore

---

test/python/compiler/__init__.py
test/python/compiler/test_assembler.py
test/python/compiler/test_compiler.py

As sort of a follow-up to #1856, add `test/python/compiler/__init__.py`, in order to turn it into a Python package - as otherwise neither `pylint` or the test runner in the CIs pick up the files inside that folder. 
Digging a bit deeper, it seems we have been not running those test since the refactor, and in the process a regression was introduced during #2006, causing `test/python/compiler/test_compiler.py::TestCompiler::test_move_measurements` to fail. This PR temporarily skips the test, in order to allow running the rest of the `test/python/compiler` tests while investigating further.
As a follow-up, we should re-introduce `TestCompiler::test_move_measurements`.

Make test.python.compiler a package

---

test/python/compiler/test_compiler.py

Follow up from https://github.com/Qiskit/qiskit-terra/pull/2025
Removing `@unittest.skip('Temporary skipping (see #2025 and #2006')` and fix it.

test_move_measurements no skipped

---

qiskit/quantum_info/operators/predicates.py

Fixes a casting bug in `quantum_info.operators.predicates` when input numpy arrays are not of type complex128.

fix numpy casting error with *=

---

test/python/quantum_info/channel/test_linearops.py

Fixes occasionally failing channel test for `Kraus.add` and `Kraus.subtract` by making sure all comparisons happen in the unique `SuperOp` representation

fix occasionally failing tests from non-unique Kraus conversion

---

qiskit/quantum_info/operators/channel/basechannel.py
qiskit/quantum_info/operators/channel/chi.py
qiskit/quantum_info/operators/channel/choi.py
qiskit/quantum_info/operators/channel/kraus.py
qiskit/quantum_info/operators/channel/ptm.py
qiskit/quantum_info/operators/channel/stinespring.py
qiskit/quantum_info/operators/channel/superop.py
qiskit/quantum_info/operators/channel/unitarychannel.py
qiskit/quantum_info/operators/unitary.py
test/python/quantum_info/channel/test_chi.py
test/python/quantum_info/channel/test_choi.py
test/python/quantum_info/channel/test_kraus.py
test/python/quantum_info/channel/test_ptm.py
test/python/quantum_info/channel/test_stinespring.py
test/python/quantum_info/channel/test_superop.py
test/python/quantum_info/channel/test_unitarychannel.py
test/python/quantum_info/test_unitary.py

After discussion with Ali, this removes the `inplace` kwarg from `QuantumChannel` and `Unitary` objects.

Remove `inplace` from QuantumChannel and Unitary

---

CHANGELOG.rst
qiskit/transpiler/passes/__init__.py
qiskit/transpiler/passes/mapping/noise_adaptive_layout.py
test/python/transpiler/test_noise_adaptive_layout.py

This pass uses backend calibration data to find a good initial qubit layout which will improve program success rate. The pass is based on the greedy heuristic from 
Prakash Murali, Jonathan M. Baker, Ali Javadi-Abhari, Frederic T. Chong, Margaret R. Martonosi. Noise-Adaptive Compiler Mappings for Noisy Intermediate-Scale Quantum Computers, ASPLOS 2019
(https://arxiv.org/abs/1901.11054)
The pass uses backend calibration data to determine a good set of physical qubits for the program dag. It selects physical qubits based on CNOT and readout errors. The pass improves the program's success rate (fraction of runs that produce the correct answer) on real hardware evaluations as demonstrated in arXiv:1901.11054.
This pass implements the noise-adaptive initial layout technique, it does not …

Noise-adaptive initial qubit layout pass

---

qiskit/transpiler/transpiler.py
test/python/compiler/test_compiler.py

Fixes #2035 
The default pipeline runs `Optimize1qGates()` and `CXCancellation()` until the DAG reaches a fixed point.

Optimize gates up to fixed point in the default pipeline

---

setup.py

The name of the key is extras_require not extra_requires to declare
optional dependencies. [1] This commit corrects the typo so it works
correctly.
[1] https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies

Fix typo in setuptools extras declaration

---

test/python/visualization/test_circuit_matplotlib_drawer.py

This commit adds a test that verifies that when we call the mpl backend
it draws an empty image of the expected size. This is just a white image
background of the default size.
Related to #1845 and #2097

Test to verify mpl draws an empty circuit empty

---

qiskit/transpiler/transpiler.py

@mtreinish discovered that #2086 affected significantly the performance of the transpiler "by default". 
That makes sense, since the optimizations `Optimize1qGates()` and `CXCancellation()` are run at least twice in order to find the fixed point. This is something that it was not done before.
However, I run the code of the benchmark locally, to see if something can be made.
Before #2086 
After #2086 
Notice that most of the extra time is in the comparison of DAGs `dag_circuit.py:741(__eq__)`. So this PR moves away from this approach and search for a fixed point in depth. This reduce the time significantly.

Performance issue because optimizations-until-fixed-point approach

---

qiskit/quantum_info/operators/unitary.py
test/python/quantum_info/test_unitary.py

Also, implement __str__ and __repr__ methods.
Expose the "getter" for quantum_info.Unitary's representation. With this change `Unitary.representation` and `Unitary._representation` work.
This pr also implements `__str__` and `__repr__` methods to simplify viewing the representation e.g.
```
In [1]: print(unitary)
[[0.+0.j 1.+0.j]
[1.+0.j 0.+0.j]]
```
```
In [2]: unitary
<qiskit.quantum_info.operators.unitary.Unitary object at 0x7f4a7473b2b0>
array([[0.+0.j, 1.+0.j],
[1.+0.j, 0.+0.j]])
```

make representation method of Unitary object more public

---

qiskit/converters/qobj_to_circuits.py
test/python/converters/test_qobj_to_circuits.py

Right now when you call qobj_to_circuits on a qobj that has an
initialize instruction in an experiment it will stacktrace with an error
because the number of positional arguments is not what's expected. This
is because the 2 positional arguments for initialize are lists and we're
currently calling initialize() on the output circuit with a * to convert
each list element into a positional argument. This commit fixes this by
special casing initialize instructions and properly passing the expected
positional args when calling initialize on the output circuit.

Fix qobj_to_circuits for circuits with initialize

---

.travis.yml
appveyor.yml

As a new version of `IBMQProvider` was released in preparation for the terra release, CIs might choke when trying to install it, as it requires terra>=0.8 (which understandably is not released). This PR fixes installs 0.1rc3 instead during this window.

Fix ibmqprovider version in CIs

---

.pylintrc
CHANGELOG.rst
qiskit/converters/dag_to_circuit.py
qiskit/dagcircuit/dagcircuit.py
qiskit/providers/basicaer/unitary_simulator.py
qiskit/tools/compiler.py
qiskit/transpiler/passes/__init__.py
qiskit/transpiler/passes/collect_2q_blocks.py
qiskit/transpiler/passes/commutation_analysis.py
qiskit/transpiler/passes/consolidate_blocks.py
qiskit/transpiler/passes/mapping/barrier_before_final_measurements.py
qiskit/transpiler/passes/merge_adjacent_barriers.py
qiskit/visualization/utils.py
test/python/test_dagcircuit.py
test/python/transpiler/test_collect_2q_blocks.py
test/python/transpiler/test_consolidate_blocks.py

Two passes are added, one for analyzing a circuit to find blocks of sequential 1- or 2-qubit gates. The other for replacing previously found blocks (this time of arbitrary width) by an equivalent Unitary operator node. This can later be resynthesized, e.g. using methods in #2119 and #2121.
Example:
```python
qv = QuantumCircuit.from_qasm_str(qasm)
pm = PassManager()
pm.append(Collect2qBlocks())
pm.append(ConsolidateBlocks())
qv2 = pm.run(qv)
```
```
q_0: |0>────────────────────────────────────────────────────────────
q_1: |0>────────────────────────────────────────────────────────────
q_2: |0>────────────────────────────────────────────────────────────
┌──────────┐            ░ ┌─┐      
q_3: |0>─────────────────────────┤0         ├────────────░─┤M├──────
┌─────────┐              │ …
```

Collect2qBlocks and ConsolidateBlocks transpiler passes

---

CHANGELOG.rst
qiskit/circuit/instruction.py
qiskit/circuit/quantumcircuit.py
qiskit/circuit/variabletable.py
test/python/circuit/test_variable_parameters.py

Small changes following review of #2103 . There are still two open questions (one on when and how parameters of subcircuits are promoted to be parameters of their parent circuit, and one on the API of variable_table), but those can be fixed separately.

Parameterized circuit documentation

---

qiskit/compiler/assembler.py

This change lets instruction params be any type, not just sympy expression. If they are sympy expressions they are evaluated as before.
This is needed to pass numpy matrices in for instructions (eg unitary) without unnecessarily wrapping them in a sympy matrix.

allow non-sympy instruction params

---

qiskit/__init__.py

The deprecation message for qiskit.compile() says that it is deprecated
and instead qiskit.assemble_circuits() in conjuction with transpile()
should be used instead of calling compile(). However, we never added
assemble_circuits to the root namespace on qiskit so you couldn't
actually call it that way. This commit corrects the oversight and
adds it to the root namespace.

Add assemble_circuits() to root namespace

---

qiskit/circuit/quantumcircuit.py
qiskit/transpiler/preset_passmanagers/default.py
qiskit/transpiler/transpiler.py
test/python/circuit/test_variable_parameters.py
test/python/transpiler/test_transpile.py

Fixes #2145 by removing `Optimize1qGates` from default set of passes when the circuit has variables which have not yet been assigned a value. Also, adds a `QuantumCircuit.unassigned_variables` property.

Remove numeric passes from default set for parameterized circuits.

---

qiskit/transpiler/transpiler.py
test/python/transpiler/test_cx_cancellation.py
test/python/transpiler/test_optimize_swap_before_measure.py
test/python/transpiler/test_pass_scheduler.py
test/python/transpiler/test_remove_reset_in_zero_state.py
test/python/transpiler/test_transpile.py

Fixes #1408 . Deprecates `transpiler.transpile_dag` in favor of `transpiler.transpile`.

Deprecate transpile_dag

---

qiskit/compiler/assembler.py

This changes the format of "unitary" and "snapshots" in assembler
* "unitary" now has a standard format for params with `"params": [mat]` rather than `"params": mat` which needed a special case to catch.
* "snapshot" changes `"type"` to more descriptive `"snapshot_type"`.
These need to be synced with Aer [PR 161](https://github.com/Qiskit/qiskit-aer/pull/161)

change qobj format of unitary and snapshot

---

qiskit/circuit/variabletable.py

This commit updates the import path for the MutableMapping. We currently
import from collections in stdlib. However that import is deprecated and
will be removed in 3.8, this raises a warning on python 3.7. To address
this and prevent breakage when python 3.8 is released, this commit
updates the path to collections.abc which is the supported path.

Update import path for MutableMapping in variabletable

---

qiskit/circuit/quantumcircuit.py
qiskit/circuit/variabletable.py
test/python/circuit/test_variable_parameters.py

Previously when assigning a variable to a circuit using the `assign_variables` method the full variable table was preserved in the new circuit. In this PR the generated circuit no longer tracks the substituted expressions.
This PR also corrects a bug where partial expression substitution resulted in no substitution.

reduce circuit's tracked variable parameters upon assignment.

---

qiskit/visualization/matplotlib.py

This commit adds support for sympy symbols as parameters to gates. These
are encountered in parametric circuits. Previously the mpl drawer
assumed all gate parameters would be numeric and thus try to format
(and/or convert) them the same way. However, if it is a sympy symbol
that can't be resolved to a numeric value then we have to just use the
symbol name instead of a numeric value.
Fixes #2144

Handle symbolic parameters in mpl circuit drawer

---

.travis.yml

Right now the jobs listed in travis don't have explicit names. You can
pretty easily figure out which jobs do what based on the OS icon and the
environment variables set for each job. But to make it a bit easier just
name each job with a descriptive human readable name so we're explicit
about which each job is doing.

Add Job names to travis config

---

qiskit/dagcircuit/dagcircuit.py
qiskit/transpiler/passes/commutation_analysis.py
qiskit/visualization/dag_visualization.py
test/python/test_dagcircuit.py

Deprecates direct access to `dagcircuit.multi_graph` in favor of the DAGCircuit API.

Deprecate DAGCircuit multi_graph access

---

qiskit/compiler/assembler.py
qiskit/extensions/simulator/snapshot.py
qiskit/schemas/examples/qobj_openqasm_example.json
qiskit/schemas/qobj_schema.json

PR #2164 changed the qasm qobj field for snapshots from `"type"` to `"snapshot_type"`, but didn't update the JSON schema so circuits with snapshots fail validation. This PR updates the schema to correct format.

Fix json schema for Qasm qobj snapshot

---

CHANGELOG.rst
qiskit/__init__.py
qiskit/compiler/__init__.py
qiskit/compiler/assembler.py
qiskit/compiler/models.py
qiskit/compiler/run_config.py
qiskit/compiler/transpile_config.py
qiskit/compiler/transpiler.py
qiskit/converters/circuits_to_qobj.py
qiskit/execute.py
qiskit/tools/compiler.py
qiskit/tools/parallel.py
qiskit/transpiler/passes/unroller.py
qiskit/transpiler/passmanager.py
qiskit/transpiler/preset_passmanagers/default.py
qiskit/transpiler/transpiler.py
test/python/aer_provider_integration_test/test_aer_qobj_headers.py
test/python/basicaer/test_basicaer_qobj_headers.py
test/python/basicaer/test_qasm_simulator.py
test/python/circuit/test_variable_parameters.py
test/python/compiler/test_assembler.py
test/python/compiler/test_compiler.py
test/python/compiler/test_disassembler.py
test/python/compiler/test_transpiler.py
test/python/converters/test_qobj_to_circuits.py
test/python/notebooks/test_pbar_status.ipynb
test/python/qobj/test_qobj.py
test/python/qobj/test_qobj_identifiers.py
test/python/quantum_info/test_unitary.py
test/python/transpiler/test_transpile.py

This is a refactoring of `qiskit.compiler` to define the user interfaces and the internal method interfaces.
There are 3 main user-facing functions: `transpile()`, `assemble()`, and `execute()`.
All 3 can handle both circuits and pulse schedules. All have an expansive set of arguments, which are overloaded heavily in certain cases for convenience (e.g. an initial_layout can be passed as a dict, or list, or Layout object).
A parsing stage separates this from the internal methods and data-structures.
Internally we have well-defined methods (e.g. `transpile_circuit()` takes a `QuantumCircuit` and a `TranspileConfig`. The TranspileConfig has a model defined whereby it only allows initial_layout to be of type Layout, etc. etc.)
- Deprecates and moves the ``transpile()`` function from the …

interface to execute(), transpile() and assemble()

---

qiskit/visualization/matplotlib.py

Fixes #2233 
The label is only added if it is short enough.
For example for the following circuit
```
qr = QuantumRegister(1)
qc = QuantumCircuit(qr)
U1 = random_unitary(2)
qc.u3(pi/2, pi/2, pi/2, qr[0])
qc.append(U1, [qr[0]])
```
This image is generated :

mpl label only shows shorter parameters

---

qiskit/circuit/parameter.py
qiskit/circuit/parametertable.py
qiskit/circuit/quantumcircuit.py
qiskit/compiler/assembler.py
qiskit/compiler/run_config.py
qiskit/execute.py
test/python/circuit/test_parameters.py
test/python/compiler/test_assembler.py

Follows #2204 , add support for specifying a list of parameter bindings to `execute` or in `RunConfig` to `assemble_circuits`.  
Example:
```
x = Parameter('x')
y = Parameter('y')
param_qc = ... # circuit over theta, phi
job = execute(param_qc, parameter_binds=[{x: 0, y: 0}, {x: 0, y: 1}, {x: 1, y: 0}, {x: 1, y: 1}])
```
will generate and run a qobj with four circuits: `param_qc(x=0,y=0)`, `param_qc(x=0,y=1)`, `param_qc(x=1,y=0)`, and `param_qc(x=1,y=1)`.
Additionally:
- Moves internal in-place parameter binding from `ParameterTable` to `QuantumCircuit`
- Raises an error when attempting to bind a parameter not found in the circuit
- Adds `Parameter.__repr__`
Needs to be rebased after #2166 , and a full model definition in run_config.

Add parameterized circuits support in RunConfig and execute

---

qiskit/circuit/instruction.py
qiskit/circuit/parameter.py
qiskit/compiler/transpile_config.py
qiskit/compiler/transpiler.py
qiskit/transpiler/passes/optimize_1q_gates.py
qiskit/transpiler/preset_passmanagers/default.py
qiskit/transpiler/transpiler.py
test/python/circuit/test_instructions.py
test/python/transpiler/test_optimize_1q_gates.py

Currently, if a circuit contains a parameterized gate, we skip Optimize1qGates in the default set of transpiler passes, even though would be possible to optimize 1q gates over runs where all of the parameters are bound. This PR updates Optimize1qGates to treat parameterized gates as opaque (so they are not optimized over) and returns Optimize1qGates to the default set of transpiler passes for parameterized circuits.

Treat parameterized gates as opaque in Optimize1qGates

---

qiskit/compiler/assembler.py
qiskit/pulse/commands/instruction.py
qiskit/pulse/interfaces.py
qiskit/pulse/ops.py
qiskit/pulse/schedule.py
test/python/pulse/test_schedule.py

This PR refactors the schedule traversal method and replaces `flatten` with `_instruction`, adds a new property `instructions` to `ScheduleComponent` which calls the `_instruction` generator. A new `op` is added `flatten` which returns a new flat schedule of the parent.
Closes #2240.

Refactor enhance schedule

---

CHANGELOG.rst
qiskit/_util.py

Since the warning was too noisy and gets emitted on every qiskit import
this commit just removes it. The _util module is still deprecated, and
listed as such in the module and in the changelog (and the future
release notes). But, since it was marked as private previously weighing
the noise of advertising the deprecation with a warning against the
potential of an external user using it removing the warning seems the
better option.
Fixes #2252

Remove warning from qiskit._util and rely on a comment

---

qiskit/transpiler/passes/unroller.py
test/python/transpiler/test_unroller.py

Currently, `Parameter`s do not support any math operations. Unrolling gates defined in terms of expressions will fail if the param is a `Parameter` (in the standard gate set, this includes cu1 and cu3). This PR improves the error message raised from
```
TypeError: unsupported operand type(s) for /: 'Parameter' and 'int'
```
to
```
qiskit.exceptions.QiskitError: 'Unrolling gates parameterized by expressions is currently unsupported.'
```

Improve error message when unrolling parameterized CU1.

---

qiskit/assembler/disassemble.py
test/python/converters/test_qobj_to_circuits.py

This commit fixes the qobj_to_circuits converter to handle opaque/custom
instructions that aren't decomposed in the qobj. At the same time the
identity gate handling is fixed because it is a special case where the
gate name doesn't match the function name (id vs iden()) and needs to be
handled that way.

Handle opaque instructions and identity in qobj_to_circuits

---

qiskit/visualization/matplotlib.py

Implemented #1957 for the matplotlib drawer. The example given is now drawn as

Corrected drawing of rzz and cu1 for mpl

---

qiskit/providers/models/backendconfiguration.py

Follow up to #2216 
Update the order of the arguments in `BackendConfiguration` for making it consistent with `QasmBackendConfiguration` and prevent confusiong when instantiating without named args - the `open_pulse` parameter ended up in a different place in the signature.

Update BackendConfiguration signature

---

qiskit/transpiler/passes/__init__.py
qiskit/transpiler/passes/mapping/set_layout.py
qiskit/transpiler/passmanager.py
qiskit/transpiler/preset_passmanagers/default.py
test/python/transpiler/test_mappers.py
test/python/transpiler/test_pass_scheduler.py

This PR introduces the method `PassManager.reset`  to allow the reuse of pass manager instances. 
Because the reset includes cleaning the property set associated, a new pass is introduced to set the layout and avoid handling the property set manually.

Allow PassManager instances to be reused

---

CHANGELOG.rst
qiskit/extensions/unitary.py
qiskit/mapper/compiling.py
qiskit/quantum_info/synthesis/__init__.py
qiskit/quantum_info/synthesis/two_qubit_decompose.py
qiskit/quantum_info/synthesis/two_qubit_kak.py
test/python/quantum_info/test_synthesis.py

This is one piece of #1580 but not a solution by itself.
Should fix #1965 and #2009 
Implements the approximate KAK decomposition from [arXiv:1811.12926](https://arxiv.org/abs/1811.12926) [quant-ph] appendix B.
For testing, one should generate a set of test unitaries of the form:
K1.Ud(a,b,c).K2
where K1 and K2 are products of single-qubit unitaries and should be tested for combinations of all 24 Cliffords for each of the single-qubit pieces, as well as some generic U3(x,y,z) gates.
The a,b,c should be tested for generic cases, but there are a lot of subtle chances to fail for particular values of a,b,c and so at least should be checked:
𝜋/4,0,0 (CNOT class)
𝜋/4,𝜋/4,0 (iSWAP class)
𝜋/4,𝜋/4,𝜋/4 (SWAP class)
𝜋/4,𝜋/8,0 (B class)
𝜋/8,𝜋/8,𝜋/8 (sqrtSWAP class)
x,x,x for arbitrary x (partial …

Implement approximate KAK decomposition

---

qiskit/quantum_info/operators/channel/quantum_channel.py

Fix typo where `to_channel` should have been `to_quantumchannel`

Fix typo in QuantumChannel init

---

qiskit/pulse/ops.py
test/python/pulse/test_schedule.py

Small bug in timing of appends with buffer. Currently a buffer will be inserted for first pulse on channel, which is not required.

Remove buffer from first pulse on channel

---

.travis.yml
appveyor.yml

The wheel build jobs failed to install twine so when the jobs completed
and went to upload the wheels this failed because the command wasn't
found. This commit fixes the issue by installing twine as part of the
wheel build job set ups so that we can actually upload our built
binaries.

Install twine in wheel build jobs

---

qiskit/visualization/latex.py

As part of the large refactor adding column justification to the latex
drawer in #1977 the function used to determine the image depth was
greatly simplified since most of the work was offset to the dag
processing prior to the latex drawer. However, one piece of critical
code was removed inadvertently which was used for determining the row
spacing. This section looked at every operation and determined if we
should increase or decrease the row spacing depending on what time of
operations were being drawn. The result of this check end up directly
setting a value in the output latex call to \Qcircuit. Without this code
the calculations which are done to determine the output page size are
off by the spacing factor and result in the output circuit exceeding the
single page size. This causes a …

Determine row spacing properly

---

appveyor.yml
test/python/visualization/test_circuit_matplotlib_drawer.py

In #2328 tests were added that required nxpd to be installed, but it was
merged before waiting for the results from appveyor. These new tests
don't pass appveyor because the requirements installed were different
from what were installed on travis. This commit fixes this so that we
install the same set of requirements on appveyor and travis jobs to
make sure when people take shortcuts in the future there are less
surprises.

Match appveyor requirements install to travis

---

qiskit/converters/qobj_to_circuits.py

Fixes #2334 in stable
This PR fixes the deprecation warning for `qobj_to_circuit`.

[stable] DeprecationWarning message to replace qobj_to_circuit

---

Make.bat
Makefile
test/python/__init__.py
tox.ini

✅ I have read the CONTRIBUTING document.
There were unused vestiges of a profiling environment. The way it was implemented interfered with some tools. In particular the VS Code automatic test discovery and running were broken by the `load_tests()` override in `tests/python/__init__.py`.
This patch removes all traces of the profiling, since anything like that probably belongs in the Qiskit/qiskit repo's benchmarking folder.

Remove profile testing loader

---

.github/CONTRIBUTING.rst

This commit documents are policy for the stable branch, how it's used
what we need to evaluate when looking at potential changes, and the
priorities for the stable branch. Some of this information was already in
the document in other sections, but this puts it together in a concrete
section.
Fixes #2352

Add stable branch policy to CONTRIBUTING.rst

---

qiskit/compiler/transpile.py

This commit adds a docstring for optimization level 3 which was missing
from the docstring for the qiskit.compiler.transpile function.

Add missing optimization level to transpile() docstring

---

qiskit/compiler/transpile.py

Fixes #2349
When a basis is not defined for a circuit, the default basis set is the
set of gates used in the circuit. This makes total sense to me.
However, passes might add gates and the might be out of that bases. For
this reason, I'm suggesting to add the base basis (UBase and CXBase) as
part of the default basis set. If I understand correctly, the base
basis (is that their name?) is supported by every backend by
definition, so the gates that are added by the transpiler can run in
the backend.
(cherry picked from commit 4bfcc5d44771beb0549ad5b5b604b0e9563d735b)
Backported from: #2357

[Stable] Transpiler add passes that might be out of the default basis

---

qiskit/compiler/transpile.py

This commit adds a docstring for optimization level 3 which was missing
from the docstring for the qiskit.compiler.transpile function.
(cherry picked from commit 757ad8a4d38927212a3ad4e6f843ed1365afb9a8)
Backported from #2367

[Stable] Add missing optimization level to transpile() docstring

---

qiskit/qobj/converters/pulse_instruction.py
test/python/qobj/test_pulse_converter.py

As noted in #2346, expression sanitization was too strict and was failing on strings of form `-(P1)`. This update the sanitization to allow strings of this form to pass.
Closes #2346.
Backported from: #2376

[Stable[ Update expression math sanitization

---

qiskit/assembler/assemble_schedules.py

Makes assemble_schedule arguments non-optional.
Backport of #2351.

[Stable] Make assemble_schedule arguments non-optional

---

qiskit/validation/base.py

Fixes #2151 
When `qiskit.validation.exceptions.ModelValidationError` raises because the input type does not match the expected type, the expected type was part of the error message but not the input type.
```
qiskit.validation.exceptions.ModelValidationError: {'n_qubits': ["Value '2' is not the expected type <class 'int'>"]}
```
With this PR the error looks like this:
```
qiskit.validation.exceptions.ModelValidationError: {'n_qubits': ["Value '2' <class 'numpy.int64'>: is not the expected type <class 'int'>"]}
```
(the example is descriptive, not a real example, see https://github.com/Qiskit/qiskit-terra/issues/2151#issuecomment-491292005)

Input type in qiskit.validation.exceptions.ModelValidationError

---

qiskit/circuit/quantumcircuit.py
qiskit/pulse/ops.py
qiskit/pulse/schedule.py
qiskit/qobj/converters/lo_config.py
qiskit/qobj/converters/pulse_instruction.py
qiskit/transpiler/passes/mapping/basic_swap.py
qiskit/transpiler/passes/mapping/check_cx_direction.py
qiskit/transpiler/passes/mapping/check_map.py
qiskit/transpiler/passes/mapping/cx_direction.py
qiskit/transpiler/passes/mapping/dense_layout.py
qiskit/transpiler/passes/mapping/lookahead_swap.py
qiskit/transpiler/passes/mapping/noise_adaptive_layout.py
qiskit/transpiler/passes/mapping/stochastic_swap.py
qiskit/transpiler/passes/mapping/trivial_layout.py

As @levbishop helpfully pointed out in #2400, more measures were need for  handling the `cyclic-import` disables - actually, they needed ... solving!
It turns out the _module-level_ `disable=cyclic-import` at `qiskit/circuit/quantumcircuit.py` and at `qiskit/pulse/schedule.py` were obscuring a number of import cycles inadvertently.  A `disable` at a wide scope prevents finer-level warnings to be raised, and that is the reason why we recommend being mindful when using `pylint: disable` in general (and in particular with "dangerous" ignores): it should not be used as a systematic way of appeasing the linter but in a controlled way and ideally in the smallest scope possible, in order to help the team and keep maintainability and good practices at a high level.
A summary of the changes:
* …

Fix cycles in several modules

---

Makefile

During #2211, the invocation of `make lint` was changed to parallelized execution via `-j 2` for a (reasonable!) performance gain during the travis linting job. However, as @levbishop noted in https://github.com/Qiskit/qiskit-terra/pull/2400#issuecomment-491507733 and inferred [from the docs](https://pylint.readthedocs.io/en/latest/user_guide/run.html#parallel-execution) and from usage, there are some limitations when running pylint in parallel mode - in practice, it prevents some checks to be performed, such as the `cyclic-import`, which might obscure problems in the codebase if we rely solely on the paralellized execution.
This PR proposes reverting back to the non-parallel behaviour, with the thinking that the ` Lint and pure python test` would _probably_ still be dominated by the 3.5 …

Revert pylint execution to non-parallel behaviour

---

.travis.yml
appveyor.yml

In using a very similar ci wheel build automation setup in
[mtreinish/retworkx](https://github.com/mtreinish/retworkx) the linux ci failed to upload the built wheels on the
0.0.2 release because the system install version of six was too old and
pip's lack of a dep solver failed to upgrade that. [1] This commit address
this so it's not an issue when we push a bugfix release on the stable
branch by making twine install a separate command with -U to avoid this
in all 3 ci envs.
[1] https://travis-ci.com/mtreinish/retworkx/jobs/199756375#L1116
This is being pushed to the stable branch since it effects CI setup and doesn't apply to master yet (although #2292 will address it on master).

[Stable] Use pip install -U when installing twine

---

qiskit/dagcircuit/dagnode.py
qiskit/providers/models/pulsedefaults.py
qiskit/qobj/converters/__init__.py
qiskit/qobj/converters/lo_config.py
qiskit/qobj/converters/pulse_instruction.py
qiskit/qobj/models/__init__.py
qiskit/qobj/models/base.py
qiskit/qobj/models/pulse.py
qiskit/qobj/models/qasm.py
qiskit/transpiler/passes/mapping/enlarge_with_ancilla.py
qiskit/transpiler/passes/mapping/full_ancilla_allocation.py
qiskit/transpiler/passes/mapping/legacy_swap.py
qiskit/transpiler/passes/mapping/noise_adaptive_layout.py
qiskit/transpiler/preset_passmanagers/__init__.py
qiskit/transpiler/preset_passmanagers/default.py
qiskit/validation/fields/custom.py
qiskit/validation/jsonschema/__init__.py
qiskit/visualization/utils.py

Update license header in several modules:
* qiskit/dagcircuit
* qiskit/providers
* qiskit/qobj
* qiskit/transpiler
* qiskit/validation
* qiskit/visualization
From https://github.com/Qiskit/qiskit-terra/issues/2232#issuecomment-492610262, it seems the old copyright header managed to find its way through.
This PR is the first of a series of PRs that attempt to find the last remaining usages of the old headers (by grepping for ".py files that contain a specific line that was present on the old header", and after that for ".py files that do not contain `LICENSE.txt` in them"). They were split into several PRs for easier reviewing and reducing the risk of conflicts (mostly, `pulse` and `quantuminfo` vs "rest of modules", and `qiskit` vs `test`).

Update license header in several modules, 1

---

examples/python/commutation_relation.py
examples/python/hello_quantum.py
examples/python/load_qasm.py
qiskit/tools/qi/__init__.py
test/python/validation/__init__.py

_Final_ PR for the license updates round - this one is a bit different than the previous ones, as instead of replacing, it adds the license header to some `.py` files that seemed to be missing it:
* examples/python
* qiskit/tools/qi
* test/python/validation
#2423 , #2232

Add license header to several modules

---

qiskit/visualization/matplotlib.py

Fixes #2422 
This simply sets the style to be `DefaultStyle()` before it is then updated with any parameters given by the user. This needs to be done otherwise it attempts to update the style dict before it has been initialised.

Fixed mpl style by adding in the default style dict

---

qiskit/providers/models/backendconfiguration.py
qiskit/test/mock.py

This PR sets `rep_times` in the pulse backend configuration model to `Integer` rather than `Float` to be in line with the specification.
Closes #2409.

make rep_times an integer and not a float

---

qiskit/qobj/models/pulse.py
test/python/qobj/test_qobj.py

This PR rearranges the order in which `ByType` is applied in the `PulseQobInstruction` schema. As String was first in the list, floats were being converted to a string when `as_dict` was called. A set of tests have also been added converted from marshmallow models to dicts. 
The alternative to the approach in this PR is to create a new type of `CmdDefPulseQobjInstruction` that inherits from `PulseQobjInstruction`. This would allow `PulseQobjInstruction` to not accept a string as a valid option. See [this branch](https://github.com/taalexander/qiskit-terra/tree/issue-2411-framechange-instruction-as-dict-new-model) for the implementation.
Closes #2411.

Framechange instruction as_dict bug

---

MANIFEST.in

This commit fixes an issue with our published sdists. We are not
including the cython source files in the sdist. While the generated cpp
files get included the pyx files are required because we unconditionally
call cythonize in the setup.py. This causes building from sdist to fail
because it can't find the required files.
Fixes Qiskit/qiskit#278

Add cython files to manifest to enable sdist compilation

---

qiskit/visualization/qcstyle.py

In #2344 we made the default mpl style have colored gates. However in
that change we incorrectly reset the gate colors to white when a style
dict was passed in. This was likely just a copy and paste error, because
the black and white style class did the same thing. This commit fixes
this by removing that and letting the default colors be used when a
style dict is used.

Fix color reset on use of style dict

---

qiskit/qobj/models/pulse.py
test/python/qobj/test_qobj.py

This PR rearranges the order in which `ByType` is applied in the `PulseQobInstruction` schema. As String was first in the list, floats were being converted to a string when `as_dict` was called. A set of tests have also been added converted from marshmallow models to dicts. 
The alternative to the approach in this PR is to create a new type of `CmdDefPulseQobjInstruction` that inherits from `PulseQobjInstruction`. This would allow `PulseQobjInstruction` to not accept a string as a valid option. See [this branch](https://github.com/taalexander/qiskit-terra/tree/issue-2411-framechange-instruction-as-dict-new-model) for the implementation.
Backport of #2413.

[Stable] Framechange instruction as_dict bug

---

qiskit/providers/models/backendconfiguration.py
qiskit/test/mock.py

This PR sets `rep_times` in the pulse backend configuration model to `Integer` rather than `Float` to be in line with the specification.
Backport of #2416.

[Stable] make rep_times an integer and not a float

---

qiskit/visualization/matplotlib.py
qiskit/visualization/qcstyle.py

This commit addresses some of the style issues with the mpl drawer
outlined in #2319. There are 5 small style issues addressed by this
commit. The first is the subtext for parameters are now placed in
brackets. Secondly the label for the id gates is changed to have a
leading capital letter and read 'Id'. Then the output for the initialize
instruction is change to read '|psi>' instead of initialize and the
vector being used is printed. The unitary gate's label is also changed
to read 'U'. However, unlike the initialize instruction, the unitary
does not print the unitary matrix being used. This is because of spacing
concerns since the unitaries are typically going to be much larger (being
a square matrix). However, this may be addressed in a future commit. The
last style issue addressed by …

Improve style for Matplotlib circuit drawer

---

qiskit/pulse/commands/frame_change.py
qiskit/qobj/models/pulse.py
test/python/pulse/test_commands.py
test/python/qobj/test_qobj.py

This PR adds casting of the framechange instruction to a phase.
This is required because the marshmallow schema will error out if the phase is passed as an integer. The typical edge case for this is if the user passes in a framechange of `0`.
Backport of #2432.

[Stable] Add framechange phase casting to float

---

MANIFEST.in

This commit fixes an issue with our published sdists. We are not
including the cython source files in the sdist. While the generated cpp
files get included the pyx files are required because we unconditionally
call cythonize in the setup.py. This causes building from sdist to fail
because it can't find the required files.
Fixes Qiskit/qiskit#278
(cherry picked from commit fdc59cfacb331fa4dac79e46adb3adc0bf094238)
Backported from #2436

[Stable] Add cython files to manifest to enable sdist compilation

---

qiskit/qobj/converters/pulse_instruction.py
test/python/qobj/test_pulse_converter.py

…tion for all involved qubits, rather than one per each qubit.
Fixes #2471 
Join all converted acquire instructions (in qiskit/qobj/converters/pulse_instruction.py) into a single acquire instruction.

For each Acquire, create only one AcquireInstruction with all qubits

---

qiskit/qobj/converters/pulse_instruction.py
test/python/qobj/test_pulse_converter.py

Fixes #2471
Join all converted acquire instructions (in qiskit/qobj/converters/pulse_instruction.py) into a single acquire instruction.
Backport of #2484.

[Stable] For each Acquire, create only one AcquireInstruction with all qubits

---

qiskit/visualization/utils.py

In #2451 we made both pillow and pylatexenc optional requirements just
for users who wanted to use latex visualizations. However in that patch
we missed a place where pillow was being imported unconditionally at the
module level. This causes an exception to be raised whenever someone
import's qiskit without pillow installed. This commit fixes this by
handling the ImportError raised by a missing pillow and raising a more
detailed ImportError if/when a user tries to use the sole function that
needs pillow.

Fix unconditional pillow import

---

qiskit/visualization/pass_manager_visualization.py

This commit fixes the graphviz check in the pass manager visualization
added recently in #2445. The check was added to determine if the dot
command was in the default PATH by trying to subprocess out and run
'dot -V' however the way in which subprocess was called results in both
the dot version string and a blank line being printed if graphviz is
actually installed. This happens on import time which we definitely
don't want to do (and breaks test discovery in stestr). This commit addresses
that by updating the subprocess call to redirect stdout and stderr, but it also
loosens the exception catch to never raise, if anything fails during the attempt
to run dot we should not treat that as fatal, instead just say we don't have
graphviz.

Fix graphviz check in pass manager visualization

---

qiskit/transpiler/preset_passmanagers/level0.py
test/python/transpiler/test_preset_passmanagers.py

The following code was failing because the same reason as https://github.com/Qiskit/qiskit-terra/issues/2421 in level 0.
```
backend = BasicAer.get_backend('qasm_simulator')
qr = QuantumRegister(3, 'q')
cr = ClassicalRegister(3, 'c')
circuit = QuantumCircuit(qr, cr, name='a_cx_to_map')
circuit.h(qr[1])
circuit.cx(qr[1], qr[2])
circuit.measure(qr, cr)
job_device = execute(circuit, backend, optimization_level=0)
```
The fixed is this PR.

optimization_level=0 without coupling map

---

qiskit/visualization/pulse_visualization.py

We need to close the figure before return it.

Fix issue #2449 - Pulse figure not closed before return

---

qiskit/transpiler/preset_passmanagers/level3.py

Stable backport of #2434 -- this is needed to make #2509 work on stable. Both PRs are bug fixes. One fixes level0 and one fixes level3.

[Stable] Remove call to CXDirection if necessary

---

qiskit/validation/jsonschema/schema_validation.py

This knocks off about 50s from running the test suite on my laptop and should give a huge speed improvement on use cases where there a large number of small circuits, where validation takes the majority of the time. Previously about 75% of the cost of validation was checking the schema against it's meta schema. Since we cache validators, this does not need to be done on every use. This patch changes the validation against meta schema to be a one-time deal at load time.
Possibly we could go further and change `check_schema` to default to `False`. This would speed up `import qiskit` by a tiny amount and any errors should still be caught by the `test_schemas_are_valid` testcase.

Do schema validation once at validator init, rather than at every use

---

qiskit/test/mock.py

This PR extends the `FakeBackend`s in `qiskit/test/mock.py` with `FakePoughkeepsie`, since sometimes we receive issues in this backend.

FakePoughkeepsie in qiskit/test/mock.py

---

qiskit/visualization/latex.py

As part of the large refactor adding column justification to the latex
drawer in #1977 the function used to determine the image depth was
greatly simplified since most of the work was offset to the dag
processing prior to the latex drawer. However, one piece of critical
code was removed inadvertently which was used for determining the row
spacing. This section looked at every operation and determined if we
should increase or decrease the row spacing depending on what time of
operations were being drawn. The result of this check end up directly
setting a value in the output latex call to \Qcircuit. Without this code
the calculations which are done to determine the output page size are
off by the spacing factor and result in the output circuit exceeding the
single page size. This causes a …

[Stable] Determine row spacing properly

---

CHANGELOG.rst
qiskit/quantum_info/synthesis/two_qubit_decompose.py
test/python/quantum_info/test_synthesis.py

* Change test_synthesis to use operator.compose in most cases instead of UnitarySimulatorPy (gives around a 9x speedup for the tests)
* Fix TwoQubitBasisDecomposer to correctly decompose into non-CNOT basis (and mark relevant test as expected to pass)

Speed up test_synthesis and fix non-CNOT decompose

---

CHANGELOG.rst
qiskit/qobj/utils.py
qiskit/validation/base.py
qiskit/validation/fields/custom.py
test/python/circuit/test_unitary.py
test/python/qobj/test_qobj.py

Fixes #2487 
deprecate qobj.as_dict and use qobj.to_dict

deprecate qobj.as_dict

---

examples/python/ghz.py
examples/python/hello_quantum.py
examples/python/load_qasm.py
examples/python/qft.py
examples/python/using_qiskit_terra_level_0.py
examples/python/using_qiskit_terra_level_1.py
examples/python/using_qiskit_terra_level_2.py

For some examples, the whole logic is encapsulated in a try/except block. I don't think this is useful. Those try/excepts that are targeting user error are useful in examples (for example try loading IBMQ credentials, and if unsuccessful provide a helpful error message).
But putting the whole example in try/except just makes it hard to debug when things go wrong, as it suppresses the traceback (for example the error in https://github.com/Qiskit/qiskit-terra/issues/2498#issuecomment-497979061). Those errors are usually our errors, and not the user.

remove try/except in examples

---

qiskit/test/mock.py

Fixes generation of 2Q gates definitions on FakeBackends to reference correct qubits.
Fixes the following bug:
```
>>> qc = qk.QuantumCircuit(3)
>>> qc.cx(0,1)
<qiskit.circuit.instructionset.InstructionSet object at 0x1334ca048>
>>> qc.cx(1,2)
<qiskit.circuit.instructionset.InstructionSet object at 0x1334ca128>
>>> qk.transpile(qc, backend=FakeTenerife())
<qiskit.circuit.quantumcircuit.QuantumCircuit object at 0x13358fbe0>
>>> qk.transpile(qc, backend=FakeTenerife(), optimization_level=2)
File "<stdin>", line 1, in <module>
File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/compiler/transpile.py", line 147, in transpile
circuits = parallel_map(_transpile_circuit, list(zip(circuits, transpile_configs)))
File …
```

Fix labeling of 2Q gate qubits on FakeBackends.

---

qiskit/providers/basicaer/qasm_simulator.py
qiskit/providers/basicaer/unitary_simulator.py
qiskit/validation/base.py

Fixes #2566 
Master has some `as_dict` calls that were deprecated in #2556

removing deprecated as_dict

---

CHANGELOG.rst
qiskit/transpiler/passmanager.py
test/python/transpiler/test_pass_scheduler.py

Simplify pass manager by removing 2 unused options. Also a bit of docstring cleanup.

remove ignore_preserves and ignore_requires from PassManager

---

test/python/transpiler/test_layout.py

Related to #2576.
In an effort to reduce the number of warnings when running tests, this PR silences some specific `DeprecationWarnings` during `LayoutDeprecatedTest` (with the assumption that they are fully in control, due to the class' purpose). The end goal is being able to detect _unintended_ warnings (deprecated and otherwise) in the tests a bit more easily, cleaning up a bit the test output in the process.

Disable warnings output for LayoutDeprecatedTest

---

qiskit/tools/monitor/backend_overview.py

Fixes #2604, fixes #2602 
The backend monitor code had a bug in finding multi-qubit gates. It assumed that the gate set only has u1,u2,u3,cx. The addition of `id` to the Tokyo device breaks the assumption and caused failures on the master branch. This fixes that.

fix backend monitor multi-qubits

---

qiskit/assembler/disassemble.py
test/python/compiler/test_disassembler.py

This commit fixes a longstanding feature gap in the
disassembler/qobj_to_circuits converter with conditional instructions.
Previously the disassembler was not able to handle these correctly and
any conditionals in the qobj would just be silently ignored. This
corrects this by checking for the injected bfunc and mapping the bitmask
and value back to registers so the conditional can be applied to
whatever the next instruction is.
Fixes #2197

Add support for conditionals to disassembler

---

.travis.yml

This commit adds coverage collection to the CI environment. It adds
reporting back to coveralls for the python 3.6 job. So when that job
finishes executing it will send the collected coverage data to coveralls
so we can track out unit test coverage.
Fixes #771

Add coverage collection to CI

---

CHANGELOG.md

After #2359, some bits of the changelog and other documents are not displayed properly, most likely due to the automated tool not being able to cope with some of our previous syntax. This PR attempts to get it back to a readable state:
* fixing the:
> ... [blah]{.title-ref} ...
entries that were present in [a number of places](https://github.com/Qiskit/qiskit-terra/blob/14f9697367e06f4b8397da9142e46e1f97c9e891/CHANGELOG.md#changed-1)
* fixing [blocks with nested indentation](https://github.com/Qiskit/qiskit-terra/blob/14f9697367e06f4b8397da9142e46e1f97c9e891/CHANGELOG.md#deprecated-2)
Additionally:
* updates the links to reference links at the bottom of the document instead of inline
* standardizes the headers, using simple pound-style headers instead of underline

Fix CHANGELOG display errors

---

qiskit/pulse/timeslots.py
qiskit/tools/jupyter/backend_monitor.py
test/python/pulse/test_timeslots.py

Fixes #2596. 
Within `TimeslotCollections.is_mergeable_with()`, checks if each `slot.channel` already exists in `self._table`. If the `channel` does not exist, it skips the rest of the check and moves on to the next `timeslot` in the `TimeslotCollection`. If the `channel` does exist, it continues to the `Interval.has_overlap()` function.

Ensure is_mergeable_with does not mutate TimeslotCollection

---

qiskit/tools/jupyter/__init__.py
qiskit/tools/jupyter/backend_monitor.py

This PR deprecates the `qiskit_backend_monitor` Jupyter magic in favor of an HTML repr callback that is added in the Jupyter kernel for `IBMQbackend` class objects.
Additionally, jobs data is now loaded only when the jobs tab is selected to decrease initial load time.

Backend monitor as backend HTML repr in Jupyter 

---

.travis.yml

This commit adds an additional output stage to the python 3.6 job, which
is used for collecting coverage, that runs the diff-cover tool to show
which parts of the diff have test coverage. This is useful for both
reviewers and the commit author to see if the changes being made in a PR
are actually being exercised by the testing we run.

Add diff-cover output when coverage is collected

---

qiskit/pulse/timeslots.py
test/python/pulse/test_timeslots.py

Within TimeslotCollections.is_mergeable_with(), checks if each slot.channel already exists in self._table. If the channel does not exist, it skips the rest of the check and moves on to the next timeslot in the TimeslotCollection. If the channel does exist, it continues to the Interval.has_overlap() function.
Backport of #2626

[Stable] Backport Ensure is_mergeable_with does not mutate TimeslotCollection

---

.travis.yml
appveyor.yml

The current wheel build automation uploads the wheel files to
test.pypi.org. The idea behind this was to enable manual verification of
the built wheels prior to pushing the releases for real. However, this
just adds another manual process to the release process and increases
the chance of something going wrong. There also isn't any manual
validation that happens for most of the wheels. When it is done, it
provides no more than what the build automation does already
(running an example script). To simplify the release process and reduce
the chances for errors involved with downloading and re-uploading
this commit switches the build automation to directly upload to
pypi.org. The release workflow with this is now just push a tag for the
release, then build and upload a sdist to pypi. …

[Stable] Upload wheels to pypi.org instead of test.pypi.org

---

.travis.yml
requirements-dev.txt
test/randomized/test_transpiler_equivalence.py

The randomized tests have been consistently timing out when run on merges to master (even though they consistently complete on PR branches). To better understand why:
- Increase the `travis_wait` time to 45 minutes
- Tell hypothesis to stop at the first found error, and not try to search further
- Cut the random circuit count from 100 to 50.
These can be revised when we better understand why the master jobs are running so long.

Reduce randomize testing timeouts in CI

---

qiskit/version.py

This commit changes the behavior slightly for the
qiskit.__qiskit_version__ attribute. Previously we relied solely on pip
to extract the version information for installed packages. However, in
some situtations this can get out of sync with the actual version of the
package. To address this potential issue this commit adds a first round
check to use the attributes from the installed packages. If it doesn't
work then we look at the pip data as a fallback (because we have to use
pip anyway for the meta-package which doesn't contain any python code).
Fixes #2494

Default to __version__ attribute for __qiskit_version__

---

qiskit/version.py

As part of the `qiskit.__qiskit_version__` attribute we have to call pip
to check for the meta-package version (since it doesn't contain any
python code). However, when doing this there was no error handling in
case pip failed for any reason. This is an issue because the version
discovery code runs on import, so if pip fails for any reason, this
becomes fatal and makes all of qiskit unusable. Since versions queried
via pip aren't critical to the operation this commit adds the necessary
error handling to the pip call. If pip fails for any reason we catch it
and just move on.
Fixes #2660

Make pip error for version discovery non-fatal

---

CHANGELOG.md
qiskit/extensions/standard/iden.py
qiskit/transpiler/passes/optimize_1q_gates.py
test/python/circuit/test_diag.py
test/python/circuit/test_isometry.py
test/python/circuit/test_squ.py
test/python/circuit/test_ucg.py
test/python/circuit/test_ucx_y_z.py
test/python/transpiler/test_optimize_1q_gates.py
test/python/transpiler/test_unroller.py

Fixes #2373 
Identity gates are now like explicit 'wait' commands. They will never be removed. Even in the absence of barriers:
i.e. this circuit will stay like this even at high optimization levels, and will mean "excite qubit, then wait for 11 single-qubit-gate cycles.

never remove id gates

---

CHANGELOG.md
qiskit/extensions/standard/u0.py

The `u0` gate was used to insert variable amounts of noise. From now on, the `id` gate is the only gate used for this purpose that allows inserting variable amounts of delay (as integer multiples of a single-qubit-gate delay). So insert an `id` raised to the power of 5 to force 5 units of delay. For more fine-grained control over delays, use open pulse.

deprecate u0 gate

---

CHANGELOG.md
qiskit/transpiler/passes/commutation_analysis.py
test/python/transpiler/test_commutative_cancellation.py

Fixes #2667, Fixes #2668 
Conditional gates must be excluded when computing commutation relations.

do not commute conditional gates

---

CHANGELOG.md
qiskit/providers/basicaer/qasm_simulator.py
qiskit/providers/basicaer/statevector_simulator.py
qiskit/providers/basicaer/unitary_simulator.py
test/python/basicaer/test_qasm_simulator.py
test/python/basicaer/test_statevector_simulator.py
test/python/basicaer/test_unitary_simulator.py

Adds arbitrary 'unitary' gates to BasicAer simulator basis gates.
Closes #2341

add 'unitary' to BasicAer simulators

---

qiskit/visualization/text.py

Small tweak to avoid a bunch of:
```
qiskit-sdk-py/qiskit/visualization/text.py:962: DeprecationWarning: Accessing a bit register by bit[0] or its index by bit[1] is deprecated. Go for bit.register and bit.index.
clbit = [bit for bit in self.cregs if bit[0] == creg]
```
when running the tests.

Fix text drawer DeprecationWarning

---

qiskit/test/base.py

In preparation for the new provider release, remove the `IBMQ` "resetting" during `QiskitTestCase.tearDown()`. This was included by the time the provider was part of `terra`, and relevant for tests that needed a "fresh" provider (as `qiskit.IBMQ` is a global object) - as the logic was moved to the provider (and the private `._accounts()` is to be removed in the new release), let's remove it from the base testcase as well to ensure a smoother transition.
Currently no tests in terra depend on a fresh provider (`IBMQ` is used mainly by `test_backend_monitor` and others) - in case it is still needed, each testcase or test should be responsible of cleaning up as needed.

Remove IBMQ resetting from QiskitTestCase

---

CHANGELOG.md
qiskit/providers/basicaer/qasm_simulator.py
test/python/basicaer/test_qasm_simulator.py

Fixes bug where measure sampling was incorrectly done if the same qubit was measured more than once.
Fixes #2664

Fix qasm_simulator measure sampling bug

---

CHANGELOG.md
qiskit/pulse/schedule.py
test/python/pulse/test_schedule.py

Closes https://github.com/Qiskit/qiskit-terra/issues/2742, and ~possibly~ closes https://github.com/Qiskit/qiskit-terra/issues/2741.
I don't have a concise tests of this to add yet, so this is just a draft for now until I can find some.

Fixed multi parameter bug

---

qiskit/quantum_info/operators/channel/superop.py
qiskit/quantum_info/operators/operator.py
test/python/quantum_info/operators/channel/test_superop.py
test/python/quantum_info/operators/test_operator.py

Fixes a bug in converting circuits/instructions to operator objects that wasn't fixed by #2723. 
This bug is where 2-qubit gates without an explicit matrix def (like cu1, cu3) are decomposed into gates was raising an error that they were being applied to incorrect sized qargs.

Fix bug in circuit to Operator/SuperOp conversion

---

.travis.yml

As part of streamlining the release process, this commit adds automation
for publishing an sdist to pypi. This was one of the last manual steps
that was part of the release process. Now there are no manual steps left
after pushing a git tag. There are still some optimizations that need to
be done prior to pushing a tag, but that is more of a process problem
rather than something that can directly be fixed by automation.

Add automation for sdist pypi upload

---

test/randomized/test_transpiler_equivalence.py

since #2672, the default optimization level is just level 1, so there is no need to test `optimization_level=None` anymore.

remove optimization_level=None from randomized tests

---

qiskit/circuit/instruction.py
test/python/circuit/test_instructions.py

Fixes #2751 
Modifies `Instruction.__eq__` to first try the default `__eq__` of the parameter type, and fall back to checking for either array-like or float-like equality if that fails. 
We should at some point rethink how we organize comparison of instruction parameters by the possible types (first check that parameter types align, then use the right type-specific equality test), but this should be sufficient to unblock https://github.com/Qiskit/qiskit-aer/pull/239 .

Support equality checks for Instructions with ndarray parameters.

---

CHANGELOG.md
qiskit/providers/basicaer/qasm_simulator.py
test/python/basicaer/test_qasm_simulator.py

Fixes #2744. Adds some additional tests for BasicAer qasm simulator
Measure sampling was behaving incorrectly if a subset of qubits were measured since it was assuming the position in the measured qubit list was the qubit number.

fix measure sampling bug in BasicAer

---

test/python/tools/monitor/test_backend_monitor.py

Sort of follow-up from the changes at #2828 - explicitly disable the provider account on the backend monitor tests in order to advance in getting `master` passing, as being a global variable the state is shared between tests.

Add IBMQ cleanup to backend monitor test

---

qiskit/visualization/matplotlib.py

This commit handles fixes a spacing issue when drawing a unitary gate
with the matplotlib circuit drawer backend. Previously it was assuming
the gate was as wide as the operation name which was "unitary" and was
spacing based on that. However the gate is drawn with the name "u" and
is using a standard wide gate box (which has a layer width of 2). This
commit fixes the issue by treating the unitary gate as a standard wide
gate.
Fixes #2686

Handle unitary width issue in matplotlib drawer

---

test/randomized/__init__.py
test/randomized/test_transpiler_equivalence.py

#2892 removed an import that was needed by #2783 . This wasn't caught by pylint because `test/randomized` had no `__init__.py`. This PR adds the missing import, and the init file.

Add __init__ to test/randomized directory and fix missing import

---

azure-pipelines.yml
test/python/visualization/test_circuit_matplotlib_drawer.py

The azure pipelines commands were previously using the script directive
which on windows uses cmd.exe to run commands. The return code for the
step process only returns non-zero and exits if the last command in the
script returns non-zero, it will continue running if an intermediate
command fails. This can lead to hard to parse errors because something
failed earlier in the pipeline and we don't catch it until later. For
example pip install stestr failing because of a network issues and then
we get a command not found error when we go to run tests. This commit
fixes this issue by switching all the scripts to explicitly use bash
and then using 'set -e' to set errexit to make sure any failing
command causes the job to fail there.
Related to #2879

Make azure pipeline steps fail on intermediate commands

---

azure-pipelines.yml

In #2905 we switched the stestr version used for the macOS jobs to use
master from git instead of the release at the time. This was to mostly
pull in some result analysis fixes that were added to be able to debug
segfaults in the macOS jobs. While these fixes weren't 100% necessary it
was useful to avoid secondary stack traces in stestr when the test
runner segfaulted. However, now stestr 2.5.0 has been released which
includes all of these fixes. This commit removes this so we switch macOS
back to following released stestr.

Remove git stestr usage from macOS jobs

---

CHANGELOG.md
qiskit/quantum_info/__init__.py
qiskit/quantum_info/operators/operator.py
qiskit/quantum_info/states/statevector.py
test/python/quantum_info/operators/test_operator.py
test/python/quantum_info/states/test_statevector.py

* Adds `equiv` method to `Operator` class that returns `True` if two operators are equivalent up to global phase.
* Adds `equiv` method to `Statevector` class that returns `True` if two statevectors are equivalent up to global phase.
* Adds equiv tests
* Adds `Statevector` and `DensityMatrix` classes to `quantum_info.__init__.py`

Add equiv method to Operator and Statevector classes

---

.travis.yml

This commit adds the isometry benchmarks to the set of benchmarks we run
in CI. This shouldn't significant additional time to the job run, but
will add a useful benchmarks for tracking the performance of a patch.
Most interestingly it will add a benchmark that doesn't measure time but
instead compares the CNOT count output from the transpiler. Which makes
a lot of sense in this CI job because it won't be bound to the
variable performance of the cloud guests that travis runs it's jobs on.

Add isometry benchmarks to travis ci benchmark job

---

qiskit/assembler/assemble_schedules.py
test/python/compiler/test_assembler.py

This PR fixes a bug creating qobj with wrong `memory_slots`. Also tests are added.
fix #2913

Fix memory_slots number bug in pulse assembler

---

qiskit/visualization/matplotlib.py

Fixes #2953 
This was occurring when there were multiple barriers in a layer, which can happen when there are multiple registers in a circuit. Previously, if a barrier was encountered and not plotted, the count of where to put the next gate would be decremented. However this would happen for every barrier hit, so if there were 2 barriers in the layer it would be decremented twice and cause the overlap seen in #2953.
Fixed by calculating when to move the barrier better. Only decrementing by 1 when everything in the layer hasn't been plotted.
Part of the updated circuit :

Barriers plot correctly over multiple registers in mpl

---

qiskit/transpiler/passes/collect_2q_blocks.py
test/python/transpiler/test_collect_2q_blocks.py

As revealed in the [random testing](https://travis-ci.com/Qiskit/qiskit-terra/jobs/223620181#L4545) there was a niche bug in Collect2QBlocks that lead to blocks of 3 qubits being collected. This occured because the predeccessors/successors of the nodes were added using the calls `predecessors()` and `successors()` rather than `quantum_predecessors()` and `quantum_successors()`. This meant that if there was a pred/succ node that shared the same classical register, but was not a `cx` node it could [be added](https://github.com/Qiskit/qiskit-terra/blob/3c1ad77cfecc1485179a42117d219249106bbaca/qiskit/transpiler/passes/collect_2q_blocks.py#L70) despite potentially not sharing the same qubits as the node currently being looked at.
As it is blocks of quantum gates we are looking for, it makes …

Fixed block collection with classical conditions in Collect2QBlocks

---

qiskit/visualization/state_visualization.py

Seaborn is an optional visualization dependency only ever used if we
have matplotlib installed and support using visualizations. However, we
were previously unconditionally importing it when we load the
qiskit.visualization.state_visualization module. This leads to an error
if you have not installed seaborn even though this is a supported state.
This commit corrects it by moving the seaborn import into the
conditional section of imports after we've verified that matplotlib is
installed and the installation supports running visualization.

Make seaborn import work if it's not installed

---

qiskit/dagcircuit/dagcircuit.py

With the introduction of the Bit classes in #2414 the arguments for
many of the methods in the DAGCircuit class, which often deal with
individual bits, were changed to deal with these new classes instead of
tuples. However, in that process a couple of docstrings were missed and
not updated to reflect the expected types. This commit corrects the
oversight and updates the docstrings for those cases. This also updates
several cases of using the deprecated tuple based bit access in exception
messages, which would generate a warning in addition to the expected
exception.
Fixes #2820

Update dagcircuit docstrings for bit class arguments

---

qiskit/__init__.py

Recently we started emitting on failed imports for IBMQ and Aer in #2842
to tell users if they have a misconfigured or missing qiskit-aer or
qiskit-ibmq-provider package. However, in that PR we set the warning
class to ImportWarning which is ignored by default in python. This
defeats the whole purpose of emitting the warning because no one will
see it unless they explicit enable printing ImportWarnings to stderr.
ImportWarning was chosen because it seems to map the best to what we're
warning about and provides a unique enough class that is easy to filter
for those users who do not wish to install either Aer or IBMQ. This
commit changes the warning class to RuntimeWarning so that it will show
by default but still meet the criteria that we original chose
ImportWarning based on.

Change warning class for Aer and IBMQ warning

---

qiskit/visualization/latex.py

Right now the latex drawer has a few instances of deprecated bit access
assuming a tuple right now. This results in a deprecation warning when
calling the latex drawer. To avoid emitting a deprecation warning
internally from qiskit this commit fixes this and updates the access
to use the bit class attributes.

Adjust deprecated bit access in latex drawer

---

azure-pipelines.yml

In #2905 we switched the macOS jobs only use a concurrency of 2 instead
of nprocs for running tests. This was done in an attempt to debug a
segfault (which wasn't easy to diagnose from CI). But as #2793 has shown
the issue isn't the concurrency but instead running on macOS 10.14.
Since we also downgraded the macOS version used for these jobs we
shouldn't need to limit the concurrency anymore and increase it back to
4 workers. This should hopefully improve the test runtime on macOS jobs
slightly since they report having 4 CPUs available.

Use nprocs concurrency for test running on macOS

---

CHANGELOG.md
qiskit/circuit/parameter.py
test/python/circuit/test_parameters.py

Fixes #2429
Fixes #2864
`Parameter`s were defined such that they would only ever `__eq__ self`. That way, if a user defined a `Parameter('theta')` and wanted to compose in a subcircuit defined elsewhere which contained a different `Parameter('theta')`, we would be able to detect that the parameter names overlapped and raise an error.
However, if a user sent a `Parameter` to a different python instance though (say through `multiprocessing.Pool` or `qiskit.tools.parallel_map`), it would be instantiated as a different python object and so no longer be considered equal to the original parameter.
This PR changes `Parameter` to instead generate a random UUID on instantiation and use that for equality testing. Unlike `id(self)`, `self._uuid` will be preserved across pickling and de-pickling, but …

Change Parameter equality from python id() to internal uuid().

---

appveyor.yml

With the recent instability and unreliability with azure-pipelines
relying on it to build our windows wheels for the upcoming 0.9 release
doesn't seem to be prudent. Especially when considering our ability to
create reliable portable wheels for a windows environment manually
outside of CI is limited (we've had issues trying to do it manually in
the past). This commit adds back our appveyor config for building wheels
which has worked well for past releases. This way even if azure fails
for us we have a fallback available when we push our release tag.

Add appveyor config back for building windows wheels

---

appveyor.yml

The py37 job run in appveyor isn't meant to actually count, it's
there so appveyor won't leave a pending job sitting in the github
checks list while we have it configured as a wheel building backup
for azure, see #2979. Right now this job is failing and leaving a red x on commits
(which is at least as bad as leaving patches status as pending) because
of a new pulse test that is sensitive to subtle floating point type
differences between environments. To avoid the bad optics of a red x on
jobs we don't care about this commit switches to just always return 0 when we
run this job. We only configured to make it easy to ignore and setting the test
script to be always passing means that is unlikely to fail.

Limit the set of tests run in appveyor

---

qiskit/visualization/latex.py

```python
from qiskit.circuit import QuantumCircuit
from qiskit.circuit import QuantumRegister, ClassicalRegister
q = QuantumRegister(4, 'q')
circ1 = QuantumCircuit(q, name='my instruction')
inst = circ1.to_instruction()
circ2 = QuantumCircuit(q, name='circ2')
circ2.append(inst, q[:])
circ2.draw(output='latex')
```
I also removed some DeprecationWarnings.

Latex drawer should allow spaces in custom instruction names

---

qiskit/compiler/assemble.py
qiskit/execute.py

The use of assemble() from the execute function in
https://github.com/Qiskit/qiskit-terra/blame/master/qiskit/execute.py#L218
passes run_config as a named parameter when assemble expects it as
kwargs. This causes it to be packed into a dict with a single run_config
key that is never unpacked.
The fix was to pass run_config, instead of as a named param, as an unpacked dict to assemble as it expects.

Fix passing of kwargs to the compiler assembler

---

qiskit/visualization/text.py
test/python/visualization/test_circuit_text_drawer.py

Fixes #2973
```python
qr4 = QuantumRegister(4)
cr4 = ClassicalRegister(2)
inst = QuantumCircuit(qr4, cr4, name='name').to_instruction()
qr6 = QuantumRegister(6, 'q')
cr6 = ClassicalRegister(6, 'c')
circuit = QuantumCircuit(qr6, cr6)
circuit.append(inst, qr6[1:5], cr6[1:3])
```
```
q_0: |0>─────────
┌───────┐
q_1: |0>┤0      ├
│       │
q_2: |0>┤1      ├
│       │
q_3: |0>┤2      ├
│       │
q_4: |0>┤3      ├
│  name │
q_5: |0>┤       ├
│       │
c_0: 0 ╡       ╞
│       │
c_1: 0 ╡0      ╞
│       │
c_2: 0 ╡1      ╞
└───────┘
c_3: 0 ═════════
c_4: 0 ═════════
c_5: 0 ═════════
```

Text drawer supports composite gates with both quantum and classical wires

---

CHANGELOG.md
qiskit/transpiler/passmanager.py
qiskit/visualization/circuit_visualization.py
qiskit/visualization/pass_manager_visualization.py

`PassManager.draw()` requires `filename` parameter and it was kind of inconvenient in the context of jupyter notebooks.
```
pass_manager.draw("temp.png")
from IPython.display import Image
Image("temp.png")
```
This PR allows `PassManager.draw()` to dump the picture directly as an image in the notebook, making the `filename` parameter optional, inline with the circuit drawers.

Passmanager.draw() in Jupyter notebooks 

---

qiskit/visualization/pulse/matplotlib.py

fix #2984 
Maximum time duration (`.tf`) and waveform amplitude (`v_max`) are overwritten by 1 when schedule's waveform is empty. Just in case a schedule contains only FCs.

Allow for visualizing empty waveform

---

CHANGELOG.md
qiskit/dagcircuit/dagcircuit.py

Since we have circuit.draw() and passmanager.draw() and schedule.draw()...
If pydot or graphviz are not installed, it will raise an error.

add dag.draw() method

---

qiskit/compiler/transpile.py
releasenotes/notes/0.9/new-features-0.9-159645f977a139f7.yaml

When the log_level parameter is set on the `transpile()` call we use that
to set the level for all the transpiler functions called. To do this we
get an instance of the pass manager logger and set the level of logs
we want. However, this functionality is redundant because python stdlib
logging already exposes, users just need to call
`logging.getLoggger('qiskit.transpiler').setLevel()`. Since the `transpile()`
function is widely used and has a stable interface the cost for removing
a potentially unnecessary argument is high, so to err on the side of caution
this removes the kwarg for the 0.9 release. If we decide that it's needed in
a future release we can always add it back when we find the need.
Fixes #3010

Remove log_level kwarg from transpile()

---

releasenotes/notes/0.9/error_map-plot-5d995d0fd67fbe35.yaml

In #2965 we added a new visualization function, plot_error_map(), but
that PR was original proposed prior to our adoption of reno to handle
release notes. Therefore it was missing the corresponding release
documentation for the new feature. This commit address that oversignt
and adds a release note for this new feature.

Add release note for plot_error_map

---

qiskit/visualization/pass_manager_visualization.py
test/python/visualization/test_pass_manager_drawer.py

I accidentally introduced this bug in PR #3005. When `passmanager.draw(raw=true)`, a filename needs to be provided and the method returns `None`. This PR handles that situation which was not capture by the CI (see #3023)

if passmanager.draw(raw=true), do not create the png

---

qiskit/transpiler/preset_passmanagers/level3.py

This removes the calls to `CXDirection` pass in O3 passmanager if the coupling map is symmetric.  This reduces the compile time of QV circuits by a factor of two in this mode.

remove cx_direction from O3 if symmetric

---

requirements.txt
setup.py

We have had the jsonschema version capped since it was introduced as a
requirement into terra. There is no clear reason for this and it limits
interoperability with other python packages. Especially because
jsonschema is commonly used library across the python ecosystem. The
version we were capping to was also quite old being release 2.5 years
ago. This commit removes the cap so that people can run terra in
environments where newer jsonschema is required.
(cherry picked from commit e1fc918751462af4a1f9f22a3e084083f4779cf9)
Backported from #3037

[Stable] Remove jsonschema cap (#3037)

---

qiskit/visualization/pass_manager_visualization.py
test/python/visualization/test_pass_manager_drawer.py

Previously the graphivz availablity check was performed at import time.
This meant that everytime anyone imported anything from qiskit.* we'd be
shelling out to try and run 'dot -V' to see if python could find
graphviz in order to run the passmanager drawer. This was based on the
model we used for matplotlib which also does it at import time. However,
unlike matplotlib this isn't a simple python import path check shelling
out and running another program takes a non-negligble amount of time to
any import of qiskit. [1] We shouldn't force this check to run all the
time if graphviz is only needed when running the pass manager
visualizer. This commit address this by switching the graphviz check to
be the first operation that occurs in the pass_manager_drawer() function
instead of at the …

[Stable] Make graphviz availability check at runtime (#3041)

---

azure-pipelines.yml

The python hash seed is used to control the seed for the hash() function
for types covered by hash randomization. If we encounter errors around
ordering for things like iterating over dictionaries to reproduce
failures locally it is useful to know what the hash seed was. However,
to ensure the code is robust we still want to have a random value for
the hash seed to make sure things aren't dependent on a single order.
This commit accomplishes this by explicitly selecting a random number
and setting that to the value of PYTHONHASHSEED. This value is then
printed right before we run the tests. This way if we encounter an issue
around ordering we can try and reproduce it locally.

Set an explicit random hashseed for tests in CI

---

qiskit/tools/jupyter/job_widgets.py

Tried to save space by showing last seven digits only.  Sadly, made life difficult when you needed full job id

display full job ID in job watcher

---

qiskit/transpiler/passes/ms_basis_decomposer.py
qiskit/transpiler/transpile_circuit.py
test/python/compiler/test_transpiler.py

Mølmer-Sørensen basis decomposer
Adds a simple pass to convert a circuit unrolled to U3,CX to Rx, Ry, Rxx.
Modifies default pass_manager selection if user is targeting an ion-trap backend. If the circuit needs to be unrolled (contains gates outside the backend's basis gates), first unroll to U3,CX, then decompose to backend's basis gates.

Add partial transpiler support for targeting ion trap backends.

---

.travis.yml

https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration
Travis CI: The sudo: tag is deprecated on Travis
https://blog.travis-ci.com/2018-11-19-required-linux-infrastructure-migration

Travis CI: The sudo: tag is deprecated on Travis

---

qiskit/circuit/quantumcircuit.py
test/python/circuit/test_circuit_operations.py

Fix a syntax error in QuantumCircuit.mirror.

---

qiskit/visualization/matplotlib.py

If the style property "gatefacecolor" is set to a different value than the default, this color is applied.
Code for testing:
```
%matplotlib inline
from qiskit import QuantumRegister, QuantumCircuit, ClassicalRegister
qr = QuantumRegister(3)
cr = ClassicalRegister(1)
qc1 = QuantumCircuit(qr)
qc1.x(qr[1])
qc1.h(range(3))
qc1.cx(qr[1], qr[2])
qc1.cx(qr[0], qr[1])
style = {'gatefacecolor': '#FF0000'}
f = qc1.draw(output='mpl', style=style)
f
```
Fixes #3106

Fix for #3106 gatefacecolor key on circuit diagrams

---

qiskit/pulse/commands/sample_pulse.py

This PR aims to fix Travis failing on Samplepulse clipping on OsX only.

Pulse clipping fix for Travis Osx

---

qiskit/assembler/assemble_schedules.py

Use `instruction.channels` not `instruction.timeslots.channels`
In progress of refactoring `Timeslots`, thought this would be an easy separate PR. Fewer files changed in the more interesting PR.

Remove superfluous reference to timeslots from assemble_schedules

---

qiskit/visualization/matplotlib.py

* Issue #3106 gatefacecolor key has no effect on circuit diagrams
If the style property "gatefacecolor" is set to a different value than the default, this color is applied.
Fixes #3106
* Solved style problem
space before : eliminated
Backported from #3137 
(cherry picked from commit 531666618f798007fdded883afc6aadbcb5661c9)

[Stable] Fix for #3106 gatefacecolor key on circuit diagrams (#3137)

---

.travis.yml

This commit adds the import benchmark to the travis benchmark job. The
import benchmark simply times how long it takes a fresh python
interpreter to run 'import qiskit'. This benchmark executes very quickly
so it should not add significant time to the benchmark. But it will
provide useful information about the impact of our changes under
development.

Add import benchmark to travis benchmark job

---

qiskit/version.py

This commit speeds up the import time of qiskit by removing the pip call
at run time. This call was overkill and slow, since all we really needed
it for was to get the installed versions of the qiskit meta package. We
were also using as a fallback if element.`__version__` failed, but that
was potentially misleading. This commit replaces the pip subprocess call
with the pkg_resources setuptools module to query if the metapackage is
installed and if so to grab that version. This is always faster than
subprocess to call pip freeze. That being said the performance at import
will vary based on the number of installed python packages because it
still has to check all the installed packages.

Speed up qiskit import by not using pip in version.py

---

qiskit/pulse/commands/command.py

This argument is specified by `Command`, but no implementations of `Command` allow `timeslots` as an input argument. Commands can be made into instructions and then shifted in time.
This follows along with not letting Instructions take timeslots as input; the timeslots are only used for internal time tracking, rather than a user interface.

The timeslots argument in Command isn't used

---

qiskit/extensions/standard/__init__.py
qiskit/extensions/standard/ms.py
qiskit/transpiler/passes/ms_basis_decomposer.py
qiskit/transpiler/transpile_circuit.py

Molmer-Sorenson gate on a variable number of qubits. 
Decomposes to a bunch of 2-qubit XX interactions.
This also updates the ion-trap branch to sync with master.

Add global Molmer-Sorenson gate

---

qiskit/circuit/parameterexpression.py
test/python/circuit/test_parameters.py

also start to support complex Parameters
This PR supports negated expressions. This resolves an exception which would be raised when using gates which negate their parameters, such as `extensions.standard.cu3`. For example,
```
x = Parameter('x')
y = Parameter('y')
expr = -x + y
```

add negation support for Parameter. closes #3098.

---

qiskit/circuit/instruction.py
qiskit/circuit/instructionset.py
qiskit/circuit/quantumcircuit.py
qiskit/circuit/random/utils.py
qiskit/converters/dag_to_circuit.py
qiskit/dagcircuit/dagcircuit.py
test/python/test_dagcircuit.py

Cleaning up some more references to `inst.control` to not get warnings.

Cleanup inst control usage from source tree

---

.pylintrc
qiskit/circuit/quantumcircuit.py
qiskit/visualization/circuit_visualization.py
qiskit/visualization/counts_visualization.py
qiskit/visualization/matplotlib.py
qiskit/visualization/state_visualization.py
releasenotes/notes/pass-mpl-ax-kwarg-069f793f01cd61a7.yaml
test/python/test_dagcircuit.py

This commit adds support for passing a matplotlib axes to visualization
functions. This enables integrating the qiskit visualizations into a
larger matplotlib visualization. When an ax kwarg is set that input will
be used for the output visualization and a new figure will not be
generated or returned.
Fixes #1950

Add ax kwarg to matplotlib visualization functions

---

test/python/test_dagcircuit.py

PR #2008 introduced a `pylint disable=invalid-name` that is very easy to fix.

remove disable=invalid-name in test/python/test_dagcircuit.py

---

qiskit/tools/jupyter/__init__.py

Normally if you're importing the qiskit jupyter magics from inside a
jupyter environment you'll want to use the widgets with matplotlib. If
you're running this and you forgot to install matplotlib it's not
exactly clear what happened. Especially if you're following a tutorial
or guide that uses `%qiskit_backend_overview` and it just raises a
UsageError because it was never initialized when you don't have
matplotlib installed. This commit attempts to mitigate this by raising a
runtime warning if the backend overview magic registration was skipped
because matplotlib wasn't found explaining that you need to have
matplotlib for that magic.

Add warning on jupyter imports if matplotlib isn't found

---

qiskit/circuit/instruction.py
releasenotes/notes/deprecate-qasm-ast-node-params-3cc930ea2c677a96.yaml

This commit deprecates the option of passing in a circuit parameter of
a qasm.node.Node type. Passing in qasm ast nodes as a parameter is
rarely used and is not actually done anywhere in the qiskit-terra code
or tests. Additionally there is the qiskit ast_to_circuit converter
which will take a program node object (the root node of a qasm ast) and
convert that directly to a circuit object.

Deprecate passing in an ast node as a instruction parameter

---

qiskit/visualization/latex.py

The latex drawer was writing out latex for the bit labels as:
\lstick{$REG_$INDEX: \ket{0}}
where $REG and $INDEX are a quantum register name and index
respectively. However, if the index exceeds 1 character in length the
latex subscript doesn't work anymore because it will only apply to the
first character. This commit fixes that issue by wrapping the index in
{} to make the subscript apply to the whole thing.
Fixes #3244

Fix latex drawer bit subscript for indexes >=10

---

qiskit/circuit/random/utils.py

The conditional code in qiskit.circuit.random.random_circuit() was
creating a list of 2^n_qubits to use np.random.choice() to pick a
single integer from that list. However, when you have a large number of
qubits, like 53, this will result in a memory error because you're
trying to allocate a list larger than is possible. This commit changes
the selection of the conditional value to select a random integer
directly instead of using a list to select a random integer.

Use numpy randint instead of choice for conditional

---

releasenotes/notes/Instruction-layering-for-circuit-drawing-has-changed-f62ce5aaeb8ce221.yaml
releasenotes/notes/add-memory-slots-to-pulse-qobj-exp-header-c21c795d761ab5a3.yaml
releasenotes/notes/circuit-data-modification-validation-52f02f955ecf90a1.yaml
releasenotes/notes/dense_noise_aware-46489df2439aab05.yaml
releasenotes/notes/deprecate-instruction-control-a363a15b3f0f0d72.yaml
releasenotes/notes/deprecate_bit_eq_tuple-e751168412b09702.yaml
releasenotes/notes/deprecate_unknown_styles-93f84aedd1887c44.yaml
releasenotes/notes/mock-backend-properties-a369bb6efdbae602.yaml
releasenotes/notes/passmanager_replace-d89e2cc46517d917.yaml
releasenotes/notes/remove-deprecated-device-specs-2d1aeab5f09b5a68.yaml
releasenotes/notes/remove-deprecated-schedule-ops-f57b3c2477312cbb.yaml
releasenotes/notes/rzz-visualization-5ade105ae6cae0eb.yaml

This commit updates some styling and wording issues in the release notes
for the 0.10.0 release so far. The most common issues is the use of
markdown style formatting instead of rst which is what reno uses.

Update release note styling and wording

---

qiskit/circuit/quantumcircuit.py
qiskit/extensions/quantum_initializer/diag.py
qiskit/extensions/quantum_initializer/squ.py
qiskit/extensions/quantum_initializer/ucg.py
qiskit/extensions/quantum_initializer/ucx.py
qiskit/extensions/quantum_initializer/ucy.py
qiskit/extensions/quantum_initializer/ucz.py

The QuantumCircuit had several instances of invalid rst formatting that
prevented the docs from rendering clearly. This commit fixes several of
them.
Two follow ups to this should be fixing all the warnings issued
during the docs builds (since most of them are highlighting valid
issues with formatting). Additionally all the docstrings for the
standard gate and circuit instruction methods should be updated to
flush out the docs here. Most of the docstrings for these methods are
one line and don't explain clearly what the inputs or outputs are.

Fix rst formatting for QuantumCircuit docstrings

---

qiskit/result/result.py
releasenotes/notes/partialresults-44d0ce37b1c09413.yaml

This PR allows the `Result` class to return partial results. If a valid result schema is loaded that contains some experiments which succeeded and some which failed, this allows accessing the data from experiments that succeeded, while raising an exception for experiments that failed and displaying the appropriate error message for the failed results.
This is related to Qiskit-Aer [Issue #346](https://github.com/Qiskit/qiskit-aer/issues/346).
Should be synced with Qiskit Aer [PR #365](https://github.com/Qiskit/qiskit-aer/pull/365)
Currently when `Result` is loaded from a valid JSON, if the top level `success` is false it will raise an exception when any experiment data is accessed, and only return the top level `status` message.
If a provider returned a valid JSON schema result for a …

Add support for partial results to Result class

---

qiskit/__init__.py

There was a race condition for the setting of the `__qiskit_version__`
attribute for the provider packages. Since the provider packages use a
separate pkutil namespace package the qiskit.providers package needs to
be imported for any provider package versions to be initialized for
pkgutil to load the additional packages. However, because of the import
path for python qiskit.version would often be loaded prior to that. This
caused the package versions for aer and ibmq to be missing from
`qiskit.__qiskit_version__`, since it just does an assignment from
qiskit.version's module attribute. To workaround this issue we need to
make sure that `_get_qiskit_versions()` is always called after
qiskit.providers is loaded. This commit does this by changing when we
run the function to be in the …

Update __qiskit_version__ call time

---

.travis.yml

The new aer packages use manylinux2010, and the randomized testing job
is using the sdist instead of the wheel. This commit updates the pip
version prior to installing aer to try and get it to install the binary
version instead of the source package.

Update pip prior to installing aer

---

qiskit/dagcircuit/dagnode.py

Addresses #3278 issue. Discussed and confirmed with @maddy-tod 
Updates doc strings under methods in `DAGNode` class.
Updates doc strings for `DAGNode.qargs`, `DAGNode.cargs`, and `DAGNode.wire` due to changes made in #2917

Fix doc strings in DAGNode class

---

.travis.yml
azure-pipelines.yml
constraints.txt

With the recent release of networkx 2.4 several deprecated APIs were
removed. This broke the visualization dependency nxpd. A fix is in
progress [1] to address this. But in the meantime to get tests working
again we need to make sure we do not install networkx 2.4 for testing.
This commit does this by pinning the version we use in our testing in
the constraints file to 2.3. This will unblock our development while we
wait for a new nxpd release.
(cherry picked from commit 38b03f4d1a73e3c6c3594f7ad79bfc0607b1a7c3)
[1] https://github.com/chebee7i/nxpd/pull/15
Backported from #3276

[Stable] Pin networkx in constraints

---

.travis.yml

#3143 restored travis jobs for environments other than 3.6, but the benchmarks are currently set to run on 3.5, which needed to be overridden explicitly.

Reset python env for CI benchmarks to 3.5.

---

tox.ini

We started setting the basepython attribute in the root testenv
configuration in the tox.ini in #1761. This was done to ensure that
users on environments with both python2 and python3 installed that jobs
which weren't explicit about the python version (like 'lint') would not
attempt to use python2 in error. However, this had the unintended side
effect of also making jobs which were opinionated about python version
(basically the standard test jobs 'py37', 'py36', and 'py35') would end
up using the 'python3' binary in the standard path instead of the
version specified in the job name. This mostly came up on systems with
more than one python version installed. The basepython declaration is
only needed for jobs that do not specify a python version. This commit
updates the tox.ini to remove …

Stop setting basepython in base tox testenv

---

qiskit/extensions/standard/__init__.py
qiskit/extensions/standard/r.py
qiskit/extensions/standard/rx.py
qiskit/extensions/standard/ry.py

Adds `RGate` for rotation about axis in X-Y plane to standard gates.
Re-defines `RxGate` and `RyGate` in terms of `RGate`

Add R gate to standard gates

---

qiskit/visualization/latex.py

The latex drawer uses a class attribute img_depth to keep track of the
number of columns to put in the output img_depth (along with some other
things related to that). This value was attempted to be figured out by
looking at the number of layers except if there is a cu1 gate in a
layer then that layer has 2 columns (because the label takes up one).
However this count was done incorrectly and instead the number of
columns was equivalent to the number of gates in each layer plus 2
columns for each cu1. This resulted in a huge empty space for circuits
with lots of qubits, especially if they had lots of gates per layer.
This commit corrects the layer count loop to instead properly only
count a layer once and twice if it has a cu1 gate in the layer.
(cherry picked from commit …

[Stable] Fix latex columns count

---

qiskit/visualization/matplotlib.py

This commit fixes issues reported with long parameter lists in the mpl
drawer. The issue is that when the length of the parameters list exceeds
20 characters the mpl drawer removes the parameters. Multiple attempts
have attempted to address this issue (#2994 #3353) by just increasing
that limit. But this doesn't actually solve the problem because the
boxes are fixed width so the parameters just exceed the width of the
boxes. The proper way to fix this is to dynamically
In addition this whole problem is primarily caused because we don't
round any parameter values. This commit rounds the parameters so that we
rarely have to scale to have super wide parameter lists.
Fixes #2822

Fix matplotlib with wide parameters

---

.travis.yml

In #3143 we added back most of the jobs which we removed from travis to
see if we preferred running jobs in travis or azure pipelines. After
having this for a full day it's become apparent that even with the extra
capacity from our travis subscription that the wait times on travis with
the full job load are too high. The travis check returned significantly
slower than the equivalent job in azure pipelines. So for now we'll
stick to running the majority of and required testing in azure pipelines
and use travis only for extra jobs where needed. This commit removes all
the duplicated jobs that we run in azure from the travis config.

Remove duplicated test jobs from travis

---

qiskit/validation/base.py
test/python/validation/test_models.py

As explored with @ajavadia , this PR introduces a way of opting-in for not performing validation when creating an instance of a `BaseModel`, intended for cases where the creator of the object has strong assurances about its validity. It does so by using a `validate=False` argument to the instantiation, which is treated as a special flag swallowed by the binder - a side effect is that it becomes sort of a reserved word.
Additionally, it revises some of the docstrings that were not accurate enough as a result of #3084 and others.

Allow bypassing validation during model instantiation

---

qiskit/assembler/assemble_circuits.py
qiskit/circuit/instruction.py

Following #3368 , disables on-init validation of `QasmQobjInstruction` during `assemble_circuits`.
```
$ asv continuous --bench assembl master assemble_circuits-disable-instruction-validation
...
before           after         ratio
[2ad7a666]       [45740444]
<master>         <assemble_circuits-disable-instruction-validation>
-     1.26±0.06ms         584±10μs     0.46  assembler.AssemblerBenchmarks.time_assemble_circuit(1, 8)
-     4.50±0.07ms       1.55±0.2ms     0.34  assembler.AssemblerBenchmarks.time_assemble_circuit(8, 8)
-      2.11±0.5ms         701±20μs     0.33  assembler.AssemblerBenchmarks.time_assemble_circuit(2, 8)
-     2.95±0.03ms         966±80μs     0.33  assembler.AssemblerBenchmarks.time_assemble_circuit(5, 8)
-        383±10ms        96.2±10ms     0.25 …
```

Disable QasmQobjInstruction validation during circuit assembly.

---

qiskit/pulse/pulse_lib/continuous.py
qiskit/pulse/pulse_lib/discrete.py
test/python/pulse/test_discrete_pulses.py

Fixes #3313 to correctly offset the pulses for Gaussian, Gaussian Square, Sech
Also makes default sampling midpoint

fix zeroed_width issues, make default sampling midpoint

---

qiskit/pulse/pulse_lib/discrete.py

Fixes #3412  --- optional zeroing of first/last sample for `gaussian`, `gaussian_square`, `drag` (real part), `sech` pulses. default is True.

make zeroing of discrete pulses optional

---

qiskit/tools/monitor/backend_overview.py

After #3325 the import structure of the tools directory was changed so
that sometimes the ibmq imports at the top of the
qiskit.tools.monitor.backend_overview module get evaluated prior to the
pkgutil call in qiskit.providers.__init__ that is used to look for
namespace packages outside of the terra repo. When this happens the
imports from the qiskit-ibmq-provider package fail because they haven't
been added to the python namespace yet. The way the backend monitor was
checking made this non-fatal but would never populate the names. So when
you'd later go to run the function it would fail with a NameError
because the imports didn't work, even if ibmq was installed (and
working otherwise). This commit works around this issue by making the
ibmq imports occur at runtime inside the functions in …

Make ibmq imports for backend monitor at runtime

---

test/python/basicaer/test_basicaer_backends.py

I noticed that `test.python.basicaer.test_basicaer_backends.TestBasicAerBackends.test_deprecated` was printing log when tested: 
```
test_deprecated (test.python.basicaer.test_basicaer_backends.TestBasicAerBackends)
Test that deprecated names map the same backends as the new names. ... Backend 'qasm_simulator_py' is deprecated. Use 'qasm_simulator'.
Backend 'statevector_simulator_py' is deprecated. Use 'statevector_simulator'.
Backend 'unitary_simulator_py' is deprecated. Use 'unitary_simulator'.
Backend 'local_qasm_simulator_py' is deprecated. Use 'qasm_simulator'.
Backend 'local_statevector_simulator_py' is deprecated. Use 'statevector_simulator'.
Backend 'local_unitary_simulator_py' is deprecated. Use 'unitary_simulator'.
Backend 'local_unitary_simulator' is deprecated. Use …
```

a less noisy test_deprecated

---

qiskit/circuit/quantumcircuit.py

This reverts commit e276505ffd78dee937d8879fceff9e71d72d5a4a. The scale
parameter default value of 0.7 was chosen intentionally to keep the
image sizes more reasonable, especially inside of jupyter notebooks. This
value of 0.7 is used in several other places as well for this reason. The
issue with the images being cutoff that this was trying to address isn't
because we're scaling the image and it's a more general problem.
Especially when you can consider the images can still be scaled down they
will still experience the same issue. Just increasing the size of the
image isn't a general solution and only fixed it for specific cases. There
is a tight_layout method in matplotlib that should be used to address
images getting truncated which we can look into in adding back in a future
PR.

Revert #3421 "Set the scale parameter of QuantumCircuit.draw to a default 1"

---

requirements.txt
setup.py

In the networkx release notes for 2.4 [1] it states clearly that the 2.4
release is the last release with python 3.5 support. Since the release
timeline is not fixed and we may end up support python 3.5 in terra
longer than networkx this adds a capped version of networkx on 2.4 for
python 3.5. However, since networkx 2.4 is seemingly relying on the
guaranteed insertion ordering for dicts introduced in 3.6 for how we're
using topological sort this adjusts the cap previously introduced to be
< 2.4 instead of <= 2.4. This should avoid the failures related to this
on python 3.5 and networx 2.4.
As part of #3280 the networkx version for python 3.5 was pinned to be
< 2.4 as part of a larger refactor of the dag drawer. That refactor is
not eligble for backport to a stable branch because of the …

[Stable] Add python 3.5 pin for networkx

---

examples/python/ibmq/using_qiskit_terra_level_0.py
test/python/tools/monitor/test_backend_monitor.py

in the new release of IBMQ, the .backends() method no longer exists and this is on individual providers. Tweak terra to match.

fix no IBMQ.backends()

---

qiskit/circuit/add_control.py
qiskit/visualization/text.py
test/python/visualization/test_circuit_text_drawer.py

With the help of @ewinston, we solved a small issue in which the params the `ControlledGate.base_gate` were getting lost. This is the fix.

Params in controlled gates

---

test/python/circuit/test_controlled_gate.py

A follow up to #2862 (see #3453)

Removing unused import modules from test_controlled_gate.py

---

qiskit/result/__init__.py
qiskit/result/postprocess.py
qiskit/result/result.py
qiskit/result/utils.py
releasenotes/notes/marginal-counts-51108f216cc684d1.yaml
releasenotes/notes/result-get-marginal-counts-51108f216cc684d1.yaml
test/python/result/test_result.py

A utility function `qiskit.result.marginal_counts()` to obtain marginalized counts from an experiment where more measurements were done than desired.
I'll later deprecate the method that exists in ignis tomography module (https://github.com/Qiskit/qiskit-ignis/issues/283)

Result marginal counts

---

qiskit/circuit/instruction.py

#3156 updated `@params.setter` on the `Instruction` class to auto-instantiate a `Parameter` object when a string was provided in `params`. (Previously, the setter had wrapped the strings in `sympy.Symbol` objects.) However, this can lead to inconsistent behavior for gates using string parameters. This PR leaves string parameters as `str` in `params`.

Revert auto-Parameter creation from param of type str.

---

qiskit/transpiler/passes/mapping/noise_adaptive_layout.py

Changed swap_reliab of swap graph edges with 0 reliability from -math.inf to math.inf
Fixed issue   #3517 
Fixed the issue where a cx with 0 reliability would be always choosed by the `NoiseAdaptiveLayout` trasnpiler pass.

Fixed noise adaptive layout choosing 0 reliability cx

---

qiskit/tools/parallel.py

Some of the reset flags for parallel were `False` rather than `FALSE` as they should be.

Fix parallel flags

---

CONTRIBUTING.md

As part of the effort to standardize working between all the qiskit
elements and adopting the same workflow and common practices for each
element we recently added most of terra's contributing.md file into the
documentation (see Qiskit/qiskit#686). This commit updates the
contributing file to reference the hosted documentation and removes the
duplicated sections. At the same time this commit also adds some additional
details on referencing issues inside a release note.

Cleanup CONTRIBUTING.md file

---

qiskit/extensions/simulator/snapshot.py
releasenotes/notes/remove_implicit_conversion_snapshot_label-f3082561ede0bed5.yaml

The label has to be a string. The warning with the cast is being removed after 7 months of being there.

Remove implicit string cast of the snapshot label

---

qiskit/dagcircuit/dagcircuit.py
qiskit/transpiler/passes/decompose.py
test/python/circuit/test_isometry.py
test/python/transpiler/test_decompose.py

Fixes #3440 
When #3233 was implemented, a check was added to the unroller to ensure that, before using `DAGCircuit.substitute_node`,  the definition width matched that of the instruction being replaced, but this fix was not included in the `Decompose` pass. This PR add that check.

Decompose substitute_node only when gate width matches definition.

---

qiskit/visualization/matplotlib.py

This commit fixes 2 issues related to the dynamic spacing regarding
both the dynamic width of gates with parameters and the corresponding
spacing between the gates. The first issue regarding gate width, we were
incorrectly using the raw string length for the parameters of a wide
gate when dynamically spacing it. This was incorrect because there is
often $\pi$ included in a gate's parameters which will increase the
number of characters from len() calls on the string, but because of
mathtext markup in mpl results in a single character on the output. This
meant we were incorrectly assuming the gates were significantly longer
than the actual length causing unnecessarily long boxes.
The second issue regarding spacing is a bit more subtle, when dynamic
width boxes for parameters were introduced …

Fix dynamic spacing for gate params in mpl circuit.draw()

---

qiskit/compiler/transpile.py
test/python/basicaer/test_basicaer_integration.py
test/python/transpiler/test_1q.py

If transpile is called with `coupling_map=None` this checks the number of qubits in the circuit doesnt exceed the backends `n_qubits` only if it is a real device with a physical qubit limit, not a simulator
Fixes failing build in Qiskit Aer
#3557 introduced an unintended bug where transpile would fail for simulations that should be possible due to truncation of qubits. The Aer simulators check the size of the circuit during execution after any qubit trunction/remapping is performed.

Fix transpile to only check for max qubits if backend is not a simulator

---

qiskit/assembler/assemble_schedules.py
test/python/compiler/test_assembler.py

Closes #3580. Adds conversion of enums to canonical serialized values in `assemble_schedules`. Also, all assembly tests now test against the json schema.

Fix enum meas_return to_dict bug

---

qiskit/visualization/pulse/matplotlib.py
qiskit/visualization/pulse/qcstyle.py

Fixes a bug where too many framechanges in a plot would cause the table to become too large and the waveform section would have a negative height.

Fix bug where too many framechanges in table would cause plotting to fail

---

qiskit/providers/models/backendconfiguration.py
qiskit/providers/models/pulsedefaults.py

This is a patch fix to make warnings for dt and qubit_freq_est only be raised when called. This is achieved by turning these attributes into properties.

Added one time warnings for dt and qubit_freq_est turning into properties

---

qiskit/schemas/deprecated/qobj/qobj_generic_schema.json
qiskit/schemas/qobj_schema.json

Small fix noticed during #3553, with some of the .json files having tabs instead of spaces during recent (and not so recent) additions. This PR replaces the tabs with spaces to avoid formatting issues.

Replace tabs with spaces in .json schemas

---

qiskit/extensions/quantum_initializer/initializer.py

To fix a failing lint on master. scipy.kron is deprecated

Replace scipy.kron with numpy.kron in quantum_initializer.

---

.travis.yml
azure-pipelines.yml

Since we've deprecated python 3.5 having 3.5 be the first round of
testing performed in CI feels out of place. This commit makes the
default jobs run in the first stage of the CI pipeline in azure all use
python 3.7. We still need to verify that 3.5 works and still gate on the
3.5 job passing. But, it doesn't get as much attention now that it's
deprecated. At the same time this commit takes the opportunity to remove
the duplicated python 3.8 job in the travis config. This was added
originally because travis had 3.8 support well before azure pipelines
but was never removed after azure added their 3.8 support.

Make python 3.7 default in CI and remove duplicate job

---

test/python/circuit/test_gate_definitions.py
test/python/circuit/test_parameters.py
test/python/visualization/test_circuit_drawer.py
test/python/visualization/test_circuit_text_drawer.py

Fix typos in python files under `test/python/circuit` and `test/python/visualization`.   
Most of them in comment or message. Two lines change test method name.

fix typo under python/test

---

qiskit/transpiler/passes/crosstalk_adaptive_schedule.py
requirements-dev.txt
test/python/transpiler/test_crosstalk_adaptive_scheduler.py

PR #3532 introduced an optional dependency on `z3-solver`. This PR skips the tests using that module when not available.

skip test_crosstalk_adaptive_scheduler when z3-solver not available

---

qiskit/visualization/matplotlib.py

Fixes #3607 .
Unwanted huge gaps between the 'unitary' custom gates have been corrected. The gaps were a result of using the size of the parameters to determine the layer width. Since the custom 'unitary' gate takes elements of a unitary matrix as the parameter, the layer width gets exploded. This has been corrected by updating matplotlib.py.

Huge gaps between 'unitary' gates in mpl drawer corrected

---

qiskit/quantum_info/synthesis/one_qubit_decompose.py
test/python/quantum_info/test_synthesis.py

Start adding infrastructure for phase correct one-qubit synthesis
* Removes transformation via Quaternions for Rx Ry Rx single qubit synthesis algorithm.
* Style improvements to one qubit synthesis class
Removing the quaternions transformation is necessary for phase correct synthesis for the XYX basis in #3472. This PR makes some other style fixes to the one qubit synthesis class in preparation for the phase-correct synthesis in that PR

Remove quaternions from XYX synthesis algorithm

---

qiskit/quantum_info/operators/operator.py
test/python/quantum_info/operators/test_operator.py

Fixes #3671 
Fixes bug with `Operator.transpose` not swapping input and output dimensions. This would case transpose to fail for rectangular operators.

Fix ``Operator.transpose`` for rectangular operators

---

qiskit/extensions/quantum_initializer/initializer.py

To fix a failing lint on master. scipy.kron is deprecated
(cherry picked from commit 71802756e351e17c4436db5209a84262f190876c)
Backported from #3623

[Stable] Replace scipy.kron with numpy.kron in quantum_initializer. (#3623)

---

constraints.txt

The recent nbformat release 5.0.0 that was just pushed to pypi is
missing jsonschema files from the uploaded artifacts,
(see jupyter/nbformat#155). This is causing CI failures, until the issue
is resolved this commit pins the version installed via pip using the
constraints file (since it's not a direct dependency).

Pin nbformat to 4.4.0

---

constraints.txt

The recent nbformat release 5.0.0 that was just pushed to pypi is
missing jsonschema files from the uploaded artifacts,
(see jupyter/nbformat#155). This is causing CI failures, until the issue
is resolved this commit pins the version installed via pip using the
constraints file (since it's not a direct dependency).
Backported from #3691 
(cherry picked from commit 7718e3576d0c9d77991c8c4b813ac05b7b1aa940)

[Stable] Pin nbformat to 4.4.0 (#3691)

---

qiskit/assembler/assemble_schedules.py
qiskit/compiler/assemble.py
qiskit/execute.py
qiskit/providers/models/backendconfiguration.py
qiskit/qobj/converters/lo_config.py
test/python/compiler/test_assembler.py
test/python/qobj/test_pulse_converter.py

Closes #3595, #3596. Fixes a bug where lo units are not being properly converted, nor were they being accepted in Hz by assemble/execute and schedule_los.
* Fix backend config where lo ranges were not adjusted to Hz.
* Fix bug where assemble/execute accepted parameters in GHz rather than Hz.
* linting
* Documentation fixes for Hz.
* Add channel bandwidth.
* bug fix with kwarg pop.
* Missing None in kwargs pop.
* linting.
* Fix range in list comprehension for lo ranges in backend configuration.
* Update qiskit/compiler/assemble.py
Co-Authored-By: Lauren Capelluto <laurencapelluto@gmail.com>
* Update qiskit/compiler/assemble.py
Co-Authored-By: Lauren Capelluto <laurencapelluto@gmail.com>
* lo to LO in docstrings.
Backported from: #3597 
Co-authored-by: Matthew Treinish …

[Stable] Fix bug where lo units were not being properly converted (#3597)

---

constraints.txt
requirements-dev.txt

Currently we're pinning pylint and astroid via a constraints file. This
was done primarily because astroid is not a direct dependency for
development since we only actually directly use pylint. The constraints
file mechanism is designed for this purpose to let us set explict
versions for repeatability for any package installed via pip, even if
it's not a direct requirement. However, the constraints file mechanism
isn't obvious to developers who are manually installing development
requirements into their environment. Additionally, the
requirements-dev.txt had a pylint version cap which conflicts with the
version set via the constraints file which made it extra confusing.
This commit moves away from using the constraints for pylint and moves
to using requirements-dev.txt directly. To …

Pin pylint and astroid in requirements-dev.txt

---

qiskit/pulse/reschedule.py
test/python/pulse/test_reschedule.py

```
input_sched = Schedule(name="X")
sched = align_measures([input_sched], self.cmd_def)[0]
```
Before, `sched.name` would be `None`, now it is `"X"`
Thank you @nkanazawa1989 for reporting

Fixup bug where name isnt maintained by align_measures

---

qiskit/schemas/examples/qobj_openpulse_example.json

While reviewing #3702, noticed that one of the examples had a duplicate `description` field in the `header` - this PR fixes it by picking the most recent description.

Remove duplicated field in json example

---

qiskit/schemas/backend_configuration_schema.json
qiskit/schemas/examples/backend_configuration_openpulse_example.json
qiskit/schemas/examples/qobj_openpulse_example.json
qiskit/schemas/qobj_schema.json

Update schemas as necessary for #3463 
- expects BackendConfiguration `parametric_pulses` field to be allowed
- expects Qobj instruction with `name="parametric_pulse"` and `params` field

Update schemas for parametric pulses

---

qiskit/visualization/utils.py
test/python/visualization/test_visualization.py

Fix some instances of strings that contain invalid escape sequences (that were actually emitting [`DeprecationWarnings`](https://docs.python.org/3/reference/lexical_analysis.html#string-and-bytes-literals) under some configurations) by using raw strings instead.

Use raw literals in strings

---

setup.py

The project description on pypi (https://pypi.org/project/qiskit-terra/) is currently a bit lacking (and with a formatting artifact):
As pypi supports markdown since a while ago, this PR replaces the current long_description with the contents of `README.md`, in order to use it as the project description in the pypi web interface (similar to the current https://pypi.org/project/qiskit-ibmq-provider/).

Use README as package long_description

---

qiskit/compiler/assemble.py

In #3606 an error condition was added to the qiskit.compiler.assemble()
function when the shots parameter exceeds max_shots set in the backend.
However, the first revision of #3606 was originally raising a warning
and changing the shots value used. When the PR was repurposed to instead
raise an error, the old warning message was used as the new error
message. However, this also mentions changing the value of shots which
was no longer relevant. This commit corrects the oversight so that the
error message no longer says "Reducing shots to max_shots".

Fix error message for shots exceeding max_shots

---

qiskit/quantum_info/__init__.py
qiskit/quantum_info/states/__init__.py
qiskit/quantum_info/states/measures.py
qiskit/quantum_info/states/utils.py
test/python/quantum_info/test_states.py

Updates the `quantum_info.state_fidelity` function to work with `Statevector` and `DensityMatrix` objects, along with raw numpy statevector and density matrix arrays.
Updates state_fidelity documentation

fix ``state_fidelity`` to work with ``Statevector`` and ``DensityMatrix`` classes

---

qiskit/quantum_info/operators/base_operator.py
qiskit/quantum_info/operators/channel/chi.py
qiskit/quantum_info/operators/channel/choi.py
qiskit/quantum_info/operators/channel/kraus.py
qiskit/quantum_info/operators/channel/ptm.py
qiskit/quantum_info/operators/channel/quantum_channel.py
qiskit/quantum_info/operators/channel/stinespring.py
qiskit/quantum_info/operators/channel/superop.py
qiskit/quantum_info/operators/operator.py
releasenotes/notes/operator-dot-fd90e7e5ad99ff9b.yaml
test/python/quantum_info/operators/channel/test_chi.py
test/python/quantum_info/operators/channel/test_choi.py
test/python/quantum_info/operators/channel/test_kraus.py
test/python/quantum_info/operators/channel/test_ptm.py
test/python/quantum_info/operators/channel/test_stinespring.py
test/python/quantum_info/operators/channel/test_superop.py
test/python/quantum_info/operators/test_operator.py

* Adds `dot` method to operator API in BaseOperator class
* Changes operator `__mul__` method to implement `dot`
* Leaves operator `__rmul__` method as implementing `multiply` (scalar multiplication)
* Deprecates `front=True` kwarg of operator `compose` method which is now implemented with `dot`.

Add ``dot`` method to operator classes

---

qiskit/quantum_info/__init__.py
qiskit/quantum_info/states/__init__.py
qiskit/quantum_info/states/measures.py
qiskit/quantum_info/states/states.py
test/python/quantum_info/states/test_measures.py
test/python/quantum_info/test_states.py

This removes function `quantum_info.states.states.purity` and replaces it with a function `quantum_info.states.measures.purity` which works with Statevector and DensityMatrix classes (along with raw nparrays).
The function is a wrapper for converting the input to a Statevector or DensityMatrix and calling the `.purity` method of that class with additional.

fix ``purity`` function to work with ``Statevector`` and ``DensityMatrix`` classes

---

qiskit/pulse/commands/persistent_value.py
qiskit/qobj/converters/pulse_instruction.py
releasenotes/notes/deprecate-persistent-value-command-4ec516a314197887.yaml

The ConstantPulse parametric pulse should be used in its place. This requires the user to know the duration for which the signal amplitude should be changed.

Deprecate the PersistentValue instruction. 

---

qiskit/visualization/text.py
test/python/visualization/test_circuit_text_drawer.py

When label is provided, text-draw it instead of the name

---

qiskit/quantum_info/__init__.py
qiskit/quantum_info/states/__init__.py
qiskit/quantum_info/states/measures.py
qiskit/quantum_info/states/states.py
qiskit/quantum_info/states/utils.py
qiskit/tools/qi/qi.py
releasenotes/notes/state-measures-f662a847d0db42b8.yaml
test/python/quantum_info/states/test_measures.py
test/python/quantum_info/states/test_utils.py

* Add functions `entropy`, `mutual_information`, `concurrence`, and
`entanglement_of_formation` to quantum_info.states that work with
`Statevector` and `DensityMatrix` classes.
* Add unittests for new functions
* Deprecate EVERYTHING in `tools.qi.qi.py`
* Deprecate `basis_states` and `projector` in `quantum_info.states.states.py`
* Allow entropy based functions to set custom base with kwarg (default base 2)

Add entropy and entanglement state measures to quantum_info

---

qiskit/quantum_info/operators/base_operator.py
qiskit/quantum_info/operators/channel/chi.py
qiskit/quantum_info/operators/channel/choi.py
qiskit/quantum_info/operators/channel/kraus.py
qiskit/quantum_info/operators/channel/ptm.py
qiskit/quantum_info/operators/channel/quantum_channel.py
qiskit/quantum_info/operators/channel/stinespring.py
qiskit/quantum_info/operators/channel/superop.py
qiskit/quantum_info/operators/operator.py
releasenotes/notes/operator-dot-fd90e7e5ad99ff9b.yaml

* Removes the deprecation of the `front=True` kwarg for the BaseOperator class from when the `dot` method for front composition was added in PR #3740.
* Adds class level API documentation for Operator and quantum channel classes.
Now `front=True` is a allowed, but still equivalent to the `dot` method. The motivation for not deprecating it if a compose method is added to circuits, dot likely will not be added as `compose(other, qargs, front=True)` makes more sense than `dot` which is specifically referring to matrix multiplication of operators, not contraction of a DAG.

De-deprecated front compose for operators, update operator API docs

---

qiskit/validation/base.py
test/python/validation/test_schemas.py

Closes #3021.
Add optional `**kwargs` to `bind_schema`, that are propagated into  `_SchemaBinder` and the schema initialization. Even if not used directly, this provides support to custom uses of `bind_schema`, where the user needs finer control of the instantiation parameters.

Add optional parameters to bind_schema

---

qiskit/circuit/instruction.py

To partially address the regression introduced in #3773 and the issue raised in #3800 , updates `deepcopy(Instruction)` to return `Instruction.copy()` which shallow copies the instruction instance and its `params`.

deepcopy(Instruction) to use Instruction.copy.

---

qiskit/transpiler/passes/routing/stochastic_swap.py

When profiling a level 0 transpile of a 20x50 random circuit the timing
data shows that after switching to retworkx the largest chunk of time in
in stochastic swap's _layer_permutation function is spent calling pformat
for log messages. This is just for debugging and is unnecessary, and in a
world where we're no longer bottle-necked on dag operations a significant
cost to the run time.

Remove pformat from stochastic swap log messages

---

qiskit/pulse/reschedule.py

Fixup documentation formatting in qiskit.pulse.reschedule where verbatim formatting was not properly closed

Docathon: Fixup: formatting

---

test/python/tools/jupyter/test_notebooks.py

The tests in test.python.tools.jupyter.TestJupyter rely on the ibmq
provider for the execution of the notebooks. However we don't require
the local installation (or the configuration) of the provider for
running tests anywhere else. In cases where someone is missing either
ibmq or credentials the tests (of which only test_jupyter_jobs_pbars) in
the class will fail because they can't import qiskit.IBMQ. This commit
addresses this issue by adding a skip to the class on
hasattr(qiskit, 'IBMQ') so that if the ibmq provider is not installed
the tests will all skip.

Skip TestJupyter tests if ibmq provider is not installed

---

docs/apidocs/pulse.rst
qiskit/pulse/__init__.py
qiskit/pulse/pulse_lib/__init__.py
qiskit/pulse/pulse_lib/discrete.py

Closes #3392
Adding math expressions for the functions being sampled in `discrete.py`. 
1. Updated doc strings in `discrete.py` to include math expressions, along with a couple of jupyter-execute sections for plotting pulses with a simple shape but whose mathematical expression may not be immediately recognizable (or at least weren't to me).
2. Code provided by @SooluThomas: Updated `pulse.rst` and `pulse/__init__.py` to include a section in the sphinx pulse toc called Pulse Library, which links to the `discrete` module.

Docathon! Docs for discrete pulse functions 

---

qiskit/pulse/pulse_lib/discrete.py

This commit fixes the citation syntax in `qiskit/pulse/pulse_lib/discrete.py`.

Fix citation in pulse_lib/discrete

---

qiskit/pulse/__init__.py
qiskit/pulse/channels.py

Update the pulse module init file for documentation. This includes adding autosummary references to important parts of the module that were previously unreachable, and providing introductory summaries where appropriate
This also closes #3406.
~Also: I will wait on #3838 to merge first, since I anticipate merge conflicts~

Docathon: Module level docs for Pulse

---

qiskit/circuit/library/__init__.py
qiskit/circuit/library/boolean_logic.py
releasenotes/notes/boolean-logic-circuit-library-0f913cc04063210b.yaml
test/python/circuit/test_library.py

add a `qiskit.circuit.library` namespace and add some basic boolean logic circuits.
It would be nice to converge on the same name for libraries of different kinds.
I propose:
```
qiskit.circuit.library
qiskit.pulse.library  # instead of current pulse_lib
qiskit.transpiler.library  # instead of current preset_passmanagers
```

start of a circuit library

---

qiskit/circuit/__init__.py
qiskit/circuit/random/utils.py

This commit adds the docs for random_circuit to the Quantum Circuit docs
so that the docstring is usable from the rendered docs. It previously
was not being included in any documentation which meant the only
documentation about it was in the code.

Add random circuit function to api docs

---

qiskit/extensions/standard/i.py

As noted by @mtreinish, the deprecated `iden` method of `QuantumCircuit` fails. 
This is due to the use of a deprecated argument in the method itself.
The traceback is:
```
File "D:\a\1\s\test\terra\decorators.py", line 31, in is_method_available
dummy_circ.iden(0)
File "c:\miniconda\envs\qiskit-aer-20200224.3\lib\site-packages\qiskit\util.py", line 108, in wrapper
return func(*args, **kwargs)
File "c:\miniconda\envs\qiskit-aer-20200224.3\lib\site-packages\qiskit\extensions\standard\i.py", line 104, in iden
return self.append(IGate(), [q], [])
File "c:\miniconda\envs\qiskit-aer-20200224.3\lib\site-packages\qiskit\circuit\quantumcircuit.py", line 462, in append
expanded_qargs = [self.qbit_argument_conversion(qarg) for qarg in qargs or []]
File …
```

Fix use of deprecated argument in ``iden``

---

qiskit/extensions/quantum_initializer/isometry.py
qiskit/extensions/quantum_initializer/squ.py
qiskit/extensions/quantum_initializer/uc_pauli_rot.py

There were unnecessary Identity gates being inserted in the decomposition of some gates. This was due to a bug which was fixed by #3274. So removing the Identities.

remove identity insertion in gate decomposition

---

qiskit/quantum_info/operators/base_operator.py
qiskit/quantum_info/operators/channel/chi.py
qiskit/quantum_info/operators/channel/choi.py
qiskit/quantum_info/operators/channel/kraus.py
qiskit/quantum_info/operators/channel/ptm.py
qiskit/quantum_info/operators/channel/quantum_channel.py
qiskit/quantum_info/operators/channel/stinespring.py
qiskit/quantum_info/operators/channel/superop.py
qiskit/quantum_info/operators/operator.py
releasenotes/notes/base-operator-update-b0d824738b4bfd4d.yaml
test/python/quantum_info/operators/channel/test_chi.py
test/python/quantum_info/operators/channel/test_choi.py
test/python/quantum_info/operators/channel/test_kraus.py
test/python/quantum_info/operators/channel/test_linearops.py
test/python/quantum_info/operators/channel/test_ptm.py
test/python/quantum_info/operators/channel/test_stinespring.py
test/python/quantum_info/operators/channel/test_superop.py
test/python/quantum_info/operators/test_operator.py
test/python/quantum_info/states/test_densitymatrix.py
test/python/quantum_info/states/test_statevector.py

Simplifies some methods of the base class to make inheritance in derived classes easier. Removes a lot of duplicated code by adding common functions to BaseOperator and QuantumChannel base classes. Deprecates base methods for addition, subtraction, and scalar multiplication that should be done using binary operators +, -, *. 
* Deprecate `add` (replaced with `_add`)
* Deprecate `subtract` (replaced with `_add(-other)`)
* Deprecate `multiply` (replaced with `_multiply`)
* Make _add and _multiply non abstract base methods that raise a
NotImplementedError so if subclasses don't have to implement these methods
if they don't support them.
* Move some common functionality from linear channel classes into the base
QuantumChannel class to avoid code duplication.
* Make internal `_reshape` method …

Simplify BaseOperator abstract class

---

qiskit/extensions/standard/__init__.py
qiskit/extensions/standard/multi_control_rotation_gates.py
qiskit/extensions/standard/multi_control_toffoli_gate.py

Several multi-controlled gates (see below) have been copied to Terra, but are not included in any `__init__` and therefore only imported through Aqua, where they are included in an `__init__` file.
If they already exist in Terra we should also include them from there, so we can finally remove these duplicate gate implementations from Aqua.
Two files remain in Aqua, namely the multi-control multi-target Toffoli and some boolean logic gates. Is there a reason why only part of the gates have been moved here?
This affects:
```
multi_controlled_u1_gate -> mcu1
multi_controlled_toffoli_gate -> mct
multi_controlled_rotation_gates -> mcrx, mcry, mcrz
```
These gates exist in Aqua: https://github.com/Qiskit/qiskit-aqua/tree/master/qiskit/aqua/circuits/gates
The three files named above also …

Import the multi-controlled Gates from Terra, not Aqua

---

qiskit/providers/basejob.py

Right now warnings aren't fatal for terra's doc builds, but other
elements are ahead of it in that regard and they catch many more docs
issues and formatting bugs because of it. However, because of this
disparity it is possible for terra to introduce a warning on something
that is used as a parent class for another element which will be fatal
for that project's docs jobs. This happened in #3731 which broke the
docs job of Aer because of incorrect formatting in the docstring (which
would result in poorly formatted output). This commit fixes this and
updates the docstring to not cause a warning. A necessary follow-on here
is to fix all the sphinx warnings emitted by terra during a docs build.
Fixes #3898

Fix sphinx warning in wait_for_final_state

---

qiskit/test/mock/backends/boeblingen/fake_boeblingen.py
qiskit/test/mock/backends/johannesburg/fake_johannesburg.py
qiskit/test/mock/backends/melbourne/fake_melbourne.py
qiskit/test/mock/backends/ourense/fake_ourense.py
qiskit/test/mock/backends/poughkeepsie/fake_poughkeepsie.py
qiskit/test/mock/backends/rochester/fake_rochester.py
qiskit/test/mock/backends/rueschlikon/fake_rueschlikon.py
qiskit/test/mock/backends/singapore/fake_singapore.py
qiskit/test/mock/backends/tenerife/fake_tenerife.py
qiskit/test/mock/backends/tokyo/fake_tokyo.py
qiskit/test/mock/backends/vigo/fake_vigo.py
qiskit/test/mock/backends/yorktown/fake_yorktown.py
qiskit/test/mock/fake_backend.py
qiskit/test/mock/fake_provider.py

The fake backends were missing attributes (`max_experiments`, `_credentials`) and methods (`jobs`) that limited the usefulness of these tools, e.g. https://github.com/Qiskit/qiskit/issues/836.  This fixes that.

Add required items to fake backends

---

qiskit/circuit/quantumcircuit.py
releasenotes/notes/fix-propagation-of-substituted-parameters-78bc9ece47013dbb.yaml
test/python/circuit/test_parameters.py

Analogously to #3729, which fixes the propagation of binding floats to Parameter objects, this PR fixes the binding of Parameter objects to Parameter objects.
This is a required functionality for refactoring the variational forms, resp. Ansatz class, in the next Aqua release.
The `Parameter` objects in circuits can be substituted with new parameters by using the `QuantumCircuit._substitute_parameters` method. This, however, only updates the parameter table of the circuit object and doesn't propagate the change to the instructions in defining the circuit (in `QuantumCircuit.data`). When the circuit is then decomposed or transpiled, the parameter change can get lost.
See also https://github.com/Qiskit/qiskit-terra/pull/3729#issue-364995145 for more information.

Fix substitute parameters when decomposing composite gates

---

qiskit/extensions/standard/rxx.py

The current version of the `RXX(θ)` gate uses 3 gates parameterized by `θ` and is up to a phase of `exp(iθ/2)`. There is a more efficient implementation with the same amount of gates but only 1 gate parameterized on `θ` with a phase of `exp(-iθ/2)`. Less parameters are desirable e.g. for gradient computation or parameter binding. 
This PR implements this more efficient version. 
The gate sequence changes as follows.
```
(HGate(), [q[0]], []),  # was: U3Gate(np.pi / 2, theta, 0)         
(HGate(), [q[1]], []),
(CnotGate(), [q[0], q[1]], []),
(U1Gate(theta), [q[1]], []),  # was: U1Gate(-theta)
(CnotGate(), [q[0], q[1]], []),
(HGate(), [q[1]], []),
(HGate(), [q[0]], []), # was: U2Gate(-np.pi, np.pi - theta)
```

Less parameters in the RXX gate

---

qiskit/qobj/qasm_qobj.py
test/python/qobj/test_qobj.py

In #3383 we moved away from using marshmallow for Qobj objects to flat
classes with normal attributes. However, in that migration we missed one
parameter for the qasm qobj instruction class which had no test coverage
in terra (and is only used by Aer), snapshot_type. This commit corrects
the oversight and adds test coverage to ensure we don't miss it in the
future.

Add missing parameter from QasmQobjInstruction

---

qiskit/qobj/qasm_qobj.py

In #3383 we removed marshmallow from the qobj objects a side effect of
this was the type coercion to something that was serializable with a
bare json.dumps() call was removed. In the majority of cases this wasn't
necessary as this was either something easily handled in a json
serializer class, or for aer (and other local simulators) are native
types that casting adds unnecessary overhead. However, there was one
edge case missed, the ParameterExpression class which is used for
parameterized circuits. This is a terra class and while it's easy to fix
in the ibmq provider for json serialization (although it hasn't been
yet, a PR will be pushed for this shortly) Aer doesn't have native
handling of this class. As a workaround until this is fixed the
QasmQobjInstruction's to_dict() method will …

Convert ParameterExpression to float in QasmQobjInstruction.to_dict()

---

qiskit/circuit/instruction.py
releasenotes/notes/list-params-1fa4c3f8b67ff57d.yaml

Adds `list` param setter case in `Instruction` class. This is used by expectation value snapshots in Aer.
We previous hacked around this not being supported by wrapping the lists as object Numpy arrays that were later converted back to list during assembly of Qobj, however the recent removal of Marshmallow classes broke this so we should add a proper fix.

Allow list params in Instruction

---

.travis.yml

This commit adds back the full battery of test jobs to the travis ci
config. We're in the middle of an azure pipelines outage and without
any acknowledgment from support or any indication that they're aware
of the issue. We've been blocked for more than 1 day because of this,
and with the 0.13.0 release fast approaching we need to have a
functional ci system running. This commit adds the full test matrix
we're using on azure back to travis which is still working. We can
revert this commit when azure is back running, because it is still
faster and has less resource contention. Azure also has windows jobs
which we can not get coverage for in travis.

Add back full travis config during azure pipelines outage

---

requirements.txt
setup.py

Retworkx 0.3.2 has been released[1] which fixed a perforamnce issue with
the ancestors and descendants functions (see mtreinish/retworkx#41 for
more details). As part of that fix the return type for the functions was
changed from a list to a set. This commit bumps the minimum to ensure
end users always get he performance fix.
[1] https://github.com/mtreinish/retworkx/releases/tag/0.3.2

Bump retworkx minimum

---

.mergify.yml

Since we're in the middle of an azure pipelines outage we've temporarily
switched to using travis as our sole ci provider (see #3973) until the
situation is resolve. However, the mergify config is hard coded to check
for azure pipelines to report success before continuing. This commit
updates the mergify config so that the automerge tag will continue to
work while we're relying on travis for all of our ci.

Update mergify config to require travis not azure

---

qiskit/visualization/latex.py
qiskit/visualization/matplotlib.py
qiskit/visualization/text.py
test/python/visualization/test_circuit_text_drawer.py

Fixes #3968 .
The CCZ gate was previously drawn as a double controlled box gate. It has been changed to be drawn as follows:
Additionally the 'mpl' version of CZ  gate was drawn as a controlled box gate. It has been updated to be drawn as below:

Drawing CCZ now consistent

---

qiskit/dagcircuit/dagcircuit.py
qiskit/transpiler/passes/basis/unroll_3q_or_more.py
qiskit/transpiler/passes/layout/csp_layout.py
qiskit/transpiler/passes/layout/layout_2q_distance.py
qiskit/transpiler/passes/layout/noise_adaptive_layout.py
qiskit/transpiler/passes/optimization/crosstalk_adaptive_schedule.py
qiskit/transpiler/passes/routing/basic_swap.py
qiskit/transpiler/passes/utils/check_cx_direction.py
qiskit/transpiler/passes/utils/check_map.py
qiskit/transpiler/preset_passmanagers/level0.py
qiskit/transpiler/preset_passmanagers/level1.py
qiskit/transpiler/preset_passmanagers/level2.py
qiskit/transpiler/preset_passmanagers/level3.py
test/python/circuit/test_unitary.py
test/python/test_dagcircuit.py
test/python/transpiler/test_csp_layout.py
test/python/transpiler/test_preset_passmanagers.py
test/python/transpiler/test_stochastic_swap.py

Preset pass managers were always decomposing swaps, which sometimes you don't want if the Swap is in the basis. This makes sure Unroller is called appropriately and removes an explicit calling of Decompose(Swap).
Furthermore this restructuring exposed a deficiency in `dag.twoQ_gates` and `dag.threeQ_or_more`, since they only find gates, whereas we may want non-gate (non-unitary) operations as well. I deprecated those two methods and added `dag.two_q_ops` and `dag.multi_q_ops`.
I tried to organize things into commits so it's easier to review.

Fix preset pass managers to not always decompose Swaps

---

qiskit/quantum_info/__init__.py
qiskit/quantum_info/operators/custom_iterator.py
qiskit/quantum_info/operators/symplectic/__init__.py
qiskit/quantum_info/operators/symplectic/pauli_table.py
qiskit/quantum_info/operators/symplectic/pauli_utils.py
releasenotes/notes/pauli-table-965fbb28c136af73.yaml
test/python/quantum_info/operators/symplectic/__init__.py
test/python/quantum_info/operators/symplectic/test_pauli_table.py
test/python/quantum_info/operators/symplectic/test_pauli_utils.py

Adds a `PauliTable` class that is an efficient representation of a list of N-qubit Pauli's. This class used a single boolean numpy array internally and all operations are implemented using vectorized numpy array operations for performance.
Includes a lot of utility methods for accessing and modifying parts of the table including:
* Allows array slicing notation to access sub parts of the table without copying the underlying array.
* Includes methods for sorting Pauli's in the table by lexicographic order or weight, deleting duplicate Paulis
* Includes custom iterators for iterating over the table and converting each Pauli to a string label or matrix.
* Finding rows that commute or anti-commute with another Pauli or set of Paulis

Add ``PauliTable`` symplectic operator class

---

qiskit/circuit/quantumcircuit.py

More efficient way to get current count when going through loop
Very small clean up/efficiency improvement in the count_ops() method in the QuantumCircuit class. No change in functionality.
The clean up made the code slightly shorter and (in my opinion) slightly more readable, and slightly more efficient in traversing the for loop. I am working on a different PR and thought of this small optimization so I thought I would create a separate PR for this before submitting my bigger PR. Thanks!

Small improvement to count_ops

---

qiskit/visualization/matplotlib.py
qiskit/visualization/qcstyle.py

Fixes #4012 .
The colour of the box and the control wires were different for ch, cy gates. matplotlib has been updated to get consistent colouring. Inconsistencies were also found in multi-control gates and have now been corrected.
The inconsistencies in colouring looked like:
The gates now look like:

Colouring in controlled gates now consistent

---

qiskit/quantum_info/operators/base_operator.py
qiskit/quantum_info/operators/channel/kraus.py
qiskit/quantum_info/operators/channel/quantum_channel.py
qiskit/quantum_info/operators/channel/stinespring.py
qiskit/quantum_info/operators/operator.py
qiskit/quantum_info/operators/scalar_op.py
qiskit/quantum_info/states/densitymatrix.py
qiskit/quantum_info/states/quantum_state.py
qiskit/quantum_info/states/statevector.py

Cleans up some of the internal code for default atol and rtol values used for float comparison in quantum info state and operator classes.
I'm not sure if its really necessary to raise deprecation warning for what was a private method of the classes, of if I should just delete the deprecated setters and be done with it.
* Changes the class variables (ATOL, RTOL, MAX_TOL) to be private (_ATOL_DEFAULT, _RTOL_DEFAULT, _MAX_TOL)
* Deprecates `_atol` and `_rtol` setters
* Adds class setters `_set_atol` and `_set_rtol` for changing default class values.

Clean up default class atol and rtol for operators and states

---

qiskit/quantum_info/states/quantum_state.py
releasenotes/notes/state-sample-measure-9710a22dfcb01ed6.yaml
test/python/quantum_info/states/test_densitymatrix.py
test/python/quantum_info/states/test_statevector.py

* Adds `sample_measure` function to `Statevector` and `DensityMatrix` for sampling measurement outcomes from the current state.
* Adds `seed` method to QuantumState for setting the seed of the objects internal RNG used for sampling measure outcomes.

Add ``sample_measure`` to ``Statevector`` and ``DensityMatrix``

---

qiskit/dagcircuit/dagnode.py
qiskit/dagcircuit/retworkx_dagcircuit.py

This commit caches the string sort key used for lexicographical
topological sort as an attribute in DAGNode objects. Currently when
retworkx's lexicographical topological sort call is called it needs to
call the python callable provided to get a string used for sorting.
Prior to this commit about ~70% of the cumulative time spent in the
lexicographical topological sort function is spent in python. This is
because every time it is sorting a DAGNode it has to call
str(x.qargs) which spends all that time constructing the string
including a dict.get() and bit and register repr() calls, etc. To avoid
this unnecessary overhead at run time this commit adds a sort_key
attribute to the DAGNode class which is set during `__init__()` and
updates to the qargs property. Then the DAGCircuit …

Cache lexicographical topological sort key in DAGNode

---

qiskit/circuit/controlledgate.py

Fixes #4031 
Previously the equality check for controlled gates was not checking whether `ctrl_state` was equal and `definition`. This pr fixes issue #4031 .

fix equality check for controlled gates. 

---

releasenotes/notes/add-pygments-dfe2cd949c237deb.yaml
setup.py

In #3861 a new requirement was added pygments used to do syntax
highlighting of QASM files. While that PR added it to the
requirements.txt file that isn't actually used by pip (see #1586) and
it needed to be added to the setup.py file too. This commit corrects
the oversight and adds pygments to the requirements list in setup.py.
Additionally this commit adds a release note documenting the addition of
a new dependency because it is a potential upgrade issue for users that
they'll need to be aware of when installing the next release.

Add pygments to requirements list in setup.py and document it

---

qiskit/assembler/assemble_schedules.py
test/python/compiler/test_assembler.py

Fix a critical bug where the Qobj sample pulse instruction did not have the same name as the pulse library pulse
Fix #4047

Bugfix: Instruction name / pulse library name mismatch

---

qiskit/compiler/transpile.py
qiskit/transpiler/pass_manager_config.py
qiskit/transpiler/preset_passmanagers/level0.py
qiskit/transpiler/preset_passmanagers/level1.py
qiskit/transpiler/preset_passmanagers/level2.py
qiskit/transpiler/preset_passmanagers/level3.py
releasenotes/notes/transpile-method-selectors-1c426457743a6fa7.yaml

Adding the ability to quickly select `layout_method` and `routing_method` from the top-level `transpile()` call. This configures the level 0-3 passmanagers to use the given methods for layout and routing. 
Something like this using `passmanager.replace()` is also doable but not as convenient due to the issue of conditions, control-flow, etc. surrounding the passes.
Generally I think there are a few basic & key steps to the compilation flow, each of which have several possible methods: optimization, placement, routing, scheduling, pulse selection. 
With `optimization_level`, `layout_method`, `routing_method` we cover the first 3. The 4th is in the form of `schedule(circuit, method)` right now.
Building a passmanager gives you ultimate control over how passes get chained, repeated until …

layout_method and routing_method selectors in transpile()

---

qiskit/transpiler/passes/utils/barrier_before_final_measurements.py
releasenotes/notes/3937-transpiler-pushes-gates-behind-measurements-3799753c21878237.yaml
test/python/transpiler/test_barrier_before_final_measurements.py

Fixes #3937 by extending the barrier added by `BarrierBeforeFinalMeasurements` to cover all dag qubits.

BarrierBeforeFinalMeasurements pass to insert device-wide barrier.

---

qiskit/circuit/quantumcircuit.py
qiskit/qasm/__init__.py
qiskit/qasm/pygments/__init__.py
qiskit/qasm/pygments/lexer.py
qiskit/tools/jupyter/library.py
releasenotes/notes/add-pygments-dfe2cd949c237deb.yaml
requirements-dev.txt
requirements.txt
setup.py

This commit switches to make pygments an optional dependency. Pygments
is solely a visualization requirement. It is used to provide syntax
highlighting for qasm code either in the qasm() circuit method or in a
jupyter widget. We typically do not add visualization dependencies to
the requirements list, so this commit remvoes it from the requirements
lists and adds it to the optional extras list for visualization. All the
uses of pygments are put behind try except blocks. It is added to
requirements-dev because while there are no tests for the pygments
output the docs build depends on it.
At the same time this bumps the minimum version we specified to a
working version. The minimum version of 2.2 was too low and caused
issues for users on 2.3.
Fixes #4048

Make pygments an optional dependency

---

qiskit/quantum_info/states/densitymatrix.py
qiskit/quantum_info/states/quantum_state.py
qiskit/quantum_info/states/statevector.py
releasenotes/notes/state-measure-reset-8a3f2df197325e9c.yaml
test/python/quantum_info/states/test_densitymatrix.py
test/python/quantum_info/states/test_statevector.py

Adds `measure` and `reset` methods to `Statevector` and `DensityMatrix` classes.
* `measure` samples a single measurement outcome for the specified subsystems, and collapses those systems to the post-measurement computational basis state.
* `reset` resets the specified subsystems to the |0> computation basis state (for statevectors this involves sampling a measurement outcome so is non-determinisitic).

Add measure and reset methods to QuantumState classes

---

qiskit/compiler/transpile.py
qiskit/execute.py
qiskit/transpiler/passmanager.py
releasenotes/notes/fix-3925-c0e40ece078f2ce1.yaml
releasenotes/notes/parameter_conflict_in_transpile-fc67d76288b480c4.yaml
releasenotes/notes/passmanager_parameter_in_transpile-9768d95afbe9127e.yaml
test/python/circuit/test_unitary.py
test/python/compiler/test_compiler.py
test/python/compiler/test_transpiler.py
test/python/transpiler/test_collect_2q_blocks.py
test/python/transpiler/test_commutative_cancellation.py
test/python/transpiler/test_consolidate_blocks.py
test/python/transpiler/test_cx_cancellation.py
test/python/transpiler/test_mappers.py
test/python/transpiler/test_optimize_1q_gates.py
test/python/transpiler/test_optimize_swap_before_measure.py
test/python/transpiler/test_pass_scheduler.py
test/python/transpiler/test_passmanager.py
test/python/transpiler/test_remove_diagonal_gates_before_measure.py
test/python/transpiler/test_remove_reset_in_zero_state.py
test/python/transpiler/test_resource_estimation_pass.py

If `transpile` is called with `pass_manager`, most of the additional parameters are already embed in the pass manager configuration and they are currently silently ignored.
This PR raises when that happen and includes a small refactor to reorganize the code.

Transpiler should raise when conflicting parameters, not just ignore them silently

---

qiskit/converters/circuit_to_gate.py
qiskit/schemas/backend_configuration_schema.json

Fixes #4064
When a user tries to convert a circuit to a gate and an instruction in the circuit is not a Gate, an error message appears. The code was changed to display which instruction caused the error message.

Fix issue #4064 by changing error msg in circuit_to_gate

---

qiskit/pulse/instructions/instruction.py
test/python/pulse/test_instructions.py

Fixed #4078 
Added a check in instructions.py __init__ to accept a numpy int for the duration value that was passed from a Delay instance.
Modified test_instructions.py to add a second call to Delay with a numpy int instead of a python int for duration.

Fixed #4078 by checking for numpy int and added test to TestDelay

---

qiskit/quantum_info/states/densitymatrix.py
qiskit/quantum_info/states/quantum_state.py
qiskit/quantum_info/states/statevector.py
releasenotes/notes/states-dep-028ed0ef6a7db02a.yaml
test/python/quantum_info/states/test_densitymatrix.py
test/python/quantum_info/states/test_statevector.py
test/python/quantum_info/test_counts.py

Deprecate unused or unneeded methods of quantum state class.
upgrade:
- |
The :class:`qiskit.quantum_info.Statevector` and 
:class:`qiskit.quantum_info.DensityMatrix` classes no longer copy the
input array if it is already the correct dtype.
deprecations:
- |
The ``add``, ``subtract``, and ``multiple`` methods of the
:class:`~qiskit.quantum_info.Statevector` and 
:class:`~qiskit.quantum_info.DensityMatrix` classes are deprecated.
Use ``+``, ``-``, ``*`` binary operators instead.
- |
The ``rep`` method of the :class:`~qiskit.quantum_info.Statevector` and 
:class:`~qiskit.quantum_info.DensityMatrix` classes is deprecated. Use
``isinstance`` to check for type instead.

Deprecate some unneeded methods of QuantumState

---

qiskit/transpiler/preset_passmanagers/level1.py
qiskit/transpiler/preset_passmanagers/level2.py

In #3999 we increased the number of trials, but the global benefit from
doing this isn't clear. With the pending release weighing the increased
run time for more trials against this, this commit temporarily reverts
the number of trials for level 1 and level 2 back to their previous
setting of 20. When we get to the bottom of #4094 and have a fix or
change for that we can increase the number of trials again.
Related #4094

Temporarily drop down number of trials for level1 and level2

---

qiskit/quantum_info/operators/symplectic/clifford.py
qiskit/quantum_info/operators/symplectic/clifford_circuits.py
qiskit/quantum_info/synthesis/clifford_decompose.py
releasenotes/notes/clifford-synthesis-42a959703bfc9c9a.yaml
test/python/quantum_info/operators/symplectic/test_clifford.py

Adds optimal compilation of Cliffords into circuits with the minimal number of CX gates for N <= 3 qubits.
This method is based on Bravyi & Maslov (arXiv:2003.09412 [quant-ph]), but does not require lookup tables for the 2 and 3 qubit case.
For N > 3 qubits, synthesis is done using general non-optimal decomposition from Aaronson and Gottesman.

Optimized clifford synthesis for up to 3 qubits

---

qiskit/transpiler/coupling.py
releasenotes/notes/coupling-map-name-b3bde705196bfe15.yaml

Follow up #4103, I think there is a risk of start using `CouplingMap.name` as an identificator. Using strings to identify objects showed to be a bad idea in the past. My suggestion is to rename the attribute to `description` to mitigate that possibility.

CouplingMap.name -> CouplingMap.description

---

qiskit/transpiler/passes/routing/lookahead_swap.py
test/python/transpiler/test_lookahead_swap.py

Resolves #2171 by adding a check that a candidate swap is able to either map at least one gate or improve the score of the resulting layout before it is considered. A follow up PR is needed to generalize this approach. (Ideally, this should be incorporated into `_score_step`, and we should make sure this does not limit our ability to find a long-range improvement that requires first passing through short-term loss).
Additionally, adds some debug level logging and removes duplicate edges for symmetric 2q gates from the list of available swaps.

Add LookaheadSwap condition to prevent hangs

---

qiskit/circuit/gate.py
qiskit/circuit/instruction.py
qiskit/converters/ast_to_dag.py
qiskit/extensions/quantum_initializer/diagonal.py
qiskit/extensions/quantum_initializer/initializer.py
qiskit/extensions/quantum_initializer/isometry.py
qiskit/extensions/quantum_initializer/mcg_up_to_diagonal.py
qiskit/extensions/quantum_initializer/squ.py
qiskit/extensions/quantum_initializer/uc.py
qiskit/extensions/standard/barrier.py
qiskit/extensions/unitary.py
test/python/circuit/test_extensions_standard.py
test/python/visualization/test_circuit_text_drawer.py

This change has some unforseen backwards compatibility implications and
is causing downstream projects like qiskit-aer to fail CI now. Given the
pending release and this not being critical, this commit reverts this
commit and we can revisit it after the 0.13.0 release.
This reverts commit 5afe87ce1e5279ca716fdf5a3c478f2e27a6519f.

Revert "Moving up some parameter checks in the class hierarchy (#3668)"

---

qiskit/pulse/schedule.py
test/python/pulse/test_schedule.py

Fix #4120 - Remove renaming the schedule after using `exclude` and `filter`

---

qiskit/transpiler/passes/optimization/_gate_extension.py
qiskit/transpiler/passes/optimization/hoare_opt.py

On Python 3.5, a non existing module will raise `ImportError` instead of `ModuleNotFoundError`

Fix import exception of Z3 package to be compatible with python 3.5

---

qiskit/circuit/instruction.py
test/python/circuit/test_initializer.py

Fixes #4151 by re-ordering instruction parameter type checks so that numpy checks and conversion occur before checks for built-in python types.

Fix conversion of numpy.number instruction params to python types.

---

qiskit/extensions/standard/rzx.py

Fixes definition of `RZXGate` to use `RZGate` in its definition rather than `U1Gate`. 
This is to be consistent with the other Pauli rotation gates which use `RZGate`. It also means that the phase-difference in the canonical matrix definition and the unrolled gate matrix from `Operator(gate)` is localized to the `RZGate`.

Use RZGate in RZXGate definition

---

qiskit/extensions/standard/x.py
qiskit/visualization/latex.py

Fixes #4039.
Add a check on the ancilla input on the `QuantumCircuit.mcx` and `mct` methods by calling `QuantumCircuit.qbit_argument_conversion(q_ancillas)`.

Check circuit.mcx() ancilla input

---

qiskit/extensions/unitary.py

The `._definition`s of two-qubit `UnitaryGate`s are currently `QuantumCircuit` instances, instead of the list of `(inst, qargs, cargs)` tuples used for other gates. This passes the `Unroller` because `QuantumCircuit` has a `__len__` and a `__getitem__` that will iterate through `qc.data`.
This PR sets the definition to be a list of `(inst, qargs, cargs)` tuples, in line with how definitions are set for other gates.

Remove QuantumCircuit instance from UnitaryGate.definition.

---

qiskit/circuit/library/basis_change/qft.py
test/python/circuit/test_library.py

Add `is_inverse` to the QFT and allow to directly build the inverse QFT.
We need to be able to distinguish between the inverse and non-inverse QFT, also this fixes the potential bug 
```python
iqft = QFT(2).inverse()
iqft.do_swaps = False  # is reset and the normal QFT, not IQFT, is built
```

Add correct inverse functionality to QFT

---

test/python/quantum_info/operators/test_random.py
test/randomized/test_clifford.py

Fixes #4126 
This PR makes `test.python.quantum_info.operators.test_random.TestRandomClifford.test_valid` deterministic and moves the non-deterministic part to `test/randomized/test_clifford.py`

deterministic test/python/quantum_info/operators/test_random.py

---

qiskit/qobj/converters/pulse_instruction.py
qiskit/schemas/qobj_schema.json
test/python/qobj/test_pulse_converter.py

pulse_instruction.py and pulse2sq2.py did not have the same name for SetFrequency.
* Changed name from `sf` to `setf`
* Added SetFrequency to the schemas

* Fixed SetFrequency name sf -> setf in pulse instructions.

---

qiskit/circuit/quantumcircuit.py
qiskit/dagcircuit/dagcircuit.py
releasenotes/notes/circuit-compose-c320c4057cd2bb8f.yaml
test/python/circuit/test_compose.py
test/python/dagcircuit/test_compose.py

Compose two circuits (without having to turn one into a gate). Uses dag.compose() under the hood.

add circuit.compose() method

---

qiskit/circuit/instruction.py
releasenotes/notes/instruction.is_parameterized-to-check-if-fully-bound-f1004abf10f15930.yaml
test/python/circuit/test_parameters.py

This causes a failure of TestKAKOverOptim.test_cu1_optimization after
switching to BasisTranslator. For CU1, the Unroller will generate
U1Gate(pi/2), ..., but the BasisTranslator will generate a (still
valid) U1Gate(ParameterExpression(pi/2)).

Instruction.is_parameterized to return False when fully bound.

---

qiskit/dagcircuit/dagcircuit.py

There were several places deprecation warnings are emitted in the
DAGCircuit class. However, none of these deprecations set a stacklevel
kwarg which means the default of 1 is used. This means the deprecation
warnings refer to the warn() line as the source of the deprecation
instead of the caller of the function. This commit corrects this
oversight by adding stacklevel=2 which will show the caller as the
source of the deprecation warning.

Add missing stacklevel param from dagcircuit DeprecationWarnings

---

qiskit/extensions/standard/x.py

In #4076 the multi-controlled X was changed to use the default no-ancilla versions of the 3-controlled and 4-controlled X gate. If ancilla qubits are available, these are not the most efficient implementations in terms of gate count, therefore they should not be chosen by default.
Additionally to that, for a reason yet not clear, this breaks the `v-chain` mode if used in Grover search and it's oracles.

No C3X and C4X by default

---

azure-pipelines.yml
requirements-dev.txt
test/python/transpiler/test_hoare_opt.py

The z3-solver package isn't precompiled on macOS (there is an open issue
about this Z3Prover/z3#2800) so on CI jobs when running on macOS we spend a
great deal of time (typically >10min for each macOS job) building z3 from
source. This is delaying everyone's development and is just wasting time. This
commit removes z3-solver from the requriements-dev.txt list and manually
installs it on linux and windows CI jobs where precompiled binaries are
available.

Make z3-solver opt-in for testing

---

qiskit/extensions/quantum_initializer/ucrx.py
qiskit/extensions/quantum_initializer/ucry.py
qiskit/extensions/quantum_initializer/ucrz.py

As a follow up to #4243 there was a pylint error for a cyclic import
raised by the isometry module which stemmed from importing classes from
the base 'qiskit' namespace. Those aliases are added for end user
convenience and shouldn't be accessed directly in any module from the
code. This commit goes through the remaining places where things are
imported directly from 'qiskit' and updates them to use the full module
path.

Fix potential cyclic imports

---

azure-pipelines.yml

Right now the compiled docs upload to the artifact store is a bottleneck
for a CI throughput. In an attempt to speed it up this commit sets the
parallel option on the task [1]. This will hopefully reduce the amount
of time spent uploading files to the artifact store.
[1] https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/utility/publish-build-artifacts?view=azure-devops

Compress built docs before upload

---

qiskit/quantum_info/operators/symplectic/random.py
releasenotes/notes/fix-random-clifford-cff2b266c8ad7e2d.yaml

Fixes #4271 
A typo in `_sample_qmallows` function was preventing `random_clifford` from sampling the full Clifford group.
Running 10k samples for N=1 and N=2 now samples the full group:

Fix bug in random_clifford

---

azure-pipelines.yml

Currently the azure pipelines jobs are not being cancelled for PR
updates before a job finishes. According to the docs [1] this is
supposed to be default 'true' however we have had issues with implicit
defaults in the past on azure. This commit makes the configuration
explicit in the hope that it will re-enable the feature and improve
CI throughput.
[1] https://docs.microsoft.com/en-us/azure/devops/pipelines/repos/github?view=azure-devops&tabs=yaml#multiple-pr-updates

Set autoCancel on azure pipelines pr trigger

---

azure-pipelines.yml

As follow up to #4343 and the third attempt to get auto cancellation to
work fully this commit removes conditions from all job definitons and
decouples the test/pr stage from the wheel build stage. Without this the
stage is still getting triggered despite the auto cancellation or always
being skipped. This should hopefully be the last attempt as currently the
second stage is getting cancelled (at least some of the time) which
means the config is partially working.

Remove conditional execution for jobs in azure-pipelines

---

qiskit/extensions/unitary.py

The PR https://github.com/Qiskit/qiskit-terra/pull/4259 imports `Isometry` from `qiskit.extensions.quantum_initializer.isometry` while  ` `qiskit.extensions.quantum_initializer.isometry` was already in scope.

unnecessary import in UnitaryGate.control

---

qiskit/circuit/library/arithmetic/integer_comparator.py

The `IntegerComparator` circuit uses the `circuit.OR` (deprecated) instead of the `OR` boolean logic circuit and leads to a lot of deprecation warnings in both Terra and Aqua.
Use `OR(num_qubits)` instead of `self.OR`

Fix deprecations coming from circuit.OR

---

qiskit/quantum_info/states/densitymatrix.py
qiskit/quantum_info/states/statevector.py
releasenotes/notes/quantum-state-from-int-20a91dc5d4c62dbb.yaml
test/python/quantum_info/states/test_densitymatrix.py
test/python/quantum_info/states/test_statevector.py

Allows initializing a statevector in the state |i>, and density matrix in state |i><i| for specified subsystem dimensions.

Add ``from_int`` method to ``Statevector`` and ``DensityMatrix``

---

qiskit/circuit/equivalence.py
releasenotes/notes/equiv-lib-draw-8f3c4bd897a2fa6c.yaml

The EquivalenceLibrary.draw() method was recently added in #4196, but
was missing a few things. Most critically was the ImportError message
for handling the missing optional visualization dependencies. This
commit reworks the import structure so that run time imports are avoided
and instead the optional dependencies missing are handled at import time
and at runtime if they're not present but are required a descriptive
error message is raised. At the same time a filename kwarg is added so
that instead of just outputting a pillow Image object a user can write
the visualization to disk. Then a release note is added to document the
new feature when it comes time to release 0.15.0.

Small tweaks to EquivalenceLibrary.draw()

---

azure-pipelines.yml

Azure pipelines caching task does not update the cached data for a given
key after it's been stored. This means our pip cache is never being
updated. So the effects of #4346 can't be seen because the built wheels
are not actually being cached between runs. Also, when new versions of
requirements are released the cache will not be updated with them
either which will eventually mean we have no cache hits. This commit
updates the key string used for the cache to include the build number
meaning we will always upload the contents of the pip cache after each
run. This will enable storing new entries in the cache so we keep it up
to date.

Actually update pip cache on each run

---

qiskit/pulse/schedule.py
test/python/pulse/test_schedule.py

Issue: #4171
This commit adds a ```__len__``` function to the ```Schedule``` class in Pulse, allowing users to obtain the number of instructions present in that ```Schedule``` object with ```len()```.
Enabling the use of ```len()``` on a ```Schedule``` object also allows for checking if a schedule is empty. It acts as a replacement for bool() in the following situation - ```if not Schedule(): print('Empty')```, which will now print 'Empty'.
Tests related to the above were written in ```test/python/pulse/test_schedule.py``` by asserting that an empty schedule is ```False``` and ```len()``` equal to zero. Asserting the equality of ```len()``` and number of instructions appended to a schedule at each step were also tested.
Although ```__len__``` being based on ```self.instructions``` is a …

Add __len__ to Schedule in Pulse along with related tests.

---

qiskit/visualization/pulse/matplotlib.py

`schedule.draw(channels=channels)` was failing because `schedule.duration` should have been used, not `schedule.timeslots.duration`

Fix bug in visualization/pulse/matplotlib

---

docs/conf.py
requirements-dev.txt

`jupyter_sphinx` has a new version that gives a warning in docs.  Since warnings are fatal, this is not good.  This should fix that. Additionally, a new ddt release has been pushed which is broken (see datadriventests/ddt#83) which is blocking the CI too. This commit combines the fixes for both so CI can be unblocked again.

Unblock CI with fix for new jupyter execute and pin ddt

---

qiskit/result/postprocess.py

Currently aer is returning a list of complex numbers instead of a numpy
array for statevectors in it's result class. Now that marshmallow isn't
coercing the types anymore this is not getting coverted to a list of
lists of complex components and the postprocessing to normalize
statevectors is incorrectly trying to convert the complex numbers to
complex numbers. This commit fixes this by handling the case where we
receieve a list of complex numbers. Ideally longer term aer will be
updated to return a numpy array for statevectors so that the post
processing just gets skipped.

Handle aer's current return format

---

docs/conf.py
requirements-dev.txt

* fix for new jupyter execute
* Pin ddt to avoid broken release
The recent ddt 1.4.0 release does not work (see datadriventests/ddt#83)
and is blocking CI. This commit blacklists the new version in the
dev requirements list so we can run tests again.
Co-authored-by: Matthew Treinish <mtreinish@kortar.org>
Backported from #4407
(cherry picked from commit 534d70a322184f94c446aee740b5db383049efbf)

[Stable] Unblock CI with fix for new jupyter execute and pin ddt (#4407)

---

qiskit/extensions/unitary.py

@ajavadia found the following issue in master:
```python
from qiskit.extensions import UnitaryGate
circ = QuantumCircuit(2)
u = UnitaryGate([[1,0], [0,1]], label='my gate')
circ.compose(u.control(1), [0,1], inplace=True)
print(circ)
```
```
q_0: ───────■────────
┌──────┴───────┐
q_1: ┤ circuit57_dg ├
└──────────────┘
```
With this PR, here is the output:
```
q_0: ─────■─────
┌────┴────┐
q_1: ┤ my gate ├
└─────────┘
```

Label support for controlled unitary

---

qiskit/converters/circuit_to_gate.py
qiskit/converters/circuit_to_instruction.py
releasenotes/notes/converters-equivalence-library-registration-optional-266758d497d82ce3.yaml
test/python/circuit/test_equivalence.py

Add equivalence_library kwarg to circuit_to_{gate,inst} converters.
Make gate registration on circuit_to_{gate,inst} conversion opt-in.
Resolves #4414 .

Add equivalence_library kwarg to circuit_to_{gate,inst} converters.

---

qiskit/quantum_info/states/densitymatrix.py
test/python/quantum_info/states/test_densitymatrix.py

This is handy when you have a circuit in a product state and you want the reduced state as a statevector (e.g. discarding an uncomputed ancilla).

add DensityMatrix.to_statevector() for pure states

---

qiskit/compiler/assemble.py
qiskit/execute.py
qiskit/schemas/examples/qobj_openpulse_example.json
qiskit/schemas/examples/qobj_openqasm_example.json
qiskit/schemas/qobj_schema.json
releasenotes/notes/add-init-qubits-option-ea1844f88fcddcf6.yaml
test/python/compiler/test_assembler.py

Users can request a reset instruction. This can be done with `reset` in the program. To request that no initialization sequence happen, `init_qubits` should be set to False. No reset and no `init_qubits` will default to including an initialization sequence.
**tldr; I added 3 questions in the "Files changed".**
As I have it now, the qobj schema default for init qubits is True, but I'm not sure where this default takes effect.
The default value for `init_qubits` in execute is True.
The default value for `init_qubits` in assemble is to not be included.
What are the right values for these cases? If it's not supplied, the default should be True right now, but I hear that eventually we will want the default to be False. I think the default for execute and assemble should be the same, not sure …

Add init qubits flag to qobj

---

qiskit/transpiler/preset_passmanagers/level0.py
releasenotes/notes/level0_RemoveResetInZeroState-942c0fb19cb6c087.yaml
test/python/transpiler/test_preset_passmanagers.py

Transpiler optimization level 0 should not remove the reset instructions.

Removing RemoveResetInZeroState from transpiler optimization level 0

---

qiskit/providers/models/backendproperties.py
test/python/providers/test_backendproperties.py

Small change to how conversions to SI are done in Qiskit, so very small numbers (e.g. 1e-12) are never used, which could cause distortions to precision. This was causing some issues when converting `gate_length`s to `dt` (did not become multiple of dt).

improve floating point precision in backend properties

---

requirements-dev.txt
tox.ini

In the recent reno release 3.1.0 the sphinx extension config option
'parallel_read_safe' was set to true. [1] This makes it possible to run
sphinx builds with reno in parallel without a warning being raised. This
commit does just that and adds '-j auto' to the default sphinx build
command in the tox docs job. This should hopefully speed up the docs
builds in CI (although the degree to which is limited by the available
resources in the CI nodes) and for local builds.
[1] https://opendev.org/openstack/reno/commit/cc09e3d38c2c1046a529270f133de525c0692809

Enable parallel docs builds and bump reno min version

---

qiskit/transpiler/passes/__init__.py
qiskit/transpiler/passes/basis/__init__.py
qiskit/transpiler/passes/basis/basis_translator.py
qiskit/transpiler/passes/basis/unroll_custom_definitions.py
releasenotes/notes/add-basistranslator-pass-d5e7de69ab9f20a1.yaml
test/python/transpiler/test_basis_translator.py
test/python/transpiler/test_unroll_custom_definitions.py
test/python/transpiler/test_unroller.py

Adds BasisTranslator and UnrollCustomDefinition passes from https://github.com/Qiskit/rfcs/pull/6 . `UnrollCustomDefinitions` unrolls all instructions in the circuit according to their `.definition` property, stopping when reaching either the specified `basis_gates` or a set of gates in the provided `EquivalenceLibrary`. `BasisTranslator` searches over the set of translations in the provided `EquivalenceLibrary` to re-write circuit instructions in a specified basis.
~on-hold for #4431 .~

Add BasisTranslator and UnrollCustomDefinitions passes.

---

qiskit/providers/models/pulsedefaults.py
releasenotes/notes/remove-circuit-instruction-map-37fb34c3b5fe033c.yaml

Remove `circuit_instruction_map` attribute from `PulseDefaults` which had been deprecated and replaced with `instruction_schedule_map` in Terra release 0.12.0.

Remove circuit_instruction_map deprecated attribute

---

qiskit/quantum_info/synthesis/two_qubit_decompose.py

Deprecration notice for 'euler_angles_1q' said 'euler_angles_q1'.

Correct typo in deprecation warning

---

qiskit/circuit/quantumcircuit.py

The link to the Gate class in the documentation of the circuit methods currently doesn't work. This PR fixes this.
The docstrings linked to `qiskit.circuit.library.standard_gates` but should link to `qiskit.circuit.library` instead to work.

Fix the circuit gate links in docs

---

examples/python/ibmq/hello_quantum.py

The hello_quantum example was repeatedly failing because it usually selected the 1-qubit Armonk provider, but it needs two qubits to run.
I've added a filter to ensure that only usable providers are selected.
There are no automated tests for this example, but it now runs on my machine. (I know, I know...)
Fixes #4510

Restrict hello_quantum ibmq example script to backends with at least two qubits

---

qiskit/circuit/controlledgate.py
test/python/circuit/test_controlled_gate.py

The controlled gate definition property was being evaluated and it was
an controlled X gate with an open control the generated definition
would reference itself because the working definition becomes defined
with self as an element in the list. That meant whenever the definition
was fully expanded ControlledGate.definition would infinitely recurse.
To workaround this issue this commit adds a shallow copy to break the
reference loop.
Fixes #4512

Fix infinite recursion in controlled gate definition

---

qiskit/circuit/controlledgate.py
test/python/circuit/test_controlled_gate.py

This reverts commit 8771e595a67e584f7ce1bac2d70db84516cd3432. The fix
did not actually work and was missed because of typo in the tests from
the reproduce case. There is still an infinite recursion present when
the test is fixed. More debug and investigation will be needed to fix
this bug for real. Until then this reverts the commit which didn't work.

Revert "Fix infinite recursion in controlled gate definition (#4513)"

---

qiskit/circuit/quantumcircuit.py
releasenotes/notes/circuit-repeat-8db21ef8d8c21cda.yaml
test/python/circuit/test_circuit_operations.py
test/python/circuit/test_parameters.py

Implement `circuit.repeat(reps)` to return a circuit containing `reps` repetitions of the original.
Use-cases:
1. Avoid explicitly casting to an Instruction to do this
2. Circuit library objects may know an efficient way of repeating themselves, so we need to be able to overwrite `repeat`

Add circuit.repeat

---

qiskit/assembler/assemble_schedules.py
qiskit/pulse/commands/acquire.py
qiskit/pulse/instructions/acquire.py
qiskit/pulse/transforms.py
qiskit/qobj/converters/pulse_instruction.py
qiskit/scheduler/utils.py
releasenotes/notes/remove-multi-acquires-747701103ddd816c.yaml
test/python/compiler/test_assembler.py
test/python/pulse/test_schedule.py

The properties ``acquires``, ``mem_slots``, and ``reg_slots`` of the
:class:`qiskit.pulse.instructions.Acquire` pulse instruction have been
deprecated.
The option to Acquire multiple qubits at once was deprecated in Terra
release 0.12.0 and is now removed. Specifically, the init args
``mem_slots`` and ``reg_slots`` have been removed from 
:class:`qiskit.pulse.instructions.Acquire`, and ``channel``, ``mem_slot``
and ``reg_slot`` will raise an error if a list is provided as input.

Remove deprecated multi-qubit acquire instructions

---

releasenotes/notes/0.9/changes-on-upgrade-6fcd573269a8ebc5.yaml
releasenotes/notes/0.9/missing-changelog-d8129ba95dde3156.yaml
releasenotes/notes/0.9/new-features-0.9-159645f977a139f7.yaml

Few reno indentation errors show up sometimes when running `tox -edocs`.

Fix reno indentation errors that shows up during `tox -edocs`

---

requirements-dev.txt

Sphinx released 3.1.0 yesterday which has introduced 1821 warnings to
the terra docs builds. Until these can all be fixed the CI jobs are
failing because we enforce no warnings as sphinx warnings almost always
point to real docs bugs. This commit pins the sphinx version we use for
testing and local builds until we can fix all the newly introduced
warnings.

Pin sphinx version temporarily

---

qiskit/dagcircuit/dagcircuit.py
qiskit/dagcircuit/dagdependency.py
qiskit/transpiler/passes/layout/csp_layout.py
qiskit/transpiler/passes/layout/noise_adaptive_layout.py
qiskit/transpiler/passes/optimization/consolidate_blocks.py
qiskit/transpiler/passes/optimization/hoare_opt.py
qiskit/transpiler/passes/routing/basic_swap.py
qiskit/transpiler/passes/routing/layout_transformation.py
qiskit/transpiler/passes/routing/lookahead_swap.py
qiskit/transpiler/passes/routing/stochastic_swap.py
qiskit/transpiler/passes/utils/barrier_before_final_measurements.py
qiskit/visualization/utils.py
releasenotes/notes/deprecate-dag-qubits-method-0a61b37fa4a5bcd5.yaml
test/python/dagcircuit/test_dagdependency.py

Fixes #4484 
The list of qubits and clbits of a dag were being recreated every time `dag.qubits()` and `dag.clbits()` methods were called, which was slow. Here I make them cached properties. Being properties is also aligned with how they are in QuantumCircuit.

Cache dag qubits/clbits

---

requirements-dev.txt

Sphinx released 3.1.0 yesterday which has introduced 1821 warnings to
the terra docs builds. Until these can all be fixed the CI jobs are
failing because we enforce no warnings as sphinx warnings almost always
point to real docs bugs. This commit pins the sphinx version we use for
testing and local builds until we can fix all the newly introduced
warnings.
Backported from #4556 
(cherry picked from commit 2dad686009ea84247f43cbec05e02cf28d3d233a)

[Stable] Pin sphinx version temporarily (#4556)

---

qiskit/extensions/unitary.py
test/python/circuit/test_controlled_gate.py

Fix #4549
The control() method in UnitaryGate did not include the num_ctrl_bits or ctrl_state parameters when making a call to ControlledGate.

Added num_ctrl_bits and ctrl_state to UnitaryGate call to ControlledGate

---

qiskit/dagcircuit/dagcircuit.py
test/python/dagcircuit/test_dagcircuit.py
test/python/transpiler/test_layout_transformation.py

In #4535 `dag.qubits()` and `dag.clbits()` are being deprecated. We should stop using them in our tests.

Stop using dag.qubits() and dag.clbits() while testing, as deprecated in #4535

---

qiskit/circuit/library/data_preparation/zz_feature_map.py
releasenotes/notes/fix-zz-feature-map-barriers-ab1a2d930a6b5af1.yaml

The ``insert_barriers`` keyword argument in the ``ZZFeatureMap`` class
didn't actually insert barriers in between the Hadamard layers and 
evolution layers. This has been fixed.

Fix ZZFeatureMap barriers

---

qiskit/circuit/instruction.py
qiskit/circuit/library/arithmetic/polynomial_pauli_rotations.py
qiskit/circuit/quantumcircuit.py
qiskit/extensions/quantum_initializer/initializer.py
qiskit/quantum_info/operators/operator.py
releasenotes/notes/circuit-reverse-bits-ce1873a89b06e3df.yaml
test/python/circuit/test_circuit_operations.py
test/python/circuit/test_instructions.py
test/python/circuit/test_parameters.py

Adding an operation `reverse_bits` to reverse the order of bits in a circuit. This helps in making circuits written in big-endian convention into little-endian and vice versa.
Also a previous method `mirror()` is now called `reverse()`. This is to avoid confusion with mirror gates (e.g. [here](https://arxiv.org/abs/quant-ph/0407108) and [here](https://arxiv.org/pdf/1811.12926.pdf)).

Circuit reverse_bits operation

---

qiskit/transpiler/passes/basis/unroll_3q_or_more.py
releasenotes/notes/large_gate_bugfix-cbf0b6f1dcfbd5dd.yaml
test/python/transpiler/test_unroll_3q_or_more.py

No longer crashes upon unrolling of some gates with more than 2 qubits. Required simple fix of throwing away empty operations when looping through 3+ qubit gates (used to just crash when it saw this).

fixes issue of crashing on unroll of 3+ qubit gates (#4577).

---

qiskit/circuit/library/standard_gates/equivalence_library.py
qiskit/compiler/transpile.py
qiskit/quantum_info/synthesis/two_qubit_decompose.py
qiskit/transpiler/passes/optimization/collect_2q_blocks.py
qiskit/transpiler/passes/optimization/consolidate_blocks.py
qiskit/transpiler/passmanager_config.py
qiskit/transpiler/preset_passmanagers/level0.py
qiskit/transpiler/preset_passmanagers/level1.py
qiskit/transpiler/preset_passmanagers/level2.py
qiskit/transpiler/preset_passmanagers/level3.py
releasenotes/notes/add-basistranslator-to-default-levels-1c0de250f8ca4a59.yaml
test/python/circuit/test_extensions_standard.py
test/python/circuit/test_gate_definitions.py
test/python/compiler/test_transpiler.py
test/python/transpiler/test_basis_translator.py
test/python/transpiler/test_consolidate_blocks.py

Resolves #3146
Resolves #3086
- Fix free param calculation in standard gates to_matrix test.
Previous code mis-calculated the number of available free parameters
from the gate signature, resulting in creation of gates like
XGate(label=0.1). These would cause errors if the circuits containing
these gates were drawn.
-  Remove definition for C3XGate, C4XGate due to name conflict with MCXGate.
-  Add Rz->RX,RY, U3->RX,RY, CX->RXX to StandardEquivalenceLibrary.
Updates BasisTranslator-Unroller compatability test
test_basis_translator.TestUnrollerCompatibility.test_unroll_all_instructions
to verify the generated circuit is equivalent (with snapshot,
measure instructions removed) as the circuit transpiled by the
BasisTranslator is no longer gate-for-gate equal with that of the
Unroller.
- Add …

Adds BasisTanslator, UnrollCustomDefinitions to default levels.

---

qiskit/circuit/parameterexpression.py
releasenotes/notes/parameter-conjugate-a16fd7ae0dc18ede.yaml
test/python/circuit/test_parameters.py

Adds `conjugate` to the `ParameterExpression`. Since they are real, conjugate returns self. 
This adds flexibility and convenience, since real numbers in Python (such as float) also support this.
This is analogous to real numbers in Python,
```python
>>> import numpy
>>> numpy.conj(float(1)) 
1.0
>>> numpy.conj(Parameter('x'))  
x  # before: TypeError: loop of ufunc does not support argument 0 of type Parameter which has no callable conjugate method
```

Parameter conjugate

---

qiskit/compiler/assemble.py
qiskit/execute.py
qiskit/qobj/pulse_qobj.py
qiskit/schemas/qobj_schema.json
test/python/compiler/test_assembler.py

Fixes #4618
Fix a bug causing schema validation to fail from https://github.com/Qiskit/qiskit-terra/pull/4539. 
- Added back old schema which works w/ IBM Quantum Experience
- Cast `rep_time` to integer as was done previously

Fix schema bug in `rep_delay` addition

---

qiskit/pulse/pulse_lib/sample_pulse.py

Should partially resolve #4599. I'm not sure what changed in numpy 1.19 to cause this, but this appears to be a resolution.

fix sample pulse normalization

---

qiskit/transpiler/passes/layout/sabre_layout.py

The seed was not being set as part of the sabre_layout pass. This commit corrects the oversight.

set seed for sabre_layout

---

qiskit/transpiler/passes/routing/cython/stochastic_swap/swap_trial.pyx

This commit switches the set data structure we use for a set in the
stochastic swap trial. C++'s std::set is backed by an RB Tree while
std::unordered_set is a hashset. For the use in swap_trial all we ever
do is a lookup via `count()` and `erase()` to remove elements from the set
after it's initially constructed. The lookup for an RB tree is O(log n)
vs O(1) for a hash set. While for small number of qubits this doesn't
matter too much, but as the number of qubits grows this makes a
noticeable difference.

Switch from std::set to std::unordered set in swap_trial

---

test/python/transpiler/test_hoare_opt.py

The tests for the hoare optimization pass were emitting deprecation
warnings because they were manually creating DAGNode objects and
passing in the parameters as a dictionary instead of kwargs. This was
deprecated in #4086 and actually adds some overhead. This commit fixes
this oversight and uses kwargs for the test's DAGNode creation.

Fix deprecation warnings in hoare optimization tests

---

qiskit/quantum_info/operators/channel/superop.py
qiskit/quantum_info/operators/operator.py
qiskit/quantum_info/operators/symplectic/clifford_circuits.py

Fixes #4590 
Includes handling for barriers when constructing operators (Operator, Clifford, QuantumChannel types) from circuits.

Fix initializing operators from circuits containing barriers

---

qiskit/extensions/quantum_initializer/initializer.py

`Instruction.mirror` is deprecated by `reverse_ops`, this emits a lot of deprecation warnings depending on the application.

Use reverse_ops instead of mirror in initializer

---

qiskit/__init__.py
qiskit/circuit/__init__.py
qiskit/circuit/quantumcircuit.py
qiskit/circuit/quantumregister.py
releasenotes/notes/ancilla-qubit-cdf5fb28373b8553.yaml
test/python/circuit/test_circuit_registers.py

Add the concept of ancilla qubits, which wrap the qubit type but allow 
to mark certain qubits as ancillas. This allows to re-use these work qubits 
in larger circuits and algorithms or during transpilation. 
Ancilla qubits are qubits. They can be acted on as usual qubits and asking the circuit for its qubits will return the 
ancillas as well. This type is just an additional information that can be used in circuit construction and optimization.
This is also useful for circuits in the library where the circuit can explicitly mark which qubits are only used 
as intermediary work-qubits whose state is again `|0>` after the circuit operation.
The types are called ``AncillaRegister`` and ``AncillaQubit``.
With ``QuantumCircuit.num_ancillas`` the number of ancilla qubits is returned and …

Ancilla qubit type

---

qiskit/quantum_info/states/statevector.py

Improves performance of the evolve method for the the `Statevector` class by explicitly using Numpy transpose + dot instead of einsum.
Co-Authored-By: Yuchen Pang <yuchenpang@users.noreply.github.com>
This can give up to a good speed up when evolving by 2+ qubit operators.

Improve performance of Statevector.evolve

---

azure-pipelines.yml

Right now CI jobs are failing because of the dep solver because of a
version conflict between 'aws-sam-cli' and the dateutil version terra
requires. We're not installing aws-sam-cli as it's not in the dependency
tree for terra, so presumably it's coming from the system python
environment. This commit uses virtualenv to create an isolated
environment for running tests to avoid these types of interactions in
the future.

Isolate ci test environment with virtualenvs

---

qiskit/quantum_info/states/densitymatrix.py
qiskit/quantum_info/states/quantum_state.py
qiskit/quantum_info/states/statevector.py
releasenotes/notes/quantum_state_expval-18359552aab42343.yaml
test/python/quantum_info/states/test_densitymatrix.py
test/python/quantum_info/states/test_statevector.py

Adds expectation value method to Statevector and density matrix classes for computing the expectation value of an operator.
This is a simple implementation which leaves room for future optimizations for different operator types.

Add ``expectation_value`` function to ``Statevector`` and ``DensityMatrix``

---

qiskit/circuit/quantumcircuit.py
test/python/circuit/test_circuit_operations.py

The cnot method for QuantumCircuit was broken when using positional
arguments that weren't named. This is because it was upassing in the
kwargs which aren't used from deprecated_arguments to the cx method.
The kwargs are only used as a placeholder for passing in args by name
from the old deprecated name and the conversion is handled by the
decorator. This commit fixes this oversight so that QuantumCircuit.cnot
works as expected.
Fixes #4708

Fix cnot method on QuantumCircuit

---

qiskit/providers/models/backendconfiguration.py
qiskit/providers/models/backendproperties.py
qiskit/providers/models/jobstatus.py
qiskit/providers/models/pulsedefaults.py
test/python/providers/test_backendconfiguration.py
test/python/providers/test_backendproperties.py
test/python/providers/test_pulse_defaults.py

The provider model classes were built as subclasses for
`SimpleNamespace`, primarily because they allow attribute access for
arbitrary kwargs from the constructor and `SimpleNamespace` makes that
easy. Unfortunately this adds a great deal of complexity if the subclass
has required positional arguments, since the parent class signature for
`SimpleNamespace` is just **kwargs. For example, when using pickle to
serialize the object (often as part of a deecopy or multiprocessing) it
relies on the `__reduce__` from the parent class which is configured to
only handle **kwargs and it will fail because of missing required
positional arguments. `QasmBackendConfiguration `attempted to fix this by
defining a custom `__reduce__` method to pass in the required args, but
then pickle would miss the …

Fix pickling for provider models by removing SimpleNamespace

---

qiskit/visualization/latex.py

closes  #4692
As per issue #4692 , `aliases` was passed strangely and not accessible through the circuit drawer. It also didn't seem to get used.
This pull request removes it from `latex.py`.

remove aliases from visualization/latex.py

---

qiskit/visualization/state_visualization.py

In the recently released matplotlib 3.3.0 release matplotlib started
enforcing that the number of ticklabels matches the number of tick
locations. [1] This ends up breaking on the plot_state_hinton()
visualization function because the hinton plot was not setting a label
for the implicit tick at the top of the graph, even though there is no
value for it. This commit fixes this by just setting a blank label for
the unused tick so that the visualization will still work on matplotlib
3.3.0.
[1] https://matplotlib.org/3.3.0/api/api_changes.html#axis-set-ticklabels-must-match-fixedlocator-locs

Fix compatibility for plot_state_hinton with mpl 3.3.0

---

qiskit/circuit/library/blueprintcircuit.py
qiskit/circuit/quantumcircuit.py
qiskit/circuit/register.py

Analogous to #4535 , caches `qubits` and `clbits` properties of `QuantumCircuit.` This avoids the cost of the list comprehension from `qc.qubits` in `qbit_argument_conversion` which can be considerable when making many calls to `QuantumCircuit.append`.
Also, updates `Register.__iter__` to avoid the type checks in `Register.__getitem__`.
ex: Adding 1024 mcx gates on a 53 qubit circuit:
* master @ 80dcb846 : 
* After `Register.__iter__` avoiding type checks in `Register.__getitem__`:
* With caching QuantumCircuit.qubits:
* Building with `_append`:
```
$ asv continuous --python 3.6 --no-only-changed --bench 'circuit_construction|time_build_ripple_adder' master quantumcircuit-cache-bits
...
before           after         ratio
[80dcb846]       [996e18fe]
<master> …
```

QuantumCircuit cache bits

---

qiskit/circuit/quantumcircuit.py
test/python/circuit/test_compose.py

Fixes a bug where the parameters of the added object were not added to the new parameter table. Thereby also fixes the Aqua CI, which is currently failing due to this.
```python
p = ParameterVector('p', 10)
qc1 = QuantumCircuit(1)
qc1.rx(p[0], 0)
qc2 = QuantumCircuit(1)
qc2.rx(p[1], 0)
qc3 = qc1.compose(qc2)
qc3.parameters  # before: {Parameter(p[0])}, now: {Parameter(p[0]), Parameter(p[1])}
```

Circuit.compose updates the ParameterTable

---

qiskit/pulse/transforms.py

Summary
Pulse transforms need proper inserts to schedule so that longer sequences don't fail.
Details and comments
This addresses bug #4774, so no release note or docstrings were modified. No tests were included. I believe tests included in the PR for #4755 should have caught this error. I ran both tox -py38 and tox -elint successfully.Thanks to @nkanazawa1989 and @taalexander for identification and proposing the solution to the problem.Changelog: Bugfix Fixed

Fixes #4774. Schedule inserts needed for long sequences.

---

qiskit/visualization/dag_visualization.py

Fixes dag_drawer visualization as mentioned in the issue #4793.
A temporary files is deleted after the image is shown.

Fix dag_drawer() that raises file access error on Windows.

---

qiskit/circuit/register.py

Fixes #4791 
#4591 has caused a significant performance regression in circuit construction time because numbers.Integral adds significant overhead
So, I have resolved this by explicitly checking for several types to reduce overhead

Fixed #4791: Explicity checked for several int types

---

qiskit/circuit/library/__init__.py
qiskit/circuit/library/arithmetic/__init__.py
qiskit/circuit/library/arithmetic/quadratic_form.py
releasenotes/notes/quadratic-form-circuit-f0ddb1694960cbc1.yaml
test/python/circuit/test_library.py

Add a circuit implementing a quadratic form on binary variables.
Uses a circuit from https://arxiv.org/pdf/1912.04088.pdf and works similar to the QFT-based adder. Used to construct the input states for the Grover applications in the `GroverOptimizer` algorithm.
Co-authored-by: Austin Gilliam <austin.gilliam777@gmail.com>

Quadratic form on binary variables circuit

---

qiskit/assembler/assemble_circuits.py
test/python/compiler/test_assembler.py

This commit adds the global phase circuit property to the experiment
headers in the assembled qobj. Currently we do not pass the global phase
to backends so simulators can not take it into account. The experiment
header is used since it's a free form field for properties of the
circuit that a backend can use if they want, but there are no
requirements on it. With this in place it should enable #4805 and
Qiskit/qiskit-aer#847 to be fixed.
Related to #4805

Add global phase to qobj in assembly

---

qiskit/transpiler/passes/optimization/consolidate_blocks.py
test/python/transpiler/test_consolidate_blocks.py

This commit fixes an edge condition in the consolidate blocks when a
basis gate was set but it doesn't contain a KAK gate that can be used
for decomposition. In this case we don't have a method to decompose the
any 2q blocks and the pass can't run. While the machinery in the pass's
run() method existed to skip any analysis if there isn't a decomposer
set we weren't doing this in this case. Instead we'd instantiate a
TwoQubitBasisDecomposer object without a KAK basis set. This fixes this
by just setting decomposer to None in these cases so that when
consolidate blocks is run on a dag it becomes a no-op.
Fixes #4826

Don't try and run ConsolidateBlocks without a KAK basis

---

qiskit/quantum_info/synthesis/two_qubit_decompose.py

In #4656 we added rounding to the output of the decomp0 method to handle
a case where differing FP precision on windows environments was causing
an expected result in running two_qubit_cnot_decompose on np.eye(4)
with numpy 1.19.x installed leading to a hard failure in the qasm tests.
This seemed to reliably unblock testing and make unit tests work
reliably. However, that original fix from #4656 was superseded by #4835
which was a fix for a more general issue with the reproducibility of the
decompositions and reverted. Since #4835 has merged we've been seeing an
uptick in the failure rate on the same unitary qasm test that #4656
fixed, so the change in #4835 was not actually sufficient for the
windows case. This commit restores the fix from #4656 to unblock CI and
fix the reproducability …

Restore approx 0 rounding to decomp0 method

---

qiskit/qobj/pulse_qobj.py

The frequency would not show up in the str(PulseQobjInstruction) or
repr(PulseQobjInstruction) views of a PulseQobjInstruction. This commit
should remedy that bug.
e.g.
``PulseQobjInstruction(name='setf', t0=0, ch="d0")`` -> ``PulseQobjInstruction(name='setf', t0=0, ch="d0", frequency="4.5")``
I can add a release note if it's a big enough fix (don't know if people rely on the string representation of a PulseQobjInstruction for any reason...). Or add a test if desired.
A different fix implementation is factoring out the list of attributes into a class variable, to prevent this mistake in the future.
One **other semi-bug**: values have different quotes than the names (i.e. ``name='instr_name', ch="d0"``). Not sure which quote you want to use, but happy to add a small commit to fix that.

PulseQobjInstruction: show frequency in str/repr

---

qiskit/assembler/assemble_circuits.py
qiskit/circuit/quantumcircuit.py
qiskit/compiler/assemble.py
qiskit/qobj/qasm_qobj.py
releasenotes/notes/pulse-gate-calibrations-78fd3fa5a5328761.yaml
test/python/compiler/test_assembler.py

Add piece for assembling front end to the defined qobj schema
Follow up to #4859 
TODO

Pulse gates: assembly changes

---

qiskit/circuit/library/standard_gates/p.py

Fixes an issue with MCPhaseGate definition.
When defining a many-controlled PhaseGate with more that 1 control, PhaseGates are used to implement two-qubit rotations.  However PhaseGate is defined as one qubit gate. This was causing an issue when creating operator from MCPhaseGate.
```
Operator(MCPhaseGate(pi,2))
```
This PR uses CPhaseGate instead. 
MCPhaseGate(pi,2) definition before this PR
```
┌───┐┌───────────┐┌───┐┌──────────┐
q_0: ────────────┤ X ├┤0          ├┤ X ├┤0         ├
┌──────────┐└─┬─┘│           │└─┬─┘│          │
q_1: ┤0         ├──■──┤  P(-pi/2) ├──■──┤  P(pi/2) ├
│  P(pi/2) │     │           │     │          │
q_2: ┤1         ├─────┤1          ├─────┤1         ├
└──────────┘     └───────────┘     └──────────┘
```
MCPhaseGate(pi,2) definition before this PR
```
┌───┐ …
```

Fixes MCPhaseGate definition

---

releasenotes/config.yaml
requirements-dev.txt

The recent reno release 3.2.0 included a new feature [1] for setting the
character encoding that reno uses for all it's files. [2] This commit
sets this option in the reno config file to make the release note files
explicitly utf8. This is important (especially for windows users)
because we have literal inlines of the text drawer in some release notes
which use utf8 characters. This should avoid issues for users who's
system encoding is not compatible with the text drawer output in the
release notes.
[1] https://opendev.org/openstack/reno/commit/984bcba17e4e0b46763f42015d09680e5c5d5a04
[2] https://docs.openstack.org/reno/latest/user/usage.html#configuring-reno

Explicity set encoding of release notes via reno config

---

qiskit/circuit/instruction.py
qiskit/circuit/library/standard_gates/dcx.py
qiskit/circuit/library/standard_gates/h.py
qiskit/circuit/library/standard_gates/iswap.py
qiskit/circuit/library/standard_gates/ms.py
qiskit/circuit/library/standard_gates/p.py
qiskit/circuit/library/standard_gates/r.py
qiskit/circuit/library/standard_gates/rx.py
qiskit/circuit/library/standard_gates/rxx.py
qiskit/circuit/library/standard_gates/ry.py
qiskit/circuit/library/standard_gates/ryy.py
qiskit/circuit/library/standard_gates/rz.py
qiskit/circuit/library/standard_gates/rzx.py
qiskit/circuit/library/standard_gates/rzz.py
qiskit/circuit/library/standard_gates/s.py
qiskit/circuit/library/standard_gates/swap.py
qiskit/circuit/library/standard_gates/t.py
qiskit/circuit/library/standard_gates/u1.py
qiskit/circuit/library/standard_gates/u2.py
qiskit/circuit/library/standard_gates/u3.py
qiskit/circuit/library/standard_gates/x.py
qiskit/circuit/library/standard_gates/y.py
qiskit/circuit/library/standard_gates/z.py
qiskit/converters/ast_to_dag.py
qiskit/converters/circuit_to_gate.py
qiskit/converters/circuit_to_instruction.py
releasenotes/notes/4863-Parameterized-gate-definitions-built-with-incomplete-ParameterTable-a9becfb8aff7d906.yaml
test/python/circuit/test_gate_definitions.py

Resolves #4863 by updating assignments to `._data` to instead use `._append` which will update the parameter table and skip validation.
Also, fixes the `bottom_gate` of `MCPhaseGate` to be `CPhaseGate` which was came up in an added test.

Fix parameterized Gate.definition to have valid ParameterTable.

---

qiskit/circuit/parameterexpression.py
test/python/circuit/test_parameters.py

- Resolves #4978
Allows `ParameterExpression`s to be cast to ints
Adds cast operator for `int`s. Any truncation will occur only after evaluation of the expression (which must be fully bound in order to cast).

Allow ParameterExpressions to be cast to ints

---

qiskit/circuit/quantumcircuit.py
test/python/circuit/test_circuit_operations.py

Fixes #5015 
Checks that `other` parameter in `__eq__` is a `QuantumCircuit`. That way, if `None`, an empty `Instance` traitlet or anything different to a `QuantumCircuit` is provided it will return `False`.

Fix/5015 QuantumCircuit __eq__ should always return a Bool

---

qiskit/circuit/instruction.py
qiskit/circuit/library/standard_gates/sx.py
qiskit/circuit/library/standard_gates/x.py
releasenotes/notes/4953-Inverse-of-MCX-gates-generated-without-qubits-for-ancillae-d8858552eb2cd3f9.yaml
test/python/circuit/test_gate_definitions.py

Resolves #4953 by adding `inverse` methods to the `MCXGate` modes which return gates of the same mode.
Also, fixes some small related bugs that came up during testing:
- `SXGate().inverse()` to return `SXdgGate()` and vice versa.
- `Instruction.inverse` to no longer return modified copy of input gate.
This is necessary for gates which do not have a defined `inverse` method and are not self-adjoint (e.g. DCX, iSwap), because the returned gate would have an updated `definition`, but still incorrectly retain properties of the original gate (namely `to_matrix`).
- Fix `C3XGate.inverse` to negate angle if non-zero.

Inverse of MCX gates to include ancillae

---

qiskit/transpiler/passmanager.py
releasenotes/notes/passmanager_remove-c8f8c0b44ce89756.yaml
test/python/transpiler/test_pass_scheduler.py

Fixes #5023
```python
from qiskit.transpiler.passmanager_config import PassManagerConfig
from qiskit.transpiler.preset_passmanagers import level_1_pass_manager
pm = level_1_pass_manager(PassManagerConfig())
pm.draw()
```
```python
pm.remove(1)
pm.draw()
```

Passmanager.remove(index)

---

qiskit/circuit/quantumcircuit.py
releasenotes/notes/extend-updates-cached-qubits-2dbafe010bd5a946.yaml
test/python/circuit/test_circuit_operations.py

Fixes #5038.
Extending circuits with differing registers didn't updates the cached list of qubits.

QuantumCircuit.extend updates cached bits

---

qiskit/tools/events/progressbar.py
qiskit/tools/events/pubsub.py

Fixes #5012.
It allows more than one subscriber per event, so that bad subscribers
don't block good subscribers from getting events. It does this by changing
the internal _Subscriber class to determine equality based on the callback
function object id, instead of just by name.
To prevent errors described in #5012, it avoids running the progress bar update if it
has not been initialized yet (i.e. start() has not run yet). It also
skips update when it doesn't make sense (e.g. step iteration is greater than
the set total number of iterations on start).
This is sensitive to object ids in order to work, so as long as the callbacks
are dynamically defined functions, this will work.

Fix random crashes on TextProgressBar

---

qiskit/visualization/latex.py
test/python/visualization/test_visualization.py

Fixes #5025 by checking that `self.ops` list is not empty, before checking its first element.
The issue seems to be that `self.ops` is empty, but its first element is checked in `if self.cregbundle and self.ops[0][0].name == "measure"`
https://github.com/Qiskit/qiskit-terra/blob/master/qiskit/visualization/latex.py#L302
Now, if I have understood correctly, `self.ops` is the list of layers in the circuit.
I noticed that in text.py this list is handled differently (called `instructions` there, but still, if I'm not mistaken...), so my guess is that it's OK for `self.ops` to be empty, and it's fine just checking it before accessing its first element.
**Question**: how come test_visualization.py (TestLatexSourceGenerator) wasn't failing earlier? There are tests about latex conversion... …

Fix latex circuit drawer handling of circuits without gates

---

qiskit/tools/jupyter/__init__.py
qiskit/tools/jupyter/monospace.py
releasenotes/notes/monospaced_magic-4716fbc6aec82f5f.yaml

Printing circuit in Jupyter notebooks is relatively common use case. For example, printing circuits in a loop. When `print(circuit)`, the `TextDrawing._repr_html_` method is not called (this happens only when Jupyter shows `circuit.draw('text')`. This creates an ugly output when `print(circuit)`.
This PR adds the magic `%monospaced_output`, solving the issue:

monospaced_output magic for a nicer print(circuit)

---

azure-pipelines.yml
qiskit/circuit/library/template_circuits/__init__.py

This commit adds a missing `__init__.py` file to
`qiskit/circuits/library/template_circuits`, without this `__init__.py` the
template_circuits directory is not a valid python package. This means
it's `qiskit.circuit.library.template_circuits` is not a valid python
path, which means tooling that relies on this in python like unittest
discovery or critically in this case `setuptools.find_packages()` would
not see this package and it would be excluded. This results in
ModuleNotFoundErrors when installing the package. However, in the case
where an editable install was used this wouldn't cause a hard error
because the editable install is just a symlink to the source repo and
since the module was only accessed via relative imports it would be
found. Adding the missing `__init__.py` will fix …

Add missing __init__.py to template_circuits

---

test/python/visualization/references/test_4597.tex
test/python/visualization/references/test_deep.tex
test/python/visualization/references/test_empty.tex
test/python/visualization/references/test_huge.tex
test/python/visualization/references/test_normal.tex
test/python/visualization/references/test_teleport.tex
test/python/visualization/references/test_tiny.tex
test/python/visualization/test_circuit_latex.py
test/python/visualization/test_utils.py
test/python/visualization/visualization.py

Fixes #1186
I split the `test_visualization.py` into `test_circuit_latex.py` and `test_utils.py`. In `test_circuit_latex.py`, I created the references for the latex source and the equality check.

Improve the circuit latex (source) drawer testing

---

qiskit/test/base.py
qiskit/test/runtest.py
requirements-dev.txt

In #5071 we tried to fix an implicit testing requirement dependency we
added in #3982 for capturing output streams from test runs. However,
that change didn't go far enough in making the capture features opt-in.
While it fixed the hard failure it still made the installation of
testtools and fixtures hard requirement for running tests, even if the
stream capturing was never used. For an example of this see #5078. This
commit attempts to remedy this situation by making the stream capturing
opportunistically opt-in. It splits out the common functionality between
the old test class without stream capturing into a new common base
class. Then it adds the stream capturing base class on top of that. The
stream capturing class is only used if testtools and fixtures is
installed and …

Make stream capturing test class opportunistic

---

qiskit/circuit/library/standard_gates/ms.py
qiskit/circuit/quantumcircuit.py
qiskit/circuit/random/utils.py
qiskit/quantum_info/operators/pauli.py
releasenotes/notes/3927-0d94adeac9299540.yaml
test/python/circuit/test_extensions_standard.py

In #3927, some deprecation warnings were inserted for parameters `n_qubits` and `numberofqubits`. The warnings were released with 0.13 (Apr, 2020). This PR removes those warnings.

Removing deprecated n_qubits and numberofqubits (warnings in 0.13)

---

qiskit/visualization/transition_visualization.py

As laid out in https://github.com/Qiskit/qiskit-terra/issues/5100,
``qiskit.visualization.transition_visualization`` is on the critical
path for any ``qiskit`` import. This means that the imports in this file
will always be imported. Profiling of import time showed that
``matplotlib.animation`` was a slow import, and so should be deferred
from the critical path.
Ref #5100 
Moved after ``HAS_MATPLOTLIB`` check to be reasonably sure that matplotlib & the animation module is installed.

Transition Visualization: defer matplotlib import

---

qiskit/assembler/assemble_circuits.py
releasenotes/notes/fix_global_phase_in_assembled_circuit-8836260c7962c247.yaml
test/python/compiler/test_assembler.py

Fixes bug where extra global_phase from unrolled gates was added during circuit assembly which didn't need unrolling.

Fix global phase for qobj assembly

---

qiskit/compiler/assemble.py

Modify `rep_delay` warning to not mention `rep_time`, as that is only for pulse jobs.

Update error msg when use rep delay and dyn rep rates off

---

qiskit/visualization/bloch.py
qiskit/visualization/state_visualization.py

I accidentally introduced a dependency to `packaging` when merging #4893 (which was detected via #5108). When tested, I assumed `packaging` was installed as part of one of our requirements. Well... no. So, this PR removes the dependency via checking if matplotlib has the aspect ratio method available. In this way, instead of comparing the versions, it sets the right ratio when possible.

Remove packaging dependency

---

qiskit/circuit/parameterexpression.py

Just as in #4385 and #3156 we should not be importing sympy at the
module level. Sympy is a very heavy dependency and is slow to import
(and slow to run too). Adding a sympy import to the module level makes
imports significantly slower. This commit reverts the top level import
of sympy, which was only added for type hints, to fix the import
performance regression.

Avoid module level sympy import again

---

test/python/providers/test_backendconfiguration.py

In #4711 a regression test was added to validate the bugfix being added
in that PR. However, a stray debug print from development slipped in and
has stuck around since that merged. This commit removes the stray print
to remove it from our test output since it serves no purpose.

Remove stray print from test_backendconfiguration

---

qiskit/transpiler/passes/scheduling/alap.py
qiskit/transpiler/passes/scheduling/asap.py
test/python/circuit/test_scheduled_circuit.py
test/python/transpiler/test_scheduling_pass.py

Fix #5154 
This PR rewrite `ALAPSchedule` pass without using `reverse_ops()` so that it fixes the instruction name mismatch bug reported in #5154. As a bonus, the removal of double reversion of circuits would improve the performance of `ALAPSchedule` pass.

Fixed issue 5154 by rewriting ALAP scheduler without reverse_ops

---

qiskit/transpiler/passes/routing/lookahead_swap.py
test/python/transpiler/test_lookahead_swap.py

In #4915, the passes were extended with global phase awareness. The `lookahead` pass was coping the dag without the global phase. This PR fixes that.

The lookahead_swap pass is global_phase aware

---

qiskit/compiler/transpile.py
qiskit/transpiler/__init__.py
qiskit/transpiler/instruction_durations.py
test/python/circuit/test_scheduled_circuit.py

like all other args in transpile(), supplying your own arg should overwrite the one that is read from backend.
plus a couple other enhancements to the InstructionDuration object, like a print option.

instruction_durations overwrites backend durations, does not extend them

---

qiskit/circuit/library/blueprintcircuit.py
releasenotes/notes/build-blueprintcircuit-before-inverse-8ef85f6389588fe0.yaml
test/python/circuit/library/test_blueprintcircuit.py

Assert a call on `_build` method of a `BlueprintCircuit` if `inverse` or `compose` is called in order to populate internal `_data` field.
Previously, as reported on #5140, the following would fail since `_data` is still `None`.
```python
var_form = EfficientSU2(2, entanglement="linear")
var_form.inverse()
---
raises TypeError
---
qc.h([0, 1])
var_form.compose(qc, inplace=True)
---
raises TypeError
---
```
As with other attributes, before internal data of the circuit is accessed on `inverse` and `compose` functions, the `_build` method is called.

Build BlueprintCircuit before inverse and compose

---

qiskit/circuit/quantumcircuit.py
test/python/circuit/test_scheduled_circuit.py

Fix #5109 
Add functions to inquire the `start_time` and `stop_time` of each qubit in a circuit that has been scheduled.
- `qubit_start_time`: the start time of the first instruction, excluding delays, over the supplied qubits.
- `qubit_stop_time`: the stop time of the last instruction, excluding delays, over the supplied qubits.
- `qubit_duration`: `qubit_stop_time - qubit_start_time`, which is the same spec as the future spec of `pulse.Schedule.ch_duration` after #4848.

Add per-qubit duration in a scheduled circuit

---

qiskit/compiler/transpile.py
qiskit/transpiler/passes/basis/basis_translator.py
qiskit/transpiler/passes/basis/ms_basis_decomposer.py
qiskit/transpiler/passes/basis/unroll_custom_definitions.py
qiskit/transpiler/passes/basis/unroller.py
qiskit/transpiler/passes/optimization/commutation_analysis.py

delay, like measure, reset, etc. is a fundamental instruction that cannot be re-written as another instruction. So this commit teaches the compiler to not attempt to unroll or translate it. With this I also remove a previous hack that patched delay onto basis gates.

add delay as a builtin instruction

---

qiskit/dagcircuit/dagnode.py
qiskit/dagcircuit/releasenotes/notes/remove-dagnode-dict-32fa35479c0a8331.yaml

This commit removes the deprecated DAGNode dict constructor positional
argument support. Passing in a dictionary as the first positional arg
has been deprecated since the 0.13.0 release on April 9th, 2020 so per
the deprecation policy [1] it has been sufficient time to remove the
deprecated feature now.
[1] https://qiskit.org/documentation/contributing_to_qiskit.html#deprecation-policy

Remove deprecated DAGNode dict constructor argument

---

qiskit/circuit/library/standard_gates/h.py

Fixes issue number #5207
(Originally addressed here https://github.com/Qiskit/qiskit/issues/1053)
The note on the documentation page for the CHGate displays an equation where a 1/sqrt(2) is incorrectly factored out the final matrix representation. This pull request fixes the terms in the final matrix representation by removing the 1/sqrt(2) outside the matrix and distributing it correctly to the bottom-right block of the matrix. 
Here is a visual representation of what was changed:

Fix the matrix representation in the documentation of CHGate

---

qiskit/circuit/library/standard_gates/u3.py

Fixed issue #5210 
(Originally addressed here https://github.com/Qiskit/qiskit/issues/1055)
An instance of pi is not defined correctly in the code under the examples section of the U3Gate documentation
The problem can be found here under the examples section:
https://qiskit.org/documentation/stubs/qiskit.circuit.library.U3Gate.html
This pull request adds the missing backslash in front of "pi" in the lambda input variable of the example
Example of the results from the changes in the code:

Fix rendering of "pi" in the U3 documentation

---

azure-pipelines.yml

This commit reverts a change made during #5083 to use aqua from master
for the tutorials job. This was done to workaround an aqua bug with
a non-u1/u2/u3 basis that was occuring with the 0.7.x release of aqua.
We typically use the released versions of the libraries in these jobs to
catch potentially breaking changes for the biggest users of the terra
api (the other qiskit elements). This restores this coverage by
switching back to using the aqua release for the job.

Restore using aqua from release for tutorials job

---

qiskit/circuit/library/probability_distributions/lognormal.py
qiskit/circuit/library/probability_distributions/normal.py
qiskit/quantum_info/operators/random.py

The scipy.stats submodule is a relatively slow import and takes up
roughly 12% of our total import time. This is disproportionately large
compared to its use in the random operator generator functions and
probability distribution circuit library classes which are not critical to
any of the core functionality or performance
critical. This commit shifts the module level import to be a runtime
import to avoid this import cost, while this does add runtime overhead
(and an initial cost on the first execution) that is worth the tradeoff
to remove it from the default import path.
Related #5100

Move scipy.stats imports to runtime

---

qiskit/quantum_info/synthesis/two_qubit_decompose.py
test/python/quantum_info/test_synthesis.py

The hermitian optimized eigen solver function in scipy has shown
to possibly produce varied results in different environments. For
example, the matrix returned by the `eigh()` call in the
`TwoQubitWeylDecomposition` class's `__init__` method when called for
a CXGate:
```python
TwoQubitWeylDecomposition(Operator(CXGate()))
```
was observed to be
```
[[ 0.70710678  0.         -0.70710678  0.        ]
[ 0.         -0.70710678  0.          0.70710678]
[ 0.          0.70710678  0.          0.70710678]
[ 0.70710678  0.          0.70710678  0.        ]]
```
on one system/environment but
```
[[ 0.70710678  0.         -0.70710678  0.        ]
[ 0.          0.70710678  0.          0.70710678]
[ 0.         -0.70710678  0.          0.70710678]
[ 0.70710678  0.          0.70710678  0.        ]]
```
on …

Use evd driver for eigh in TwoQubitWeylDecomposition

---

qiskit/circuit/library/standard_gates/x.py
qiskit/qasm/libs/qelib1.inc
releasenotes/notes/c4xgate-fix-inconsistent-qasm-def-b979edcc93a591d7.yaml

The QASM definition of `C4XGate` doesn't currently match `C4XGate._define`.
qelib1
```
// 4-controlled X gate
gate c4x a,b,c,d,e
{
h e; cu1(-pi/2) d,e; h e;
c3x a,b,c,d;
h d; cu1(pi/4) d,e; h d;
c3x a,b,c,d;
c3sqrtx a,b,c,e;
}
```
`_define`:
```
from qiskit.circuit.quantumcircuit import QuantumCircuit
from .u1 import CU1Gate
q = QuantumRegister(5, name='q')
qc = QuantumCircuit(q, name=self.name)
rules = [
(HGate(), [q[4]], []),
(CU1Gate(-numpy.pi / 2), [q[3], q[4]], []),
(HGate(), [q[4]], []),
(C3XGate(), [q[0], q[1], q[2], q[3]], []),
(HGate(), [q[4]], []),
(CU1Gate(numpy.pi / 2), [q[3], q[4]], []),
(HGate(), [q[4]], []),
(C3XGate(), [q[0], q[1], q[2], q[3]], []),
(C3XGate(numpy.pi / 8), [q[0], q[1], q[2], q[4]], []),
]
for instr, qargs, cargs in rules:
qc._append(instr, qargs, cargs) …
```

Fix C4XGate QASM definition.

---

qiskit/circuit/classicalfunction/__init__.py

```
import qiskit as qk
from qiskit.circuit import classical_function, Int1
def build_qc():
qc = qk.QuantumCircuit(2)
@classical_function
def cfunc(a: Int1) -> Int1:
return not a
qc.append(cfunc, [0,1])
return qc
build_qc().draw()
```
had raised
```
File "/Users/kevin.krsulichibm.com/q/qiskit-terra/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3343, in run_code
exec(code_obj, self.user_global_ns, self.user_ns)
File "<ipython-input-1-640b2be56591>", line 12, in <module>
build_qc().draw()
File "<ipython-input-1-640b2be56591>", line 7, in build_qc
def cfunc(a: Int1) -> Int1:
File "/Users/kevin.krsulichibm.com/q/qiskit-terra/qiskit/circuit/classicalfunction/__init__.py", line 119, in classical_function
return ClassicalFunction(source, …
```

classical_function decorator to handle parsing indented define.
