releasenotes/notes/0.16/classical_funciton_compliation-c5d75e0aaf04c8f1.yaml
There is a typo in the release note for 0.16, when classical function compiler is explained.
Related to https://github.com/Qiskit/qiskit/pull/1071
=> Fix release note about the classical function compiler

qiskit/circuit/library/data_preparation/pauli_feature_map.py, releasenotes/notes/paul_feature_alpha-1fdba69c577c6b4d.yaml, test/python/circuit/library/test_pauli_feature_map.py
Introduce parameter alpha( default=2) instead of hard-coded 2 in the Paul-feature-map.  
This would allow more flexible decision boundary control for QSVM
This work is done with close collaboration with @woodsp-ibm , Stephen Woener, and Jae-Eun Park from IBM
Original Paul Feature Map has hard-coded value "2" 
Beyond the feature scaling,  the factor allows QSVM to create more classical looking decision boundaries with better analytical performance.
=> Paul Feature_map update with rotation factor (alpha)

qiskit/circuit/library/standard_gates/x.py
Fixed issue, closes Qiskit/qiskit#1050
Apparently a user pointed an incorrect operation at the Toffoli gate equation in Qiskit Documentation. I just corrected how he proposed to.
=> CCX Equation Corrected

qiskit/execute.py, releasenotes/notes/bugfix-delays-are-supported-d294bc1cb478d149.yaml, test/python/circuit/test_scheduled_circuit.py
This no longer errors.
```
qc = QuantumCircuit(2, 2)
qc.delay(10, [0])
tqc = transpile(qc, backend)
execute(tqc, backend)
```
=> Fix bug: execute valid circuits built with delays

qiskit/result/result.py, test/python/result/test_result.py
Fixed #5283 , changed ` backend_version ` to ` backend_name ` in `Result.__repr__ `
changed ` backend_version ` to ` backend_name ` in `Result.__repr__ `
=> Fix display of backend name in Result.__repr__

test/python/classical_function_compiler/test_classical_function.py, test/python/classical_function_compiler/test_parse.py, test/python/classical_function_compiler/test_simulate.py, test/python/classical_function_compiler/test_synthesis.py, test/python/classical_function_compiler/test_typecheck.py
In environments without tweedledum installed, skip rather than fail the classical function compiler tests.
=> Skip classical function compiler tests if tweedledum unavailable.

qiskit/result/result.py
Replace ``get_data()`` with ``data()`` as  the former was superseded by the latter as of Terra 0.7.
=> result.py: fix documentation for get_counts()

qiskit/tools/parallel.py, qiskit/user_config.py, releasenotes/notes/paralle-config-options-97c1ad44ab76e052.yaml, test/python/test_user_config.py
This commit adds new options to the user config file, 'parallel' and
'num_processes' which when set will override the default behavior of
terra's parallel_map function (which is used internally by transpile()
and assemble()). Along with these new options the default behavior on
macOS is changed to disable parallel execution by default.
Fixes #5323
=> Add user config file options to control parallel execution

qiskit/quantum_info/operators/base_operator.py, qiskit/quantum_info/operators/channel/chi.py, qiskit/quantum_info/operators/channel/choi.py, qiskit/quantum_info/operators/channel/kraus.py, qiskit/quantum_info/operators/channel/ptm.py, qiskit/quantum_info/operators/channel/quantum_channel.py, qiskit/quantum_info/operators/channel/stinespring.py, qiskit/quantum_info/operators/channel/superop.py, qiskit/quantum_info/operators/operator.py, qiskit/quantum_info/operators/scalar_op.py, qiskit/quantum_info/operators/symplectic/clifford.py, qiskit/quantum_info/operators/symplectic/pauli_table.py, qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py, qiskit/quantum_info/states/densitymatrix.py, qiskit/quantum_info/states/quantum_state.py, test/python/quantum_info/operators/channel/test_chi.py, test/python/quantum_info/operators/test_operator.py
Updates BaseOperator class to have a more efficient __init__ method for N-qubit operators. This is important for improving the performance of Cliffords and Pauli operators for large numbers of qubits which were spending a large amount of time in the initialization.
Previously the initialization would construct the two input and output dimension tuples `num_qubits * (2, )`. These aren't needed if the operator is known to be an N-qubit operator,  so now these dimensions are only generated lazily for N-qubit operators when needed (such as composing them with a non-qubit operator or reshaping).
=> Improve init efficiency of BaseOperator for N-qubit operators

qiskit/quantum_info/operators/channel/quantum_channel.py, qiskit/quantum_info/operators/measures.py, releasenotes/notes/fix-quantum_channel_sub-4a31394a7a1237d4.yaml, test/python/quantum_info/operators/channel/test_linearops.py
* Fixes bug when subtracting an operator object from a quantum channel object
* Fixes warning in `diamond_norm` from deprecated usage of CVXPY
=> Fix bug in quantum channel subtraction

qiskit/circuit/quantumcircuit.py
This commit switches the deprecation warnings emitted by the deprecated
u1, u2, u3, cu1, mcu1, and cu3 to use the deprecate_function decorator
instead of explicitly calling the warnings.warn() method directly. This
has the advantage of only emitting the warning once per python process.
Right now we emit the warning once per call which can end up being quite
verbose, especially when its called internally by something like ignis
or aqua. This should fix that issue by making the warning only appear
once.
=> Use deprecate_function for u1, u2, u3 methods

qiskit/providers/backend.py
Fixes a typo in `Backend.set_options()` where `field` is the first argument when it should be the second.
=> Fix hasattr in Backend.set_options

qiskit/tools/jupyter/job_watcher.py, tox.ini
A recent urllib3 release is breaking compatibility with requests which
is blocking CI in the docs job. However, requests is only ever used by
the IBMQ provider which we install in the docs job because of one
jupyter widget and to avoid a packaging warning (which would also be
fatal to the sphinx build). This commit attempts to fix the current ci
failure by removing the qiskit-ibmq-provider package from the CI job and
fixing or suppressing the warnings/failures related to packaging.
=> Remove IBMQ provider from docs CI job

qiskit/circuit/quantumcircuit.py
Unblocks Qiskit/qiskit-aqua#1404.
Example code using `>>>` in the docstring is being run by Aqua CI since it has objects deriving from the QuantumCircuit. This sometimes leads to errors since this code is not tested in Terra. Using the jupyter-execute block resolves this issue.
In this particular case, Aqua's Sphinx build complains about a missing character encoding and about return values which are not displayed in the code snippet.
=> Use jupyter execute instead of >>> in QuantumCircuit

qiskit/transpiler/passes/optimization/template_matching/template_substitution.py
Just as has been demonstrated many times in the past we should not be
importing sympy at the module level. In #5259 another import was added
and was immediately flagged as an import speed regression [1]. Sympy is
a very heavy dependency and is slow to import (and slow to run too).
Adding a sympy import to the module level makes and is honestly a
dependency we should be reluctant to add anywhere because it becomes
the primary bottleneck whenever it is used. This commit removes the top
level sympy import and moves to be a runtime import in the single method
that uses sympy. Just as it was done in #5149, #4385, and #3156 before.
[1] https://qiskit.github.io/qiskit/#import.QiskitImport.time_qiskit_import?commits=b5d5a3bb
=> Avoid module level sympy yet another time

qiskit/quantum_info/operators/base_operator.py, releasenotes/notes/fix-op-ufunc-multiple-d1c59b236024f483.yaml, test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
Fixes #5408
Fix is to add dispatch mechanism for numpy ufuncs to BaseOperator which maps `np.multiply` to the `BaseOperator._multiply` method.
=> Fix bug when multiplying SparsePauliOp by np.int64

qiskit/circuit/bit.py, qiskit/circuit/register.py, test/python/circuit/test_bit.py, test/python/circuit/test_circuit_registers.py
In #5272 the `__eq__` method was changed to use a single string comparison
away from a nested attribute comparison for performance reasons. This
had the unexpected side effect that when comparing a register or a bit
object against an object of another type an `AttributeError` would be
raised because the private `_repr` attribute doesn't exist outside of
those classes. This leads to unexpected failures when running with aqua
because they were comparing a register to a string. This commit
addresses this by catching the attribute error and returning false
because objects of different types are not equal.
=> Handle type mismatch on bit and register __eq__

constraints.txt
The appnope 0.1.1 release from this morning is the only package change
between a working and failing CI job. This commit explicitly pins it in
the constraints file (since we don't directly require it) to ensure we
get a known working version to try and unblock CI.
=> Pin appnope in CI

qiskit/circuit/quantumcircuit.py, test/python/circuit/test_parameters.py
Fixes #5457 
This PR adds a test to catch the issue. It also proposes a fix by checking if the parameter is already in the `_parameter_table` of the quantum circuit.
=> Fix parameter assignment bug.

qiskit/circuit/parameterexpression.py, releasenotes/notes/parameterexpression-eq-compares-bounded-expr-to-val-ba7588cac6e53b5d.yaml, test/python/circuit/test_parameters.py
This is a code update in response to issue [#5423](https://github.com/Qiskit/qiskit-terra/issues/5423)
The current implementation of __eq__ method of ParameterExpression class only allows comparison between two parameter expressions.
With this update it should be possible to compare a bounded parameter expression with a fixed value.
If the argument passed to `__eq__` is a number:
(1) Check that self has no unbound parameters i.e. self.parameters == 0
(2) Check that the value of the sympy expression is equal to the argument
Added a test called `test_compare_to_value_when_bound` in test/python/circuit/test_parameters.py to check that the comparison with a fixed value works
=> ParameterExpression.__eq__ takes bounded expr == value

qiskit/transpiler/coupling.py
In #5183 we switched the internal graph datastructures used for the
CouplingMap to be based on retworkx instead of networkx. That PR was
written against the 0.6.0 retworkx release and for the from_grid()
and from_full() constructors python had to be used since retworkx
was missing functions to generate graphs of those types. However, in the
recent 0.7.x retworkx release 2 new generators directed_grid_graph() [1]
and directed_mesh_graph() [2] were added. This commit switches the
implementation of from_grid() and from_full() to use these generators,
which significantly speeds up (and reduces the memory overhead) of the
constructor methods.
The only constructor which still relies on a Python loop is the
from_full() method when bidirection=False. This is because retworkx
doesn't offer a …
=> Leverage retworkx generators for all cmap constructors

qiskit/assembler/assemble_schedules.py, qiskit/qobj/converters/pulse_instruction.py, releasenotes/notes/bugfix-assemble-delay-32a96b59bb84badd.yaml, test/python/compiler/test_assembler.py, test/python/compiler/test_disassembler.py
Previously, we could ignore delays rather than assembling them. Now, with pulse gates, there are times that we want to schedule ONLY a delay, and not including the delay itself would remove the delay!
Example:
```
qc = QuantumCircuit(1, 1)
qc.x(0)
qc.append(Gate('example', 1, []), [0])
qc.measure(0, 0)
qc.add_calibration('example', [0], pulse.Delay(1600, pulse.DriveChannel(0)))
```
=> Convert delays to instructions when assembling

qiskit/dagcircuit/dagcircuit.py
This commits removes the `rx.is_directed_acyclic_graph()` call from the
`DAGCircuit.depth()` method. This call was unnecessary as the
`rx.dag_longest_path_length()` method will internally raise an exception
if the input graph has a cycle. Additionally, for very large circuits
the `rx.is_directed_acyclic_graph()` can segfault. To reduce the overhead
of the `depth()` method and to avoid the potential bug this unnecessary
call is removed.
Fixes #5502
=> Remove rx.is_directed_acyclic_graph() from DAGCircuit.depth()

qiskit/util.py
In #5420 the `qiskit.util` module was migrated to `qiskit/utils` to be
consistent with imported code from qiskit-aqua in #5422. However, the
backwards compat shim added in that PR has a couple of issues, mainly
around re-exporting the entirety of `qiskit.utils` which occasionally
causes import cycles and is larger than what functions used to exist in
`qiskit.util` and should be deprecated. This commit fixes this by changing
the deprecation shim in `qiskit.util` to only re-export the functions that
previously existed in `qiskit.util` for backwards compatibility during the
deprecation period.
=> Restrict qiskit.util to actual deprecated functions

qiskit/transpiler/passes/layout/csp_layout.py
In #5183 the inner graph object of the CouplingMap object was switched
to retworkx. While generally faster there are a few different edge cases
where retworkx performance can be worse than networkx. Namely, any place
where large lists are returned, for example lists of all nodes or edges
in a graph. In those cases the conversion from the Rust objects to the
Python objects can cumulatively be expensive. To avoid this conversion
overhead in every case retworkx has custom return types that are python
sequences but defer type conversion to `__getitem__`, meaning that the
return is fast but complete traversal can be slow, especially when done
multiple times. In such cases it's easier to cast the sequence to a
Python object such as a set or a list so the conversion is only done
once. However, …
=> Fix performance regression in CSPLayout pass

qiskit/result/models.py, test/python/result/test_result.py
Allows arbitrary data attributes in the `ExperimentResultData` class letting it function more like the dict container it is exposed to users as via the `Result.data` method.
This (or something like this) will be needed if the future to allow Aer to add different data types to the result data container (such as probabilities and expectation values).
The existence of this class at all seems rather superfluous since it is always converted to a dict via the various `Result` methods like `data` `get_statevector` `get_unitary`. It could easily just be replaced by a plain dictionary in the `ExperimentResult` and `Result` classes and methods. I think it is only still here as a leftover from the Marshmallow classes.
=> Allow arbitrary data attributes in ``ExperimentResultData``

qiskit/execute.py
This PR makes 2 changes:
1. the current code in `execute()` iterates over `run_kwargs` and may delete its entries. The deletion, however, would raise a `RuntimeError: dictionary changed size during iteration` error. This PR converts the dictionary keys to a list to avoid the iterator being changed while looping. 
2. `parameter_binds` is not really a backend option, so this PR handles it separately to avoid removing it when it's not in backend options.
=> Convert run_kwargs  keys to list in execute()

qiskit/circuit/quantumcircuit.py, releasenotes/notes/fix-global-phase-upon-repeat-f742f4c0201fea97.yaml, test/python/circuit/test_circuit_operations.py
Fixes #5586.
Fix the global phase of the output of ``circuit.repeat``. If a circuit with global
phase is appended to another circuit, the global phase is currently not propagated.
The simulators rely on this, since the phase otherwise gets applied multiple times.
This sets the global phase of ``circuit.repeat`` to 0 instead of multiplying the existing
phase times the number of repetitions.
=> Fix global phase handling in circuit.repeat

test/python/circuit/library/test_nlocal.py
For some of the nlocal tests we are seeing a non-deterministic failure
rate of roughly 1% in CI without any debugging information. An asserted
equality is returning False failing which doesn't tell us how the
circuits differ or offer any indication as to what went wrong.
In local testing we've been un able to reproduce the failure. However,
the test_nlocal module is using the random_circuit() function to
randomly generate a circuit for test purposes and was not setting a
seed which is the only source of randomness in the test path. This means
the output circuit could be a bad input and we're tripping a weird edge
case. To hopefully address the failure mode this commit sets a seed on
all the random_circuit calls in the module to ensure we're always using
the same input.
Attempts to Fix …
=> Set a seed for random_circuit in nlocal tests

qiskit/opflow/primitive_ops/pauli_op.py, releasenotes/notes/bugfix-propagate-pauli-phase-in-pauliop-eval-b7fa0d14b1e3b61a.yaml, test/python/opflow/test_op_construction.py
Propagate the phase of the internal primitive when evaluating a `PauliOp`.
The phase of the Pauli needs to be propagated into the result coefficient when evaluating a `PauliOp`.
Otherwise, the following two codes would return identical results:
```
(X @ Z).eval('0')
(Z @ X).eval('0')
```
This is obviously not intentional and this PR fixes the behavior.
Rather, the above codes should return different results and, on top of that, should be equal to the following:
```
(X @ Z).eval('0') == (-1j * Y).eval('0')
(Z @ X).eval('0') == (1j * Y).eval('0')
```
(Note, that `(+/-1j * Y)` was already working before.)
Unittests have been added to assert this behavior.
=> Propagate Pauli phase when evaluating PauliOp

.github/CODEOWNERS
The utils/ codeowners rule was intended to match the qiskit/utils
directory which contains a lot of code migrated from aqua. However, the
the rule was overly broad and matching any utils directory for example
qiskit/transpiler/passes/utils. This commit restricts the rule to
explicitly match qiskit/utils only which was the intent.
=> Fix codeowners matching rule for utils

qiskit/quantum_info/operators/op_shape.py, qiskit/quantum_info/states/densitymatrix.py, qiskit/quantum_info/states/statevector.py, releasenotes/notes/state_reverse_qargs-f2f3c9a3e1c3aaa0.yaml, test/python/quantum_info/states/test_densitymatrix.py, test/python/quantum_info/states/test_statevector.py
Implements #4592 for state classes.
~Depends on #5432~
=> Add `reverse_qargs` method to `Statevector` and `DensityMatrix`

qiskit/circuit/quantumcircuit.py
As pointed out by Aleksey Zhuravlev on the Qiskit slack, the deprecation message for `QuantumCircuit.u2` gives an incorrect decomposition of the U2Gate in terms of phase + sx. This PR updates it to `u2(φ,λ) = p(π/2+φ) sx p(λ-π/2)`, which is consistent with the definition in the OpenQASM spec.
=> Fix U2Gate decomposition in QuantumCircuit.u2 deprecation message.

qiskit/transpiler/preset_passmanagers/level2.py, test/python/transpiler/test_preset_passmanagers.py
This commit adds the basis translation step to the level 2 preset
passmanager's optimization loop. The level 2 optimization loop runs the
commutative cancellation pass which use Rx and U1 gates as part of it's
optimization step which may not be in the target basis gates. This can
result in a gate outside of the target basis ended up in the output. To
avoid this in a general manner we need to rely on the basis translation
step because we can't write a pass to do the simplified rotation in a
manner compatible with any basis (especially since the target basis
could be using custom gates).
Fixes #5644
=> Add unroll step to level2 passmanager optimization loop

qiskit/dagcircuit/dagcircuit.py
Currently the return type from collect_1q_runs is being converted from
the 'list(list(DAGNode))' which is returned by retworkx.collect_runs()
to be 'set(tuple(DAGNode))' so that it is consistent with the return
type from collect_runs(). However, this ends up adding significant
overhead to the collect_1q_runs method and ends up being the bottleneck.
We spend more time running the set expression to convert from the list
than we do in rx.collect_runs() (mainly the filter function). Since
collect_1q_runs hasn't been included in a release yet we can change the
return type without breaking users and avoid this extra overhead. This
commit does that and removes the set comprehension and just returns the
nested list directly from retworkx.collect_runs().
=> Change collect_1q_runs return for performance

qiskit/dagcircuit/dagcircuit.py, qiskit/quantum_info/operators/operator.py, qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py, test/python/compiler/test_transpiler.py
This commit tunes the performance of the optimize_1q_decomposition pass.
Previously, the bottleneck of the pass was in creating the operator to
decompose because we were creating an unecessary circuit and then having
the Operator class convert that to a matrix which involved running
to_instruction() and lots of copying. Instead this commit switches the
pass to just go straight to an array or operator (if __array__ isn't
defined) for each gate and compose that directly onto the operator.
Doing this ends up being faster than using a circuit as an
intermediate class.
=> Tune performance of optimize_1q_decomposition

qiskit/transpiler/passes/routing/sabre_swap.py, test/python/transpiler/test_sabre_swap.py
Fixes #5675 
SabreSwap does `make_symmetric` on `coupling_map`, changing the parameter in place. This PR makes a copy if the coupling map is not symmetric.
=> coupling_map argument should not change when SabreSwap is run   

qiskit/circuit/delay.py, test/python/pulse/test_instructions.py
This enables `Operator()` of circuits containing `delay` instructions. Previously, this would raise an error.
fixes #5697 
Adds a `to_matrix` method to delay instruction to point to its alreadly existing `__array__` method.
=> enable Operator() of circuits with delay instruction

qiskit/dagcircuit/dagcircuit.py, releasenotes/notes/fix-invalid-ops-collect-runs-b9fd2f2e85136834.yaml, test/python/dagcircuit/test_dagcircuit.py
This commit fixes a bug introduced in the backport PR #5655. On the
current master branch the bugfix that was being backported relies on a
feature in newer versions of retworkx. Since we can't bump the minimum
retworkx version required on a stable branch that functionality was
rewritten in the dagcircuit class directly. However, that implementation
included a typo which is causing non-gates and atomic instructions to be
included in collected runs which is not correct behavior and causes
errors to be raised. This commit corrects the bug in the backport and
adds a test to ensure the regression is not present.
This is a direct commit to the stable branch and not a backport since
this bug is not present on master and was only introduced through a bad
backport.
Fixes #5736
=> Fix typo adding non-gates to _collect_1q_runs() output

qiskit/circuit/register.py, qiskit/opflow/primitive_ops/pauli_op.py, qiskit/opflow/primitive_ops/pauli_sum_op.py, qiskit/quantum_info/operators/measures.py, qiskit/quantum_info/operators/pauli.py, qiskit/quantum_info/operators/symplectic/base_pauli.py, qiskit/quantum_info/operators/symplectic/clifford.py, qiskit/quantum_info/operators/symplectic/pauli.py, qiskit/quantum_info/operators/symplectic/pauli_table.py, qiskit/quantum_info/operators/symplectic/pauli_utils.py, qiskit/quantum_info/operators/symplectic/random.py, qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py, qiskit/quantum_info/operators/symplectic/stabilizer_table.py, qiskit/visualization/pulse_v2/generators/waveform.py, qiskit/visualization/utils.py, test/python/pulse/test_samplers.py, test/python/quantum_info/operators/symplectic/test_clifford.py, test/python/quantum_info/operators/symplectic/test_legacy_pauli.py, test/python/quantum_info/operators/symplectic/test_pauli_table.py, test/python/quantum_info/operators/symplectic/test_stabilizer_table.py
Resolves: https://github.com/Qiskit/qiskit-terra/issues/5756
Numpy 1.20.0 deprecates `Using the aliases of builtin types like np.int`.
See the [release note](https://numpy.org/devdocs/release/1.20.0-notes.html#using-the-aliases-of-builtin-types-like-np-int-is-deprecated).
=> Remove DeprecationWarning of np.int, np.bool, np.complex

CONTRIBUTING.md
This commit expands on the stream capture section of the CONTRIBUTING.md
guide. The existing section was a bit confusing because it makes the
QISKIT_TEST_CAPTURE_STREAMS environment variable sound general but it
only works with stestr (or a similar test runner built on the same
stack). This clarifies that it only has the desired effect with stestr
and if you're using the stdlib runner this is the equivalent of running
--buffer.
=> Clarify the CONTRIBUTING.md section on stream capture

qiskit/qobj/utils.py
On Feb. 1, 2021 fastjsonschema 2.15.0 was released that made some
changes to the exception API. [1][2] These changed the inheritance tree
used for the exception classes so that `JsonSchemaException` (which is
the class qiskit is catching) was changed to be a base class instead of
the class raised by validation errors. A new class
`JsonSchemaValueException` a subclass of that now base class is now raised
by validation errors. The attributes used to wrap that exception and
raise a custom exception are now defined in `JsonSchemaValueException`
and not `JsonSchemaException`. This is causing pylint to fail because
the attributes are not defined in the base class. But in practice this
will not raise an error as `JsonSchemaValueException` will always be
raised even if we only `isinstance` check …
=> Disable pylint rule causing failure with fastjsonschema 2.15.0

qiskit/visualization/text.py
There are times when the sys.stdout encoding may be None. Namely if the
sys.stdout object is replaced with a buffer like io.StringIO. This is a
common pattern in testing and is also how the stdlib unittest's --buffer
flag works. However, by default io.StringIO the encoding attribute is
set to None. In this case the text drawer attempts to explicitly encode
a string to bytes with a None encoding which will result in an error. To
address this case this commit adds handling for when sys.stdout.encoding
is None and in those cases it sets a fallback default to utf8 which is
the default character encoding for python3 strings.
=> Add handling for no stdout encoding to text drawer

qiskit/transpiler/passes/scheduling/alap.py, qiskit/transpiler/passes/scheduling/asap.py, test/python/circuit/test_scheduled_circuit.py
Fix #5771 
Within scheduling passes, `Instruction` object is used to store duration. However, instructions in scheduled circuit was not always guaranteed to have different objects, and failed to report correct durations occasionally. This PR fix the bug by ensuring all instruction objects in scheduled circuit are different.
=> Fix incorrect durations in scheduled circuit

qiskit/pulse/schedule.py, test/python/pulse/test_schedule.py
Fixes #5754
* Explicitly allow times to either be ``numpy.integer`` or ``int``
* Add test
=> Pulse Schedules: allow mixed schedule time types

qiskit/algorithms/amplitude_amplifiers/grover.py, qiskit/algorithms/optimizers/aqgd.py, qiskit/algorithms/optimizers/gsls.py, qiskit/algorithms/optimizers/spsa.py, qiskit/opflow/gradients/circuit_gradients/lin_comb.py, qiskit/opflow/gradients/circuit_qfis/lin_comb_full.py
Algorithms and Opflow are new in Terra so remove any deprecated method or method parameters.
As requested on issue  #5776, it removes deprecation with the exception of Grover that is handled on PR #5680
=> Remove deprecated methods/parameters from algorithms and opflow

qiskit/circuit/register.py, qiskit/qobj/utils.py, qiskit/quantum_info/operators/pauli.py, qiskit/quantum_info/operators/symplectic/clifford.py, qiskit/quantum_info/operators/symplectic/pauli_table.py, qiskit/quantum_info/operators/symplectic/pauli_utils.py, qiskit/quantum_info/operators/symplectic/random.py, qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py, qiskit/quantum_info/operators/symplectic/stabilizer_table.py, qiskit/visualization/pulse_v2/generators/waveform.py, qiskit/visualization/utils.py, test/python/circuit/test_circuit_registers.py, test/python/pulse/test_samplers.py, test/python/quantum_info/operators/symplectic/test_clifford.py, test/python/quantum_info/operators/symplectic/test_pauli_table.py, test/python/quantum_info/operators/symplectic/test_stabilizer_table.py, test/python/quantum_info/test_pauli.py
The latest release of numpy, 1.20.0, deprecated type aliases for
python's built in numeric types (complex, int, float, etc). The usage of
these aliases has caused a myriad of deprecation warnings on import and
during runtime everytime they were used. This commit fixes this so that
terra's 0.16.x series is compatible with numpy 1.20.0.
This commit is effectively a backport of #5758 and #5768 but because of
significant divergance between master and stable/0.16 it was not a
straight backport.
=> Fix compatibility with numpy 1.20.0

tools/find_optional_imports.py
In #5582 we added a script that is used to ensure we don't import
slow optional dependencies in the default 'import qiskit' path. Since
that PR merged we've managed to remove a few more packages from the
default import path (see #5619, #5485, and #5620) which we should add
the same checks to to ensure we don't regress and accidently start
importing them again in the default path. This commit adds all these
packages to the list of imports not allowed as part of 'import qiskit'.
=> Update slow optional import list to include additional packages

qiskit/circuit/quantumcircuit.py, test/python/circuit/test_circuit_operations.py
Fixes #5802
After `circuit.remove_final_measurements()`, `circuit.clbits` property is not being updated.
=> Clean QuantumCircuit.clbits after QuantumCircuit.remove_final_measurements

azure-pipelines.yml, constraints.txt, qiskit/opflow/converters/abelian_grouper.py
Since the pulse simulator in the aer 0.7.4 release appears to not be
compatible with numpy releases <1.20.0 (see Qiskit/qiskit-aer#1120) we
need to ensure that we're running jobs that use aer with numpy 1.20.0
too. This commit attempts to ensure we're using the latest numpy release
in all CI jobs to unblock CI while we wait for a fixed aer release.
=> Attempt to install latest numpy in all CI jobs

Makefile, azure-pipelines.yml, tox.ini
Move pycodestyle max-line-length to tox.ini
Keeps it all consistent in one place, and makes it so that people don't have to configure their editor to use the non-default commandline option, if they are using pycodestyle for live linting in their editor.
=> Move pycodestyle max-line-length to tox.ini

qiskit/__init__.py
There is a typo in the docstring fro class IBMQWrapper.
Should read: "wrapper"
Reads: "wraooer"
=> Correct typo in docstring of ``IBMQWrapper``

qiskit/transpiler/passes/layout/noise_adaptive_layout.py
Fixes #5530 
Changes in #5411, to use retworkx's neighbors() function, replaces the
returned dict with an iterator. In the dict version, neighbor node indices
are the keys and therefore, they are unique. In the iterator version, node
indices appear multiple times, once per edge in multigraphs.
This commit uses a Python set to preserve the semantics of the old version
ensuring the uniqueness of the nodes.
=> Ensure uniqueness of nodes in neighbors()

qiskit/quantum_info/operators/symplectic/clifford.py
In #5617 a single usage of np.int slipped in to the clifford module.
This type is deprecated in numpy 1.20.0 and is just an alias for
python's stdlib int type (see #5788 and #5758 for the earlier fixes).
This usage is causing downstream failures in other project's CI that
use this module in environment's where warnings aren't allowed (mainly
ignis's docs builds). This commit fixes this stray np.int usage to
unblock CI and remove the deprecation warning from anything using the
clifford module.
=> Remove stray np.int usage

qiskit/circuit/register.py, qiskit/quantum_info/operators/symplectic/pauli.py, qiskit/quantum_info/operators/symplectic/pauli_table.py, qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py, qiskit/quantum_info/operators/symplectic/stabilizer_table.py
Fix an `isinstance` of statement to allow all numpy integers.
Discussed in #5758
=> Fix an isintanceof statement to allow all numpy integers

qiskit/opflow/primitive_ops/pauli_sum_op.py, test/python/algorithms/test_qaoa.py, test/python/algorithms/test_vqe.py, test/python/opflow/test_pauli_sum_op.py
I misunderstood about the endian in the PauliSumOp.
I think this endian is correct, but please double check it.
[test_vqe.py](https://github.com/Qiskit/qiskit-terra/compare/master...ikkoham:fix-paulisumop-eval?expand=1#diff-5d988c768c31118bf11473a07191e32dbb3a7dfde87f5631c7b34fb7d0e602d6R150) is the revert of the previous PR https://github.com/Qiskit/qiskit-terra/pull/5623.
=> Fix the endian bug in PauliSumOp

requirements-dev.txt, setup.py
Tweedledum is highly unstable piece of software that might break backward compatibility, as in mentioned in https://github.com/Qiskit/qiskit-terra/issues/5852
Pinning tweedledum version fixes https://github.com/Qiskit/qiskit-terra/issues/5852
=> pin tweedledum version

azure-pipelines.yml
We're histting a relatively high tutorial job failure rate caused by
jupyter/jupyter_client#541 on certain notebooks we run in the tutorials
job. This appears to be caused by multiprocessing usage inside the
qiskit that print to stdout while running. To try and avoid this issue,
this commit disables parallelism in qiskit by setting the env var to do
that. The only concern is whether we have sufficient time budget to
execute the notebooks in CI.
=> Try disabling parallelism on tutorials job

qiskit/circuit/bit.py, qiskit/circuit/register.py, releasenotes/notes/bit-register-immutable-7a06a212400b3b60.yaml, test/python/circuit/test_bit.py, test/python/circuit/test_circuit_registers.py
This commit changes the Register and Bit classes to make the attributes
used in the hash of an object immutable. We previously would allow these
attributes to be settable after object creation. However this would lead to
unsound behavior that would corrupt container structure that rely on a hash
(such as a `dict`) since these attributes are treated as immutable
properties of a register or bit. [1] To avoid this unsound behavior the
attributes of a Register and Bit are no longer settable after initial
creation. This is technically a breaking API change, but because doing
this operation before would result in breaking Python's `__hash__` API and
potentially result in unsound behavior this is necessary.
Fixes #4705
[1] https://docs.python.org/3/glossary.html#term-hashable
=> Make Register and Bit hashed attrs immutable

qiskit/opflow/gradients/circuit_qfis/overlap_diag.py, test/python/opflow/test_gradients.py
* Allow multi-parameter gates if all parameter are bound.
* Don't use bare assertion.
* Add error message on unsupported gate.
E.g. the following circuit was not supported due to the U-gate.
```python
circuit = QuantumCircuit(1)
circuit.u(1, 1, 1, 0)
circuit.ry(parameter, 0)
```
=> Fix more bugs in OverlapQFI on multi-parameter gates

.travis.yml
This commit adds a new CI job to publish precompiled binary wheels for
linux on aarch64 (arm64). Since the latest numpy and scipy releases now
publish wheels for aarch64 we can run CI jobs to do the same since we
won't be spending all our CI time budget compiling upstream dependencies
from source anymore. This enables users running on linux aarch64 systems
to install qiskit without having to compile everything from source
anymore.
=> Add linux arm64 release wheel jobs

test/python/algorithms/test_qaoa.py, test/python/circuit/test_circuit_registers.py
Replace `np.bool` and `np.int` with `bool` and `int`, respectively.
See #5758 for details.
This PR also fixes a random seed of test_qaoa.
=> Remove np.bool and np.int in the unit tests

qiskit/dagcircuit/dagdependency.py, qiskit/transpiler/passes/basis/unroll_custom_definitions.py, qiskit/transpiler/passes/basis/unroller.py
Legacy snapshot unrolling was intended to be preserved in #5701, however this was only done `unroller.py` not `unroll_custom_definitions.py`. This fixes by adding 'snapshot' back to basic_instructions for unroller custom definitions.
=> Add missing snapshot from unroller custom def

qiskit/algorithms/minimum_eigen_solvers/vqe.py, qiskit/opflow/evolutions/evolved_op.py, qiskit/opflow/expectations/aer_pauli_expectation.py, qiskit/opflow/expectations/expectation_factory.py, qiskit/opflow/list_ops/composed_op.py, qiskit/opflow/list_ops/list_op.py, qiskit/opflow/list_ops/summed_op.py, qiskit/opflow/list_ops/tensored_op.py, qiskit/opflow/operator_base.py, qiskit/opflow/primitive_ops/circuit_op.py, qiskit/opflow/primitive_ops/matrix_op.py, qiskit/opflow/primitive_ops/pauli_op.py, qiskit/opflow/primitive_ops/pauli_sum_op.py, qiskit/opflow/primitive_ops/primitive_op.py, qiskit/opflow/state_fns/circuit_state_fn.py, qiskit/opflow/state_fns/cvar_measurement.py, qiskit/opflow/state_fns/dict_state_fn.py, qiskit/opflow/state_fns/operator_state_fn.py, qiskit/opflow/state_fns/state_fn.py, qiskit/opflow/state_fns/vector_state_fn.py, qiskit/quantum_info/operators/operator.py, qiskit/utils/backend_utils.py, qiskit/utils/quantum_instance.py, test/python/algorithms/test_measure_error_mitigation.py, test/python/algorithms/test_skip_qobj_validation.py, test/python/algorithms/test_vqe.py, test/python/opflow/test_state_op_meas_evals.py, test/python/quantum_info/operators/test_measures.py
Since it is suppressed in pylintrc this cleans up a lot of imported aqua code by removing local suppressions.
Follow on from #5826 
After: 663 local suppressions
=> Drop local import-outside-toplevel suppressions

qiskit/visualization/__init__.py, qiskit/visualization/array.py, qiskit/visualization/latex.py
This PR moves the `array_to_latex `function from latex.py to array.py.
=> Move array_to_latex from latex.py to array.py

qiskit/visualization/qcstyle.py
The displaycolor object is documented with a list of defaults. I added quotes to make it copy-paste ready.
n/a
=> Fix quotes in displaycolor documentation

qiskit/circuit/instruction.py, releasenotes/notes/fix-global-phase-in-instruction-inverse-2306e4539ffb0bee.yaml, test/python/circuit/test_instructions.py
`Instruction.inverse` ignores the global phase of `instruction.definition`.  This has been fixed.
Resolves #5914.
Calling `instruction.inverse` and then adding control was causing a relative phase difference. This was the root of #5914 since the grover operator in the amplitude estimation circuit had a global phase in its definition.
=> fix global phase in Instruction.inverse

qiskit/circuit/quantumcircuit.py, releasenotes/notes/calibrations-add-iadd-265b92f42ffce92a.yaml, test/python/circuit/test_calibrations.py
Fixes #5908
Added the calibrations to methods `combine` and `extend`.
=> Fix to carry over calibrations with __iadd__ and __add__

qiskit/transpiler/passes/layout/noise_adaptive_layout.py, requirements.txt
In #5847 we added a set() cast to calls to retworkx's graph neighbors
method. This was to workaround a bug in retworkx where duplicate node
indices would be returned if there were parallel edges to a successor
node. In the recent retworkx 0.8.0 release this issue has been fixed
[1][2] so there is no need to cast to a set anymore. Removing the set
cast will remove a duplicate iteration (to generate the set) over the
neighbors list, marginally improving performance.
[1] https://retworkx.readthedocs.io/en/stable/release_notes.html#bug-fixes
[2] https://github.com/Qiskit/retworkx/commit/49727f82c4d93ea8dfd76c69a2751173af38501e
=> Remove set() cast in noise adaptive layout

qiskit/opflow/primitive_ops/tapered_pauli_sum_op.py
This single line was printing a lot of deprecate messages in chemistry.
=> Replace np.int for int on opflow due to new numpy

qiskit/quantum_info/synthesis/one_qubit_decompose.py
This commit improves the performance slightly of the
`OneQubitEulerDecomposer` by making to changes, avoiding the use of 
`append()` and avoiding the use of `np.isclose()`.
Avoiding `append()`, which does extra validation of the arguments when
constructing the output circuits. Instead the _append() method is used
which does not have the validation overhead, however this is not
necessary since we know how the circuit is constructed and the
arguments when adding the gate are being set correctly (there is only
1 qubit anyway).
The `np.isclose()` function quickly becomes a bottlneck in the
`OneQubitEulerDecomposer` class as the majority of the operations are
comparing angles to decide when to insert gates. However, we can avoid
this overhead by switching from numpy's isclose function which is …
=> Tune performance of OneQubitEulerDecomposer

qiskit/quantum_info/synthesis/one_qubit_decompose.py, qiskit/quantum_info/synthesis/two_qubit_decompose.py, qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py, qiskit/transpiler/passes/synthesis/unitary_synthesis.py
Previously when running the `OneQubitEulerDecomposer` the first step
it would perform is a check that the input matrix is a 1 qubit unitary.
However, in situations when we're explicitly generating a unitary matrix
and know the input we're passing is unitary there is no need to run this
check and it adds unnecessary overhead to the process. This commit adds a
new kwarg, check_unitary, to the `__call__` method on the
`OneQubitEulerDecomposer` which when set to False will skip the unitary
check to avoid this overhead. The flag is then set
when the decomposer is called from the `Optimize1qGatesDecomposition`,
`UnitarySynthesis` passes, and `TwoQubitBasisDecomposer` to avoid the
overhead when we know the input is unitary.
~This depends on #5926~
=> Add option to 1q euler decomposer for disabling unitary check

qiskit/dagcircuit/dagnode.py
Defining a `__hash__` without also defining `__eq__` goes [against the python data model](https://docs.python.org/3/reference/datamodel.html#object.__hash__).
It looks like in the past there was a custom `__eq__` but that was removed in #2006 at which time `__hash__` should have been removed also.
Its also not necessary in this case as a hash based on the object `id` is what you get by default.
Its also a performance issue: microbenchmarking reveals that set and dict operations are around 10x slower with custom hash compared to default. I didn't check but I wonder how much this was at issue in #5952 and #5685.
=> Remove DagNode.__hash__()

azure-pipelines.yml
This commit reorganizes the stages and job structure of our CI jobs to
try and improve overall project throughput. It moves to a 3 stage
pipeline instead of the 2 we used before. The first stage runs python
3.7 on all OSes and lint, the second runs the remaining unittest jobs
(for 3.6, 3.7, and 3.8), and the final stage runs the docs builds and
tutorials job (which are the slowest jobs). The goal is by splitting
thing up into more stages and making the slowest jobs run last that this
will improve overall efficiency of CI.
=> Reorganize CI jobs and stages

qiskit/dagcircuit/dagcircuit.py, test/python/dagcircuit/test_compose.py
This fixes #5999 
Calibrations in compose of DAGCircuit are now carried over. A test has also been added.
=> DAG compose carries over calibrations

azure-pipelines.yml, test/python/algorithms/algorithms_test_case.py, test/python/opflow/opflow_test_case.py, test/python/visualization/test_circuit_text_drawer.py
This commit is an attempt to fix the CI configuration around character
encoding in windows when running tests. The test jobs all rely on stestr
for running the tests which spawns multiple worker processes to execute
the tests using python's stdlib subprocess.Popen. This however can
cause issues with the default character encoding on windows (as reported
in mtreinish/stestr#295) where either the worker processes or the pipe
used for interprocess communication on windows does not carry over the
same character encoding as the parent process and reverts to the default
windows encoding of cp1252. This commit tries setting the character
encoding both through the change code page command and through setting
the LANG env variable.
For testing purposes a test is added to purposefully emit utf8 …
=> Set character encoding in windows CI

.gitignore, qiskit/quantum_info/states/cython/exp_value.pyx, qiskit/quantum_info/states/densitymatrix.py, qiskit/quantum_info/states/statevector.py, test/python/quantum_info/states/test_densitymatrix.py, test/python/quantum_info/states/test_statevector.py
Fixes bug in #5941 that showed up in Aer CI tests.
Also fixed the phase coefficient of the `Pauli` operator not being applied if it was not `1`.
The cython function for density matrix expectation value only worked if the matrix memory was a C-contiguous array, which isnt always true since superop evolution vectorizes the array using Fortran ordering (col-vec). This updates the cython function to work on a flattened array assuming F ordering and adds some extra tests to check it works with both C- and F-ordered data arrays in density matrix.
=> Fix density matrix expval cython function

qiskit/assembler/assemble_schedules.py, qiskit/pulse/instructions/play.py, test/python/compiler/test_assembler.py, test/python/pulse/test_instructions.py
This PR removes pulse `delay` instructions from the qobj if they are on `Acquire` channels. They are unnecessary as pulse instructions are already absolutely timed. 
Additionally, an error is included when `Acquire` channels are used on `Play`.
The net result is that pulses excluding the `Acquire` instruction will not be passed into the qobj.
=> Remove delays from Acquire Channels

qiskit/quantum_info/states/cython/exp_value.pyx
A quantity is anded with a bitmask of all 1s. This should be a noop.
This PR removes anding with such a mask in two places.
If the function where the change is made is not sufficiently tested, then this PR should add a test. There doesn't appear
to be a unit test for the function in question yet.
=> Remove useless all 1s masks

qiskit/visualization/state_visualization.py
Fixes an error that is generated when only a single axis is specified for the `plot_state_city` method.
A minimal example that shows the original problem:
```
import matplotlib.pyplot as plt
from qiskit import QuantumCircuit, Aer, execute
from qiskit.tools.visualization import plot_state_city
from mpl_toolkits.mplot3d import Axes3D
qc = QuantumCircuit(2, 2)
c=qc.cregs
qc.h(0)
simulator = Aer.get_backend('statevector_simulator')
result = execute(qc, simulator).result()
statevector = result.get_statevector(qc)
fig=plt.figure(20);plt.clf()
ax = Axes3D(fig)
plot_state_city(statevector, title='Bell state', ax_real=ax, ax_imag=None)
```
=> Fix error in plot_state_city if only real axis is specified

qiskit/circuit/library/standard_gates/u.py, qiskit/circuit/library/standard_gates/u3.py
Fixes #6006 
1. Match the order of phi and lambda in [inverse U](https://qiskit.org/documentation/stubs/qiskit.circuit.library.UGate.html#qiskit.circuit.library.UGate.inverse) and [inverse U3](https://qiskit.org/documentation/stubs/qiskit.circuit.library.U3Gate.html#qiskit.circuit.library.U3Gate.inverse) to function return, as mentioned in issue #6006 .
2. fixed a typo in [inverse U gate](https://qiskit.org/documentation/stubs/qiskit.circuit.library.UGate.html#qiskit.circuit.library.UGate.inverse) docstring, which should be U(\theta,\phi,\lambda)^{\dagger} =U(-\theta,-\phi,-\lambda).
=> Fixed issue #6006 and fixed a typo

qiskit/providers/basicaer/basicaertools.py, qiskit/providers/basicaer/qasm_simulator.py, qiskit/providers/basicaer/statevector_simulator.py, qiskit/providers/basicaer/unitary_simulator.py, test/python/compiler/test_transpiler.py
This commit adds the Rz SX and X gates to basic aer simulators basis
gate set. This is necessary for running simulations of the fake backends
which are using the new basis set for the ibmq gates.
This was written by @taalexander and extracted from #5577 which is blocked on
unrelated issues. However the lack of the new basis in basicaer is blocking #6021 (which
itself has partial with #5577) overlap for test jobs where aer isn't installed. To unblock
#6021 and any other use case where basic aer not supporting the new ibmq basis
is blocking this splits out the basic aer component into a separate PR.
=> Add additional basis gates rz, sx, x to basicaer.

azure-pipelines.yml
In #5988 we changed the character encoding used in windows CI jobs so
that it was explicitly using utf8 to avoid issues with characters being
emitted from the tests outside the default windows character encoding.
This was coming up because even though python is explicitly utf8 the
shell or the pipes used for interprocess communication in stestr did not
know we were using utf8 and would raise an encoder error when trying to
write out a string with utf8 characters. However, what that PR neglected
was the later step in the windows test jobs that we pipe the subunit
stream for the test run into a junitxml generator which would also
suffer from this problem. However we did not encounter this because only
the test id, runtime, and any failure or error messages are written out
on the process …
=> Set utf8 character encoding for windows generate results steps

qiskit/circuit/quantumcircuit.py, test/python/circuit/test_registerless_circuit.py
As reported by @Cryoris , `QuantumCircuit.add_bits` (added in #5486 ) was handling `AncillaQubit`s incorrectly, leading to the following:
```
>>> qr, ar = QuantumRegister(1), AncillaRegister(1)
>>> circuit = QuantumCircuit(ar, qr)
>>> circuit.x(0)
>>> circuit.draw()
┌───┐
a0_0: ┤ X ├
└───┘
q0_0: ─────
>>> circuit.decompose.draw()
q0_0: ─────────────
┌───────────┐
a0_0: ┤ U3(π,0,π) ├
└───────────┘
```
=> Fix AncillaQubits added via .add_bits to be included in .qubits.

test/python/algorithms/test_optimizer_aqgd.py, test/python/algorithms/test_shor.py
This commit changes 3 of the slowest tests to use Aer (and skip if it's
not present) instead of basicaer and also tag tests that take >=1 min
as slow (so they're skipped by default).
Recently our CI test jobs have been growing in duration. Looking at the
statistics show the 3 slowest tests are:
`test.python.algorithms.test_optimizer_aqgd.TestOptimizerAQGD.test_simple`
`test.python.algorithms.test_optimizer_aqgd.TestOptimizerAQGD.test_int_values`
`test.python.algorithms.test_shor.TestShor.test_shor_factoring_1__15___qasm_simulator____3__5__`
which take up a signficant fraction of the total runtime. All of these
tests were using basic aer which is definitely contributing to the poor
performance. This commit switches both test modules,
`test.python.algorithms.test_optimizer_aqgd` and …
=> Switch slow algorithm tests to aer and tag slow

qiskit/assembler/assemble_schedules.py, test/python/compiler/test_assembler.py
#5971 broke the pulse simulator tests. This PR removes the condition that breaks it.
Removed the condition, if the qubits are not in the meas_map -- Raise Error
=> Fix failing pulse simulator tests

requirements-dev.txt
PR #6087 attempted to fix CI by fixing compatibility with the recent
matplotlib release 3.4.0. However to fix the deprecated API usage we
need new features from matplotlib 3.4.0 which would break compatibility
for users on older matplotlib (as our tutorials job caught since it pins
mpl to avoid a performance regression). As an alternative to that this
commit just pins matplotlib in CI so we do not install the version
emitting deprecation warnings. This means that users will see
deprecation warnings when they use some function (mainly qsphere and
bloch sphere), but until we're ready to raise our minimum supported
matplotlib version to 3.4.0 that is unavoidable.
=> Pin matlotlib in CI

qiskit/opflow/operator_base.py, qiskit/opflow/primitive_ops/primitive_op.py, test/python/algorithms/test_vqe.py
Fix #6100.
The arguments required for initialization may change in the operator in the future. So I fixed PrimitiveOp.to_matrix_op not to use the constructor.
=> Fix TaperedPauliSumOp.to_matrix_op()

constraints.txt, requirements-dev.txt
ipython and ipykernel have both recently released and since that release
a large portion of our CI jobs have started failing with exceptions in
these packages. In order to unblock CI this commit pins the packages in
the constraints files (as they're not direct dependencies).
=> Cap ipython and ipykernel in CI

qiskit/circuit/quantumcircuit.py, test/python/circuit/test_circuit_operations.py
When `remove_final_measurements()` is run it converts the circuit to a
dag, removes the measurements at the end of the dag, clears the circuit,
and then iterates over the modified dag copying the instructions back
into the circuit. As part of this process though the parameter table is
not cleared, this resulted in duplicate entries in the table for each
parameter, one with the old instructions and the other for the new
copies. In practice this didn't really do anything, as the old
instructions weren't in the circuit, until someone went to run the
`copy()` method which iterates over the parameter table to ensure things
are updated, in which case the duplicates would result in a `KeyError`.
This commit fixes this issue by clearing the parameter table in
`remove_final_measurements` too so …
=> Properly clear parameter table on remove_final_measurement

.mergify.yml
@mtreinish noticed that `strict: smart+fasttrack` would be better than `strict: smart`, in that it will move PRs already based on master to the head of the merge queue.
=> Mergify to fasttrack merging of PRs already based on master.

qiskit/circuit/bit.py, qiskit/opflow/gradients/circuit_qfis/overlap_diag.py, qiskit/quantum_info/operators/dihedral/dihedral.py, qiskit/quantum_info/operators/dihedral/dihedral_circuits.py, qiskit/quantum_info/operators/symplectic/base_pauli.py, qiskit/transpiler/passes/layout/noise_adaptive_layout.py, qiskit/transpiler/passes/utils/check_gate_direction.py, qiskit/transpiler/passes/utils/gate_direction.py, qiskit/visualization/gate_map.py, qiskit/visualization/latex.py, qiskit/visualization/timeline/generators.py, qiskit/visualization/timeline/layouts.py, qiskit/visualization/utils.py, releasenotes/notes/quantumcircuit-optional-registers-60f0b2832ec95239.yaml, test/python/circuit/test_bit.py, test/python/quantum_info/operators/test_dihedral.py, test/python/visualization/test_gate_map.py
Deprecate references from Bit objects to their containing Register.
~on hold for #5519 .~
=> Deprecate Bit.index and Bit.register

constraints.txt, test/python/algorithms/test_qaoa.py
In the qaoa tests networkx was being used to generate a random
adjancency matrix as an input. This would work fine especially as the
graph size is small so performance isn't an issue. However, with the
recent release of decorator 5.0.0 earlier today these tests are
failing because of an [internal incompatibility](https://github.com/networkx/networkx/issues/4718) with the random state
decorator networkx is using for random_gnp_graph() function. Instead
of pinning decorator in the constraints file and hoping people running
tests without tox know to use it, this commit just switches that test to
use retworkx instead. retworkx doesn't have an external dependency on
decorator (or anything except numpy) and can generate an adjacency
matrix for a gnp random graph in basically the same exact way …
=> Stop using networkx for qaoa tests

qiskit/circuit/quantumcircuit.py
I have corrected the typo to 'noancilla' instead of 'no-ancilla' as said by @jsistos 
Fixes #6149
=> Fixed Typo in docstring for MCX gate (Issue #6149)

qiskit/algorithms/minimum_eigen_solvers/vqe.py, qiskit/dagcircuit/dagdependency.py, qiskit/dagcircuit/dagdepnode.py, qiskit/providers/__init__.py, qiskit/quantum_info/operators/channel/quantum_channel.py, qiskit/quantum_info/operators/symplectic/clifford.py, qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py, qiskit/quantum_info/states/densitymatrix.py, qiskit/quantum_info/states/statevector.py, qiskit/quantum_info/synthesis/one_qubit_decompose.py, qiskit/transpiler/passes/optimization/collect_2q_blocks.py, qiskit/transpiler/passes/optimization/crosstalk_adaptive_schedule.py, test/python/transpiler/test_preset_passmanagers.py
Fix spelling. Follow-up of #6160 
I checked the code using `sphinxcontrib-spelling`. I leave typos in the release notes. If you wish, I can fix spelling of release notes too.
The typo of qiskit.qasm.OpenQASMLexer.get_tokens_unprocessed is part of pygments.
Spell check results with this PR
```
/Users/ima/tasks/1_2021/qiskit/terra/docs/release_notes.rst:550: Spell check: passess: Two new transpiler passess, .
/Users/ima/tasks/1_2021/qiskit/terra/docs/release_notes.rst:550: Spell check: inteded:  module. These new passes are inteded to.
/Users/ima/tasks/1_2021/qiskit/terra/docs/release_notes.rst:655: Spell check: efficent: , with more efficent circuits based on.
/Users/ima/tasks/1_2021/qiskit/terra/docs/release_notes.rst:960: Spell check: apperance: New stylesheets can take callback …
```
=> Fix spelling in several docstrings

MANIFEST.in
In the recent terra 0.17.0 release the sdist on pypi is not buildable,
this is because it didn't include the cython pyx file for the pauli
expectation values function that was new for 0.17.0. This was not caught
in CI or local testing because the missing file is present in a git
checkout, but since it's not a *py file they are not included in the
sdist. This commit fixes this issue by updating the MANIFSET.in file to
include all cython files in qiskit instead of just the stochastic swap
file. Making this more broad is a good idea as there will likely be
additional cython modules added over time and this will ensure this
error doesn't happen again.
=> Ensure we include all cython files in sdist

qiskit/quantum_info/states/statevector.py, qiskit/visualization/state_visualization.py
In the new draw method in the statevector we did not port the paulivec and the city. Both of these are common and should be there as they offer a different way of viewing the state. Paulivec is common for states that are stabilizers and city gives better feel for the size of the bars than Hinton.
=> Adding Pauli and city to the draw option for statevector

qiskit/transpiler/passes/basis/unroller.py, releasenotes/notes/bugfix-global-phase-unroller-d1ac1a248558c1d8.yaml, test/python/transpiler/test_unroller.py
Resolves #6134.
`Unroller` doesn't preserve global phase in case of an instruction with nested "simple" (one rule) definitions. To fix this the global phase should be accumulated while traversing the rules.
=> Preserve global phase in `Unroller`

qiskit/algorithms/optimizers/spsa.py, releasenotes/notes/fix-spsa-recalibration-cbdae6fab0b8ef8b.yaml, test/python/algorithms/optimizers/test_spsa.py
Fix a bug where using :class:`~qiskit.algorithms.optimizers.SPSA` with automatic
calibration of the learning rate and perturbation (i.e. ``learning_rate`` and
``perturbation`` are ``None`` in the initializer), stores the calibration for all
future optimizations. Instead, the calibration should be done for each new objective
function
E.g. running
```python
def f1(x): return -(x ** 2)
def f2(x): return -10000 * (x ** 2)
spsa = SPSA(maxiter=100)
result1 = spsa.optimize(1, f1, initial_point=[0.5])  # calibrates learning rate and perturbation according to f1
result2 = spsa.optimize(1, f2, initial_point=[0.5])  # uses the calibrations from f1 instead of recalibrating for f2!
```
=> Fix SPSA recalibration

qiskit/opflow/state_fns/dict_state_fn.py
This makes the implementation of `DictStateFn.num_qubits` more performant.
In the previous implementation, a list of each of the terms in the state function is constructed, and the number of qubits (length) of the first one is returned. (It is assumed that the `DictStateFn` is constructed correctly so that each term (a string) is of the same length.)
In this PR, the intermediate list is not constructed. An iterator over the keys is used instead.
This is also more elegant and should be the canonical way to get and operate on the first key in a dict.
fixes #5803
=> Make DictStateFn.num_qubits more efficient

qiskit/quantum_info/operators/channel/kraus.py
Fixes #6144 
The documentation for quantum_info.Kraus had an incomplete and redundant statement: 'The Kraus representation for a quantum channel $\mathcal{E}$ is a set of matrices $[A_0, ... A_{K-1}]$ such that'. This line has been removed from the docstring, as the remaining documentation conveys the required information completely.
=> Remove redundant docstring in quantum_info.Kraus

qiskit/transpiler/passes/scheduling/calibration_creators.py, releasenotes/notes/calibration-builder-index-fix-779f3f40fae040d8.yaml
PR #6069 deprecated Bit.index which the CalibrationCreator was using. This PR aligns the CalibrationCreator to the new methodology.
The code now uses the methodology based on:
```
bit_indices = {bit: index for index, bit in enumerate(dag.qubits)}
```
=> * Aligned the CalibrationCreator to the removal of Qubit.index.

MANIFEST.in, azure-pipelines.yml, test/python/basicaer/test_qasm_simulator.py, test/python/circuit/test_circuit_load_from_qasm.py, test/python/compiler/test_compiler.py, test/python/compiler/test_transpiler.py, test/python/converters/test_ast_to_dag.py, test/python/qasm/entangled_registers.qasm, test/python/test_qasm_parser.py, test/python/test_schemas.py, test/python/tools/jupyter/test_notebooks.py, test/python/transpiler/test_mappers.py, test/python/visualization/test_circuit_latex.py, test/python/visualization/test_circuit_visualization_output.py, test/python/visualization/test_pass_manager_drawer.py, test/python/visualization/test_pulse_visualization_output.py
Previously we were never explicitly testing the generation of an sdist
and whether we could build a package from that generated sdist. This
caught us by surprise in the 0.17.0 release because of an oversight
in #5941 we forgot to update the MANIFEST.in to include the new cython
source files which resulted in an sdist that could not be built. To
prevent potential issues like this in the future this commit modifies
one of the existing test jobs to explicitly generate an sdist and
install from that sdist instead of just pip installing the repo. This
will prevent such issues in the future.
=> Modify linux 3.7 CI job to install from sdist

qiskit/visualization/latex.py, test/python/visualization/references/test_latex_big_gates.tex, test/python/visualization/references/test_latex_ghz_to_gate.tex, test/python/visualization/references/test_latex_init_reset.tex, test/python/visualization/references/test_latex_iqx.tex, test/python/visualization/references/test_latex_pauli_clifford.tex, test/python/visualization/references/test_latex_r_gates.tex, test/python/visualization/references/test_latex_scale_default.tex, test/python/visualization/references/test_latex_scale_double.tex, test/python/visualization/references/test_latex_scale_half.tex
Fixes #2092 .
This PR introduces numbering of active wires when drawing custom instruction in latex drawer. This PR is a part of #5551 refactored to PR #5855. The latex tests containing multiqubit boxed instructions have been updated to adapt this change. Some examples of the modified circuits containing custom instructions are as below:
=> Latex drawings now show numbering of active wires in custom instructions

qiskit/version.py
With the release of the domain specific qiskit application packages,
qiskit-finance, qiskit-nature, qiskit-optimization, and
qiskit-machine-learning it would be useful to optionally include the
versions in the `__qiskit_version__` attribute which is used for
debugging and by the jupyter extension used in tutorials to show
package versions. This commit adds entries to the `__qiskit_version__`
dict so that if any of the application packages are installed their versions
will show up in the dictionary.
=> Add qiskit application modules to __qiskit_version__

requirements-dev.txt
In #4556 we pinned sphinx to workaround some CI failures related to new
warnings being emitted by sphinx with the release sphinx 3.1.0. Since
then there have been several releases of sphinx with new features and
more importantly several bug fixes, and the warnings previously being
emitted no longer seem to be an issue (at least for local builds on
python 3.8). This commit removes the pin so we can use the latest
version of sphinx in CI and locally.
=> Remove sphinx pin

qiskit/algorithms/phase_estimators/phase_estimation_scale.py
This makes the computation of the eigenvalue bound  for Hamiltonian phase estimation slightly more efficient.
* Factors a factor out of a sum
* Avoid construction of a list
=> Make computation of bound for phase estimation more efficient

azure-pipelines.yml
stestr maintains a local repository of run history which is used for
both local debugging (like for automated bisecting of failures between
runs) and also to provide data for parallel test scheduling based on the
the previous run time. In #5451 we added a cache step to the azure ci
configuration to cache the .stestr directory (the default location of
the stestr local repository) to preserve the run history to improve
parallel test scheduling to try and improve throughput. This however had
the unintended side effect of growing the stestr repository directory
significantly. Right now the stestr cache is several gigabytes in size.
This is because stestr will keep a history of all the runs in that
directory and by preserving it in a cache it's growing every time we
commit to the branch. …
=> Cleanup stestr caching to only what's necessary

qiskit/algorithms/phase_estimators/hamiltonian_phase_estimation_result.py, qiskit/algorithms/phase_estimators/phase_estimation_result.py, qiskit/algorithms/phase_estimators/phase_estimator.py, test/python/algorithms/test_phase_estimator.py
IterativePhaseEstimation #6096 will satisfy the PhaseEstimator interface.
However, the property for retrieving the phase is currently
`PhaseEstimator.most_likely_phase`, which is too specific to accomodate
IterativePhaseEstimation, which only computes a single phase in any
case. This PR renames this property to `phase`, and leaves the
definition of `phase` to the specific implementation.
This PR currently does not include a deprecated version of the previous attribute `most_likely_phase`. Perhaps it should.
=> [WIP] Change attribute `most_likely_phase` to `phase` in PhaseEstimator

qiskit/algorithms/phase_estimators/phase_estimation_scale.py, qiskit/transpiler/passes/optimization/optimize_swap_before_measure.py, releasenotes/notes/optimize-swap-condition-a8ac54e6cb3d9ba4.yaml, test/python/transpiler/test_optimize_swap_before_measure.py
Fixes #6192
If a `SwapGate `has a condition on it, this PR will not remove that swap or change the `Measure `when running `OptimizeSwapBeforeMeasure`.
=> Don't remove swaps with conditions in OptimizeSwapBeforeMeasure

qiskit/quantum_info/synthesis/clifford_decompose.py, test/python/quantum_info/operators/symplectic/test_clifford.py
This PR fixes a small bug in clifford instruction naming, caused by `def decompose_clifford_` simplifying the giving clifford, changing its name in the process, before using the name for the resulting instruction. This results in correct behavior but wrong naming.
=> Bugfix in clifford instruction name

.travis.yml, CONTRIBUTING.md, azure-pipelines.yml, qiskit/test/testing_options.py, qiskit/version.py, tools/report_ci_failure.py
With the pending support being added to qiskit-bot in
Qiskit/qiskit-bot#9 we're able to rename the default branch for the
repository to 'main'. However, when we do that several things will need
to be updated, most importantly the CI trigger was hardcoded to the
previous default branch 'master. This commit fixes these references and
should be merged after we rename the branch to re-enable CI.
=> Prepare for renaming default branch to main

qiskit/algorithms/amplitude_amplifiers/amplification_problem.py, test/python/algorithms/test_grover.py
Fix type hints for AmplificationProblem, and revise the test case accordingly.
Fit the type hint for the oracle parameter of the constructor of the AmplificationProblem class, according to the corresponding parameter of the GroverOperator class and to the code to instantiate the class in test_grover.py
FIx the type hint for the is_good_state parameter of the constructor of the AmplificationProblem class, according to the corresponding property method which handles four different types. 
Revise the test for the property method in test_grover.py, so that it exercises all the four types.  This led me to change the good state used in the test to keep the one-state-for-all "principle".
=> Fix type hints for AmplificationProblem

qiskit/visualization/circuit_visualization.py, qiskit/visualization/latex.py
The following example fails in `main`:
```python
from qiskit.circuit import BooleanExpression, QuantumCircuit
expression = BooleanExpression('~x & (y | z)')
circuit = QuantumCircuit(4)
circuit.append(expression, [0, 1, 2, 3])
circuit.draw('latex')
```
```
CalledProcessError: Command '['pdflatex', '-halt-on-error', '-output-directory=/tmp', 'circuit.tex']' returned non-zero exit status 1.
```
Several reasons, but mostly because the `~`. This PR takes care of that corner case.
=> BooleanExpression expression breaks label in the latex circuit drawer

qiskit/opflow/__init__.py, qiskit/opflow/state_fns/__init__.py, qiskit/opflow/state_fns/sparse_vector_state_fn.py, releasenotes/notes/fix-sparse-statefn-equality-and-to-dict-96d1a1ae98bcdb52.yaml, test/python/opflow/test_op_construction.py
Fix the `to_dict_fn` and `equals` methods and add the class to the `qiskit.opflow` and `qiskit.opflow.state_fns` init files.
The `to_dict_fn` method previously had at most one entry for the all zero state due to an index error.
The `equals` method to returns now `True` or `False` instead of a sparse vector comparison of the single elements.
=> Small fixes in the ``SparseVectorStateFn``

qiskit/extensions/quantum_initializer/initializer.py, releasenotes/notes/fix_initializer_global_phase-977eea9d416c9918.yaml, test/python/circuit/test_initializer.py
Fixes global phase in initializer.
fixes #5230
=> fix global phase in initializer

qiskit/opflow/state_fns/operator_state_fn.py
This PR improves the performance of `eval() of (OperatorStateFn @ VectorStateFn)`.
When I implemented PauliSumOp, I took a profile for QEOM. https://github.com/Qiskit/qiskit-terra/pull/5537
As you can see on the right side of this profile, `eval()` of `OperatorStateFn` spends a lot of time.
This PR changes to use the expectation_value in quantum_info and it achieves more than 1000 times performance improvement.
=> Improve Performance of eval() of OperatorStateFn @ VectorStateFn by > 1000 times

azure-pipelines.yml
This commit adds a new wheel job for building universal2 wheels for
macOS. The universal2 wheels will enable running on arm64 macOS systems.
As we don't have any arm64 mac hardware available in CI systems yet
these jobs are cross-compiling arm64 binaries from an x86_64 mac, we
also can't test the arm64 binary component as part of the job because of
this.
This commit also takes the opportunity to update the cibuildwheel
version used for CI to the latest release 1.10.0, since we need to 
use >=1.9.0 for arm on macOS support.
Related to Qiskit/qiskit#1201
=> Add macos universal2 wheel job

qiskit/visualization/pulse_v2/generators/frame.py, qiskit/visualization/pulse_v2/generators/waveform.py, test/python/visualization/pulse_v2/test_generators.py
General object generation fix for v2 pulse visualizer.
Fix #5951 
The bug is induced by accessing to the `.name` property of `ParameterExpression` which doesn't exist. The object is now directly passed to string formatter. Along with this fix, I updated pulse name generation logic which is currently force overriding pulse names in the measurement channel as `Measure`. This may hurt user experience in some corner case, see [Qiskit Textbook 6.6](https://qiskit.org/textbook/ch-quantum-hardware/ac-Stark-shift.html). M channel is used as a off-resonant drive channel to induce Stark shift. Pulse name of this pulse is `resonator tone` in this example.
=> Fix draw object generation in v2 pulse visualizer

qiskit/quantum_info/operators/symplectic/base_pauli.py, releasenotes/notes/fix-pauli-evolve-c6653853962885cd.yaml, test/python/quantum_info/operators/symplectic/test_pauli.py
Fixes bug in the `Pauli.evolve` function when evolving CY, CZ, or Swap gates.
Fixed the tests that should have caught this bug. These gates were being synthesized via clifford back to CX + 1 qubit clifford gates which were all working correctly.
=> Fix bug in ``Pauli.evolve`` for CZ, CY, Swap

qiskit/visualization/dag_visualization.py
When drawing a DAG with `dag_drawer` an exception can occur when the method tries to remove the temporary file while the temporary file is still open in the PIL Image. The PR fixes the problem by making a copy of the `Image` and then closing the original `Image` before removing the file. Fixes #6256
For opening and closing a context manager is used as provided by `PIL`.
=> fix error when `dag_drawer` removes a temporary file that is still open

qiskit/quantum_info/states/densitymatrix.py, qiskit/quantum_info/states/statevector.py, releasenotes/notes/fix-expval-pauli-qargs-183843993ca83f71.yaml, test/python/quantum_info/states/test_densitymatrix.py, test/python/quantum_info/states/test_statevector.py
Fixes #6303 
Fixes bug in Statevector and DensityMatrix expectation_value method where the qargs kwarg was ignored if the operator was a Pauli or SparsePauliOp.
=> Fix expval pauli qargs bug

qiskit/quantum_info/states/quantum_state.py, releasenotes/notes/fix-state-probabilities-qargs-f5f2a29dc07e69cd.yaml, test/python/quantum_info/states/test_statevector.py
Fixes #6320 
Fixes bug in how permuted probabilities were calculated for non-trivial `qargs` kwarg in Statevector and DensityMatrix probabilities.
=> Fix QuantumState._subsystem_probabilities

qiskit/pulse/builder.py, test/python/pulse/test_builder.py
Fix #6323 
This bug was induced by method name upgrade for backward compatibility. `.instructions` returns `Tuple[t0, Instruction]`, but this requires block-to-schedule conversion. Since the subroutine call just checks number of stored instructions, this conversion is not necessary.
Conditional branch just for the method name seems to be redundant. Renaming `ScheduleBlock.blocks` to `ScheduleBlock.children` is alternative approach.
=> Fix builder call_subroutine to accept parameterized duration

qiskit/opflow/converters/pauli_basis_change.py, releasenotes/notes/fix-expectation-for-non-hermitian-op-880a3b9b13320574.yaml, test/python/opflow/test_aer_pauli_expectation.py, test/python/opflow/test_gradients.py, test/python/opflow/test_matrix_expectation.py, test/python/opflow/test_pauli_expectation.py
Fixes #6307
Remove adjoint() when PauliBasisChange converts operators.
I've fixed the test of gradient, which originally worked by taking the complex conjugate twice.
=> Fix #6307 (PauliExpectation takes unnecessary adjoint when it converts operators)

qiskit/visualization/counts_visualization.py
`plot_histogram` previously only worked for positive values, as expected given that the results are derived from counts.  However, as mentioned in #6267 we need a viewer for quasiprobabilities that can include negative values.  Doing the necessary work for #6267 is likely not going to be done on time given the myriad of other things needed, so a stop gap is to fix `plot_histogram` so that it does not crash when given small (~1e-3) negative values.  This does that.  This will not elucidate the quasiprobabilities, but it does allow for quick viewing without converting to the closest true probability dist.
=> plot_histogram does not raise for neg values

qiskit/pulse/parameter_manager.py, qiskit/pulse/schedule.py, qiskit/pulse/transforms/alignments.py, qiskit/pulse/transforms/canonicalization.py, releasenotes/notes/fix-inline-bug-6b9461fa213b0aae.yaml, test/python/pulse/test_parameter_manager.py, test/python/pulse/test_schedule.py, test/python/pulse/test_transforms.py
This is the high priority patch. These call instructions left in the schedule can crash job execution.
Fix #6321
=> Fix schedule inline transform

qiskit/transpiler/passes/basis/basis_translator.py, releasenotes/notes/bugfix-skip-target-basis-translation-12a9fa02c9ceef25.yaml
Fixes #6085. 
This commit fixes a bug in the `basis_translator.py` that was causing translation of gates already in the target basis. For example, target basis gate CX was unnecessarily translated with 4 CX gates. The fix will check gate names in the `current_basis` during translation, and if it matches with any gate on the target basis, it will skip equivalence checking (and possible translation) for that gate.
I ran `tox`, and the tests are passing. However, I did not add any tests.
=> BasisTranslator skips translating gates already in target basis

qiskit/opflow/gradients/derivative_base.py
Follow up on #6335. Remove SymPy usage (and code duplication) from ``DerivativeBase`` and instead rely on ``ParameterExpression.gradient``.
=> Remove SymPy usage from Opflow's DerivativeBase

qiskit/circuit/parameterexpression.py
As reported in symengine/symengine.py#351 and
Qiskit/qiskit-machine-learning#84 when trying to use a single precision
numpy float symengine raises an error. To workaround this (and unblock
machine-learning) this commit just casts to a python float before we
pass the value to symengine. This should avoid the incompatibility and
enable machine learning to continue to use np.float32 until support is
added in symengine.
Fixes Qiskit/qiskit-machine-learning#84
=> Cast numpy fixed precision types for symengine subs

test/python/transpiler/test_basis_translator.py
This PR adds a test to the changes in #6350 which was merged as part of 0.17.2.
=> Add test for 6350

CONTRIBUTING.md
=> Fix missing parenthesis in CONTRIBUTING.md

qiskit/dagcircuit/dagcircuit.py, qiskit/transpiler/passes/basis/basis_translator.py
With recent adoption of symengine for the performance critical path
with ParameterExpressions the workaround for large expression evaluation
in #6072 is no longer needed or applicable, except in environments
without symengine. However, with symengine available using the sympy
evaluate context adds noticeable overhead, both to import sympy (which
wouldn't be used otherwise) and to load the sympy evalue context
wrapper. This commit removes these as we shouldn't compromise performance
in the performance path to try and speed up a path with degraded
performance because symengine isn't available (32bit platforms).
This reverts commit f436f5ab7ef903e14d46a89f2d9f1c8d9c3b4b92.
=> Revert "Set sympy.evaluate(False) on frequent code paths for phase tracking. (#6072)"

.stestr.conf, test/python/test_user_config.py, test/python/visualization/test_gate_map.py
Removing  the grouping regex in .stestr.conf should allow stestr to pack its test workers better, and therefore improve the speed of test execution. However, pre-existing test cases utilizing non-unique tempfiles began to fail after the configuration change. This commit modifies such tests to pass under these new conditions. This also allows the test suite to properly execute using pytest-xdist.
Fixed #6105
Per #6105 a few tests (TestGateMap and TestUserConfig) were failing when using pytest-xdist.  Both tests were reliant on a hardcoded file name "temp.txt", which is the root source of the failures.  This pull modifies both to use less brittle file buffers. 
I also went ahead and removed the regex found in https://github.com/Qiskit/qiskit-terra/blob/master/.stestr.conf#L3 as discussed in …
=> Remove stestr's grouping configuration

qiskit/utils/run_circuits.py, releasenotes/notes/respect-max-experiments-quantum-instance-aae99429034aab52.yaml, test/python/algorithms/test_backendv1.py
In #6299 support was fixed for strict BackendV1 backends that only take
QuantumCircuit objects (instead of qobj) for the input. That was fixed
by adding a parallel path when running with a new backend. However that
parallel path wasn't identical and was missing the support the qobj path
had for splitting an algorithm run into multiple jobs if the backend if
the number of circuits was greater than the max_experiments set in the
backend. This would result on some providers' backends, such as ionq and
aqt, both of which have max_experiments set to 1. This commit fixes this
issue by splitting the circuits list into smaller sublists when the
len(circuits) > max_experiments (or the old env var, which we should
change the name of at some point).
=> Respect max_experiments in QuantumInstance BackendV1 path

qiskit/circuit/parametertable.py
Removed redundant definition of `__rand__` as discussed in Qiskit Slack https://qiskit.slack.com/archives/C7SS31917/p1621176935254800
- No doc update
- No test added
- Have signed CLA
`__rand__` defined twice in qiskit/circuit/parametertable.py
Acknowledged by @mtreinish and @1ucian0 in Qiskit Slack
=> Removed redundant definition of `__rand__`

qiskit/quantum_info/operators/symplectic/pauli.py
Improves the performance of `Pauli.evolve` when evolving by a `Clifford` operator.
Computes the evolution directly from the Clifford table without converting to a circuit first.
=> Improve performance of ``Pauli.evolve``

qiskit/quantum_info/operators/measures.py
Fixed two typos in the `process_fidelity` docstring that prevented the rendering of maths formulas in the function's description.
=> Fix process_fidelity documentation

qiskit/opflow/converters/circuit_sampler.py, qiskit/utils/backend_utils.py, qiskit/utils/quantum_instance.py, qiskit/utils/run_circuits.py, test/python/algorithms/test_vqe.py, test/python/opflow/test_aer_pauli_expectation.py, test/python/opflow/test_gradients.py, test/python/opflow/test_state_op_meas_evals.py
This adds a test for statevector simulator and save_statevector in QuantumInstance in case it is not in the circuit already. This solution may not be optimal.
Also, passes circuits instead of qobj to backends.
=> QuantumInstance use circuit instead of qobj for all backends

qiskit/utils/measurement_error_mitigation.py
Fixes the code that was showing the msg: "DeprecationWarning: Back-references to from Bit instances to their containing Registers have been deprecated. Instead, inspect Registers to find their contained Bits."
=> Fix deprecate msg in Measurement Error Mitigation

requirements-dev.txt
Since the recent release of the sphinx-panels plugin the docs jobs have
all been failing CI. Since the only recent related release was this
sphinx plugin this commit caps the version to be less than the recent
version to unblock CI.
=> Pin sphinx-panels version for docs builds

qiskit/tools/parallel.py, releasenotes/notes/disable-39-multirpc-8618c89aeaa620f9.yaml
We've recently been hitting a slew of job timeouts in python 3.9 CI jobs
recently. This was originally reported in #6188 but the frequency of
these timeouts have spiked since #6270 merged which added sympy to the
default mulitprocessing path (for pickling symengine expressions by
first converting it to a sympy expression). Trying to debug this locally
is tricky but when I've reproduced it seems to be just hanging
indefinitely on pickling. I think whatever is causing the issue as
reported in #6188 was just made worse by adding a sympy import to the
pickling process (assuming there is a parameter expression in the
circuit). To workaround this issue until we can come up with a solution
for whatever is causing things to hang this commit disables
multiprocessing on python 3.9 by default (it …
=> Don't enable multiprocessing by default on Python 3.9

qiskit/circuit/instruction.py, releasenotes/notes/bugfix-gate-inverse-name-3401093a18813ace.yaml, test/python/circuit/test_instructions.py
Summary
Each call to a gate's `inverse` method appends '_dg' to the name attribute of the gate.
Details and comments
Upon running the following code,
```
qc.cx(0,1)
qc_gate = qc.to_gate(name='qc_gate')
qc_gate_inv = qc_gate.inverse()
qc_gate_inv_inv = qc_gate_inv.inverse()
print(qc_gate.name)
print(qc_gate_inv.name)
print(qc_gate_inv_inv.name)
```
The output was:
```
circuit_name
circuit_name_dg
circuit_name_dg_dg
```
The output after the proposed changes is:
```
circuit_name
circuit_name_dg
circuit_name
```
=> Fix multiple appends of '_dg' in name attribute on calling inverse()

qiskit/algorithms/minimum_eigen_solvers/vqe.py
If you have the `deprecate_function` above `property` it will return wrapper instead of the property.
This PR inverts the order.
=> Fixes deprecator decorator order on VQE optimal_params property

tools/find_optional_imports.py
In #5798 `find_optional_imports.py` had the superficially-superfluous `import qiskit` line removed. Unfortunately this stopped the script from doing its job to check if qiskit made use of the optional imports.
This PR adds this back, with a comment explaining why not to drop it, and makes a couple other minor tweaks to the file.
=> Fix find_optional_imports.py

qiskit/transpiler/passes/routing/cython/stochastic_swap/utils.pxd, tools/verify_headers.py
- Add .pxd files to those checked by verify_headers.py
- Fix utils.pxd
- Minor tweaks to verify_headers.py
=> fix verify_headers.py

tools/subunit_to_junit.py
This commit fixes several pylint issues identified in the
tools/subunit_to_junit script. This script is only used in CI to adapt
the subunit v2 output we get from stestr to the junitxml format expected
by azure pipelines for feeding the analytics. Most of the issues were
over lack of internal documentation for the internal functions. As we're
looking at running pylint on the tools dir in #6609 this commit makes the
necessary changes for pylint to pass.
=> Fix lint in subunit to junit tools script

constraints.txt
I have seen a couple instances of jobs failing due to segfaults or other
system errors when running tests that leverage jax. Looking at the
release history for jax and jaxlib, there have been multiple releases
the past few days. Until the project stabilizes these issues this commit
just pins the version we run in CI to the last release from May which
wa stable in CI.
=> Pin jax version in constraints

azure-pipelines.yml
This commit updates the azure pipelines configuration for the tutorials
job. There was a todo in there from right before the 0.17.0 release
about using git versions of ignis and aqua which we were supposed to
have fixed after the release so we don't lose the backwards compat
testing the tutorials job provides. Since then we've also removed the
aqua usage from qiskit-tutorials as the general algorithms and opflow
tutorials have been updated to use terra and the applications tutorials
have been migrated to the application repositories. So this commit
removes aqua from the installed packages list.
=> Update tutorials CI configuration

qiskit/circuit/register.py
@TimAlexisKoerner noticed that `Register.__getitem__` says in the documentation that it should raise `QiskitIndexError` when out of range. (see #6574).
=> Fix in Register.__getitem__ docstring

qiskit/transpiler/passes/basis/unroll_3q_or_more.py, qiskit/transpiler/passes/utils/check_map.py, test/python/compiler/test_transpiler.py
This commit fixes an issue in a couple of transpiler passes where a
multiqubit gate on >2 qubits that has a custom calibration. When a gate
has a calibration it should mostly be treated as a black box because the
pulse definition is passed directly to the backend for that gate.
However, previously for passes that worked on gates > 2 qubits weren't
correctly handling this which would result in an error. This has been
fixed so that if a multiqubit gate is in a circuit with a calibration
set it will be left as a black box and passed directly to the backend.
Fixes #6572
=> Fix calibration handling of transpiler passes on gates with >2 qubits

qiskit/circuit/library/__init__.py, qiskit/circuit/qpy_serialization.py, test/python/circuit/test_circuit_load_from_qpy.py
This commit adds string parameter handling to the qpy serialization
format. The PauliGate generalized gate class uses pauli strings as a
parameter to the constructor. If there was a PauliGate in the circuit
the qpy serialization would fail because the string parameters weren't
handled. This commit fixes that by adding string as an allowed type for
qpy parameters.
To fix the reported issue of PauliGate serialization with qpy though the
PauliGate class needs to be exported in the __init__.py for the
qiskit.circuit.library path. Without this qpy doesn't know about the
special PauliGate constructor that allows strings and tries to treat it
as a normal custom gate which will fail when trying to create it with a
string parameter.
Fixes #6660
=> Add string parameter handling to QPY

qiskit/opflow/gradients/gradient.py, qiskit/opflow/list_ops/list_op.py
This fixes a breakage that showed up in Machine Learning Tests that stemmed from the change to how Gradient detected that this was a regular Listop using its default combo_fn.
In the past it checked against `ListOp([])._combo_fn` since that was set to `lamdba x: x` when None. Now #6650 was done to serialize operators and we cannot serialize callables. So things were changed to make the default on the constructor None instead of lambda x: x and internally if its None the the property combo_fn returns lambda x: x.
So instead of checking `operator._combo_fn` with `ListOp([])._combo_fn` it was changed to check against `None`. This looks like it would work. Thing is when we doing certain operators on the ListOp it will return a copy building out the new ListOp from the modified contents and …
=> Fix for "Add Operator Settings #6650"

qiskit/circuit/gate.py, qiskit/circuit/instruction.py, qiskit/circuit/library/blueprintcircuit.py, qiskit/circuit/quantumcircuit.py, qiskit/converters/circuit_to_instruction.py, qiskit/extensions/simulator/snapshot.py
Moves `_label` attribute, and `label` getter/setter from `Gate` to its parent class `Instruction`.
There isn't really any reason labels should be specific to `Gate` subclasses rather than part for the base `Instruction` class. This allows setting custom labels for general instructions using the `inst.label` setter.
=> Move `Gate.label` to parent `Instruction` class

qiskit/transpiler/layout.py, test/python/transpiler/test_layout.py
Layout supports `del` but it doesn't work
`v2p` and `p2v` maintain bi-direction mapping.
If key is `int`, deletion must be processed
1.  delete `v2p` with `v2p[key]`
2. delete `p2v` with `key` 
else, vice versa.
=> fix bug in layout deletion

qiskit/transpiler/passes/optimization/collect_2q_blocks.py, test/python/transpiler/test_collect_2q_blocks.py
Since this #6534 merged we've seen a spike in test failures with
test_transpile_across_optimization levels where the transpile fails to
stabilize on a fixed depth. While we haven't confirmed the root cause of
the failure to be #6534 given the proximity to the release, the relative
timing adds up. The performance improvement the PR made was good, but
not critical as collect_2q_blocks is hardly ever a bottleneck. Given the
proximity to the 0.18.0 release this commit reverts #6534 to try and
relieve pressure on CI. We can reinvestigate adding this back after the
0.18.0 release.
The test that is failing is being improved in #6685 to isolate the test
methods to one for each optimization level. This will hopefully let us
debug the failure more easily when we re-apply #6534
This reverts commit …
=> Revert "Performance improvement for Collect2qBlocks (#6534)"

qiskit/circuit/library/blueprintcircuit.py, qiskit/circuit/quantumcircuit.py, releasenotes/notes/compose-can-wrap-e839c29e426051e8.yaml, test/python/circuit/test_compose.py
Add the option to wrap circuits in ``QuantumCircuit.compose``. This makes ``append`` for circuits obsolete so that for circuit compositions only ``compose`` is used.
If the circuit to compose is unitary and `wrap=True`, it will be added as `Gate` to maintain access to unitary operations such as control, otherwise as `Instruction`.
Here's a brief example:
```python
from qiskit.circuit import QuantumCircuit
oracle = QuantumCircuit(2, name='Oracle')
oracle.cz(0, 1)
qc.h(range(2))
qc.compose(oracle, wrap=True, inplace=True)
print(qc.draw())
```
yields
```
┌───┐┌─────────┐
q_0: ┤ H ├┤0        ├
├───┤│  Oracle │
q_1: ┤ H ├┤1        ├
└───┘└─────────┘
```
=> Add the option to wrap circuits in ``QuantumCircuit.compose``

qiskit/circuit/library/grover_operator.py, test/python/circuit/library/test_grover_operator.py
Fixes the finance tutorials (see also https://github.com/Qiskit/qiskit-finance/pull/71).
Due to our current distinction into `Gate` and `Instruction` and their different features, we have to explicitly try converting the library circuits to gates and only to instructions when the gate conversion fails.
=> Fix wrapping of ``GroverOperator``

constraints.txt
Networkx 2.6 released a few hours ago and is causing a version conflict
with the matplotlib version we install in the tutorials job. The version
we use in the tutorials job was specifically pinned because of
performance issues we were seeing with newer matplotlib releases
(admittedly a while ago) to side step the issue and get 0.18.0 out the
door this commit pins the networkx version we use in the constraints
file. After 0.18.0 releases we can investigate removing the matplotlib
pin in the tutorials job and this constraint.
=> Pin networkx for CI

qiskit/circuit/qpy_serialization.py, test/python/circuit/test_circuit_load_from_qpy.py
This commit fixes an issue with generating and loading QPY files with
complex instruction parameters (initialize) or blueprint circuits that
were in a circuit. Normally complex parameter types aren't valid on
gates or instructions, however initialize uses them as the statevector
elements are stored as the parameter list for the object (instead of as
a numpy array parameter like unitary). So to fix this we need to be able
to handle this edge case and save complex numbers for parameters too.
Similarly there was an issue found when trying to deserialize a blueprint
circuit object. It doesn't seem possible to reconstruct an instance of a
blueprint circuit reliably from just the parameters list for the
circuit. This causes an issue when deserializing as the gate
reconstructed from the qpy data …
=> Handle complex parameters and blueprint circuits in QPY (#6713)

test/ipynb/results.py
In #6672, graphs were added to the binder tests. As part of this, there were 2 directories created which meant that the zip files for the mismatched images now had a variable directory name which was put in an f-string, but the f was left off. This adds the f.
=> Add f to f-strings in mpl tester results.py

docs/apidocs/qpy.rst, qiskit/circuit/qpy_serialization.py
The documentation for QPY was not building correctly and none of the
user documentation was being built. This was because of a missing
toctree argument to the autosummary directive. This commit fixes this,
but also expands the documentation to contain a top level module example
and also add a missing explanation for the complex parameter type added
in #6713 to the documentation for the INSTRUCTION_PARAM struct.
=> Fix QPY documentation

azure-pipelines.yml
This commit consolidates the 2 fast executing CI jobs for the QPY
compatibility testing and image comparison test validation to be stages
at the end of the linux 3.7 CI job. Our primary resource constraint in
CI is the number of concurrent jobs we can run (which is currently 10
jobs). These two jobs typically take < 3minutes total which includes
provision time, git checkout, and pip dependency installation time.
Since these jobs execute so quickly there is no reason to waste a CI
node to run them when we can just append these to the end of an existing
job. This commit makes this change and adds runs these test job as
separate stages at the end of the linux 3.7 job. This should hopefully
reduce the resource contention in CI slightly and improve CI throughput.
=> Consolidate quick CI jobs into 3.7 linux unittest job

qiskit/__init__.py
The plan is that 0.19 will be the last version to support Python 3.6,
with a view to begin adding 3.10 support at the same time it is removed.
=> Specify version for Python 3.6 support ending

qiskit/algorithms/optimizers/qnspsa.py, releasenotes/notes/fix-qnspsa-settings-91d5a9553706cc72.yaml, test/python/algorithms/optimizers/test_optimizers.py
Add the missing ``fidelity`` argument in the ``QNSPSA.settings`` method.
Fixes the deserialization of the optimizer with the ``RuntimeDecoder``.
=> Fix QNSPSA settings

qiskit/transpiler/passes/routing/bip_mapping.py, releasenotes/notes/fix-bip-mapper-requirements-930c7dcd5a3b82ba.yaml, setup.py
The 'cplex' package is not (presently) available on Python 3.6 or 3.9.
This means that
pip install qiskit-terra[all]
will fail on those Python versions, because the requirements cannot be
specified.
This patch makes it so that the 'all' target will treat requirements
from 'bip-mapper' as unnecessary on the relevant Python versions, but
will still enforce them if 'qiskit-terra[bip-mapper]' is specified
explicitly.
Fix #6842.
=> Exclude bip-mapper extra from all

qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py, test/python/transpiler/test_optimize_1q_decomposition.py
closes #6848 
Tames an overly active warning which is triggered during synthesis-based 1Q simplification.
In #6553, we added a warning in `Optimize1qGatesDecomposition.__call__` which was meant to check that gate sequences emitted by an operator-based 1Q synthesis routine were always more efficient (i.e., shorter) than the sequence used to form the input. The idea was that this would warn us if a synthesis routine were ever to emit a sequence which is not maximally efficient.
We made a mistake in the definition of 'maximally efficient'. In general, a synthesis routine promises to emit gates whose types form a _subset_ of some larger set of native gates, and it cannot make guarantees (nor be expected to make guarantees) about optimality of its circuits within the larger set, but only …
=> Tame 1Q simplification warning

azure-pipelines.yml
After 0cdacec (#6865) sped up the docs build to a reasonable time again,
they are no longer a CI bottleneck.  This splits the last CI stage
between the other two, increasing the parallelisation of the stages, and
hopefully getting total CI times down quite a lot.
=> Rearrange CI jobs back into two stages

qiskit/quantum_info/synthesis/two_qubit_decompose.py, qiskit/quantum_info/synthesis/weyl.py
`weyl_coordinates` was unnecessarily computing the entire
diagonalisation of the M2 matrix, even though it only needed the
diagonal.  The diagonal is just the eigenvalues (no matter the
degeneracy pattern), so this can be computed directly without the random
algorithm used to find the diagonalising SO(4) element.
The transformation to the magic basis is factored out into one place, so
only one location is responsible for it.  Factoring it out into a black
box also lets us store the basis and its adjoint with unusual
normalisations, to minimise floating-point errors when applying it.  By
storing one matrix directly as
B = np.array([[1, 1j, 0, 0], ..., [1, -1j, 0, 0]])
and the other as
B_dagger = 0.5 * B.conj().T
the normalisation of the _transformation_ is maintained, but the two …
=> Unify and simplify some Weyl decomposition code

qiskit/circuit/quantumcircuit.py
Follow-up of #6831
Fixes https://github.com/Qiskit/qiskit-optimization/issues/225. Qiskit Optimization unit test of GroverOptimizer takes so long time after the merge of #6831.
This PR resolves it by applying `repeat` if `power` is `np.integer`.
`GroverOptimizer` of Qiskit optimization set `power` by `numpy.random.Generator.integers`. The type is `numpy.int64`. So, it is necessary to use `np.integer` for `isintance` to catch this case.
https://github.com/Qiskit/qiskit-optimization/blob/4953e56e3c062df42e7e51fa6b89172e1f69e3c1/qiskit_optimization/algorithms/grover_optimizer.py#L220-L232
https://numpy.org/doc/stable/reference/random/generated/numpy.random.Generator.integers.html
=> Use `repeat` in `QuantumCircuit.power` if `power` is `numpy.integer` 

qiskit/compiler/assembler.py, releasenotes/notes/fix-assemble-parametric-pulse-eea8fba73c56a69f.yaml, test/python/compiler/test_assembler.py
This commit fixes an issue with the assemble() function. If the
parametric_pulses kwarg was set to an empty list the assemble function
was incorrectly treating this as if no parametric pulse kwarg was set.
This would result in the incorrect qobj being generated by assemble()
including any parametric pulses given for a provided backend instead of
the expected empty list. This commit fixes the issue by correcting the
logic in assemble() so we only use the backends value if the kwarg is
not set, not when the kwarg evals to False (which was the bug).
Fixes #6898
=> Correctly handle parametric pulse assemble() kwarg if empty list

qiskit/result/result.py
This fixes the broken API reference format of `Result`.
Especially, `Returns` part of `get_counts` looks broken as attached.
https://qiskit.org/documentation/stubs/qiskit.result.Result.html#qiskit.result.Result.get_counts
=> Fix the docstring of Result

qiskit/transpiler/coupling.py
Fixes #6993 
This pull request fixes the issue #6993. The documentation of the coupling map class does not specify that the indexes must be contiguous. The constructor identifies if there is a hole and adds the nodes as isolated nodes in the coupling map. I have added this requirement to the documentation in the coupling map class.
=> fixed issue #6993 documenting requirement of coupling map class

qiskit/circuit/library/blueprintcircuit.py, qiskit/circuit/quantumcircuit.py, releasenotes/notes/circuit-size-depth-filter-function-2177a8a71588f915.yaml, test/python/circuit/test_circuit_properties.py
adding the ability to filter by instructions when inquiring circuit.depth() or circuit.size()
closes #6702
=> filter_function for circuit.depth() and circuit.size()

qiskit/dagcircuit/dagcircuit.py, qiskit/transpiler/passes/utils/remove_final_measurements.py
The RemoveFinalMeasurement was determining which operations were at the
end of a circuit quite inefficiently. It was searching over the entire
DAG to find barrier and measurement instructions and then checking any
that were found if they're children were output nodes. While instead
it'd be much more efficient to chack the parent of each output node for
whether it's a barrier or a measurement. Additionally, the output dag
was being needless rebuilt by modifying the input and then looping over
all nodes in the dag again and copy the node to a new dag. While instead
we can just return the modified input graph. This commit makes those
changes to improve the efficiency of the pass.
Fixes #7038
=> Improve efficiency of RemoveFinalMeasurement transpiler pass

qiskit/dagcircuit/dagcircuit.py, qiskit/transpiler/passes/optimization/optimize_1q_commutation.py, qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py
This PR follows on from #6992 , speeding it up.
In #6992, we conservatively modified one 1Q run, treated the whole lot as invalidated, and re-started from scratch. This caused a lot of re-re-...-re-synthesis of 1Q runs which were analyzed early on, as well as a lot of calls to `collect_1q_runs`. Additionally, we weren't particularly careful about how frequently we converted synthesis output between its circuit and DAG representations, which added substantial overhead. This PR addresses both of these points.
Aside from the pass introduced in #6992, the main place where this PR touches existing code is in `DAGCircuit.substitute_node_with_dag`, which now returns a dictionary mapping the node IDs from the input DAG to the corresponding newly minted nodes in the target DAG. This lets us modify …
=> Speed up `Optimize1qGatesSimpleCommutation`

qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py
The warning strings reported by users in #7041, #7033, and #7042 were made illegible by implicit use of `DAGNodeOp.__str__`. This PR changes the generated warning string to something actually useful for debugging.
I tested this change by hand, by replacing the default values for `simplify=True` and `allow_non_canonical=True` with `False` in `qiskit/quantum_info/synthesis/one_qubit_decompose.py`. It's somewhat cumbersome to test this automatically.
=> improve warning when 1q synthesis emits long strings

azure-pipelines.yml
In the linux py37 CI job ever since #6175 we build an sdist and then
install that in a venv manually in a test /tmp directory we create for
running the tests. However, as part of that we were handling the .stestr
history caching incorrectly. We cache the .stestr directory's times.dbm
files (which contain a record of the most recent run time for each test)
to provide scheduler hints to stest in future runs. But, instead of
updating the .stestr cache with the data from the run we were just
re-populating the data we pulled from the cache. This has also been
somewhat error prone because in some cases the cache isn't downloaded
correctly and will cause an error when we try to remove unnecessary files
from the cache and the .stestr directory doesn't exist, presumably
because azure didn't pull …
=> Fix handling of .stestr caching for linux py37 job

qiskit/test/mock/fake_backend.py
Previously the `system_model` parameter was being passed positionally,
but this was filling in the `validate` parameter in Aer's
`PulseSimulator`, rather than the intended slot.
Fix #7059.
=> Fix calling convention of `PulseSimulator.run`

qiskit/transpiler/coupling.py, releasenotes/notes/add-hexagonal-lattice-couplingmap-d3b65b146b6cd1d1.yaml, test/python/transpiler/test_coupling.py
Adds `qiskit.transpiler.CouplingMap.from_hexagonal_lattice`.
Add `qiskit.transpiler.CouplingMap.from_hexagonal_lattice`, which generates a hexagonal lattice as a coupling map.
=> Add hexagonal lattice CouplingMap

azure-pipelines.yml
Currently, the images are just set to `macOS-latest`, which resolves to
10.15, so this has no immediate change in behaviour.  However, the
GitHub/Azure images will soon be moving `macOS-latest` to 11.x, and
those images do not have built-in Python 3.6 support.  Terra 0.19 will
still support Python 3.6, so we need to maintain a suitable testing
environment for it, and with Terra being (mostly) a Python-only package,
the 11.x/10.15 difference should not be as important as the different
Python versions.
See actions/virtual-environments#4060.
FIx #7073.  I don't imagine we'll make another patch release now after 0.18.3, but it's probably best to be safe an backport this, just in case.
It would in theory be possible to get a Python 3.6 build on macOS 11, but in practice it would require fairly …
=> Pin CI Mac images to 10.15

constraints.txt
This dependency is used transitively by jupyter via nbformat.  In the
new 4.0 release of jsonscheme, nbformat uses deprecated behaviour,
triggering CI failures, so we pin jsonschema to a known-good version.
The pin can be removed once nbformat is updated.
Fix #7090.
See jupyter/nbformat#232 for the tracking issue.
=> Pin jsonschema==3.2.0 in constraints

qiskit/circuit/library/n_local/qaoa_ansatz.py, test/python/circuit/library/test_qaoa_ansatz.py
Improve the performance of `QAOAAnsatz.decompose()` by adding direct access of `QAOAAnsatz.num_qubits`.
The current code accesses the number of qubits `QAOAAnsatz.num_qubits` via `EvolvedOperatorAnsatz.num_qubits`.
It results in `QAOAAnsatz.operators` -> `QAOAAnsatz.mixer_operator` -> computation of mixer terms if `self._mixer` is None. But the mixer_operator is not used for num_qubits. So, we can reduce the overhead of mixer operator.
micro benchmark
```python
from qiskit.circuit.library import QAOAAnsatz
from qiskit.opflow import PauliSumOp
n = 50
lst = []
for i in range(n - 1):
v = ["I"] * n
v[i] = v[i + 1] = "Z"
lst.append(("".join(v), 1))
op = PauliSumOp.from_list(lst)
qaoa = QAOAAnsatz(cost_operator=op, reps=5)
print(f'{timeit(lambda: qaoa.decompose(), …
```
=> Add `QAOAAnsatz.num_qubits` to improve performance

qiskit/synthesis/evolution/product_formula.py, test/python/circuit/library/test_evolution_gate.py
For 1 and 2 qubit evolutions we return the according standard gate (if we have it in the library), so that e.g. the time evolution `exp(it XX)` uses the `RXX` gate. For the `exp(it XZ)` evolution the qubit order in applying the RZX gate is reversed, since the X term should act on qubit 1 and Z on qubit 0. The same happens analogously for `exp(it ZX)`.
This was realized since prior to #6975, the `PauliTrotterEvolution` returned 
```
┌───┐┌───────┐┌───┐┌──────────────┐
q_0: ─────┤ X ├┤ Rz(2) ├┤ X ├┤ circuit-7_dg ├
┌───┐└─┬─┘└───────┘└─┬─┘└────┬───┬─────┘
q_1: ┤ H ├──■─────────────■───────┤ H ├──────
└───┘                        └───┘
```
(where `circuit-7_dg` is empty)
and after that PR was merged it returned 
```
┌───┐┌───┐┌─────────┐┌───┐┌───┐
q_0: ┤ H ├┤ X ├┤ Rz(2.0) ├┤ X ├┤ H ├ …
```
=> Fix wrong qubit order for ``ZX`` evolution in ``PauliEvolutionGate``

qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py, releasenotes/notes/add-sparsepauliop-sum-d55fc817c9fded82.yaml, test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
Adds `SparsePauliOp.sum` as a specialized version the builtin `sum` for a list of `SparsePauliOp`.
The builtin `sum` calls `SparsePauliOp._add` N-1 times if there are N items in the list.
Each `SparsePauliOp._add` stacks arrays of z, x, phase and coeffs and it is carried out N-1 times.
On the other hand, the new method `SparsePauliOp.sum` stacks all arrays at once. So, it can reduce the overhead.
Jordan Wigner transformation takes a sum of a list of `SparsePauliOp` and it is one of the bottlenecks.
I proposed a [workaround](https://github.com/Qiskit/qiskit-nature/blob/cf6511578d39a2ed2a3b6a2db2aff9c194ba72e4/qiskit_nature/mappers/second_quantization/qubit_mapper.py#L146
) to reduce the overhead in this PR https://github.com/Qiskit/qiskit-nature/pull/397;
but, it is not intuitive.
The …
=> Add `SparsePauliOp.sum`

.github/workflows/coverage.yml
This commit adds a concurrency limit for jobs running from a single PR.
This means that on PR updates github actions will cancel any currently
running job for that because they exceed the concurrency limit on the
PR. Without this we end up running duplicate jobs when there are
frequent pushes to an open pull request.
=> Add concurrency limit on github actions coverage job

qiskit/utils/__init__.py, qiskit/utils/deprecation.py, releasenotes/notes/remove-manual-warning-filters-028646b73bb86860.yaml
Previously, qiskit attempted to override the deprecation warning filters
for internal qiskit code as soon as it was imported, so that they were
shown with the default filters.  This isn't something we should be
doing; it's a user's choice, and it's unexpected that we would override
their settings in order to violate the normal Python behaviour.  It also
had no effect on the tests, since test runners hook into the warnings
control at various times during the execution.  If we do want to do
something similar, it would have been better to use
`warnings.filterwarnings`, instead of a private function.
The other change is to remove the "only warn once" filter from
`qiskit.utils.deprecate_function`.  It's the default behaviour of Python
to only show one warning from each `(category, message, …
=> Remove overrides of standard warning behaviour

qiskit/algorithms/minimum_eigen_solvers/qaoa.py, qiskit/circuit/library/evolved_operator_ansatz.py, releasenotes/notes/fix-qaoa-construct-da37faf75f29fc35.yaml, test/python/algorithms/test_qaoa.py, test/python/circuit/library/test_qaoa_ansatz.py
Fixes following two bugs.
1. `QAOAAnsatz` cannot handle identities of `PauliSumOp` and it has a wrong number of parameters. 
2. `QAOA.construct_circuit` does not update circuits if different operators with the same number of qubits are given.
Fixes #7223
I introduced `QAOA._cost_operator` to check whether `operator` is same as `_cost_operator` or not.
If we don't have to decompose `QAOA.ansatz`, we can compare `operator` with `QAOA.ansatz.cost_operator`.
Once #6674 is fixed, we need to revisit it.
https://github.com/Qiskit/qiskit-terra/blob/0a4c666ca09e129768f83f7c95ee7168455d869d/qiskit/algorithms/minimum_eigen_solvers/qaoa.py#L133
=> Fix QAOA handling of ``PauliSumOp`` identities and changing cost operators

qiskit/circuit/library/n_local/n_local.py, releasenotes/notes/fix-nlocal-add_layer-c3cb0b5a49c2b04e.yaml, test/python/circuit/library/test_nlocal.py
Fix `NLocal.add_layer` to append layers correctly when `NLocal._data` is built already
Because `layer.compose` does not have `inplace=True`, `layer` is not modified as expected.
https://github.com/Qiskit/qiskit-terra/blob/02b49e03ef62c8297437cfa907520f1f9c14283c/qiskit/circuit/library/n_local/n_local.py#L782-L784
=> Fix `NLocal.add_layer` to append layers correctly when `NLocal._data` is built already

qiskit/transpiler/passes/routing/algorithms/bip_model.py, qiskit/transpiler/passes/routing/bip_mapping.py, test/python/transpiler/test_bip_mapping.py, tools/find_optional_imports.py
The docplex and cplex optional dependencies which are used for the BIP
mapper routing transpiler pass are quite heavy weight and pull in a lot
of extra libraries to the import tree slowing down the overall import of
qiskit when installed. For example, just importing docplex also imports
pandas, jedi, and ipython. We don't want this overhead for importing
qiskit because docplex and cplex are only used by a small part of qiskit
which is not widely used (and not even available to all users). To avoid
this overhead when docplex and cplex are installed this commit moves the
docplex and cplex imports to be runtime during the execution of the pass
which uses them. This is necessary because the pass gets re-exported to
the root qiskit.transpiler.passes which gets imported as part of the
root …
=> Make docplex and cplex imports for BIP mapper runtime imports

qiskit/opflow/primitive_ops/pauli_sum_op.py, releasenotes/notes/pauli-op-permute-fix-d244a1145093369d.yaml, test/python/opflow/test_pauli_sum_op.py
There is a bug in PauliSumOp with the permute function.
Currently, the following code
```python
from qiskit.opflow import Z, I
op = (I^Z^I) + (Z^Z^I)
op.permute([1, 0, 2])
```
raises the error `QiskitError: 'Pauli string label "" is not valid.'`. This should not happen. This PR introduces a small fix to avoid such errors when the permutation does not introduce identities.
=> Fix permute issue in PauliSumOp

qiskit/circuit/library/standard_gates/x.py, qiskit/qasm/libs/qelib1.inc, releasenotes/notes/fix-c3sxgate-7138e004a2b05ca8.yaml, test/python/circuit/test_controlled_gate.py
The phases used in the decomposition were inverted, so that the gate was
actually equivalent to `SdgXGate().control(3)` rather than the intended
`SXGate().control(3)`.  Note that both gates are valid square roots of
`C3XGate()`, which is likely how this went undetected, but the names and
value of `ControlledGate.base_gate` did not match.
The decomposition of `C4XGate` had a similar negative-phase error, but
the prelude cancelled with the use of the inverse `C3SXGate`, resulting
in a correct gate in the end.  This commit updates `C4XGate` to work
with the new `C3SXGate`.
Fix #7209.
=> Fix decomposition of C3SXGate

qiskit/qasm3/ast.py, qiskit/qasm3/exporter.py, qiskit/qasm3/printer.py, test/python/circuit/test_circuit_qasm3.py
The concatenation `||` operator in OpenQASM 3 is currently supposed to
operate only on arrays, but the exporter had been using it on single
qubits.  This changes the logic so that all the elements of a catenation
are arrays, and attempts to make each run as long as possible.
A new node to represent a `Range` was necessary to achieve this.  This
also meant reorganising the split between `IndexIdentifier`,
`IndexIdentifier2` and the builder-internal `indexIdentifierList`.
These names were originally taken from the OpenQASM 3 reference ANTLR
grammar, but the grammar has changed somewhat since then, and there are
also more descriptive names available.
(Note the internal Terra OpenQASM 3 AST is temporary, and due to be replaced after the 0.19 release.)
Fix #7214
=> Output arrays in QASM 3 alias concatenations

qiskit/compiler/transpiler.py, qiskit/transpiler/passes/synthesis/plugin.py, qiskit/transpiler/passes/synthesis/unitary_synthesis.py, qiskit/transpiler/passmanager_config.py, qiskit/transpiler/preset_passmanagers/level0.py, qiskit/transpiler/preset_passmanagers/level1.py, qiskit/transpiler/preset_passmanagers/level2.py, qiskit/transpiler/preset_passmanagers/level3.py, test/python/transpiler/test_unitary_synthesis_plugin.py
This commit adds a new option to the unitary synthesis plugin interface
for plugins to accept free form user config. Two potential synthesis
plugins both have asked for an interface where a user can pass
configuration options through to the plugin to tune how the plugin runs.
To enable this, this commit adds a new kwarg to transpile() to pass a
configuration dictionary straight through to the plugin. As this is a
custom thing for each plugin the burden is on the plugin author to
define how this dictionary is used, implement using it, and documenting
it's use.
=> Add option to unitary synthesis plugin interface for user config

qiskit/tools/jupyter/backend_overview.py
Leave `avg_cx_err` as the string "NA" if there are no `cx` gates in the map.
Fix #7259.
I didn't write a unit test for it because I'm lazy, we have absolutely no testing infrastructure for testing IPython line magics at the moment, and I didn't want to play around with the mock backends, and mock out the inner calls to return dummy backends with missing `cx` gates and so forth.  We probably should, though...  It's just hard to find the time to do it.
=> Fix ZeroDivisionError in qiskit_backend_overview

test/python/quantum_info/xx_decompose/test_polytopes.py, test/python/quantum_info/xx_decompose/test_weyl.py
In #6551 a few debug prints slipped into the unittests which are dumping
arrays to stdout during unit test runs. This commit just cleans those up
and removes the stray prints.
=> Remove leftover debug prints in unit tests

qiskit/qasm3/printer.py, test/python/circuit/test_circuit_qasm3.py
The QASM3 concatenation operator changed to `++` in Qiskit/openqasm#303.  This brings Terra in line with the change.
No changelog necessary because the exporter hasn't been released yet.
=> Change concatenation operator to match QASM spec

qiskit/opflow/primitive_ops/tapered_pauli_sum_op.py, releasenotes/notes/taper_empty_operator_fix-53ce20e5d2b68fd6.yaml, test/python/opflow/test_z2_symmetries.py
Tapering logic would detect an empty/zero operator, log a warning and return the original operator unchanged. When running code with symmetry reduction in Qiskit Nature this ended up failing in VQE if one or more of the auxilary operators was zero. The set that ended up getting passed in would tapered non-zero operators and any zero operators were the originals which now were bigger, in terms of num_qubits, that the tapered operators. Given the number of qubits mismatched VQE raised an error.
This alters the code to so that a zero operator of the correct tapered size is returned from taper and not the original as before.
=> Fix tapering of zero/empty operators

qiskit/result/postprocess.py
Required for https://github.com/Qiskit/qiskit-aer/pull/1388
Fixes an issue with how the `Result` class handles post-processing for the functions `get_statevector` and `get_unitary` if the result data is already a Statevector or Operator object.
This is needed for planned feature for the next Aer release to automatically format the result data for save instructions to the corresponding terra classes (Statevector, DensityMatrix, Operator, SuperOp, Clifford, ProbDistribution).
~Because of all the unexpected cyclic dependencies already in terra I couldn't import the Statevector or Operator classes for type checking in the `postprocessing` or `result` module, so had to do a duck-type check based on the class name instead.~
=> Fix Result post-processing

qiskit/circuit/library/standard_gates/equivalence_library.py
an example that can be a use case for backendV2 and its compiler support.
ccx can be written as 2 cx and 3 csx (which is better than only if cx was available)
cx and csx can also be written as rzx(pi/2) and rzx(pi/4) respectively.
so in principle the basis translator should be able to rewrite ccx in terms of rzx(pi/2) and rzx(pi/4) if that's the instruction set that the backend has.
=> equivalence of toffoli in terms of cx and sqrt(cx)

qiskit/compiler/transpiler.py, releasenotes/notes/fix-transpile-empty-list-c93a41d4145a01c3.yaml, test/python/compiler/test_transpiler.py
Previously `transpile([])` raised a warning.  Now we just return quickly without further tests, similarly to how we return early if we're asked to transpile a list of `Schedule`s.
Fix #7287.
=> Return fast from transpile with empty input

qiskit/circuit/library/n_local/qaoa_ansatz.py
Improve performance of `QAOAAnsatz` by initializing mixer terms directly with `PauliSumOp.from_list`
```python
from qiskit.circuit.library import QAOAAnsatz
from qiskit.opflow import PauliSumOp
n = 50
lst = []
for i in range(n - 1):
v = ["I"] * n
v[i] = v[i + 1] = "Z"
lst.append(("".join(v), 1))
op = PauliSumOp.from_list(lst)
qaoa = QAOAAnsatz(cost_operator=op, reps=5)
print(f'{timeit(lambda: qaoa.assign_parameters([0] * qaoa.num_parameters), number=1)} sec')
```
main
```
4.2214362309998705 sec
```
this PR (13% improvement)
```
3.6385711119999087 sec
```
=> Initialize mixer terms of `QAOAAnsatz` with `PauliSumOp.from_list` (performance improvement)

qiskit/transpiler/passes/layout/vf2_layout.py, test/python/transpiler/test_vf2_layout.py
This commit fixes some issues with the initial implementation of the
VF2Layout pass and improves the pass to make it suitable for use in the
preset pass managers. This includes several changes:
1. The vf2 pass was raising an exception if it was
run with >2 qubit gates. This caused issues if we run with
calibrations (or backends that support >2q gates) as vf2 layout is
used as an opportunistic thing and if there is for example a 5q gate
being used we shouldn't fail the entire transpile just because vf2
can't deal with it. It's only an issue if the later passes can't
either, it just means vf2 won't be able to find a perfect layout.
2. Add multiple trials to the pass and a mapping quality heuristic with
basic noise awareness to the pass. For performance we should be using
the vf2++ heuristic …
=> Improve VF2Layout pass

test/python/transpiler/aqc/test_aqc_plugin.py
On rare occasions the `TestAQCSynthesisPlugin.test_with_pass_manager` may fail due to unlucky randomization of the initial parameters and the algorithm does not converge with the default number of iterations. This PR aims to fix randomization in the AQC plugin unit tests and make them fully reproducible.
In the CI an error like this may be seen:
```
File "D:\a\1\s\test\python\transpiler\aqc\test_aqc_plugin.py", line 100, in test_with_pass_manager
np.testing.assert_array_almost_equal(np.eye(8), approx_unitary, 3)
File "D:\a\1\s\test-job\lib\site-packages\numpy\testing\_private\utils.py", line 1046, in assert_array_almost_equal
assert_array_compare(compare, x, y, err_msg=err_msg, verbose=verbose,
File "D:\a\1\s\test-job\lib\site-packages\numpy\testing\_private\utils.py", line 844, in …
```
=> Fix randomization in AQC plugin unit tests

qiskit/transpiler/synthesis/aqc/aqc_plugin.py
This commit tweaks the imports for the aqc plugin to make the optimizer
and other aqc method imports occur at run time only. Previously these
were done at the module level, which is normally best practice for many
reasons, but in this specific case doing plugin discovery causes the
module to be loaded (and the plugin class instaniated) even if the
plugin is not specified by the user. The imports for aqc are fairly
heavy as both the algorithms tree and scipy can be slow to load. To
avoid the overhead on discovery these imports are moved to runtime so we
only load them if the aqc plugin is used and these imports are needed.
=> Adjust imports in aqc plugin to avoid discovery overhead

qiskit/transpiler/passes/calibration/builders.py, qiskit/transpiler/passes/optimization/echo_rzx_weyl_decomposition.py, releasenotes/notes/deprecate-backend-rzx-cal-build-8eda1526725d7e7d.yaml, test/python/pulse/test_calibrationbuilder.py, test/python/transpiler/test_echo_rzx_weyl_decomposition.py
The RZXCalibrationBuilder and EchoRZXWeylDecomposition transpiler passes
were previously taking BaseBackend instances as arguments. Besides that
being a deprecated class which will be removed soon, it also is
incorrect because backend objects are not guaranteed to be pickleable so
when a pass manager runs in parallel processes this will cause an error.
This was never caught because these passes aren't part of any default
pass managers and their tests don't include running them as part of
transpile().
To fix this passes typically take the properties of a backend they
require. This is being reworked for BackendV2 in #5885 so a target
object can be used to encapsulate the model of a backend so we have a
single data structure to pass around, but until that is the minimum
backend version we …
=> Fix arguments for RZXCalibrationBuilder and EchoRZXWeylDecomposition

qiskit/providers/__init__.py
As a follow-on to #5885 this commit updates the top level
qiskit.providers module documentation for ``BackendV2``. This primarily
consists of two things, updating the writing a provider section to use
``BackendV2`` instead of ``BackendV1`` and adding a migration section on user
facing changes between ``BackendV1`` and ``BackendV2``.
=> Update top level provider documentation for BackendV2

qiskit/qasm3/exporter.py, releasenotes/notes/qasm3-limitations-ebfdedab3f4ab6e1.yaml, test/python/circuit/test_circuit_qasm3.py
There were previously parts of the QASM 3 exporter where it attempted to
do its best guess at what should happen, even when this always produced
entirely incorrect results.  These were subroutine definitions with
parameters, opaque gates (`defcal`) and non-included gates with
parameters.
We now choose to fail loudly with a message that we do not currently
support certain features, rather than outputting a meaningless
programme.  For the parameterised gates, we now force the exporter to
output a separate definition for every instance of a gate if it cannot
be sure that it has the most general form to start with.  The code it
outputs looks silly (the gates take parameters, but do not use them in
their definitions, and each gate may be defined many times), but the
semantics of the programme …
=> Fail safe in the QASM 3 exporter

qiskit/opflow/converters/circuit_sampler.py
#7217 calls transpilation two times: 1) transpile of parameterized circuits and 2) transpile of bound circuits.
Unless users define their pass for the second pass, we don't need to call the transpile again.
Fixes #7337 
```
from qiskit import Aer
from qiskit.algorithms import VQE
from qiskit.algorithms.optimizers import COBYLA
from qiskit.circuit.library import RealAmplitudes
from qiskit.opflow import PauliSumOp
from qiskit.utils import QuantumInstance
quantum_instance = QuantumInstance(backend=Aer.get_backend('aer_simulator'), shots=1)
vqe = VQE(ansatz=RealAmplitudes(), optimizer=COBYLA(maxiter=1), quantum_instance=quantum_instance)
op = PauliSumOp.from_list([("ZZ"*5, 1), ("IX"*5, 2)])
print(f'{timeit(lambda: vqe.compute_minimum_eigenvalue(op), number=10)} sec') …
```
=> Fix performance regression of VQE by #7217

qiskit/transpiler/passmanager.py
Calling `pm.run(circuits)` with an empty pass manager is slow since it uses parallel map and does dag-circuit conversions which aren't necessary if there are no passes to run. This changes the pass manager to return the input circuits for these cases.
Here is a trivial case showing the slow performance
```python
from qiskit.transpiler import PassManager
pm = PassManager()
circuits = [QuantumCircuit(2) for _ in range(100)]
%timeit pm.run(circuits)
```
Before change
```
69.5 ms ± 2.13 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)
```
After this change:
```
164 ns ± 3.58 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)
```
=> Speed up passmanager if it is empty

qiskit/providers/options.py, test/python/providers/test_options.py
This is an awful hack to support various SimpleNamespace-like operations
that qiskit-experiments are using.  We need to transition downstream
packages to the new Options API, but in the meantime, this makes the
Options class behave as much like a SimpleNamespace as it can, while
still keeping the new instance attributes and methods.
This passes the `qiskit-experiments` tests on my machine.  The real problem is how `qiskit-experiments` accesses `options.__dict__`, so this involves some terrible behaviour to make that work as expected.
It's an absolutely horrific hack, and I regret ever learning Python.
@eggerdj - this passes the tests on my machine, but could you check it does everything you need as well?
=> Hack in SimpleNamespace-like functionality to Options

qiskit/providers/options.py, releasenotes/notes/add-backend-v2-ce84c976fb13b038.yaml, test/python/providers/test_options.py
Adds copy method to the `Option` class.
The option refactor changes the behaviour of `copy.copy(opts)` compared to the original class so that changing option values of the copy also change the original.
This adds a `copy` method for returning a shallow copy of option values where changes of the copy do not change the values of the original.
This copy functionality is used in qiskit-experiments.
=> Add copy method to Options

qiskit/converters/circuit_to_gate.py, qiskit/converters/circuit_to_instruction.py, releasenotes/notes/0.19/fix-circuit-conversion-loose-qubits-8d190426e4e892f1.yaml, test/python/converters/test_circuit_to_gate.py, test/python/converters/test_circuit_to_instruction.py
Previously, `circuit_to_instruction` and `circuit_to_gate` were finding
the number of bits in a circuit by summing the sizes of the registers.
This failed if any bits were not in a register, or in more than one
register.  Instead, we can simply ask the input circuit how many bits it
contains.
Fix #7364.
Ideally, Aer 0.10 needs this. @hhorii.
=> Fix circuit instruction conversion with loose bits

qiskit/circuit/controlflow/builder.py, releasenotes/notes/0.19/fix-control-flow-builder-parameter-copy-b1f6efcc6bc283e7.yaml, test/python/circuit/test_control_flow_builders.py
There are a few places where the structure of an element of
`QuantumCircuit.data` is specifically assumed to be
Tuple[Instruction, List[Qubit], List[Clbit]]
rather than the more abstract
Tuple[Instruction, Sequence[Qubit], Sequence[Clbit]]
For performance reasons, the control-flow builders used tuples to store
their arguments internally, because this prevents any copying being
necessary, and allows the arguments to be put in sets.  Now, in lieu of
changing the `QuantumCircuit` data structure to be more abstract, which
would have performance implications, or to require the tuples, which may
create more bugs, we just make the builder interface convert its tuples
to lists on output.
A relatively hidden bug, but a bug nonetheless, and fixing this will make it much easier for Aer to write its …
=> Fix copying control-flow bodies in builder interface

qiskit/circuit/controlflow/for_loop.py, qiskit/circuit/quantumcircuit.py
Some docstring have examples on how to use `c_if` without a `val` parameter, which is required.
=> documentation update: c_if needs val

qiskit/circuit/measure.py, qiskit/circuit/reset.py, releasenotes/notes/reinstate-deprecate-loose-measure-reset-11591e35d350aaeb.yaml, test/python/circuit/test_circuit_operations.py
Previously, the `QuantumCircuit` methods `.measure` and `.reset` were
defined as regular functions in `circuit/measure.py` (m.m. `reset`) and
monkey-patched onto `QuantumCircuit`.  Commit 2cd42b493 removed the
monkey-patching by defining them as regular methods, but did not
implement a deprecation period for the functions.  This reinstates them,
with the deprecation warning.
Fix #7370.  This came up on `pennylane_qiskit`: see PennyLaneAI/pennylane-qiskit#164.
=> Reinstate and deprecate loose measure and reset functions

qiskit/transpiler/passes/optimization/inverse_cancellation.py, test/python/transpiler/test_inverse_cancellation.py
As reported in GH-7378, the InverseCancellation optimization pass
previously assumed that inverse gate pairs would always share a
common name, but this is not universally true. This commit updates
the pass to search for runs containing any of the gate names in the
gates_to_cancel list, instead of only the first.
Co-authored-by: Bruno Schmitt <bruno.schmitt@epfl.ch>
=> Fix InverseCancellation pass to handle gates of different names.

qiskit/circuit/qpy_serialization.py, releasenotes/notes/fix-paramater-vector-qpy-52b16ccefecf8b2e.yaml, test/python/circuit/test_circuit_load_from_qpy.py, test/qpy_compat/test_qpy.py
This adds special handling for `ParameterVectorElement` instances within
circuits on serialisation to QPY.  These needed to be recreated into
the correct class (as opposed to a raw `Parameter`) so that their sort
order in `QuantumCircuit.parameters` would remain the same after a QPY
round trip.  Without special handling, once there were 10 or more
elements in the vector, the naming (suffixed numbers with no leading
zeros) would cause the sort order to be wrong.
- Fix #7372
On hold til after #7374, because this modifies version 3 of QPY:
=> Fix ParameterVector handling in QPY serialization

qiskit/circuit/controlflow/break_loop.py, qiskit/circuit/controlflow/builder.py, qiskit/circuit/controlflow/condition.py, qiskit/circuit/controlflow/continue_loop.py, qiskit/circuit/controlflow/for_loop.py, qiskit/circuit/controlflow/if_else.py, qiskit/circuit/controlflow/while_loop.py, qiskit/circuit/quantumcircuit.py, releasenotes/notes/fix-circuit-builder-registers-21deba9a43356fb5.yaml, test/python/circuit/test_control_flow_builders.py
Previously, the only resources tracked by the builder interface were the
"wires" used in the DAG representation of the circuit.  This meant that
registers in conditions were not added to the circuit bodies of the
blocks that contained them.  This did not raise any exception at the
time of circuit creation, but would subsequently crash later routines
such as conversions to the DAG, because the registers would not exist.
This commit also adds warnings to all the builder-interface internal
objects, noting that they should not be used by the public.  This should
have been in the original release.
Fix #7379.  @hhorii.
_Technically_ this isn't entirely stable, but it only changes interfaces that _shouldn't_ have been public.  The PR adds documentation notes to all the unstable objects noting …
=> Fix register conditions in control-flow builders

qiskit/converters/circuit_to_instruction.py, releasenotes/notes/fix-circuit_to_instruction_single-bit-condition-db75291ce921001a.yaml, test/python/converters/test_circuit_to_instruction.py
This version of the change is stable for backports, but a more thorough
refactor of `circuit_to_instruction` is in order to support multiple
registers, overlapping registers and remove the creation of unnecessary
registers.
This is the minimal change needed to fix #7394.  There's unnecessary registers being created in `circuit_to_instruction`, in a manner that is limiting its ability to handle conditions on registers not containing _all_ the clbits in the instruction, but this is part of a larger issue (see #5529 and #6496, for example).
I've tagged this for 0.19.2, because I want to consider 0.19.1 closed now pending release.
=> Fix registerless bit conditions in circuit_to_instruction

.github/workflows/randomized_tests.yml, azure-pipelines.yml, tox.ini
The recent release of Aer 0.10 has major performance regressions, and
appears to be causing Terra's CI to fail with timeouts on Mac and Linux.
@chriseclectic, @hhorii I guess we've got more impetus to get a new patch release fixing this now.
=> Pin Aer to 0.9.1 in CI

qiskit/quantum_info/operators/symplectic/pauli_list.py
I believe this is what was intended when the example was originally added (#5993), as this now matches the method signature, and the `phase` on the previous line is no longer an unused variable.
=> Pass `phase` in `PauliList.from_symplectic` example

.mailmap
This will help ensure that my name appears in `Qiskit.bib` in only one form, the one I use for academic publications.
I've included my personal email address here, too, as both #7435 and #7436 were changed to that address when they were squashed & merged.  It seems that using an account's primary email address when squashing [is intended behavior](https://github.community/t/github-squash-and-merge-how-is-the-author-email-determined/156376) by GitHub, even though it seems to not *always* be changed (e.g., when https://github.com/Qiskit/qiskit-optimization/pull/296 was merged).
=> Update garrison's name in .mailmap

qiskit/test/base.py, requirements-dev.txt, test/python/circuit/test_gate_definitions.py
The recent setuptools releases, since 59.6.0 according to the release
notes: https://setuptools.pypa.io/en/latest/history.html#v59-6-0, have
been emitting a deprecation warning about the use of Version classes
from distutils. The seaborn project is still using these in the current
releases which is causing the project to emit these deprecation
warnings. Since the test suite enforces we don't emit deprecation
warnings this is causing test failures when running with newer
setuptools. The deprecated usage has already been fixed upstream in
seaborn but it hasn't been released. To fix test runs and CI while
waiting for a seaborn release this commit adds the distutils version
class deprecation message to the warning ignore list. We should remove
this once seaborn releases.
Fixes #7457
=> Add distutils warning ignore from seaborn

qiskit/circuit/library/n_local/excitation_preserving.py
Fix the matrix of the two-qubit interaction the ``qiskit.circuit.library.ExcitationPreserving`` circuit is using.
The middle 2x2 block should have `-i sin(theta / 2)` on the antidiagonal instead of what the documentation currently states. This can also be seen if the circuit is instantiated:
```python
>>> from qiskit.circuit.library import ExcitationPreserving
>>> circuit = ExcitationPreserving(2, reps=1)
>>> circuit.decompose().draw()
┌──────────┐┌────────────┐┌────────────┐┌──────────┐
q_0: ┤ Rz(θ[0]) ├┤0           ├┤0           ├┤ Rz(θ[3]) ├
├──────────┤│  Rxx(θ[2]) ││  Ryy(θ[2]) │├──────────┤
q_1: ┤ Rz(θ[1]) ├┤1           ├┤1           ├┤ Rz(θ[4]) ├
└──────────┘└────────────┘└────────────┘└──────────┘
>>> bound = circuit.bind_parameters([0, 0, np.pi / 4, 0, 0])
>>> Operator(bound) …
```
=> Fix matrix representation of ``ExcitationPreserving`` circuit

qiskit/circuit/__init__.py, qiskit/circuit/library/__init__.py, requirements-dev.txt
Sphinx 4 is more particular about disallowing the same Python object to
be documented in multiple toctree entries.  The culprits were `Barrier`,
`Reset` and `Measure` in the circuit library; the library re-exports
them from their canonical locations, and used `autosummary` to generate
extra links to them.  We still re-export them, but change the
`autosummary` tables to link to the existing definitions.
This then builds the documentation without errors on Sphinx 4, and
consequently the pin on `sphinx-panels` can be removed.  Previously the
pin was applied because an update to that package caused the
documentation build to break; in reality, it's just that
`sphinx-panels<0.6` pinned itself to `Sphinx<4`, whereas version 0.6
allowed Sphinx 4 - there were no breaking changes for us.
This …
=> Fix documentation for Sphinx 4

qiskit/algorithms/optimizers/p_bfgs.py
Comparing the string `platform.get_version_tuple()[1] >= "8"` fails once
the minor version has two digits.
No changelog because Python 3.10 support hasn't been released yet.
=> Fix bad version test in P_BFGS

qiskit/circuit/quantumcircuit.py
Changed the documentation from "Apply RYGate" to "Apply RZGate" for QuantumCircuit.rz() in the Qiskit documentation.
=> Fixed Issue #7511

qiskit/visualization/bloch.py, releasenotes/notes/fix-path2d-mpl3.4-b1af3a23b408d30a.yaml
In Matplotlib 3.4, the paths for cropping the figure down to its bounding box attempted to access `Arrow3D._path3d` without it being set.  This just ensures it is set as soon as the patch is drawn onto a figure.
Fix #7488
=> Fix Bloch sphere with Matplotlib 3.3 and 3.4

.github/CODEOWNERS
Ikko has been doing great work maintaining the opflow and quantum_info
code bases. The optimization and improvements he's made there have
greatly improved performance and he has shown an understanding and
respect for the code contribution guidelines and review process.
This commit adds him as a codeowner of those submodules which gives him
merge permission on PRs that touch either submodule and a formal
responsibility to review and maintain both submodules.
=> Add ikkoham as code owner for quantum_info and opflow

.github/workflows/wheels.yml, pyproject.toml, releasenotes/notes/ibm-cpu-arch-support-3289377f3834f29e.yaml
This commit adds a new CI job at release time to build precompiled
binaries for s390x and ppc64le linux platforms.  These platforms do not
have precompiled wheels for any upstream dependencies (except for
retworkx and tweedledum, which both publish binaries for both platforms).
Since the only publically available CI service that has native s390x and
ppc64le environments available is travis which doesn't provide
sufficient quota to open source projects anymore to make it usable we
have to rely on either cross compilation or emulation. Cross compiling
with python wheels while possible is quite tricky to setup and configure
in practice so emulation is used here. This is a much simpler path
configure, especially because cibuildwheel has support for emulating
non-x86 architectures via QEMU to …
=> Add cross-build wheel jobs for ppc64le and s390x

pyproject.toml, releasenotes/notes/py310-support-869d47583c976eef.yaml
In #7102 we added support for Python 3.10 to Qiskit. However, numpy and
scipy stopped publishing wheels for 32bit platforms in Python 3.10. This
means that to test Python 3.10 32bit wheels we will have to compile
numpy and scipy from source (which for scipy is prohibitively slow).
In response this commit updates our cibuildwheel configuration to skip
tests on 32bit Python 3.10 wheels since we can't reliably test the built
wheels in CI and it would require users to build them from source.
This is the same approach taken in PR #7549 for ppc64le and s390x. For
32 bit platform users on python 3.10 this means they'll need to locally
build numpy, scipy, and potentially other depencies from source to use
Qiskit Terra with Python 3.10, but for the Qiskit components at least
precompiled binaries …
=> Drop support for 32bit py310 wheel builds

qiskit/assembler/assemble_schedules.py, qiskit/pulse/schedule.py
In type hints, strings are converted to `typing.ForwardRef` instances,
which only attempt to evaluate to a true reference when the are the
subject of a `typing.get_type_hints` call, which defines the scoped
names they can resolve over.  Further, the instances store their
resolved value, so they only need to be evaluated once.  Together, this
means that the evaluation order of type hints can change the result of a
program, if a `ForwardRef` is imported into a different scope.
In Terra, this happened within a type alias in the `pulse` module.  The
fix in this case is to ensure that the type aliases were concrete types
(by putting them after the definition of the classes they aliased over),
and references to the aliases _within the same file_ were done by
forward reference.
Fix #7534.
=> Fix imported forward references in type hints

qiskit/compiler/transpiler.py, qiskit/transpiler/target.py, releasenotes/notes/fix-non-global-operation-name-ideal-sim-3dcbc97e29c707c7.yaml, test/python/compiler/test_transpiler.py, test/python/transpiler/test_target.py
This commit fixes an issue in the Target
get_non_global_operation_names() method. Previously this method would
crash when you had a target with it's instruction properties set to
None (which is typically used for an ideal simulator).
=> Fix error in Target non-global operation method with ideal gates

azure-pipelines.yml
This commit tweaks the apt usage in the Ubuntu CI job configuration.
Previously the Ubuntu CI jobs were using 'apt' which emits a warning
about having an unstable CLI. This commit switches to use apt-get
to avoid the warning and calls apt-get update prior to the installation
step to ensure we've synced with the mirror prior to installing.
=> Tweak apt usage in Ubuntu CI job configuration

qiskit/circuit/library/basis_change/qft.py, releasenotes/notes/warn-on-too-large-qft-a2dd60d4a374751a.yaml, test/python/circuit/library/test_qft.py
Previously, the rotation angles were calculated by dividing `pi` by
increasingly large numbers for large qubit counts.  This meant that the
intermediate result could overflow to infinity for large circuits,
raising an ``OverflowError``.  Instead, we do the calculation as a
multiplication with a very small number, so the intermediate values
safely underflow to zero in this case (if the intermediate value
underflows, the final value would have had precision loss anyway).
To make sure the user is aware, we raise warnings when this will happen.
Fix #7538.
I think there's probably some speed-ups to be had in various methods called by `QFT.build` here; it takes much longer to build the circuit than I'd expect.  Probably there's some extraneous copying and binding that we can reduce.
=> Warn not error on overflow in QFT

azure-pipelines.yml, pyproject.toml, releasenotes/notes/manylinux2014-e33268fda54e12b1.yaml
Numpy and Scipy are moving to drop manylinux2010 wheels on newer
platforms, which gives us some cover to do the same.  To test, we need
to ensure that we pull Numpy and Scipy in binary form only (forcing pip
to install slightly older versions like 1.21 instead of 1.22 on
unsupported Python versions), rather than attempting to build Numpy from
source as part of our testing process.
We are going to deploy 0.19.2 with manylinux2014 for Python 3.10, since we don't have any prior commitments in the 0.19 series for Python 3.10, but we left raising the VM on other Pythons until the next minor.  Given that we really don't use much of the C API, there won't be any huge improvement from upping the VM, but it'll be easier for us to keep pace with Numpy and Scipy going forwards.
=> Use manylinux2014 on all Linux builds

qiskit/dagcircuit/dagnode.py, releasenotes/notes/add-repr-for-dag-nodes-2d0a95fecd3dd3db.yaml, test/python/dagcircuit/test_dagcircuit.py
A `__repr__` method is added for the `DAGOpNode` class for better representation of op nodes in qiskit
- The original issue required a `__repr__` method for the `DAGNode` but since its attributes are going to be deprecated in later versions of qiskit, it is added to the `DAGOpNode`, `DAGInNode` and `DAGOutNode` classes which inherit from `DAGNode`
- Representations are - 
```
DAGOpNode(op = [Operation] , qargs = [List of qargs], cargs = [List of cargs])
DAGInNode(wire = [wire of node])
DAGOutNode(wire = [wire of node])
```
- A unit test is added for the same
Fix #7165
=> Add `__repr__` to DAG nodes

qiskit/circuit/quantumcircuit.py
**Summary**
There was a spelling mistake in a comment at line 262 of qiskit.circuit.quantumcircuit.py
**Details and comments**
I replaced "Qubt" with "Qubit" at line 262 of a #comment
=> Fix typo at line 262 of qiskit.circuit.quantumcircuit.py in a #comment

qiskit/circuit/library/pauli_evolution.py, test/python/circuit/library/test_evolution_gate.py
The backported commit 6b6df5a added some additional error raising to
`PauliEvolutionGate`, which while physically correct is not stable due
to the new error.  This broke qiskit-nature downstream, and cannot be
released in a patch cycle.
Supersedes #7594 in terms of fixing the regression.
=> Do not error on complex coefficients in PauliEvolutionGate

qiskit/qasm3/exporter.py
Fixes #7611
fixes f-sting where `f` was missing at the start of the string
```diff
-                " exporter. Received this instruction, which appears parameterized:\n{instruction}"
+                " exporter. Received this instruction, which appears parameterized:"
+                f"\n{instruction}"
```
Separated `f"\n{instruction}"` from `" exporter. Received this instruction, which appears parameterized:"` to keep it consistent with https://github.com/Qiskit/qiskit-terra/blob/74014e6adbeb9e4e794403bcec6dd221c2045371/qiskit/qasm3/exporter.py#L455-L457
=> Fix broken f-string in qasm3 exporter error message

qiskit/quantum_info/operators/operator.py, releasenotes/notes/Operator-from_circuit-25b20d4b3ad5c398.yaml, test/python/quantum_info/operators/test_operator.py
This commit adds a new constructor method .from_circuit() to the
Operator class. This allows users to construct Operator objects from
QuantumCircuits and have additional features than the default __init__
constructor allows. To start this just involves permuting the qubit
order based on the specified layout. The permutation based on layout has
come before, especially in testing with transpilation (see #7213 for
where equivalent functionality was done inline in the unittests).
Exposing this as an api will provide a single place to build an Operator
with a layout. It also will provide us a dedicated location if we need
to offer additional options to the construction of Operators from
circuits.
=> Add Operator.from_circuit constructor method

.github/CODEOWNERS
This explicitly overrides the release notes directory to have no code
owner, so anybody with write access can give an approving review to
changes within, without GitHub requesting review from everyone.
@mtreinish and I tried this on a separate repository, and it seemed to do the right thing, as best I could tell.
=> Allow anybody to approve release notes

qiskit/dagcircuit/dagcircuit.py, releasenotes/notes/bump-retworkx-0.11.0-97db170ae39cacf8.yaml, requirements.txt, test/python/dagcircuit/test_dagcircuit.py
Replaces the bulk of the implementation of `DAGCircuit.replace_block_with_op` with the generic retworkx method `PyDiGraph.contract_nodes`, added in https://github.com/Qiskit/retworkx/pull/487.
At a minimum, this change rids Terra of graph manipulation code that is more widely applicable in a generic graph library. For our current use cases (the `ConsolidateBlocks` pass) this change might improve performance slightly, but the primary speedup would be observed by `replace_block_with_op` callers that pass `cycle_check=True`, since retworkx's `contract_nodes` performs this check prior to modifying the DAG, and without making a backup copy.
Resolves #7418
=> Use `contract_nodes` from retworkx in `DAGCircuit`.

qiskit/compiler/transpiler.py, releasenotes/notes/remove-deprecated-pass-manager-dc1dddbd7dcd866f.yaml, test/python/compiler/test_transpiler.py
Removes the `pass_manager` kwarg to `qiskit.compiler.transpile` per @jakelishman's suggestion on issue #7663.
- The change to transpiler.py is only deletions. I removed 2 unused functions: `_check_conflicting_argument` and `_parse_pass_manager`.
- One test just needed the `pass_manager` kwarg removed.
- Reno release note added that mostly copies the [0.13 deprecation note](https://github.com/Qiskit/qiskit-terra/blob/83ac6d738641a7e00b389dbe845abe9d8492f806/releasenotes/notes/0.13/passmanager_parameter_in_transpile-9768d95afbe9127e.yaml).
Please don't hesitate to let me know if there's more I can do.
=> Remove deprecated pass_manager arg to transpile()

qiskit/circuit/classicalregister.py, qiskit/circuit/quantumregister.py, releasenotes/notes/bit-slots-17d6649872da0440.yaml
Response to #7704, namely adding `__slots__` fields for the `Bit` subclasses `Clbit`, `Qubit` and `AncillaQubit`.
According to [the official Python 3 docs](https://docs.python.org/3/reference/datamodel.html);
"The action of a `__slots__` declaration is not limited to the class where it is defined. `__slots__` declared in parents are available in child classes. However, child subclasses will get a [`__dict__`](https://docs.python.org/3/library/stdtypes.html#object.__dict__) and `__weakref__` unless they also define `__slots__` (which should only contain names of any additional slots)."
This PR adds `__slots__` for the `Bit` subclasses, effectively denying the creation of a `__dict__` for those instances.
=> Add `__slots__` for `Bit` subclasses

Cargo.lock, Cargo.toml, src/lib.rs
The PyO3 and rust-numpy projects recently released version 0.16.0. This
commit bumps the version we use for qiskit-terra to use these new
releases. The details on these releases can be found here:
https://pyo3.rs/v0.16.0/changelog.html
and
https://github.com/PyO3/rust-numpy/blob/main/CHANGELOG.md
=> Bump PyO3 and rust-numpy versions to the latest release

.github/CODEOWNERS
This commit adds @nkanazawa1989 as a listed code owner for the qpy
module. @nkanazawa1989 introduced the standalone qpy in #7852 which
made the qpy code far more understandable and maintainable. He has
shown good understanding of both file format and terra code using the
format. This commit gives @nkanazawa1989 merge permission on PRs that
touch QPY code and a formal responsibility to review and maintain the
submodule.
=> Add @nkanazawa1989 as CODEOWNER for qpy module

qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
Improves the performance of `SparsePauliOp.compose` by replacing `np.kron` with a specialized operation for 1d arrays.
This PR replaces `np.kron` of 1d arrays with a faster alternative.
`np.kron` seems slow due to `concatenate` inside.
```python
import random
from qiskit.quantum_info import SparsePauliOp
def bench(k, n):
random.seed(123)
op = SparsePauliOp.from_list([(''.join(random.choices('IXYZ', k=k)), 1) for _ in range(n)])
op2 = SparsePauliOp.from_list([(''.join(random.choices('IXYZ', k=k)), 1) for _ in range(2)])
print(f'{k}, {n}: {timeit(lambda: op.compose(op2), number=1000)} sec')
bench(20, 2000)
```
cProfile call graph
main
```
20, 2000: 1.7031413420008903 sec
```
this PR
```
20, 2000: 0.73382812699856 sec
```
This PR has an impact on qubit converter of …
=> Performance improvement of `SparsePauliOp.compose`

Cargo.lock, Cargo.toml
Hashbrown 0.12.0 bumped the MSRV (minimum support rust version) to
1.56.1 which was released on November 2021. This is causing some issues
for people building locally as that is a pretty new version of rust.
While we don't set an MSRV for terra, I think we should try to at least
support that past ~6 months of Rust releases for building just to give
people time to upgrade and not require everyone to use rustup.
As there was nothing critical in hashbrown 0.12.0 this commit just
reverts back to 0.11.2 for now. We can look at bumping that after the
0.20.0 release.
This reverts commit d05931dbfac77abb0c21955b52d8ea19d5d051a3.
=> Revert "Bump hashbrown from 0.11.2 to 0.12.0 (#7730)"

pyproject.toml, requirements-dev.txt
This follows up on #7702, which removed the last of the Cython code. The current change was was presumably intended to be part of that PR, I think, based on the release note added there:
> Cython is no longer a build dependency of Qiskit Terra and is no longer required to be installed when building Qiskit Terra from source.
@mtreinish
=> Remove Cython as a build dependency

qiskit/transpiler/passes/optimization/consolidate_blocks.py, qiskit/transpiler/preset_passmanagers/level0.py, qiskit/transpiler/preset_passmanagers/level1.py, qiskit/transpiler/preset_passmanagers/level2.py, qiskit/transpiler/preset_passmanagers/level3.py, qiskit/transpiler/target.py, releasenotes/notes/consolidate-blocks-target-aware-6482e65d6ee2d18c.yaml, test/python/transpiler/test_consolidate_blocks.py, test/python/transpiler/test_target.py
This commit updates the consolidate blocks pass target aware so that at
its instantiation a Target object can be specified to define the target
device for compilation. When specified this target will be used for
all device aware operations in the pass. When a target is specified the
consolidate blocks pass will only consolidate blocks with instructions
outside the target (both operation and qubits).
Part of #7113
TODO:
=> Make ConsolidateBlocks transpiler pass target aware

qiskit/transpiler/passes/layout/dense_layout.py, qiskit/transpiler/preset_passmanagers/level0.py, qiskit/transpiler/preset_passmanagers/level1.py, qiskit/transpiler/preset_passmanagers/level2.py, qiskit/transpiler/preset_passmanagers/level3.py, qiskit/transpiler/target.py, releasenotes/notes/dense-layout-target-aware-2b330ccee948d31a.yaml, test/python/transpiler/test_dense_layout.py, test/python/transpiler/test_target.py
This commit updates the dense layout pass target aware so that at
its instantiation a Target object can be specified to define the target
device for compilation. When specified this target will be used for
all device aware operations in the pass. When a target is specified the
error matrix used is the average of all 1q and 2q operations while
before the matrix was composed of just cx and readout error rates.
Part of #7113
=> Make DenseLayout transpiler pass target aware

qiskit/transpiler/preset_passmanagers/level1.py, qiskit/transpiler/preset_passmanagers/level2.py, qiskit/transpiler/preset_passmanagers/level3.py
The previous check would always run the body of the optimisation loop
once after the fixed point had been achieved.  As well as being
unnecessary, this also made it possible in theory for the optimisation
loop to "unfix" the point, although hopefully our optimisations on that
front would never increase the number of operations.
Instead, we now do the depth/size scans ahead of the loop, then move the
checking condition to the end.  In the best-case scenario for
optimisation (the circuit is already optimised) this would be a 2x
speedup of the optimisation loop for free, but more likely it will
manifest itself as a ~20% or so speedup.
A smallish subset of the transpiler benchmarks:
```text
before           after         ratio
[592b9acb]       [4977c3a7]
<main> …
```
=> Fix order of do-while loop in transpile optimisation

constraints.txt
The recent jinja2 release is breaking the tutorials ci job. This is
because something in the nbsphinx, jupyter, sphinx pipeline is
incompatible with the new version. These issues have been reported
upstream to jinja2 (and promptly closed as won't fix) so until the docs
build toolchain is upgraded to work with the new version this commit
pins the jinja2 version.
=> Pin jinja2 in CI

qiskit/tools/jupyter/library.py
For the purpose of documentation many of the circuit library classes
were using the circuit_library_widget to provide a visualization of
the circuit, a QASM definition, and some basic high level statistics
about the circuit. However, since #6634 and #6659 all the circuit
library elements are wrapped in an outer Instruction object. This
makes the top level object appear as a logical block in the circuit.
This has the unintended side effect of causing the widget output to not
be super useful, primarily it would should a single logical block for
each element and the circuit statistics would be for the single element
as opposed to its implementation. This commit address this by adding a
single decompose() call around all the statistics and drawing calls
inside the widget code. Since we're …
=> Add a decompose() call to circuit library table in docs

qiskit/transpiler/__init__.py
In #6962, the conditional flow-controller classes
`ConditionalController` and `DoWhileController` were promoted to being
able to be added to a `PassManager` directly via `PassManager.append`.
Since they are now a bit more public, this commit exposes them in the
`qiskit.transpiler` module (the same as `PassManager`), and adds them to
the documentation.
The release note about these classes imports them from `qiskit.transpiler` (which makes a lot of sense), but they're not actually available from there without this PR - they're only in the incredibly arcane location `qiskit.transpiler.runningpassmanager`.
=> Expose conditional `FlowController` classes

qiskit/primitives/estimator.py, qiskit/primitives/sampler.py, test/python/primitives/test_estimator.py, test/python/primitives/test_sampler.py
Remove parameter broadcasting that can be applied only for 1 circuit case.
Addresses part of #7836 (see this issue for details)
=> Remove parameter broadcasting in Primitives

qiskit/providers/fake_provider/__init__.py, qiskit/test/mock/__init__.py, qiskit/test/mock/fake_mumbai_v2.py, releasenotes/notes/rename-fake-mumbai-v2-2a4b4ead7360eab5.yaml, test/python/providers/test_backend_v2.py
https://github.com/Qiskit/qiskit-terra/pull/7643 implemented mocked IBM Quantum Systems backends using the new BackendV2 interface. FakeMumbaiV2 in https://github.com/Qiskit/qiskit-terra/blob/8105a80c84ce2447a1e224b85f4f56e98f074763/qiskit/test/mock/fake_mumbai_v2.py was created earlier for testing new V2 interface. This PR fix the name conflict between the old FakeMumbaiV2 (with hard coded instruction properties) and new FakeMumbaiV2 (built with device snapshots payloads) based on the new FakeBackendV2 class.
Partial fixes #7838
=> Rename old FakeMumbaiV2 to avoid name conflict with new FakeMumbaiV2

qiskit/circuit/library/standard_gates/iswap.py, qiskit/circuit/library/standard_gates/r.py, qiskit/circuit/library/standard_gates/rx.py, qiskit/circuit/library/standard_gates/rxx.py, qiskit/circuit/library/standard_gates/ry.py, qiskit/circuit/library/standard_gates/ryy.py, qiskit/circuit/library/standard_gates/rz.py, qiskit/circuit/library/standard_gates/rzx.py, qiskit/circuit/library/standard_gates/rzz.py, qiskit/circuit/library/standard_gates/u.py, qiskit/circuit/library/standard_gates/u1.py, qiskit/circuit/library/standard_gates/u3.py, qiskit/circuit/library/standard_gates/xx_minus_yy.py, qiskit/circuit/library/standard_gates/xx_plus_yy.py
The pull request fixes issuehttps://github.com/Qiskit/qiskit-terra/issues/7800 (#7800). I have modified the docstrings of standard_gates module to fix the parenthesis size.
The docstrings of some files of qiskit/circuit/library/standard_gates module were written without appropriate latex tag (\left, \right) for parenthesis (they were using default parenthesis). So, the parenthesis size was not align with other text. We can refer to https://github.com/Qiskit/qiskit-terra/issues/7800#issuecomment-1078872749 to see how modifying latex tags fixes parenthesis size.
I have edited docstrings of 13 files in the standard_gates module. Basically I adjusted the parenthesis tags to fix their size.
=> Improve parenthesis in circuit library equations 

qiskit/primitives/utils.py, releasenotes/notes/fix-primitive-init-observable-pauli-e312c05d1c3bd804.yaml
This PR fixes https://github.com/Qiskit/qiskit-ibm-runtime/issues/262.
=> Fix init_observable for Pauli

qiskit/primitives/base_estimator.py, qiskit/primitives/base_sampler.py, qiskit/primitives/estimator_result.py, qiskit/primitives/sampler.py, qiskit/primitives/sampler_result.py, qiskit/primitives/utils.py
There was an indent missing in the `EstimatorBase`:
And not all functions were fully documented (missing input args or return docs). Also I tried to improve the consistency with the rest of Qiskit whre we usually use full sentences in the docs, but feel free to reject or adjust that!
Is there a reason why we use `collections.abc` for typehints instead of `typing` as in the most of the (or all?) codebase? 🙂
=> Fix indent & improve consistency of primitive docs with Qiskit

.azure/tutorials-linux.yml, tox.ini
For sphinx builds we set the -W flag to treat warnings as errors. This
however, has the unfortunate side-effect of exiting the sphinx build
on the first warning and in the typical documentation debugging
workflow multiple iterations are required to debug all the issues. This
commit adds the --keep-going sphinx-build flag [1] to the default build
options. The --keep-going flag will still treat warnings as errors, but
not exit the build early. This should hopefully improve the
debuggability of the documentation as we'll get a complete picture of
what's wrong with a build instead of having to deal with it one warning
at a time.
[1] https://www.sphinx-doc.org/en/master/man/sphinx-build.html#cmdoption-sphinx-build-keep-going
=> Set sphinx-build --keep-going by default

test/randomized/test_synthesis.py, test/randomized/test_transpiler_equivalence.py
Since Aer 0.10.4 is now released with corrected handling of subnormal
floating-point numbers when compiled with gcc, this commit is no longer
necessary.
This reverts commit 77219b5c7b7146b1545c5e5190739b36f4064b2f.
Reverts #7719.
=> Revert "Workaround Aer bug with subnormal floats in randomised tests (#7719)"

test/randomized/test_transpiler_equivalence.py
Chooses layout, routing, and scheduling methods to use when invoking
transpile. This way, preset pass manager behavior with designated
transpilation method combinations is covered.
To support scheduling method coverage, a filter list is introduced to
exclude any fake backends that do not provide the necessary information
for instruction scheduling (i.e. gate durations).
Secondarily, this test is now configurable via enviroment variables,
the intention of which is to ultimately make it easy for transpiler passes
living outside of Terra to run equivalence tests in their own CI pipelines
to ensure proper Terra integration. For now, this has limited utility,
since neither layout, routing, nor scheduling methods can be used with
`transpile` unless Terra already knows about them. In the near …
=> Improve transpiler coverage of randomized equivalence test

qiskit/transpiler/passes/routing/sabre_swap.py, releasenotes/notes/fix-sabreswap-clbits-428eb5f3a46063da.yaml, test/python/transpiler/test_sabre_swap.py
Previously, SabreSwap only checked that it was valid to add a gate back
to the DAG by ensuring that all its qubit predecessors had already been
added to the DAG.  It did not check for clbit successors.  This meant
that measurements and (potentially, unverified) classically conditioned
gates could be re-ordered out from the correct topological ordering.
The most notable effect of this was that measurements writing to the
same bit could be re-ordered, changing the output of the circuit.
See gh-7950 for more detail.
Fix #7950.  I also believe this to be the cause of the sporadic randomised test failures (see an example in the linked issue).
Ali (@ajavadia) - this might be something you ought to look at, since I don't understand SabreSwap well.
=> Make SabreSwap account for clbits in predecessors

qiskit/circuit/library/graph_state.py
Since NetworkX 2.8, calling `networkx.adjacency_matrix` issues a
FutureWarning that causes the documentation build to fail.  There's no
reason for us to be using `networkx` since we have `retworkx` now.
NetworkX 2.8 released on the 9th of April and started emitted this `FutureWarning`, but we've fortunately not had any CI failures with this yet because our `pip` cache is still valid and pulling version 2.6.3.  Kevin's `tox` environment for the docs pulled the new version in and caused a failure, though.
=> Swap old networkx usage to retworkx

qiskit/transpiler/passes/routing/sabre_swap.py, releasenotes/notes/sabreswap-loop-230ef99e61358105.yaml, test/python/transpiler/test_sabre_swap.py
This adds a "release valve" mechanism to `SabreSwap`, so that it will
always eventually make forwards progress and terminate the run.  Before
this commit, it was possible for certain pathological circuits
(see `looping_circuit` in `test/python/transpiler/test_sabre_swap.py`
for an example) to get stuck in a stable local minimum of the
'lookahead' or 'decay' heuristics (no matter the weightings).
The release mechanism is done with very small per-loop overhead for the
vastly more common good paths; we simply count how many iterations we
have been through since we made progress, and the minimum weight in the
coupling map to be overcome to make progress again.  Once the
number of iterations without progress exceeds some value, we backtrack
(inefficiently, because this is the bad path) to the …
=> Fix potential infinite loop in SabreSwap

azure-pipelines.yml
Adds the missing install of `setuptools_rust` to the stable branch's Azure configuration, to fix the sdist build and deploy.
See also #7973 for the same thing on `main`.
=> Fix sdist build step on stable

azure-pipelines.yml
Adds the missing lines to install `setuptools_rust` (and `twine`, which somehow got dropped during #7698).
Perhaps the "proper" way to do this is to use a PEP-517 builder (e.g. https://pypi.org/project/build/), but this PR is more about getting things working again before we forget.
=> Fix sdist build and deployment

qiskit/qasm3/exporter.py, releasenotes/notes/fix-qasm3-global-statement-order-ca8bdb35e0fb8dec.yaml, test/python/circuit/test_circuit_qasm3.py
The current reference grammar requires that inputs and outputs are
defined before any gate declarations, so previously exported OpenQASM 3
programmes could fail to parse with the reference implementation.  It is
likely that the ordering is an arbitrary restriction and can be removed
from the grammar, but for the time being, we ought to match what is
written.
Fix #7964.
=> Fix order of input and gate declarations in QASM 3 exporter

test/randomized/test_transpiler_equivalence.py
This commit updates the strategies used to do the randomised testing of
transpiler equivalence, having three main effects:
1. The "pre-transpilation" circuit is now run on an Aer backend without
any transpilation at all, making the test truer to its name.
Previously `execute` was used which secretly performs a transpilation
internally.  This was accompanied by a small change to the set of
gates, to ensure only those that are directly supported by Aer are
used.
2. The strategies used for drawing gates are simplified into (mostly) a
single rule that draws a gate from a set, and populates it.  This is
just tidying up - it unifies the logic for drawing a gate into one
strategy rather than several.
3. The tests are updated to avoid using deprecated behaviour (e.g.
back-referencing a register …
=> Update randomised transpiler-equivalence test strategies

qiskit/test/mock/utils/backend_converter.py, releasenotes/notes/fix-target-dt-4d306f1e9b07f819.yaml, test/python/providers/test_fake_backends.py
Previously, `convert_to_target` was reading `dt` from the configuration/conf file, expecting it to be in seconds, when it is actually in nanoseconds.
The effect of this was that `FakeBackendV2` targets would return a `InstructionDurations` with all durations as `0`, since all durations round to `0` when divided by the erroneously large `dt` and converted to an integer.
=> Fix `dt` units in test util function `convert_to_target`

qiskit/compiler/transpiler.py, releasenotes/notes/fix-transpile-backendv2-durations-dbc85688564cc271.yaml, test/python/compiler/test_transpiler.py
When running `transpile()` with `BackendV2` based backends the instruction
durations property from the backend would not be processed correctly
resulting in the absence of the default durations for instructions
supported on the target backend. This commit fixes this by correctly
handling `BackendV2` based backends and using those instruction durations
by default for `transpile()`.
=> Fix instruction durations in transpile() with BackendV2

tox.ini
This change allows setting the number of rayon threads used by tox by passing through `RAYON_NUM_THREADS`, so that the user is not required to also specify `TOX_TESTENV_PASSENV=RAYON_NUM_THREADS`.
=> Pass through `RAYON_NUM_THREADS` env var in `tox.ini`

qiskit/test/mock/utils/backend_converter.py, qiskit/visualization/gate_map.py, releasenotes/notes/delay-fake-backends-3f68c074e85d531f.yaml, test/python/providers/test_fake_backends.py
This commit adds the delay instruction to the target for fake backends
based on BackendV2. With BackendV2 and the Target delay isn't assumed to
be present on every backend and it has to be explictly listed. This
commit fixes this so that the compiler is aware that delay is a valid
operation (without any additional constraints) on the BackendV2 based
fake backends.
=> Add missing delay instruction to fake backends

qiskit/transpiler/passes/synthesis/unitary_synthesis.py
This commit tweaks the logic around loading plugins in the
UnitarySynthesis transpiler pass. Previously we would unconditionally
perform plugin discovery in all cases even if no custom plugin was
specified. This added some overhead the first time we initialize a
UnitarySynthesis pass object to do the initial discovery, import, and
initialization of any installed plugins. While typically this is fast
(locally just with the 2 plugins including in terra this takes ~.04
seconds) it does depend on the performance of all the installed plugins.
However, this overhead is not necessary if there is not a custom
synthesis method requested by a user. If the default method is being
used we can just directly instatiate the plugin and avoid the discovery
process. This commit changes the UnitarySynthesis …
=> Avoid UnitarySynthesis plugin discovery overhead with no method set

qiskit/quantum_info/states/statevector.py, releasenotes/notes/statevector-enable-iter-4652d7ce87f4d459.yaml, test/python/quantum_info/states/test_statevector.py
Fixes https://github.com/Qiskit/qiskit-terra/issues/8039.
This is achieved by enabling proper iteration over `Statevector`.
I've opted to not add a docstring to the newly-added `__iter__` method, as I believe it's quite straightforward. Please, let me know if documentation should be added there and/or elsewhere.
I am new to the project, so if you could please suggest whether a release note needs to be added in the case of this PR.
Thanks!
=> Enable proper iteration over `Statevector`

src/results/marginalization.rs
Commit 84cfd5c1 recently used a `&[char; 2]` as the type in the
constructor of the `std::Pattern` trait, which is a feature of Rust
unstable, and only available in newer versions of Rust.  We've not fixed
an absolute minimum supported Rust version, but have generally tried to
keep things building with at least the last six months' releases.
=> Reduce Rust MSRV to 1.56

qiskit/dagcircuit/dagdependency.py
Checking whether gates are over disjoint sets of qubits: if so, they commute, and the more expensive check using matrix multiplication is not necessary. 
This is just a quick optimization. See also #8020.
A few experiments on random clifford circuits: 
```
gates = ["i", "x", "y", "z", "h", "s", "sdg", "cx", "cz", "swap"]
qc = random_clifford_circuit(num_qubits, num_gates, gates=gates, seed=0)
```
```
#qubits = 5,  #gates =  100  : size = 100,  depth = 26,   #edges = 138,  previous time = 0.29,    new time = 0.07
#qubits = 5,  #gates =  500  : size = 500,  depth = 146,  #edges = 722,  previous time = 3.51,    new time = 1.49
#qubits = 5,  #gates =  1000 : size = 1000, depth = 294,  #edges = 1500, previous time = 11.41,   new time = 4.32
#qubits = 5,  #gates =  5000 : size = 5000, depth = …
```
=> Small speedup to construct DagDependency

qiskit/quantum_info/operators/symplectic/base_pauli.py
I noticed that #7830 causes performance regression of `SparsePauliOp.to_list`.
Source: https://qiskit.github.io/qiskit/#quantum_info.SparsePauliOpBench.time_to_list
This PR fixes the regression.
`phase` used to be np.int64 and it was fast. But, #7830 makes `phase` as small as possible such as np.uint8 or np.uint16. I observe that operations of these types are slow.
```python
import random
from qiskit.quantum_info import SparsePauliOp
k = 10
n = 10_000
m = 3
random.seed(123)
op = SparsePauliOp.from_list([(''.join(random.choices('IXYZ', k=k)), 1) for _ in range(n)])
print(f'{timeit(lambda: op.to_list(), number=100)} sec')
```
main (794db47)
```
6.5075130869999995 sec
```
this PR
```
3.9482219790000004 sec
```
main (cbc801e, before merging #7830)
```
4.329158903 sec …
```
=> Fix performance regression of `BasePauli._to_label` by #7830

qiskit/extensions/quantum_initializer/diagonal.py, releasenotes/notes/3842-14af3f8d922a7253.yaml, test/python/circuit/test_diagonal_gate.py
Fixes #3842
I took the suggested solution from https://github.com/Qiskit/qiskit-terra/issues/3842 (thanks @hhyap!)  and the test from https://github.com/Qiskit/qiskit-terra/pull/4375 (thanks @ewinston!)
This issue was simple enough if you do not consider the full extend of #4375
=> Checks if DiagonalGate has modulus 1 

qiskit/quantum_info/operators/symplectic/pauli.py
@mberna found a MathJax syntax problem in https://qiskit.org/documentation/stubs/qiskit.quantum_info.Pauli.html
The problem is that that there is an amp alignment in a single equation.
I dont think the fix needs reno nor changelog entry.
=> Remove erroneous LaTeX alignment character

qiskit/version.py
Qiskit Aqua has been deprecated with its support ending and eventual archival being no sooner than 3 months from that date. This commit removes qiskit-aqua's deprecated version loading try-except mechanism located under qiskit/version.py and fixes TODO.
No additional details or comments.
=> (fix): deprecate qiskit-aqua version loading try-except after deprecation

qiskit/transpiler/passes/layout/_csp_custom_solver.py, qiskit/transpiler/passes/layout/csp_layout.py, qiskit/utils/optionals.py, releasenotes/notes/constraint-optional-b6a2b2ee21211ccd.yaml, requirements-dev.txt, requirements.txt, setup.py
Since #7213 we no longer have been using the CSPLayout pass by default
in the preset passmanagers or transpile(). This is because it has been
superseded by the VF2Layout pass which is now used everywhere. While we
will keep the CSPLayout pass around for the forseeable future there is
no need to install python-constraint by default anymore since it's only
user is the CSPLayout pass, which isn't going to be commonly used
anymore now that it's not used in the default compilation path anymore.
This commit removes the python-constraint library from the requirements
list and makes it an optional dependency.
Fixes #7726
=> Make python-constraint optional

qiskit/circuit/quantumcircuit.py
This PR changes the misleading line
https://github.com/Qiskit/qiskit-terra/blob/56b0de6822dec3fe1d97c05f4a5ddf3c3f4d4174/qiskit/circuit/quantumcircuit.py#L1739
to be 
```
**mpl**: images with color rendered purely in Python using matplotlib.
```
as a new user most likely would try `output='matplotlib'` whereas the correct param is `output='mpl'`.
The other output formats given in the docstring reflect the correct params, see https://qiskit.org/documentation/stubs/qiskit.circuit.QuantumCircuit.draw.html.
Closes #8119
=> Correct output format for matplotlib in `QuantumCircuit.draw` docstrings

qiskit/algorithms/eigen_solvers/numpy_eigen_solver.py
Trivial perf bugfix in NumpyEigensolver (to_spmatrix() was called twice on some paths, instead of first resullt being reused.
In the code of _solve(), `sp_mat `is assigned the result of `operator.to_spmatrix()`.  Later, on two code-paths, that expression is recomputed, instead of `sp_mat` being reused.  That's it.  A trivial performance fix (b/c `to_spmatrix()` can be very, very expensive for large operators.
=> Fix double matrix computation in numpy eigensolver

qiskit/compiler/transpiler.py, qiskit/transpiler/__init__.py, qiskit/transpiler/preset_passmanagers/__init__.py, qiskit/transpiler/target.py, releasenotes/notes/generate_pass_manager_preset-1e6c9641accd5d60.yaml, test/python/transpiler/test_preset_passmanagers.py
This commit adds a new function, `generate_preset_pass_managers()`, which
is used to quickly generate the preset pass manager for manual
interaction. Prior to this new function there were lower level functions
which are used to generate the individual pass manager objects for each
optimization level but they are hidden behind an abstraction object,
`PassManagerConfig` which is the only input. This makes it harder to work
with because the user has to manually remember to generate the config
object prior to creating the pass manager. Similarly this new function
simplifies the creation of preset pass managers by having a single entry
point instead of 4 for each optimization level.
=> Add function to easily generate preset pass managers

qiskit/test/mock/utils/configurable_backend.py, releasenotes/notes/fix-t2-configurablefakebackend-8660ab3d7a57a824.yaml, test/python/mock/test_configurable_backend.py
Fixes #8112 by setting T2 in `ConfigurableFakeBackend` with the input value
Unit tests added to verify it works
=> set T2 with the correct value in ConfigurableFakeBackend

qiskit/tools/jupyter/backend_overview.py
`threading.currentThread` was deprecated in Python 3.10 (October 2021) and will be removed in Python 3.12 (October 2023).
Replace with `threading.current_thread`, added in Python 2.6 (October 2008).
* https://docs.python.org/3.12/whatsnew/3.10.html#deprecated
* https://github.com/python/cpython/pull/25174
=> Replace deprecated threading.currentThread with current_thread

qiskit/synthesis/evolution/lie_trotter.py
The Lie-Trotter formula has a second order error [1][2].
[1] https://arxiv.org/pdf/math-ph/0506007.pdf
[2] https://simons.berkeley.edu/sites/default/files/docs/15639/trottererrortheorysimons.pdf
=> Fix the order of the Lie-Trotter formula in the documentation

qiskit/synthesis/evolution/suzuki_trotter.py
My previous commit https://github.com/Qiskit/qiskit-terra/pull/8167 corrects the documentation for the Lie-Trotter formula. According to my understanding of [1], the Suzuki-Trotter formula is second order accurate. This is now corrected in this commit.
[1] https://arxiv.org/pdf/math-ph/0506007.pdf
=> Fix the order of the Suzuki-Trotter formula in the documentation

qiskit/qasm3/exporter.py, releasenotes/notes/qasm3-fix-basis-gates-c96a0b357dfdcb47.yaml, test/python/circuit/test_circuit_qasm3.py
Previously the logic in the QASM 3 exporter was out-of-order, and would
ignore non-standard names added to `basis_gates`.  This changes the
logic order to correctly assume that everything in `basis_gates` is
automatically defined.
Fix #8159.
=> Fix QASM 3 exporter not respecting unknown `basis_gates`

docs/conf.py, qiskit/visualization/dag_visualization.py, test/python/visualization/test_dag_drawer.py
Switched to the `retworkx` method as suggested in the issue.
Made necessary changes to the tests.
Tested by running the code snippet provided before and after the changes - the graph output was identical except for the empty node.
Partially addresses #7717
=> Switched `dag_drawer` from `pydot` to `retworkx`

Cargo.lock, Cargo.toml, src/lib.rs, src/results/converters.rs
In the recently merged #8051 we create a lookup table in Rust to speed
up the hex->bin conversion used internally as part of the
marginal_memory() function. This was previously done using the
lazy_static crate which is used to lazily evaluate dynamic code to
create a static at runtime on the first access. The typical use case for
this is to create a static Vec or HashMap. However for the
marginal_counts() usage we didn't need to do this because we were
creating a fixed size array so the static can be evaulated at compile
time assuming the array is constructed with a const function. This
commit removes the lazy_static usage and switches to a true static to
further improve the performance of the lookup table by avoiding the
construction overhead.
=> Refactor marginal_memory() hex to bin lookup table to be a true static

qiskit/qpy/interface.py
As pointed out by @nkanazawa1989 in #8232 the regex construction added
to the QPY interface functions in #8200 can be a significant portion of
the overall function time especially for smaller inputs. Especially as
we're building it on every call interface function call. To ameliorate
that cost this commit compiles the version regex a single time at the
module level. This adds the overhead to import but it will only be done
once which should be a net improvement in performance.
=> Move QPY version regex construction to import time

qiskit/extensions/unitary.py, releasenotes/notes/fix-qasm2-identity-as-unitary-aa2feeb05707a597.yaml, test/python/circuit/test_unitary.py
The OpenQASM 2 exporter has a special case for providing `gate`
definitions, which was implemented purely for `UnitaryGate`.  This is
stateful per instruction, and does not generally behave well with the
rest of the exporter.  This commit fixes one misbehaviour: the way the
qubit operands for the definition was calculated was unreliable in both
order and number of qubits, if any of the qubits were unaffected by
the gate operation.
There are general problems with the special-case approach to defining the definition like this (see also #8222), which this commit does not fix, and the whole OpenQASM 2 exporter is known to be pretty questionable with custom and parameterised gates still.
Fix #8224.
=> Fix `UnitaryGate.qasm()` with unused qubits

test/python/quantum_info/test_synthesis.py
Addresses issue #8233.
Perhaps there was some issue with the use of `self.id` for the seed of the RNG. To check whether there was some decomposition error a ran this test with 1000 different seeds and didn't encounter any failures.
=> fix seed in qsd test

qiskit/pulse/library/symbolic_pulses.py
The support for serializing SymbolicPulse objects using QPY was added in
PR #7300 and has been released as part of 0.21.0. However, the
documentation for the SymbolicPulse class had a note saying the QPY
support was pending. This was necessary when the SymbolicPulse class was
added in #7821 because it was unclear when we'd be able to add the QPY
support. But, #7300 was updated and merged soon after #7821, but we
neglected to remove that note. This commit corrects the oversight and
removes the stale note.
=> Remove stale note about pending QPY support for SymbolicPulse

qiskit/extensions/unitary.py
Recently the pylint CI runs have all started failing because of an
unused OrderedDict import failure in qiskit/extensions/unitary.py. The
OrderedDict usage was removed in #8234 but the import was left in
accidently. This should have been caught by the lint job on that PR but
for some reason it was not caught and has sat there until relatively
recently when pylint started erroring because of the error. Normally for
failures like this they can be attributed to environment differences,
typically a release of pylint or astroid. However, we pin those package
versions because of their tendancy to change behavior, and also a diff
between the installed python packages in CI doesn't show any differences.
Regardless of the underlying cause to unblock CI this commit is necessary
to fix the unused …
=> Fix lint failure in qiskit/extensions/unitary.py

qiskit/opflow/evolutions/evolved_op.py, releasenotes/notes/fix-evolvedop-to-instruction-c90c4f1aa6b4232a.yaml, test/python/opflow/test_evolution.py
Fixes #8025.
As already described in #8025 by @kevinsung, the `EvolvedOp` should implement the unitary of `self.to_matrix()` and not `self.primitive.to_matrix()`, since the latter didn't yet exponentiate the operator.
=> Fix `EvolvedOp.to_instruction`

requirements-dev.txt
Sphinx 5.1 released on July 24th is braking the documentation building, so `Sphinx>=3.0.0,<5.1`:
```
2022-07-25T07:40:25.9446794Z ##[section]Starting: Run Docs build
2022-07-25T07:40:25.9453658Z ==============================================================================
2022-07-25T07:40:25.9453901Z Task         : Bash
2022-07-25T07:40:25.9454101Z Description  : Run a Bash script on macOS, Linux, or Windows
2022-07-25T07:40:25.9454296Z Version      : 3.201.1
2022-07-25T07:40:25.9454465Z Author       : Microsoft Corporation
2022-07-25T07:40:25.9454724Z Help         : https://docs.microsoft.com/azure/devops/pipelines/tasks/utility/bash
2022-07-25T07:40:25.9455011Z ==============================================================================
2022-07-25T07:40:26.0669105Z Generating script. …
```
=> Sphinx 5.1 breaks doc building

qiskit/algorithms/linear_solvers/hhl.py, qiskit/circuit/library/arithmetic/piecewise_chebyshev.py, qiskit/circuit/library/arithmetic/piecewise_polynomial_pauli_rotations.py
and update other locations with published version
Add a missing reference to `PiecewiseChebychev` that explains where the circuit is coming from. Also update locations of with the arXiv version with the published version of the paper.
=> Add explanatory reference to ``PiecewiseChebychev``

qiskit/opflow/state_fns/circuit_state_fn.py, releasenotes/notes/fix-opflow-vector-to-circuit-fn-02cb3424269fa733.yaml, test/python/opflow/test_state_op_meas_evals.py
Fix converting a `VectorStateFn` to a `CircuitStateFn`, which previously resulted in a `StateFn` that couldn't be adjoint.
Previously it was not possible to adjoint a `CircuitStateFn` that has been
constructed from a `VectorStateFn`, because the statevector has been 
converted to a circuit with the `Initialize` instruction, which
is not unitary. This problem is now fixed by instead using the `StatePreparation`
instruction, which can be used since the state is assumed to start out in the all 0 state.
For example we can now do:
```python
from qiskit.opflow import StateFn
left = StateFn([0, 1])
left_circuit = left.to_circuit_op().primitive
right_circuit = QuantumCircuit(1)
right_circuit.x(0)
overlap = left_circuit.inverse().compose(right_circuit)  # this …
```
=> Fix converting `VectorStateFn` to a `CircuitStateFn`

qiskit/compiler/assembler.py
When the `parameter_binds` are `[{}]`, the condition becomes `True`. So it causes unnecessary copies, resulting in lower performance.
=> Improve the performance of assemble when parameter_binds is a list of empty dicts

qiskit/algorithms/optimizers/scipy_optimizer.py, qiskit/test/base.py
Scipy 1.9.0 was recently released and introduced a few new deprecation
warnings. Due to the terra test suite being configured to make
DeprecationWarnings raised during the execution of tests fatal this is
causing failures in CI and local test runs when scipy 1.9.0 is used.
The first deprecation warning is that the minimize function has
deprecated the maxiter kwarg and replaced it with the maxfun argument
(which was introduced in scipy 1.5.0) for the TNC optimizer. To address
this the maxiter argument for the algorithms scipy optimizer is changed
to translate maxiter arguments (which is part of qiskit's api) when the
tnc optimizer is being used to send maxfun to scipy instead to avoid the
warning. The second warning being emitted is caused by scikit-learn's
internal usage of scipy. To …
=> Fix compatibility with Scipy 1.9.0

qiskit/transpiler/passmanager.py, releasenotes/notes/fix-staged-passmanager-c2e423ebf17eb57e.yaml, test/python/transpiler/test_staged_passmanager.py
Handle repeated stage names provided on `StagedPassManager` initialization.
`UserWarning` is thrown and only first occurrences are preserved.
=> Handle repeated stage names in StagedPassManager

qiskit/algorithms/optimizers/spsa.py, qiskit/extensions/unitary.py, qiskit/transpiler/passes/scheduling/padding/pad_delay.py
Using `code-block::python` without the space between the colon and `python` seems to be invalid and the docs do not display the code block at all. This is also used in a releasenote from 0.18. Can we still fix that by updating the files in this repo?
I also moved the trailing Example from SPSA's initializer to the class docstring, where all the others are.
For example the `UnitaryGate` docs contain the snippet
```
Example:
We can create a unitary gate from a unitary matrix then add it
to a quantum circuit. The matrix can also be directly applied
to the quantum circuit, see :meth:`~qiskit.QuantumCircuit.unitary`.
.. code-block::python  # no space here!
from qiskit.extensions import UnitaryGate
matrix = [[0, 0, 0, 1],
[0, 0, 1, 0],
[1, 0, 0, 0],
[0, 1, 0, …
```
=> Fix `code-block:: python` in docs

qiskit/circuit/parameterexpression.py, releasenotes/notes/fix-paramexpr-isreal-8d20348b4ce6cbe7.yaml, test/python/circuit/test_parameters.py
Fixes #8417.
This PR works around a case in symengine where an expression is not identified as real or imaginary if it is multiplied by a constant. This led to the unexpected behavior in Qiskit that e.g. `2 * I` was not being identified as imaginary:
```python  
from qiskit.circuit import Parameter
x = Parameter("x")
expr = 1j * x
bound = expr.bind({x: 2})
print(bound.is_real())  # used to be True, but is now False
```
=> Fix ``ParameterExpression.is_real`` if ``symengine`` is installed

qiskit/primitives/primitive_job.py, test/python/primitives/test_sampler.py
Fixes `PrimitiveJob`'s `status` to correctly return `JobStatus.DONE` when there were no errors.
=> Fix `PrimitivesJob`'s status method

qiskit/qpy/binary_io/circuits.py, releasenotes/notes/fix-qpy-controlledgate-open-control-35c8ccb4c7466f4c.yaml, test/python/circuit/test_circuit_load_from_qpy.py, test/qpy_compat/test_qpy.py
Previously, an incorrect definition and name would be re-instated on
QPY deserialisation of a `ControlledGate` instance with open controls.
The base name would include the dynamic `_o{ctrl_state}` suffix, causing
the suffix to later be duplicated, and the definition would duplicate
the logic that added the open controls.  This fixes both by stripping
the suffix on re-read before it is assigned, and serialising only the
"11...1" state definition, since this is what is required and stored by
`ControlledGate`.
Fix #8549.
This is technically a breaking change in the behaviour of QPY (it changes how something is serialised and deserialised), but it is not a format change.  A file created with the previous serialisation behaviour will still load with this new logic, and an older Qiskit will be …
=> Fix QPY serialisation of ControlledGate with open controls

qiskit/circuit/quantumcircuit.py, releasenotes/notes/fix-QuantumCircuit.compose-in-control-flow-scopes-a8aad3b87efbe77c.yaml, test/python/circuit/test_control_flow_builders.py
Previously, `QuantumCircuit.compose` with `inplace=True` would insert
the appended instructions outside the scope due to unchecked use of
`QuantumCircuit._append` (and direct modification of the `data`
attribute).  This now respects any active control-flow scopes.
Using `front=True` in conjunction with `inplace=True` within a
control-flow scope has no clear meaning, and so the behaviour is
forbidden.  Emitting a new circuit (`inplace=False`) while in an active
scope would produce a broken circuit - the active scope would need to be
cloned to ensure equivalence, but it wouldn't be part of any
Python-managed context, so the scope could never be closed.
Fix #8433.
=> Fix QuantumCircuit.compose within control-flow scopes

test/qpy_compat/test_qpy.py
Circuits in QPY backwards compatibility should always have fixed names,
to avoid changes in the number of circuits constructed during library
set-up code affected the output names.
Fixes CI failing in the QPY tests (which only run on 3.10 / Linux).
=> Ensure QPY test circuits have non-generated names

qiskit/primitives/estimator.py, qiskit/primitives/sampler.py
This is a part of https://github.com/Qiskit/qiskit-terra/pull/8367.
This PR reduces deepcopy of the circuit by not calling `bind_parameters` when no parameters exist.
=> Skip binding when parameter is None

tox.ini
In the second run of `tox`, it fails as follows:
```
File "qiskit-terra/setup.py", line 19, in <module>
from setuptools_rust import Binding, RustExtension
ModuleNotFoundError: No module named 'setuptools_rust'
ERROR: invocation failed (exit code 1)
__________________________________________________________________________________________________________________________________ summary __________________________________________________________________________________________________________________________________
ERROR:   py39: InvocationError for command qiskit-terra/.tox/py39/bin/python setup.py --name (exited with code 1)
```
This PR add the dependency (`setuptools_rust`) to `tox.ini`.
=> Add setuptools_rust to tox.ini

qiskit/primitives/estimator.py, qiskit/primitives/sampler.py, qiskit/primitives/utils.py
This PR Improves performance of `Estimator` by converting circuits to instructions manually to avoid parameter binding in `circuit_to_instruction` method.
Address the same issue with #8367 
TODO
Comparison with microbenchmark
```python
from timeit import default_timer
from qiskit.circuit import QuantumCircuit
from qiskit.primitives import Estimator
from qiskit.quantum_info.random import random_pauli
num_qubits = 6
num_operators = 100
num_circuits = 100
circ = QuantumCircuit(num_qubits)
circ.x(range(num_qubits))
observables = [random_pauli(num_qubits, seed=seed) for seed in range(1, num_operators + 1)]
start = default_timer()
estimator = Estimator()
for _ in range(num_circuits):
a = estimator.run([circ] * num_operators, observables)
print(f"{default_timer() - start} sec")
```
```
main …
```
=> Improve performance of `Estimator` and `Sampler` by avoiding deep copy at `circuit_to_instruction`.

qiskit/utils/deprecation.py
Currently there is no way to warn when an argument is deprecated and no replacement is provided. 
I propose that passing None as `new_arg`.
This comes from the comment https://github.com/Qiskit/qiskit-terra/pull/8510#discussion_r942583962
Comments are welcome.
=> Support deprecate_arguments with new_arg None

qiskit/visualization/circuit_visualization.py, releasenotes/notes/fix-latex-split-filesystem-0c38a1ade2f36e85.yaml
=> Fix LaTeX drawer on split-filesystem systems

src/sabre_swap/sabre_dag.rs, test/python/transpiler/test_sabre_layout.py
This commit fixes a bug introduced in SabreSwap that was caught by the
randomized testing in #8635. A copy paste error was causing the rusty
sabre code to panic in cases where there were classical bits of a
particular index assigned prior to the qubit with the same index. This
commit fixes the typo so the behavior is corrected in general and the
panic is also fixed.
Fixes #8635
=> Fix panic in SabreSwap with classical bits

.azure/test-linux.yml, .azure/test-macos.yml, .azure/test-windows.yml, .github/workflows/randomized_tests.yml
This should hopefully just help a bit with the logging when CI fails due to Rust panics.  We've seen a couple of places where it could have been useful in the randomised tests recently.
=> Enable Rust backtraces in CI

src/sabre_swap/mod.rs, test/python/transpiler/test_sabre_layout.py
This commit fixes a potential overflow which was caught by the
randomized testing around tracking the number of search steps for the
purposes of resetting the decay rates used by the heuristic scoring.
The number of search steps was using an unsigned 8bit integer because
it's typically not a large number and it's used to track if we've
performed 5 steps or more before resetting the decay rate for each
qubit. However in some cases if there were more than 255 steps
this value would overflow the way this detection was being done.
While this actually wouldn't be fatal because the value would reset back
to 0 and we'd still track the decay rate correctly this was a potential
error in debug mode. This commit fixes this by detecting when we've
reached DECAY_RESET_INTERVAL steps and resetting the …
=> Fix potential overflow in sabre swap

qiskit/utils/deprecation.py
The current deprecate decorators only support `DeprecationWarning`
If someone needs to use `PendingDeprecationWarning` there isn't decorator support.
This PR adds an optional category to the decorators that defaults to `DeprecationWarning`
This seems to me a much required feature for all the deprecation that will be written for algorithms.
=> Add optional category parameter to deprecate decorators

.github/workflows/randomized_tests.yml
In #8639 we added an environment variable to enable printing the rust
back traces when the rust code under test panics. However, that PR had a
small syntax error as it used the bash syntax for setting an env
variable and not the correct yaml syntax for github actions. This commit
corrects the oversight to fix the job configuration so that the jobs run
again.
=> Fix github actions yaml syntax for randomized testing

qiskit/algorithms/optimizers/spsa.py, releasenotes/notes/qiskit-nature-797-8f1b0975309b8756.yaml, test/python/algorithms/optimizers/test_spsa.py
Fixes https://github.com/Qiskit/qiskit-nature/issues/797
The internal function `qiskit.algorithms.optimizers.spsa._batch_evaluate` uses `np.split` instead of `np.array_split`. This results in an exception as described [here](https://github.com/Qiskit/qiskit-nature/issues/797) when the split is uneven.
I used the static method `qiskit.algorithms.SPSA.estimate_stddev` for testing, since it was not directly tested and the method made it easier to parametrize in a way to cover the fix. However, I'm not sure if my input for that test is making any sense.
=> Use np.array_split instead of np.split to support uneven splits in spsa._batch_evaluate

qiskit/visualization/gate_map.py
Fixes #8670 
The example for the "plot_coupling_map" function interchanged the order of the two inputs "qubits_coordinates" and "coupling_map" leading to an intermingled graph output. The proper output was obtained by simply interchanging the two inputs.
=> Fix incorrect docs image in `plot_coupling_map`

qiskit/algorithms/factorizers/shor.py, qiskit/algorithms/linear_solvers/hhl.py
Add the alternative links to tutorials in the deprecation messages for HHL and Shor
=> Improve HHL/Shor deprecated messages

qiskit/pulse/__init__.py, qiskit/pulse/builder.py, releasenotes/notes/qiskit.pulse.builder-ddefe88dca5765b9.yaml, test/python/pulse/test_builder.py
In https://github.com/Qiskit/qiskit-terra/pull/6158 (released in 0.18.0, July 2021) the functions `qiskit.pulse.builder.inline` and `qiskit.pulse.builder.pad` are deprecated. Time to remove them.
=> Remove deprecated pulse-builder contexts

qiskit/pulse/utils.py, releasenotes/notes/deprecated-pulse-deprecator-394ec75079441cda.yaml
The decorator `deprecate qiskit.pulse.utils.deprecated_functionality` was introduced in https://github.com/Qiskit/qiskit-terra/pull/5854/ and its functionality is fully covered by the current `qiskit.utils.deprecation.deprecate_function`.
=> deprecate qiskit.pulse.utils.deprecated_functionality in favor of qiskit.utils.deprecation.deprecate_function

qiskit/quantum_info/operators/mixins/linear.py, releasenotes/notes/base-operators-sums-d331e78a9fa4b5d8.yaml, test/python/quantum_info/operators/test_scalar_op.py
This enables the use of `sum(...)` for subclasses of the `LinearMixin` class. It also adds the reflective operand dunder methods `__radd__` and `__rsub__`.
Since this is not part of the publicly documented API, I did not add a reno.
=> feat: support sum(LinearMixin)

qiskit/circuit/instruction.py, test/python/circuit/test_circuit_qasm.py
OpenQASM 2 can't represent single bit conditions, so it's impossible for us to output sensible code in this case.  Instead, we just make sure the error message clearly explains what's going on.
Fix #8700.
=> Improve error message on QASM 2 export of single-bit conditions

requirements-dev.txt
After the recent release of stestr 4.0.0 CI started failing in a weird unexpected way 100% of the time. It's not clear why the failure started and I'm unable to reproduce it locally (which is part of why I pushed stestr 4.0.0, I did test that I passed tests locally before releasing). To try and unblock CI this commit caps the stestr version we install in CI to see if this fixes the failure and potentially unblock CI.
=> Cap stestr version in CI

qiskit/qasm3/exporter.py, releasenotes/notes/qasm3-fix-conditional-measurement-2d938cad74a9024a.yaml, test/python/circuit/test_circuit_qasm3.py
The `.condition` attribute for `Instruction` instances corresponding to OpenQASM 3 built-ins (such as `reset` and `measure`) would previously be ignored.  This now correctly nests them inside a a branching statement in the exporter, so the condition is preserved.
Fix #8730.
=> Fix OpenQASM 3 built-ins with classical conditions

qiskit/visualization/__init__.py
A recent change to the structure of the visualisation module in #8306 caused `matplotlib` to be eagerly imported when `qiskit.visualization` was imported, since the internal `bloch` module was imported in the `__init__`.  This means that `QuantumCircuit.draw()` in text mode had ceased working without the visualisation extra installed.
This module doesn't really need to be eagerly imported, and it's faffy to refactor it all to use lazy imports.
I've seen a couple of CI failures in the QPY backwards-compatibility tests seemingly caused by this.  It's odd they didn't prevent the initial merge, but maybe some internal dependencies re-organised themselves around the same time.
=> Fix QuantumCircuit.draw without matplotlib installed

qiskit/visualization/circuit/_utils.py, test/python/visualization/test_circuit_text_drawer.py
The wire management in the circuit drawers could accidentally mutate the qubits in the input circuit.  The root cause of this is because `QuantumCircuit.qubits` (and `.clbits`) are properties that expose the internal, mutable lists that back them directly.  This is a larger failing of the `QuantumCircuit` API, but one that is slightly tricky to walk back without backwards-incompatible changes or performance regressions.
Fix #8739.  No release note because this regression was introduced by #8173, which hasn't been released yet.
=> Fix circuit drawers mutating input circuits

qiskit/algorithms/gradients/base_estimator_gradient.py, qiskit/algorithms/gradients/base_sampler_gradient.py, qiskit/primitives/base_estimator.py, qiskit/primitives/base_sampler.py, qiskit/primitives/estimator.py, qiskit/primitives/sampler.py, test/python/algorithms/test_estimator_gradient.py, test/python/algorithms/test_sampler_gradient.py, test/python/primitives/test_estimator.py, test/python/primitives/test_sampler.py
@jyu00 requested renaming `run_options` to `options` for consistency with `qiskit-ibm-runtime`.
=> Rename run_options to options

qiskit/transpiler/passes/basis/unroll_3q_or_more.py, qiskit/transpiler/passes/basis/unroll_custom_definitions.py, qiskit/transpiler/passes/basis/unroller.py, qiskit/transpiler/passes/optimization/collect_linear_functions.py, qiskit/transpiler/passes/optimization/cx_cancellation.py, qiskit/transpiler/passes/optimization/optimize_cliffords.py, qiskit/transpiler/passes/optimization/optimize_swap_before_measure.py, qiskit/transpiler/passes/optimization/remove_diagonal_gates_before_measure.py, qiskit/transpiler/passes/optimization/reset_after_measure_simplification.py, qiskit/transpiler/passes/utils/__init__.py, qiskit/transpiler/passes/utils/control_flow.py, qiskit/transpiler/passes/utils/remove_barriers.py, test/python/transpiler/test_clifford_passes.py, test/python/transpiler/test_cx_cancellation.py, test/python/transpiler/test_linear_functions_passes.py, test/python/transpiler/test_optimize_swap_before_measure.py, test/python/transpiler/test_remove_barriers.py, test/python/transpiler/test_remove_diagonal_gates_before_measure.py, test/python/transpiler/test_reset_after_measure_simplification.py, test/python/transpiler/test_unroll_3q_or_more.py, test/python/transpiler/test_unroll_custom_definitions.py
This converts all transpiler passes whose structure allows their `run` methods to be made trivially recursive, either by eagerly modifying all control-flow operations in a depth-first pass before running the method on the top level of the circuit, or by inserting the recursion during an interior loop.
There are other passes that are relatively simple to handle as well (`UnitarySynthesis` is one), but their current structure would require just a shade more work than the trivial cases in this commit.
Close #8445 (by obsoleting it).  We can rework #8565 to do essentially this as well - we probably just want to take a bit more care than that PR currently does not to redo all the setup work in the pass.
=> Lift trivial transpiler passes to handle control flow

test/python/algorithms/state_fidelities/test_compute_uncompute.py
This PR removes `test_param_mismatch` from the `ComputeUncompute` unit tests, as this check is already performed in the sampler unit test.
Motivated by CI breaking because of fidelity tests in https://github.com/Qiskit/qiskit-terra/pull/8760.
=> Remove param. test for `ComputeUncompute`

qiskit/visualization/state_visualization.py, releasenotes/notes/rh1_state_to_latex_fix-e36e47cbdb25033e.yaml, test/python/quantum_info/states/test_statevector.py
Fix for #8460 
Couldn't find tests for the `_state_to_latex_ket` function but happy to add this test case if they exist somewhere.
=> Fix _state_to_latex_ket prefix kwarg bug

qiskit/transpiler/preset_passmanagers/level3.py
For some time (I expect since #6403 but maybe before) we've been running the optimization loop for optimization level 3 twice for no reason. This is clearly a mistake as it adds a single extra run of all the optimization passes since we've already reached a steady state in depth and size by this point. This is just a waste of time and was unintentional. This commit removes the unintended duplication.
=> Remove duplicate optimization loop in level 3 PassManager

requirements-dev.txt
The just released update of `sphinx-autodoc-typehints` is crashing the docs with the error:
```
sphinx.errors.ExtensionError: Handler <function process_docstring at 0x7fbaa478e550> for event 'autodoc-process-docstring' threw an exception (exception: list index out of range)
```
Changed to avoid the new version 1.19.3 for now.
=> Pin sphinx-autodoc-typehints to avoid 1.19.3

qiskit/algorithms/__init__.py, qiskit/algorithms/minimum_eigen_solvers/vqe.py, qiskit/algorithms/minimum_eigensolvers/__init__.py, qiskit/algorithms/minimum_eigensolvers/minimum_eigensolver.py, qiskit/algorithms/minimum_eigensolvers/numpy_minimum_eigensolver.py, qiskit/algorithms/minimum_eigensolvers/vqe.py, qiskit/algorithms/observables_evaluator.py, qiskit/algorithms/optimizers/spsa.py, qiskit/algorithms/time_evolvers/trotterization/trotter_qrte.py, qiskit/algorithms/utils/__init__.py, qiskit/algorithms/utils/validate_bounds.py, qiskit/algorithms/utils/validate_initial_point.py, qiskit/algorithms/variational_algorithm.py, releasenotes/notes/0.19/add-getters-and-setters-for-vqe-edc753591b368980.yaml, releasenotes/notes/0.19/support-dict-for-aux-operators-c3c9ad380c208afd.yaml, releasenotes/notes/0.19/taper_empty_operator_fix-53ce20e5d2b68fd6.yaml, releasenotes/notes/vqe-with-estimator-primitive-7cbcc462ad4dc593.yaml, test/python/algorithms/minimum_eigensolvers/test_numpy_minimum_eigensolver.py, test/python/algorithms/minimum_eigensolvers/test_vqe.py, test/python/algorithms/test_observables_evaluator.py, test/python/algorithms/time_evolvers/test_trotter_qrte.py, test/python/algorithms/utils/__init__.py, test/python/algorithms/utils/test_validate_bounds.py, test/python/algorithms/utils/test_validate_initial_point.py
Adds a standard `VQE` implementation using an `Estimator` primitive.  Closes #8471.
A `SamplingVQE` implementation that takes a `Sampler` primitive is introduced in PR #8669.
This fresh implementation lives in `qiskit/algorithms/minimum_eigensolvers`. The prior implementation may still be found in `qiskit/algorithms/minimum_eigen_solvers`.
The following elements have been removed:
* The final "eigenstate". To reproduce this one may use a `Sampler` and the optimal point from VQE outside the algorithm.
* ~~The callback from the energy evaluation.  Instead the callback should be attached to the optimizer which can allow to additionally evaluate the energy at the current point.~~ After discussing with @woodsp-ibm, I decided to add back the callback on VQE as this may be simpler for users. …
=> VQE implementation with estimator primitive

.github/CODEOWNERS
This better represents which of the internal team have the time to devote to being a full code owner of the pulse and scheduling modules. Will has been doing great reviews of Naoki's features for the pulse module, and he's the best person to join as another code owner there. Dan doesn't have time now to be a full code owner of pulse, which is the only reason for removing him.
I've spoken to the current code owners of Pulse, plus @wshanks, @mtreinish and @kdk for sign-off already.
=> Change pulse code owners

qiskit/primitives/base_estimator.py
Remove incorrect return type annotation from `BaseEstimator.set_options` method
The function does not return anything.
=> Remove incorrect return type annotation from `BaseEstimator.set_options`

qiskit/transpiler/passes/layout/vf2_utils.py, test/python/transpiler/test_vf2_layout.py, test/python/transpiler/test_vf2_post_layout.py
The subgraph isomorphism problem we are solving here can fairly easily be extended to account for the available types of control flow in Qiskit right now.  We just treat each control flow operation as "transparent" in the pass, i.e. as if each of its blocks were simply inserted verbatim (with the requisite wire mapping) sequentially.
We use the same weighting heuristics for control-flow loop bodies in the scoring as elsewhere; for-loops count for the number of iterations, while if-else and while loops count (all of) their bodies once.
The testing in this particular commit is slightly light, because some of the general strategies involve a `transpile` call, which isn't fully ready yet with control flow.
Getting VF2 working with control flow was very easy - this sort of "block transparency" …
=> Make VF2Layout and VF2PostLayout work with control flow

qiskit/transpiler/passes/utils/check_map.py, test/python/transpiler/test_check_map.py
Adds control flow handling to the CheckMap transpiler pass.
=> add controlflow handling to CheckMap transpiler pass.

test/python/algorithms/minimum_eigensolvers/test_adapt_vqe.py
This stabilizes the flaky test of `AdaptVQE` reported in #8806 by:
- setting `algorithm_globals.random_seed`
- decreasing the convergence threshold for good measure
Prior to this fix, I was able to reproduce flakiness after ~300 independent repetitions of the flaky test.
After this fix, I could ran 1000 repetitions without running into it again :+1: 
Closes #8806
=> fix: stabilize the flaky cyclicity test of AdaptVQE

qiskit/transpiler/passes/layout/dense_layout.py, test/python/transpiler/test_dense_layout.py
Add control flow handling to dense layout pass.
depends on #8763
todo: may still need to update `Target.operation_names_for_qargs` when target object is supplied.
=> add control flow handling to DenseLayout pass

test/python/primitives/test_backend_estimator.py
The backend estimator tests are using Aer as a simulator via the fake backends to validate that we calculate an expected expectation value for the BackendEstimator. However, since #8736 merged this test has had a non-zero failure rate since being introduced due to the RNG and tolerance issues. It turns out that the tests were setting the rng seed incorrectly. Options on the BackendEstimator (and BackendSampler) are passed through to the underlying backend. So in this case to set a fixed seed for simulation we should be using `seed_simulator` instead to fix the seed for the simulation. This commit fixes this. Also just in case the rtol for the test in question is bumped too to avoid any potential issue in the future.
Fixes #8819
=> Fix random failure in backend estimator tests

requirements.txt
There is no wheel for tweedledum 1.1.1 for M1 Mac, and attempting to compile from the sdist does not generally work.  This has caused significant problems for our users in the past, and given we are moving to remove tweedledum as a core requirement, it's simplest just to add a constraint to make life easier for users in the interrim.
Fix #8716
=> Force skip tweedledum 1.1.1 on macOS amd64

qiskit/transpiler/passes/utils/gates_basis.py, test/python/transpiler/test_gates_in_basis_pass.py
It's not yet entirely clear how control-flow will be supported through the `Target` and `basis_gates`, but for the time being, we just test them as if they will be added like any other instruction.  This is unlikely to entirely remain the case as more classical handling is added.
=> Add control-flow support to `GatesInBasis`

qiskit/transpiler/passes/utils/check_gate_direction.py, qiskit/transpiler/passes/utils/gate_direction.py, releasenotes/notes/gate-direction-target-a9f0acd0cf30ed66.yaml, test/python/transpiler/test_check_gate_direction.py, test/python/transpiler/test_gate_direction.py
These are largely straightforwards, but since each pass has essentially two separate versions, it became simpler to refactor them out when doing the recursion, rather than using internal closures.  As part of the refactor, we also swap to using `Target.instruction_supported` to check for validity - this method was added after the passes were originally made target-aware.
=> Update GateDirection and checker for control flow

requirements.txt
`importlib_metadata` 5.0 broke `stevedore`.  Normally we would set this pin in `constraints.txt`, but since this is critical functionality and we may need to release before `stevedore` is fixed, we fix the problem at the requirements level, temporarily making `importlib_metadata` a direct requirement.
Fix broken CI for Python 3.7.
=> Limit importlib_metadata in requirements

qiskit/circuit/quantumcircuit.py, releasenotes/notes/condition-in-while-loop-d6be0d6d6a1429da.yaml, test/python/circuit/test_control_flow.py
This makes the behaviour match that of `if_test`; the omission here was just a bug.
=> Resolve classical conditions in `QuantumCircuit.while_loop`

qiskit/quantum_info/operators/symplectic/clifford.py, qiskit/quantum_info/operators/symplectic/clifford_circuits.py, test/python/quantum_info/operators/symplectic/test_clifford.py
Improve the performance of Clifford.from_circuit() by avoiding unnecessary `to_instruction` calls.
As a by-product, the `clifford_circuits._append_circuit` function is refactored into two functions `clifford_circuits._append_circuit` and `clifford_circuits._append_operation` for readability.
=> Improve the performance of Clifford.from_circuit()

qiskit/primitives/backend_estimator.py, qiskit/primitives/base_estimator.py, qiskit/primitives/estimator.py, qiskit/primitives/utils.py, test/python/primitives/test_backend_estimator.py, test/python/primitives/test_estimator.py
=> Introduce observable key for Estimator

qiskit/compiler/transpiler.py, qiskit/quantum_info/operators/operator.py, qiskit/transpiler/basepasses.py, qiskit/transpiler/layout.py, qiskit/transpiler/passes/layout/apply_layout.py, qiskit/transpiler/runningpassmanager.py, qiskit/visualization/circuit/latex.py, qiskit/visualization/circuit/matplotlib.py, qiskit/visualization/circuit/text.py, qiskit/visualization/gate_map.py, releasenotes/notes/fix-Opertor.from_circuit-transpile-5c056968ee40025e.yaml, test/python/quantum_info/operators/test_operator.py, test/python/transpiler/test_bip_mapping.py, test/python/transpiler/test_preset_passmanagers.py, test/python/transpiler/test_sabre_layout.py, test/python/visualization/test_circuit_text_drawer.py, test/python/visualization/test_gate_map.py
This commit fixes a bug in the Operator.from_circuit() constructor method for Layout's generated by transpile(). The transpiler would set the _layout property for an output circuit to be the mapping from the input circuit's virtual qubits to the physical qubits (also the output circuit's qubit index). This is useful for visualization and visually tracking the permutation assuming you have the original circuit. However for the `Operator.from_circuit()` constructor method which will reverse the permutation caused by layout in the generated matrix this is not sufficient information since we need to order of the original circuits qubits. To fix this issue this commit changes the `_layout` attribute of the QuantumCircuit class to store both the initial layout as before and also a mapping of …
=> Fix reverse permutation for transpiled circuits in Operator.from_circuit

qiskit/transpiler/__init__.py
Changed from `from qiskit.transpiler.preset_passmanager` to `from qiskit.transpiler.preset_passmanagers` in the documentation example, and a few additional random typos.
=> Fixing import in preset_passmanagers code example

qiskit/primitives/estimator.py, test/python/primitives/test_estimator.py
Variance may be negative by numerical error.
This PR warns it and change the negative variance to zero.
Thank you for finding the bug @dlasecki.
=> Handle negative variance in Estimator

qiskit/transpiler/preset_passmanagers/plugin.py
In the [2022-09-15 DemoDay recording](https://github.com/Qiskit/feedback/wiki/Qiskit-DemoDays#sep-15-2022), @mtreinish says:
> ... a `PassManagerStagePlugin ` needs a `PassManagerConfig` and.... apparently I need to update the docs, because it also takes an optimization level ...
This PR is that doc update, plus some excuse to use the `optimization_level` parameter as an example.
=> Fix in Transpiler Stage Plugin Interface docs

test/python/primitives/test_backend_estimator.py
We're still seeing a rare occasional tolerance failure in CI from the BackendEstimator tests. To eliminate this possibility this commit sets a fixed seed for all the BackendEstimator tests which weren't currently to eliminate any non-deterministic failures in CI.
=> Set a fixed seed for all BackendEstimator tests

releasenotes/notes/begin-tweedledum-removal-25bb68fc72804f00.yaml, requirements.txt
In gh-8818 we prevented macOS arm64 from attempting to use tweedledum 1.1.1 as no arm64 wheels are supplied for that version.  In fact, the "arm64" and "universal2" wheels supplied for 1.1.0 are actually mislabelled x86_64 wheels as well, and so there is no working binary version of tweedledum for arm64, and the sdist build process works only rarely for most people.
Since the work of gh-8738 makes `tweedledum` _effectively_ optional for `import qiskit` with immediate effect, and the only way to have a working installation on M1 mac is essentially to have already manually built `tweedledum` from source, the effects of immediately removing the requirement from arm64 macs only should be very slight at worst, and a good quality of life improvement for normal M1 users.
See also …
=> Remove tweedledum from macOS arm64 immediately

.pylintrc, qiskit/circuit/equivalence.py, qiskit/transpiler/coupling.py, qiskit/transpiler/passes/basis/basis_translator.py, qiskit/visualization/dag_visualization.py
With the recent release of retworkx 0.12.0 the package has been renamed to rustworkx. For compatibility the retworkx python namespace continues to work and instead it just redirects imports to the new name. However, pylint is unable to reason about this dynamic import redirecting which causes it to fail in CI. While in 0.23.0 we'll update the requirement to the rustworkx name in order to unblock CI for the pending 0.22.0 release this commit adds the retworkx namespace to the list of generated modules which tells pylint to try not to detect members of the module.
=> Add retworkx to generated module list in the .pylintrc

qiskit/providers/fake_provider/fake_backend.py, test/python/providers/fake_provider/test_fake_backends.py
This commit fixes the noise model construction of instances of FakeBackendV2. Previously, the FakeBackendV2 class would try to build the noise model only if there was a stored BackendProperties JSON payload present. However, if run() is used directly without `transpile()` or something querying the Target for the backend we won't have necessarily loaded the properties yet. This commit fixes this issue by first checking we have a target defined which will load the properties json if present and then uses the presence of properties to construct the noise model.
Fixes #8862
Fixes #8801
=> Ensure target is generated during run() with FakeBackendV2

qiskit/algorithms/minimum_eigensolvers/sampling_vqe.py, qiskit/primitives/base_estimator.py
Change doc string to reflect respective primitive in SamplingVQE and BaseEstimator classes. 
- SamplingVQE: Changed attribute string to reflect Sampler
- BaseEstimator: Changed deprecation message to reflect BaseEstimator
=> Minor doc fix in `SamplingVQE` and `BaseEstimator`

qiskit/quantum_info/operators/symplectic/base_pauli.py, qiskit/quantum_info/operators/symplectic/pauli.py, qiskit/quantum_info/operators/symplectic/pauli_list.py, releasenotes/notes/fix_8438-159e67ecb6765d08.yaml, test/python/quantum_info/operators/symplectic/test_pauli.py, test/python/quantum_info/operators/symplectic/test_pauli_list.py
Fixes #8438 
Fixes issue where `Pauli.evolve` and `PauliList.evolve` would raise a dtype error when evolving by certain Clifford gates which modified the Pauli's phase.
This fix make it so that rather than cast the dtype of the phase vector to a fixed type, it will accept any signed or unsigned integer dtype and work with that.
=> Fix pauli.evolve dtype casting error

qiskit/pulse/transforms/alignments.py, releasenotes/notes/0.22/deprecated-pulse-deprecator-394ec75079441cda.yaml
This fixes some deprecation warnings that pop up during my use of `main` (or, equivalently, `qiskit-terra==0.22.0rc1`)
=> Fix deprecation warning for `deprecated_functionality`

qiskit/transpiler/passes/basis/unroll_3q_or_more.py, test/python/transpiler/test_unroll_3q_or_more.py
This commit fixes the handling of ControlFlowOps in the Unroll3QOrMore transpiler pass when the the control flow ops are in the basis set. Previously, the check for whether the operation was native to the target was done before recursing into the control flow block. This effectively skipped the conversion that should have happened in the block. To fix this the control flow operation handling is moved before the basis check. Later passes (mainly basis translation) will fail if the control flow operations aren't available on the target and we should always recursively unroll gates in this pass.
=> Fix handling of controlflow ops when control flow is in basis

qiskit/transpiler/passes/routing/stochastic_swap.py, qiskit/transpiler/passes/routing/utils.py, test/python/transpiler/test_stochastic_swap.py
The `StochasticSwap` pass has some fairly complex hand-offs between
different parts of its API, including in recursive calls and the regular
hand-off between Python and Rust.  In the course of adding the
control-flow support, some of these became muddled, and the mapping
between different virtual/physical/integer representations got mixed up,
resulting in invalid swaps being output in the final circuit.
This commit simplifies much of the internal mapping, removing many
superfluous `DAGCircuit` creations and compositions.  This also removes
instances where two layouts were "chained"; this was not well typed (the
output of a "virtual -> physical" mapping can't be the input for another
"virtual -> physical" mapping), and in general was being used to "undo"
some of compositions that were …
=> Fix control-flow routing in StochasticSwap

qiskit/transpiler/passes/routing/stochastic_swap.py, test/python/transpiler/test_stochastic_swap.py
If a control-flow block is not required to be entered (such as an "if" with no "else"), then it can't affect the layout in case the branch isn't taken.  This failure would have been clearer in a more control-flow-graph view of the circuit, but we don't yet have that, which is how this bug snuck through.  The case of "exit layout need not match entry layout" is really the special case for routing, which this commit makes a bit clearer.
This should also go into 0.22.
The diff looks funkier than it actually is - in reality, the old `_route_control_flow_looping` got removed, and `_route_control_flow_multiblock` (with the addition of a `maintain_layout` switch) got inlined into `_control_flow_layer_update`, since the split no longer made sense.
=> Fix StochasticSwap routing for if blocks with no else

qiskit/quantum_info/operators/symplectic/pauli_utils.py, releasenotes/notes/fix-pauli-basis-dep-27c0a4506ad38d2c.yaml
Fixes the removal of `pauli_list` kwarg of `pauli_basis` which broke existing code using the `pauli_list=True` future compatibility on upgrade to Qiskit Terra 0.22. This kwarg has been added back to the the function with a deprecation warning instead.
=> Fix pauli_basis deprecation

qiskit/qpy/binary_io/circuits.py, releasenotes/notes/fix-qpy-loose-bits-5283dc4ad3823ce3.yaml, test/python/circuit/test_circuit_load_from_qpy.py
A typo in clbit-reconstruction was generating the incorrect number of loose clbits in circuits that contained registers and loose bits, and had more qubits than clbits.  A bug elsewhere in the code caused circuits with _no_ registers to be deserialised as containing registers, since the `QuantumCircuit(int, int)` constructor actually does produce two registers (slightly surprisingly, perhaps).
=> Fix loose-bit handling in QPY

qiskit/qpy/binary_io/circuits.py, releasenotes/notes/fix-qpy-custom-controlled-gate-a9355df1a88a83a5.yaml, test/python/circuit/test_circuit_load_from_qpy.py
This commit fixes a bug in the QPY serialization of ControlledGate subclasses that defined custom _define() methods. The _define() method is the typical way to provide a custom definition in Gate classes. While ControlledGate class provides an alternative interface that handles custom control states at initialization, but the _define() interface is still valid even if it doesn't account for this. In #8571 we updated the QPY serialization code to use the _definition() method directly to correctly handle the open control case. But this fix neglected the case where people were providing definitions via the mechanism from Gate. This commit fixes this assumption by ensuring we load the definition that comes from _define() which will fix the serialization of these custom subclasses.
Fixes #8794
=> Fix qpy custom ControlledGate with overloaded _define()

qiskit/transpiler/passes/layout/dense_layout.py, qiskit/transpiler/target.py, releasenotes/notes/fix-global-inst-qarg-method-target-a9188e172ea7f325.yaml, test/python/transpiler/test_target.py
This commit fixes the handling in the target for working with instructions defined globally in the target. It adds handling to the operation_names_for_qargs() and operations_for_qargs() methods to build outputs that include globally defined operations instead of ignoring them. Additionally the add_instruction() method is updated to validate the input qargs to ensure that only valid qubits and qargs are allowed to be added to the target for an instruction.
Fixes #8914
=> Fix handling of globally defined operations in Target

qiskit/transpiler/passes/utils/barrier_before_final_measurements.py, releasenotes/notes/fix-barrier-before-final-measurements-loose-1849282c11fc5eb0.yaml, test/python/transpiler/test_barrier_before_final_measurements.py
We simply need to consider loose bits as well when constructing the new DAG layer.  This isn't `DAGCircuit.copy_empty_like` because we don't want things like metadata and global phase.
Fix #8923.
=> Fix `BarrierBeforeFinalMeasurements` with loose bits

qiskit/dagcircuit/dagnode.py, releasenotes/notes/fix-circuit-condition-compare-d8d85e5ca47c1416.yaml, test/python/circuit/test_circuit_operations.py, test/python/dagcircuit/test_dagcircuit.py
Previously, the `condition` of a given operation would not be converted into bit indices in order do the semantic-equality checking that the rest of the qargs and cargs get in a circuit.  This caused loose-bit comparisons to produce false negatives.
=> Fix single-bit-condition equality in QuantumCircuit and DAGCircuit

constraints.txt
These were added in #7174 and #7815.  Both Matplotlib and Sphinx have been updated several times since then, and should now be compatible.
=> Relax now-unneeded constraints

pyproject.toml
There appears to be an issue with memory consumption under the hood when using QEMU with Rust cargo: 
https://github.com/rust-lang/cargo/issues/10583.
This is causing the CI wheel workflow to run out of memory and fail for QEMU-based jobs, e.g.:
https://github.com/Qiskit/qiskit-terra/actions/runs/3244845622/jobs/5322060193#step:6:1964
Due to this issue the original release of Terra 0.22.0 never actually produced wheels for Linux aarch64, ppc64le, and s390x. A separate branch has been created to manually retrigger the 0.22.0 release wheel jobs, which have now completed successfully (also used in validating the changes in this PR).
https://github.com/Qiskit/qiskit-terra/compare/0.22.0...Qiskit:qiskit-terra:dnm-non-x86-64-wheels-retry?expand=1
From the discussion on the linked issue, the …
=> Fix QEMU-based Linux wheel jobs

qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py, releasenotes/notes/fix-sparse-pauli-real-63c31d87801671b1.yaml, test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
Fix `SparsePauliOp.dot` between operators with real coefficients.
To fix this, the `dtype` that `SparsePauliOp` can take is restricted to
`np.complex128` and `object`.
Fix #8992
=> Fix #8992 (SparsePauliOp.dot with real coefficients)

MANIFEST.in, releasenotes/notes/fix-styles-manifest-b8c852a07fb86966.yaml
Fixes #8991
This changes the entry for the `MANIFEST.in` file to point to `visualization/circuit/styles` for locating the built-in styles for the mpl circuit drawer. This bug was introduced in #8306.
=> Fix manifest entry for mpl styles

.azure/docs-linux.yml, .azure/lint-linux.yml, .azure/test-linux.yml, .azure/test-macos.yml, .azure/tutorials-linux.yml
This commit removes the pip cache in azure pipelines t improve the reliability of the CI jobs. Right now the pip cache has grown to be > 4GB and we're seeing a high rate of the step bogging down while downloading the data. Running with a cache in practice has proven to be quite unreliable and just pulling packages from pypi appears to be significantly faster.
=> Remove pip cache in azure pipelines jobs

qiskit/transpiler/target.py, releasenotes/notes/fix-transpile-ideal-measurement-c37e04533e196ded.yaml, test/python/compiler/test_transpiler.py
This commit fixes an oversight in the transpile() function when running with a Target (either directly or via a backend) that contains a Measurement operation that is ideal (either globally or locally) with no properties defined. This was not handled correctly in the function used to convert a Target to a BackendProperties payload for passes that are not yet target aware and this would cause an exception to be raised. This commit fixes this edge case and excludes readout properties from the generated BackendProperties in this case.
Fixes #8969
=> Fix transpile() with a Target containing an ideal Measure

qiskit/circuit/library/standard_gates/equivalence_library.py, releasenotes/notes/add-xxyy-equivalence-a941c9b9bc60747b.yaml, test/python/circuit/test_gate_definitions.py
These are just copied from the `_define` method on the classes.  The equivalence-library tests are updated (since `subTest` doesn't isolate correctly with `testtools`) to print out all the names of the tests being run, so it's clear that the existing test now tests these definitions.
Bonus points to anyone who already knew the esoteric Python scoping rules that forbade me from using a list comprehension to define the test parametrisation here.
=> Add missing equivalences for XX{Plus,Minus}YYGate

test/python/opflow/test_aer_pauli_expectation.py
This triggered semi-reliably on Windows with all optional packages installed, with the output different by 2 ULP.  It's a floating-point equality check, so what we care about asserting is approximate equality, not exact.
Turned up by #8967.
=> Fix exact floating-point comparison causing flaky test

qiskit/circuit/random/utils.py, releasenotes/notes/speedup-random-circuits-8d3b724cce1faaad.yaml, test/python/circuit/test_random_circuit.py
There is no need to use the slower `append` (which adds a lot of checking overhead for large circuits) since we fully control the construction of the circuit.
This also overhauls all the randomisation components to produce all the necessary randomness for a given layer in a single go.  This massively reduces the Python-space and Numpy-dispatch overhead of the nested loop.
The changes to the randomisation in this new form mean that on average, more gates will be generated per circuit, because the output will choose 1q gates more frequently than it chooses 2q, which in turn will be more frequent than 3q, but each layer of the "depth" still has to involve every qubit.  The change is because the likelihood of choosing a gate with a given number of qubits is now proportional to how many …
=> Speed up `random_circuit`

qiskit/transpiler/passes/layout/vf2_post_layout.py
This commit fixes a few copy paste errors and errors in the docstring for the VF2PostLayout pass. It also adds a a link to the paper for the pass.
This was originally part of #9026 as these fixes were part of modifying the docstring to document the new feature being added in that PR. This commit just extracts those docstring fixes from that PR.
=> Fix up docstring for VF2PostLayout

Cargo.lock, Cargo.toml
Since our MSRV for the Rust code in Qiskit is 1.56.1 we can set the Rust editions [1] to Rust Edition 2021 [2]. This will enable us to leverage newer syntax features in the rust code. This commit bumps the rust edition from 2018 to 2021.
[1] https://doc.rust-lang.org/edition-guide/editions/index.html
[2] https://doc.rust-lang.org/edition-guide/rust-2021/index.html
=> Set Rust edition to 2021

qiskit/compiler/transpiler.py, qiskit/transpiler/preset_passmanagers/common.py, qiskit/transpiler/preset_passmanagers/level0.py, qiskit/transpiler/preset_passmanagers/level1.py, qiskit/transpiler/preset_passmanagers/level2.py, qiskit/transpiler/preset_passmanagers/level3.py, releasenotes/notes/toqm-extra-0.1.0-4fedfa1ff0fedfa0.yaml, requirements-dev.txt, setup.py
Qiskit TOQM is now available as a `PassManagerStagePlugin` as of version `0.1.0`.
Removes special casing previously needed to use TOQM routing from preset pass managers.
The TOQM integration, namely `optionals.HAS_TOQM`, the advertised `"toqm"` extra and unit testing conditioned on the TOQM module's presence are left intact.
=> Use TOQM routing staged pass manager.

qiskit/transpiler/passes/layout/vf2_post_layout.py, releasenotes/notes/fix-vf2post-regression-d4b057ea02ce00d3.yaml
The `add_nodes` call should be outside the loop; inside, it adds nodes quadratically.  This commit also squashes a minor inefficiency in set allocation.
I couldn't immediately think of a sensible test for this, since the internal graph isn't really accessible.
=> Fix incorrect graph construction in VF2PostLayout

requirements-dev.txt, test/python/transpiler/test_preset_passmanagers.py
In #9042 we removed the special case code to enable using toqm as an optional routing method. This was needed prior to qiskit-terra 0.22.0 as we didn't have the transpiler stage plugin interface. However, now that we've added a dedicated interface for external transpiler passes to integrate into transpile() the toqm passes are using that interface. However, in #9042 the tests for verifying the previously hard-coded toqm routing method path worked as before were left intact. In general this would be a good approach to ensure we're maintaining backwards compatibilty with the new modular interface with earlier releases. However, in this specific case this is causing an issue with how tests are run. Since qiskit-toqm has a necessary dependency on qiskit-terra this means when we install our …
=> Remove qiskit-toqm tests and requirements-dev.txt entry

qiskit/__init__.py, qiskit/transpiler/passes/routing/sabre_swap.py, qiskit/transpiler/passes/routing/stochastic_swap.py, src/lib.rs, src/nlayout.rs, src/stochastic_swap.rs
This commit moves the NLayout rust class out of the stochastic swap python module into a new standalone nlayout module in qiskit._accelerate. The NLayout class was originally added with the stochastic swap rust code, but since then it's started being used by other rust code including SabreSwap (and soon to be VF2Layout and VF2PostLayout scoring in #9026).
=> Split out NLayout rust class into standalone Python module

qiskit/primitives/backend_estimator.py, releasenotes/notes/fix-backend-primitive-no-max-experiments-e2ca41ec61de353e.yaml, test/python/primitives/test_backend_estimator.py
The ``max_experiments`` field in the BackendConfiguration for a BackendV1 backend is not a required field. While in practice most real backends set it, some simulators (including aer) do not. This causes a failure when using the Backend primitive classes with these backends as we were previously assuming the ``max_experiments`` attribute was always present.
=> Fix Backend primitive classes for BackendV1 with no max_experiments

qiskit/circuit/quantumcircuit.py, test/python/circuit/test_circuit_operations.py
=> add qubits and clbits args to QuantumCircuit.from_instructions

qiskit/algorithms/eigensolvers/numpy_eigensolver.py, qiskit/algorithms/minimum_eigensolvers/numpy_minimum_eigensolver.py, qiskit/algorithms/minimum_eigensolvers/sampling_vqe.py, test/python/algorithms/minimum_eigensolvers/test_qaoa.py
Small fix of the TypeHints in the `NumPyEigensolverResult` and `NumPyMinimumEigensolverResult` from `np.ndarray` to `list[Statevector]` and `Statevector`, respectively.
=> Fix NumPy(Minimum)EigensolverResult typehints

constraints.txt
The recent release of jupyter-core 5.0.0 started emitting a deprecation warning during the image comparison tests which is causing a failure caused by usage in seasborn via ipywidgets. To workaround this in the short term this commit set a constraint on the jupyter-core version. We should remove this pin after seaborn and ipywidgets are updated, or we add an explicit warning exclude to the test suite.
=> Pin jupyter-core to < 5.0.0

qiskit/extensions/quantum_initializer/squ.py, test/python/circuit/test_squ.py
Coveralls had been complaining about `/qiskit/extensions/quantum_initializer/squ.py` unstable coverage. For [example](https://coveralls.io/builds/53938134/source?filename=qiskit%2Fextensions%2Fquantum_initializer%2Fsqu.py#L142):
There was a missing seeding in a test. I also moved it to ddt.
=> Stabilising  test_squ

qiskit/namespace.py
This PR ports a fix from https://github.com/Qiskit/rustworkx/pull/728 that fixes the following `ImportWarning` under `Python>=3.10`
```console
ImportWarning: QiskitLoader.exec_module() not found; falling back to load_module()
```
Some further context can be found in the corresponding retworkx PR https://github.com/Qiskit/rustworkx/pull/728.
The underlying code was introduced in https://github.com/Qiskit/qiskit-terra/pull/5089.
Fixes https://github.com/Qiskit/qiskit-terra/issues/8853.
=> 🐛 fix deprecated `Loader.load_module()`

src/sabre_swap/mod.rs
This should not meaningfully affect any small-scale outputs, but at larger scales, there are floating-point instabilities that can make the "best swaps" set miss swaps that are logically at the same score as others.  This does not (cannot) fully stabilise us against all minor floating-point rounding errors in calculations; the order of iteration through the swaps can still technically change the swap set, for example if three swaps with relative differences `{0, 0.8, 1.6} * BEST_EPSILON` are encountered in a different orders.  The float epsilon is chosen to be significantly larger than the actual magnitude of fluctuations, and significantly smaller than the changes caused by all the actual components of scoring, in order to mitigate this effect.
This detail is (to the best of my …
=> Use float-epsilon calculation in Sabre best scores

qiskit/transpiler/passes/routing/sabre_swap.py, releasenotes/notes/fix-sabre-swap-random-seed-dcf3dace63042791.yaml, src/sabre_swap/mod.rs
This commit fixes an issue in the case no random seed is provided by the user when initializing an instance of SabreSwap. The pass was previously potentially reusing the random seed between runs even if no seed was specified. This was an artifact of storing the initial seed as an instance variable. Instead this commit just relies on the the Rust RNG to initialize from entropy if no seed is specified.
=> Fix random seed initialization between runs in SabreSwap

.azure/lint-linux.yml
Right now the lint CI job runs a number of scripts and commands which do not print any output unless there is an error, while other commands always print to stdout even on success. This can be confusing if a command towards the end prints error output after normal stdout from earlier commands. For example, this was the output from a recent failed CI run:
```
------------------------------------
Your code has been rated at 10.00/10
Checking cfg-if v1.0.0
Checking scopeguard v1.1.0
Checking once_cell v1.16.0
Checking either v1.8.0
Checking smallvec v1.10.0
Checking ppv-lite86 v0.2.16
Checking rawpointer v0.2.1
Checking unindent v0.1.10
Checking fixedbitset v0.4.2
Checking matrixmultiply v0.3.2
Checking libc v0.2.137
Checking crossbeam-utils v0.8.12
Checking libm v0.2.5
Checking memoffset …
```
=> Add debug prints to lint CI job

qiskit/circuit/library/n_local/n_local.py, releasenotes/notes/initial_state-8e20b04fc2ec2f4b.yaml
PR #6585 deprecated the support for non-`QuantumCircuit` in the `initial_state` parameter of `NLocal`. That deprecation was introduced in 0.18 (released in July 2021) and it is time to remove it.
=> Removed NLocal inital_state that is not a QuantumCircuit

qiskit/pulse/instructions/instruction.py, releasenotes/notes/reinstate-pulse-instruction-draw-7bf4bbabaa1f1862.yaml
This was erroneously broken by gh-8306 and not detected by lint because of the existence of `qiskit.visualization.__getattr__`.  This reinstates the functionality using the deprecated old instruction drawers.
I'm using the deprecated functionality, achieved by inlining what the old `pulse_drawer` (v1) code did for this path, because the paths in use haven't been triggering their deprecation warnings properly due to `stacklevel` issues, so are not eligible for immediate removal.  This PR is stable for backport (fixes a bug in the deprecation period), and I'll follow it with a PR for 0.23 that applies the deprecations to the v1 pulse drawer (and this method) correctly.
=> Reinstate `pulse.Instruction.draw`

qiskit/primitives/utils.py, releasenotes/notes/fix-primitives-numpy-parameters-1589d997864dfb37.yaml, test/python/primitives/test_sampler.py
=> Fix the bug primitives cannot handle circuits with ndarray parameters

qiskit/visualization/__init__.py, releasenotes/notes/remove-visualization-optionals-e4c3ed415bc1bbbe.yaml
These were deprecated in 0.21, since the lazy optional checkers in `qiskit.utils.optionals` became available.
=> Remove deprecated redirects from visualization

qiskit/algorithms/gradients/finite_diff_estimator_gradient.py, qiskit/algorithms/gradients/finite_diff_sampler_gradient.py, releasenotes/notes/gradient-methods-b2ec34916b83c17b.yaml, test/python/algorithms/gradients/test_estimator_gradient.py, test/python/algorithms/gradients/test_sampler_gradient.py
=> Add gradient methods to FinDiffGradients

qiskit/primitives/utils.py
Since `to_list` is slow, this improves the performance issue.
Question:
Does this PR have `stable backport potential`?
=> Improve performance of _observable_key in Primitives

qiskit/algorithms/minimum_eigensolvers/adapt_vqe.py, releasenotes/notes/adapt-vqe-supports-aux-operators-1383103839a338c6.yaml, test/python/algorithms/minimum_eigensolvers/test_adapt_vqe.py
`AdaptVQE` does indeed support aux operators but did not overwrite the default classmethod of the `MinimumEigensolver` interface. This PR fixes that.
=> fix: overwrite `AdaptVQE.supports_aux_operators`

requirements-dev.txt
`jaxlib` released Python 3.11 wheels as of 0.3.24 on 2022-11-04, so we can release our pin on the constraint in `requirements-dev.txt`.
=> Unpin jaxlib Python-version constraints

qiskit/quantum_info/synthesis/one_qubit_decompose.py, qiskit/quantum_info/synthesis/two_qubit_decompose.py, test/python/circuit/test_circuit_qasm.py, test/python/transpiler/test_dynamical_decoupling.py
This commit updates the det() function used for computing the determinant of the unitary used as part of the calculation of one and two qubit unitary deocmposers. It is now using the numpy linalg module's det() function. Previously it was using the function from scipy which required a runtime import and also marginally slower under cProfile (which might be a red herring because of profiler overhead as scipy has more python space calls). This also standardizes the det() call usage in the module as other places were already using the numpy version of the function.
=> Use numpy.linalg.det instead of scipy's function

azure-pipelines.yml
This had got triggered again by something, and since the upstream requirements of qiskit-toqm have changed, it was impossible for any jobs to even install, and so this was just failing every night. This commit disables the cron for the old branch.
=> Disable cron CI on old stable branch

src/error_map.rs, test/python/transpiler/test_vf2_layout.py
The pickle method previously attempt to expose the natural type of the state of the `ErrorMap` struct to Python to handle the pickling, which is `HashMap<[usize; 2], f64>`.  Unfortunately, PyO3 has a recursive `ToPyObject` conversion for `HashMap`, which causes the `[usize; 2]` to be converted to `list[int]`, which is unhashable, causing a panic. There are sufficient traits for conversion from Python to Rust that we can _accept_ the natural type, but for Rust to Python, we have to manually convert.
No reno bugfix because the feature hasn't been released, but it's a logical bugfix for the developer track, hence the label.
Fix #9199.
=> Fix pickle of Rust `ErrorMap` struct

qiskit/quantum_info/states/quantum_state.py, releasenotes/notes/probabilities_dict_bug_fix-aac3b3d3853828dc.yaml, test/python/quantum_info/states/test_densitymatrix.py, test/python/quantum_info/states/test_statevector.py
Closes #9210
The solution to #9210 was pointed out by @chriseclectic : the `dims` attribute (giving a list of subsystem dimensions) needed to be reversed in one place in the `QuantumState._subsystem_probabilities` method. This explains why it worked for states where all subsystems were of equal dimension: reversing `dims` has no effect in this case.
This PR includes tests validating correct functioning of `QuantumState.probabilities_dict` in the case that `dims` contains unequal dimensions.
=> Fix ordering of dims in QuantumState.probabilities_dict

qiskit/transpiler/passes/synthesis/unitary_synthesis.py
By accident I ran into some small formatting and spelling issues in `qiskit/transpiler/passes/synthesis/unitary_synthesis.py`.
=> some doc formatting issues in passes/synthesis/unitary_synthesis.py

test/python/algorithms/minimum_eigensolvers/test_sampling_vqe.py
I noticed `TestSamplerVQE` sometimes fails as follows. This PR fixes the random seed of the test.
```
======================================================================
FAIL: test_ansatz_resize_1 (test.python.algorithms.minimum_eigensolvers.test_sampling_vqe.TestSamplerVQE)
test.python.algorithms.minimum_eigensolvers.test_sampling_vqe.TestSamplerVQE.test_ansatz_resize_1
----------------------------------------------------------------------
testtools.testresult.real._StringException: Traceback (most recent call last):
File "/Users/ima/envs/dev39/lib/python3.9/site-packages/ddt.py", line 220, in wrapper
return func(self, *args, **kwargs)
File "/Users/ima/tasks/2_2022/qiskit/terra/test/python/algorithms/minimum_eigensolvers/test_sampling_vqe.py", line 120, in test_ansatz_resize …
```
=> Fix the random seed for `TestSamplerVQE`

qiskit/quantum_info/synthesis/one_qubit_decompose.py, qiskit/transpiler/passes/optimization/optimize_1q_commutation.py, qiskit/transpiler/passes/optimization/optimize_1q_decomposition.py, releasenotes/notes/use_dag-one-qubit-euler-decomposer-6df00931384b14bd.yaml, test/python/transpiler/test_optimize_1q_decomposition.py
This commit adds a new option to the euler one qubit decomposer class,
use_dag, which when set to True will return a DAGCircuit object for the
decomposed matrix instead of a QuantumCircuit object. This is useful for
transpiler passes that call the decomposer so that they don't have to
convert from a circuit to a dag. The passes that use the decomposer are
also updated to use this new option.
This was originally attempted before in #5926 but was abandoned because
at the time there was no real performance improvement from doing this.
However, since then this class has changed quite a bit, and after #9185
the overhead of conversion between QuantumCircuit and DAGCircuit is a
more critical component of the runtime performance of the 1 qubit
optimization pass. By operating natively in …
=> Add DAGCircuit output option to OneQubitEulerDecomposer

qiskit/algorithms/minimum_eigensolvers/diagonal_estimator.py, qiskit/algorithms/minimum_eigensolvers/sampling_vqe.py, releasenotes/notes/fix-sampling-vqe-aggregation-107e3983147c57bc.yaml, test/python/algorithms/minimum_eigensolvers/test_sampling_vqe.py
In the `SamplingVQE` the aggregation was not passed to the `_DiagonalEstimator` and therefore had no effect! 
Also fixed  a bug in the CVaR aggregation function, which overshot the expected value and improved the docs to include an explanation how a custom aggregation should look like.
Thanks @t-imamichi for finding the bug!
=> Fix the ``aggregation`` argument of ``SamplingVQE``

qiskit/algorithms/minimum_eigensolvers/diagonal_estimator.py, releasenotes/notes/fix-sampling-vqe-performance-b5bfe92c2d3e10ab.yaml
I notice that `SamplingVQE` is slower than the former `VQE` when I update a tutorial of Qiskit optimization.
The bottleneck is `_DiagonalEstimator._evaluate_sparsepuali`. See https://github.com/Qiskit/qiskit-optimization/pull/448#discussion_r1037868880 for details.
I optimized that part with numpy.
microbenchmark
```python
from qiskit.algorithms.minimum_eigensolvers.diagonal_estimator import _evaluate_sparsepauli
from qiskit.quantum_info import SparsePauliOp
from qiskit.quantum_info.random import random_pauli_list
seed = 123
n = 100
m = 100
op = SparsePauliOp(random_pauli_list(num_qubits=n, size=m, seed=seed))
print(_evaluate_sparsepauli(2<<n-1, op))
print(f'{timeit(lambda: _evaluate_sparsepauli(2<<n-1, op), number=100)} sec')
```
main
```
(-2+4j) …
```
=> Performance improvement of `_DiagonalEstimator`

qiskit/primitives/backend_sampler.py, releasenotes/notes/fix-backend-sampler-890cbcf913667b08.yaml, test/python/algorithms/minimum_eigensolvers/test_sampling_vqe.py, test/python/primitives/test_backend_sampler.py
`BackendSampler` raises an error if two `run`s are called sequentially as follows. This PR fixes the issue.
This PR is straightforward. So, it might be better to skip circuits that are already transpiled.
```python
from qiskit import Aer, QuantumCircuit
from qiskit.primitives import BackendSampler
sampler = BackendSampler(Aer.get_backend('aer_simulator'))
qc1 = QuantumCircuit(1,1)
qc1.h(0)
qc1.measure(0, 0)
qc2 = QuantumCircuit(1,1)
qc2.x(0)
qc2.measure(0, 0)
print(sampler.run([qc1]).result())  # OK
print(sampler.run([qc2]).result())  # NG
```
output
```
SamplerResult(quasi_dists=[{1: 0.5078125, 0: 0.4921875}], metadata=[{'shots': 1024}])
File "/home/ima/github/qiskit/terra/tmp/backendsampler.py", line 14, in <module>
print(sampler.run([qc2]).result()) …
```
=> Fix a transpile issue of BackendSampler

qiskit/quantum_info/states/statevector.py, test/python/quantum_info/states/test_statevector.py
This is a follow up to #8807 which provided a significant speedup if `Statevector` handled `Initialize` instructions -- however this PR didn't correctly account for initializations on a subpart of the qubits and returned a shrunken statevector! This PR fixes this and adds a test. 
This causes a Qiskit ML tutorial to fail, thanks @manoelmarques for finding it! Also, since #8807 is not yet released, no reno is included (and no backport required 🙂).
=> Handle `Initialize` on subsystem in `Statevector`

qiskit/circuit/qpy_serialization.py, releasenotes/notes/deprecate-old-qpy-d39c754d82655400.yaml, test/python/circuit/test_circuit_load_from_qpy.py, test/qpy_compat/test_qpy.py
This includes a try/except for the old name in the backwards compatibility tests because we still need that test file to succeed against old versions of Terra to generate the old files.
=> Deprecate old path to QPY

qiskit/algorithms/gradients/lin_comb_sampler_gradient.py, qiskit/algorithms/gradients/utils.py, releasenotes/notes/fix-libcomb-sampler-gradient-d759d6b0e2659abe.yaml
`LinCombSamplerGradient` raises errors with `AerSampler`. This PR fixes the issue.
Note that `AerSampler` of 0.11.2 has an issue https://github.com/Qiskit/qiskit-aer/issues/1679. Need to run the following script with Aer 0.11.1.
```python
from qiskit import QuantumCircuit, BasicAer
from qiskit.circuit import Parameter
from qiskit.primitives import Sampler, BackendSampler
from qiskit_aer.primitives import Sampler as AerSampler
from qiskit.algorithms.gradients import LinCombSamplerGradient
a = Parameter("a")
qc.rxx(a, 0, 1)
qc.measure_all()
for sampler in [Sampler(), AerSampler()]:
gradient = LinCombSamplerGradient(sampler)
result = gradient.run([qc], [[1]], shots=1000).result()
print(sampler)
print(result)
```
main
```
<qiskit.primitives.sampler.Sampler object at …
```
=> Fix `LinCombSamplerGradient` to leverage `AerSampler`

constraints.txt, requirements-dev.txt
ipywidgets 8.0.3 (released on Dec 7 [link](https://pypi.org/project/ipywidgets/8.0.3/#history)) raises a deprecation warning as follows.
```
======================================================================
ERROR: test_plot_error_map_over_100_qubit_backend_v2 (test.python.visualization.test_gate_map.TestGateMap)
test.python.visualization.test_gate_map.TestGateMap.test_plot_error_map_over_100_qubit_backend_v2
----------------------------------------------------------------------
testtools.testresult.real._StringException: Traceback (most recent call last):
File "/Users/ima/tasks/2_2022/qiskit/terra/test/python/visualization/test_gate_map.py", line 151, in test_plot_error_map_over_100_qubit_backend_v2
fig = plot_error_map(backend)
File …
```
=> Pin ipywidgets

azure-pipelines.yml
The CI jobs on both Mac and Linux fail with Python 3.11.1, see also #9291. While this is not a fix, using Python 3.11.0 can unblock the CI until we track down the issue that seems to be coming from wrapping `TestClass`.
Not actually sure if this works, so this PR tests the fix by triggering the CI.
=> [Test] Pin maximum python version in CI to <3.11.1

constraints.txt, qiskit/algorithms/optimizers/snobfit.py, qiskit/circuit/instruction.py, qiskit/quantum_info/operators/channel/kraus.py, requirements-dev.txt, test/python/algorithms/optimizers/test_optimizers_scikitquant.py, test/python/test_util.py
* In the 1.24.0 release, NumPy followed through on deprecating the creation of arrays with elements differing in size (like `np.array([[1,2], [3]])`, which broke several tests. This PR fixes each of these, with the exception of the `SNOBFIT` optimizer. There we rely on github.com/scikit-quant and the compatibility needs to be fixed there. Until then, the `SNOBFIT` optimizer will raise a `QiskitError` if used with NumPy 1.24.0 or above and the tests are skipped.
* Pin `coverage` to below 7.0.0 (released Dec 18th) which breaks with Python 3.8 due to a missing import of
```
File "/opt/hostedtoolcache/Python/3.8.15/x64/bin/coveragepy-lcov", line 5, in <module>
from coveragepy_lcov.cli import main
File …
```
=> Fix NumPy 1.24.0 compatibility and pin `coverage<7.0`

tox.ini
With the recent merge of #9346 that stopped using the problematic jupyter-sphinx plugin we're no long blocked from running sphinx-build in parallel anymore. We had originally enabled this in #4477 to get a speed boost during docs builds. However, we were forced to revert that in #6539 because jupyter-sphinx was unreliable and had a race condition when 2 jupyter-execute blocks were run at the same time (see #5904 for more details). Since we've removed the jupyter-sphinx usage that is no longer a problem and we can reliably run parallel sphinx builds again. This commit makes that change and changes the default sphinx-build behavior when run via tox (as is done via ci) to use all available system cores to perform a sphinx build. Annecdoteally this provides a nice speed up, on my local …
=> Re-enable parallel sphinx builds by default

qiskit/pulse/__init__.py, qiskit/pulse/library/__init__.py, qiskit/pulse/library/symbolic_pulses.py, qiskit/qobj/converters/pulse_instruction.py, releasenotes/notes/gaussian-square-drag-pulse-1e54fe77e59d5247.yaml, test/python/pulse/test_pulse_lib.py
Add GaussianSquareDrag symbolic pulse shape
Add new `qiskit.pulse.GaussianSquareDrag` pulse shape. This pulse
shape is similar to `qiskit.pulse.GaussianSquare` but uses the
`qiskit.pulse.Drag` shape during its rise and fall. The correction
from the DRAG pulse shape can suppress part of the frequency spectrum of
the rise and fall of the pulse which can help avoid exciting spectator
qubits when they are close in frequency to the drive frequency of the
pulse.
`GaussianSquareDrag` is sometimes used on IBM backends and its absence from qiskit requires those backends to report calibrations using the pulse with `Waveform`s instead of `SymbolicPulse` which obscures the parameters and is less efficient to transfer.
Depending on the timing, either this PR or #9314 will need to be updated to account …
=> Add GaussianSquareDrag symbolic pulse shape

qiskit/algorithms/eigensolvers/numpy_eigensolver.py, qiskit/algorithms/minimum_eigensolvers/numpy_minimum_eigensolver.py, qiskit/quantum_info/operators/operator.py, releasenotes/notes/fix-numpy-eigensolver-sparse-pauli-op-b09a9ac8fb93fe4a.yaml, test/python/algorithms/eigensolvers/test_numpy_eigensolver.py, test/python/algorithms/minimum_eigensolvers/test_numpy_minimum_eigensolver.py, test/python/quantum_info/operators/test_operator.py
Fixes an issue where `NumPyEigensolver` and by extension `NumPyMinimumEigensolver` did not support all `BaseOperator` instances, in particular `SparsePauliOp`. This was because it required the data attribute, which `Operator` exposes but e.g. `SparsePauliOp` does not. Closes #9091.
For all `BaseOperator` child classes, other than `Operator`, `to_matrix` is used to get the `NumPy` matrix for the operator and compute the eigenvalues and eigenstates. If an `Operator` instance, we still use `data`.
Additionally this PR:
* Refactors `NumPyEigensolver` to be stateless w.r.t. results. I.e. the result is no longer stored.
* Adds unit tests to check `NumPyEigensolver` with `SparsePauliOp`s.
* Adds units tests to check `NumPyMinimumEigensolver` with `SparsePauliOp`s and `Operator`s.
* Uses sparse …
=> Fix `NumPyEigensolver` with `SparsePauliOp`

test/python/transpiler/test_unitary_synthesis.py
The test_qv_natural UnitarySynthesis test is designed to test that when the pulse efficient flag is set on the default unitary synthesis plugin for the UnitarySynthesis pass the output from synthesis is only emitting entangling gates in the natural direction implemented on the target. However, when running on Windows with Python 3.11 and numpy 1.24 we're seeing a non-zero failure rate (in CI it's ~5% across all jobs) of this test likely do to fp precision. When this failure occurs it appears as the failure from detailed in issues #5832, #9177, and others as the test was creating a pass manager that mirrors the optimization loop used in the preset pass managers. The optimization loop is failing to converge on a fixed depth as the unitary synthesis is oscillating between multiple equivalent …
=> Simplify UnitarySynthesis pass test test_qv_natural

.azure/test-linux.yml, constraints.txt, qiskit/test/base.py
These were originally added in #9105 and #9272 respectively, but the original problem package `seaborn` has released since then, which may have fixed things.
If this isn't sufficient, we can consider adding manual suppressions instead; the various parts of the Jupyter stack in the past have shown some apathy towards fixing warnings being emitted from low-level packages if they wouldn't be displayed to users by default, so the wait for fixes can be long.
=> Relax constraints on jupyter-core and ipywidgets

.azure/test-linux.yml, .github/workflows/coverage.yml, constraints.txt, qiskit/algorithms/optimizers/snobfit.py, qiskit/circuit/instruction.py, qiskit/quantum_info/operators/channel/kraus.py, qiskit/test/base.py, qiskit/utils/classtools.py, releasenotes/notes/wrap-method-311-147d254d4b40e805.yaml, requirements-dev.txt, test/python/algorithms/optimizers/test_optimizers_scikitquant.py, test/python/test_util.py, test/python/utils/test_classtools.py
This is a manual collection of several backport PRs that need to be merged in one go to fix the CI on the stable branch.  The bases of those PRs are:
- #9305
- #9310
- #9361 
- #9364
Close #9313
Close #9358
=> Fix stable tests

constraints.txt, requirements-dev.txt
The 1.21.0 release appears to have changed the spacing in its outputs, which is causing a bunch of Sphinx/docutils warnings for some of our docstrings.
=> Pin sphinx-autodoc-typehints

constraints.txt
Version 1.21.1 was recently released, which fixes the spacing bug introduced in 1.21.0.
See tox-dev/sphinx-autodoc-typehints#294.
=> Relax pin on sphinx-autodoc-typehints

requirements-dev.txt
The 1.23.4 release of ``sphinx-autodoc-typehint`` broke the docs build of the CI.
The build errors with
```
reading sources... [  3%] apidocs/algorithms .. stubs/qiskit.algorithms.SciPyImaginaryEvolver
:26: (ERROR/3) no path specified
:26: (ERROR/3) no path specified
File "/home/vsts/work/1/s/.tox/docs/lib/python3.9/site-packages/sphinx/cmd/build.py", line 281, in build_main
app.build(args.force_all, args.filenames)
File "/home/vsts/work/1/s/.tox/docs/lib/python3.9/site-packages/sphinx/application.py", line 347, in build
self.builder.build_update()
File "/home/vsts/work/1/s/.tox/docs/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 310, in build_update
self.build(to_build,
File "/home/vsts/work/1/s/.tox/docs/lib/python3.9/site-packages/sphin …
```
=> Pin ``sphinx-autodoc-typehint``

Cargo.lock, Cargo.toml, qiskit/transpiler/passes/layout/sabre_layout.py, qiskit/transpiler/passes/routing/sabre_swap.py, src/results/marginalization.rs, src/sabre_layout.rs, src/sabre_swap/mod.rs
The latest releases of PyO3 and rust numpy were just released. The changelogs for both can be found at:
https://pyo3.rs/v0.18.0/changelog
and
https://github.com/PyO3/rust-numpy/blob/main/CHANGELOG.md
Since the two releases are tightly coupled this commit opts to update them together instead of the normal dependabot workflow. Similarly some of our usage (mainly around signatures and argument ordering) for building a python interface using PyO3 has been deprecated. That usage is also updated in this PR to avoid compilation warnings, which will be treated as errors by clippy in CI.
=> Update PyO3 and Rust Numpy to 0.18.0

qiskit/transpiler/passes/calibration/rzx_builder.py, test/python/transpiler/test_calibrationbuilder.py
In the recently merged #9343 support for using the Target directly was added to the RZXCalibrartionBuilder family of passes. However, test coverage in that PR was omitted by mistake for that pass (other passes in the PR were covered). There was a bug in the code change introduced in that PR which caused an error on initialization if a target were specified without an InstructionScheduleMap (which was the intent of the new target kwarg). This commit fixes the logic bug in the pass and adds test coverage to ensure specifying only a target continues to work moving forward.
=> Add missing test coverage for RZXCalibration builder with target

qiskit/opflow/primitive_ops/pauli_op.py, releasenotes/notes/fix-PauliOp-adjoint-a275876185df989f.yaml, test/python/opflow/test_op_construction.py
- Resolve #9433
- Add test for `PauliOp.adjoint()`
=> Fix `PauliOp.adjoint()`

qiskit/transpiler/passes/synthesis/graysynth.py, qiskit/transpiler/synthesis/__init__.py, qiskit/transpiler/synthesis/graysynth.py, test/python/synthesis/test_gray_synthesis.py
This commit reverts a breaking change made in #8568, in that PR the graysynth module was moved to the qiskit.synthesis package and the cnot_synth function was also renamed as part of the move. However, this change would break any existing users of the module without any warning. To fix this for the 0.23.0 release this commit adds back the graysynth module and just exports the contents of the module in its new location. Additionally, a small wrapper function is added so that the legacy cnot_synth function name can continue to be used for the time being. In the 0.24.0 cycle we can deprecate the old module and remove them after we've giving users a warning about the change.
=> Add back qiskit.transpiler.passes.synthesis.graysynth module

.azure/docs-linux.yml
The most recent release tox, 4.4.0, changed the behavior of how tox interacts with constraints files. It is raising an error because it doesn't like the format of our constraints file in qiskit. This commit works around this by pinning our tox version. Given that we're preparing to release 0.23.0 pinning is the fastest solution in the short term, we can adjust things after the release is out.
=> Pin tox version in CI

requirements-dev.txt
This commit adds a tweedledum to the requirements-dev.txt list. Since the release of qiskit-terra 0.23.0 the CI docs job has started to fail. This is because tweedledum is a requirement for the classicalfunction compiler docs. It turns out we were getting tweedledum installed in docs build jobs via a weird path. The install order for docs build was installing packages that require qiskit-terra before terra itself was being installed. This would cause qiskit-terra from pypi from being isntalled first, and old versions of terra required tweedledum which would install it. Then we'd later upgrade terra to the current version under test. To fix this in the short term this adds add tweedledum to the requirements list so we unblock CI. One thing to note is that since the primary reason we …
=> Add tweedledum to requirements-dev.txt

qiskit/pulse/calibration_entries.py, releasenotes/notes/fix-instmap-add-with-arguments-250de2a7960565dc.yaml, test/python/pulse/test_instruction_schedule_map.py
This is a followup PR of #8885 for (edge case) bug fix. When `InstructionScheduleMap.add` is called with `arguments` and non-picklable value is specified (such as python dict key), parallel transpile will fail with the inst map due to this line.
https://github.com/Qiskit/qiskit-terra/blob/a3b359b899d5d963272a7b424c8a283bc6bd4c0d/qiskit/compiler/transpiler.py#L365-L368
See new test case for code to reproduce the bug. This PR typecast `arguments` to python list so that any iterable is stored in the picklable format.
=> Manage edge case of pickling instmap.

qiskit/circuit/register.py, releasenotes/notes/fix-register-name-format-deprecation-61ad5b06d618bb29.yaml, test/python/circuit/test_register.py
This inadvertantly made the class attribute accessible only from instances.  It's no use for this to only be on instances, since you historically needed to validate against the regex to be sure the instance initialisation would succeed.
Fix #9493
=> Fix bad deprecation of Register.name_format

qiskit/providers/backend_compat.py, releasenotes/notes/fix-backendv2converter-de342352cf882494.yaml
I found and fixed bugs of `BackendV2Converter`.
Important and critical bugs to use BackendV2Converter.
=> Bug fix property and methods of BackendV2Converter

qiskit/algorithms/state_fidelities/compute_uncompute.py, releasenotes/notes/computeuncompute-local-fidelity-501fe175762b7593.yaml, test/python/algorithms/state_fidelities/test_compute_uncompute.py
Adds a flag `average_local` to the `ComputeUncompute` state fidelity class that allows to compute the local fidelity, which is defined by averaging over single-qubit projectors. It has been shown that global observables, such as the global projector used in the standard fidelity, lead to cost-function induced barren plateaus that can be mitigated by employing a local cost-function instead [1].
While this local fidelity cannot replace the global fidelity in all use cases, it coincides with the global version in the case that the fidelity is 1. This is especially useful in algorithms where the fidelity is maximised variationally, such as for example in p-VQD.
I added a unit test for the case where the fidelity is 1. Open for suggestions for further unit tests if anyone has an idea of an …
=> Local fidelity

qiskit/visualization/pass_manager_visualization.py
Signed-off-by: Paul S. Schweigert <paul@paulschweigert.com>
Follow-on from #9128 
Fixes a docstring typo in the `pass_manager_drawer` function.
=> Fix doc typos in pass_manager_drawer

CONTRIBUTING.md
Going through my first build and reading the contributing guides, I realized we're missing to mention that a dev environment requires `setuptools-rust`, which is picked up by `pip install ...` commands, but if a user does `python setup.py ...` they need to have them installed themselves. This PR adds a note for the dependencies.
I also noticed this in `pyproject.toml`:
```
[tool.black]
line-length = 100
target-version = ['py37', 'py38', 'py39', 'py310']
```
Do we want `py311` there (in this or a separate PR)?
=> DOC add build dependency to contributing guides

pyproject.toml
Python 3.11 was missing as a target version for black. This PR adds that.
ref: https://github.com/Qiskit/qiskit-terra/pull/9510#issuecomment-1412543621
cc @jakelishman
=> MNT add py311 as a target to black config

qiskit/synthesis/__init__.py
While working on #9484, I realized that the `QDrift` trotterization method is not shown in the rendered docs. Adding it to the toctree to be able to link it in the guide.
=> Add `synthesis.QDrift` to sphinx toctree

src/lib.rs
Inlining variables into format strings is now a lint failure in the most recent Rust versions, but the syntax isn't available in the stable branch's MSRV of 1.56.1.
This disables the lint rule we fixed in #9470 but couldn't backport, since it's now causing issues.
=> Disable f-string clippy lint

Cargo.toml
This formalises the MSRV policy by enforcing it at the configuration level.  This has helpful knock-on effects; `clippy` will no longer emit linter failures for rules added in new versions of `clippy` that can't be implemented in the MSRV.  This makes our CI more stable against updates to `clippy`.
We can backport this, but must remember to change the MSRV to 1.56.1 in the backport.  This PR would solve the same problem (more properly) as #9529.
=> Set MSRV in `Cargo.toml`

qiskit/providers/backend_compat.py, qiskit/providers/fake_provider/utils/backend_converter.py, qiskit/transpiler/target.py, releasenotes/notes/fix-target-aquire_alignment-typo-d32ff31742b448a1.yaml, test/python/transpiler/test_target.py
The misspelled `aquire_alignment` appears in the `Target` constructor and attribute. This will be replaced with the correct spelling `acquire_alignment`.
=> Fix typo of Target argument name

qiskit/providers/fake_provider/fake_backend.py
Update fake backend not to use deprecated arguments, `standard_gates` and `warnings`, in the construction of a noise model for simulation.
=> Fix fake backend not to use deprecated arguments in NoiseModel construction

qiskit/quantum_info/states/statevector.py, qiskit/quantum_info/synthesis/xx_decompose/decomposer.py
Following discussion, I'm splitting https://github.com/Qiskit/qiskit-terra/pull/8187 by module.
There are 8 errors left:
```
qiskit/quantum_info/synthesis/two_qubit_decompose.py:580: error: Missing positional arguments "num_qubits", "params" in call to "Gate"  [call-arg]
qiskit/quantum_info/synthesis/two_qubit_decompose.py:580: error: Argument 1 to "Gate" has incompatible type "float"; expected "str"  [arg-type]
qiskit/quantum_info/synthesis/two_qubit_decompose.py:583: error: Missing positional arguments "num_qubits", "params" in call to "Gate"  [call-arg]
qiskit/quantum_info/synthesis/two_qubit_decompose.py:583: error: Argument 1 to "Gate" has incompatible type "float"; expected "str"  [arg-type]
qiskit/quantum_info/synthesis/two_qubit_decompose.py:590: error: Missing positional …
```
=> Fix mypy errors (quantum_info)

qiskit/transpiler/passes/utils/gate_direction.py, releasenotes/notes/gate-direction-swap-885b6f8ba9779853.yaml, test/python/transpiler/test_gate_direction.py
Swaps are inherently symmetrical like `cz`, but in cases where we're using the legacy directed `CouplingMap`, it can still be convenient to ensure that we output swaps in the preferred order.
Discovered in changes to the algorithm in #9560.
=> Add flipping of `swap` to `GateDirection` pass

qiskit/transpiler/passes/utils/merge_adjacent_barriers.py, releasenotes/notes/deterministic-barrier-before-final-measurements-04e817d995794067.yaml, test/python/transpiler/test_adjacent_barriers.py, test/python/transpiler/test_barrier_before_final_measurements.py
The barrier-merging step at the end directly converted its inner (unordered) sets of bits into (ordered) lists, which is an operation dependent on `PYTHONHASHSEED`.  This can have an impact on subsequent topological iteration orders, if there are any barriers that are not full-width in the circuit, which can in turn cause later stochastic transpiler passes to have different outputs for fixed random seeds, depending on `PYTHONHASHSEED`.
This is what's causing the non-determinism in the test on #9560.
=> Make `BarrierBeforeFinalMeasurements` deterministic

qiskit/transpiler/coupling.py
Right now the CouplingMap.make_symmetric has a quadratic overhead. It was iterating over a list of each edgess' endpoints in the graph and for each edge it was iterating over the same list again to check whether the reverse edge is present or not. The overhead for this for large coupling maps can be quite large, for example with a 10497 qubit heavy hex coupling map the time it took to run this method as part of SabreLayout's initialization was ~10x slower than actually running the pass (a equally sized Bernstein-Vazirani circuit). Instead of doing an O(n) contains check inside the loop this commit updates it to use a set which will be an O(1) lookup. This should address the performance issue with this method. In the future we should leverage the native rustworkx method to do this, which …
=> Improve efficiency of CouplingMap.make_symmetric

.azure/wheels.yml, pyproject.toml
This commit fixes an issue in the recently merged #9584 which added a rustup toolchain file to the qiskit repo to default to our MSRV when using rustup. In that commit the intent was for wheel jobs to use the latest version of the stable Rust to publish precompiled wheels. However, the mechanism by which that was done in the PR won't work for linux environments. The linux cibuildwheel jobs leverage a docker container to build the binaries in that have known manylinux compatible environment so that the wheels we ship are compatible with the packaging specification. #9584 was setting the rust version override in the host environment via `rustup override` which wouldn't propogate to inside the docker container. To address this issue this commit updates the cibuildwheel config to set the …
=> Fix setting rustup toolchain override in wheel builds

qiskit/algorithms/time_evolvers/classical_methods/evolve.py, releasenotes/notes/fix-numpy-eigensolver-sparse-0e255d7b13b5e43b.yaml
Same issue as #9575: due to a missing indent sparse operators were accidentally converted to dense matrices.
This led to the kernel being dumped on ~20 qubit time evolution whereas this should only take seconds to minutes to run.
I just updated the reno from #9575 to also include this PR as it's exactly the same problem 🙂
=> Fix sparse matrix conversion for `SciPy<Real/Imaginary>Evolver`

.azure/test-linux.yml, azure-pipelines.yml
We now run all Rust tests in the preliminary Linux test job and when pushing to the repo.
Why, when we already have great Python tests of our Rust interface? Because we're restricting ourselves from testing at lower levels of abstraction, like unit tests for helper functions. We will still keep our Python tests! But some of our Rust code is highly complex now, so it's valuable to have the ability to test at a lower abstraction level.
These Rust tests are intended to be fast. If in the future we make more robust ~integration tests, we'll revisit the CI setup.
The tests run in the preliminary stage to give faster feedback to Rust developers. This is a tradeoff: it means non-Rust PRs are slightly slower. If this proves too slow, then we can move the tests to later.
In the future, we also can …
=> Run Rust tests in CI

.pylintrc, qiskit/opflow/converters/pauli_basis_change.py, requirements-dev.txt, test/python/pulse/test_transforms.py
Pylint 2.16 adds support for Python 3.11 and also adds lots of great new checks.
To facilitate landing this, I disabled all the new checks that we fail. This will be fixed in a followup in https://github.com/Qiskit/qiskit-terra/issues/9614. 
Why not fix those before this PR?
1. I want to use Pylint with Python 3.11
2. Landing the upgrade now means that once we fix a check and enable it, we'll proactively avoid any regressions for that check.
=> Upgrade Pylint to 2.16.2

qiskit/transpiler/passes/synthesis/unitary_synthesis.py, test/python/transpiler/test_unitary_synthesis.py
This commit fixes an issue introduced into the UnitarySynthesis pass as part of #9175. In #9715 the UnitarySynthesis pass was updated to consider multiple different target bases and select the best performing synthesis output found. When UnitarySynthesis is provided a Target object this involves querying the target for the error rates and duration of the instructions used. However, currently this lookup doesn't handle a couple of edge cases in the target data model resulting from variable width operations and ideal gates (i.e. from a simulator that don't have error or durations). In those cases some fields in the internal dictionaries used to store data can be None or the gate object stored in the target can be a class not an instance of a class. If a target with either of these …
=> Fix target error and duration lookup in UnitarySynthesis

qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py
Performance improvement of `SparsePauliOp.tensor` by skipping a redundant phase check.
```python
import random
from qiskit.quantum_info import SparsePauliOp
def bench(k, n):
random.seed(123)
op = SparsePauliOp.from_list([(''.join(random.choices('IXYZ', k=k)), 1) for _ in range(n)])
op2 = SparsePauliOp.from_list([(''.join(random.choices('IXYZ', k=k)), 1) for _ in range(n)])
print(f'{k}, {n}: {timeit(lambda: op.tensor(op2), number=1)} sec')
bench(10, 5000)
```
main
```
10, 5000: 3.415048268998362 sec
```
this PR
```
10, 5000: 1.9170281529986823 sec
```
=> Performance improvement of `SparsePauliOp.tensor`

test/python/providers/test_fake_backends.py
789707c61 (gh-9630) added a test for wrapping Aer in a converted `BackendV2` subject to providing an extended name mapping for all the custom instructions that Aer supports, which Terra does not generally define.  However, the supported lists were based off a slightly older version of Aer (approximately release version 0.11), and fail on the current `main` version (due to soon become version 0.12) because of `break_loop` and `continue_loop` support being added.
=> Add loop ops to Aer BackendV2 test

qiskit/execute_function.py
Fixing this minor formatting issue in https://qiskit.org/documentation/apidoc/execute.html :
=> minor formatting issue in qiskit.execute_function

qiskit/circuit/random/utils.py, releasenotes/notes/fix-random-circuit-conditional-6067272319986c63.yaml, test/python/circuit/test_random_circuit.py
The `condition` field is expected to be a comparison of a register or bit with a Python bigint (or bool, which is a subclass).  This function could previously output fixed-width Numpy types, however, which could cause problems with subsequent bitmasks if the constructed masker/maskee _was_ a Python bigint and couldn't fit in the Numpy type.  The more recent `IfElseOp` enforces the correct typing, it's just the old form that doesn't.
Fix #9649
=> Fix typing error in `random_circuit` conditionals

qiskit/circuit/library/__init__.py, qiskit/circuit/library/standard_gates/__init__.py
Only the docstring from ` qiskit/circuit/library/__init__.py` is actually built into the documentation - any changes to the `../standard_gates/__init__.py` docstring has no effect on the built documentation.
- Some gates were moved from `../standard_gates/__init__.py` to `qiskit/circuit/library/__init__.py`, since they do not appear in the documentation of the circuit library.
- Some gates changed their places according to the alphabetic order of their names.
- `qiskit/circuit/library/__init__.py` docstring has been removed, since it's not used.
=> Update the docsring of the circuit library

qiskit/transpiler/target.py, releasenotes/notes/fix-missing-instproperty-calibration-e578052819592a0b.yaml, test/python/transpiler/test_target.py
In #9597 we updated the `InstructionProperties.calibration` to internally store `CalibrationEntry` subclass. However, there still be the case `None` is stored instead when user/system doesn't provide any calibration, e.g. `reset` instruction or any control flow operation. Accessing calibration of such entry raises AttributeError, which must be suppressed and it must return `None` instead.
=> Stop raising AttributeError when accessing missing calibration

qiskit/version.py
Since `pkg_resources.declare_namespace` has been deprecated, our CI is failed.
I removed the dependency to `pkg_resources`.
CI message
```
==============================
Failed 1 tests - output below:
==============================
test.python.test_version.TestVersion.test_qiskit_version
--------------------------------------------------------
Captured traceback:
~~~~~~~~~~~~~~~~~~~
File "/Users/runner/work/1/s/test/python/test_version.py", line 25, in test_qiskit_version
self.assertEqual(__version__, __qiskit_version__["qiskit-terra"])
~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
File "/Users/runner/work/1/s/qiskit/version.py", line 168, in __getitem__
self._load_versions()
File "/Users/runner/work/1/s/qiskit/version.py", line 104, in _load_versions
import …
```
=> Remove dependency to pkg_resources

qiskit/algorithms/time_evolvers/pvqd/pvqd.py, qiskit/circuit/controlledgate.py, qiskit/circuit/quantumcircuit.py, qiskit/opflow/gradients/qfi_base.py, qiskit/quantum_info/operators/symplectic/base_pauli.py, qiskit/quantum_info/synthesis/qsd.py, qiskit/tools/events/progressbar.py, qiskit/tools/events/pubsub.py, qiskit/tools/jupyter/progressbar.py, qiskit/utils/backend_utils.py, qiskit/utils/run_circuits.py, qiskit/visualization/circuit/circuit_visualization.py, test/python/circuit/test_commutation_checker.py, test/python/dagcircuit/test_dagcircuit.py, test/python/transpiler/test_commutative_cancellation.py, test/python/transpiler/test_commutative_inverse_cancellation.py
Errors are found by the command `ruff check --select=D403 qiskit tools test examples setup.py`, and likewise for 
D211, D419 , D201, D208 , D405.
This PR fixes these errors, largely manually either because there is no automatic fix, or the fix suggested is not really what we want.
See #9707
=> Fix docstring format errors found by ruff

qiskit/qasm/qasmlexer.py, qiskit/quantum_info/operators/symplectic/stabilizer_table.py, test/python/result/test_result.py, test/python/visualization/test_circuit_text_drawer.py
This fixes some formatting typos in some docstrings.
This is a followup to #9689. There are four cases found as follows
```shell
> ruff check --select=D210  qiskit tools test
qiskit/qasm/qasmlexer.py:127:9: D210 [*] No whitespaces allowed surrounding docstring text
qiskit/quantum_info/operators/symplectic/stabilizer_table.py:1030:9: D210 [*] No whitespaces allowed surrounding docstring text
test/python/result/test_result.py:130:9: D210 [*] No whitespaces allowed surrounding docstring text
test/python/visualization/test_circuit_text_drawer.py:13:1: D210 [*] No whitespaces allowed surrounding docstring text
```
These cases are compounded by other quirks or typos in the docstrings. Both the extra whitespace and quirks are fixed manually here.
=> More fixing extra whitespace surrounding docstrings

qiskit/transpiler/instruction_durations.py, qiskit/transpiler/passmanager_config.py, releasenotes/notes/fix-backendv1-pm-config-from-backend-914869dd6e1c06be.yaml, test/python/transpiler/test_passmanager_config.py
This commit fixes two small oversights that would appear when calling PassManagerConfig.from_backend() with a simulator BackendV1 backend. The handling of optional fields in the BackendProperties and PulseDefaults objects for BackendV1 backends was missing that a BackendProperties object's gates field could be None and that the defaults() method could return None in the absense of any pulse calibrations (both of which typically only are True for simulators). In these cases this would cause an error constructing the InstructionDurations object and the InstructionScheduleMap object respectively. This fixes the handling of these edge cases so that PassManagerConfig.from_backend() will work with any BackendV1 based backend.
Fixes #8546
Fixes #9265
=> Fix handling of BackendV1 simulators in PassManagerConfig.from_backend

test/python/transpiler/test_optimize_1q_decomposition.py
This patch adds regression tests for #9701. See https://github.com/Qiskit/qiskit-terra/pull/9701#pullrequestreview-1324700689.
Please advise if this change warrants an entry in the release notes.
=> test/transpiler: add regression tests for #9701

test/python/pulse/test_block.py
In the recently released qiskit-aer 0.12.0 the `PulseSimulator` backend (used as its name implies to simulate pulse schedules) was deprecated in favor of the actively maintained qiskit-dynamics package. This deprecation is causing test failures when running our test suite with qiskit-aer installed because a single test was opportunistically using the `PulseSimulator` backend when aer was installed. This commit adds an assertion to catch the `DeprecationWarning` and adds a comment to rewrite the test to use dynamics. Although we may not wish to add the optional bidirectional dependency for a single test, in which case we should just delete the test. But that is a discussion for a follow up PR when CI is not blocked by an upstream/downstream package's release. This commit is just a short …
=> Suppress PulseSimulator deprecation warning in tests

.azure/docs-linux.yml, setup.py, tox.ini
I was getting 4567 errors on my mac when using `tox -e docs`, in the form of:
```
[autosummary] failed to import qiskit.circuit.classicalfunction.ClassicalFunction.add_decomposition.
Possible hints:
* AttributeError: module 'qiskit.circuit.classicalfunction.ClassicalFunction' has no attribute 'add_decomposition'
* ModuleNotFoundError: No module named 'qiskit.circuit.classicalfunction.ClassicalFunction.add_decomposition'; 'qiskit.circuit.classicalfunction.ClassicalFunction' is not a package
```
This is because editable install can break macOS Sphinx: https://github.com/sphinx-doc/sphinx/issues/10943. (Thank you @jakelishman for the tip!)
We still use an editable install for all other Tox environments. That avoids needing to rebuild the venv when changes are made to Terra, which is faster …
=> Fix `tox -e docs` for macOS

qiskit/transpiler/passes/utils/gate_direction.py, releasenotes/notes/fix-gate-direction-calibration-c51202358d86e18f.yaml, test/python/transpiler/test_gate_direction.py
If there is an explicit calibration given, this overrides the generic information from the `CouplingMap` or the `Target` for that particular instance, since one can use pulse-level control to define gates on a circuit-by-circuit basis that are not generically available in a way that can be specified in the coupling or target.
Fix #9783
=> Fix explicitly calibrated gates in `GateDirection`

qiskit/transpiler/passes/utils/gate_direction.py, test/python/transpiler/test_gate_direction.py
The `Target` version of `GateDirection` has more information available to make better error messages. It can distinguish cases where the failure is because a gate would be valid if flipped but the pass doesn't know how to do it, and the case where the gate wouldn't be valid in either direction.
This addresses the error-message component of #9783.
=> Improve error messages in `Target`-based `GateDirection` pass

qiskit/algorithms/factorizers/shor.py, qiskit/algorithms/linear_solvers/hhl.py, qiskit/algorithms/phase_estimators/phase_estimation_result.py, qiskit/dagcircuit/dagcircuit.py, qiskit/utils/deprecation.py, test/python/utils/test_deprecation.py
Applies https://github.com/Qiskit/qiskit-terra/pull/9685 to our current deprecation decorators.
=> `@deprecate_arguments` and `@deprecate_function` add deprecation to docstring

qiskit/quantum_info/operators/symplectic/pauli_list.py, releasenotes/notes/paulilist-do-not-broadcast-from-paulis-96de3832fba21b94.yaml, test/python/quantum_info/operators/symplectic/test_pauli_list.py
When constructing a `PauliList` from `Pauli`s or labels, the number of qubits is inferred from the first argument, and a `ValueError` is raised if any subsequent element has a different number of qubits.  For instance:
```python
>>> from qiskit.quantum_info import PauliList
>>> PauliList(["XXX", "ZZ"])
File "<stdin>", line 1, in <module>
File "/home/garrison/Qiskit/qiskit-terra3/qiskit/quantum_info/operators/symplectic/pauli_list.py", line 140, in __init__
base_z, base_x, base_phase = self._from_paulis(data)
^^^^^^^^^^^^^^^^^^^^^^^
File "/home/garrison/Qiskit/qiskit-terra3/qiskit/quantum_info/operators/symplectic/pauli_list.py", line 193, in _from_paulis
base_z[i] = pauli._z
~~~~~~^^^
ValueError: could not broadcast input array from shape (2,) into shape …
```
=> Remove implicit broadcasting from `Pauli`/label construction of `PauliList`

azure-pipelines.yml
This commit attempts to add a trigger condition to our azure pipelines job to trigger on commits to the gh merge queue branch.
=> Attempt to trigger Azure pipelines on merge queue events

crates/accelerate/src/dense_layout.rs
Clippy has started complaining about this on the stable branch, and it's probably correct to do so.
=> Remove useless `into_iter()` on `Range`

.mergify.yml
Due to recent changes in the mergify configuration/service the merge queue feature of mergify is no longer working as expected. It's not clear if this just a temporary bug in mergify, a longer term change in behavior (which requires all PR authors to be registered on mergify), or some incompatibility between the github api and mergify. However, because we're no longer able to rely on it we've moved to using github's native merge queue feature [1][2] instead. Since this new merge queue would conflict with mergify's this commit removes the merge queue configuration from the mergify configuration. The configuration for stable backporting is left in place because github doesn't natively offer that feature and it appears to still work fine.
[1] …
=> Stop using mergify merge queue feature

tox.ini
Solves the issue from https://github.com/Qiskit/qiskit-terra/pull/9477. 
As explained in the code's comment, this results in pip resolving Aer's dependency on Terra via the local installation, not from PyPI.
How did I test this works? 
* I changed `requirements.txt` to set `python-dateutil==2.8.2`, then added to `deps` `python-dateutil==2.8.1`. That should cause a conflict: the `deps` stage will install `2.8.1`, then when installing Terra locally, we'll try using `2.8.2`. But due to [Tox wonkiness not fixed until Tox 4.4](https://tox.wiki/en/latest/changelog.html#features-4-4-0), tox silently allows for that conflict to happen.
* But, when adding `.` to `deps` as well, pip fails due to the conflict. This indicates that Pip indeed is installing from the local installation during the `deps` …
=> Fix Tox installing Terra from PyPI

qiskit/circuit/quantumcircuit.py, releasenotes/notes/fix-qasm-reset-ef7b07bf55875be7.yaml, test/python/circuit/test_circuit_qasm.py
`QuantumCircuit.qasm` misses `;` after `reset` as follows. This PR fixes it.
```python
qc.reset(range(2))
print(qc.qasm())
```
main
```
OPENQASM 2.0;
include "qelib1.inc";
qreg q[2];
reset q[0]
reset q[1]
```
this PR
```
OPENQASM 2.0;
include "qelib1.inc";
qreg q[2];
reset q[0];
reset q[1];
```
=> Fix `QuantumCircuit.qasm` with `reset`

qiskit/compiler/transpiler.py, releasenotes/notes/improve-transpile-typing-de1197f4dd13ac0c.yaml
This patch improves the typing of the (top-level) `qiskit.compiler.transpiler.transpile` function.
The main change is the introduction of two overloads that allow narrowing the return type depending on whether a single circuit or a list of circuit was passed as the `circuits` argument. This is relevant for uses of Qiskit in a typed context. In this situation, the following snippet currently causes an error:
```python
qc = QuantumCircuit(...)
transpiled_qc = transpile(qc,...)
num_qregs = len(transpiled_qc.qregs)  # pyright: Cannot access member "qregs" for type "List[QuantumCircuit]"
```
A common workaround is to manually narrow the type, which is tedious and distracting:
```python
qc = QuantumCircuit(...)
transpiled_qc = transpile(qc,...)
assert isinstance(transpiled_qc, QuantumCircuit) …
```
=> transpile: narrow the return type depending on the circuits argument

qiskit/quantum_info/synthesis/one_qubit_decompose.py, releasenotes/notes/fix-type-angles-euler-decompose-233e5cee7205ed03.yaml, test/python/quantum_info/test_synthesis.py
This commit fixes a regression introduced in the rewrite of the internals of the OneQubitEulerDecomposer class to be in rust. Previously the angles() and angles_and_phase() methods of OneQubitEulerDecomposer would work with a non-complex dtype in the input, however because the rust component of the module is strictly typed to only work with a complex128 dtype passing the array to rust to compute the angles and phase of the unitary would fail. To address this limitation this commit casts the input matrix to be complex before passing it to the rust function.
Fixes #9827
=> Fix non-complex dtypes in OneQubitEulerDecomposer methods

qiskit/transpiler/passes/synthesis/unitary_synthesis.py, test/python/transpiler/test_unitary_synthesis.py
Since moving `Optimize1qDecomposition` down to the Rust level, some of its use in the default `UnitarySynthesis` plugin was allowing `None` to be passed to an internal function unchecked.  This correctly returns the "could not synthesise" value when appropriate.
Fix #9842.  No changelog because the carcinisation of `Optimize1qDecomposition` isn't released yet.
=> Fix missing handling of no-synthesis case in `UnitarySynthesis`

qiskit/circuit/quantumcircuit.py, qiskit/compiler/transpiler.py, qiskit/converters/dag_to_circuit.py, qiskit/transpiler/basepasses.py, qiskit/transpiler/passes/basis/basis_translator.py, qiskit/transpiler/passes/utils/control_flow.py, qiskit/transpiler/runningpassmanager.py, releasenotes/notes/deepcopy-option-dag_to_circuit-2974aa9e66dc7643.yaml
This commit adds a new option, copy_operations, which allows to disable the deepcopy on dag_to_circuit(). Previously the dag to circuit converter would always deep copy the operations, however in the transpiler we don't need this extra overhead because the DAGCircuits are temporary internal artifacts and will not be resused outside of the transpiler. So we can avoid the copy overhead in these situations, however in general the converter needs to default to copying. This new argument enables this workflow by keeping the current behavior by default but enabling the transpiler to skip copying operations in the output conversion.
=> Add option to skip deepcopy on dag_to_circuit

requirements.txt
The recent release of symengine 0.10.0 has changed the precision of complex multiplications, breaking some tests that expect a pure imaginary result (i.e `2.3j`) and get a complex with a real part (`1.408343819019456e-16+2.3j`):
- ` test.python.circuit.test_parameters.TestParameterExpressions.test_complex_parameter_bound_to_real`
- `test.python.circuit.test_parameters.TestParameterExpressions.test_expressions_of_parameter_with_constant`
While we find a permanent solution (either opening an issue on symengine or dealing with the truncation ourselves), pinning the symengine version can help to keep the merge queue moving.
This pin can be reverted once the issue is fixed.
EDIT: This PR might not be necessary if https://github.com/Qiskit/qiskit-terra/pull/8734 fixes the issue.
=> pin symengine to `<0.10.0`

.azure/lint-linux.yml, .azure/test-linux.yml, .azure/test-macos.yml, .azure/test-windows.yml, .azure/tutorials-linux.yml, .github/workflows/coverage.yml, .github/workflows/randomized_tests.yml, .github/workflows/slow.yml
Up-to-date Python packages should not require this step, however there are several packages, especially those that are optional for Terra functionality, that do not yet contain `pyproject.toml` files when building them from source.  In these cases, `pip` will begin erroring out from version 23.1 if `wheel` is not installed.
This commit proactively ensures that the minimum build dependencies for legacy Python packages is prepared and up-to-date before attempting installations; this includes ensuring that these are updated _inside_ any created venvs as well as outside them.
In reviewing a few recent CI runs, I've been noticing pip outputting the message (e.g.):
```text
DEPRECATION: pyperclip is being installed using the legacy 'setup.py install' method, because it does not have a …
```
=> Ensure up-to-date `pip`, `setuptools` and `wheel` in CI

qiskit/algorithms/amplitude_amplifiers/grover.py, qiskit/algorithms/amplitude_estimators/ae.py, qiskit/algorithms/amplitude_estimators/fae.py, qiskit/algorithms/amplitude_estimators/iae.py, qiskit/algorithms/amplitude_estimators/mlae.py, qiskit/algorithms/aux_ops_evaluator.py, qiskit/algorithms/eigen_solvers/eigen_solver.py, qiskit/algorithms/eigen_solvers/numpy_eigen_solver.py, qiskit/algorithms/eigen_solvers/vqd.py, qiskit/algorithms/evolvers/evolution_problem.py, qiskit/algorithms/evolvers/evolution_result.py, qiskit/algorithms/evolvers/imaginary_evolver.py, qiskit/algorithms/evolvers/real_evolver.py, qiskit/algorithms/evolvers/trotterization/trotter_qrte.py, qiskit/algorithms/minimum_eigen_solvers/minimum_eigen_solver.py, qiskit/algorithms/minimum_eigen_solvers/numpy_minimum_eigen_solver.py, qiskit/algorithms/minimum_eigen_solvers/qaoa.py, qiskit/algorithms/minimum_eigen_solvers/vqe.py, qiskit/algorithms/optimizers/adam_amsgrad.py, qiskit/algorithms/optimizers/qnspsa.py, qiskit/algorithms/optimizers/spsa.py, qiskit/algorithms/phase_estimators/hamiltonian_phase_estimation.py, qiskit/algorithms/phase_estimators/ipe.py, qiskit/algorithms/phase_estimators/phase_estimation.py, qiskit/algorithms/phase_estimators/phase_estimation_result.py, test/python/algorithms/optimizers/test_spsa.py
See https://github.com/Qiskit/qiskit-terra/pull/9676 for the motivation.
=> Apply new deprecation decorators to algorithms folder

qiskit/primitives/backend_estimator.py, qiskit/primitives/backend_sampler.py, qiskit/primitives/base/base_primitive.py
Following discussion, I'm splitting https://github.com/Qiskit/qiskit-terra/pull/8187 by module.
<details>
<summary> Previous content </summary>
The are ~20 errors left:
```
qiskit/primitives/base_estimator.py:322: error: Invalid index type "Union[int, QuantumCircuit]" for "Tuple[QuantumCircuit, ...]"; expected type "SupportsIndex"  [index]
qiskit/primitives/base_estimator.py:342: error: Invalid index type "Union[int, QuantumCircuit]" for "Tuple[ParameterView, ...]"; expected type "SupportsIndex"  [index]
qiskit/primitives/base_estimator.py:345: error: Invalid index type "Union[int, QuantumCircuit]" for "Tuple[ParameterView, ...]"; expected type "SupportsIndex"  [index]
qiskit/primitives/base_estimator.py:349: error: Invalid index type "Union[int, QuantumCircuit]" for …
```
=> Fix mypy errors (primitives)

qiskit/transpiler/passes/synthesis/high_level_synthesis.py
This commit fixes an issue in the HighLevelSynthesis transpiler pass where it was doing plugin discovery each time the pass was run. This can cause unecessary overhead to discover the same thing every time a pass is run when an instance of the pass is run more than once (which in the preset pass managers is always the case). This commit just moves the plugin manager initialization to the pass initialization so that the plugins are only discovered once per pass instance. We're never in a situation where a user is able to install extra plugins and use them during the liftetime of a single pass instance anyway so re-running discovery on each call to HighLevelSynthesis.run() isn't needed.
=> Only do HLS plugin discovery once

qiskit/qobj/__init__.py, qiskit/qobj/converters/pulse_instruction.py, qiskit/qobj/pulse_qobj.py, qiskit/qobj/qasm_qobj.py, qiskit/qpy/interface.py
=> Apply new deprecation decorators to qobj and qpy

qiskit/execute_function.py, qiskit/opflow/gradients/derivative_base.py, qiskit/synthesis/evolution/suzuki_trotter.py, qiskit/test/decorators.py, qiskit/utils/quantum_instance.py
=> Apply new deprecation decorators to util files and folders

qiskit/quantum_info/operators/symplectic/pauli_table.py, qiskit/quantum_info/operators/symplectic/pauli_utils.py, qiskit/quantum_info/operators/symplectic/random.py, qiskit/quantum_info/operators/symplectic/stabilizer_table.py, qiskit/quantum_info/synthesis/clifford_decompose.py, qiskit/quantum_info/synthesis/cnotdihedral_decompose.py, qiskit/quantum_info/synthesis/two_qubit_decompose.py
=> Apply new deprecation decorators to quantum_info folder

qiskit/visualization/pulse/matplotlib.py
This a small fix to the formatting, which used an expression of form `"%s" % time * dt`. Since the `%` has higher priority it end up multiplying string by floating point number `dt`. I think the intent was to use `time * dt` for formatting
=> Fix string formatting in pulse drawer

qiskit/transpiler/passes/utils/cx_direction.py, test/python/visualization/references/pass_manager_standard.dot, test/python/visualization/references/pass_manager_style.dot, test/python/visualization/test_pass_manager_drawer.py
Adding a deprecator to the constructor of `CXDirection` causes us to need new dot files for the pass manager visualization. See the first commit.
That is blocking the use of `@deprecate_func` in https://github.com/Qiskit/qiskit-terra/pull/9868.
So, @mtreinish suggested rewriting the test to no longer use `CXDirection`.
=> Refactor test to not use deprecated `CXDirection`

qiskit/circuit/quantumcircuit.py, qiskit/transpiler/__init__.py, qiskit/transpiler/layout.py, releasenotes/notes/add-layout-attribute-c84e56c08ca93ada.yaml
Since the Qiskit 0.9.0 release the QuantumCircuit has had a private `_layout` attribute which is used to track the permutations introduced to a circuit by the transpiler. At the time this was made private because we didn't want to commit to an interface on this at the time until a dedicated API could be introduced (see #2853). However, since that time ~4 years ago we've never introduced an alternative public interface for `_layout`. This has left users needing to reason about the permutation caused by transpile() in a weird place because the only mechanism to do this is private. This commit adds a public read-only attribute `.layout` to solve this, which just exposes the previously private `._layout` attribute via a documented and public interface.
Unlike from 0.9.x through 0.21.x we …
=> Add public layout attribute to QuantumCircuit

qiskit/transpiler/passes/__init__.py, qiskit/transpiler/passes/utils/__init__.py, qiskit/transpiler/passes/utils/minimum_point.py, qiskit/transpiler/preset_passmanagers/level3.py, releasenotes/notes/add-minimum-point-pass-09cf9a9eec86fd48.yaml, test/python/compiler/test_transpiler.py, test/python/transpiler/test_minimum_point.py
This commit adds a new transpiler pass MinimumPoint which is used to find a local minimum point from the property set between executions of the pass. This is similar to the existing FixedPoint pass but will find the minimum fixed point over the past n exeuctions as opposed to finding a when two subsequent exectuions are at the same point. This is then used in optimization level 3 because the 2q unitary synthesis optimization that is part of the optimization loop can occasionally get stuck oscillating between multiple different equivalent decompositions which prevents the fixed point condition from ever being reached. By checking that we've reached the minimum over the last 5 executions we ensure we're reaching an exit condition in this situation.
Fixes #5832
Fixes #9177
Fixes #9776
(the …
=> Add MinimumPoint transpiler pass

qiskit/test/base.py
This improves the error message when running the test suite, if an `assertEqual` is applied to two circuits; on a failed test, the circuits are now drawn so they can be compared, rather than just seeing that the two pointers are not the same.
Given a test:
```python
a = QuantumCircuit(2)
a.h(0)
a.cx(0, 1)
b = QuantumCircuit(2)
b.cx(0, 1)
b.h(0)
self.assertEqual(a, b)
```
With this change, the output is:
```text
Captured traceback:
~~~~~~~~~~~~~~~~~~~
File "/Users/jake/code/qiskit/terra/test/python/circuit/test_circuit_registers.py", line 43, in test_bad
self.assertEqual(a, b)
File "/Users/jake/python/3.10.6/lib/python3.10/unittest/case.py", line 845, in assertEqual
assertion_func(first, second, msg=msg)
File …
```
=> Improve error messages on failed circuit-equality assertions

qiskit/circuit/quantumcircuit.py, qiskit/converters/circuit_to_dag.py, releasenotes/notes/deepcopy-option-circuit_to_dag-1d494b7f9824ec93.yaml
Just as was done for #9825 for dag_to_circuit(), this commit adds a new option, copy_operations, which allows to disable the deepcopy on circuit_to_dag(). Previously, the circuit to dag converter would always deep copy every operation, however we don't need this extra overhead in every case; where the input QuantumCircuit is discarded after conversion. This new flag lets us avoid the copy overhead in these situations, however in general the converter still needs to default to copying.
=> Add option to skip deepcopy on circuit_to_dag

qiskit/circuit/library/arithmetic/linear_pauli_rotations.py
For a register of state qubits $\ket{x}$, a target qubit $\ket{0}$ the operation $Y$ of a linear  rotation on a zero-input qubit is:
$$|x\rangle |0\rangle \mapsto \cos(ax + b)|x\rangle|0\rangle + \sin(ax + b)|x\rangle |1\rangle$$
with $a=$ `slope`/2 and $b=$ `offset`/2.
- link issue: https://github.com/Qiskit/qiskit-terra/issues/9861#issuecomment-1492126522
- link documentation: https://arxiv.org/pdf/1806.06893.pdf,
=> Fix `offset` and `slope` definitions for Linear Pauli Rotations (#9861)

qiskit/transpiler/passmanager.py, releasenotes/notes/fix-9798-30c0eb0e5181b691.yaml, test/python/compiler/test_transpiler.py, test/python/transpiler/test_passmanager_run.py
This patch fixes #9798 by returning a length-1 list if the input to `PassManager.run` was a length-1 list.
- dedicated regression tests are added to `test.python.transpiler.test_passmanager_run`
- type annotations on `PassManager.run` and `StagedPassManager.run` are` fixed / improved.
Fixes #9798.
=> PassManager.run: preserve input signature for length 1 list

qiskit/visualization/circuit/text.py, releasenotes/notes/fix-circuit-drawing-low-compression-965c21de51b26ad2.yaml, test/python/visualization/test_circuit_text_drawer.py
When using `QuantumCircuit.draw('text')` there was a wrong character used for drawing boxes in case of `vertical_compression="low"`. I fixed this bug by a oneliner and updated the tests. I did not find a corresponding open issue.
The bug is appears in this example:
```python
qc.h(0)
qc.h(1)
drawing_high = qc.draw("text", vertical_compression="high")
drawing_normal = qc.draw("text")
drawing_low = qc.draw("text", vertical_compression="low")
print(drawing_high)
print(drawing_low)
```
The "high"-circuit is drawn correctly, but the second Hadamard of the seconed circuit is drawn incorrectly. It incorrectly uses the character `┤` for the upper right corner of the Box of the Gate.
```
┌───┐
q_0: ┤ H ├
├───┤
q_1: ┤ H ├
└───┘
┌───┐
q_0: ┤ H …
```
=> Fix a bug in QuantumCircuit.draw related to vertical_compression

qiskit/transpiler/passes/basis/unroll_custom_definitions.py, releasenotes/notes/fix-unroll-custom-definitions-empty-definition-4fd175c035445540.yaml, test/python/transpiler/test_unroll_custom_definitions.py
The previous form of the code assumed that the `data` of the definition of a custom instruction contained the complete information.  This is not the case; a definition might also have a global phase.  If the definition of a custom instruction was empty but had a global phase set, this pass would silently throw it away.
Fixes an issue found in https://github.com/Qiskit/qiskit-terra/pull/9251#issuecomment-1494683204.
=> Fix `UnrollCustomDefinitions` handling of empty definitions

qiskit/synthesis/__init__.py, qiskit/synthesis/clifford/__init__.py, qiskit/synthesis/stabilizer/__init__.py, qiskit/synthesis/stabilizer/stabilizer_decompose.py, releasenotes/notes/stabilizer_state_synthesis-c48c0389941715a6.yaml, test/python/synthesis/test_clifford_decompose_layers.py, test/python/synthesis/test_stabilizer_synthesis.py
#9036 
Synthesis of a stabilizer state preparation. 
Based on the Clifford layered synthesis, it requires only the layers H2 - S1 - CZ1 - H1, 
so for linear nearest neighbor (LNN) connectivity it has 2q depth 2n+2.
Co-authored by: @alexanderivrii
=> Synthesis of a stabilizer state for LNN connectivity

qiskit/compiler/transpiler.py, releasenotes/notes/transpile-coupling-maps-3a137f4ca8e97745.yaml, test/python/compiler/test_transpiler.py
=> Fixed handling of a list of coupling_maps passed to transpile()

qiskit/circuit/quantumcircuitdata.py, releasenotes/notes/fix-setting-circuit-data-operation-1b8326b1b089f10c.yaml, test/python/circuit/test_circuit_data.py
The legacy ability to directly mutate `QuantumCircuit.data` was not accounting for cases where the operation could be an implementor of `Operation` that is not `Instruction`.  Actually using this functionality is still discouraged, but it should work.
Thanks to @kevinsung for pointing this out in https://github.com/Qiskit/qiskit-terra/pull/8714#discussion_r967038296.
=> Fix `QuantumCircuitData` handling of `Operation`

qiskit/transpiler/passes/routing/sabre_swap.py, test/python/transpiler/test_sabre_swap.py
`SabreSwap` requires that the input circuit is exactly the same size as the system implied by the coupling map, since this is used internally in Rust for the virtual-to-physical mapping.  Failure to ensure this can lead to panics in the Rust code.  This commit catches the failure case (for free) in Python space, and attempts to help the user work out what they needed.
This was prompted by [a discussion in Slack about the confusing error](https://qiskit.slack.com/archives/C034SHPSKSQ/p1680635772120959), though I've done approximately the same thing myself before and got confused.
=> Improve SabreSwap error message on unexpanded circuits

qiskit/circuit/library/standard_gates/equivalence_library.py, releasenotes/notes/add-ecr-sx-equivalences-5b6fe73ec599d1a4.yaml, test/python/transpiler/test_basis_translator.py
close #9907 
Add equivalences of to the equivalence library:
- CX decomposed into ECR and 1-qubit Clifford gates
- H decomposed into SX and S gates
- H decomposed into SXdg and Sdg gates
=> Add equivlences of ECR, SX and SXdg gates to the equivalence library

qiskit/providers/backend_compat.py, releasenotes/notes/filter-faulty-qubits-and-gates-v2-converter-b56dac9c0ce8057f.yaml, test/python/providers/test_fake_backends.py
Add flag to filter faulty qubits and gates to BackendV2Converter
This commit adds a flag to filter faulty qubits or gates from the
created target when using `BackendV2Converter`. The BackendProperties
object had a rarely used feature to annotate qubits or gates as being
non-operational and previously the BackendV2Converter would
unconditionally include qubits and gates with this flag set in the
output Target and BackendV2 instance. This new flag will enable users to
filter these if that is more desireable behavior. When filtering is set
the backend will still be listed as full width but any faulty qubits
will just not include any operations.
Fixes #9910
=> Add flag to filter faulty qubits and gates to BackendV2Converter

qiskit/algorithms/amplitude_estimators/ae.py, qiskit/algorithms/amplitude_estimators/estimation_problem.py, releasenotes/notes/ae-warns-on-goodstate-7dbb689ba6a5e5e4.yaml, test/python/algorithms/test_amplitude_estimators.py
As discussed in [Slack](https://qiskit.slack.com/archives/C7SS31917/p1680543628959579), the `AmplitudeEstimation` algorithm does not support `EstimationProblem.is_good_state` but just accept and silently ignores it, which leads to unexpected outcomes. This PR warns if the option is set and adds a note to the docs, that this option should be set differently.
That `is_good_state` is not supported is a property of the algorithm itself, not laziness on the dev side 🙂 
I labelled this "bugfix" as I thought that silently ignoring arguments is a bug, but we could also label this as docs change.
=> Fix `AmplitudeEstimation` is silently ignoring `is_good_state` in the estimation problem

.github/workflows/coverage.yml, .github/workflows/neko.yml
With our switch to using the GitHub merge queue with speculative merging, it's now possible for us to have two push events to a protected branch (like `main`) within a couple of minutes.  If this happens, the eager cancellation rules we have set for the coverage and Neko runs in GHA trigger, causing a spurious build failure to appear in the commit logs, and for the coverage history to be lost for one commit.
Instead, we can set the cancel-on-update behaviour to only trigger on PR sync events, not branch-push events.
We also likely want to set the workflows to only trigger on pushes to Qiskit repos so users' notifications don't get spammed, and we're not just burning the planet running unnecessary CI, but that's a separate logical change.
=> Don't cancel GHA runs on subsequent push events

requirements-dev.txt
The recent release of pygments 2.15.0 [1] has started emitting an error in the custom qasm pygments lexer included in qiskit in OpenQASMLexer. In the interest of not blocking CI this commit pins the pygments version we're installing in CI. Longer term, we should probably look at just deprecating the qiskit version and just using openqasm-pygments which is the pygments tools for OpenQASM maintained by the openqasm community.
[1] https://pypi.org/project/Pygments/2.15.0/
=> Pin pygments in CI

qiskit/transpiler/passes/utils/check_map.py, qiskit/transpiler/preset_passmanagers/common.py, qiskit/transpiler/preset_passmanagers/level1.py, test/python/transpiler/test_check_map.py, test/python/visualization/references/pass_manager_standard.dot, test/python/visualization/references/pass_manager_style.dot
In the recently merged 5672c70649b4f83a6c7146c68a6a543d4a3908fd the CheckMap transpiler pass had issues when handling some Target inputs (which was added as a supported type in that PR). These issues were actually pointed out in code review during #9263 but the follow up slipped through. This commit makes the required fixes and also updates the signature of the CheckMap to match the other changes made in #9263.
=> Fix CheckMap pass target handling

qiskit/transpiler/passes/utils/check_map.py, qiskit/transpiler/preset_passmanagers/common.py, releasenotes/notes/vf2postlayout-fix-16bb54d9bdf3aaf6.yaml, test/python/transpiler/test_preset_passmanagers.py, test/python/visualization/references/pass_manager_standard.dot, test/python/visualization/references/pass_manager_style.dot
This commit fixes an issue where we were incorrectly not running
VF2PostLayout in the one case where it should be run. Optimization level
1 is more involved than higher optimization levels because for backwards
compatibility it runs multiple different passes to try and find a
perfect layout, first starting with TrivialLayout, then VF2Layout, and
only if those 2 fail to find a perfect match do we run SabreLayout (or
DenseLayout and StochasticSwap if control flow are present). We only
should run VF2PostLayout if we're running the heuristic layout pass.
However, when we integrated routing into SabreLayout the checking for
whether we found a pefect layout in the layout stage stopped working as
expected.
To fix this issue a new flag is added to the CheckMap pass to specify an
alternative …
=> Ensure we run VF2PostLayout when needed in optimization level 1

qiskit/qpy/__init__.py, qiskit/qpy/binary_io/schedules.py, qiskit/qpy/common.py, qiskit/qpy/formats.py, qiskit/qpy/type_keys.py, releasenotes/notes/add-support-for-qpy-reference-70478baa529fff8c.yaml, test/python/qpy/test_block_load_from_qpy.py, test/qpy_compat/test_qpy.py
This PR adds support for `Reference` pulse instruction to QPY. In addition, ScheduleBlock with assigned subroutine after round-trip keeps original reference data structure. 
```python
from qiskit import pulse, qpy
import io
with pulse.build() as sub:
pulse.play(pulse.Constant(100, 0.1), pulse.DriveChannel(0))
with pulse.build() as schedule:
pulse.call(sub, name="subroutine")  # this immediately assigns subroutine to the reference
with io.BytesIO() as container:
qpy.dump(schedule, container)
binary = container.getvalue()
with io.BytesIO(binary) as container:
schedule_load = qpy.load(container)[0]
```
Original reference structure:
```python
>>> schedule.references
ReferenceManager(references=[('subroutine',)])
```
Conventional behavior:
```python
>>> schedule_load.references …
```
=> Add support for pulse reference to QPY

qiskit/qasm/__init__.py, requirements-dev.txt
The problem was because the latest version of Pygments included a docstring in `Lexer.__init__` that includes a crossreference to an object that Qiskit naturally doesn't have.  We don't need to inherit the `__init__` docstring for this object; we're only interested in documenting the existence of object itself.
This is the proper fix for the problem that #9938 quick-fixed.
=> Fix docs build with Pygments 2.15

crates/qasm2/src/lib.rs, test/python/qasm2/test_parse_errors.py
Previously, if Python thought the target file for `qasm2.load` existed, but Rust was unable to open it, the result `io:Error` would be propagated up to Python space verbatim, and these situations usually have confusing error messages.  This could happen, for example, if the target was a directory on Windows.
Detected while doing #9955 preparing for 0.25.  This PR is a bugfix for #9784, though, so wants to be in 0.24.
=> Wrap `io::Error` in `QASM2ParseError` on failed file read

qiskit/transpiler/passes/layout/vf2_layout.py, qiskit/transpiler/passes/layout/vf2_post_layout.py, releasenotes/notes/vf2-post-layout-max-trials-98b1c736e2e33861.yaml, test/python/transpiler/test_vf2_post_layout.py
Adds a new parameter `max_trials` to pass `VF2PostLayout` which, when specified, limits the number of layouts discovered and compared when searching for the best layout.
This can be used to place an upper bound on the time spent scoring potential layouts, which may be useful for larger devices. In a follow-up PR, we'll specify the parameter accordingly when invoking VF2 post layout within the preset pass managers.
=> Add `max_trials` parameter to `VF2PostLayout`.

qiskit/circuit/library/standard_gates/equivalence_library.py, qiskit/circuit/library/standard_gates/h.py, qiskit/circuit/library/standard_gates/r.py, qiskit/circuit/library/standard_gates/rx.py, qiskit/circuit/library/standard_gates/ry.py, qiskit/circuit/library/standard_gates/s.py, qiskit/circuit/library/standard_gates/sx.py, qiskit/circuit/library/standard_gates/t.py, qiskit/circuit/library/standard_gates/u2.py, qiskit/circuit/library/standard_gates/x.py, qiskit/circuit/library/standard_gates/xx_minus_yy.py, qiskit/circuit/library/standard_gates/xx_plus_yy.py, qiskit/circuit/library/standard_gates/y.py, qiskit/circuit/library/standard_gates/z.py, test/python/circuit/test_extensions_standard.py, test/python/qasm3/test_export.py
Prior to 4a6eb32337 (gh-3156), the value `qiskit.qasm.pi` was a re-export of a Sympy object, so it had some value.  Since then, we no longer use Sympy at all, let alone as the default type for parameters, and the export served no real purpose.  It did, however, cause a bunch of problematic circular dependencies between `qiskit.circuit` and `qiskit.qasm`, since `qiskit.qasm` is logically higher in the module hierarchy than `qiskit.circuit`.
Solving this circular dependency is another step down the path of being able to fully deprecate and remove the legacy `qiskit.qasm` code.
=> Remove circular dependency on `qiskit.qasm.pi`

qiskit/algorithms/minimum_eigensolvers/adapt_vqe.py, releasenotes/notes/adapt-vqe-thresholds-239ed9f250c63e71.yaml, test/python/algorithms/minimum_eigensolvers/test_adapt_vqe.py
- adds a new `eigenvalue_threshold` setting to the `AdaptVQE` which allows a more fine-tuned control of the convergence based on a minimal change of the eigenvalue with respect to an increasing ansatz
- renames the previously existing `threshold` attribute of the `AdaptVQE` to be called `gradient_threshold` in order to disambiguate it from the other (new) threshold mentioned above (using the old attribute will now log a `PendingDeprecationWarning`)
=> `AdaptVQE` threshold improvements

qiskit/providers/options.py, releasenotes/notes/options-implement-mutable-mapping-b11f4e2c6df4cf31.yaml, test/python/providers/test_options.py
This is an option for resolving #9686 by implementing the [`collections.abc.MutableMapping`](https://docs.python.org/3/library/collections.abc.html#collections.abc.MutableMapping) interface for the `Options` class. This automatically provides implementations of the suggested `items()` and of the existing `get()` methods.
As a `MutableMapping`, `Options` instances behave like mutable dictionaries with the extra validator feature. The `__setitem__` implementation goes through `update_options` to make sure that the validator is running. This is inconsistent with `__setattr__` but I understand that the namespace interface is there for backwards compatibility and running the validator may break use cases (although this would arguably be a logic error).
A side effect of implementing …
=> providers/options: implement Mapping

.azure/docs-linux.yml, .azure/lint-linux.yml, .azure/test-linux.yml, .azure/test-macos.yml, .azure/test-windows.yml, .azure/tutorials-linux.yml, .azure/wheels.yml, .github/workflows/coverage.yml, .github/workflows/randomized_tests.yml, .github/workflows/slow.yml
On some OSes and configurations (usually Windows), there can be problems when a binary attempts to one that is in use, especially itself.  For this reason, it is more reliable to use `python -m pip install ...` than `pip install`.  We have seen some CI failures on Windows due to `pip` failing to update itself because of the direct-executable `pip install` form.
=> Invoke `pip install` by module not executable

qiskit/qasm3/__init__.py, qiskit/qasm3/ast.py, qiskit/qasm3/experimental.py, qiskit/qasm3/exporter.py, qiskit/qasm3/printer.py, test/python/qasm3/test_export.py
This changes Terra's OpenQASM 3 exporter to add support for the IBM QSS `switch` extension to the OpenQASM 3 language.  This is currently only a pull request to the OpenQASM 3 specification, so its syntax might be subject to some amount of change, and it is hidden behind an "experimental" flag in the exporter.
See openqasm/openqasm#463.  Since the PR is not formally accepted yet, it is possible that the syntax might change slightly.  Terra is adding support for the feature eagerly, before acceptance, but essentially hidden behind a "vendor" flag (c.f. web browsers' `--moz`, `--webkit` etc CSS prefixes) until the proposal is formally accepted into the language.  The experimental feature flag is versioned as a precaution, so we can eagerly add support for new syntaxes if they are suggested, …
=> Add experimental OpenQASM 3 support for switch

qiskit/result/utils.py, releasenotes/notes/fix-marginal-distribution-np-ints-ee78859bfda79b60.yaml, test/python/result/test_counts.py, test/python/result/test_quasi.py
This commit fixes an oversight in the input type checking for the marginal_distribution() function. The function which is primarily written in rust has some quick input type checking to raise a more descriptive TypeError if the input distribution/counts object isn't of a known type (and also to dispatch to the correct rust function). This type checking was overly restrictive and would cause an error to be raised if an input counts dictionary was using numpy integer types as a value instead of a python int. This commit updates the type check to treat numpy ints as valid too.
=> Fix handling of numpy integers in marginal_distribution()

qiskit/providers/backend_compat.py
A custom calibration defined in `backend.defaults()` was silently dropped during the conversion to a target using `convert_to_target` in a certain case. Consequently, a `BackendV2` object converted from a `BackendV1` object using `BackendV2Converter` may not contain a custom calibration added to `BackendV1.defaults()` accidentally.
This commit adds a docstring that clearly describes when a custom calibration in `defaults` may be dropped and it is not recommended to update a BackendV1 object before conversion to `convert_to_target` and `BackendV2Converter` to avoid such a case.
=> Update docstrings on BackendV2Converter and convert_to_target 

qiskit/dagcircuit/dagcircuit.py, qiskit/transpiler/passes/routing/stochastic_swap.py, qiskit/transpiler/preset_passmanagers/common.py, releasenotes/notes/switch-case-9b6611d0603d36c0.yaml, test/python/compiler/test_transpiler.py, test/python/providers/test_fake_backends.py, test/python/transpiler/test_gates_in_basis_pass.py, test/python/transpiler/test_stochastic_swap.py, test/python/transpiler/test_target.py
For the most part, the heavy lifting for this was already done in the previous support for control flow.  This commit refactors some of the handling into larger, more descriptive helper functions, and most of the rest of the work is in testing.
I'm fairly confident there are some register-related problems to do with mappings in `DAGCircuit.substitute_node_*` and `QuantumCircuit.compose` right now, in both existing control flow and the new switch statement, which will need revisiting.
~Depends on #9916, #9919, #9926.  This PR currently contains a cherry-pick of all three of those, which will be rebased out before merge.~
=> Add support to `switch` in `transpile`

qiskit/transpiler/passes/layout/sabre_layout.py, test/python/compiler/test_transpiler.py, test/python/transpiler/test_sabre_layout.py
This commit fixes an issue in the `SabreLayout` pass when run on backends with a disjoint connectivity graph. The `SabreLayout` pass internally runs routing as part of its operation and as a performance efficiency we use that routing output by default. However, in the case of a disjoint coupling map we are splitting the circuit up into different subcircuits to map that to the connected components on the backend. Doing final routing as part of that split context is no sound because depsite the quantum operations being isolated to each component, other operations could have a dependency between the components. This was previously discovered during the development of #9802 to be the case with classical data/bits, but since merging that it also has come up with barriers. To prevent any issues …
=> Don't run routing in SabreLayout with split components

qiskit/providers/backend.py, qiskit/transpiler/passes/layout/sabre_layout.py, qiskit/transpiler/passes/routing/sabre_swap.py, qiskit/transpiler/target.py, test/python/compiler/test_transpiler.py, test/python/transpiler/test_target.py
Previously, the return value from `Target.build_coupling_map` could contain a shared reference to the underlying `PyDiGraph`, which subsequent calls to `make_symmetric` could mutate, affecting the backing `Target` and consequently backend.  This now always causes `build_coupling_map` to return a value that is fully owned by the caller, removes some now-redundant copies in other parts of the stack, and adds a manual cache into the `BackendV2.coupling_map` property to avoid performance surprises there.  `BackendV2.coupling_map` was previously relying on `build_coupling_map` being cached for its performance, so this makes it more explicit.
Fix #9997 
This is something we probably ought to logically do to avoid other surprises later down the line, and it immediately fixes the issue.  However, …
=> Give ownership of output from `Target.build_coupling_map`

.github/workflows/coverage.yml, .github/workflows/wheels.yml
The Node 12 runners are due to be removed from GitHub Actions this summer.  We updated most of them in 5d977fbf (gh-8856), but a couple remained un-updated.
The `actions-rs/toolchain` action is unmaintained.  The replacement used in this commit is actively updated, and has mostly the same interface, although the Rust version is typically specified using the action version.
The alternative to this is just installing calling `rustup` manually.
=> Upgrade straggler GitHub Actions to Node 16

qiskit/visualization/gate_map.py
A small typo:
> sequence **much mast** the number
instead of
> sequence **must match** the number
=> Fix typo in documentation - parameters description

azure-pipelines.yml
The nightly tests for the old 0.22 series are still running, and they're inconsistent with Aer 0.12, causing nightly failures.  This just disables them from running.
=> Disable cron runs on 0.22.x series

qiskit/providers/backend_compat.py, qiskit/providers/fake_provider/fake_backend.py, test/python/providers/test_fake_backends.py
This commit fixes an issue with the fake backend classes built on the BackendV2 that used ECR or CZ (or any 2q gate besides CX) as gates. The fundamental issue was the fake backend class had a hardcoded dict mapping gate names to classes to use for generating a target. This prevents the correct gate class from being reported when a backend uses gates outside of that dict. To fix this issue this commit switches the fake backends to use the convert_to_target function which is part of the BackendConverterV2 class. That function provides the same functionality as the one used internally by the fake provider except it is more general as its designed to work with any backend. At the time of its introduction this unification wasn't done because the fake backend's version would be more efficient …
=> Use backend_compat module's convert to target

test/python/circuit/test_controlled_gate.py
This PR removes a redefinition of RZGate matrix in the test file and makes the tests phase sensitive by removing the parameter `ignore_phase=True`
=> test_controlled_gate phase correct

qiskit/transpiler/passes/scheduling/alap.py, qiskit/transpiler/passes/scheduling/asap.py, qiskit/transpiler/passes/scheduling/base_scheduler.py, qiskit/transpiler/passes/scheduling/dynamical_decoupling.py, qiskit/transpiler/passes/scheduling/padding/base_padding.py, qiskit/transpiler/passes/scheduling/padding/dynamical_decoupling.py, qiskit/transpiler/passes/scheduling/padding/pad_delay.py, qiskit/transpiler/preset_passmanagers/common.py, releasenotes/notes/fix-delay-padding-75937bda37ebc3fd.yaml, test/python/compiler/test_transpiler.py, test/python/transpiler/legacy_scheduling/test_scheduling_pass.py, test/python/transpiler/test_dynamical_decoupling.py, test/python/transpiler/test_scheduling_padding_pass.py
Fixes delay padding in `transpile()` function and tranpiler passes to respect target's constraints.
`PadDelay` and `PadDynamicalDecoupling` are fixed so that they do not pad any idle time of qubits for which the `target` does not support `Delay` instruction. For that, the parent `BasePadding` as well as `PadDelay` is updated so that it optionally takes `target` argument. Legacy scheduling passes `ASAPSchedule` and `ALAPSchedule`, which pad delays internally, are also fixed in the same way. In addition, `transpile()` is fixed to call `PadDelay` with a `target` object so that it works correctly when called with `scheduling_method` option.
Fixes #9993
=> Fix delay padding to respect target's constraints

qiskit/quantum_info/operators/op_shape.py, releasenotes/notes/fix-0q-operator-statevector-79199c65c24637c4.yaml, test/python/quantum_info/states/test_statevector.py
The root of the problem was the `OpShape` producing a "vector-like" shape if it detected that "input size" was 1.  If both the input and output dimension are 1, it is instead a 0q operator (scalar).
Fix #10012
=> FIx 0q operation handling in `Statevector`

qiskit/circuit/quantumcircuit.py, releasenotes/notes/improve-quantum-circuit-assign-parameters-typing-70c9623405cbd420.yaml
This patch improves on the type annotations of the `qiskit.circuit.quantumcircuit.QuantumCircuit.assign_parameters` method.
The return type is now correctly narrowed depending on the `inplace` argument:
```python
qc = QuantumCircuit(...)
a = qc.assign_parameters(..., inplace=False)  # default
reveal_type(a)  # type: QuantumCircuit
b = qc.assign_parameters(..., inplace=True)
reveal_type(b)  # type: None
```
As an alternative to the verbose type overload, one could always return the bound circuit (as a reference to `self` when `inplace=True`). This should be backwards compatible since users of `inplace=True` should not be using the return value.
=> circuit: narrow the return type of QuantumCircuit.assign_parameters

qiskit/pulse/library/waveform.py, test/python/pulse/test_pulse_lib.py
`tostring` has been deprecated since numpy 1.17.
=> Replace deprecated function call

qiskit/transpiler/passes/scheduling/alignments/reschedule.py
The ConstrainedReschedule pass previosuly was using a recursive depth first traversal to push back overlapping gates after aligning operations. This however would cause a failure for a sufficiently large circuit when the recursion depth could potentially exceed the maximum stack depth allowed in python. To address this, this commit rewrites the depth first traversal to be iterative instead of recursive. This removes the stack depth limitation and should let the pass run with any size circuit.
~However, the performance of this pass is poor for large circuits. One thing we can look at using to try and speed it up is~ ~rustworkx's dfs_search() function which will let us shift the traversal to rust and call back to python to do the timing~ ~offsets.~ I tried this in …
=> Remove recursion from ConstrainedReschedule pass

test/python/algorithms/test_phase_estimator.py, test/python/primitives/test_backend_estimator.py, test/python/primitives/test_backend_sampler.py
Addresses the slow test errors https://github.com/Qiskit/qiskit-terra/actions/runs/4848239802/jobs/8639178931
This fixes the first error and revises the other tests to be more informative when error.
I could not reproduce the bound_pass_manager errors on my local environment.
#7864 
```
==============================
Failed 3 tests - output below:
==============================
test.python.algorithms.test_phase_estimator.TestHamiltonianPhaseEstimation.test_H2_hamiltonian
----------------------------------------------------------------------------------------------
Captured traceback:
~~~~~~~~~~~~~~~~~~~
File "/home/runner/work/qiskit-terra/qiskit-terra/qiskit/test/decorators.py", line 98, in _wrapper
return func(*args, **kwargs)
File …
```
=> Address slow test errors

qiskit/circuit/library/standard_gates/multi_control_rotation_gates.py, releasenotes/notes/0.24/su2-synthesis-295ebf03d9033263.yaml, test/python/circuit/test_controlled_gate.py
This utility function is used to construct multi-controlled Pauli rotations, but since it's a utility only used internally and we might need to move/adjust it, it would be better if it's a private function -- we can still turn it into a public one if we decide to.
=> Mark `mcsu2_real_diagonal` utility function as private

qiskit/transpiler/passes/synthesis/plugin.py, qiskit/transpiler/passes/synthesis/unitary_synthesis.py, releasenotes/notes/0.24/unitary-synthesis-based-on-errors-8041fcc9584f5db2.yaml, test/python/transpiler/test_unitary_synthesis_plugin.py
This commit reverts an unecessary breaking API change that was introduced in #9175. In that PR the data type for two arguments, gate_lengths and gate_errors, that was potentially passed to plugins was changed. This change was well intentioned as it was used by the default plugin as part of the changes to the default plugin made in that PR. But this neglected the downstream effects for any existing plugin interface users relying on the input to those fields. Making this change to existing fields would break any plugins that were using the old data format and is a violation of the Qiskit stability and deprecation policy. This commit reverts that change so that gate_lengths and gate_errors contain the same data format as in previous releases. Instead to facilitate the new workflow a new …
=> Undo breaking API change in unitary synthesis plugin interface

qiskit/circuit/quantumcircuit.py, releasenotes/notes/new-circuit-qasm2-methods-b1a06ee2859e2cce.yaml, test/python/qasm2/test_circuit_methods.py, test/python/qasm2/test_legacy_importer.py
This uses the extensibility and the legacy compatiblity data in the new Rust OpenQASM 2 parser to switch over the old `QuantumCircuit` constructor methods to the new parser.  This gives users of these methods large speedups while maintaining the same feature set (and fixing a long-standing bug surrounding `U` and `CX`!).
One test is removed for the circuit methods; the circuit methods are set to use `strict=False` mode of the new parser, which is more permissive, including making the empty string an allowable program.  The alternative was to set `strict=True`, which would have made an unrelated test in `SabreLayout` fail instead due to its slightly improper use of floating-point values in OpenQASM 2 (the OQ2 spec technically requires decimal points even in constructs like `1e3`, unlike …
=> Switch `QuantumCircuit.from_qasm_str` and `from_qasm_file` to new parser

qiskit_bot.yaml
Every user who I changed in this PR was getting two forms of notifications when new PRs open up:
1. Code owners from GitHub, since the `CODEOWNERS` file matches them
2. An `@` mention from the Qiskit bot, due to our config file.
That's noisy. Instead, this PR turns off the bot notifications and relies on code owners.
We still think it's valuable to list these people in the Qiskit bot comment so contributors know who is relevant to the code. But, we escape the users with \` so that they don't get the notification.
=> Turn off Qiskit Bot notifications for code owners

crates/accelerate/src/euler_one_qubit_decomposer.rs, releasenotes/notes/fix-transpile-pickle-4045805b67c0c11b.yaml, test/python/compiler/test_transpiler.py, test/python/transpiler/test_optimize_1q_decomposition.py
Fixes https://github.com/Qiskit/qiskit-terra/issues/10091
=> define __getstate__ and __setstate__ for OneQubitGateErrorMap

Makefile
In #1973 the Makefile was updated to add manual concurrency handling to the invocation of stestr. At the time (> 4 yrs ag) our CI setup looked very different, everything was run in TravisCI which had much smaller memory quotas in the worker VMs and we also were actively using the Makefile to run tests. Since that time though CI and our development workflow have changed. At the time running multiple tests in parallel was causing us to exhaust the available RAM in the CI workers for MacOS and Windows so we set concurrency limits to prevent this. However, we no longer use travis, and the use of the makefile has long since been replaced by using tox as it provides a unified interface that manges venvs along with running tests in a consistent way across systems (including locally and CI). This …
=> Remove concurrency handling from Makefile stestr usage

qiskit/tools/jupyter/jupyter_magics.py, qiskit/tools/jupyter/library.py, releasenotes/notes/deprecate-circuit-library-jupyter-629f927e8dd5cc22.yaml
This has not been used since the switch away from using `jupyter-execute` in gh-9346, so is neither maintained nor necessary. Any improvements to styling should be made to the new paths, not to these.  These objects were originally intended only for the documentation so we expect user impact to be minimal, and the objects are not maintained anyway.
These are the only direct users of the Pygments lexer that caused us problems that needed a fix in #9938.  We planned to deprecate these in https://github.com/Qiskit/qiskit-terra/pull/9346#discussion_r1063358895, but we failed to follow up on it at the time.
=> Deprecate circuit-library Jupyter magic

CITATION.bib, README.md
_Originally posted by @garrison in https://github.com/Qiskit/qiskit-metapackage/issues/1722#issuecomment-1545938188_
> Just noticed that `CITATION.bib` needs to move as well.  Otherwise, the link from the Terra README will be broken after `qiskit-terra` -> `qiskit`.
This is related with [`RFC 0011`](https://github.com/Qiskit/RFCs/blob/master/0011-repo-rename.md )
=> CITATION.bib from metapackage

qiskit/circuit/classicalfunction/boolean_expression.py, releasenotes/notes/fix-exception-from_dimacs_file-b9338f3c913a9bff.yaml
This commit fixes an oversight in the 0.24.0 release that caused an accidental change in the exception raised when attempting to use BooleanExpression.from_dimacs_file without having tweedledum installed. In #9754 the detection of tweedledum was updated to avoid import time detection so that the module can be imported even if tweedledum isn't installed. This was done through the use of the optionals decorators so that tweedledum is only attempted to be imported when the classicalfunction modules is used. However, the decorators don't wrap classmethod constructors by default and this caused the incorrect exception type to be raised. This commit fixes this by doing the runtime checking manually inside the from_dimacs_file constructor.
=> Fix tweedledum runtime detection in BooleanExpression.from_dimacs_file

test/python/algorithms/optimizers/test_umda.py, test/python/circuit/library/test_nlocal.py, test/python/quantum_info/operators/symplectic/test_pauli_list.py, test/python/result/test_quasi.py
Mainly a follow-up to #8695, where we noticed some plain `assert` statements used instead of the appropriate `unittest` methods. Also replaces those in some other tests and removes a dangling commented `assert` line.
=> Replace `assert` in tests with unittest methods

test/python/primitives/test_backend_estimator.py, test/python/primitives/test_backend_sampler.py
The slow nightly tests have been failing for a while on a specific unit test for the backend primitives (https://github.com/Qiskit/qiskit-terra/issues/7864#issuecomment-1556493785) that seems to be pretty hard to reproduce locally/on CI (at least, I haven't been able to). 
I don't know exactly why these tests are failing, but I find it suspicious that there are two consecutive assertions that reuse the same instance of `DummyTP()` and they always fail on the second one. I know that the order of tests shouldn't matter, but I don't know, there might be some interference related to reusing instances with `mock`. 
After spending some time trying to reproduce the failure unsuccessfully, I figured that it might make sense to push a potential fix and see if it works. I have separated the test …
=> Attempt to fix backend primitives unittest failure on slow tests

qiskit/transpiler/passes/calibration/rzx_builder.py, releasenotes/notes/fix-exception-decription-3ba0b5db82c576cf.yaml, test/python/transpiler/test_calibrationbuilder.py
Fix https://github.com/Qiskit/qiskit-terra/issues/10113
=> Remove undefined variable

qiskit/compiler/transpiler.py, releasenotes/notes/fix-initial_layout-loose-qubits-0c59b2d6fb99d7e6.yaml, test/python/compiler/test_transpiler.py
The previous logic around building a `Layout` object from an `initial_layout` was still couched in the "registers own bits" model, so could not cope with loose bits.  It's most convenient to just build the mapping ourselves during the parsing, since the logic is quite specific to the form of the `initial_layout` argument, rather than being something that's inherently tied to the `Layout` class.
Fix #10125.
=> Fix `initial_layout` in `transpile` with loose qubits

qiskit/pulse/library/symbolic_pulses.py
The doc strings for SymbolicPulse's Sawtooth, Triangle, Cos, Sin had an erroneous "&" sign.
=> Minor docs correction for SymbolicPulse library

qiskit/circuit/__init__.py
I cleared a small typo in this file  
as as to as a
=> Update the typo in __init__.py

qiskit/circuit/quantumcircuit.py, releasenotes/notes/fix-compose-switch-19ada3828d939353.yaml, test/python/circuit/test_compose.py
The register-mapping code was not being applied to `SwitchCaseOp.target` in the same way that it is for conditions.  This commit does not change any behaviour about recursing into _nested_ control-flow blocks, which still likely have problems with composition.
Fix #10108, at least as far as the top-level issue that's being reported there.  See that issue for a further discussion of other problems that stem from the root of that issue.
=> Fix top-level `switch` statements in `QuantumCircuit.compose`

qiskit/transpiler/passmanager_config.py, releasenotes/notes/fix-pm-config-from-backend-f3b71b11858b4f08.yaml, test/python/transpiler/test_passmanager_config.py
This commit fixes an issue in the PassManagerConfig.from_backend constructor method when using BackendV1 based simulator backends. The pass was incorrectly handling the case when the backend configuration didn't have a coupling map defined and incorrectly creating a coupling map with 0 qubits instead of using None to indicate the lack of connectivity. This has been fixed so the coupling map creation is skipped if there is no coupling map attribute in the backend's configuration.
Fixes #10171
=> Fix PassManagerConfig.from_backend with BackendV1 and no CouplingMap

.azure/lint-linux.yml, CONTRIBUTING.md, Makefile, pyproject.toml, requirements-dev.txt, tox.ini
This adds linting using `ruff` to the relevant configuration files. Only a few rules are enabled and none of them trigger an error in the current state of 	qiskit-terra.
The immediate goal of this PR is to test integrating `ruff` into local workflows as well as CI.  This is the reason why only very few rules are enabled, and none necessitated code changes.
If this PR is successful, more `ruff` rules will be added in subsequent PRs.
=> Add ruff to local tests and CI

Cargo.lock, crates/accelerate/Cargo.toml, crates/accelerate/src/edge_collections.rs, crates/accelerate/src/error_map.rs, crates/accelerate/src/nlayout.rs, crates/accelerate/src/sabre_swap/neighbor_table.rs, crates/accelerate/src/sabre_swap/sabre_dag.rs, crates/qasm2/Cargo.toml, crates/qasm2/src/lib.rs
PyO3 0.19.0 and rust-numpy 0.19.0 were just released. This commit updates the version used in qiskit to these latest releases. At the same time this updates usage of text signature for classes that was deprecated in the PyO3 0.19.0 release. While not fatal for normal builds this would have failed clippy in CI because we treat warnings as errors.
=> Bump pyo3 and rust numpy version to 0.19.0

qiskit/circuit/quantumcircuit.py, releasenotes/notes/circuit-assign-parameter-to-concrete-value-7cad75c97183257f.yaml, test/python/circuit/test_circuit_load_from_qpy.py, test/python/circuit/test_parameters.py, test/python/qasm3/test_export.py
Changed `QuantumCircuit.assign_parameters` so that assigning a concrete value to a parameter inserts that value directly into the circuit's instructions' parameter rather than inserting a `ParameterExpression` containing only that value.
When `QuantumCircuit.assign_parameters` is called, parameter substitution occurs in the list of parameters for each instruction, in the definition of each instrution, in the global phase of the circuit, and in the mapping of gates to schedules in the circuit's calibrations dictionary. Before this change, numeric assigned values were inserted into the instructions' parameters lists as `ParameterExpression` instances with no free parameters and into the calibrations dictionary as floats. This discrepancy in handling of parameters in these two cases was a …
=> Assign values directly to fully bound parameters in quantum circuits

qiskit/circuit/library/standard_gates/global_phase.py
Fixed typo in issue #10198. Changed "Mathamatical" to "Mathematical" for GlobalPhaseGate in Qiskit docs.
=> Fix typo issue #10198

qiskit/quantum_info/states/densitymatrix.py, releasenotes/notes/fix-partial-transpose-output-dims-3082fcf4147055dc.yaml, test/python/quantum_info/states/test_densitymatrix.py
Add dimensions to the `DensityMatrix` returned by `partial_transpose` so its dimensions match those of the input density matrix.
Fix #10155
=> Fix output of `DensityMatrix.partial_transpose` to match input dimensions

qiskit/visualization/circuit/circuit_visualization.py, releasenotes/notes/fix-regression-in-the-LaTeX-drawer-of-QuantumCircuit-7dd3e84e1dea1abd.yaml
Per the discussion in #10211 I've filed this quick fix. 
When calling `QuantumCircuit.draw('latex', out.pdf)`, the program breaking when qiskit tries to move the compiled pdf from the tmp folder to the target directory. The generated pdf is then deleted alongside the tmp folder.
The bug is due to 'os.rename(...)' not working properly across filesystems.
Resorting to `shutil.move(...)` solved the problem.
I'm afraid there isn't a test I can add for the bug since it is device-dependent.
=> Fix QuantumCircuit.draw() not outputting pdf in latex mode

test/python/compiler/test_transpiler.py
The previous method of running the assertions in these tests could produce false negatives if routing caused an operation to take place on a virtual qubit that was initially an ancilla.  It was tricky to make sensible assertions in these cases, since it is slightly fiddly to determine which ancillas have been assigned to which physical components of the chip.  This lead to `optimization_level=1` being skipped in one test, because the routing would use these ancillas.
This refactors the test to be more resistant to valid choices the routing algorithm might make.  We instead find _all_ the physical qubits that are in each connected component, determine the mapping of virtual qubits to components, and then make assertions based on the physical qubits.  This is resistant to ancillas being …
=> Refactor disjoint routing tests to be more resilient

.github/workflows/coverage.yml, constraints.txt
The release of Aer 0.12.1 included a bug in the results output that made the general `Result` object unpickleable.  Several places in our tests assume that these objects should be able to be pickled to be sent across a process boundary, or such like.
See Qiskit/qiskit-aer#1845
=> Pin Aer to known good version

qiskit/transpiler/passes/routing/basic_swap.py, releasenotes/notes/fix-basicswap-fakerun-7469835327f6c8a1.yaml, test/python/transpiler/test_basic_swap.py
This is a repeat of #10149. This change is fixing a minor typo, where a variable was referenced instead of a method.
I initially made changes directly on the main branch of my forked repository, and opened a PR from this branch. Instead, I should have first created a new branch from main, made my changes on this new branch, and then opened the PR from the new branch. This error led to conflicts with the upstream main branch, requiring me to reset and force push on main, which closed the original PR.
As far as I can tell, opening a new PR is the best practice for fixing this mistake.
=> Fix BasicSwap FakeRun Typo

qiskit/primitives/backend_estimator.py, qiskit/primitives/base/base_estimator.py, qiskit/primitives/estimator.py, qiskit/primitives/utils.py, releasenotes/notes/fix-primitives-import-warnings-439e3e237fdb9d7b.yaml
The primitives still need to support the legacy
`qiskit.opflow.PauliSumOp` while that object is deprecated but not removed.  However, we do not want the import of `qiskit.primitives` to need to import `opflow` to do that, since that will cause the deprecation warnings emitted by the import of `opflow` to be hidden (they'll be blamed on Qiskit library code, so hidden by default).
All type-hint usage we can hide behind the `TYPE_CHECKING` static analysis gate.  For cases where we were actively runtime type-checking an object, we can gate the `isinstance` check behind a check that `qiskit.opflow` is already imported; the object cannot be a `PauliSumOp` if the module isn't initialised.
Fix #10245
=> Fix deprecation warnings emitted by `import qiskit.primitives`

qiskit/circuit/quantumcircuit.py, releasenotes/notes/fix-qasm-circuit-export-943394536bc0d292.yaml, test/python/circuit/test_circuit_qasm.py
Before this fix, the resulting qasm for a circuit with inner gates sequentially added with the same name, was wrong.
Some Algorithms, like Grover's algorithm, produce a wrong qasm by this problem.  
To fix it, just a name recheck was added!
See #10162 for further information
=> Fix qasm export for gates with same name

qiskit/circuit/library/standard_gates/equivalence_library.py, releasenotes/notes/add-pauli-equivalences-74c635ec5c23ee33.yaml, test/python/compiler/test_transpiler.py
This makes `transpile` a little more reliable in cases where people are trying to use it to convert to a constrained basis.  We can't necessarily recognise _all_ possible transformations into an incomplete basis, but simple Pauli relations are things people may well expect.
Fix #10293.
=> Add standard 1q Pauli equivalences to standard library

constraints.txt
We are not (should not be) fundamentally incompatible with Numpy 1.25, there are just new deprecation warnings and seemingly some behavioural changes that are causing flakiness in the isometry CI.  This temporarily pins Numpy to allow people to continue working while we address the root cause.
Workaround #10305.
=> Pin Numpy to less than 1.25 in CI

qiskit/opflow/primitive_ops/pauli_op.py, qiskit/opflow/primitive_ops/pauli_sum_op.py, qiskit/quantum_info/operators/channel/chi.py, qiskit/quantum_info/operators/channel/choi.py, qiskit/quantum_info/operators/channel/ptm.py, qiskit/quantum_info/operators/channel/stinespring.py, qiskit/quantum_info/operators/channel/superop.py, qiskit/quantum_info/operators/channel/transformations.py, qiskit/quantum_info/operators/operator.py, qiskit/quantum_info/operators/random.py, qiskit/quantum_info/operators/symplectic/pauli_list.py, qiskit/quantum_info/states/densitymatrix.py, qiskit/quantum_info/states/random.py, qiskit/quantum_info/states/statevector.py, qiskit/result/mitigation/local_readout_mitigator.py, qiskit/synthesis/discrete_basis/commutator_decompose.py, qiskit/transpiler/passes/synthesis/unitary_synthesis.py, test/python/quantum_info/operators/test_random.py, test/python/quantum_info/operators/test_scalar_op.py, test/python/quantum_info/states/test_random.py
Most of the effects we see are because of the removal of various aliases (`np.product` being a common one), but the new warning on implicit conversion of size-1 arrays to scalars that was initially found in parts of c463b3c has reared its head again too.
This is not a complete resolution of #10305 because of larger issues with correctness of the `Isometry` code triggered by Numpy 1.25.  It should fix all the new deprecation warnings, though.
=> Fix Numpy 1.25 deprecations

qiskit/algorithms/eigensolvers/vqd.py, releasenotes/notes/fix-vqd-result-27b26f0a6d49e7c7.yaml, test/python/algorithms/eigensolvers/test_vqd.py
Fixes #10263 
I think that there should be a unit test checking this, will add soon.
=> Fix VQD's `optimal_values`

pyproject.toml
This got missed during 4dfef130, and is needed to avoid Pylint complaining about standard-library features that were added after the minimum version it thinks we're on.
See also #10009.
=> Update minimum Python version for `pylint`

docs/apidocs/passmanager.rst, docs/apidocs/terra.rst, qiskit/passmanager/__init__.py, qiskit/passmanager/base_pass.py, qiskit/passmanager/exceptions.py, qiskit/passmanager/flow_controllers.py, qiskit/passmanager/passmanager.py, qiskit/passmanager/passrunner.py, qiskit/passmanager/propertyset.py, qiskit/transpiler/__init__.py, qiskit/transpiler/basepasses.py, qiskit/transpiler/exceptions.py, qiskit/transpiler/passmanager.py, qiskit/transpiler/propertyset.py, qiskit/transpiler/runningpassmanager.py, releasenotes/notes/add-passmanager-module-3ae30cff52cb83f1.yaml
This PR adds new `qiskit.passmanager` module and reorganizes `qiskit.transpiler`. New module implements a generic pass manager which is not sensitive to object types (input, output, IR) under transformation, and only provides a management for pass execution.
1 of 2 PRs. Pass manager internals will be refactored in the follow up.
The internal logic is almost as-is. One visible change is in `qiskit.passmanager.passrunner`. This provides `BasePassRunner` which is a superclass of `RunningPassManager`. New base class implements
- `BasePassRunner._to_passmanager_ir`
- `BasePassRunner._to_target`
- `BasePassRunner._run_base_pass`
which are all abstract methods. These are type sensitive and intended to be implemented by a subclass for particular data types, e.g. for existing pass manager, input: …
=> Pass manager refactoring: add passmanager module

pyproject.toml, qiskit/circuit/library/standard_gates/x.py
A very minor fix and enable `used-before-assignment`.
Relates to #9614
=> pylint: enable used-before-assignment

pyproject.toml, qiskit/pulse/transforms/alignments.py, qiskit/qpy/binary_io/schedules.py, qiskit/quantum_info/operators/scalar_op.py, qiskit/visualization/pulse_v2/plotters/matplotlib.py, qiskit/visualization/timeline/layouts.py, qiskit/visualization/timeline/plotters/matplotlib.py
Turn on `pointless-exception-statement` pylint warning.
It turns out we had a  half-dozen instances where we were indeed creating  an  exception without raising it, so I fixed them.
Obviously, those exception cases did not have test coverage and I have not created tests to cover them here.
Relates to #9614
=> Pylint: enable pointless-exception-statement

qiskit/circuit/library/n_local/real_amplitudes.py
Correct small typo in real_amplitude.py file.
Fixes #10340
Erased repeated "of"
=> fix typo in real_amplitude.py

constraints.txt
The newest Scipy on Windows seems to have caused a convergence error in some of the Weyl-chamber code.  This pins Scipy temporarily while we resolve that issue.
See #10345 for more detail.
=> Temporarily pin `scipy<1.11` in CI

pyproject.toml, test/python/quantum_info/test_synthesis.py
This gives a tiny readability improvement and slightly removes one more line from the config file
Relates to #9614
=> pylint: enable consider-using-from-import

.github/workflows/neko.yml
Ideally we'd be running the Neko tests against the requirements that will actually form the complete package.  In practice, however, there are persistent failures from Neko stemming from PySCF's use of SciPy, which we get via Nature, which is no longer under Qiskit control.
While we work out what the future of the Neko test suite is, with the application modules now no longer being IBM-managed Qiskit packages, we can apply the CI constraints so we can return to getting reports from the parts of the integration tests that are actually within our control.
We might choose to revert this in the future, when we've got a different view on what the Neko tests will look like in the future.  We can also revert it more eagerly, if PySCF makes a new release that includes pyscf/pyscf#1771, since the …
=> Honour CI constraints in Neko tests

azure-pipelines.yml
GitHub Actions have uploaded a fixed version of Python 3.7.17 on macOS, so we should be able to release this pin now.
See #10307.
=> Unpin macOS CI from Python 3.7.16

qiskit/transpiler/passes/utils/check_map.py, releasenotes/notes/fix-checkmap-nested-condition-1776f952f6c6722a.yaml, test/python/transpiler/test_check_map.py
The recursion inside the `CheckMap` pass was based on a custom `DAGCircuit.compose` solution, rather than the more standard qubit-argument-binding setup we normally use.  This did not pass in the clbit ordering to the composition, which could cause it to fail to map nested conditional statements.
Instead, we can just enter each DAG naturally, and use the regular wire map to access the physical indices being referred to.
Fix #10394.
=> Fix `CheckMap` with control-flow builder nested conditionals

qiskit/algorithms/minimum_eigensolvers/qaoa.py, qiskit/circuit/library/standard_gates/u3.py, qiskit/circuit/register.py, qiskit/compiler/transpiler.py, qiskit/execute_function.py, qiskit/pulse/library/parametric_pulses.py, qiskit/quantum_info/operators/symplectic/sparse_pauli_op.py, qiskit/result/mitigation/correlated_readout_mitigator.py, qiskit/result/mitigation/local_readout_mitigator.py, qiskit/transpiler/passes/optimization/template_matching/template_matching.py, qiskit/transpiler/passes/synthesis/solovay_kitaev_synthesis.py
This PR fixes the bullet list for the transpilation level in the documentation, besides some other small issues (like double "the"s)
Before 
After
=> small fixes in docs: bullet lists in transpiler levels

qiskit/quantum_info/__init__.py, qiskit/quantum_info/states/__init__.py, qiskit/quantum_info/states/measures.py, releasenotes/notes/add-feature-negativity-logarithmic-negativity-fce5d8392460a0e9.yaml, test/python/quantum_info/states/test_measures.py
I and @PayalSolanki2906 are adding the feature which can be used to calculate the entanglement measures negativity and logarithmic negativity. To this end, we have created a function: `negativity` inside `qiskit.quantum_info.states.measures` module.
=> Adding the feature of calculating entanglement measures negativity

qiskit/circuit/bit.py, releasenotes/notes/fix-bit-copy-4b2f7349683f616a.yaml, test/python/circuit/test_bit.py
Overrides the default behavior of `copy` and `deepcopy` for `Bit` to return `self` for new-style bits.
We choose this behavior because `Bit`s are immutable, and it allows us to deep-copy new-style bits while maintaining equality between the original and the copy. For old-style bits, we leave the behavior unchanged, since some existing code appears to depend on `_register` getting deep-copied.
Note that we now return `self` when shallow-copying old-style bits, which we can do safely since `Bit`s themselves are immutable.
Resolves #10409.
=> Fix `deepcopy` for new-style `Bit`

qiskit/algorithms/gradients/reverse/derive_circuit.py, qiskit/algorithms/gradients/reverse/split_circuits.py, qiskit/algorithms/gradients/utils.py, qiskit/circuit/quantumcircuit.py, qiskit/quantum_info/synthesis/qsd.py, qiskit/transpiler/passes/basis/basis_translator.py, test/python/circuit/test_circuit_load_from_qpy.py, test/python/circuit/test_circuit_operations.py, test/python/transpiler/test_clifford_passes.py
This removes (as best as our test suite touches) all uses of the implicit legacy tuple form of `CircuitInstruction` that have crept in since ea02667 (gh-8093).  The changes are largely just mechanical over to the new form.
This PR doesn't propose the deprecation of the legacy interface yet.  At the very least, that should come early in the cycle for a Terra version, and we know there to be uses in downstream Qiskit projects (Aer and Experiments each have a couple of fairly minor instances) that we can mitigate first.
=> Reduce use of legacy `CircuitInstruction` formats

test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py, test/visual/mpl/graph/test_graph_matplotlib_drawer.py
In the recently merged #9961 the visual comparison tests were re-added to run a visual diff on the visualization output against a known reference image. These improved tests provide us missing coverage and have already found potential bugs in proposed changes, see:
https://github.com/Qiskit/qiskit-terra/pull/10208#discussion_r1260234421
However, the comparison were looking for a 100% match between the reference image and the generated output. In an ideal world we'd be able to rely on this. But in practice an exact comparisons of the images are quite flaky. This is because the actual visualization output is a function of not only our python code in Qiskit, but also upstream python dependencies (such as matplotlib, seaborn, etc) and more importantly those libraries leverage many system …
=> Add 1% tolerance to visual tests

constraints.txt
With the release of Aer 0.12.2, the CI problems we were having caused by non-picklability of the Aer `Result` objects are now be resolved.
See #10270 for the initial pin.
=> Relax pin on `qiskit-aer==0.12.0` in CI

qiskit/circuit/quantumcircuit.py, test/python/circuit/test_circuit_properties.py
Commit e2674ce (gh-10416) reduced usage of the legacy format for `CircuitInstruction` within Terra, but one of the changes meant that a previously valid input to a public API function became invalid.  This caused Qiskit Experiments' CI to fail, and wasn't a valid change to Terra.
=> Fix API break in `QuantumCircuit.has_calibration_for`

qiskit/transpiler/passes/synthesis/unitary_synthesis.py, releasenotes/notes/fix-synthesis-cf-mapping-fe9bd2e5fbd56dfb.yaml, test/python/transpiler/test_unitary_synthesis.py
Fixes an issue with the `UnitarySynthesis` pass where circuits with control flow were not properly mapped to the provided ``target``.
Issue found while enabling control flow support in optimization level 3.
https://dev.azure.com/qiskit-ci/qiskit-terra/_build/results?buildId=47531&view=logs&j=80763036-ed5e-5d3e-143d-8ae8edc29f03&t=0b590cc4-1220-55fc-f610-714bdf68abc8&l=24136
=> Fix inner qubit mapping in `UnitarySynthesis`

docs/apidocs/circuit_classical.rst, docs/apidocs/terra.rst, qiskit/circuit/classical/__init__.py, qiskit/circuit/classical/expr/__init__.py, qiskit/circuit/classical/expr/constructors.py, qiskit/circuit/classical/expr/expr.py, qiskit/circuit/classical/expr/visitors.py, qiskit/circuit/classical/types/__init__.py, qiskit/circuit/classical/types/ordering.py, qiskit/circuit/classical/types/types.py, test/python/circuit/classical/__init__.py, test/python/circuit/classical/test_expr_constructors.py, test/python/circuit/classical/test_expr_properties.py, test/python/circuit/classical/test_types_ordering.py
This adds a method of representing a classical type system and expression tree in Qiskit.  This initial version contains only simple bitwise, logical and relational operations on Booleans and sized unsigned integers.  This is largely in line with
https://github.com/Qiskit/RFCs/blob/0dd13344/0010-simple-classical-representations.md
Some of the details surrounding construction and representation have been changed slightly from that design, but the type system described is the same.
In particular, this commit slightly modifies the representation of the tree; instead of individual tree items for each unary and binary operation, they are part of the `Unary` and `Binary` nodes with a respective enumeration discriminator in the node.  This was done to make visitors to the expression tree require …
=> Add initial representation of classical expressions

qiskit/circuit/instruction.py, qiskit/circuit/quantumcircuit.py, qiskit/qasm/__init__.py, qiskit/qasm/exceptions.py, test/python/circuit/test_gate_definitions.py
Since gh-9784 added a new `qiskit.qasm2` package and suitable exceptions for both import and export of OpenQASM 2 programs, this commit now unifies the exception handling through the rest of the library to use these exceptions.
To avoid breaks in compatibility, the old `qiskit.qasm.QasmError` is now a re-export of `qiskit.qasm2.QASM2Error`.  This is the base error of both the exporter and importers, despite the old documentation of `QasmError` claiming to be specifically for parser errors.  In practice, the exporter also emitted `QasmError`, so having that be `QASM2Error` allows people catching that error to get the same behaviour in these new forms.  The actual exporter and importer are updated to emit the precise subclasses.
Probably this will clash a little with #9955 (and this PR …
=> Unify OpenQASM 2 exceptions

qiskit/dagcircuit/dagcircuit.py, qiskit/transpiler/passes/layout/sabre_layout.py, qiskit/transpiler/passes/routing/sabre_swap.py, test/python/converters/test_circuit_to_dag.py, test/python/dagcircuit/test_dagcircuit.py
This adds support to the `DAGCircuit` builder methods `apply_operation_front` and `apply_operation_back`, and consequently to the converter `circuit_to_dag`.  This commit does not directly enhance `DAGCircuit.compose`, which will come later.
The principal change is that `_bits_in_condition` is modified to the more general `_bits_in_operation`, which now accounts for both a `condition` (if set) and any additional fields from a `target` if the operation is a suitable `ControlFlowOp`.  This has the effect of upgrading the converters into the `SabreDAG` format as well, but nothing is done to change the Sabre algorithms themselves.
Close #10226.  Depends on #10358.  Changelog to follow as part of #10331.
The change of `_bits_in_condition` to `_bits_in_operation` likely does most of the …
=> Add `Expr` supprt to `DAGCircuit` simple constructors

qiskit/circuit/parameter.py, qiskit/circuit/parametervector.py
This commit optimizes the construction code for the ParameterVector and ParameterVectorElement classes. The construction of these objects was primarily dominated by the UUID construction time. This is because each element in the vector was calling uuid4() to generate a random unique identifier for each Parameter element. However, we don't need a truly random identifier as we just need to avoid collisions with identically named elements. So instead of calling uuid4() n times this commit opts to call uuid4() once and then just use an index offset of that value. This is slightly faster because we don't need to need run the full uuid4 algorithm each time and instead just wrap an integer in uuid object. While this does slightly increase the change of a collision between identically named …
=> Slightly optimize ParameterVector construction

requirements.txt
The current release branch of Terra could never match this requirement any more, so it's not needed.
Introduced in #8828.
=> Drop Python-3.7 pin on `importlib-metadata`

qiskit/quantum_info/operators/symplectic/clifford_circuits.py, releasenotes/notes/clifford-no-circuly-c7c4a1c9c5472af7.yaml, test/python/quantum_info/operators/symplectic/test_clifford.py
This reliance on `RecursionError` could lead to CPython crashing, when the user had raised the recursion limit beyond what their operating system could actually support in terms of Python frames.  This was particularly an issue with Windows when in a context that `jedi` is active (such as in an IPython session, or if `seaborn` was imported), since `jedi` unilaterally sets the recursion limit to 3000, while CPython tends to overflow the stack on Windows at around 2700 frames.
Recursive `definition` fields are not valid data in the Qiskit model, as the definition is supposed to be hierarchical, and a decomposition in terms of gates that do not involve the current one in any form.  For defining equivalences that may involve cycles, one should use the `EquivalenceLibrary` objects that Terra …
=> Remove cyclic-definition handling from `Clifford.from_circuit`

qiskit/qasm3/ast.py, qiskit/qasm3/exporter.py, qiskit/qasm3/printer.py, releasenotes/notes/qasm3-alias-refactor-3389bfce3e29e4cf.yaml, test/python/qasm3/test_export.py
This removes spurious `_loose_bit` "registers" from the OpenQASM 3 output, and instead emits loose bits with individual `bit` and `qubit` declarations.  Non-overlapping registers are emitted using regular `bit[n]` and `qubit[n]` definitions when possible, and we only resort to aliasing if we must to describe the structure.
This avoids introducing structure to the definitions that does not exist in the original program, making round-trips and interactions with other OQ3 consumers more straightforwards.  It's better not to use advanced features that don't map to hardware particularly well when it's not necessary.
On the technical side, all bits are now properly tracked in the symbol table.  Previously, there was a lot of code duplication, internal state tracking and magic inferences that …
=> Refactor output of OpenQASM 3 exporter to use fewer aliases

qiskit/circuit/classical/expr/__init__.py, qiskit/circuit/classical/expr/visitors.py, qiskit/circuit/controlflow/switch_case.py, qiskit/converters/circuit_to_dag.py, qiskit/dagcircuit/dagnode.py, test/python/circuit/classical/test_expr_helpers.py, test/python/converters/test_circuit_to_dag.py, test/python/dagcircuit/test_dagcircuit.py
This adds support to semantically check the variables of `Expr` nodes that occur within `DAGCircuit` constructs, using similar logic to the remapping done by the existing condition checks.  As a knock-on effect of how the control-flow introspection was added to allow these checks, the canonicalisation performed by `qiskit.test._canonical.canonicalize_control_flow` is now inherent to the `DAGCircuit` equality methods, largely removing the need for that explicit canonical form in tests.
The dispatch of `QuantumCircuit.__eq__` to `DAGCircuit.__eq__` means that direct comparisons of `QuantumCircuit`s will also benefit from this change.
As a partial implementation detail, the semantic checking is achieved and defined by the function `expr.structurally_equivalent`, with key functions for …
=> Add support for semantic equality checking of `Expr`s in `DAGCircuit`

qiskit/circuit/quantumcircuitdata.py
This was originally added as a mitigation for performance loss in consumers of `QuantumCircuit.data` that were still using the legacy interface.  It is now becoming more critical to minimise memory usage in the `QuantumCircuit` object, so the extra slot is a luxury we can no longer afford.
This represents a 12.5% reduction in the inherent memory footprint of `CircuitInstruction`, though in practice the impact will be smaller, since the `operation` and `qubits` fields will near-universally have associated weight themselves (the `clbits` field is _usually_ the empty tuple, with is a natural singleton untracked by the GC in CPython). Other ongoing work on making more objects singletons will reduce those weights, however.
100% of the performance impact of this change _within Terra_ should be …
=> Remove `_legacy_format_cache` slot from `CircuitInstruction`

qiskit/transpiler/preset_passmanagers/level1.py, releasenotes/notes/sabre-ctrl-flow-o1-431cd25a19adbcdc.yaml, test/python/transpiler/test_preset_passmanagers.py
Enables Sabre layout and routing for control flow circuits at optimization level 1.
Depends on #10366.
Resolves #9422
=> Enable Sabre for control flow circuits at O1

qiskit/circuit/_classical_resource_map.py, qiskit/circuit/quantumcircuit.py, qiskit/dagcircuit/dagcircuit.py, test/python/dagcircuit/test_compose.py
The remapping facilities are (except for some esoteric behaviour for mapping registers to others in a different order) the same as for `QuantumCircuit`, so it makes sense to unify the handling.  As part of switching the old `DAGCircuit` classical-resource-mapping methods over to the new general-purpose forms, this does most of the necessary work to upgrade `substitute_node_with_dag` as well.
Resolve #10230.  Depends on #10375 (since I elected to generalise some of the new handling from that PR).  Changelog in #10331.
=> Add `Expr` support to `DAGCircuit.compose`

qiskit/circuit/controlflow/builder.py, qiskit/circuit/controlflow/if_else.py, qiskit/circuit/controlflow/switch_case.py, qiskit/circuit/controlflow/while_loop.py, releasenotes/notes/fix-controlflow-builder-nested-switch-008b8c43b2153a1f.yaml, test/python/circuit/test_control_flow_builders.py
This is generally relatively straightforwards; anywhere where we examine the resources used by an operation, we need to update to account for classical resources potentially being tied up in `ControlFlowOp` fields in `Expr` nodes as well.
This also has the side effect of fixing a bug where a nested `SwitchCaseOp.target` wasn't considered in the scope building for _all_ control-flow operations, which could incorrectly cause some registers to be missed in outer scopes.
Fix #10398.
Close #10228.
Depends on #10367.
Additional feature changelog in #10331.
=> Add `Expr` support to the control-flow builders

qiskit/dagcircuit/dagcircuit.py, test/python/dagcircuit/test_dagcircuit.py
Control-flow operations might not include their classical resources in their `cargs` fields while in the `DAGCircuit` form (since the resources have no particular order, and are inherent to the operation), so we needed to update the logic of the `wire_pos_map` sorter to have a way to specify that some bits need not be present in the output.
Close #10231.  Depends on #10377.
=> Add `Expr` support to `DAGCircuit.replace_block_with_node`

qiskit/dagcircuit/dagcircuit.py, releasenotes/notes/dag-substitute-node-propagate-condition-898052b53edb1f17.yaml, test/python/dagcircuit/test_dagcircuit.py
As part of this minor refactor, this updates the logic to no longer silently override conditions on the replacement `op`.  The method gains a `propagate_condition` argument analogous to the same argument in `substitute_node_with_dag`, which can be set `False` to specify that the caller is aware that the new operation should implement the same conditional logic.
Close #10380.  Depends on #10377.  This has a partial changelog of itself, but the rest is coming in #10331.
=> Add `Expr` support in `DAGCircuit.substitute_node`

qiskit/dagcircuit/dagcircuit.py, test/python/dagcircuit/test_dagcircuit.py
Most of this was automatically upgraded during the switchover of `DAGCircuit.compose` to use the same general variable-remapping forms that `QuantumCircuit.compose` does.  The remaining piece is to skip attempting to propagate the condition onto the subnodes; that is legacy behaviour from an old model of treating conditions as some "extra" to an operation, and not an inherent component of what was being applied.
Resolve #10379.  Depends on #10377.
=> Add `Expr` support to `DAGCircuit.substitute_node_with_dag`

qiskit/circuit/classical/expr/constructors.py, test/python/circuit/classical/test_expr_constructors.py
This expands the inference on integer widths that was previously only done in the bitwise operations to all binary operations, to reduce the number of cast nodes that will be inserted.  This is mostly a quality-of-life improvement (for us as well), because there's not really a need to include casts when we could just have our integer literals start off at the correct size.
In the immediate term, this is useful for OpenQASM 3 export for the IBM QSS stack, which doesn't support explicit casting yet.
This turned up during my testing of our capabilities against the QSS stack.
=> Expand `Expr` integer type-width inference to all binary operations

qiskit/transpiler/target.py, releasenotes/notes/fix-update-from-instruction-schedule-map-d1cba4e4db4b679e.yaml, test/python/transpiler/test_target.py
Update_from_instruction_schedule_map failed when the duration of schedules is treated as a parameter.
I added try.. except statement and set duration `None` when the duration is the parameter.
=> Fix UnassignedDurationError of update_from_instruction_schedule_map

azure-pipelines.yml
We no longer need to be running nightly CI on the 0.23.x series, since it is no longer supported.
=> Disable cron runs on `stable/0.23`

azure-pipelines.yml
We no longer need to be running nightly CI on the 0.24.x series, since it is no longer supported.
=> Disable cron runs on `stable/0.24`

docs/_templates/autosummary/class.rst, docs/_templates/autosummary/class_no_inherited_members.rst, qiskit/algorithms/optimizers/nft.py, qiskit/providers/backend.py
Currently, methods have their own HTML page. This PR changes them to live on the class page.
Motivations:
1. Speed up our docs build. Before: 8 minutes, 20 seconds. After: 4 minutes, 30 seconds.
2. Better user experience. While it's true we sometimes have very long method entries, most of our methods are small and it's a frustrating user experience to have to change pages so much. Compare this to e.g. Python docs, where the entire module is documented on a single page. An IBM design team suggested we make this change.
A follow-up will move functions to their module page, rather than dedicated pages.
We decided it's not worth adding redirects for method pages. Sphinx will already properly update all cross-references to the right place, and we don't expect there to be many external links to …
=> Methods are documented on class pages

qiskit/visualization/circuit/matplotlib.py
Switch to using NodeData class
Following on #10207 and from a suggestion by @jakelishman, this PR switches to using a NodeData class for storing data used in the drawing elements of a circuit and keyed on the node id. So a previous use such as `node_data[node]["width"]` is now `node_data[node].width`. This improves the readability of the code, provides for descriptions of the attributes in one place, and allows removal of several initialization checks.
=> Structural change to mpl circuit drawer to use class NodeData

qiskit/pulse/channels.py, releasenotes/notes/channel-validation-bug-fix-c06f8445cecc8478.yaml, test/python/pulse/test_channels.py
Fix a bug in the validation of Pulse channel index.
Fix #10475
=> Fix Pulse channel index validation

qiskit/circuit/__init__.py, qiskit/circuit/controlflow/switch_case.py
The class page for the `SwitchCaseOp` had some broken hyperlinks, and the documentation of the switch `CASE_DEFAULT` object was broken.  This fixes both, and adds some more explicit examples of usage of the `CASE_DEFAULT` object, with some overlap of what was already in `QuantumCircuit.switch`.
Fix #10458
=> Fix documentation of `SwitchCaseOp`

crates/qasm2/src/parse.rs, qiskit/circuit/quantumcircuit.py, releasenotes/notes/qasm2-fix-zero-op-barrier-4af211b119d5b24d.yaml, test/python/circuit/test_circuit_qasm.py, test/python/qasm2/test_parse_errors.py
The new parser would allow a `barrier;` statement, implicitly broadcasting it across all qubits in scope.  This is technically not supported by the OpenQASM 2 specification, but is a useful quality-of-life extension to the specification (in the same way that Qiskit interprets barriers, and the OpenQASM 3 specification defines the `barrier;` statement).  The precise rule is added to the new parser's `strict` mode.
The OpenQASM 2 _exporter_ similarly should not have been putting out `barrier;` statements.  These could only occur in Qiskit when a barrier was explicitly constructed with zero elements (as opposed to the call `QuantumCircuit.barrier()`, which has the all-in-scope behaviour), and consequently have no actual meaning or effect.  The exporter is modified to simply skip such …
=> Fix empty-barrier handling in OpenQASM 2

qiskit/tools/jupyter/version_table.py
After merging https://github.com/Qiskit/qiskit-terra/pull/10242, the current magic looks like this:
With this PR, it looks like this:
=> Improve `%qiskit_version_table` Jupyter magic

qiskit/circuit/commutation_checker.py, releasenotes/notes/add-limits-in-commutation-checker-66a1b9e90921621f.yaml, test/python/circuit/test_commutation_checker.py
Fixes #10488.
The matrix-based commutativity check in `CommutationChecker` requires to construct `2^N x 2^N` matrices, leading to memory problems when `N` is large. 
I have added a new argument `max_num_qubits` to `CommutationChecker::commute` that allows to skip the commutativity check if the number of qubits of either operation exceeds this amount.
Note that simpler versions of the commutativity check not involving matrix multiplication continue to work as before (e.g., two quantum operations over disjoint sets of qubits commute regardless of the number of qubits).
This actually changes the behavior of commutation checking when the number of qubits is in the range from 4 to 12 (when the matrices could be constructed and multiplied). However personally I don't think we will be missing a …
=> limiting matrix-based commutativity check

qiskit/circuit/library/evolved_operator_ansatz.py, qiskit/circuit/library/n_local/efficient_su2.py, qiskit/circuit/library/n_local/excitation_preserving.py, qiskit/circuit/library/n_local/n_local.py, qiskit/circuit/library/n_local/qaoa_ansatz.py, qiskit/circuit/library/n_local/real_amplitudes.py, qiskit/circuit/library/n_local/two_local.py
Fixes #10456 and generally use `collections.abc` over `typing`.
Also makes the docs more consistent by removing the first line of the `__init__` doc and the `TODO` in the Examples section (tracked in #10480).
=> Consistent typehints for ``NLocal`` family

qiskit/transpiler/passes/routing/stochastic_swap.py, test/python/transpiler/test_stochastic_swap.py
This was mostly already there (and why I had missed problems when testing before), the missing piece was just for `switch` statements. This commit also adds some final tests of the pass.
Changelog from #10331.
=> Add full `Expr` support to `StochasticSwap`

qiskit/transpiler/passes/routing/sabre_swap.py, test/python/transpiler/test_sabre_swap.py
This also fixes a small bug with the general control-flow handling, where a `SwitchCaseOp` would not have its classical wires respected, which left it possible to be routed out-of-order.
Fix #10232.  Feature changelog via #10331.  No changelog for the bugfix because it was unreleased as yet.
=> Add tests of `Expr` support through `SabreSwap`

qiskit/circuit/quantumcircuit.py, qiskit/visualization/circuit/_utils.py, qiskit/visualization/circuit/circuit_visualization.py, qiskit/visualization/circuit/latex.py, qiskit/visualization/circuit/matplotlib.py, qiskit/visualization/circuit/text.py
This at least causes the circuit visualisers to not crash when encountering an `Expr` node, and instead emit a warning and make a best-effort attempt (except for LaTeX) to output _something_.  We intend to extend the capabilities of these drawers in the future.
This is not an ideal situation, and I've not written any tests really because there's not really much to test here.  The intent is just to improve the situation beyond a crash to a warning that something's amiss, and display _something_.  We're hoping to add more complete support later.
=> Make circuit drawers *not crash* on `Expr` nodes

qiskit/circuit/tools/pi_check.py, releasenotes/notes/qasm2-float-decimal-76b44281d9249f7a.yaml, test/python/circuit/test_circuit_qasm.py
The letter of the OpenQASM 2 specification has a regex defining floating-point literals that requires a decimal point, even in the presence of an exponential component.  This is unusual for most programming languages, but Qiskit's exporter should follow the spec as close as we can to increase interop.  Our parser accepts floats with an exponent and no decimal point as a minor syntax extension, unless in strict mode.
Fix #10531.
=> Force decimal points in OpenQASM 2 floats

qiskit/transpiler/passes/scheduling/dynamical_decoupling.py
It fixes #10442
Replaced `DynamicalDecouplingPadding` to `PadDynamicalDecoupling`.
=> Fixed  qiskit.transpiler.passes.DynamicalDecoupling depreciation note

qiskit/circuit/library/phase_estimation.py
The previous Qiskit textbook URL referenced in the phase estimation docstring is no longer reachable. This commit updates the URL to point to the current location of the relevant textbook recourse.
Resolves #10535
No functional code changes; only the docstring was changed.
Old URL: https://qiskit.org/textbook/ch-algorithms/quantum-phase-estimation.html
New URL: https://learn.qiskit.org/course/ch-algorithms/quantum-phase-estimation
=> Update deprecated textbook URL in phase estimation docstring

docs/conf.py
We only use Google-style docstrings, so disabling the Numpy-style parsing gives us a bit of speed boost in the documentation build.  More importantly, it fixes an issue where headings whose names clashed with a specially handled keyword such as
Examples
========
used in module-level documentation as true sections would get translated into `rubric` elements, so would lose their section-heading status, confusing the toctree structure and the output display.
I noticed this in the `qiskit.qasm2` module-level documentation, but it's possible that it appeared elsewhere as well.
At the time of writing, see [the built documentation for `qiskit.qasm2`](https://qiskit.org/documentation/apidoc/qasm2.html).  The section heading "Examples" is correct in the source code, but has not produced a proper …
=> Disable Numpy-style docstring handling in Napoleon

qiskit/qpy/binary_io/circuits.py, releasenotes/notes/fix-qpy-nested-custom-controlled-2a23dfe828bc46c8.yaml, test/python/circuit/test_circuit_load_from_qpy.py
When a circuit contained multiple custom controlled gates that in turn had custom definitions, the QPY serialisation could fail to write out some of the inner instructions correctly.  This led to an invalid QPY file that could not be read back.
Fix #9746.
=> Fix multiple nested custom controlled gates in QPY

.azure/docs-linux.yml, .azure/tutorials-linux.yml, .gitignore, docs/conf.py, docs/index.rst, docs/tutorials.rst, docs/tutorials/algorithms/placeholder.ipynb, docs/tutorials/circuits/placeholder.ipynb, docs/tutorials/circuits_advanced/placeholder.ipynb, docs/tutorials/operators/placeholder.ipynb, requirements-dev.txt, requirements-tutorials.txt, tools/convert_tutorials.py, tools/execute_tutorials.py, tools/prepare_tutorials.bash, tox.ini
Implements most of https://github.com/Qiskit/qiskit-metapackage/issues/1724. 
We won't move the content of the actual tutorials over until we switch the docs deployment from qiskit-metapackage to qiskit-terra. That avoids the content living in two places and keeps one source of truth. Instead, this PR sets up all the infrastructure so that we will only need to copy over the files. 
Our docs build will use `nbsphinx_execute='never'` by default. That keeps the doc build much faster for iteration. 
Similar to qiskit-metapackage, the env var `QISKIT_DOCS_BUILD_TUTORIALS` can be used to instead re-execute the notebooks so their output is refreshed.
We want to make sure that Terra changes don't break the tutorials. So we have a CI job that executes the notebooks. It does that using `jupyter …
=> Set up infrastructure for qiskit-tutorials migration

test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py
The unit test `test_group_commuting` of `SparsePauliOp` does not check `SparsePauliOp.group_commuting(qubit_wise=True)`
https://github.com/Qiskit/qiskit-terra/blob/df2ddcadf3c6d59b8bab8b0b1ceff14234fa82b5/test/python/quantum_info/operators/symplectic/test_sparse_pauli_op.py#L947-L947
On the other hand, the unit tests of `PauliList` cover grouping of qubit-wise commuting.
https://github.com/Qiskit/qiskit-terra/blob/966aab1bb624cb45f8de77d305f5407d94dbd82d/test/python/quantum_info/operators/symplectic/test_pauli_list.py#L2096
This PR adds a unit test of `SparsePauliOp.group_commuting(qubit_wise=True)`.
=> Add a unit test of qubit-wise grouping of SparsePauliOp

qiskit/extensions/unitary.py, releasenotes/notes/unitary-u-not-u3-0a32c2d968f7890e.yaml, test/python/circuit/test_circuit_qasm.py, test/python/circuit/test_unitary.py
Replaced U3 with U gate so that when I decompose it uses U not U3 as U is the gate going forward.
=> Change 1q UnitaryGate definition to use U instead of U3

qiskit/visualization/circuit/matplotlib.py, test/visual/mpl/circuit/test_circuit_matplotlib_drawer.py
Fixes a problem where open circles were drawing incorrectly in mpl circuit drawer and ups the visual circuit tests to .9999 accuracy
A bug in the drawing of open circles for conditional gates was introduced in #10504. Circles would be drawn closed when the value was 0. The auto visual circuit tests did not detect this problem due to the accuracy being set at 99%. This also changes that accuracy to 99.99%.
=> Fix open circles drawing incorrectly in mpl drawer and up visual circuit tests to .9999 accuracy

.github/workflows/docs_deploy.yml
This commit fixes an issue in the job definition for the new docs deployment job added in #10610. The new jobs are conditioned to only execute from the Qiskit/qiskit-terra repo. However that line is being flagged as a syntax error in github. This seems to be due to the double quotes used for `"Qiskit"`. A similar condition exists on the pre-existing github actions jobs but they use a single quote instead of a double and they function correctly. This commit updates the condition to used single quotes to match the working syntax in other jobs.
=> Fix repository_owner condition docs_deploy gha job

requirements-dev.txt
The recent Sphinx 7.2 release is causing errors during docs jobs around the furo style sheet. There seems to be a compatibility issue between furo, qiskit_sphinx_theme, and this new Sphinx release. While the issue is getting resolved this commit pins the sphinx version we use in CI and for local docs builds to avoid the new release.
See https://github.com/sphinx-doc/sphinx/issues/11608 for details
=> Pin sphinx version to less than 7.2

azure-pipelines.yml
This commit fixes 3 issues identified during the 0.25.1 release. The first is that the name of the qiskit package build/publish job was invalid in azure pipelines. The `-` character is not valid and throws an error when the release is triggered. The second issue is that the qiskit package job is triggered at the same time as all the qiskit-terra package build/publish jobs. However, the qiskit package is very quick to build while the qiskit-terra jobs take some time so qiskit will be published first and qiskit-terra second. This will result in a small period when `qiskit` is uninstallable because it depends on a yet unpublished release of qiskit-terra. To address this the build artifact deployment is split into 2 stages, the first builds the qiskit-terra precompiled binary wheels and …
=> Fix release jobs post-0.25.1 release

qiskit/providers/__init__.py, qiskit/providers/backend.py, qiskit/providers/basicaer/basicaerjob.py, qiskit/providers/basicaer/qasm_simulator.py, qiskit/providers/basicaer/unitary_simulator.py, qiskit/providers/fake_provider/__init__.py, qiskit/providers/fake_provider/fake_backend.py, qiskit/providers/models/__init__.py, qiskit/providers/models/backendconfiguration.py, qiskit/providers/models/backendproperties.py, qiskit/providers/models/jobstatus.py, qiskit/providers/models/pulsedefaults.py
This fixes all the broken crossreferences in the Sphinx build of `qiskit.providers`, found by using Sphinx's nitpicky mode.  Leaving aside the errors due to attempted crossreferences to Python builtin and standard-library types (which are fixed in another commit), there were just over 500 errors in this module (the count inflated severely because of docstring inheritance) which are now all fixed.
The "other commit" alluded to in the message that fixes the builtin/standard-library types is #10523, but this PR doesn't depend on that one.
=> Fix broken documentation references in `qiskit.providers`

qiskit/circuit/parameterexpression.py, releasenotes/notes/added-sign-feature-parameterexpression-57693dd69103dc8c.yaml, test/python/circuit/test_parameters.py
Added a new feature in parameterexpression.py to display the sign of an expression
…the expression inputted
I've added a feature that allows a user to display the sign of an inputted expression using an object of the Parameter class.
=> #10360 New sign feature in parameterexpression.py

qiskit/utils/deprecation.py, qiskit/utils/units.py
Following discussion, I'm splitting https://github.com/Qiskit/qiskit-terra/pull/8187 by module.
I've moved a setter and getter to be one after another (as per https://github.com/python/mypy/issues/1465)
The are ~40 errors left:
<details>
<summary> All error list </summary>
```
qiskit/utils/measurement_error_mitigation.py:154: error: Argument "qubit_list" to "complete_meas_cal" has incompatible type "range"; expected "Optional[List[int]]"  [arg-type]
qiskit/utils/measurement_error_mitigation.py:158: error: Incompatible types in assignment (expression has type "List[List[int]]", variable has type "List[str]")  [assignment]
qiskit/utils/measurement_error_mitigation.py:174: error: Argument "qubit_list" to "complete_meas_cal" has incompatible type "range"; expected "Optional[List[int]]" …
```
=> Fix mypy errors (utils)

qiskit/transpiler/passes/scheduling/dynamical_decoupling.py, qiskit/transpiler/passes/scheduling/padding/dynamical_decoupling.py, releasenotes/notes/fix-param-global-phase-31547267f6124552.yaml, test/python/transpiler/test_dynamical_decoupling.py
It fixes #10569
Removed `_mod_2pi` function.
It is similiar to Qiskit/qiskit-ibm-provider#689
=>  Removed 2pi wrapping for global phase parameter

crates/accelerate/src/sabre_swap/mod.rs
When building the extended set, the current traversal order uses a BFS of _all_ nodes as they become unblocked. This means that the order in which we encounter 2Q operations isn't necessarily the ones closest to inclusion in the front layer first. Since we limit the size of the extended set, operations that are closer to the front layer might not actually be included.
To fix this, we change the traversal order to visit non-2Q nodes (namely, 1Q gates and control flow ops) as soon as they're unblocked. Otherwise, we do the original BFS. This way, we get a BFS specifically of 2Q nodes as they become unblocked.
Here's an example of the traversal orders before and after this PR for a 4 qubit circuit with a run of 1Q H gates, where the extended set is limited to size 4.
The magenta arrows show …
=> Fix Sabre extended set population order

qiskit/circuit/library/standard_gates/x.py, releasenotes/notes/mcxvchain_dirty_auxiliary-5ea4037557209f6e.yaml, test/python/circuit/test_controlled_gate.py
Implementation of MCX with $k$ controls and $k - 2$ dirty auxiliary qubits following the optimizations described by Iten et al. in [1].
[1] http://arxiv.org/abs/1501.06911
The changes made to the MCXVChain class only affect the dirty_ancilla mode. This implementation produces MCX circuits with at most $8k - 6$ CNOTs with $k$ control qubits. It also addresses issue #5872 and is a necessary step to further improve PR #8710.
=> Improved MCXVChain with dirty auxiliary qubits
